### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by jaxcore** [nodejs/node-gyp#100]
I'm trying to get the sqlite3 node module to work on iOS.  I'm running into some gcc-related configuration problems.  Here's what happens when I run node-gyp build on the sqlite package:

```
iPod-touch:/var/mobile/sqlite3 root# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.5.7
gyp info using node@0.6.14
gyp make: Entering directory `/private/var/mobile/sqlite3/build'
info  CC(target) Release/obj.target/sqlite3/deps/sqlite3/sqlite3.o
 spawn make
cc1: error: unrecognized command line option "-arch"
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** [Release/obj.target/sqlite3/deps/sqlite3/sqlite3.o] Error 1
make: Leaving directory `/private/var/mobile/sqlite3/build'
gyp ERR! build error Error: `make` failed with exit code: 2
gyp ERR! build error     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:215:23)
gyp ERR! build error     at ChildProcess.emit (events.js:70:17)
gyp ERR! build error     at maybeExit (child_process.js:360:16)
gyp ERR! build error     at Process.onexit (child_process.js:396:5)
gyp ERR! not ok 
```

This line is the hint:

```
cc1: error: unrecognized command line option "-arch"
```

I think somewhere in node-gyp the architecture needs to support armv5... this is just a guess.  Any help would be appreciated.

**Comment by Trott** [comment]
I have to imagine this update has happened by now, but since I don't know.... @nodejs/node-gyp

**Comment by rvagg** [comment]
closing due to staleness
