### ISSUE TITLE
error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers

### ISSUE THREAD

**Issue by naveend915** [nodejs/node-gyp#1011]
I am getting the below error message

```
21>C:\Development\path\node_modules\node-gyp\
21>src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition
21>; different type modifiers [C:\Development\path
21>\node_modules\node-sass\build\binding.vcxproj]
gyp ERR! build error 
21>EXEC : gyp ERR! stack error : `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.
21>exe` failed with exit code: 1
21>  gyp ERR! stack     at ChildProcess.onExit (C:\Development\path
21>  \node_modules\node-gyp\lib\build.js:276:23)
21>  gyp ERR! stack     at emitTwo (events.js:87:13)
21>  gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
21>  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_pro
21>  cess.js:200:12)
21>  gyp ERR! System Windows_NT 6.1.7601
21>  gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Development\\
21>  path\\node_modules\\node-gyp\\bin\\node-g
21>  yp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_
21>  ldflags=" "--libsass_library="
21>  gyp ERR! cwd C:\Development\path\node_mo
21>  dules\node-sass
21>  gyp ERR! node -v v4.5.0
21>  gyp ERR! node-gyp -v v3.2.1
21>  gyp ERR! not ok 
21>  Build failed
21>  
21>  npm ERR! Windows_NT 6.1.7601
21>  npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nbk\\AppData\
21>  \Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "node-sass"
21>  npm ERR! node v4.5.0
21>  npm ERR! npm  v3.10.7
21>  npm ERR! code ELIFECYCLE
21>  npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
21>  npm ERR! Exit status 1
21>  npm ERR! 
21>  npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build
21>  .js'.
21>  npm ERR! Make sure you have the latest version of node.js and npm installed.
21>  npm ERR! If you do, this is most likely a problem with the node-sass package,
21>  npm ERR! not with npm itself.
21>  npm ERR! Tell the author that this fails on your system:
21>  npm ERR!     node scripts/build.js
21>  npm ERR! You can get information on how to open an issue for this project wit
21>  h:
21>  npm ERR!     npm bugs node-sass
21>  npm ERR! Or if that isn't available, you can get their info via:
21>  npm ERR!     npm owner ls node-sass
21>  npm ERR! There is likely additional logging output above.
21>  
21>  npm ERR! Please include the following file with any support request:
21>  npm ERR!     C:\Development\path\npm-deb
21>  ug.log
```

tried with these things as mentioned in https://github.com/nodejs/node-gyp/issues/972
npm -g install npm@next

but still getting issue. Is there a work around please let me know ?
[npm-debug.txt](https://github.com/nodejs/node-gyp/files/434146/npm-debug.txt)

**Comment by bnoordhuis** [comment]
Try npm@latest.  In a nutshell, node-gyp should be v3.4.0 or newer.  You're currently running v3.2.1.

**Comment by naveend915** [comment]
@bnoordhuis this worked thanks a lot :+1:
