### ISSUE TITLE
node-gyp rebuild fails on macOS sierra

### ISSUE THREAD

**Issue by ahcarpenter** [nodejs/node-gyp#1027]
```  
CXX(target) Release/obj.target/validation/src/validation.o
../src/validation.cc:15:10: fatal error: 'nan.h' file not found
#include "nan.h"
         ^
1 error generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/drew/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Users/drew/.nvm/versions/node/v5.1.0/bin/node" "/Users/drew/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/drew/Dropbox/workspace/Web_Applications/fooji/Ooji-Front-Ends/pitch/node_modules/auto-reload-brunch/node_modules/utf-8-validate
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

any thoughts?

**Comment by bnoordhuis** [comment]
Yes, install nan.  Note that node.js v5.1.0 is obsolete, consider upgrading to the latest v6.x.
