### ISSUE TITLE
python.EXE is v3.5.2, which is not supported by gyp

### ISSUE THREAD

**Issue by qt3m45su0najc7** [nodejs/node-gyp#1042]
``` batchfile

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\tomas_brand\AppData\Local\Programs\Python\Python35-32\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\tomas_brand\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\tomas_brand\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\tomas_brand\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\WINDOWS\system32
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by bnoordhuis** [comment]
What is your question?

**Comment by bnoordhuis** [comment]
No follow-up, closing.

**Comment by JoeyAcc** [comment]
I don't know about the OP but yeah it'd be good if gyp made the switch to Python3.

**Comment by SoulFireMage** [comment]
It'd be very good, as this is roadblocking us on our site trying to use Nimvelo.

**Comment by bnoordhuis** [comment]
A switch to python3 is unlikely to happen anytime soon but see https://github.com/nodejs/node-gyp/pull/1092.
