### ISSUE TITLE
Error: Cannot find module 'shrink-ray'

### ISSUE THREAD

**Issue by HectorRPL** [nodejs/node-gyp#1052]
Hello
I have Windows 8.1
I follow the guide, but the first time that I put `gulp serve` the console sendme this error.

```
Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:/a1/rhane/web/yeoman/rhane-web_v2.0/server/config/express.js:10:1)
    at Module._compile (module.js:413:34)
    at loader (C:\a1\rhane\web\yeoman\rhane-web_v2.0\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\a1\rhane\web\yeoman\rhane-web_v2.0\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:/a1/rhane/web/yeoman/rhane-web_v2.0/server/app.js:28:1)
    at Module._compile (module.js:413:34)
    at loader (C:\a1\rhane\web\yeoman\rhane-web_v2.0\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\a1\rhane\web\yeoman\rhane-web_v2.0\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\a1\rhane\web\yeoman\rhane-web_v2.0\server\index.js:12:28)
    at Module._compile (module.js:413:34)
 [nodemon] app crashed - waiting for file changes before starting...
```

¿Any Ideas?
Thanks for your time

**Comment by bnoordhuis** [comment]
Wrong repo?  I don't understand what any of that has to do with node-gyp.

**Comment by HectorRPL** [comment]
Sorry!
I puted the question in wrong page
I will delete this post
