### ISSUE TITLE
node-gyp configure fails

### ISSUE THREAD

**Issue by vihanb** [nodejs/node-gyp#1062]
I've been attempting to make a simple app utilizing node-gyp, however whenever I run `node-gyp configure` , it throws a python error:

```
gyp info spawn args   '-I',
gyp info spawn args   '/Users/me/Documents/Code/node-gyp-test-app/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/me/.node-gyp/7.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/me/.node-gyp/7.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/me/Documents/Code/node-gyp-test-app',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 413, in LoadTargetBuildFile
    ProcessToolsetsInDict(build_file_data)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 335, in ProcessToolsetsInDict
    toolsets = target.get('toolsets', ['target'])
AttributeError: 'str' object has no attribute 'get' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/me/Documents/Code/node-gyp-test-app
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

It does however successfully create this file (`build/config.gypi`):

```
# Do not edit. File was generated by node-gyp's "configure" step
{
  "target_defaults": {
    "cflags": [],
    "default_configuration": "Release",
    "defines": [],
    "include_dirs": [],
    "libraries": []
  },
  "variables": {
    "asan": 0,
    "debug_devtools": "node",
    "force_dynamic_crt": 0,
    "host_arch": "x64",
    "icu_data_file": "icudt58l.dat",
    "icu_data_in": "../../deps/icu-small/source/data/in/icudt58l.dat",
    "icu_endianness": "l",
    "icu_gyp_path": "tools/icu/icu-generic.gyp",
    "icu_locales": "en,root",
    "icu_path": "deps/icu-small",
    "icu_small": "true",
    "icu_ver_major": "58",
    "llvm_version": 0,
    "node_byteorder": "little",
    "node_enable_d8": "false",
    "node_enable_v8_vtunejit": "false",
    "node_install_npm": "true",
    "node_module_version": 51,
    "node_no_browser_globals": "false",
    "node_prefix": "/usr/local",
    "node_release_urlbase": "https://nodejs.org/download/release/",
    "node_shared": "false",
    "node_shared_cares": "false",
    "node_shared_http_parser": "false",
    "node_shared_libuv": "false",
    "node_shared_openssl": "false",
    "node_shared_zlib": "false",
    "node_tag": "",
    "node_use_bundled_v8": "true",
    "node_use_dtrace": "true",
    "node_use_etw": "false",
    "node_use_lttng": "false",
    "node_use_openssl": "true",
    "node_use_perfctr": "false",
    "node_use_v8_platform": "true",
    "openssl_fips": "",
    "openssl_no_asm": 0,
    "shlib_suffix": "51.dylib",
    "target_arch": "x64",
    "uv_parent_path": "/deps/uv/",
    "uv_use_dtrace": "true",
    "v8_enable_gdbjit": 0,
    "v8_enable_i18n_support": 1,
    "v8_inspector": "true",
    "v8_no_strict_aliasing": 1,
    "v8_optimized_debug": 0,
    "v8_random_seed": 0,
    "v8_use_snapshot": "true",
    "want_separate_host_toolset": 0,
    "want_separate_host_toolset_mkpeephole": 0,
    "xcode_version": "7.0",
    "nodedir": "/Users/me/.node-gyp/7.1.0",
    "copy_dev_lib": "true",
    "standalone_static_library": 1
  }
}
```
Python version has been set to `2.7.12` and I've updated both node (tried v4 & v6 & v7) and node-gyp

**Comment by bnoordhuis** [comment]
Can you post your binding.gyp?

**Comment by vihanb** [comment]
@bnoordhuis sure:

```
{
    "targets": {
        "target_name": "node-gyp-test-app",
        "sources": [
            "node-gyp-test-app.cc"
        ]
    }
}

```

`node-gyp-test-app.cc` is in the same directory as the binding and all too

**Comment by bnoordhuis** [comment]
You have a bug in your binding.gyp, it should look like this:
```python
{
  'targets': [  # Note the [ { vs. just { in your file.
    {
      'target_name': 'addon',
      'sources': [ ... ],
    }
  ]
}
```

**Comment by DevinXian** [comment]
> You have a bug in your binding.gyp, it should look like this:
> 
> ```python
> {
>   'targets': [  # Note the [ { vs. just { in your file.
>     {
>       'target_name': 'addon',
>       'sources': [ ... ],
>     }
>   ]
> }
> ```

Saved my time, thanks!
