### ISSUE TITLE
how to solve npm install command please help me i am new

### ISSUE THREAD

**Issue by addikhann** [nodejs/node-gyp#1082]
i want to learn node js and my boss send me this project but its show error. how to solve this type of problem when i enter npm install this command is show below error...i already installed visual studio 2015
```

gyp ERR! stack operable program or batch file.
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:134:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:5)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin
\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Addi\Server\node_modules\iltorb
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by joaocgreis** [comment]
Please make sure you have **Visual C++** installed. You can go to Control Panel, Uninstall a Program, select Microsoft Visual Studio 2015 and click Change. There, modify the installation and make sure Visual C++ is selected under Programming Languages. Please reboot before trying to npm install again.
