### ISSUE TITLE
Can't build via npm: gyp failed with exit code 1

### ISSUE THREAD

**Issue by guymorita** [nodejs/node-gyp#1083]
Hey guys,

I've searched far and wide for fixes and tried lots of stuff. Is there something I'm missing with how to configure node-gyp?
```
guys-mbp:benchmark_raccoon_movielens guymorita$ node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guymorita/Projects/benchmark_raccoon_movielens/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guymorita/.node-gyp/7.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/guymorita/.node-gyp/7.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/guymorita/Projects/benchmark_raccoon_movielens',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/guymorita/Projects/benchmark_raccoon_movielens) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/guymorita/Projects/benchmark_raccoon_movielens
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
Here is my setup:
```
guys-mbp:benchmark_raccoon_movielens guymorita$ sw_vers -productVersion
10.10.5
guys-mbp:benchmark_raccoon_movielens guymorita$ node -v
v7.3.0
guys-mbp:benchmark_raccoon_movielens guymorita$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
I have already tried:
```
deleting dir ~/.node_gyp and running npm install
```
```
sudo npm install -g node-gyp@3.4.0
```
```
cd /usr/local/lib sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib 
```
```
brew install gcc
```
```
sudo npm cache clean -f
sudo npm install -g n
sudo n 4.4.5
sudo npm install npm -g
sudo npm uninstall node-gyp -g
```
Thanks!

**Comment by cyberphantom** [comment]
Hi,
Did you find any solution, I have same issue on windows

Thanks,

**Comment by guymorita** [comment]
Nope. But I used a different module that didn't need it.

**Comment by hogansung** [comment]
@guymorita, I encountered the same issue as you. Do you have any solution for it?

**Comment by refack** [comment]
> @guymorita, I encountered the same issue as you. Do you have any solution for it?

`node-gyp` doesn't need to be called directly (unless you are compiling an addon you are writing yourself), it is called by `npm` when installing dependencies that require compiling.

If you are writing your own addon you will require a `binding.gyp` file that has instructions on how to scaffold the build process.

**Comment by danillotorresdev** [comment]
I solved this issue by keeping the default importer of create-react-app "bcrypt": "^ 1.0.2" in package.json
