### ISSUE TITLE
error during build of node-posix on OSX v10.12.01 node v6.9.4 

### ISSUE THREAD

**Issue by evaisse** [nodejs/node-gyp#1089]
Cannot install nor `node-posix` nor `node-iconv` since homebrew update.

```
$> V=1 npm install posix

> posix@1.0.4 install /Users/evaisse/Sites/web-es-streaming-01/node_modules/posix
> node-gyp rebuild

  c++ '-DNODE_GYP_MODULE_NAME=posix' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/evaisse/.node-gyp/6.9.4/include/node -I/Users/evaisse/.node-gyp/6.9.4/src -I/Users/evaisse/.node-gyp/6.9.4/deps/uv/include -I/Users/evaisse/.node-gyp/6.9.4/deps/v8/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/posix/src/posix.o.d.raw   -c -o Release/obj.target/posix/src/posix.o ../src/posix.cc
../src/posix.cc:16:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> node_getppid(const Arguments& args) {
                                        ^~~~~~~~~
                                        v8::internal::Arguments

(...)
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/posix/src/posix.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/Cellar/node@6/6.9.4/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/evaisse/Sites/web-es-streaming-01/node_modules/posix
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN brs-realtime-server@0.0.1 No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node@6/6.9.4/bin/node" "/usr/local/bin/npm" "i" "posix"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! posix@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@1.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs posix
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls posix
```

```
$> node-gyp -v
v3.5.0
$> node -v
v6.9.4
$> clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$> c++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$> npm -v
3.10.10
```

npm-debug.log extract 
```
126 silly install posix@1.0.4 /Users/evaisse/Sites/web-es-streaming-01/node_modules/.staging/posix-5835e366
127 info lifecycle posix@1.0.4~install: posix@1.0.4
128 verbose lifecycle posix@1.0.4~install: unsafe-perm in lifecycle true
129 verbose lifecycle posix@1.0.4~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/evaisse/Sites/web-es-streaming-01/node_modules/posix/node_modules/.bin:/Users/evaisse/Sites/web-es-streaming-01/node_modules/.bin:/usr/local/Cellar/node@6/6.9.4/bin:/usr/local/sbin:/Users/evaisse/.composer/vendor/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
130 verbose lifecycle posix@1.0.4~install: CWD: /Users/evaisse/Sites/web-es-streaming-01/node_modules/posix
131 silly lifecycle posix@1.0.4~install: Args: [ '-c', 'node-gyp rebuild' ]
132 silly lifecycle posix@1.0.4~install: Returned: code: 1  signal: null
133 info lifecycle posix@1.0.4~install: Failed to exec install script
134 verbose unlock done using /Users/evaisse/.npm/_locks/staging-7f6a39ed60e31134.lock for /Users/evaisse/Sites/web-es-streaming-01/node_modules/.staging

```

strangely, global install of node posix works like a charm 

```
$> npm install -g posix
\
> posix@4.1.1 install /usr/local/Cellar/node@4/4.7.2/libexec/npm/lib/node_modules/posix
> node-gyp rebuild

  CXX(target) Release/obj.target/posix/src/posix.o
  SOLINK_MODULE(target) Release/posix.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
posix@4.1.1 /usr/local/Cellar/node@4/4.7.2/libexec/npm/lib/node_modules/posix
└── nan@2.4.0
```

**Comment by bnoordhuis** [comment]
Not a node-gyp bug.  You are trying to install a module that was written for an old node.js version.  Note the version numbers of the module: posix@1.0.4 vs. posix@4.1.1.
