### ISSUE TITLE
can't build bcrypt with node 7 (TypeError: Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by dwieeb** [nodejs/node-gyp#1090]
bcrypt 1.0.2 installation fails in node 7 (linux), but works in node 6

```
root@faef11ca52bd:/usr/src/app# npm install bcrypt                    
npm info it worked if it ends with ok
npm info using npm@4.0.5
npm info using node@v7.4.0
npm info attempt registry request try #1 at 8:25:03 AM
npm http request GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm info attempt registry request try #1 at 8:25:04 AM
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm info lifecycle bcrypt@1.0.2~preinstall: bcrypt@1.0.2
npm info linkStuff bcrypt@1.0.2
npm info lifecycle bcrypt@1.0.2~install: bcrypt@1.0.2

> bcrypt@1.0.2 install /usr/src/app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@7.4.0 | linux | x64
node-pre-gyp info check checked for "/usr/src/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v51-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v51-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.4.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.4.0 | linux | x64
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Cannot read property 'length' of undefined
gyp ERR! stack     at parse (/usr/src/app/node_modules/semver/semver.js:239:14)
gyp ERR! stack     at Function.valid (/usr/src/app/node_modules/semver/semver.js:255:11)
gyp ERR! stack     at processRelease (/usr/src/app/node_modules/node-gyp/lib/process-release.js:16:25)
gyp ERR! stack     at configure (/usr/src/app/node_modules/node-gyp/lib/configure.js:35:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/usr/src/app/node_modules/node-gyp/lib/node-gyp.js:55:37)
gyp ERR! stack     at run (/usr/src/app/node_modules/node-gyp/bin/node-gyp.js:87:30)
gyp ERR! stack     at Object.<anonymous> (/usr/src/app/node_modules/node-gyp/bin/node-gyp.js:148:1)
gyp ERR! stack     at Module._compile (module.js:571:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
gyp ERR! stack     at Module.load (module.js:488:32)
gyp ERR! System Linux 4.8.13-1-ARCH
gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/src/app/node_modules/bcrypt
/lib/binding"
gyp ERR! cwd /usr/src/app/node_modules/bcrypt
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/src/app
/node_modules/bcrypt/lib/binding' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.8.13-1-ARCH
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/src/app/node_modules/bcrypt
node-pre-gyp ERR! node -v v7.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/src/app/node_modules/bcrypt/lib/bindin
g' (7)
npm info lifecycle bcrypt@1.0.2~install: Failed to exec install script
```

**Comment by bnoordhuis** [comment]
Are your node and node-gyp from the arch repos?  I ask because the line numbers from the stack trace don't match up with the official release, which probably means you have incompatible modules.  You should report that to the maintainers of the arch packages.

If you can reproduce with a release from https://nodejs.org/, please post the output.

**Comment by dwieeb** [comment]
My apologies--I had foolishly created a docker volume that had `node_modules` linked between my arch computer and ubuntu container. I'm an idiot.

Thank you so much for the immediate, insightful response!
