### ISSUE TITLE
Creating native addon that uses a static library on windows 10 uwp api

### ISSUE THREAD

**Issue by jackwzp** [nodejs/node-gyp#1097]
Hi,

I want to expose the functionalities in a C++ <SomeLibrary>.lib to JS, so I decided to write a native addon that is essentially a wrapper. However, this static library is a Universal Windows 10 Static Library. I believe this means that the consumer of this library can only build UWP Apps with this library. 

I'm able to build the addon but when I try to run a simple test.js, I get this error:
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Jack\Documents\code\myaddon\build\Release\addon.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jack\Documents\code\myaddon\test.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

This is my bindings.gyp

```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "example.cc", 'cpp_bridge.cpp' ],
      'include_dirs': [
        'uwpstaticlib/include',
      ],      
      'libraries': [
        'uwpstaticlib/libtest-uwp.lib'
      ],

      # Add these lines and to get rid of linker warnings and makes things work
      'msvs_settings': {
        'VCCLCompilerTool': {
            'AdditionalOptions': [
                '/GR',
                '/MD',
                '/EHsc'
            ]
        }
      },
    }
  ]
}
```

**Comment by bzoz** [comment]
It seems, that one can use some parts of the UWP APIs from classic desktop apps - see https://msdn.microsoft.com/en-us/library/windows/desktop/mt695951(v=vs.85).aspx and https://code.msdn.microsoft.com/windowsdesktop/Sending-toast-notifications-71e230a2. Can you verify that this is a node/node-gyp problem? Or maybe the init method of the DLL fails?
