### ISSUE TITLE
Can't build with node v6.9.4 / gcc 4.8.2

### ISSUE THREAD

**Issue by jadekler** [nodejs/node-gyp#1098]
This is on snapci [link to failure here](https://app.snap-ci.com/pivotal-cf/pivotal-ui/branch/development/logs/defaultPipeline/432/deploy_styleguidenew_staging?back_to=build_history) - works fine locally.

System:

- `g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)`
- `node v6.9.4`
- `npm  v3.10.10`

```
+ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global js-beautify@1.5.10 should be installed with -g
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> png-img@2.1.1 install /var/snap-ci/repo/styleguide_new/node_modules/png-img
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/var/snap-ci/repo/styleguide_new/node_modules/png-img/build'
  CC(target) Release/obj.target/libpng/third_party/libpng/png.o
/tmp/cceTDRcn.s: Assembler messages:
/tmp/cceTDRcn.s:454: Error: expecting string instruction after `rep'
/tmp/cceTDRcn.s:871: Error: expecting string instruction after `rep'
/tmp/cceTDRcn.s:2521: Error: expecting string instruction after `rep'
/tmp/cceTDRcn.s:4826: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/libpng/third_party/libpng/png.o] Error 1
make: Leaving directory `/var/snap-ci/repo/styleguide_new/node_modules/png-img/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab120.16
gyp ERR! command "/opt/local/nvm/versions/node/v6.9.4/bin/node" "/opt/local/nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/snap-ci/repo/styleguide_new/node_modules/png-img
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by jadekler** [comment]
Ditto `node 6.8.1`

**Comment by bnoordhuis** [comment]
That's not an issue with node-gyp but with the module you're trying to build or, possibly, your local toolchain (compiler, assembler, etc.)  Try opening an issue with png-img and see what they say.
