### ISSUE TITLE
Missing tmp file creation on Windows?

### ISSUE THREAD

**Issue by zbjornson** [nodejs/node-gyp#1117]
I'm working on a binding.gyp file that has an "includes" pointing to a file relative to the module root:

```gyp
{
    'includes': ['static/locations.gyp'] # just has a 'variables' block
    # ...
}
```

on Windows, during `node-gyp configure`, python complains

> OSError: [Errno 2] No such file or directory: 'D:\\git\\node-canvas\\build\\static\\locations.sln.gyp.9ntbex.tmp'

<details>
<summary>full traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2009, in GenerateOutput
    version=msvs_version)
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 213, in __init__
    self.Write()
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 241, in Write
    f = writer(self.path)
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 399, in WriteOnDiff
    return Writer()
  File "C:\Users\bjornson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 346, in __init__
    dir=os.path.split(filename)[0])
  File "D:\Python27\lib\tempfile.py", line 293, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "D:\Python27\lib\tempfile.py", line 228, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: 'D:\\git\\node-canvas\\build\\static\\locations.sln.gyp.9ntbex.tmp'
```

</details>  
  
It looks like it's expected to be creating some temp file in "build" for the included file (although I don't think `locations.sln` should be created)?

The entirety of the GYP files are [here](https://github.com/Automattic/node-canvas/pull/813/files) if needed.

**Comment by bnoordhuis** [comment]
Does renaming `locations.gyp` to `locations.gypi` work?

**Comment by zbjornson** [comment]
🏆 yes, fixes it! Thank you.
