### ISSUE TITLE
node-gyp --python doesn't work

### ISSUE THREAD

**Issue by jackjameshoward** [nodejs/node-gyp#1132]
For some reason, I run the command to set the path to python and it doesn't recognise `--python` as a command. It just returns a list of possible options. 

```
node-gyp --python K:\Program_Files\Python_2.7\python-2.7.10.amd64\python.exe

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `msbuild` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates MSVC project files for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@3.5.0  K:\Program_Files\Atom\Atom x64\resources\app\apm\bin\node_modules\node-gyp
node@4.4.5
```
What am I doing wrong?

**Comment by bnoordhuis** [comment]
You don't specify an action.  Try this:
```
node-gyp --python K:\Program_Files\Python_2.7\python-2.7.10.amd64\python.exe rebuild
```

**Comment by jackjameshoward** [comment]
It did get somewhere this time thanks. But it has thrown a few errors. 
```
K:\Program_Files\Atom\Atom x64\resources\app\apm\bin>node-gyp --python \Program_Files\Python_2.7\python-2.7.10.amd64\python.exe rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@4.4.5 | win32 | x64
gyp http GET https://nodejs.org/download/release/v4.4.5/node-v4.4.5-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v4.4.5/node-v4.4.5-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v4.4.5/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v4.4.5/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v4.4.5/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v4.4.5/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v4.4.5/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v4.4.5/win-x86/node.lib
gyp info spawn \Program_Files\Python_2.7\python-2.7.10.amd64\python.exe
gyp info spawn args [ 'K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jhoward\\.node-gyp\\4.4.5\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jhoward\\.node-gyp\\4.4.5',
gyp info spawn args   '-Dnode_gyp_dir=K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: K:\Program_Files\Atom\Atom x64\resources\app\apm\bin) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (K:\Program_Files\Atom\Atom x64\resources\app\apm\bin\node_modules\node-gyp\lib\configure.j
s:308:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "K:\\Program_Files\\Atom\\Atom x64\\resources\\app\\apm\\bin\\node.exe" "K:\\Program_Files\\Atom\\Atom x64\\resources\
\app\\apm\\bin\\node_modules\\node-gyp\\bin\\node-gyp.js" "--python" "\\Program_Files\\Python_2.7\\python-2.7.10.amd64\\python.exe" "re
build"
gyp ERR! cwd K:\Program_Files\Atom\Atom x64\resources\app\apm\bin
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
You need to be in a directory containing an add-on to build, of course.  Search for directories containing a binding.gyp file.
