### ISSUE TITLE
Nodejs.org is down

### ISSUE THREAD

**Issue by mjancarik** [nodejs/node-gyp#1146]
Hi,

We have problem with npm install if website nodejs.org is down. What can we can do for fix it? 
For example: install some package to cache.

Thanks for answer.

```
> fibers@1.0.15 install project_folder/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 response downloading https://nodejs.org/download/release/v7.7.2/node-v7.7.2-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:191:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:986:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /www/clanky/web/node_modules/fibers
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-gyp exited with code: 1

```

**Comment by bnoordhuis** [comment]
If you have the tarball cached somewhere, you can tell node-gyp to use it with the --tarball switch.  Use --nodedir if it's unpacked to a directory or it's a git checkout.
