### ISSUE TITLE
npm install of hashtable fails with "Cannot find module 'block-stream'" from node-gyp

### ISSUE THREAD

**Issue by jtrayfield** [nodejs/node-gyp#1155]
I'm having a problem doing an "npm install":

emdall:fabric-client jtray$ npm i

> hashtable@2.0.2 install /Users/jtray/git/xxx/node_modules/fabric-sdk-node/fabric-client/node_modules/hashtable
> node-gyp configure build

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'block-stream'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:469:15)
gyp ERR! stack     at Function.Module._load (module.js:417:25)
gyp ERR! stack     at Module.require (module.js:497:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/entry-writer.js:7:19)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/jtray/git/xxx/node_modules/fabric-sdk-node/fabric-client/node_modules/hashtable
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

I tried upgrading node-gyp, didn't help.

This is on OSX 10.11.6

Thanks

**Comment by jtrayfield** [comment]
reinstalling npm seems to fix the problem (see https://github.com/lovell/sharp/issues/604#issuecomment-254054741)
