### ISSUE TITLE
gyp build exception

### ISSUE THREAD

**Issue by tingyugetc** [nodejs/node-gyp#1215]
I have a project for node and opencv,however when I run `node-gyp configure build`, I have the errors: 

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.9.4 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/tingyugetc/.nvm/versions/node/v6.9.4/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tingyugetc/selfworkspace/cpp/opencv/clion_learn/node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tingyugetc/.nvm/versions/node/v6.9.4/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tingyugetc/.node-gyp/6.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tingyugetc/.node-gyp/6.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tingyugetc/.nvm/versions/node/v6.9.4/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tingyugetc/selfworkspace/cpp/opencv/clion_learn/node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/image/image.o
In file included from ../image.cpp:7:
In file included from ../../header/geometry.h:10:
In file included from /usr/local/opt/opencv3/include/opencv2/opencv.hpp:62:
In file included from /usr/local/opt/opencv3/include/opencv2/flann.hpp:48:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/flann_base.hpp:40:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/params.h:33:
/usr/local/opt/opencv3/include/opencv2/flann/any.h:58:51: error: cannot use typeid with -fno-rtti
    virtual const std::type_info& type() { return typeid(T); }
                                                  ^
/usr/local/opt/opencv3/include/opencv2/flann/any.h:268:31: error: cannot use typeid with -fno-rtti
        if (policy->type() != typeid(T)) throw anyimpl::bad_any_cast();
                              ^
/usr/local/opt/opencv3/include/opencv2/flann/any.h:268:42: error: cannot use 'throw' with exceptions disabled
        if (policy->type() != typeid(T)) throw anyimpl::bad_any_cast();
                                         ^
/usr/local/opt/opencv3/include/opencv2/flann/any.h:277:31: error: cannot use typeid with -fno-rtti
        if (policy->type() != typeid(T)) throw anyimpl::bad_any_cast();
                              ^
/usr/local/opt/opencv3/include/opencv2/flann/any.h:277:42: error: cannot use 'throw' with exceptions disabled
        if (policy->type() != typeid(T)) throw anyimpl::bad_any_cast();
                                         ^
/usr/local/opt/opencv3/include/opencv2/flann/any.h:285:34: error: cannot use typeid with -fno-rtti
        return policy->type() == typeid(anyimpl::empty_any);
                                 ^
/usr/local/opt/opencv3/include/opencv2/flann/any.h:305:34: error: cannot use typeid with -fno-rtti
        return policy->type() == typeid(T);
                                 ^
In file included from ../image.cpp:7:
In file included from ../../header/geometry.h:10:
In file included from /usr/local/opt/opencv3/include/opencv2/opencv.hpp:62:
In file included from /usr/local/opt/opencv3/include/opencv2/flann.hpp:48:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/flann_base.hpp:40:
/usr/local/opt/opencv3/include/opencv2/flann/params.h:78:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException(cv::String("Missing parameter '")+name+cv::String("' in the parameters given"));
        ^
In file included from ../image.cpp:7:
In file included from ../../header/geometry.h:10:
In file included from /usr/local/opt/opencv3/include/opencv2/opencv.hpp:62:
In file included from /usr/local/opt/opencv3/include/opencv2/flann.hpp:48:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/flann_base.hpp:41:
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:113:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Invalid index file, cannot read");
        ^
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:117:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Invalid index file, wrong signature");
        ^
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:151:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Cannot read from file");
        ^
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:160:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Cannot read from file");
        ^
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:165:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Cannot read from file");
        ^
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:176:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Cannot read from file");
        ^
/usr/local/opt/opencv3/include/opencv2/flann/saving.h:181:9: error: cannot use 'throw' with exceptions disabled
        throw FLANNException("Cannot read from file");
        ^
In file included from ../image.cpp:7:
In file included from ../../header/geometry.h:10:
In file included from /usr/local/opt/opencv3/include/opencv2/opencv.hpp:62:
In file included from /usr/local/opt/opencv3/include/opencv2/flann.hpp:48:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/flann_base.hpp:43:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/all_indices.h:38:
/usr/local/opt/opencv3/include/opencv2/flann/kmeans_index.h:372:13: error: cannot use 'throw' with exceptions
      disabled
            throw FLANNException("Unknown algorithm for choosing initial centers.");
            ^
/usr/local/opt/opencv3/include/opencv2/flann/kmeans_index.h:435:13: error: cannot use 'throw' with exceptions
      disabled
            throw FLANNException("Branching factor must be at least 2");
            ^
/usr/local/opt/opencv3/include/opencv2/flann/kmeans_index.h:536:13: error: cannot use 'throw' with exceptions
      disabled
            throw FLANNException("Number of clusters must be at least 1");
            ^
In file included from ../image.cpp:7:
In file included from ../../header/geometry.h:10:
In file included from /usr/local/opt/opencv3/include/opencv2/opencv.hpp:62:
In file included from /usr/local/opt/opencv3/include/opencv2/flann.hpp:48:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/flann_base.hpp:43:
In file included from /usr/local/opt/opencv3/include/opencv2/flann/all_indices.h:41:
/usr/local/opt/opencv3/include/opencv2/flann/hierarchical_clustering_index.h:384:13: error: cannot use 'throw' with
      exceptions disabled
            throw FLANNException("Unknown algorithm for choosing initial centers.");
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/image/image.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tingyugetc/.nvm/versions/node/v6.9.4/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/tingyugetc/.nvm/versions/node/v6.9.4/bin/node" "/Users/tingyugetc/.nvm/versions/node/v6.9.4/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/tingyugetc/selfworkspace/cpp/opencv/clion_learn/node
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
```

I donot have no idea for this, help me for thans

**Comment by bnoordhuis** [comment]
That's not an issue with node-gyp but with the add-on you are trying to build.  Are you trying to write one yourself?

The error message hints at the cause: you need to set `-frtti` in your binding.gyp, possibly `-fexceptions` as well, and maybe delete the other flags with `'cflags_cc!': ['-fno-rtti', '-fno-exceptions']`.

**Comment by tingyugetc** [comment]
@bnoordhuis hi,thank for your help that help me solve this problem.
I solve this problem with this binding.gyp

```
{
  "targets": [
    {
      "target_name": "image",
      "include_dirs": [
        "../header",
        "/usr/local/opt/opencv3/include"
      ],
      "libraries": [
        "/usr/local/opt/opencv3/lib/lib*.*"
      ],
      "sources": [
        "image.cpp"
      ],
      "cflags!" : [
        "-fno-exceptions"
      ],
      "cflags_cc!": [
        "-fno-rtti",
        "-fno-exceptions"
      ],

      "conditions": [
        [
          "OS==\"mac\"", {
            "xcode_settings": {
              "OTHER_CFLAGS": [
                "-mmacosx-version-min=10.7",
                "-std=c++11",
                "-stdlib=libc++"
              ],
              "GCC_ENABLE_CPP_RTTI": "YES",
              "GCC_ENABLE_CPP_EXCEPTIONS": "YES"
            }
          }
        ]
      ]
    }
  ]
}
```
