### ISSUE TITLE
Fails to compile with error: ZLIB_VERNUM != PNG_ZLIB_VERNUM

### ISSUE THREAD

**Issue by Flimm** [nodejs/node-gyp#1243]
I'm on macOS, I've installed Node and NPM with Homebrew.

When I try to install `lwip`, I get this error:

```
$ npm install -g lwip
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

> lwip@0.0.9 install /usr/local/lib/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
../src/decoder/buffer_worker.cpp:8:56: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    _height(0), _channels(0), _trans(false), _metadata("") {
                                                       ^
1 warning generated.
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/jpeg_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/png_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/gif_decoder.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jcomapi.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapimin.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapistd.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatadst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatasrc.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcoefct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcolor.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jddctmgr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdhuff.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdinput.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmainct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmarker.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmaster.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdpostct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdsample.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jerror.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctflt.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctfst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctint.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctflt.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctfst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctint.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jutils.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemmgr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdarith.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmerge.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jaricom.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant1.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant2.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/png.o
In file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/8.0.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/lwip
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/flimm/.npm/_logs/2017-06-23T09_46_18_775Z-debug.log
```

The most relevant line I think is this:

```
In file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
```

**Comment by bnoordhuis** [comment]
That's a problem with the module you're trying to build, not node-gyp.  I can't help but you but try filing an issue with lwip.

**Comment by Flimm** [comment]
Sorry, I meant to file this in lwip, I'm not sure how I ended up here 😕

**Comment by Flimm** [comment]
Here's the relevant issue in lwip for any lurkers: https://github.com/EyalAr/lwip/issues/297
