### ISSUE TITLE
gyp ERR! Completion callback never invoked! while installing node-sqlite3

### ISSUE THREAD

**Issue by devnewbieshere** [nodejs/node-gyp#1248]
I am getting repeatedly this error while installing node-sqlite3 package.
Could somebody help me solve?
I removed /home/..node-gyp
and reinstalled :
npm install node-pre-gyp -g
npm install -g node-gyp

but still i have the problem below when installing sqlite3.

```
$ npm install sqlite3 --build-from-source

> sqlite3@3.1.8 install /home/www/myNodeApp/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp ERR! Completion callback never invoked!
gyp ERR! System Linux 3.10.23-xxxx-std-ipv6-64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/www/myNodeApp/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/www/myNodeApp/node_modules/sqlite3/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /home/www/myNodeApp/node_modules/sqlite3
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v0.7.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/www/myNodeApp/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/www/myNodeApp/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (6)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/www/myNodeApp/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 3.10.23-xxxx-std-ipv6-64
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/www/myNodeApp/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/www/myNodeApp/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/www/myNodeApp/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/www/myNodeApp/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (6)
npm WARN myApp@1.0.0 No repository field.
npm ERR! Linux 3.10.23-xxxx-std-ipv6-64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/www/myNodeApp/npm-debug.log
```

**Comment by bnoordhuis** [comment]
Upgrade your copy of node-gyp.  v0.7.0 is really ancient, v3.6.2 is the latest.

**Comment by jonatzipwhip** [comment]
this issue appears to have appeared again, running that I think is latest node-gyp.
```
➜  github docker create -t -i node:alpine sh
2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
➜  github docker start -a -i 2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
/ # apk add python; npm install node-gyp -g; node-gyp rebuild
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libbz2 (1.0.6-r7)
(2/10) Installing expat (2.2.8-r0)
(3/10) Installing libffi (3.2.1-r6)
(4/10) Installing gdbm (1.13-r1)
(5/10) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(6/10) Installing ncurses-terminfo (6.1_p20190105-r0)
(7/10) Installing ncurses-libs (6.1_p20190105-r0)
(8/10) Installing readline (7.0.003-r1)
(9/10) Installing sqlite-libs (3.28.0-r0)
(10/10) Installing python2 (2.7.16-r1)
Executing busybox-1.29.3-r10.trigger
OK: 54 MiB in 26 packages
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@5.0.3
added 98 packages from 67 contributors in 5.427s
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.10.0 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.10.0/node-v12.10.0-headers.tar.gz
gyp ERR! Completion callback never invoked!
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     https://github.com/nodejs/node-gyp/issues
/ # node-gyp -v
v5.0.3
/ # %                                                                                                                                                                   ➜  github docker rm 2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
2ef1684afc1f3ac57c713fbe313b7f7e0a0f1686c8680c2712a7d3c7acc6a20a
➜  github
```
any thoughts?

**Comment by rvagg** [comment]
see #1887
