### ISSUE TITLE
Problem installing java with npm

### ISSUE THREAD

**Issue by krogold** [nodejs/node-gyp#1249]
* **Node Version**: 
v6.11.0
* **Platform**: 
Windows Microsoft Windows 10 Entreprise
version 10.0.14393 N/A version 14393

* **Module**: 
java

Hello,
I'm trying to install java with npm and I encounter a problem during node-gyp rebuild

here is the console log:
```
C:\Users\<myself>>npm install java

> java@0.8.0 install C:\Users\<myself>\node_modules\java
> node-gyp rebuild


C:\Users\<myself>\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\<myself>\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:195:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\<myself>\node_modules\java
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN <myself>@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "java"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<myself>\npm-debug.log`
```
please find attached the npm-debug.log

[npm-debug.zip](https://github.com/nodejs/node-gyp/files/1134860/npm-debug.zip)

I also install windows build tools in order to have python v2.7, but if I try to use it it fails (but I'm pretty sure that I don't use it properly):

`npm install java --python C:\Users\myself\.windows-build-tools\python27`

can anyone help ? 

thank you

Alexandre

**Comment by bnoordhuis** [comment]
You might want to consider setting it in your .npmrc with `npm config set python ...`.  If that doesn't work and neither does upgrading to node-gyp@3.6.2 (the latest), can you post the new build output?

**Comment by krogold** [comment]
sorry, but I can't find .npmrc ... ?

**Comment by gibfahn** [comment]
@krogold as @bnoordhuis said, use `npm config set python C:\Users\myself\.windows-build-tools\python27`.

You can usually see your config location with `npm config list`.

**Comment by krogold** [comment]
ah, ok, sorry but I'm quite new to the use of npm ...
please find enclosed the new output

[npm-debug.zip](https://github.com/nodejs/node-gyp/files/1138450/npm-debug.zip)

**Comment by bnoordhuis** [comment]
Can you post the output from your terminal?  npm-debug.log doesn't contain the logging from node-gyp, npm doesn't capture it.

**Comment by krogold** [comment]
ok, here it is ... 
[log.zip](https://github.com/nodejs/node-gyp/files/1138742/log.zip)

**Comment by gibfahn** [comment]
#### `log.zip`

```bat
C:\Users\<myself>>npm install java

> java@0.8.0 install C:\Users\<myself>\node_modules\java
> node-gyp rebuild


C:\Users\<myself>\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
[node-java] Error: Command failed: reg query "hklm\software\javasoft\java development kit"
Erreur´┐¢: Erreur´┐¢: le syst´┐¢me n'a pas trouv´┐¢ la cl´┐¢ ou la valeur de Registre sp´┐¢cifi´┐¢e.

Error: Command failed: reg query "hklm\software\wow6432node\javasoft\java development kit"
Erreur´┐¢: Erreur´┐¢: le syst´┐¢me n'a pas trouv´┐¢ la cl´┐¢ ou la valeur de Registre sp´┐¢cifi´┐¢e.

gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\<myself>\node_modules\java
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN <myself>@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "java"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<myself>\npm-debug.log
```

**Comment by bnoordhuis** [comment]
> Call to 'node findJavaHome.js' returned exit status 1

Not a node-gyp issue then.  Looks like it can't find the JRE / JDK.

**Comment by krogold** [comment]
this is strange, I installed jre-8u131-windows-x64.exe a few weeks ago. Though this is entierly new for me so I probably have made mistakes and I need to install extra packages ?

**Comment by krogold** [comment]
"hklm\software\javasoft\java development kit" ... I have only jre installed ... :(

**Comment by krogold** [comment]
at least, only jre in the regedit ...
