### ISSUE TITLE
node-gyp without registry writing - is it possible?

### ISSUE THREAD

**Issue by ljgww** [nodejs/node-gyp#1251]
Is it possible to avoid writing to registry as it is disabled by administrator / security policies?

IMHO any kind of language update shall not be dependent on system administration rights.... otherwise it is pain to use it on a daily basis.

BTW I do have visual studio 2015 installed (in spite that there is report below that there is no MsBuild available. Perhaps it is not compatible with what node-gyp would be expecting?

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 
C:\>npm -v
5.2.0
C:\>node -v
v6.11.0

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
		C:\Users\xxx\AppData\Roaming\npm\node_modules\md-pdf-converter\node_modules\get-cursor-position>if not defined npm_config_node_gyp (node "C:\Users\xxxx\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node
		_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
		gyp ERR! build error
		gyp ERR! stack Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32
		gyp ERR! stack ERROR: Registry editing has been disabled by your administrator.
		gyp ERR! stack
		gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
		gyp ERR! stack     at C:\Users\xxxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:138:25
		gyp ERR! stack     at ChildProcess.exithandler (child_process.js:211:5)
		gyp ERR! stack     at emitTwo (events.js:106:13)
		gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
		gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
		gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
		gyp ERR! stack     at emitOne (events.js:96:13)
		gyp ERR! stack     at Socket.emit (events.js:188:7)
		gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
		gyp ERR! System Windows_NT 6.1.7601
		gyp ERR! command "C:\\ITHD\\nodejs611\\node.exe" "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
		gyp ERR! cwd C:\Users\xxxx\AppData\Roaming\npm\node_modules\md-pdf-converter\node_modules\get-cursor-position
		gyp ERR! node -v v6.11.0
		gyp ERR! node-gyp -v v3.6.2
		gyp ERR! not ok
		npm ERR! code ELIFECYCLE
		npm ERR! errno 1
		npm ERR! get-cursor-position@1.0.3 install: `node-gyp rebuild`
		npm ERR! Exit status 1
		npm ERR!
		npm ERR! Failed at the get-cursor-position@1.0.3 install script.
		npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

		npm ERR! A complete log of this run can be found in:
		npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-07-12T09_23_55_148Z-debug.log

```

</details>

**Comment by bnoordhuis** [comment]
node-gyp doesn't edit the registry, it only queries it.  Your administrator probably limited access too much.  You can sidestep the issue by ensuring that msbuild.exe is on the %PATH%.

**Comment by ljgww** [comment]
Thanks for the tip.

Will try to use PATH method. I am guessing VC++ shall be the target compiler.

**Comment by ljgww** [comment]
Adding msbuild folders to path has killed the problem. I could update (rebuild) node-gyp and subsequent installations that would also trigger node-gyp has passed successfuly.
