### ISSUE TITLE
node-gyp error in production

### ISSUE THREAD

**Issue by FinnFrotscher** [nodejs/node-gyp#1259]
## the stack
meteor 1.5.1 (deploy with mup)
ubuntu 16.04
dockerImage abernix/meteord:base
gcc version 5.4.0

## the env
`sudo apt-get -y install build-essential make gcc-4.8 g++-4.8 gcc-multilib libssl-dev`
`npm install node-gyp -g`

## the error
 ```

[bcrypt] Success: "/bundle/bundle/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> fibers@2.0.0 install /bundle/bundle/programs/server/npm/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting

> gl@4.0.4 install /bundle/bundle/programs/server/npm/node_modules/gl
> prebuild-install || node-gyp rebuild

sh: 1: prebuild-install: not found
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-89-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/gl
gyp ERR! node -v v4.8.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.4.0-89-generic
npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--update-binary"
npm ERR! node v4.8.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! gl@4.0.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gl@4.0.4 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /bundle/bundle/programs/server/npm/npm-debug.log

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.4.0-89-generic
npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v4.8.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /bundle/bundle/programs/server/npm-debug.log

> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js


> bcrypt@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
  
```

this issue has also been posted here: zodern/meteor-up/issues/683

**Comment by refack** [comment]
```
sh: 1: prebuild-install: not found
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 127 while in angle/src/angle.gyp.
while loading dependencies of binding.gyp while trying to load binding.gyp
```
Seems like you need to install `pkg-config`

**Comment by refack** [comment]
P.S. It seems like it's a dependency of `gl` - https://www.npmjs.com/package/gl

**Comment by FinnFrotscher** [comment]
confirm: our dependency-tree include `gl`
but adding `pkg-config libxi-dev libglu1-mesa-dev libglew-dev` to `apt-get` did not solve the issue.

**Comment by FinnFrotscher** [comment]
@refack is there maybe something else?

**Comment by refack** [comment]
Could you post the logs, something like
`/bundle/bundle/programs/server/npm-debug.log`

**Comment by FinnFrotscher** [comment]
[logs.txt](https://github.com/nodejs/node-gyp/files/1216608/logs.txt)

**Comment by FinnFrotscher** [comment]
the app runs locally without issues, even in with `--production` flags. 
we have been fiddling with the server for two days now. its not working.
its not our host either. running the app on digitalocean has the same problem

**Comment by refack** [comment]
The logs seem partial, usually they are more verbose. But I do see one thing you could try:
run `pkg-config --libs-only-l x11 xi xext` (also you can read https://github.com/yarnpkg/yarn/issues/1987).

If that doesn't get you any progress, and if your local system is the same as your production (same OS & same `node` version) you can build the addons locally and tarball your whole `node_modules` and simply copy to production.

**Comment by FinnFrotscher** [comment]
its true. i wanted to spare you the thousand lines, thats why I limited the file to 150 lines.
here is the complete:
[logs.txt](https://github.com/nodejs/node-gyp/files/1216819/logs.txt)

**Comment by refack** [comment]
@FinnFrotscher any progress or new information?

**Comment by FinnFrotscher** [comment]
yes. the issue is solved. I detail the solution here:
https://github.com/zodern/meteor-up/issues/683

**Comment by refack** [comment]
@FinnFrotscher thank you for the follow up.
