### ISSUE TITLE
Mac build failures when using "sudo npm install -g"

### ISSUE THREAD

**Issue by justmoon** [nodejs/node-gyp#126]
Steps to reproduce:

Run `sudo npm install -g leveldb` on a Mac while being logged in on a non-root account.

Here is the log:

```
*snip*
gyp WARN EACCES user "root" does not have permission to create dev dir "/Users/kevinwhitman/.node-gyp/0.8.8"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/bitcoinjs/node_modules/leveldb/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.8.8/node-v0.8.8.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.8/node-v0.8.8.tar.gz
*snip*
node-gyp build
leveldb.target.mk:128: warning: overriding commands for target `Release/leveldb.node'
deps/leveldb/leveldb.target.mk:164: warning: ignoring old commands for target `Release/leveldb.node'
make[1]: *** No rule to make target `../.node-gyp/0.8.8/common.gypi', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System Darwin 12.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /usr/local/lib/node_modules/bitcoinjs/node_modules/leveldb
gyp ERR! node -v v0.8.8
gyp ERR! node-gyp -v v0.6.7
gyp ERR! not ok 
make: *** [build] Error 1
npm ERR! leveldb@0.7.0 preinstall: `make build`
npm ERR! `sh "-c" "make build"` failed with 2
npm ERR! 
npm ERR! Failed at the leveldb@0.7.0 preinstall script.
npm ERR! This is most likely a problem with the leveldb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldb
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bitcoinjs" "-g"
npm ERR! cwd /Users/kevinwhitman
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kevinwhitman/npm-debug.log
npm ERR! not ok code 0
```

And here is my interpretation:

When using `sudo` for a global install on Mac, the write to ~/.node-gyp/ fails. `node-gyp` attempts to fall back to a local `.node-gyp` folder. So far so good, but now the path pointing to `.node-gyp` is relative, so if the package has a gyp file that is not in the root of the module, this path is invalid and the build fails.

Suggested fix:

Wherever the path `../.node-gyp/0.8.8/` is set, set an absolute path instead.

Related issues:

node-gyp #92
npm [#2340](https://github.com/isaacs/npm/issues/2430)
bitcoinjs-server [#82](https://github.com/bitcoinjs/bitcoinjs-server/issues/82)

Workaround:

Use npm's `--unsafe-perm` parameter, e.g. `sudo npm install -g leveldb --unsafe-perm`.

**Comment by eugeniusyu** [comment]
Clean interpretation and fix! Much appreciated!

**Comment by cleechtech** [comment]
I am having this same problem with global npm installs. Any fixes?

**Comment by bnoordhuis** [comment]
@cleechtech It's at the bottom:

> Use npm's --unsafe-perm parameter
