### ISSUE TITLE
installing jassa module

### ISSUE THREAD

**Issue by waeltut** [nodejs/node-gyp#1262]
* **Node Version**: 8.2.1
* **NPM Version**: 5.3.0
* **Platform**: UBUNTU 16.04
* **Compiler**: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) -->
* **Module**: npm install jassa
* **Python**: 2.7.13 (default, Aug 14 2017, 15:08:31)

<details><summary>the installation of jassa module ends with error :  `make` failed with exit code: 2</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'jassa' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose config Skipping project config: /home/wamo/.npmrc. (matches userconfig)
5 verbose npm-session 2ad8b776b6af5c85
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/jassa 15ms (from cache)
9 silly pacote tag manifest for jassa@latest fetched in 31ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly resolveWithNewModule jassa@0.5.0 checking installable status
15 http fetch GET 200 https://registry.npmjs.org/jquery 5ms (from cache)
16 silly pacote range manifest for jquery@~1.8.3 fetched in 10ms
17 warn deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.
18 silly resolveWithNewModule jquery@1.8.3 checking installable status
19 http fetch GET 200 https://registry.npmjs.org/xmlhttprequest 9ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/contextify 10ms (from cache)
21 silly pacote range manifest for xmlhttprequest@~1.4.2 fetched in 12ms
22 silly resolveWithNewModule xmlhttprequest@1.4.2 checking installable status
23 silly pacote range manifest for contextify@~0.1.3 fetched in 12ms
24 silly resolveWithNewModule contextify@0.1.15 checking installable status
25 http fetch GET 200 https://registry.npmjs.org/bindings 3ms (from cache)
26 http fetch GET 200 https://registry.npmjs.org/nan 3ms (from cache)
27 silly pacote range manifest for bindings@^1.2.1 fetched in 5ms
28 silly resolveWithNewModule bindings@1.3.0 checking installable status
29 silly pacote range manifest for nan@^2.1.0 fetched in 5ms
30 silly resolveWithNewModule nan@2.6.2 checking installable status
31 silly currentTree wamo
31 silly currentTree â”œâ”€â”€ ajv@4.11.8
31 silly currentTree â”œâ”€â”€ asn1@0.2.3
31 silly currentTree â”œâ”€â”€ assert-plus@0.2.0
31 silly currentTree â”œâ”€â”€ asynckit@0.4.0
31 silly currentTree â”œâ”€â”€ aws-sign2@0.6.0
31 silly currentTree â”œâ”€â”€ aws4@1.6.0
31 silly currentTree â”œâ”€â”€ bcrypt-pbkdf@1.0.1
31 silly currentTree â”œâ”€â”€ boom@2.10.1
31 silly currentTree â”œâ”€â”€ caseless@0.12.0
31 silly currentTree â”œâ”€â”€ co@4.6.0
31 silly currentTree â”œâ”€â”€ combined-stream@1.0.5
31 silly currentTree â”œâ”€â”€ core-util-is@1.0.2
31 silly currentTree â”œâ”€â”€ cryptiles@2.0.5
31 silly currentTree â”œâ”€â”€ cssom@0.2.5
31 silly currentTree â”œâ”€â”¬ cssstyle@0.2.37
31 silly currentTree â”‚ â””â”€â”€ cssom@0.3.2
31 silly currentTree â”œâ”€â”¬ dashdash@1.14.1
31 silly currentTree â”‚ â””â”€â”€ assert-plus@1.0.0
31 silly currentTree â”œâ”€â”€ delayed-stream@1.0.0
31 silly currentTree â”œâ”€â”€ ecc-jsbn@0.1.1
31 silly currentTree â”œâ”€â”€ extend@3.0.1
31 silly currentTree â”œâ”€â”€ extsprintf@1.3.0
31 silly currentTree â”œâ”€â”€ forever-agent@0.6.1
31 silly currentTree â”œâ”€â”€ form-data@2.1.4
31 silly currentTree â”œâ”€â”¬ getpass@0.1.7
31 silly currentTree â”‚ â””â”€â”€ assert-plus@1.0.0
31 silly currentTree â”œâ”€â”€ har-schema@1.0.5
31 silly currentTree â”œâ”€â”€ har-validator@4.2.1
31 silly currentTree â”œâ”€â”€ hawk@3.1.3
31 silly currentTree â”œâ”€â”€ hoek@2.16.3
31 silly currentTree â”œâ”€â”€ htmlparser@1.7.6
31 silly currentTree â”œâ”€â”€ http-signature@1.1.1
31 silly currentTree â”œâ”€â”€ is-typedarray@1.0.0
31 silly currentTree â”œâ”€â”€ isstream@0.1.2
31 silly currentTree â”œâ”€â”€ jsbn@0.1.1
31 silly currentTree â”œâ”€â”€ jsdom@0.2.19
31 silly currentTree â”œâ”€â”€ json-schema@0.2.3
31 silly currentTree â”œâ”€â”€ json-stable-stringify@1.0.1
31 silly currentTree â”œâ”€â”€ json-stringify-safe@5.0.1
31 silly currentTree â”œâ”€â”€ jsonify@0.0.0
31 silly currentTree â”œâ”€â”¬ jsprim@1.4.1
31 silly currentTree â”‚ â””â”€â”€ assert-plus@1.0.0
31 silly currentTree â”œâ”€â”€ location@0.0.1
31 silly currentTree â”œâ”€â”€ mime-db@1.29.0
31 silly currentTree â”œâ”€â”€ mime-types@2.1.16
31 silly currentTree â”œâ”€â”€ navigator@1.0.1
31 silly currentTree â”œâ”€â”€ oauth-sign@0.8.2
31 silly currentTree â”œâ”€â”€ performance-now@0.2.0
31 silly currentTree â”œâ”€â”€ prototype@0.0.5
31 silly currentTree â”œâ”€â”€ punycode@1.4.1
31 silly currentTree â”œâ”€â”€ qs@6.4.0
31 silly currentTree â”œâ”€â”€ request@2.81.0
31 silly currentTree â”œâ”€â”€ safe-buffer@5.1.1
31 silly currentTree â”œâ”€â”€ sntp@1.0.9
31 silly currentTree â”œâ”€â”¬ sshpk@1.13.1
31 silly currentTree â”‚ â””â”€â”€ assert-plus@1.0.0
31 silly currentTree â”œâ”€â”€ stringstream@0.0.5
31 silly currentTree â”œâ”€â”€ tough-cookie@2.3.2
31 silly currentTree â”œâ”€â”€ tunnel-agent@0.6.0
31 silly currentTree â”œâ”€â”€ tweetnacl@0.14.5
31 silly currentTree â”œâ”€â”€ underscore.string@2.3.3
31 silly currentTree â”œâ”€â”€ underscore@1.5.2
31 silly currentTree â”œâ”€â”€ uuid@3.1.0
31 silly currentTree â”œâ”€â”¬ verror@1.10.0
31 silly currentTree â”‚ â””â”€â”€ assert-plus@1.0.0
31 silly currentTree â””â”€â”€ xmlhttprequest@1.6.0
32 silly idealTree wamo
32 silly idealTree â”œâ”€â”€ ajv@4.11.8
32 silly idealTree â”œâ”€â”€ asn1@0.2.3
32 silly idealTree â”œâ”€â”€ assert-plus@0.2.0
32 silly idealTree â”œâ”€â”€ asynckit@0.4.0
32 silly idealTree â”œâ”€â”€ aws-sign2@0.6.0
32 silly idealTree â”œâ”€â”€ aws4@1.6.0
32 silly idealTree â”œâ”€â”€ bcrypt-pbkdf@1.0.1
32 silly idealTree â”œâ”€â”€ bindings@1.3.0
32 silly idealTree â”œâ”€â”€ boom@2.10.1
32 silly idealTree â”œâ”€â”€ caseless@0.12.0
32 silly idealTree â”œâ”€â”€ co@4.6.0
32 silly idealTree â”œâ”€â”€ combined-stream@1.0.5
32 silly idealTree â”œâ”€â”€ contextify@0.1.15
32 silly idealTree â”œâ”€â”€ core-util-is@1.0.2
32 silly idealTree â”œâ”€â”€ cryptiles@2.0.5
32 silly idealTree â”œâ”€â”€ cssom@0.2.5
32 silly idealTree â”œâ”€â”¬ cssstyle@0.2.37
32 silly idealTree â”‚ â””â”€â”€ cssom@0.3.2
32 silly idealTree â”œâ”€â”¬ dashdash@1.14.1
32 silly idealTree â”‚ â””â”€â”€ assert-plus@1.0.0
32 silly idealTree â”œâ”€â”€ delayed-stream@1.0.0
32 silly idealTree â”œâ”€â”€ ecc-jsbn@0.1.1
32 silly idealTree â”œâ”€â”€ extend@3.0.1
32 silly idealTree â”œâ”€â”€ extsprintf@1.3.0
32 silly idealTree â”œâ”€â”€ forever-agent@0.6.1
32 silly idealTree â”œâ”€â”€ form-data@2.1.4
32 silly idealTree â”œâ”€â”¬ getpass@0.1.7
32 silly idealTree â”‚ â””â”€â”€ assert-plus@1.0.0
32 silly idealTree â”œâ”€â”€ har-schema@1.0.5
32 silly idealTree â”œâ”€â”€ har-validator@4.2.1
32 silly idealTree â”œâ”€â”€ hawk@3.1.3
32 silly idealTree â”œâ”€â”€ hoek@2.16.3
32 silly idealTree â”œâ”€â”€ htmlparser@1.7.6
32 silly idealTree â”œâ”€â”€ http-signature@1.1.1
32 silly idealTree â”œâ”€â”€ is-typedarray@1.0.0
32 silly idealTree â”œâ”€â”€ isstream@0.1.2
32 silly idealTree â”œâ”€â”€ jassa@0.5.0
32 silly idealTree â”œâ”€â”¬ jquery@1.8.3
32 silly idealTree â”‚ â””â”€â”€ xmlhttprequest@1.4.2
32 silly idealTree â”œâ”€â”€ jsbn@0.1.1
32 silly idealTree â”œâ”€â”€ jsdom@0.2.19
32 silly idealTree â”œâ”€â”€ json-schema@0.2.3
32 silly idealTree â”œâ”€â”€ json-stable-stringify@1.0.1
32 silly idealTree â”œâ”€â”€ json-stringify-safe@5.0.1
32 silly idealTree â”œâ”€â”€ jsonify@0.0.0
32 silly idealTree â”œâ”€â”¬ jsprim@1.4.1
32 silly idealTree â”‚ â””â”€â”€ assert-plus@1.0.0
32 silly idealTree â”œâ”€â”€ location@0.0.1
32 silly idealTree â”œâ”€â”€ mime-db@1.29.0
32 silly idealTree â”œâ”€â”€ mime-types@2.1.16
32 silly idealTree â”œâ”€â”€ nan@2.6.2
32 silly idealTree â”œâ”€â”€ navigator@1.0.1
32 silly idealTree â”œâ”€â”€ oauth-sign@0.8.2
32 silly idealTree â”œâ”€â”€ performance-now@0.2.0
32 silly idealTree â”œâ”€â”€ prototype@0.0.5
32 silly idealTree â”œâ”€â”€ punycode@1.4.1
32 silly idealTree â”œâ”€â”€ qs@6.4.0
32 silly idealTree â”œâ”€â”€ request@2.81.0
32 silly idealTree â”œâ”€â”€ safe-buffer@5.1.1
32 silly idealTree â”œâ”€â”€ sntp@1.0.9
32 silly idealTree â”œâ”€â”¬ sshpk@1.13.1
32 silly idealTree â”‚ â””â”€â”€ assert-plus@1.0.0
32 silly idealTree â”œâ”€â”€ stringstream@0.0.5
32 silly idealTree â”œâ”€â”€ tough-cookie@2.3.2
32 silly idealTree â”œâ”€â”€ tunnel-agent@0.6.0
32 silly idealTree â”œâ”€â”€ tweetnacl@0.14.5
32 silly idealTree â”œâ”€â”€ underscore.string@2.3.3
32 silly idealTree â”œâ”€â”€ underscore@1.5.2
32 silly idealTree â”œâ”€â”€ uuid@3.1.0
32 silly idealTree â”œâ”€â”¬ verror@1.10.0
32 silly idealTree â”‚ â””â”€â”€ assert-plus@1.0.0
32 silly idealTree â””â”€â”€ xmlhttprequest@1.6.0
33 silly install generateActionsToTake
34 silly diffTrees action count 6
35 silly diffTrees add bindings@1.3.0
36 silly diffTrees add xmlhttprequest@1.4.2
37 silly diffTrees add nan@2.6.2
38 silly diffTrees add contextify@0.1.15
39 silly diffTrees add jquery@1.8.3
40 silly diffTrees add jassa@0.5.0
41 silly decomposeActions action count 48
42 silly decomposeActions fetch bindings@1.3.0
43 silly decomposeActions extract bindings@1.3.0
44 silly decomposeActions preinstall bindings@1.3.0
45 silly decomposeActions build bindings@1.3.0
46 silly decomposeActions install bindings@1.3.0
47 silly decomposeActions postinstall bindings@1.3.0
48 silly decomposeActions finalize bindings@1.3.0
49 silly decomposeActions refresh-package-json bindings@1.3.0
50 silly decomposeActions fetch xmlhttprequest@1.4.2
51 silly decomposeActions extract xmlhttprequest@1.4.2
52 silly decomposeActions preinstall xmlhttprequest@1.4.2
53 silly decomposeActions build xmlhttprequest@1.4.2
54 silly decomposeActions install xmlhttprequest@1.4.2
55 silly decomposeActions postinstall xmlhttprequest@1.4.2
56 silly decomposeActions finalize xmlhttprequest@1.4.2
57 silly decomposeActions refresh-package-json xmlhttprequest@1.4.2
58 silly decomposeActions fetch nan@2.6.2
59 silly decomposeActions extract nan@2.6.2
60 silly decomposeActions preinstall nan@2.6.2
61 silly decomposeActions build nan@2.6.2
62 silly decomposeActions install nan@2.6.2
63 silly decomposeActions postinstall nan@2.6.2
64 silly decomposeActions finalize nan@2.6.2
65 silly decomposeActions refresh-package-json nan@2.6.2
66 silly decomposeActions fetch contextify@0.1.15
67 silly decomposeActions extract contextify@0.1.15
68 silly decomposeActions preinstall contextify@0.1.15
69 silly decomposeActions build contextify@0.1.15
70 silly decomposeActions install contextify@0.1.15
71 silly decomposeActions postinstall contextify@0.1.15
72 silly decomposeActions finalize contextify@0.1.15
73 silly decomposeActions refresh-package-json contextify@0.1.15
74 silly decomposeActions fetch jquery@1.8.3
75 silly decomposeActions extract jquery@1.8.3
76 silly decomposeActions preinstall jquery@1.8.3
77 silly decomposeActions build jquery@1.8.3
78 silly decomposeActions install jquery@1.8.3
79 silly decomposeActions postinstall jquery@1.8.3
80 silly decomposeActions finalize jquery@1.8.3
81 silly decomposeActions refresh-package-json jquery@1.8.3
82 silly decomposeActions fetch jassa@0.5.0
83 silly decomposeActions extract jassa@0.5.0
84 silly decomposeActions preinstall jassa@0.5.0
85 silly decomposeActions build jassa@0.5.0
86 silly decomposeActions install jassa@0.5.0
87 silly decomposeActions postinstall jassa@0.5.0
88 silly decomposeActions finalize jassa@0.5.0
89 silly decomposeActions refresh-package-json jassa@0.5.0
90 silly install executeActions
91 silly doSerial global-install 48
92 verbose correctMkdir /home/wamo/.npm/_locks correctMkdir not in flight; initializing
93 verbose lock using /home/wamo/.npm/_locks/staging-0549fb20fc9b4533.lock for /home/wamo/node_modules/.staging
94 silly doParallel extract 48
95 silly extract bindings@1.3.0
96 silly extract xmlhttprequest@1.4.2
97 silly extract nan@2.6.2
98 silly extract contextify@0.1.15
99 silly extract jquery@1.8.3
100 silly extract jassa@0.5.0
101 silly doReverseSerial unbuild 48
102 silly doSerial remove 48
103 silly doSerial move 48
104 silly doSerial finalize 48
105 silly finalize /home/wamo/node_modules/bindings
106 silly finalize /home/wamo/node_modules/jquery/node_modules/xmlhttprequest
107 silly finalize /home/wamo/node_modules/nan
108 silly finalize /home/wamo/node_modules/contextify
109 silly finalize /home/wamo/node_modules/jquery
110 silly finalize /home/wamo/node_modules/jassa
111 silly doParallel refresh-package-json 48
112 silly refresh-package-json /home/wamo/node_modules/bindings
113 silly refresh-package-json /home/wamo/node_modules/jquery/node_modules/xmlhttprequest
114 silly refresh-package-json /home/wamo/node_modules/nan
115 silly refresh-package-json /home/wamo/node_modules/contextify
116 silly refresh-package-json /home/wamo/node_modules/jquery
117 silly refresh-package-json /home/wamo/node_modules/jassa
118 silly doParallel preinstall 48
119 silly preinstall bindings@1.3.0
120 info lifecycle bindings@1.3.0~preinstall: bindings@1.3.0
121 silly preinstall xmlhttprequest@1.4.2
122 info lifecycle xmlhttprequest@1.4.2~preinstall: xmlhttprequest@1.4.2
123 silly preinstall nan@2.6.2
124 info lifecycle nan@2.6.2~preinstall: nan@2.6.2
125 silly preinstall contextify@0.1.15
126 info lifecycle contextify@0.1.15~preinstall: contextify@0.1.15
127 silly preinstall jquery@1.8.3
128 info lifecycle jquery@1.8.3~preinstall: jquery@1.8.3
129 silly preinstall jassa@0.5.0
130 info lifecycle jassa@0.5.0~preinstall: jassa@0.5.0
131 silly doSerial build 48
132 silly build bindings@1.3.0
133 info linkStuff bindings@1.3.0
134 silly linkStuff bindings@1.3.0 has /home/wamo/node_modules as its parent node_modules
135 verbose linkBins bindings@1.3.0
136 verbose linkMans bindings@1.3.0
137 silly build xmlhttprequest@1.4.2
138 info linkStuff xmlhttprequest@1.4.2
139 silly linkStuff xmlhttprequest@1.4.2 has /home/wamo/node_modules/jquery/node_modules as its parent node_modules
140 verbose linkBins xmlhttprequest@1.4.2
141 verbose linkMans xmlhttprequest@1.4.2
142 silly build nan@2.6.2
143 info linkStuff nan@2.6.2
144 silly linkStuff nan@2.6.2 has /home/wamo/node_modules as its parent node_modules
145 verbose linkBins nan@2.6.2
146 verbose linkMans nan@2.6.2
147 silly build contextify@0.1.15
148 info linkStuff contextify@0.1.15
149 silly linkStuff contextify@0.1.15 has /home/wamo/node_modules as its parent node_modules
150 verbose linkBins contextify@0.1.15
151 verbose linkMans contextify@0.1.15
152 silly build jquery@1.8.3
153 info linkStuff jquery@1.8.3
154 silly linkStuff jquery@1.8.3 has /home/wamo/node_modules as its parent node_modules
155 verbose linkBins jquery@1.8.3
156 verbose linkMans jquery@1.8.3
157 silly build jassa@0.5.0
158 info linkStuff jassa@0.5.0
159 silly linkStuff jassa@0.5.0 has /home/wamo/node_modules as its parent node_modules
160 verbose linkBins jassa@0.5.0
161 verbose linkMans jassa@0.5.0
162 silly doSerial global-link 48
163 silly doParallel update-linked 48
164 silly doSerial install 48
165 silly install bindings@1.3.0
166 info lifecycle bindings@1.3.0~install: bindings@1.3.0
167 silly install xmlhttprequest@1.4.2
168 info lifecycle xmlhttprequest@1.4.2~install: xmlhttprequest@1.4.2
169 silly install nan@2.6.2
170 info lifecycle nan@2.6.2~install: nan@2.6.2
171 silly install contextify@0.1.15
172 info lifecycle contextify@0.1.15~install: contextify@0.1.15
173 verbose lifecycle contextify@0.1.15~install: unsafe-perm in lifecycle true
174 verbose lifecycle contextify@0.1.15~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/wamo/node_modules/contextify/node_modules/.bin:/home/wamo/node_modules/.bin:/home/wamo/bin:/home/wamo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
175 verbose lifecycle contextify@0.1.15~install: CWD: /home/wamo/node_modules/contextify
176 silly lifecycle contextify@0.1.15~install: Args: [ '-c', 'node-gyp rebuild' ]
177 silly lifecycle contextify@0.1.15~install: Returned: code: 1  signal: null
178 info lifecycle contextify@0.1.15~install: Failed to exec install script
179 verbose unlock done using /home/wamo/.npm/_locks/staging-0549fb20fc9b4533.lock for /home/wamo/node_modules/.staging
180 warn enoent ENOENT: no such file or directory, open '/home/wamo/package.json'
181 verbose enoent This is related to npm not being able to find a file.
182 warn wamo No description
183 warn wamo No repository field.
184 warn wamo No README data
185 warn wamo No license field.
186 verbose stack Error: contextify@0.1.15 install: `node-gyp rebuild`
186 verbose stack Exit status 1
186 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
186 verbose stack     at emitTwo (events.js:125:13)
186 verbose stack     at EventEmitter.emit (events.js:213:7)
186 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
186 verbose stack     at emitTwo (events.js:125:13)
186 verbose stack     at ChildProcess.emit (events.js:213:7)
186 verbose stack     at maybeClose (internal/child_process.js:921:16)
186 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
187 verbose pkgid contextify@0.1.15
188 verbose cwd /home/wamo/arq/testingClient
189 verbose Linux 4.4.0-62-generic
190 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "jassa"
191 verbose node v8.2.1
192 verbose npm  v5.3.0
193 error code ELIFECYCLE
194 error errno 1
195 error contextify@0.1.15 install: `node-gyp rebuild`
195 error Exit status 1
196 error Failed at the contextify@0.1.15 install script.
196 error This is probably not a problem with npm. There is likely additional logging output above.
197 verbose exit [ 1, true ]
```

</details>

**Comment by refack** [comment]
Hello @waeltut 
Your log indicates npm tries to install `contextify` which is incompatible with node >= 0.12.
AFAIK this comes from a dependency of `jassa`: [`"jquery": "~1.8.3"`](https://github.com/GeoKnow/Jassa/blob/jassa-parent-0.0.4/jassa-js/src/npm/package.json#L17)
You could try `npm i  contextify@0.1.15 --ignore-scripts` or even `npm i jassa --ignore-scripts`, if that does works a very crude hack might be to unzip https://github.com/brianmcd/contextify/tree/v0.1.15 into your node_module directory and deleting it's `binding.gyp` so that npm will not try to compile it.

**Comment by waeltut** [comment]
Hi @refack 
I tried but it did not work. yes I already downloaded the module manually but It would be better from npm to use npm directly. I already created an issue on the module github page.
Thank you for the support.

**Comment by refack** [comment]
@waeltut there are several involved parties here
1. Your code
2. `jassa` with the old `jquery` dependency (`~1.8.3`)
3. `npm` trying to install according to semver rules - `~` allowing only semver patch updates
4. `node-gyp` that tries to compile `contextify@0.1.15`

The only way I can think of for layer (4) to solve this is to have a blacklist of modules to not compile. That is problematic since we can not guarantee that the requiring module will work correctly without the compiled sub-module. So this will be a partial mitigation at best.

If you would like to pursue this and submit a PR https://github.com/nodejs/node-gyp/blob/72afdd62cdb960d92b110e713091fb4efd870963/lib/build.js#L20-L22
is a good point to insert such logic.

I'm closing this issue, since it was solved with a workaround, and an issue was opened in the target repo https://github.com/GeoKnow/Jassa-Core/issues/32
Feel free to reopen is you think I'm wrong or if you have further questions or more information.
