### ISSUE TITLE
Cannot open include file: 'v8.h': Windows 10.

### ISSUE THREAD

**Issue by kolykhalov** [nodejs/node-gyp#1265]
* **Node Version**: 8.2.1
* **NPM Version**: 5.3.0
* **Platform**: Windows 10
* **Compiler**: Microsoft (R) Build Engine version 14.0.25420.1
* **Module**: natural

<details><summary>Verbose output (from npm or node-gyp):  </summary>

```
D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  WebWorkerThreads.cc
..\src\WebWorkerThreads.cc(5): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [D:\Ivan\Doc
uments\WebstormProjects\Whisla\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.12 (node_modules\webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ natural@0.5.4
added 1 package and updated 1 package in 7.009s
```

</details>

This happens with all the semantics modules. Some of them are installed, but work not the same as on Linux systems and provide different results on the same data, so becomes obvious that some problem is with install. All modules requiring build show this err.

1. Webworker-threads fail to install with the same error.
2. node-gyp rebuild fails with binding.gyp not found
3. DONE: npm config set msvs_version 2015
4. DONE: npm install --global windows-build-tools
5. DONE: GYP_MSVS_VERSION=2015
6. DONE: path: C:\Program Files (x86)\MSBuild\14.0\Bin
7. DONE: VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
8. DONE: reboots, reopens of powershell as admin, whatever....

**Comment by digitalinfinity** [comment]
@kolykhalov can you share the verbose build log or npm output here please? You might have intended to paste it here but I don't see it?

**Comment by kolykhalov** [comment]
I'm not sure what is verbose output. I added '--verbose' to cli install, hope it helps.

<details><summary>Verbose output (from npm or node-gyp):  </summary>



```

D:\Ivan\Documents\WebstormProjects\Whisla>npm install natural --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'natural',
npm verb cli   '--verbose' ]
npm info using npm@5.3.0
npm info using node@v8.2.1
npm verb npm-session 1d0c79527bd5e8fd
npm http fetch GET 304 https://registry.npmjs.org/natural 998ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/webworker-threads 157ms (from cache)
npm verb correctMkdir C:\Users\Иван\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\Иван\AppData\Roaming\npm-cache\_locks\staging-31d9114e3b5e28eb.lock for D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\.staging
npm info lifecycle natural@0.5.4~preuninstall: natural@0.5.4
npm info lifecycle natural@0.5.4~uninstall: natural@0.5.4
npm verb unbuild rmStuff natural@0.5.4 from D:\Ivan\Documents\WebstormProjects\Whisla\node_modules
npm info lifecycle natural@0.5.4~postuninstall: natural@0.5.4
npm info lifecycle webworker-threads@0.7.12~preinstall: webworker-threads@0.7.12
npm info lifecycle natural@0.5.4~preinstall: natural@0.5.4
npm info linkStuff webworker-threads@0.7.12
npm verb linkBins webworker-threads@0.7.12
npm verb linkMans webworker-threads@0.7.12
npm info linkStuff natural@0.5.4
npm verb linkBins natural@0.5.4
npm verb linkMans natural@0.5.4
npm info lifecycle webworker-threads@0.7.12~install: webworker-threads@0.7.12

> webworker-threads@0.7.12 install D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads
> node-gyp rebuild


D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Иван\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\Иван\.windows-build-tools\python27\python.exe C:\Users\Иван\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\Иван\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.2.1
gyp verb command install [ '8.2.1' ]
gyp verb install input version string "8.2.1"
gyp verb install installing version: 8.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.2.1
gyp verb build dir attempting to create "build" dir: D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build
gyp verb build dir "build" dir needed to be created? D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\config.gypi
gyp verb common.gypi checking for gypi file: D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Иван\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Ivan\\Documents\\WebstormProjects\\Whisla\\node_modules\\webworker-threads\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Иван\\.node-gyp\\8.2.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Иван\\.node-gyp\\8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Иван\\.node-gyp\\8.2.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Ivan\\Documents\\WebstormProjects\\Whisla\\node_modules\\webworker-threads',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Ivan\\Documents\\WebstormProjects\\Whisla\\node_modules\\webworker-threads\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Иван\.node-gyp\8.2.1
gyp verb found first Solution file build/binding.sln
gyp verb `which` succeeded for `msbuild` C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.EXE
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 18.08.2017 15:20:53.
Project "D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\binding.sln" on node 1 (default
 targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\binding.sln" (1) is building "D
:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj" (2) on node 1 (
default targets).
PrepareForBuild:
  Creating directory "Release\obj\WebWorkerThreads\".
  Creating directory "Release\obj\WebWorkerThreads\WebWorkerThreads.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\WebWorkerThreads\WebWorkerThreads.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /I"C:\Users\Eaai\.node-gyp\8.2.1\include\n
  ode" /I"C:\Users\Eaai\.node-gyp\8.2.1\src" /I"C:\Users\Eaai\.node-gyp\8.2.1\deps\uv\include" /I"C:\Users\Eaai\.node-g
  yp\8.2.1\deps\v8\include" /I..\..\nan /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=WebWorker
  Threads /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /
  D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D BUILDING_NODE_EXTENSION /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:preci
  se /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\WebWorkerThreads\\" /Fd"Release\obj\WebWorkerThreads\vc14
  0.pdb" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /errorReport:queue /MP ..\src\WebWorkerThreads.cc
  WebWorkerThreads.cc
..\src\WebWorkerThreads.cc(5): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [D:\Ivan\
Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
Done Building Project "D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\WebWorkerThreads.
vcxproj" (default targets) -- FAILED.

Done Building Project "D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\binding.sln" (def
ault targets) -- FAILED.


Build FAILED.

"D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\binding.sln" (default target) (1) ->
"D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj" (default targ
et) (2) ->
(ClCompile target) ->
  ..\src\WebWorkerThreads.cc(5): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [D:\Iva
n\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.03
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm verb lifecycle webworker-threads@0.7.12~install: unsafe-perm in lifecycle true
npm verb lifecycle webworker-threads@0.7.12~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads\node_modules\.bin;D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Program Files\Anaconda2;C:\Program Files\Anaconda2\Scripts;C:\Program Files\Anaconda2\Library\bin;C:\Program Files\Aladdin\eToken\PKIClient\x32;C:\Program Files\Aladdin\eToken\PKIClient\x64;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\PuTTY\;C:\Users\Иван\WebstormProjects\phantomjs-2.1.1-windows\bin;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Tableau\Tableau 10.3\bin;C:\Program Files\Tableau\Tableau 10.3;C:\Program Files\Tableau;C:\Program Files\Tableau\Drivers\psqlODBC\0906\bin;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.4\bin;D:\AndroidSDK;D:\AndroidStudio;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Иван\Anaconda3;C:\Users\Иван\Anaconda3\Scripts;C:\Users\Иван\Anaconda3\Library\bin;C:\Users\Иван\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Heroku\bin;C:\Users\Иван\AppData\Local\.meteor\;C:\Program Files\Tableau\Tableau 10.3\bin;C:\Program Files\Tableau\Drivers\psqlODBC\0906\bin;C:\Users\Иван\AppData\Roaming\npm;C:\Program Files\MongoDB\Server\3.4\bin\;C:\Users\Иван\AppData\Local\Android\sdk;D:\Android Studio\gradle\gradle-3.2;C:\Program Files (x86)\MSBuild\14.0\Bin
npm verb lifecycle webworker-threads@0.7.12~install: CWD: D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\webworker-threads
npm info lifecycle webworker-threads@0.7.12~install: Failed to exec install script
npm info lifecycle natural@0.5.4~install: natural@0.5.4
npm info lifecycle natural@0.5.4~postinstall: natural@0.5.4
npm verb unlock done using C:\Users\Иван\AppData\Roaming\npm-cache\_locks\staging-31d9114e3b5e28eb.lock for D:\Ivan\Documents\WebstormProjects\Whisla\node_modules\.staging
npm verb saving [ { name: 'natural', spec: '^0.5.4', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.12 (node_modules\webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm verb optional SKIPPING OPTIONAL DEPENDENCY:
npm verb optional Failed at the webworker-threads@0.7.12 install script.
npm verb optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.

+ natural@0.5.4
added 1 package and updated 1 package in 15.566s
npm verb exit [ 0, true ]
npm info ok

D:\Ivan\Documents\WebstormProjects\Whisla>

```

</details>

**Comment by bnoordhuis** [comment]
It's possible node-gyp or python gets confused by the Cyrillic characters in this file path:
```
C:\Users\Иван\.windows-build-tools\python27\python.exe
```

**Comment by kolykhalov** [comment]
Reinstalled Windows 10 with their official tool. Made User path non-cyrillic,  fresh installed Node, went again through steps as mentioned in the header of this thread and it all rebuilt and works like magic now. Modules download and install as intended.

Thanks mates to @digitalinfinity and @bnoordhuis
