### ISSUE TITLE
V8 #include error OSX

### ISSUE THREAD

**Issue by BusbyActual** [nodejs/node-gyp#1273]
Hey there,

I'm trying to convert smilib into a node module and I'm getting several different errors referencing #include. config.h gives the same error however if I add the absolute path it moves forward with the error. I tried adding the header files to the binding.gyp and still get errors. Is there a recommended way of resolving #include <header.h> ?

* **Node Version**:  8.2.1
* **Platform**:  OSX El Captain - 10.11.6
* **Module**: smilib 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
admin$ node-gyp build -verbose
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'build',
gyp verb cli   '-verbose' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/admin/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  cc '-DNODE_GYP_MODULE_NAME=addon' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/admin/.node-gyp/8.2.1/include/node -I/Users/admin/.node-gyp/8.2.1/src -I/Users/admin/.node-gyp/8.2.1/deps/uv/include -I/Users/admin/.node-gyp/8.2.1/deps/v8/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/addon/lib/check.o.d.raw   -c -o Release/obj.target/addon/lib/check.o ../lib/check.c
../lib/check.c:15:10: error: '../config.h' file not found with <angled> include; use "quotes"
      instead
#include <../config.h>
         ^~~~~~~~~~~~~
         "../config.h"
In file included from ../lib/check.c:16:
In file included from /Users/admin/.node-gyp/8.2.1/include/node/node.h:63:
/Users/admin/.node-gyp/8.2.1/include/node/v8.h:21:10: fatal error: 'memory' file not found
#include <memory>
         ^
2 errors generated.
make: *** [Release/obj.target/addon/lib/check.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-verbose"
gyp ERR! cwd /Users/admin/Downloads/libsmi-0.4.0
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

</details>

### Headers  in check.c
```
#include <../config.h>
#include <node.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#include <sys/types.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#ifdef HAVE_WIN_H
#include "win.h"
#endif

#include "error.h"
#include "util.h"
#include "data.h"
#include "check.h"
#include "smi.h"

#ifdef HAVE_DMALLOC_H
#include <dmalloc.h>
#endif
```

**Comment by bnoordhuis** [comment]
I would guess that config.h is normally created at configure time.  Is smilib an autotools project?

You would either have to run the configure script at build time as an action or check in pre-configured config.h files for the platforms you want to support and then pick the right one through `'conditions': ['OS=="win"', 'include_dirs': ['config/win']]` blocks.

**Comment by BusbyActual** [comment]
That is correct the config file is created using a config command. Yes this is an autotools project. So in the case of OSX it would be :  ``` conditions': ['OS=="osx"', 'include_dirs': ['win']] ```?

<details><summary>Verbose output (from npm or node-gyp):</summary>



```
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'build',
gyp verb cli   '-verbose' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/admin/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  cd ..; /usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py -fmake --ignore-environment "--toplevel-dir=." -I/Users/admin/Downloads/libsmi-0.4.0/build/config.gypi -I/usr/local/lib/node_modules/node-gyp/addon.gypi -I/Users/admin/.node-gyp/8.2.1/include/node/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/Users/admin/.node-gyp/8.2.1" "-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp" "-Dnode_lib_file=/Users/admin/.node-gyp/8.2.1/<(target_arch)/node.lib" "-Dmodule_root_dir=/Users/admin/Downloads/libsmi-0.4.0" "-Dnode_engine=v8" binding.gyp
Exception: invalid syntax (binding.gyp, line 15)
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 499, in CallLoadTargetBuildFile
    includes, depth, check, False)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 394, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 246, in LoadOneBuildFile
    None)
  File "<string>", line 15
    'conditions': ['OS=="win"', 'include_dirs': ['config/win']]
                                              ^
SyntaxError: invalid syntax

make: *** [Makefile] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-verbose"
gyp ERR! cwd /Users/admin/Downloads/libsmi-0.4.0
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
Close.  Have a look at https://github.com/nodejs/node/blob/v8.4.0/common.gypi, that should point you in the right direction.

**Comment by BusbyActual** [comment]
That got me a little closer. Going off the binding.gyp [examples](https://github.com/Automattic/node-canvas/blob/master/binding.gyp#L185-L197) the syntax for include_dirs looks like it might need to be in an object. 

<details><summary>Verbose output with object (from npm or node-gyp):</summary>



```
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'build',
gyp verb cli   '-verbose' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/admin/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  cd ..; /usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py -fmake --ignore-environment "--toplevel-dir=." -I/Users/admin/Downloads/libsmi-0.4.0/build/config.gypi -I/usr/local/lib/node_modules/node-gyp/addon.gypi -I/Users/admin/.node-gyp/8.2.1/include/node/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/Users/admin/.node-gyp/8.2.1" "-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp" "-Dnode_lib_file=/Users/admin/.node-gyp/8.2.1/<(target_arch)/node.lib" "-Dmodule_root_dir=/Users/admin/Downloads/libsmi-0.4.0" "-Dnode_engine=v8" binding.gyp
gyp: conditions must be a list
make: *** [Makefile] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-verbose"
gyp ERR! cwd /Users/admin/Downloads/libsmi-0.4.0
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

<details><summary>Verbose output without object (from npm or node-gyp):</summary>



```
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'build',
gyp verb cli   '-verbose' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/admin/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  cd ..; /usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py -fmake --ignore-environment "--toplevel-dir=." -I/Users/admin/Downloads/libsmi-0.4.0/build/config.gypi -I/usr/local/lib/node_modules/node-gyp/addon.gypi -I/Users/admin/.node-gyp/8.2.1/include/node/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/Users/admin/.node-gyp/8.2.1" "-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp" "-Dnode_lib_file=/Users/admin/.node-gyp/8.2.1/<(target_arch)/node.lib" "-Dmodule_root_dir=/Users/admin/Downloads/libsmi-0.4.0" "-Dnode_engine=v8" binding.gyp
Exception: invalid syntax (binding.gyp, line 18)
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 499, in CallLoadTargetBuildFile
    includes, depth, check, False)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 394, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 246, in LoadOneBuildFile
    None)
  File "<string>", line 18
    'include_dirs': ['win'] ]
                  ^
SyntaxError: invalid syntax

make: *** [Makefile] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-verbose"
gyp ERR! cwd /Users/admin/Downloads/libsmi-0.4.0
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by BusbyActual** [comment]
Update: I figured out the correct syntax from looking at multiple binding.gyp files. With these settings I still receive an error referencing a dependency for v8 not being found.

/Users/admin/.node-gyp/8.2.1/include/node/v8.h:21:10: fatal error: 'memory' file not found
#include <memory>
         ^

<details><summary>Verbose output with object (from npm or node-gyp):</summary>



```
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'build',
gyp verb cli   '-silly' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/admin/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  cd ..; /usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py -fmake --ignore-environment "--toplevel-dir=." -I/Users/admin/Downloads/libsmi-0.4.0/build/config.gypi -I/usr/local/lib/node_modules/node-gyp/addon.gypi -I/Users/admin/.node-gyp/8.2.1/include/node/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/Users/admin/.node-gyp/8.2.1" "-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp" "-Dnode_lib_file=/Users/admin/.node-gyp/8.2.1/<(target_arch)/node.lib" "-Dmodule_root_dir=/Users/admin/Downloads/libsmi-0.4.0" "-Dnode_engine=v8" binding.gyp
  cc '-DNODE_GYP_MODULE_NAME=addon' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/admin/.node-gyp/8.2.1/include/node -I/Users/admin/.node-gyp/8.2.1/src -I/Users/admin/.node-gyp/8.2.1/deps/uv/include -I/Users/admin/.node-gyp/8.2.1/deps/v8/include -I../. -I../win -I../tools -I../.  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/addon/lib/check.o.d.raw   -c -o Release/obj.target/addon/lib/check.o ../lib/check.c
In file included from ../lib/check.c:16:
In file included from /Users/admin/.node-gyp/8.2.1/include/node/node.h:63:
/Users/admin/.node-gyp/8.2.1/include/node/v8.h:21:10: fatal error: 'memory' file not found
#include <memory>
         ^
1 error generated.
make: *** [Release/obj.target/addon/lib/check.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "-silly"
gyp ERR! cwd /Users/admin/Downloads/libsmi-0.4.0
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
`<memory>` is a system header.  If the compiler can't find it, make sure you have Xcode or Command Line Tools installed and select an SDK with `xcode-select`.

I'll go ahead and close this out but let me know if you have more questions.

**Comment by divan** [comment]
I hit the same error, installed Command Line Tools, and still have the same error. I tried to "switch" using `xcode-select` as `sudo xcode-select -s /Applications/Xcode.app`, but that didn't help either.

Any hints on how to debug this? I have many `memory` headers in `/Applicaions/Xcode.app` and the path is correct as reported by Xcode:

```
$ find /Applications/Xcode.app -name "memory" | wc -l
10
```

**Comment by susan51531** [comment]
Just for reference, a c file extension could also lead to this. Changing file extension from 'c' to 'cpp' or 'cc';
