### ISSUE TITLE
node c++ addons ,  node-gyp build error.  help ! help ! help

### ISSUE THREAD

**Issue by liuzhen88** [nodejs/node-gyp#1280]
I run node-gyp configure success. but I run node-gyp build is error
(linux centos 7)
node.js version is 6.2.2

hello.cc file
```cpp
#include <node.h>
#include <v8.h>

using namespace v8;

Handle<Value> SayHello(const Arguments& args){
  HandleScope scope;
  return scope.Close(String::New("Hello world"));
}

void Init_Hello(Handle<Object> target){
  target->Set(String::NewSymbol("sayHello"), FunctionTemplate::New(SayHello)->GetFunction());
}

NODE_MODULE(hello,Init_Hello);
```

error message : 
```console
make: Entering directory `/usr/local/hello/build'
  CXX(target) Release/obj.target/hello/src/hello.o
../src/hello.cc:6:30: error: ‘Arguments’ does not name a type
 Handle<Value> SayHello(const Arguments& args){
                              ^
../src/hello.cc:6:41: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> SayHello(const Arguments& args){
                                         ^
In file included from /root/.node-gyp/6.2.2/include/node/node.h:42:0,
                 from ../src/hello.cc:1:
/root/.node-gyp/6.2.2/include/node/v8.h: In function ‘v8::Handle<v8::Value> SayHello(const int&)’:
/root/.node-gyp/6.2.2/include/node/v8.h:904:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/hello.cc:7:15: error: within this context
   HandleScope scope;
               ^
../src/hello.cc:8:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(String::New("Hello world"));
                ^
../src/hello.cc:8:22: error: ‘New’ is not a member of ‘v8::String’
   return scope.Close(String::New("Hello world"));
                      ^
../src/hello.cc: In function ‘void Init_Hello(v8::Handle<v8::Object>)’:
../src/hello.cc:12:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
   target->Set(String::NewSymbol("sayHello"), FunctionTemplate::New(SayHello)->GetFunction());
               ^
../src/hello.cc:12:76: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   target->Set(String::NewSymbol("sayHello"), FunctionTemplate::New(SayHello)->GetFunction());
                                                                            ^
../src/hello.cc:12:76: note: candidate is:
In file included from /root/.node-gyp/6.2.2/include/node/node.h:42:0,
                 from ../src/hello.cc:1:
/root/.node-gyp/6.2.2/include/node/v8.h:4452:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/6.2.2/include/node/v8.h:4452:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/hello.cc: In function ‘v8::Handle<v8::Value> SayHello(const int&)’:
../src/hello.cc:9:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/hello/src/hello.o] Error 1
make: Leaving directory `/usr/local/hello/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.0-123.9.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/hello
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by refack** [comment]
Hello @liuzhen88 you probably need to update the version of your compiler (see [node@6.2.2 BUILDING file](https://github.com/nodejs/node/blob/v6.2.2/BUILDING.md#unix--os-x))
Checkout the [`devtoolset` package](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/)

**Comment by bnoordhuis** [comment]
Your code is written against an old version of the V8 API (old as in pre-node.js v4.x.)  That's not an issue with node-gyp so I'll go ahead and close this out but if you update your code to the new API, it should work.

**Comment by liuzhen88** [comment]
@bnoordhuis yes, I use new API,  it's successfully。  Thanks
