### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ritishashettigar28** [nodejs/node-gyp#1282]
I am trying to install 'LCD' package.....
It's giving me the following errors

```

> epoll@0.1.22 install /var/lib/cloud9/node_modules/lcd/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

make: Entering directory `/var/lib/cloud9/node_modules/lcd/node_modules/onoff/node_modules/epoll/build'
make: Warning: File `../binding.gyp' has modification time 6.2e+07 s in the future
  ACTION Regenerating Makefile
Traceback (most recent call last):
  File "/usr/share/node-gyp/gyp/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/pymodules/python2.7/gyp/__init__.py", line 471, in main
    options.circular_check)
  File "/usr/lib/pymodules/python2.7/gyp/__init__.py", line 111, in Load
    depth, generator_input_info, check, circular_check)
  File "/usr/lib/pymodules/python2.7/gyp/input.py", line 2378, in Load
    depth, check)
  File "/usr/lib/pymodules/python2.7/gyp/input.py", line 358, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/pymodules/python2.7/gyp/input.py", line 208, in LoadOneBuildFile
    raise Exception("%s not found (cwd: %s)" % (build_file_path, os.getcwd()))
Exception: binding.gyp not found (cwd: /var/lib/cloud9/node_modules/lcd/node_modules/onoff/node_modules/epoll/build) while trying to load binding.gyp
make: *** [Makefile] Error 1
make: Leaving directory `/var/lib/cloud9/node_modules/lcd/node_modules/onoff/node_modules/epoll/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.8.13-bone50
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/lib/cloud9/node_modules/lcd/node_modules/onoff/node_modules/epoll
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

```

**Comment by bnoordhuis** [comment]
You are using versions of node.js and node-gyp that have been loooong out of support.  Upgrade and if the problem persists (and isn't an issue with the module you are trying to install) file a new bug report.
