### ISSUE TITLE
unable to point node-gyp to python

### ISSUE THREAD

**Issue by mmclau14** [nodejs/node-gyp#1294]
this issue is caused by installing anaconda (which uses 3.5.3) over the weekend and then trying to build today. if you have a fix where i do not have to manually switch versions or uninstall anaconda that would be super helpful

* **Node Version**: 
v8.4.0
* **Platform**: 
Darwin Michaels-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Compiler**: 
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
* **Module**: 
nsfw

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'release' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle sync@0.1.13~prerelease: sync@0.1.13
6 verbose lifecycle sync@0.1.13~prerelease: unsafe-perm in lifecycle true
7 verbose lifecycle sync@0.1.13~prerelease: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/.bin:/Users/michaelmclaughlin/anaconda/bin:/Users/michaelmclaughlin/.rvm/gems/ruby-2.2.3/bin:/Users/michaelmclaughlin/.rvm/gems/ruby-2.2.3@global/bin:/Users/michaelmclaughlin/.rvm/rubies/ruby-2.2.3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:~/Library/Python/2.7/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/michaelmclaughlin/.npm-global/bin:/Users/michaelmclaughlin/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/michaelmclaughlin/bin:/usr/local/mongodb/bin:/usr/local/mysql/bin:/usr/local/bin:/Users/michaelmclaughlin/.rvm/bin
8 verbose lifecycle sync@0.1.13~prerelease: CWD: /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync
9 silly lifecycle sync@0.1.13~prerelease: Args: [ '-c', 'git push && gulp build --env=production' ]
10 silly lifecycle sync@0.1.13~prerelease: Returned: code: 0  signal: null
11 info lifecycle sync@0.1.13~release: sync@0.1.13
12 verbose lifecycle sync@0.1.13~release: unsafe-perm in lifecycle true
13 verbose lifecycle sync@0.1.13~release: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/.bin:/Users/michaelmclaughlin/anaconda/bin:/Users/michaelmclaughlin/.rvm/gems/ruby-2.2.3/bin:/Users/michaelmclaughlin/.rvm/gems/ruby-2.2.3@global/bin:/Users/michaelmclaughlin/.rvm/rubies/ruby-2.2.3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:~/Library/Python/2.7/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/michaelmclaughlin/.npm-global/bin:/Users/michaelmclaughlin/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/michaelmclaughlin/bin:/usr/local/mongodb/bin:/usr/local/mysql/bin:/usr/local/bin:/Users/michaelmclaughlin/.rvm/bin
14 verbose lifecycle sync@0.1.13~release: CWD: /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync
15 silly lifecycle sync@0.1.13~release: Args: [ '-c',
15 silly lifecycle   'git push && GH_TOKEN="CORRECT_TOKEN_HERE" build' ]
16 silly lifecycle sync@0.1.13~release: Returned: code: 255  signal: null
17 info lifecycle sync@0.1.13~release: Failed to exec release script
18 verbose stack Error: sync@0.1.13 release: `git push && GH_TOKEN="CORRECT_TOKEN_HERE" build`
18 verbose stack Exit status 255
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at EventEmitter.emit (events.js:213:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at ChildProcess.emit (events.js:213:7)
18 verbose stack     at maybeClose (internal/child_process.js:927:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid sync@0.1.13
20 verbose cwd /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync
21 verbose Darwin 16.7.0
22 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "run" "release"
23 verbose node v8.4.0
24 verbose npm  v5.3.0
25 error code ELIFECYCLE
26 error errno 255
27 error sync@0.1.13 release: `git push && GH_TOKEN="CORRECT_TOKEN_HERE" build`
27 error Exit status 255
28 error Failed at the sync@0.1.13 release script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 255, true ]






TRACE

Everything up-to-date
Rebuilding native production dependencies for darwin:x64
Error: /usr/local/Cellar/node/8.4.0/bin/node exited with code 1
Output:

> nsfw@1.0.16 install /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/nsfw
> PYTHON="/Users/michaelmclaughlin/Library/Python/2.7/bin" node-gyp rebuild --python /Users/michaelmclaughlin/Library/Python/2.7/bin


Error output:
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/Users/michaelmclaughlin/Library/Python/2.7/bin", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:5)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--python" "/Users/michaelmclaughlin/Library/Python/2.7/bin"
gyp ERR! cwd /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/nsfw
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nsfw@1.0.16 install: `PYTHON="/Users/michaelmclaughlin/Library/Python/2.7/bin" node-gyp rebuild --python /Users/michaelmclaughlin/Library/Python/2.7/bin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nsfw@1.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelmclaughlin/.npm/_logs/2017-09-19T00_19_37_058Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder-util/src/util.ts:135:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
From previous event:
    at spawn (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder-util/src/util.ts:103:3)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/yarn.ts:135:5
From previous event:
    at rebuild (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/yarn.js:93:22)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at installOrRebuild (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/yarn.js:33:21)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/packager.ts:404:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/packager.js:486:11)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/packager.ts:231:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/packager.js:379:11)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/packager.js:274:11)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3











BEFORE I TRIED TO FIX BY PASSING ENV VAR AND FLAG

Error: /usr/local/Cellar/node/8.4.0/bin/node exited with code 1
Output:

> nsfw@1.0.16 install /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/nsfw
> node-gyp rebuild


Error output:
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/michaelmclaughlin/anaconda/bin/python" is v3.5.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:262:7)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Socket.emit (events.js:210:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:545:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/nsfw
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nsfw@1.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nsfw@1.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelmclaughlin/.npm/_logs/2017-09-19T00_24_56_847Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder-util/src/util.ts:135:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
From previous event:
    at spawn (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder-util/src/util.ts:103:3)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/yarn.ts:135:5
From previous event:
    at rebuild (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/yarn.js:93:22)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at installOrRebuild (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/yarn.js:33:21)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/packager.ts:404:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/packager.js:486:11)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/packager.ts:231:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/packager.js:379:11)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/packager.js:274:11)
    at /Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/michaelmclaughlin/Sites/specless/cloud-compiler/sync/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

</details>

**Comment by bnoordhuis** [comment]
PYTHON should be the path to the binary, not the directory containing the binary.  Hope that helps.
