### ISSUE TITLE
Unable to install node-gyp under node 0.10.x SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by j4y** [nodejs/node-gyp#1299]
* **Node Version**:  node 0.10.36 and npm 1.4.28
* **Platform**: Linux (CentOS 7)
* **Compiler**:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
* **Module**: node-gyp@0.10.6

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.36 | linux | x64

/usr/local/lib/node_modules/node-gyp/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SyntaxError: Use of const in strict mode.
gyp ERR! stack     at Module._compile (module.js:439:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! stack     at Function.Module._load (module.js:312:12)
gyp ERR! stack     at Module.require (module.js:364:17)
gyp ERR! stack     at require (module.js:380:17)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-gyp/node_modules/request/node_modules/hawk/lib/index.js:5:33)
gyp ERR! stack     at Module._compile (module.js:456:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
gyp ERR! stack     at Module.load (module.js:356:32)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/licode/erizoAPI
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>

```

</details>

This used to work, but is now failing for us.  Any advice on how to proceed would be appreciated.  We are trying to run a legacy system, which uses node 0.10.x

If I try to install the latest node-gyp, it displays some warnings:
```
sudo npm install -g node-gyp
npm WARN engine request@2.82.0: wanted: {"node":">= 4"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine sntp@2.0.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
node-gyp@3.6.2 /usr/local/lib/node_modules/node-gyp
├── rimraf@2.6.2
├── graceful-fs@4.1.11
├── semver@5.3.0
├── osenv@0.1.4 (os-tmpdir@1.0.2, os-homedir@1.0.2)
├── which@1.3.0 (isexe@2.0.0)
├── nopt@3.0.6 (abbrev@1.1.0)
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── fstream@1.0.11 (inherits@2.0.3)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0)
├── tar@2.2.1 (inherits@2.0.3, block-stream@0.0.9)
├── npmlog@4.1.2 (set-blocking@2.0.0, console-control-strings@1.1.0, gauge@2.7.4, are-we-there-yet@1.1.4)
└── request@2.82.0 (is-typedarray@1.0.0, oauth-sign@0.8.2, aws-sign2@0.7.0, forever-agent@0.6.1, tunnel-agent@0.6.0, caseless@0.12.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, safe-buffer@5.1.1, extend@3.0.1, aws4@1.6.0, performance-now@2.1.0, uuid@3.1.0, combined-stream@1.0.5, qs@6.5.1, form-data@2.3.1, mime-types@2.1.17, hawk@6.0.2, tough-cookie@2.3.3, http-signature@1.2.0, har-validator@5.0.3)
```

**Comment by bnoordhuis** [comment]
See request/request#2772.  I'm afraid there isn't much you can do except install an older version of request manually.

I don't really want to pin the version of request to 2.81.x because that would prevent it from being shared with npm's copy (when node-gyp is bundled with npm - the common case) but maybe we should for now.

@nodejs/node-gyp Thoughts?

**Comment by j4y** [comment]
That is a good workaround.  thank you.  Here is what I'm using now in case it helps someone else.
```
sudo npm install -g node-gyp@0.10.6 request@2.25.0
```

**Comment by refack** [comment]
> I don't really want to pin the version of request to 2.81.x because that would prevent it from being shared with npm's copy (when node-gyp is bundled with npm - the common case) but maybe we should for now.

`npm` has pinned request to `~2.75.0` so no problem:
https://github.com/npm/npm/blob/d081cc6c8d73f2aa698aab36605377c95e916224/package.json#L86

**Comment by bnoordhuis** [comment]
Closing, #1300 was merged.
