### ISSUE TITLE
Can't Install canvas

### ISSUE THREAD

**Issue by MellyTheFireyMelly** [nodejs/node-gyp#1306]
Node Version: 8.60
Platform: ?
Compiler: Windows
Module: Canvas

```
PS C:\WINDOWS\system32> npm install canvas

> canvas@1.6.7 install C:\WINDOWS\system32\node_modules\canvas
> node-gyp rebuild


C:\WINDOWS\system32\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\Ali\AppData\Roaming\npm\node_
modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: binding.gyp not found (cwd: C:\WINDOWS\system32\node_modules\canvas) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib
\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ali\\AppData\\Roaming\\npm\\node_modules\\npm\\node_m
odules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\canvas
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN discord.js@10.0.1 requires a peer of node-opus@^0.2.1 but none was installed.
npm WARN discord.js@10.0.1 requires a peer of opusscript@^0.0.1 but none was installed.
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ali\AppData\Roaming\npm-cache\_logs\2017-10-04T23_38_52_960Z-debug.log
```

I used chocolatey `choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo` and it worked. I also installed `node-gyp` using `npm install --global node-gyp` just to make sure and I ran `npm install canvas` and I got the error.

**Comment by bnoordhuis** [comment]
I can't help you but the error is this: `binding.gyp not found` - that's the file that tells node-gyp what to do, except it's missing.  Try reporting this to the node-canvas project.

**Comment by refack** [comment]
Another observation:
```
C:\WINDOWS\system32> npm install canvas
```
You are trying to install a node library into `C:\WINDOWS\system32`. I'm pretty sure that's not a very useful place to install it.
Running `npm install` without the `--global` option tries to add a dependency to a project rooted in the current working directory. So I'm guessing it might work better if you run this in the directory of your project, or create a new directory that does not require Admin access.

**Comment by MellyTheFireyMelly** [comment]
Oh okay. I'll try again!

**Comment by MellyTheFireyMelly** [comment]
I got this error when running in my project's directory.

```
PS C:\Users\Ali\Desktop\Coding\Discord\MTFMisAJ-Dev> npm install --save canvas

> canvas@1.6.7 install C:\Users\Ali\Desktop\Coding\Discord\MTFMisAJ-Dev\node_modules\canvas
> node-gyp rebuild


C:\Users\Ali\Desktop\Coding\Discord\MTFMisAJ-Dev\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Ali\Desktop\C
oding\Discord\MTFMisAJ-Dev\node_modules\canvas\build\canvas.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ali\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ali\Desktop\Coding\Discord\MTFMisAJ-Dev\node_modules\canvas
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of node-opus@^0.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of opusscript@^0.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of uws@^8.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.9.0 requires a peer of discord.js@^12.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ali\AppData\Roaming\npm-cache\_logs\2017-10-05T22_51_07_127Z-debug.log
PS C:\Users\Ali\Desktop\Coding\Discord\MTFMisAJ-Dev>

**Comment by bnoordhuis** [comment]
CL.exe is the compiler.  See https://github.com/nodejs/node-gyp#on-windows if you don't have Visual Studio for ways of installing MS Build Tools.
