### ISSUE TITLE
pigpio.cc:2:10: fatal error: 'pigpio.h' file not found

### ISSUE THREAD

**Issue by iroy2000** [nodejs/node-gyp#1308]
* **Node Version**: 

`npm -v`
`5.4.1`

`node -v`
`v8.4.0`

* **Platform**: 

`macOS . 10.12.6`

* **Compiler**: 
```
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

* **Module**: 
https://github.com/marak/say.js/

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> fibers@1.0.15 install /Users/roy/development/tjbot-code-challenge/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:122:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:2624:10: note: 'NewFromOneByte' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:126:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:2624:10: note: 'NewFromOneByte' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:433:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                           ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:3787:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:621:14: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
                                TryCatch try_catch;
                                         ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:8157:3: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
  ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:741:34: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
                        Coroutine::pool_size = value->ToNumber()->Value();
                                                      ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:2279:10: note: 'ToNumber' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:793:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                            ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:3120:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:794:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                            ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:3120:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/fibers.cc:795:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                            ^
/Users/roy/.node-gyp/8.4.0/include/node/v8.h:3120:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/roy/.node-gyp/8.4.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
8 warnings generated.
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
Installed in `/Users/roy/development/tjbot-code-challenge/node_modules/fibers/bin/darwin-x64-57/fibers.node`

> pigpio@0.4.0 install /Users/roy/development/tjbot-code-challenge/node_modules/pigpio
> node-gyp rebuild

  CXX(target) Release/obj.target/pigpio/src/pigpio.o
../src/pigpio.cc:2:10: fatal error: 'pigpio.h' file not found
#include <pigpio.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/pigpio/src/pigpio.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/roy/development/tjbot-code-challenge/node_modules/pigpio
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

```

```

</details>

**Comment by refack** [comment]
Hello @iroy2000,
From reading the `pigpio` node binding [README](https://github.com/fivdi/pigpio), it sees like you need to install the `pigpio` C library first.
Anyway this seems like an issue that is more suited for that repo, as they probably have much more experience with library specific errors.
I'm closing this issue, but feel free to reopen or comment is you have more information.
