### ISSUE TITLE
Can't install node-webcrypto-ossl

### ISSUE THREAD

**Issue by Eligioo** [nodejs/node-gyp#1310]
* **Node Version**: v8.7.0
* **Platform**: Windows 10 x64
* **Compiler**:  15.4.8.50001 / Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x86
* **Module**: node-webcrypto-ossl

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\stefa\Desktop\nimiq socket & wrapper\core>npm install

> node-webcrypto-ossl@1.0.31 install C:\Users\stefa\Desktop\nimiq socket & wrapper\core\node_modules\node-webcrypto-ossl
> node-gyp rebuild


C:\Users\stefa\Desktop\nimiq socket & wrapper\core\node_modules\node-webcrypto-ossl>if not defined npm_config_node_gyp (node "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1900, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\stefa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\stefa\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\stefa\Desktop\nimiq socket & wrapper\core\node_modules\node-webcrypto-ossl
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\stefa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! node-webcrypto-ossl@1.0.31 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-webcrypto-ossl@1.0.31 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-webcrypto-ossl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\stefa\Desktop\nimiq socket & wrapper\core\npm-debug.log
```

</details>

**Comment by bnoordhuis** [comment]
Upgrade your copy of node-gyp.  VS 2017 support was added in 3.6.0.

**Comment by Eligioo** [comment]
@bnoordhuis 

I have node-gyp globally installed already:
node-gyp -v
v3.6.2

I also saw in the logs it still uses v3.5.0 but I cannot find where that is comming from

**Comment by Eligioo** [comment]
Finally fixed it.
In the end I installed yarn, edited the yarn.lock file and force it to use 3.6.2.

**Comment by refack** [comment]
> I have node-gyp globally installed already:
> node-gyp -v
> v3.6.2
> 
> I also saw in the logs it still uses v3.5.0 but I cannot find where that is comming from

For context- The `npm i` command uses a local `node-gyp` copy.
@Eligioo your log states you were using `npm  v4.1.2`, node-gyp@3.6.0 was added in `npm@v5.0.0`
