### ISSUE TITLE
Can't install canvas

### ISSUE THREAD

**Issue by MasterTextman** [nodejs/node-gyp#1311]
* **Node Version**:  4.7.2
* **Platform**:  4.10.0-37-generic #41-Ubuntu x86_64 GNU/Linux
* **Compiler**:  gcc version 7.0.1 20170407 (experimental)
* **Module**:  canvas

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'install', 'canvas' ]
2 info using npm@5.5.1
3 info using node@v4.7.2
4 verbose config Skipping project config: /home/textman/.npmrc. (matches userconfig)
5 verbose npm-session ff1e7943091e3ab3
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/canvas 22ms (from cache)
9 silly pacote tag manifest for canvas@latest fetched in 64ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly resolveWithNewModule canvas@1.6.7 checking installable status
15 silly currentTree textman
15 silly currentTree ├── css-font-size-keywords@1.0.0
15 silly currentTree ├── css-font-stretch-keywords@1.0.1
15 silly currentTree ├── css-font-style-keywords@1.0.1
15 silly currentTree ├── css-font-weight-keywords@1.0.0
15 silly currentTree ├── css-global-keywords@1.0.1
15 silly currentTree ├── css-list-helpers@1.0.1
15 silly currentTree ├── css-system-font-keywords@1.0.0
15 silly currentTree ├── isnumeric@0.2.0
15 silly currentTree ├── nan@2.7.0
15 silly currentTree ├── parse-css-font@2.0.2
15 silly currentTree ├── tcomb@2.7.0
15 silly currentTree ├── units-css@0.4.0
15 silly currentTree ├── unquote@1.1.0
15 silly currentTree └── viewport-dimensions@0.2.0
16 silly idealTree textman
16 silly idealTree ├── canvas@1.6.7
16 silly idealTree ├── css-font-size-keywords@1.0.0
16 silly idealTree ├── css-font-stretch-keywords@1.0.1
16 silly idealTree ├── css-font-style-keywords@1.0.1
16 silly idealTree ├── css-font-weight-keywords@1.0.0
16 silly idealTree ├── css-global-keywords@1.0.1
16 silly idealTree ├── css-list-helpers@1.0.1
16 silly idealTree ├── css-system-font-keywords@1.0.0
16 silly idealTree ├── isnumeric@0.2.0
16 silly idealTree ├── nan@2.7.0
16 silly idealTree ├── parse-css-font@2.0.2
16 silly idealTree ├── tcomb@2.7.0
16 silly idealTree ├── units-css@0.4.0
16 silly idealTree ├── unquote@1.1.0
16 silly idealTree └── viewport-dimensions@0.2.0
17 silly install generateActionsToTake
18 silly diffTrees action count 1
19 silly diffTrees add canvas@1.6.7
20 silly decomposeActions action count 8
21 silly decomposeActions fetch canvas@1.6.7
22 silly decomposeActions extract canvas@1.6.7
23 silly decomposeActions preinstall canvas@1.6.7
24 silly decomposeActions build canvas@1.6.7
25 silly decomposeActions install canvas@1.6.7
26 silly decomposeActions postinstall canvas@1.6.7
27 silly decomposeActions finalize canvas@1.6.7
28 silly decomposeActions refresh-package-json canvas@1.6.7
29 silly install executeActions
30 silly doSerial global-install 8
31 verbose correctMkdir /home/textman/.npm/_locks correctMkdir not in flight; initializing
32 verbose lock using /home/textman/.npm/_locks/staging-5e218ef0844db94b.lock for /home/textman/node_modules/.staging
33 silly doParallel extract 8
34 silly extract canvas@1.6.7
35 silly pacote trying canvas@https://registry.npmjs.org/canvas/-/canvas-1.6.7.tgz by hash: sha512-QLFCd9ca/Ww3s4vUf1KxmTX2QoYu8sZkSvXQ36RdbqNETDjn/I1H01ZEtWGGLcY0T7zNO6nsGoHX+0zrMy6JrQ==
36 silly pacote canvas@https://registry.npmjs.org/canvas/-/canvas-1.6.7.tgz extracted to /home/textman/node_modules/.staging/canvas-5e57884d by content address 48ms
37 silly doReverseSerial unbuild 8
38 silly doSerial remove 8
39 silly doSerial move 8
40 silly doSerial finalize 8
41 silly finalize /home/textman/node_modules/canvas
42 silly doParallel refresh-package-json 8
43 silly refresh-package-json /home/textman/node_modules/canvas
44 silly doParallel preinstall 8
45 silly preinstall canvas@1.6.7
46 info lifecycle canvas@1.6.7~preinstall: canvas@1.6.7
47 silly doSerial build 8
48 silly build canvas@1.6.7
49 info linkStuff canvas@1.6.7
50 silly linkStuff canvas@1.6.7 has /home/textman/node_modules as its parent node_modules
51 verbose linkBins canvas@1.6.7
52 verbose linkMans canvas@1.6.7
53 silly doSerial global-link 8
54 silly doParallel update-linked 8
55 silly doSerial install 8
56 silly install canvas@1.6.7
57 info lifecycle canvas@1.6.7~install: canvas@1.6.7
58 verbose lifecycle canvas@1.6.7~install: unsafe-perm in lifecycle false
59 verbose lifecycle canvas@1.6.7~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/textman/node_modules/canvas/node_modules/.bin:/home/textman/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
60 verbose lifecycle canvas@1.6.7~install: CWD: /home/textman/node_modules/canvas
61 silly lifecycle canvas@1.6.7~install: Args: [ '-c', 'node-gyp rebuild' ]
62 silly lifecycle canvas@1.6.7~install: Returned: code: 1  signal: null
63 info lifecycle canvas@1.6.7~install: Failed to exec install script
64 verbose unlock done using /home/textman/.npm/_locks/staging-5e218ef0844db94b.lock for /home/textman/node_modules/.staging
65 warn enoent ENOENT: no such file or directory, open '/home/textman/package.json'
66 verbose enoent This is related to npm not being able to find a file.
67 warn textman No description
68 warn textman No repository field.
69 warn textman No README data
70 warn textman No license field.
71 verbose stack Error: canvas@1.6.7 install: `node-gyp rebuild`
71 verbose stack Exit status 1
71 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
71 verbose stack     at emitTwo (events.js:87:13)
71 verbose stack     at EventEmitter.emit (events.js:172:7)
71 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
71 verbose stack     at emitTwo (events.js:87:13)
71 verbose stack     at ChildProcess.emit (events.js:172:7)
71 verbose stack     at maybeClose (internal/child_process.js:854:16)
71 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
72 verbose pkgid canvas@1.6.7
73 verbose cwd /home/textman
74 verbose Linux 4.10.0-37-generic
75 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "canvas"
76 verbose node v4.7.2
77 verbose npm  v5.5.1
78 error code ELIFECYCLE
79 error errno 1
80 error canvas@1.6.7 install: `node-gyp rebuild`
80 error Exit status 1
81 error Failed at the canvas@1.6.7 install script.
81 error This is probably not a problem with npm. There is likely additional logging output above.
82 verbose exit [ 1, true ]
```

</details>

If I remove the sudo, the errors go away and I get a bunch of warnings instead. Installing something else works [example. text-meme-cli], however when I try to run it, I get these errors:

```
Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/text-meme-cli/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

It says it can't find canvas.node. So I guess without sudo the installation still fails.

**Comment by bnoordhuis** [comment]
The log doesn't contain the actual build error but you should be able to find it in the console output.

**Comment by MasterTextman** [comment]
Apologies, here's the console output when I run `sudo npm install canvas` :
```
> canvas@1.6.7 install /home/textman/node_modules/canvas
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/textman/node_modules/canvas/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.10.0-37-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/textman/node_modules/canvas
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/textman/package.json'
npm WARN textman No description
npm WARN textman No repository field.
npm WARN textman No README data
npm WARN textman No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/textman/.npm/_logs/2017-10-14T22_18_14_208Z-debug.log
```

**Comment by bnoordhuis** [comment]
That's a permissions error, probably because you installed as root first.  Can you delete the node_modules folder and try again?

**Comment by MasterTextman** [comment]
I deleted the node_modules folder referenced in the error output, which was located at home... but the same error persisted.

It even said `gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/textman/node_modules/canvas/build'` again, so I tried deleting the same node_modules folder using rm -r...

And now it's saying the folder doesn't exist.

So the installer is trying to make a directory in a folder that doesn't exist.

However, I tried making that directory myself, and rerunning the command, but the same error showed up.

I feel like the log is incorrect...

**Comment by megamindbrian** [comment]
Getting this also, when trying to "rebuild node-gyp" which shouldn't even be necessary because there should be prebuilt packages for the most common platforms:

```
C:\Users\brian.cullinan\Documents\jupytangular2>npm install webdriverio --save

> canvas@1.6.7 install C:\Users\brian.cullinan\Documents\jupytangular2\node_modules\canvas
> node-gyp rebuild


C:\Users\brian.cullinan\Documents\jupytangular2\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\brian.cullinan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [C:\Users\brian
.cullinan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [C:\Users\brian.
cullinan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\ImageData.cc) [C:\Users\brian.cull
inan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc) [C:\Users\brian.cullina
n\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\Image.cc) [C:\Users\brian.cullinan
\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\U
sers\brian.cullinan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open
 include file: 'cairo.h': No such file or directory (compiling source file ..\src\init.cc) [C:\Users\brian.cullinan\
Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\brian.cullinan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\brian.cullinan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\brian.cullinan\Documents\jupytangular2\node_modules\canvas
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN extract-text-webpack-plugin@3.0.0 requires a peer of webpack@^3.1.0 but none was installed.
npm WARN html-webpack-plugin@2.30.1 requires a peer of webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3 but none was installed.
npm WARN less-loader@4.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none was installed.
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none was installed.
npm WARN webpack-dev-middleware@1.12.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none was installed.
npm WARN webpack-dev-server@2.7.1 requires a peer of webpack@^2.2.0 || ^3.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian.cullinan\AppData\Roaming\npm-cache\_logs\2017-10-27T17_13_44_577Z-debug.log
```

**Comment by megamindbrian** [comment]
Reinstalling didn't work.

**Comment by refack** [comment]
@megamindbrian take a look at he node-cavas wiki for Windows - https://github.com/Automattic/node-canvas/wiki/Installation---Windows
You'll need to install GTK for it to work.

**Comment by megamindbrian** [comment]
The instructions make it seem like it's either automatically install with
chocolately or manually install gtk. It's not clear.

**Comment by bnoordhuis** [comment]
I'm going to close this out because neither of the reported issues seem to be node-gyp bugs.  The node-canvas bug tracker is the right place to report them.
