### ISSUE TITLE
Error when installing node package 'oracledb'

### ISSUE THREAD

**Issue by nick250386** [nodejs/node-gyp#1317]
* **Node Version**: 7.4.0
* **Platform**: Windows 7 64-bit
* **Compiler**: 
Microsoft (R) Build Engine version 4.0.30319.36415
[Microsoft .NET Framework, version  @4.0.30319.36415]
Copyright (C) Microsoft Corporation. All rights reserved.

4.0.30319.36415
* **Module**: oracledb

<details><summary>Verbose output (from npm or node-gyp): node-gyp configure --msvs_version=2013 --debug</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@7.4.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\[username]\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[username]\\Desktop\\Oracle\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[username]\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[username]\\.node-gyp\\7.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\[username]\\.node-gyp\\7.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\[username]\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\[username]\\.node-gyp\\7.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\[username]\\Desktop\\Oracle',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\[username]\\Desktop\\Oracle\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
```

</details>

<details><summary>Verbose output (from npm or node-gyp):npm install oracledb --toolset=oci12.1-msvs2013 --verbose</summary>

```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'oracledb',
npm verb cli   '--toolset=oci12.1-msvs2013',
npm verb cli   '--verbose' ]
npm info using npm@4.0.5
npm info using node@v7.4.0
npm verb request uri http://[proxy-registry]/oracledb
npm verb request no auth needed
npm info attempt registry request try #1 at 6:58:56 PM
npm verb request id fc1f5e90190c3e04
npm verb etag "ebbca4799bbeab6d358fb0abaf58d0d4"
npm http request GET http://[proxy-registry]/oracledb
npm http 200 http://[proxy-registry]/oracledb
npm verb headers { 'x-powered-by': 'verdaccio/2.4.0',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   etag: '"1f20fb8d90a45acbcc3acb7e177c54cc"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'content-encoding': 'gzip',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aVuVsF',
npm verb headers   date: 'Wed, 01 Nov 2017 13:29:01 GMT',
npm verb headers   connection: 'keep-alive',
npm verb headers   'transfer-encoding': 'chunked' }
npm verb get saving oracledb to C:\Users\[username]\AppData\Roaming\npm-cache\[proxy-registry]\oracledb\.cache.json
npm verb correctMkdir C:\Users\[username]\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb cache add spec oracledb
npm verb addNamed "latest" is being treated as a dist-tag for oracledb
npm info addNameTag [ 'oracledb', 'latest' ]
npm verb addNameTag registry:http://[proxy-registry]/oracledb not in flight; fetching
npm verb get http://[proxy-registry]/oracledb not expired, no request
npm verb addNamed "1.13.1" is a plain semver version for oracledb
npm verb afterAdd C:\Users\[username]\AppData\Roaming\npm-cache\oracledb\1.13.1\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\[username]\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\[username]\AppData\Roaming\npm-cache\oracledb\1.13.1\package\package.json written
npm verb request uri http://[proxy-registry]/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 6:58:57 PM
npm verb etag "1361dce309ae4e4b4899fbab773bb4c1"
npm http request GET http://[proxy-registry]/nan
npm http 200 http://[proxy-registry]/nan
npm verb headers { 'x-powered-by': 'verdaccio/2.4.0',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   etag: '"f437c43260c21f385ba9dcb8ace0481b"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'content-encoding': 'gzip',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aVuVsF',
npm verb headers   date: 'Wed, 01 Nov 2017 13:29:02 GMT',
npm verb headers   connection: 'keep-alive',
npm verb headers   'transfer-encoding': 'chunked' }
npm verb get saving nan to C:\Users\[username]\AppData\Roaming\npm-cache\[proxy-registry]\nan\.cache.json
npm verb correctMkdir C:\Users\[username]\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb cache add spec nan@~2.5.0
npm verb addNamed ">=2.5.0 <2.6.0" is a valid semver range for nan
npm verb addNameRange registry:http://[proxy-registry]/nan not in flight; fetching
npm verb get http://[proxy-registry]/nan not expired, no request
npm verb addNamed "2.5.1" is a plain semver version for nan
npm verb afterAdd C:\Users\[username]\AppData\Roaming\npm-cache\nan\2.5.1\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\[username]\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\[username]\AppData\Roaming\npm-cache\nan\2.5.1\package\package.json written
npm verb correctMkdir C:\Users\[username]\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\[username]\AppData\Roaming\npm-cache\_locks\staging-e47d8a858ff9115b.lock for C:\Users\[username]\Desktop\Oracle\node_modules\.staging
npm verb unbuild node_modules\.staging\nan-eafec32e
npm verb unbuild node_modules\.staging\oracledb-1139cd9f
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\.staging\nan-eafec32e
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\.staging\oracledb-1139cd9f
npm verb tar unpack C:\Users\[username]\AppData\Roaming\npm-cache\nan\2.5.1\package.tgz
npm verb tar unpacking to C:\Users\[username]\Desktop\Oracle\node_modules\.staging\nan-eafec32e
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\.staging\nan-eafec32e
npm verb tar unpack C:\Users\[username]\AppData\Roaming\npm-cache\oracledb\1.13.1\package.tgz
npm verb tar unpacking to C:\Users\[username]\Desktop\Oracle\node_modules\.staging\oracledb-1139cd9f
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\.staging\oracledb-1139cd9f
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\.staging\nan-eafec32e\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\.staging\oracledb-1139cd9f\node_modules
npm info lifecycle nan@2.5.1~preinstall: nan@2.5.1
npm info lifecycle oracledb@1.13.1~preinstall: oracledb@1.13.1
npm info linkStuff nan@2.5.1
npm verb linkBins nan@2.5.1
npm verb linkMans nan@2.5.1
npm info linkStuff oracledb@1.13.1
npm verb linkBins oracledb@1.13.1
npm verb linkMans oracledb@1.13.1
npm info lifecycle nan@2.5.1~install: nan@2.5.1
npm info lifecycle oracledb@1.13.1~install: oracledb@1.13.1

> oracledb@1.13.1 install C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
> node-gyp rebuild


C:\Users\[username]\Desktop\Oracle\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27" in the PATH
gyp verb `which` failed Error: not found: C:\Python27
gyp verb `which` failed     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  C:\Python27 { Error: not found: C:\Python27
gyp verb `which` failed     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb could not find "C:\Python27". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.1\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 7.4.0
gyp verb command install [ '7.4.0' ]
gyp verb install input version string "7.4.0"
gyp verb install installing version: 7.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 7.4.0
gyp verb build dir attempting to create "build" dir: C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build
gyp verb build dir "build" dir needed to be created? C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[username]\\Desktop\\Oracle\\node_modules\\oracledb\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[username]\\.node-gyp\\7.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\[username]\\.node-gyp\\7.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\[username]\\Desktop\\Oracle\\node_modules\\oracledb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\[username]\\Desktop\\Oracle\\node_modules\\oracledb\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\[username]\.node-gyp\7.4.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for x64 C:\Users\[username]\.node-gyp\7.4.0\Release\node.lib
gyp info spawn C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/1/2017 6:59:09 PM.
Project "C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build\binding.sln]
Done Building Project "C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build\binding.sln" (default target) (1) ->
(oracledb target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.45
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm verb lifecycle oracledb@1.13.1~install: unsafe-perm in lifecycle true
npm verb lifecycle oracledb@1.13.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\[username]\Desktop\Oracle\node_modules\oracledb\node_modules\.bin;C:\Users\[username]\Desktop\Oracle\node_modules\.bin;C:\Users\[username]\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\[username]\bin;C:\Python27;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft Application Virtualization Client;C:\Program Files\nodejs;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_131\bin;D:\Oracle\instantClient;C:\Users\[username]\AppData\Roaming\npm;D:\vasu\apache-maven-3.1.1\bin;D:\Oracle\instantClient;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
npm verb lifecycle oracledb@1.13.1~install: CWD: C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm info lifecycle oracledb@1.13.1~install: Failed to exec install script
npm verb unlock done using C:\Users\[username]\AppData\Roaming\npm-cache\_locks\staging-e47d8a858ff9115b.lock for C:\Users\[username]\Desktop\Oracle\node_modules\.staging
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\nan
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm verb gentlyRm don't care about contents; nuking C:\Users\[username]\Desktop\Oracle\node_modules\oracledb
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\[username]\Desktop\Oracle\package.json'
npm verb enoent ENOENT: no such file or directory, open 'C:\Users\[username]\Desktop\Oracle\package.json'
npm verb enoent This is most likely not a problem with npm itself
npm verb enoent and is related to npm not being able to find a file.
npm verb enoent
npm WARN Oracle No description
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN Oracle No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN Oracle No README data
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN Oracle No license field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN Error: EPERM: operation not permitted, rmdir 'C:\Users\[username]\Desktop\Oracle\node_modules'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'C:\Users\[username]\Desktop\Oracle\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'C:\\Users\\[username]\\Desktop\\Oracle\\node_modules' }
npm verb
npm verb Please try running this command again as root/Administrator.
npm verb stack Error: oracledb@1.13.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:885:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid oracledb@1.13.1
npm verb cwd C:\Users\[username]\Desktop\Oracle
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb" "--toolset=oci12.1-msvs2013" "--verbose"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\[username]\Desktop\Oracle\npm-debug.log
```

</details>

I need some help in understanding the error that when I configured node-gyp for msvs2013 then why am I getting the error that I need the MS Visual Studio 2005 or .NET framework 2.0 SDK . I am more interested in what is going behind the screen when we are installing this 'oracledb' package. I have Python 2.7 installed on my system and added to path variable.

**Comment by bnoordhuis** [comment]
The error is this:

> MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.

And it's printed by msbuild (i.e., not node-gyp.)

You probably need to run vcvarsall.bat from VS 2013 to set up the environment and if that doesn't work, try https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#prerequisites

**Comment by nick250386** [comment]
I did the steps mentioned in 'Option 1' and the 'windows-build-tools' was installed successfully. All the details and the errors that I shared above are after completing the 'Option 1'.
Based on this information do want to share some more information on what I should do to fix this issue ?

**Comment by bnoordhuis** [comment]
I don't have much to add to what I wrote earlier.  In a nutshell, it's a configuration issue local to your system.

Aside: you are using an unsupported version of node.js.
