### ISSUE TITLE
After macOS update: npm install error - requires xcode

### ISSUE THREAD

**Issue by ChaddPortwine** [nodejs/node-gyp#1318]
* **Node Version**:  `node -v7.9.0` and `npm -v4.2.0`
* **Platform**: macOS 10.12.6
* **Compiler**:  gcc
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* **Module**: googleapis

After updating macOS, I'm struggling to install npm packages.

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Silver-Sliver:people-is dchaddportwine$ npm install googleapis --save

> unix-dgram@0.2.2 install /Users/dchaddportwine/Sites/people-is/node_modules/unix-dgram
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../src/unix_dgram.cc:5:
In file included from ../node_modules/nan/nan.h:182:
../node_modules/nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:3346:3: note: 'CloneElementAt' has been explicitly marked deprecated here
  V8_DEPRECATED("Cloning is not supported.",
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:4490:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:3026:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dchaddportwine/Sites/people-is/node_modules/unix-dgram
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
people-is@1.0.0 /Users/dchaddportwine/Sites/people-is
└─┬ googleapis@22.2.0
  ├── async@2.3.0
  ├─┬ google-auth-library@0.10.0
  │ └── lodash.noop@3.0.1
  └── string-template@1.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 (node_modules/unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

</details>

**Comment by bnoordhuis** [comment]
The xcodebuild lines in the log lines are red herrings, you can ignore them.  It says 'error' but they're really just informational from node-gyp's perspective.

The issue is that you're trying to install an old version of unix-dgram, v0.2.2.  Update to the latest - v2.0.1 - and all should be well.

**Comment by ChaddPortwine** [comment]
Thank you for the info.

Why does it look like node-gyp is failing the unix-dgram update? I'm missing something?

```
Silver-Sliver:people-is dchaddportwine$ npm uninstall unix-dgram
- bindings@1.1.1 node_modules/bindings
- nan@2.3.5 node_modules/unix-dgram/node_modules/nan
- unix-dgram@2.0.1 node_modules/unix-dgram
Silver-Sliver:people-is dchaddportwine$ npm install unix-dgram

> unix-dgram@0.2.2 install /Users/dchaddportwine/Sites/people-is/node_modules/ain2/node_modules/unix-dgram
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../src/unix_dgram.cc:5:
In file included from ../../nan/nan.h:182:
../../nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:3346:3: note: 'CloneElementAt' has been explicitly marked deprecated here
  V8_DEPRECATED("Cloning is not supported.",
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:4490:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:3026:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dchaddportwine/Sites/people-is/node_modules/ain2/node_modules/unix-dgram
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

> unix-dgram@2.0.1 install /Users/dchaddportwine/Sites/people-is/node_modules/unix-dgram
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
  SOLINK_MODULE(target) Release/unix_dgram.node
people-is@1.0.0 /Users/dchaddportwine/Sites/people-is
└─┬ unix-dgram@2.0.1
  ├── bindings@1.1.1
  └── nan@2.3.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 (node_modules/ain2/node_modules/unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by bnoordhuis** [comment]
It's because the package you're trying to install, ain2, depends on an old version of unix-dgram.  You'll have to take that up with them.
