### ISSUE TITLE
msbuild error when trying to install sqlite3

### ISSUE THREAD

**Issue by benschool** [nodejs/node-gyp#1338]
* **Node Version**: ` 9.1.0` and `npm v5.5.1` 
On windows 10

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\Ben\Desktop\Rankbot>npm install sqlite3

> sqlite3@3.1.13 install C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@9.1.0 (node-v59 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  'python' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exi
ted with code 1. [C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ben\Desktop\Rankbot\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ben\\Desktop\\Rankbot\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Ben\\Desktop\\Rankbot\\node_modules\\sqlite3\\lib\\binding\\node-v59-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Ben\\Desktop\\Rankbot\\node_modules\\sqlite3\\lib\\binding\\node-v59-win32-x64"
gyp ERR! cwd C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Ben\Desktop\Rankbot\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3\lib\binding\node-v59-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3\lib\binding\node-v59-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:135:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ben\\Desktop\\Rankbot\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3
node-pre-gyp ERR! node -v v9.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Ben\Desktop\Rankbot\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3\lib\binding\node-v59-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Ben\Desktop\Rankbot\node_modules\sqlite3\lib\binding\node-v59-win32-x64' (1)
```

</details>

I have tried installing visual studio 2015/2017, the compiling tools and the npm install for the windows stuff but none of it changes the error. I have been googling for over 4 hours now, and it feels like ive tried everything.

**Comment by bnoordhuis** [comment]
You need to install python.  Check the readme, it's listed in the prerequisites.

**Comment by benschool** [comment]
I have already installed python 2.7 and newer. Python is bit the issue

**Comment by bnoordhuis** [comment]
Then open an issue with node-sqlite3.  That error looks to originate from its install script.
