### ISSUE TITLE
Not able to install dependency node-gyp

### ISSUE THREAD

**Issue by newthings4learning** [nodejs/node-gyp#1342]
* **Node Version**: v9.2.0 and 5.5.1
* **Platform**: Microsoft Windows 10 Enterprise 
* **Compiler**: 10.0.10586 N/A Build 10586 
* **Module**:  node-gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\WINDOWS\system32>npm --msvs_version=2015 install -g botpress
npm WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports Node v6.4.0+). Also read the breaking changes for upgrading from v2 to v3 at https://github.com/niftylettuce/email-templates#v3-breaking-changes 📫
[..................] - fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] - fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] \ fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] \ fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] - fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] \ fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] | fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] - fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] - fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] - fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports N[..................] / fetchMetadata: WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports Nnpm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
C:\Users\jonny\AppData\Roaming\npm\bp -> C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\bin\botpress
C:\Users\jonny\AppData\Roaming\npm\botpress -> C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\bin\botpress

> sqlite3@3.1.8 install C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\jonny\\AppData\\Roaming\\npm\\node_modules\\botpress\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@9.2.0 | win32 | ia32
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-win32-ia32.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-win32-ia32.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@9.2.0 (node-v59 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-win32-ia32.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]

C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32 --python=C:\Users\jonny\.windows-build-tools\python27\python.exe --msvs_version=2015 )  else (node "" configure --fallback-to-build --module=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32 --python=C:\Users\jonny\.windows-build-tools\python27\python.exe --msvs_version=2015 )

C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32 )  else (node "" build --fallback-to-build --module=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\Release\\sqlite3.lib
  database.cc
  node_sqlite3.cc
  statement.cc
  win_delay_load_hook.cc
c:\users\jonny\appdata\roaming\npm\node_modules\botpress\node_modules\sqlite3\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declar
ed deprecated (compiling source file ..\src\statement.cc) [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  c:\users\jonny\.node-gyp\9.2.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\statement.cc)
c:\users\jonny\appdata\roaming\npm\node_modules\botpress\node_modules\sqlite3\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declar
ed deprecated (compiling source file ..\src\node_sqlite3.cc) [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  c:\users\jonny\.node-gyp\9.2.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\node_sqlite3.cc)
c:\users\jonny\appdata\roaming\npm\node_modules\botpress\node_modules\sqlite3\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declar
ed deprecated (compiling source file ..\src\database.cc) [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  c:\users\jonny\.node-gyp\9.2.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\database.cc)
..\src\statement.cc(103): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': can
not convert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\node_
sqlite3.vcxproj]
  ..\src\statement.cc(103): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\statement.cc(277): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress
\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\database.cc(133): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cann
ot convert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\node_s
qlite3.vcxproj]
  ..\src\database.cc(133): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\database.cc(134): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cann
ot convert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\build\node_s
qlite3.vcxproj]
  ..\src\database.cc(134): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\jonny\\AppData\\Roaming\\npm\\node_modules\\botpress\\node_modules\\sqlite3\\lib\\binding\\node-v59-win32-ia32\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\jonny\\AppData\\Roaming\\npm\\node_modules\\botpress\\node_modules\\sqlite3\\lib\\binding\\node-v59-win32-ia32"
gyp ERR! cwd C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\jonny\\AppData\\Roaming\\npm\\node_modules\\botpress\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\lib\binding\node-v59-win32-ia32' (1)
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\jonny\AppData\Roaming\npm\node_modules\botpress\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\jonny\\AppData\\Roaming\\npm\\node_modules\\botpress\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\tar\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\jonny\\AppData\\Roaming\\npm\\node_modules\\botpress\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\node_modules\\tar\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2017-11-19T21_45_42_861Z-debug.log](https://github.com/nodejs/node-gyp/files/1486028/2017-11-19T21_45_42_861Z-debug.log)

```

</details>

**Comment by bnoordhuis** [comment]
The issue is not with node-gyp but with the add-on you're trying to build, sqlite3.  Try upgrading it to the latest version and if that doesn't help, file an issue with its maintainers.  Good luck!
