### ISSUE TITLE
windows10  “.vcxproj” files  generation error！

### ISSUE THREAD

**Issue by moke666** [nodejs/node-gyp#1343]
“node-gpy configure” is ok ；
“node-gpy build” is error；
error：LINK : fatal error LNK1181:Unable to open input file "node.lib" [E:\node_c++\build\hello.vcxproj]
error reason：
.vcxproj files:
```
<Link>    <AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;&quot;C:\Users\.net\.node-gyp\8.4.0\x64\node.lib&quot;;node.lib</AdditionalDependencies>
```
correct “.vcxproj” files:
```
<Link>    <AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;&quot;C:\Users\.net\.node-gyp\8.4.0\x64\node.lib&quot;</AdditionalDependencies>
```
Remove the last "node.lib"。

System Windows_NT 10.0.15063
node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2

```
PS E:\node_c++> node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp info spawn E:\Program Files (x86)\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
LINK : fatal error LNK1181: Unable to open input file“node.lib” [E:\node_c++\build\hello.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `E:\Program Files (x86)\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code:
1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\.net\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\.net\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd E:\node_c++
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
What does your binding.gyp look like?

**Comment by moke666** [comment]
`{
    "targets":[
        {
            "target_name":'hello',
            'sources':[
                'hello.cc'
            ],
            'conditions':[
                [
                    'OS=="win"',
                    {'libraries':['-lnode.lib']}
                ]
            ]
        }
    ]
}`

**Comment by bnoordhuis** [comment]
There's your answer, right?  You shouldn't link to node.lib yourself when node-gyp does too.
