### ISSUE TITLE
what is missing from this npm install

### ISSUE THREAD

**Issue by DaunGe** [nodejs/node-gyp#1354]
* **Node Version**:  
Node version : V8.9.1
npm version : 5.5.1
* **Platform**: 
platform :Linux localhost 4.14.2-1-default #1 SMP PREEMPT Fri Nov 24 08:20:07 UTC 2017 (b0610fc) x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: 
compiler : gcc version 7.2.1 20171020 [gcc-7-branch revision 253932] (SUSE Linux) 
* **Module**: 
Module :i try to build  [Starter-Kit-2018](https://github.com/codingphasedotcom/Starter-Kit-2018)

Hello there admin Dev i try to run

>  npm install

i get an issue that im unable to figure its work. 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
localhost:/home/daunjrk/projects/dashboard # npm install
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated

> node-sass@3.13.1 install /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node8 /home/daunjrk/projects/dashboard/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node8',
gyp verb cli   '/home/daunjrk/projects/dashboard/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.1
gyp verb command install [ '8.9.1' ]
gyp verb install input version string "8.9.1"
gyp verb install installing version: 8.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.1
gyp verb build dir attempting to create "build" dir: /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/daunjrk/projects/dashboard/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/daunjrk/projects/dashboard/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/daunjrk/projects/dashboard/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.node-gyp/8.9.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/root/.node-gyp/8.9.1/include/node -I/root/.node-gyp/8.9.1/src -I/root/.node-gyp/8.9.1/deps/uv/include -I/root/.node-gyp/8.9.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++: Command not found
make: *** [src/libsass.target.mk:139: Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
make: Leaving directory '/home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/daunjrk/projects/dashboard/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.2-1-default
gyp ERR! command "/usr/bin/node8" "/home/daunjrk/projects/dashboard/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/daunjrk/projects/dashboard/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN RockyBoy@1.0.0 No repository field.
npm WARN The package babel-preset-stage-0 is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-08T08_45_09_082Z-debug.log

```

</details>

try to look back from your archive issue on 

> [trying to 'npm install', getting node-gyp rebuild errors](https://github.com/nodejs/node-gyp/issues/809)

im misleading.

may u see what i can't see from what i should do to practice.

thanks before.

**Comment by bnoordhuis** [comment]
Install the gcc-c++ package.  It sounds like you only have the C compiler installed right now, not the C++ compiler.

**Comment by DaunGe** [comment]
yoo @bnoordhuis 
 nice to have u for answering..

thanks to the power open source and free software movement.
