### ISSUE TITLE
Failed to build with my own so file

### ISSUE THREAD

**Issue by jimmylin212** [nodejs/node-gyp#1357]
* **Node Version**: v8.9.2
* **Platform**: Ubuntu x86_64 GNU/Linux
* **Compiler**: gcc version 4.9.2 (Debian 4.9.2-10)
* **Module**: my own `.so`

I would like to build my own `.so` file, not sure what is the problem. My c++ code is below:
```c++
#include <nan.h>
#include "/path/to/file.h"

void PrintDebug(const Nan::FunctionCallbackInfo<v8::Value>& printString) {
  printDebug(printString);  // printDebug is in my .h file
}

void InitChifDll(v8::Local<v8::Object> exports) {
  exports->Set(Nan::New("hello").ToLocalChecked(),
               Nan::New<v8::FunctionTemplate>(PrintDebug)->GetFunction());
}

NODE_MODULE(chifdll, InitChifDll)
```

and the content of my `binding.gyp` file
```json
{
      "target_name": "mysofile",
      "type": "static_library",
      "sources": ["/path/to/libfile.so", "main.cc"],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
      ],
      "libraries": ["-L/path/to/", "-lfile"],
      "ldflags": ["-Wl,-rpath,/path/to/libfile.so"],
      "link_settings" : {
        "libraries" : ["-ldl"]
      }
    }
```

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/jimmy/dev_blobclient_addon/build'
  CXX(target) Release/obj.target/chifdll/main.o
../main.cc:4:1: error: expected initializer before 'void'
 void PrintDebug(const Nan::FunctionCallbackInfo<v8::Value>& printString) {
 ^
../main.cc: In function 'void InitChifDll(v8::Local<v8::Object>)':
../main.cc:10:47: error: 'PrintDebug' was not declared in this scope
                Nan::New<v8::FunctionTemplate>(PrintDebug)->GetFunction());
                                               ^
chifdll.target.mk:95: recipe for target 'Release/obj.target/chifdll/main.o' failed
make: *** [Release/obj.target/chifdll/main.o] Error 1
make: Leaving directory '/home/jimmy/dev_blobclient_addon/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jimmy/.nvm/versions/node/v8.9.2/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/home/jimmy/.nvm/versions/node/v8.9.2/bin/node" "/home/jimmy/.nvm/versions/node/v8.9.2/bin/node-gyp" "build"
gyp ERR! cwd /home/jimmy/dev_blobclient_addon
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

</details>

Thank you very much.

**Comment by bnoordhuis** [comment]
Back-link to https://github.com/nodejs/nan/issues/720 for posterity.  I'll note that this isn't a node-gyp issue either.

I can't tell from the output what the exact issue is but it's a simple syntax error.  I'd take a hard look at that header file if I were you.

**Comment by jimmylin212** [comment]
Thank you for your hint, I found that there is syntax error in `.h` file

**Comment by bnoordhuis** [comment]
Good to hear.  I'll close this out.
