### ISSUE TITLE
Python executable "python" is v3.6.4, which is not supported by gyp

### ISSUE THREAD

**Issue by stonebig** [nodejs/node-gyp#1361]
hi dear gyp team, 

Apparently gyp is not yet supporting  python-3.6.4 on windows. 
Is it just a disclaimer of a true problem ?

````
node C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.4.amd64\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[1/2] ⠠ canvas: gyp info using node@6.11.5 | win32 | x64
[2/2] ⠠ jupyter-matplotlib
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
warning Error running install script for optional dependency: "C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas
Output:
C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.11.5 | win32 | x64
gyp ERR! configure error 
gyp ERR! stack Error: Python executable \"C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\python.EXE\" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)
gyp ERR! stack     at C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)
gyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\WinPython\\\\basedir36\\\\buildQt5\\\\winpython-64bit-3.6.x.0\\\\python-3.6.4.amd64\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\basedir36\\\\buildQt5\\\\winpython-64bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuisuccess Saved lockfile.
````

**Comment by bnoordhuis** [comment]
Python 2 is mandatory.  GYP - the build tool that puts the 'gyp' in node-gyp - is strictly a python2 project.
