### ISSUE TITLE
Node can't find an installed module

### ISSUE THREAD

**Issue by Levileadermc** [nodejs/node-gyp#1362]
* **Node Version**:  v8.9.3
* **Platform**:  Windows 10 64 Bit
* **Compiler**:  I don't know how to view it
* **Module**:  Floodjs ( Testing my webserver )

<details><summary>Verbose output (from npm or node-gyp):</summary>

I don't believe I need any logs, as the only problem I have is that NodeJS won't use the module, I have it installed both globally and locally, but it still can't use it

**Comment by gibfahn** [comment]
For general help can you please raise an issue in the help repo: https://github.com/nodejs/help This has nothing to do with node-gyp.

As for using this module, it's just [a single 60 line js file](https://github.com/afshinm/flood.js/blob/master/flood.js), just follow the instructions in [the README](https://github.com/afshinm/flood.js/blob/master/README.md): 

```bash
▶▶▶ npm init -y                                                                      ~/tmp/testdir
Wrote to /Users/gib/tmp/testdir/package.json:

{
  "name": "testdir",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
▶▶▶ npm install floodjs                                                              ~/tmp/testdir
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN testdir@1.0.0 No description
npm WARN testdir@1.0.0 No repository field.

+ floodjs@0.1.0
added 3 packages in 1.253s
▶▶▶ ls                                                                            ~/tmp/testdir 2s
node_modules      package-lock.json package.json
▶▶▶ cd node_modules/floodjs                                                          ~/tmp/testdir
README.md    flood.js     package.json
▶▶▶ node flood.js -h 127.0.0.1 -t 1000                          ~/tmp/testdir/node_modules/floodjs
dgram.js:419
    throw new errors.RangeError('ERR_SOCKET_BAD_PORT');
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536
    at Socket.send (dgram.js:419:11)
    at /Users/gib/tmp/testdir/node_modules/floodjs/flood.js:54:14
    at udpFlood (/Users/gib/tmp/testdir/node_modules/floodjs/flood.js:58:7)
    at Object.<anonymous> (/Users/gib/tmp/testdir/node_modules/floodjs/flood.js:23:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
▶▶▶ node flood.js -h 127.0.0.1 -t 1000 -p 80                    ~/tmp/testdir/node_modules/floodjs
/Users/gib/tmp/testdir/node_modules/floodjs/flood.js:55
        if (err) throw err;
                 ^

Error: send EMSGSIZE 127.0.0.1:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:498:11)
▶▶▶                                                          ~/tmp/testdir/node_modules/floodjs 1s
```

Basically you just download the file, `npm install` the dependencies and run it with `node path/to/flood.js`. The script errors out for me, if you have problems raise an issue in that repo.
