### ISSUE TITLE
Windows 10 :  Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32

### ISSUE THREAD

**Issue by nimatullah** [nodejs/node-gyp#1369]
* **Node Version**: v9.3.0 
* **NPM Version**: 5.5.1
* **Platform**:  Windows 10
* **Compiler**:  node-gyp build
* **Module**: 

```
PS C:\Users\nimatullah.razmjo\workstation\jobsaf-server> node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.3.0 | win32 | x64
gyp ERR! build error
gyp ERR! stack Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32
gyp ERR! stack ERROR: Registry editing has been disabled by your administrator.
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at C:\Users\nimatullah.razmjo\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:138:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:279:5)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
gyp ERR! stack     at Socket.emit (events.js:159:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:568:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nimatullah.razmjo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\nimatullah.razmjo\workstation\jobsaf-server
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

```

**Comment by bnoordhuis** [comment]
Passing `--msvs_version=2015` (assuming you're using VS 2015) might work.  If it doesn't, you should go talk to your system administrator.

**Comment by NewBeing** [comment]
I met the same error, but don't understand how to fix it. Could you please make in clear ??  @bnoordhuis

**Comment by junedsaleh** [comment]
i met the same error also , i have vs 2015 it not works

**Comment by joaocgreis** [comment]
If you have this line there's not much we can do to help:
```
gyp ERR! stack ERROR: Registry editing has been disabled by your administrator.
```
You have to ask your administrator to fix this issue. A newer version of Visual Studio might work.

If that line is not printed, please paste the output of `node-gyp rebuild --verbose`
