### ISSUE TITLE
UNCAUGHT EXCEPTION gyp ERR! stack const Hoek = require('hoek'); SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by lucasmellos** [nodejs/node-gyp#1374]
I'm trying rebuild my project after run <code>npm install --unsafe-perm</code> but this error broke my node-gyp.

* **Node Version**:  0.12.6
* **Platform**:  Raspbian Wheenzy
* **Compiler**: gcc version 4.6.3 (Debian 4.6.3-14+rpi1) 
* **Module**: node-gyp

<details>

```
# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@0.12.6 | linux | arm
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack /usr/local/lib/node_modules/node-gyp/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
gyp ERR! stack const Hoek = require('hoek');
gyp ERR! stack ^^^^^
gyp ERR! stack SyntaxError: Use of const in strict mode.
gyp ERR! stack     at exports.runInThisContext (vm.js:73:16)
gyp ERR! stack     at Module._compile (module.js:443:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
gyp ERR! stack     at Module.load (module.js:355:32)
gyp ERR! stack     at Function.Module._load (module.js:310:12)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! stack     at require (module.js:384:17)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-gyp/node_modules/request/node_modules/hawk/lib/index.js:5:33)
gyp ERR! stack     at Module._compile (module.js:460:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
gyp ERR! System Linux 3.18.7+
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/conducao_app
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
```

</details>

**Comment by bnoordhuis** [comment]
You can either upgrade node or downgrade node-gyp.  We dropped support for node.js < v4.x last year.

You'll need g++ >= 4.8.5 if you upgrade.  You may have to pin dependencies to older versions if you downgrade - those dependencies may no longer support v0.12.x, as is the case here.
