### ISSUE TITLE
Please, Please, Please make node-gyp work witn Python 3 so it is compatible with conda package manager.

### ISSUE THREAD

**Issue by abalter** [nodejs/node-gyp#1399]
* **Node Version**: v8.9.3
* **Platform**: Windows - Ubuntu (WSL)
* **Module**: https://github.com/notablemind/jupyter-nodejs

But I run into this error all the time, and so do others.

I don't really understand the problem. But I use conda package manager, and I installed node in that environment. I very frequently run into `node-gyp` related build errors. It seems to have something to do with python2 vs python3. But for heaven's sakes--we're trying to do science here. Can we please have a node gyp that plays nice with science tools?

```
balter@spectre:~/jupyter-nodejs$ npm install && node install.js

> zmq@2.15.3 install /home/balter/jupyter-nodejs/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/home/balter/jupyter-nodejs/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:10: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
          ^~~~~~~
compilation terminated.
zmq.target.mk:95: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/home/balter/jupyter-nodejs/node_modules/zmq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/balter/conda/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/home/balter/conda/bin/node" "/home/balter/conda/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/balter/jupyter-nodejs/node_modules/zmq
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package mkdirp is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/balter/.npm/_logs/2018-03-25T18_25_46_243Z-debug.log

```

</details>

**Comment by bnoordhuis** [comment]
Your issue is unrelated to python 2 vs. 3.  You're trying to install a module - zmq - that has a dependency on the zeromq library.  Check that module's documentation for prerequisites.
