### ISSUE TITLE
pentium 2 as identified as cpu but not accurate

### ISSUE THREAD

**Issue by boistordu** [nodejs/node-gyp#1402]
#

* **Node Version**: node -v
v9.3.0
npm -v
5.6.0
[vigilian@seedBSD /usr/local/etc/rc.d]$ 
* **Platform**: FREEBSD11.1
* **Compiler**: FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
* **Module**: fs-extra 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npm install fs-extra

> argon2@0.16.2 install /usr/home/flood/flood/node_modules/argon2
> node-gyp rebuild

gmake: Entering directory '/usr/home/flood/flood/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
error: unknown target CPU 'pentium2'
gmake: *** [libargon2.target.mk:112: Release/obj.target/libargon2/argon2/src/opt.o] Error 1
gmake: Leaving directory '/usr/home/flood/flood/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System FreeBSD 11.1-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/flood/flood/node_modules/argon2
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.16.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flood/.npm/_logs/2018-03-28T08_01_55_435Z-debug.log
```

```
40799 silly saveTree |   | +-- is-fullwidth-code-point@2.0.0
40799 silly saveTree |   | `-- strip-ansi@4.0.0
40799 silly saveTree |   |   `-- ansi-regex@3.0.0
40799 silly saveTree |   +-- which-module@2.0.0
40799 silly saveTree |   `-- yargs-parser@7.0.0
40799 silly saveTree `-- xmlrpc@1.3.2
40799 silly saveTree   `-- xmlbuilder@8.2.2
40800 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
40801 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
40802 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
40802 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
40802 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   freebsd
40802 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
40803 verbose stack Error: argon2@0.16.2 install: `node-gyp rebuild`
40803 verbose stack Exit status 1
40803 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
40803 verbose stack     at EventEmitter.emit (events.js:159:13)
40803 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
40803 verbose stack     at ChildProcess.emit (events.js:159:13)
40803 verbose stack     at maybeClose (internal/child_process.js:943:16)
40803 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
40804 verbose pkgid argon2@0.16.2
40805 verbose cwd /usr/home/flood/flood
40806 verbose FreeBSD 11.1-RELEASE
40807 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fs-extra"
40808 verbose node v9.3.0
40809 verbose npm  v5.6.0
40810 error code ELIFECYCLE
40811 error errno 1
40812 error argon2@0.16.2 install: `node-gyp rebuild`
40812 error Exit status 1
40813 error Failed at the argon2@0.16.2 install script.
40813 error This is probably not a problem with npm. There is likely additional logging output above.
40814 verbose exit [ 1, true ]
```
</details>

```
sudo dmesg | grep -i cpu
Password:
CPU: QEMU Virtual CPU version 2.5+ (4200.06-MHz K8-class CPU)
FreeBSD/SMP: Multiprocessor System Detected: 2 CPUs
SMP: AP CPU #1 Launched!
cpu0: <ACPI CPU> on acpi0
cpu1: <ACPI CPU> on acpi0
```

**Comment by bnoordhuis** [comment]
That's an issue with the module you're trying to build, argon2, not node-gyp.  Get in touch with its authors.  node-gyp doesn't set `-march=...` or `-mcpu=...`.
