### ISSUE TITLE
Installation issue mariasql

### ISSUE THREAD

**Issue by kamote** [nodejs/node-gyp#1403]
* **Node Version**: v8.9.0
* **Platform**:  `Darwin Randys-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
* **Compiler**: `4.2.1`
* **Module**: `mariasql@0.2.6`
* **NPM Log**: https://gist.github.com/kamote/b3d7c7db199d18a56d46010b40cc4489
```
> mariasql@0.2.6 install /Users/kamote/Documents/GitHub/knex/node_modules/mariasql
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aestables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/algebra.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/arc4.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/asn.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/bftables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/blowfish.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/coding.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/des.o
../deps/libmariadbclient/extra/yassl/taocrypt/src/des.cpp:227:5: warning: 'register' storage class specifier is deprecated and incompatible with C++1z
      [-Wdeprecated-register]
    register int i,j,l;
    ^~~~~~~~~
../deps/libmariadbclient/extra/yassl/taocrypt/src/des.cpp:227:5: warning: 'register' storage class specifier is deprecated and incompatible with C++1z
      [-Wdeprecated-register]
    register int i,j,l;
    ^~~~~~~~~
../deps/libmariadbclient/extra/yassl/taocrypt/src/des.cpp:227:5: warning: 'register' storage class specifier is deprecated and incompatible with C++1z
      [-Wdeprecated-register]
    register int i,j,l;
    ^~~~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/dh.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/dsa.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/file.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/hash.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/hc128.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/integer.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md2.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md4.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md5.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/misc.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/rabbit.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/random.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/ripemd.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/rsa.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/sha.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/tftables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/twofish.o
  LIBTOOL-STATIC Release/taocrypt.a
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/buffer.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/cert_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/crypto_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/handshake.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/lock.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/log.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/socket_wrapper.o
../deps/libmariadbclient/extra/yassl/src/socket_wrapper.cpp:49:15: warning: unused variable 'SOCKET_EINVAL' [-Wunused-const-variable]
    const int SOCKET_EINVAL = EINVAL;
              ^
1 warning generated.
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/ssl.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/timer.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_error.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_imp.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_int.o
../deps/libmariadbclient/extra/yassl/src/yassl_int.cpp:912:12: warning: unused variable 'handshake_order' [-Wunused-const-variable]
const char handshake_order[] = "Out of order HandShake Message!";
           ^
1 warning generated.
  LIBTOOL-STATIC Release/yassl.a
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/client.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/client_plugin.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/mysql_async.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/my_time.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/pack.o
  CXX(target) Release/obj.target/clientlib/deps/libmariadbclient/sql/net_serv.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql/password.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/libmysql/errmsg.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/libmysql/libmysql.o
../deps/libmariadbclient/libmysql/libmysql.c:1421:12: warning: address of array 'net->last_error' will always evaluate to 'true' [-Wpointer-bool-conversion]
  if (net->last_error && net->last_error[0])
      ~~~~~^~~~~~~~~~ ~~
1 warning generated.
  LIBTOOL-STATIC Release/clientlib.a
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/array.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/charset-def.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/charset.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/errors.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/hash.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/list.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_arr_appstr.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_dirname.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_fn_ext.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_format.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_loadpath.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_pack.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_path.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_qsort.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_unixpath.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_wcomp.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mulalloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_access.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_alloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_compress.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_context.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_default.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_div.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_error.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_fopen.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_fstream.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_getsystime.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_getwd.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_init.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_lib.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_malloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_mess.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_once.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_open.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_pthread.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_read.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_seek.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_static.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_symlink.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_thr_init.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_write.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/safemalloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/string.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/thr_mutex.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/typelib.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_sync.o
../deps/libmariadbclient/mysys/my_sync.c:136:19: warning: unused variable 'cur_dir_name' [-Wunused-const-variable]
static const char cur_dir_name[]= {FN_CURLIB, 0};
                  ^
1 warning generated.
  LIBTOOL-STATIC Release/mysys.a
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_aes.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_md5.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_rnd.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_sha1.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_sha2.o
  LIBTOOL-STATIC Release/mysys_ssl.a
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/bchange.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/bmove_upp.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-big5.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-bin.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-cp932.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-czech.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-eucjpms.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-euc_kr.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-extra.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-gb2312.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-gbk.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-latin1.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-mb.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-simple.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-sjis.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-tis620.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-uca.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-ucs2.o
../deps/libmariadbclient/strings/ctype-ucs2.c:57:1: warning: unused function 'my_bincmp' [-Wunused-function]
my_bincmp(const uchar *s, const uchar *se,
^
1 warning generated.
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-ujis.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-utf8.o
../deps/libmariadbclient/strings/ctype-utf8.c:4894:19: warning: unused function 'bincmp' [-Wunused-function]
static inline int bincmp(const uchar *s, const uchar *se,
                  ^
../deps/libmariadbclient/strings/ctype-utf8.c:5066:1: warning: unused function 'my_tosort_utf8mb3' [-Wunused-function]
my_tosort_utf8mb3(MY_UNICASE_INFO *uni_plane, my_wc_t *wc)
^
../deps/libmariadbclient/strings/ctype-utf8.c:7279:1: warning: unused function 'bincmp_utf8mb4' [-Wunused-function]
bincmp_utf8mb4(const uchar *s, const uchar *se,
^
3 warnings generated.
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-win1250ch.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/dtoa.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/int2str.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/is_prefix.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/llstr.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/longlong2str.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/my_strtoll10.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/my_vsnprintf.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/str2int.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strcend.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strcont.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strend.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strfill.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmake.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmov_overlapp.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strnmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strxmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strxnmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/str_alloc.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/xml.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strnlen.o
  LIBTOOL-STATIC Release/strings.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/strings.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kamote/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/kamote/.nvm/versions/node/v8.9.0/bin/node" "/Users/kamote/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kamote/Documents/GitHub/knex/node_modules/mariasql
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mariasql@0.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kamote/.npm/_logs/2018-03-29T17_16_41_495Z-debug.log
```

**Comment by maclover7** [comment]
Per mariasql's README, looks like your version of Node.js [does not meet their minimum of v10 of higher](https://github.com/mscdex/node-mariasql#requirements). Going to close this out as a mariasql-specific issue.

**Comment by mmozcelik** [comment]
@maclover7 I am having the same issue with node 18, and also README node requirement is >0.10.0 not >10.x. 
@kamote have you found a solution for the issue?

**Comment by cclauss** [comment]
https://github.com/mscdex/node-mariasql/issues/207
