### ISSUE TITLE
npm install ref fails on mac node version  9.0.0 >=  

### ISSUE THREAD

**Issue by DorMitzafon** [nodejs/node-gyp#1405]
* **Node Version**:  v9.10.0
* **Platform**:  macOS sierra (Darwin 16.7.0)

* **Module**: ref

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> ref@1.3.5 install /Users/dor.m/src/player-e2e/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:643:8: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  Nan::ForceSet(target, Nan::New<v8::String>("endianness").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>...
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:644:8: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  Nan::ForceSet(target, Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  SOLINK_MODULE(target) Release/binding.node

> ffi@2.2.0 install /Users/dor.m/src/player-e2e/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:58:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_OK);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:59:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_BAD_TYPEDEF);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:60:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_BAD_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:63:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_DEFAULT_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:64:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_FIRST_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:65:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_LAST_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:81:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_SYSV);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:83:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_UNIX64);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:88:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_LAZY);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:91:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_NOW);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:94:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_LOCAL);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:97:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_GLOBAL);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:100:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_NOLOAD);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:103:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_NODELETE);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:106:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_FIRST);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
       ^
../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:111:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:111:100: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:114:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_DEFAULT").ToLocalChecked(), WrapPointer((char *)RTLD_DEFAULT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:114:106: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("RTLD_DEFAULT").ToLocalChecked(), WrapPointer((char *)RTLD_DEFAULT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:117:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_SELF").ToLocalChecked(), WrapPointer((char *)RTLD_SELF), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:117:100: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("RTLD_SELF").ToLocalChecked(), WrapPointer((char *)RTLD_SELF), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:120:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("RTLD_MAIN_ONLY").ToLocalChecked(), WrapPointer((char *)RTLD_MAIN_ONLY), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:120:110: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("RTLD_MAIN_ONLY").ToLocalChecked(), WrapPointer((char *)RTLD_MAIN_ONLY), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:123:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_ARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_arg)), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:123:116: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("FFI_ARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_arg)), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:124:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_SARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_sarg)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:124:118: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("FFI_SARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_sarg)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:125:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_type)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:125:118: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_type)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:126:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("FFI_CIF_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_cif)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:126:116: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("FFI_CIF_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_cif)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
../src/ffi.cc:132:11: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  target->ForceSet(Nan::New<String>("HAS_OBJC").ToLocalChecked(), Nan::New<Boolean>(hasObjc), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
          ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/ffi.cc:132:95: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("HAS_OBJC").ToLocalChecked(), Nan::New<Boolean>(hasObjc), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:198:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:202:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::PropertyAttribute'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:3166:51: note: passing argument to parameter 'value' here
                                     Local<Value> value,
                                                  ^
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:209:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dor.m/.node-gyp/9.10.0/include/node/v8.h:163:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../src/ffi.cc:111:20: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
  target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                   ^
24 warnings and 10 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dor.m/src/player-e2e/node_modules/ffi
gyp ERR! node -v v9.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is li
```

</details>

**Comment by bnoordhuis** [comment]
That's a problem with ffi, not node-gyp.  Report it to that project.
