### ISSUE TITLE
node-gyp build electron available library failure

### ISSUE THREAD

**Issue by 962702194** [nodejs/node-gyp#1406]
* node : 8.9.3
* electron : 1.7.11
* node-gyp : 3.6.2
* node-usb-detection : 1.0.2

Excuse me, I need to use electron to monitor USB, but I have been unable to recompile the available version of electron with node-gyp. The following are the mistakes, please help me.
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp info spawn C:\ProgramData\Anaconda2\python.EXE
gyp info spawn args [ 'C:\\Users\\yeyuru\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\regionstudio\\electron\\node_modules\\node-usb-detection\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\yeyuru\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\yeyuru\\.node-gyp\\iojs-1.7.11\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\yeyuru\\.node-gyp\\iojs-1.7.11',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\yeyuru\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\yeyuru\\.node-gyp\\iojs-1.7.11\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\regionstudio\\electron\\node_modules\\node-usb-detection',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\regionstudio\\electron\\node_modules\\node-usb-detection\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: D:\regionstudio\electron\node_modules\node-usb-detection) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\yeyuru\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yeyuru\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.11" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd D:\regionstudio\electron\node_modules\node-usb-detection
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by maclover7** [comment]
> gyp: binding.gyp not found (cwd: D:\regionstudio\electron\node_modules\node-usb-detection) while trying to load binding.gyp

Given this error, my suggestion would be to contact the maintainers of `node-usb-detection` and make sure that module is configured correctly. Unfortunately I don't think there's anything else node-gyp folks can help with, since that module is missing a binding.gyp file.
