### ISSUE TITLE
Python executable not found when installing cap module

### ISSUE THREAD

**Issue by ohmtrivedi** [nodejs/node-gyp#1410]
Hi,
I am facing issue with installing cap via npm.

* **Node Version**: node v8.6.0 and npm v5.3.0 and node-gyp v3.6.2
* **Platform**: Windows 10 Pro OS
* **Module**: cap (https://github.com/mscdex/cap)
* **Python**: Anaconda3 Distribution (3.6.4)

```
C:\Users\Ohm\Desktop\My Stuff\FAU Stuff\MS Thesis\Programming\node_modules\cap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Ohm\Anaconda3\python.exe", you can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack at PythonFinder. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ohm\Desktop\My Stuff\FAU Stuff\MS Thesis\Programming\node_modules\cap
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Ohm\Desktop\My Stuff\FAU Stuff\MS Thesis\Programming\package.json'
npm WARN Programming No description
npm WARN Programming No repository field.
npm WARN Programming No README data
npm WARN Programming No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Ohm\AppData\Roaming\npm-cache_logs\2018-04-10T06_35_11_811Z-debug.log
```

</details>

**Comment by FrZ-BR** [comment]
same

**Comment by thorizer** [comment]
same
