### ISSUE TITLE
node-gyp failed to build

### ISSUE THREAD

**Issue by chris-orchard** [nodejs/node-gyp#1413]
* **Node Version**: v9.11.1 npm 5.6.0
* **Platform**: Linux vagrant-ubuntu-trusty-64 3.13.0-74-generic

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
vagrant@vagrant-ubuntu-trusty-64:~$ npm install -g run-headless-chromium --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/vagrant/.nvm/versions/node/v9.11.1/bin/node',
npm verb cli   '/home/vagrant/.nvm/versions/node/v9.11.1/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'run-headless-chromium',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v9.11.1
npm verb npm-session 6e9e9acd44635041
npm http fetch GET 304 https://registry.npmjs.org/run-headless-chromium 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rimraf 31ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xvfb 73ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/sleep 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 22ms (from cache)
npm verb correctMkdir /home/vagrant/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/vagrant/.npm/_locks/staging-35ea7a94d803e245.lock for /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/.staging
npm info lifecycle run-headless-chromium@0.1.1~preuninstall: run-headless-chromium@0.1.1
npm info lifecycle run-headless-chromium@0.1.1~uninstall: run-headless-chromium@0.1.1
npm verb unbuild rmStuff run-headless-chromium@0.1.1 from /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules
npm info lifecycle run-headless-chromium@0.1.1~postuninstall: run-headless-chromium@0.1.1
npm info lifecycle nan@2.10.0~preinstall: nan@2.10.0
npm info lifecycle sleep@3.0.1~preinstall: sleep@3.0.1
npm info lifecycle run-headless-chromium@0.1.1~preinstall: run-headless-chromium@0.1.1
npm info linkStuff nan@2.10.0
npm verb linkBins nan@2.10.0
npm verb linkMans nan@2.10.0
npm info linkStuff sleep@3.0.1
npm verb linkBins sleep@3.0.1
npm verb linkMans sleep@3.0.1
npm info linkStuff run-headless-chromium@0.1.1
npm verb linkBins run-headless-chromium@0.1.1
npm verb linkBins [ { 'run-headless-chromium': './run-headless-chromium.js' },
npm verb linkBins   '/home/vagrant/.nvm/versions/node/v9.11.1/bin',
npm verb linkBins   true ]
npm verb linkMans run-headless-chromium@0.1.1
/home/vagrant/.nvm/versions/node/v9.11.1/bin/run-headless-chromium -> /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/run-headless-chromium.js
npm info lifecycle nan@2.10.0~install: nan@2.10.0
npm info lifecycle sleep@3.0.1~install: sleep@3.0.1

> sleep@3.0.1 install /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/home/vagrant/.nvm/versions/node/v9.11.1/bin/node',
gyp verb cli   '/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.11.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.11.1
gyp verb command install [ '9.11.1' ]
gyp verb install input version string "9.11.1"
gyp verb install installing version: 9.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.11.1
gyp verb build dir attempting to create "build" dir: /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/build
gyp verb build dir "build" dir needed to be created? /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/config.gypi
gyp verb common.gypi checking for gypi file: /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/.node-gyp/9.11.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vagrant/.node-gyp/9.11.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/vagrant/.node-gyp/9.11.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/vagrant/.node-gyp/9.11.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/build'
  g++ '-DNODE_GYP_MODULE_NAME=node_sleep' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_
EXTENSION' -I/home/vagrant/.node-gyp/9.11.1/include/node -I/home/vagrant/.node-gyp/9.11.1/src -I/home/vagrant/.node-gyp/9.11.1/deps/uv/include -I/home/vagrant/.node-gyp/9.11.1/deps
/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release
/obj.target/node_sleep/sleep.o.d.raw   -c -o Release/obj.target/node_sleep/sleep.o ../sleep.cc
make: g++: Command not found
make: *** [Release/obj.target/node_sleep/sleep.o] Error 127
make: Leaving directory `/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v9.11.1/bin/node" "/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm verb lifecycle sleep@3.0.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sleep@3.0.1~install: PATH: /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/.nvm/versions/node
/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep/node_modules/.bin:/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/.b
in:/home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/.bin:/home/vagrant/.nvm/versions/node/v9.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
es:/usr/local/games
npm verb lifecycle sleep@3.0.1~install: CWD: /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/run-headless-chromium/node_modules/sleep
npm info lifecycle sleep@3.0.1~install: Failed to exec install script
npm info lifecycle run-headless-chromium@0.1.1~install: run-headless-chromium@0.1.1
npm info lifecycle run-headless-chromium@0.1.1~postinstall: run-headless-chromium@0.1.1
npm verb unlock done using /home/vagrant/.npm/_locks/staging-35ea7a94d803e245.lock for /home/vagrant/.nvm/versions/node/v9.11.1/lib/node_modules/.staging
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 (node_modules/run-headless-chromium/node_modules/sleep):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm verb optional SKIPPING OPTIONAL DEPENDENCY:
npm verb optional Failed at the sleep@3.0.1 install script.
npm verb optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.

+ run-headless-chromium@0.1.1
updated 1 package in 1.495s
npm verb exit [ 0, true ]
npm info ok
```

</details>

I am getting the above error output when running `npm install -g run-headless-chromium --verbose`. 

This is after previously having the 'Warning "root" does not have permission to access the dev dir' issue and following the advice here to use nvm and avoid doing sudo npm install:
https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803

This seems to be similar to https://github.com/npm/npm/issues/19762 which was closed due to old versions of node and npm. I am on the latest of both.

**Comment by bnoordhuis** [comment]
> make: g++: Command not found

You need to install a C++ compiler.  Prerequisites are listed in the readme.

I can't tell what distro you're using but on Ubuntu it's `apt-get install build-essential`.
