### ISSUE TITLE
Node 10 compilation failure on Travis CI

### ISSUE THREAD

**Issue by xzyfer** [nodejs/node-gyp#1420]
* **Node Version**: 
```
$ node --version
v10.0.0
$ npm --version
5.6.0
```
* **Platform**: 
```
Ubuntu 14.04.5 LTS (Travis CI)
```
* **Compiler**:
```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
before_install.7
0.01s

$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
* **Module**: 
node-sass

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /opt/pyenv/shims/python
gyp info spawn args [ '/home/travis/build/sass/node-sass/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/build/sass/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/build/sass/node-sass/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/travis/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/travis/build/sass/node-sass/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/travis/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/travis/build/sass/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/travis/.node-gyp/10.0.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/travis/build/sass/node-sass/build'
  g++-4.7 '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/home/travis/.node-gyp/10.0.0/include/node -I/home/travis/.node-gyp/10.0.0/src -I/home/travis/.node-gyp/10.0.0/deps/uv/include -I/home/travis/.node-gyp/10.0.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
g++-4.7: error: unrecognized command line option ‘-std=gnu++1y’
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
make: Leaving directory `/home/travis/build/sass/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/build/sass/node-sass/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.14.12-041412-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v10.0.0/bin/node" "/home/travis/build/sass/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/travis/build/sass/node-sass
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
```

</details>

Full build output available at https://travis-ci.org/sass/node-sass/jobs/370912267

**Comment by xzyfer** [comment]
Looks like breaking changes in Node 10.

https://github.com/nodejs/node/pull/17489

Looks like gcc-4.9 is required now.

https://github.com/nodejs/node/pull/16501
