### ISSUE TITLE
Get and pass Node version?

### ISSUE THREAD

**Issue by d3x0r** [nodejs/node-gyp#1425]
is it possible to get the current NODE_VERSION_MAJOR and NODE_VERSION_MINOR to be passed as command-line defined symbols to files to compile?

Node 10 doesn't export routines that Node < 10 does; and Node < 10 doesn't export the routines that Node >= 10 does.  The code affected cannot include node.h (node_version.h) to get the node version that way.

**Comment by bnoordhuis** [comment]
Add `#include "node_version.h"` directly in your source files.  That gives you access to the defines and is explicitly supported by node.

**Comment by richardlau** [comment]
Try [command expansions](https://gyp.gsrc.io/docs/InputFormatReference.md#Command-Expansions) and capture the output of a command as a variable?

For example, [node-report](https://github.com/nodejs/node-report) reads in its version from its own package.json: https://github.com/nodejs/node-report/blob/824648730f85b7d434e55382c49f4eef55ce884f/binding.gyp#L17-L19

**Comment by bnoordhuis** [comment]
Back-linking to https://github.com/nodejs/node/issues/20369.   The real issue is probably something we can fix on the node side.

**Comment by d3x0r** [comment]
https://gist.github.com/d3x0r/da078aae29ce859cb514b4861d4d2207
I tried to do a substitution...

```
"<!( node -p \"var x = process.version.substr(1).split('.');console.log(`NODE_VERSION_MAJOR=\\\"${x[0]}\\\" NODE_VERSION_MINOR=\\\"${x[1]}\\\"`)\")"
```
(probably have to make that two ubstitituions)

But I cannot get it to behave....

```
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2778, in Load
    variables, includes, depth, check, True)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 420, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1295, in ProcessVariablesAndConditionsInDict
    build_file)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1310, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1295, in ProcessVariablesAndConditionsInDict
    build_file)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1314, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, phase, variables, build_file)
  File "C:\Users\Panther\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 856, in ExpandVariables
    contents = eval(contents)
  File "<string>", line 1
    node -p "var x = process.version.substr(1).split('.');console.log(`NODE_VERSION_MAJOR=\"${x[0]}\" NODE_VERSION_MINOR=\"${x[1]}\"`)"
                                                                                                                                      ^
SyntaxError: invalid syntax
gyp ERR! configure error 
```

**Comment by bnoordhuis** [comment]
Calling out to node isn't 100% foolproof anyway because it might not be what the build is targeting (e.g., using node to build for electron.)

Using `#include "node_version.h"` somewhere/somehow is probably still your best bet.

**Comment by d3x0r** [comment]
Yes, that restores the two missing methods I know of...
