### ISSUE TITLE
 binding.gyp not found

### ISSUE THREAD

**Issue by bringtree** [nodejs/node-gyp#1426]
* **Node Version**:node:v9.10.1  npm:5.6.0 
* **Platform**:OS 10.13.4 
* **Compiler**:
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 
* **Module**:
wdio

 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
 huangpeisong@MBP  ~  /usr/local/Cellar/node/9.11.1/bin/node /Users/huangpeisong/Desktop/hybrid/node_modules/fibers/build                                                        ✔  10439  20:50:14
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.10.1 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/huangpeisong/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/huangpeisong/.node-gyp/9.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/huangpeisong/.node-gyp/9.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/huangpeisong/.node-gyp/9.10.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/huangpeisong',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/huangpeisong) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/9.10.1/bin/node" "/usr/local/bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /Users/huangpeisong
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
```

</details>

**Comment by bnoordhuis** [comment]
Run node-gyp inside of the directory of the native module you want to build; i.e., `cd` to that directory first.
