### ISSUE TITLE
node-gyp build unable to find node version

### ISSUE THREAD

**Issue by aleybovich** [nodejs/node-gyp#1433]
* **Node Version**: 8.11.1
* **Platform**: MacOS 10.13.4
* **Compiler**:Apple LLVM version 9.1.0 (clang-902.0.39.1)
* **Module**: npm install node-gyb

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.11.1
gyp verb ensuring nodedir is created /Users/me/.node-gyp/8.11.1
gyp verb created nodedir /Users/me/.node-gyp/8.11.1
gyp http GET https://nodejs.org/download/release/v8.11.1/node-v8.11.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.11.1' ]
gyp verb remove using node-gyp dir: /Users/leyboan1/.node-gyp
gyp verb remove removing target version: 8.11.1
gyp verb remove removing development files for version: 8.11.1
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/Users/me/.local/share/npm/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (/Users/me/.local/share/npm/lib/node_modules/npm/node_modules/request/request.js:878:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/me/.local/share/npm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/dev/cry/smart-contract-executor/node_modules/sha3
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

</details>

You can see that it's attempting to install node 8.11.1 and fails. I already have node 8.11.1 install and working fine, so I am not sure why it's trying to do that. 
Because of this issue I am unable to install `sha3` module as well.

**Comment by aleybovich** [comment]
It was my network issues, failed to download the headers. Closing
