### ISSUE TITLE
“node.h”: No such file 

### ISSUE THREAD

**Issue by Ekko1995** [nodejs/node-gyp#1448]
npm@6.0.1-next.0
node@v8.11.1
python@2.7.15
vs@2017

when I install node-ffi，this error occured. I had try Visual Studio 2017 / 2015 , the same phenomenon appears.  how could i do?  I was tortured for three days...

h:\node\node_modules\ref\src\binding.cc(5): fatal error C1083: 无法打开包括文件: “node.h”: No such file or directory [H:\node\node_modules\ref\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `H:\vs2017\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (H:\node\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "H:\\node\\node.exe" "H:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\node\node_modules\ref
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`

**Comment by bnoordhuis** [comment]
Can you post the exact steps you took and include the full build output?

**Comment by Ekko1995** [comment]
@bnoordhuis

**Comment by Ekko1995** [comment]
thx for ur reply

**Comment by Ekko1995** [comment]
thx for ur reply @bnoordhuis 
1.install node-gyp
2.install python2.7.15
3.install vs2017 official website , and I had choose all of SDKs .
4.npm install ffi , then this error occured.
And i find this error is about the  rebuilding of "ref" and "nan"  module. So i had try to install ref and nan, the same error occred , rebuild failed .

**Comment by bnoordhuis** [comment]
Can you post the full output of `npm install ffi`?

**Comment by Ekko1995** [comment]
@bnoordhuis 

H:\node>npm  install  -g  ffi

> ref@1.3.5 install H:\node\node_modules\ffi\node_modules\ref
> node-gyp rebuild


H:\node\node_modules\ffi\node_modules\ref>if not defined npm_config_node_gyp (node "H:\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "H:\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  binding.cc
  win_delay_load_hook.cc
h:\node\node_modules\ffi\node_modules\ref\src\binding.cc(5): fatal error C1083: 无法打开包括文件: “node.h”: No such file or directory [H:\node\node_modules\ffi\node_modules\ref\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `H:\vs2017\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (H:\node\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "H:\\node\\node.exe" "H:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\node\node_modules\ffi\node_modules\ref
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hyh\AppData\Roaming\npm-cache\_logs\2018-05-28T07_42_51_156Z-debug.log

**Comment by bnoordhuis** [comment]
Can you delete `C:\Users\hyh\.node-gyp` and try again?  What does that folder contain afterwards?  What's in your .npmrc?

**Comment by Ekko1995** [comment]
I had  try it.

which .npmrc? I had three  .npmrc in my node's folder

this is one :

npmrc(5) -- The npm config files
================================

## DESCRIPTION

npm gets its config settings from the command line, environment
variables, and `npmrc` files.

The `npm config` command can be used to update and edit the contents
of the user and global npmrc files.

For a list of available configuration options, see npm-config(7).

## FILES

The four relevant files are:

* per-project config file (/path/to/my/project/.npmrc)
* per-user config file (~/.npmrc)
* global config file ($PREFIX/etc/npmrc)
* npm builtin config file (/path/to/npm/npmrc)

All npm config files are an ini-formatted list of `key = value`
parameters.  Environment variables can be replaced using
`${VARIABLE_NAME}`. For example:

    prefix = ${HOME}/.npm-packages

Each of these files is loaded, and config options are resolved in
priority order.  For example, a setting in the userconfig file would
override the setting in the globalconfig file.

Array values are specified by adding "[]" after the key name. For
example:

    key[] = "first value"
    key[] = "second value"

#### Comments

Lines in `.npmrc` files are interpreted as comments when they begin with a `;` or `#` character. `.npmrc` files are parsed by [npm/ini](https://github.com/npm/ini), which specifies this comment syntax.

For example:

    # last modified: 01 Jan 2016
    ; Set a new registry for a scoped package
    @myscope:registry=https://mycustomregistry.example.org

### Per-project config file

When working locally in a project, a `.npmrc` file in the root of the
project (ie, a sibling of `node_modules` and `package.json`) will set
config values specific to this project.

Note that this only applies to the root of the project that you're
running npm in.  It has no effect when your module is published.  For
example, you can't publish a module that forces itself to install
globally, or in a different location.

Additionally, this file is not read in global mode, such as when running
`npm install -g`.

### Per-user config file

`$HOME/.npmrc` (or the `userconfig` param, if set in the environment
or on the command line)

### Global config file

`$PREFIX/etc/npmrc` (or the `globalconfig` param, if set above):
This file is an ini-file formatted list of `key = value` parameters.
Environment variables can be replaced as above.

### Built-in config file

`path/to/npm/itself/npmrc`

This is an unchangeable "builtin" configuration file that npm keeps
consistent across updates.  Set fields in here using the `./configure`
script that comes with npm.  This is primarily for distribution
maintainers to override default configs in a standard and consistent
manner.

## SEE ALSO

* npm-folders(5)
* npm-config(1)
* npm-config(7)
* package.json(5)
* npm(1)


this is another one:

msvs_version=2015
python=C:\Users\贺煜辉\.windows-build-tools\python27\python.exe

should i change  "2015"  to "2017" ?
