### ISSUE TITLE
Builds fail on macOS with XCode 10

### ISSUE THREAD

**Issue by jhermsmeier** [nodejs/node-gyp#1454]
* **Node Version**: Node v10.3.0, npm v6.1.0
* **Platform**: Darwin R2D2 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64 i386 MacBookAir5,2 Darwin
* **Compiler**:
```
Apple LLVM version 10.0.0 (clang-1000.10.25.5)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
* **Module**: https://github.com/resin-io-modules/mountutils
(but happens with anything with native bindings)

<details><summary>Verbose output (from local npm install):</summary>

```
~/W/mountutils (master|ø) $ npm i

> mountutils@1.3.12 install /Users/Jonas/Work/mountutils
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info install installing standalone, skipping download.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/n/versions/node/10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Jonas/Work/mountutils
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mountutils@1.3.12 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mountutils@1.3.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 3442ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jonas/.npm/_logs/2018-06-05T12_24_37_170Z-debug.log
```

</details>

<details><summary>Output of /usr/sbin/pkgutil --pkg-info "com.apple.pkg.CLTools_Executables":</summary>

```
$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 10.0.0.0.1.1527767617
volume: /
location: /
install-time: 1528194524
groups: com.apple.FindSystemFiles.pkg-group
```

</details>

**Comment by bnoordhuis** [comment]
Did you accept the EULA when installing xcode/xcode CLT?  Running `xcode-select` or `xcodebuild` manually should prompt you.

**Comment by jhermsmeier** [comment]
Yup, made sure that wasn't the cause – turned out it's due to the version number matching regex, PRed a fix in https://github.com/nodejs/node-gyp/pull/1455

**Comment by schnogz** [comment]
Seeing same issues running:

Node: v10.4.0 
NPM: v6.1.0
Compiler:
```
Apple LLVM version 10.0.0 (clang-1000.10.25.5)
Target: x86_64-apple-darwin17.6.0
Thread model: posix InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
