### ISSUE TITLE
Node-gyp rebuild fails Error "ERR! stack Error: `gyp` failed with exit code: 1"

### ISSUE THREAD

**Issue by sudhanshugaur4** [nodejs/node-gyp#1462]
```
sudo node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.1.0 | linux | x64
gyp info spawn /opt/bitnami/python/bin/python2
gyp info spawn args [ '/opt/bitnami/nodejs/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/projects/project/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/bitnami/nodejs/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/10.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/bitnami/nodejs/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/projects/project',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/projects/project) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/bitnami/nodejs/lib/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/projects/project
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment]
Search the bug tracker for that "binding.gyp not found" message, there are plenty of issues about it and you'll find the solution in them.

**Comment by rihannarickeminem** [comment]
also got this error
