### ISSUE TITLE
node-gyp build fails on NFS because of flock

### ISSUE THREAD

**Issue by rngadam** [nodejs/node-gyp#147]
flock is used to link by the generated Makefile from node-gyp. 

This causes the build to fail when built on NFS. Installs fine on the local disk.

This is from an npm install or a manual installation (the example is fibers:  https://github.com/laverdet/node-fibers)

```
$ tar xvfz ~/.npm/fibers/0.6.9/package.tgz
$ node-gyp configure
$ node-gyp build
yp info it worked if it ends with ok
gyp info using node-gyp@0.5.4
gyp info using node@0.8.11
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/lophilo/lophilo/tmp/package/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
../src/coroutine.cc:23:41: warning: converting to non-pointer type ‘pthread_key_t {aka unsigned int}’ from NULL [-Wconversion-null]
../src/coroutine.cc:24:40: warning: converting to non-pointer type ‘pthread_key_t {aka unsigned int}’ from NULL [-Wconversion-null]
../src/coroutine.cc: In constructor ‘Coroutine::Coroutine()’:
../src/coroutine.cc:87:46: warning: passing NULL to non-pointer argument 5 of ‘void coro_create(coro_context*, coro_func, void*, void*, long int)’ [-Wconversion-null]
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
flock: ./Release/linker.lock: Bad file descriptor
make: *** [Release/obj.target/fibers.node] Error 65
make: Leaving directory `/home/lophilo/lophilo/tmp/package/build'
gyp ERR! build error Error: `make` failed with exit code: 2
gyp ERR! build error     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:214:23)
gyp ERR! build error     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! build error     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! not ok
```

After a fail build, returning to the linking step manually completes ok (while a `make -C build` after a `node-gyp configure` fails the same).

```
$ make -C build
make: Entering directory `/home/lophilo/lophilo/tmp/package/build'
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
  COPY Release/fibers.node
make: Leaving directory `/home/lophilo/lophilo/tmp/package/build'
```

Workaround is to `export LINK=g++`. 

system info:

```
$ flock -V
flock (util-linux 2.20.1)
$ uname -a
Linux lophilo 3.4.4+ #34 Sat Oct 6 16:28:57 CST 2012 armv5tejl GNU/Linux
```

**Comment by milimetric** [comment]
Perhaps a note about this in the actual error message instead of "flock: ./Release/linker.lock: Bad file descriptor"
