### ISSUE TITLE
node-gyp issue when npm is updated. 

### ISSUE THREAD

**Issue by rjgmail88** [nodejs/node-gyp#1470]
* **Node Version**: Node 8.11.3 and npm 6.1.0
* **Platform**: Linux, Centos
* **Compiler**: Linux, Centos
* **Module**: nodejs project.

Upgraded npm version from **5.7.1** to  **6.1.0** and started getting following issue when I ran 
npm install

```
[r-7B4TXMWRMQ] Running shell script
+ **npm install**

> get-cursor-position@1.0.5 install /home/build-user/workspace/r-7B4TXMWRMQ/node_modules/get-cursor-position
> node-gyp rebuild

make: Entering directory `/home/build-user/workspace/r-7B4TXMWRMQ/node_modules/get-cursor-position/build'
  CXX(target) Release/obj.target/pos/src/pos.o
make: g++: Command not found
make: *** [Release/obj.target/pos/src/pos.o] Error 127
make: Leaving directory `/home/build-user/workspace/r-7B4TXMWRMQ/node_modules/get-cursor-position/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-862.3.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/build-user/workspace/r-7B4TXMWRMQ/node_modules/get-cursor-position
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN CalendarAIDemoUS@1.0.0 license should be a valid SPDX license expression
npm WARN The package botbuilder-timeout is included as both a dev and production dependency.
npm WARN The package express is included as both a dev and production dependency.
npm WARN The package auto-bot is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-cursor-position@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get-cursor-position@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/build-user/.npm/_logs/2018-06-13T19_14_36_140Z-debug.log
```

**Comment by bnoordhuis** [comment]
> make: g++: Command not found

That's not a node-gyp or npm issue and neither is it related to the upgrade, you simply don't have a C++ compiler installed.

**Comment by rjgmail88** [comment]
I am not sure why I would need c++ computer. I am building nodejs project.

**Comment by bnoordhuis** [comment]
What do you think node-gyp is?  A tool for building C++ modules for Node.js.
