### ISSUE TITLE
node-gype rebuild error

### ISSUE THREAD

**Issue by rihannarickeminem** [nodejs/node-gyp#1483]
first i got the `make: *** [Release/obj.target/crc32c_sse42/src/crc32c_sse42.o] Error 127`
then i made as suggested in command line node-gyp rebuild
```
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.5.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/z/.nvm/versions/node/v10.5.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/z/project/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/z/.nvm/versions/node/v10.5.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/z/.node-gyp/10.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/z/.node-gyp/10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/z/.nvm/versions/node/v10.5.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/z/.node-gyp/10.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/z/project',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/z/project) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/z/.nvm/versions/node/v10.5.0/lib/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/home/z/.nvm/versions/node/v10.5.0/bin/node" "/home/z/.nvm/versions/node/v10.5.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/z/project
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 


```
i am on linux mint 19

**Comment by bnoordhuis** [comment]
Search the bug tracker for that "binding.gyp not found" error, plenty of issues about it.  Long story short: you need to be in the right directory.
