### ISSUE TITLE
gyp ERR! configure error

### ISSUE THREAD

**Issue by fraxken** [nodejs/node-gyp#1491]
* **Node Version**: node 10.5.0 & npm 6.1.0
* **Platform**: Windows ( Windows_NT 10.0.17134 ) x64
* **Compiler**: Build engine version 15.7.179.6572, cl 19.14.26431
* **Module**: A "hello world" NAPI example

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
F:\Code\SlimIO\winni>npx node-gyp configure --verbose
gyp info it worked if it ends with ok
gyp verb cli [ 'F:\\NodeJS\\node.exe',
gyp verb cli   'F:\\Code\\SlimIO\\winni\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.7.0
gyp info using node@10.5.0 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\Code\SlimIO\winni\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\Code\SlimIO\winni\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\Code\SlimIO\winni\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\Code\SlimIO\winni\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\Code\SlimIO\winni\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\Code\SlimIO\winni\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\Code\SlimIO\winni\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\Code\SlimIO\winni\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\Code\SlimIO\winni\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\Code\SlimIO\winni\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\Code\SlimIO\winni\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\Code\SlimIO\winni\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (F:\\Code\\SlimIO\\winni\\node_modules\\which\\which.js:13:12)\n    at F (F:\\Code\\SlimIO\\winni\\node_modules\\which\\which.js:68:19)\n    at E (F:\\Code\\SlimIO\\winni\\node_modules\\which\\which.js:80:29)\n    at F:\\Code\\SlimIO\\winni\\node_modules\\which\\which.js:89:16\n    at F:\\Code\\SlimIO\\winni\\node_modules\\isexe\\index.js:42:5\n    at F:\\Code\\SlimIO\\winni\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python F:\depot_tools\python.BAT
gyp verb check python version `F:\depot_tools\python.BAT -c "import platform; print(platform.python_version());"` returned: "2.7.6\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 10.5.0
gyp verb command install [ '10.5.0' ]
gyp verb install input version string "10.5.0"
gyp verb install installing version: 10.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.5.0
gyp verb build dir attempting to create "build" dir: F:\Code\SlimIO\winni\build
gyp verb build dir "build" dir needed to be created? null
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.10240
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.10586
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.14393
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows81SDK
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: F:\Code\SlimIO\winni\build\config.gypi
gyp verb config.gypi checking for gypi file: F:\Code\SlimIO\winni\config.gypi
gyp verb common.gypi checking for gypi file: F:\Code\SlimIO\winni\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn F:\depot_tools\python.BAT
gyp info spawn args [ 'F:\\Code\\SlimIO\\winni\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
Le chemin d’accès spécifié est introuvable.
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\Code\\SlimIO\\winni\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\Code\\SlimIO\\winni\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\tgent\\.node-gyp\\10.5.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\tgent\\.node-gyp\\10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=F:\\Code\\SlimIO\\winni\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\tgent\\.node-gyp\\10.5.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\Code\\SlimIO\\winni',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\Code\\SlimIO\\winni\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (F:\Code\SlimIO\winni\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "F:\\NodeJS\\node.exe" "F:\\Code\\SlimIO\\winni\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd F:\Code\SlimIO\winni
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```
</details>

I tried to run the command globally and with npx (but for both i have the same result). Python, msvs etc seem good (at least my setup work well to install native modules). So not sure what's going on :\ 

Maybe i missed something on the verbose ouput.

Thanks for your time.

Best Regards,
Thomas

**Comment by bzoz** [comment]
In the log there is:
`gyp verb `which` succeeded python F:\depot_tools\python.BAT`.

Can you try setting `PYTHON` env variable to point to a Python binary?

**Comment by fraxken** [comment]
Hi,

Ok, i'll try ! 

My problem may be related to an issue that should be fixed on the next release of node (10.6.0) ! This release is for tonight i think.

I'll keep the issue updated.

Best Regards,
Thomas

**Comment by fraxken** [comment]
Hi,

Same result with by setting `PYTHON` env variable and with the latest Node.JS version (10.6.0). 

Best Regards,
Thomas

**Comment by bzoz** [comment]
Can you provide the exact log?

**Comment by fraxken** [comment]
Hi,

After some troubleshoot, the problem appear with the version 3.6.2 of node-gyp (no error with the version 3.6.1).

Best Regards,
Thomas

**Comment by fraxken** [comment]
Hi,

Recent version of npm seem to force node-gyp to version 3.6.2 (ignoring global and local version of installed node-gyp). So every native module installation fail :\ 

Not sure if i can force this version on npm with some settings 🤔 

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\tgent\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "F:\\NodeJS\\node.exe" "C:\\Users\\tgent\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Code\SlimIO\winni
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! winni@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the winni@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgent\AppData\Roaming\npm-cache\_logs\2018-07-23T16_40_30_562Z-debug.log
```

I will fork and take a look on commits between 3.6.1 and 3.6.2

Best Regards,
Thomas

**Comment by fraxken** [comment]
Hi,

After many tests, one of my problem was because i setted a Windows path to the Microsoft compiler (i dont know why, but it break the compiler). So native module installation was exitted with code 1 because of this.

However node-gyp continue to crash on my computer on and after version 3.6.2.

I tried to reproduce the issue on the computer of one of my coworker but everything seem to work well on his computer.

Best Regards,
Thomas

**Comment by rvagg** [comment]
seems to be resolved, I think, feel free to reopen or open a new issue if there's more to this we can investigate
