### ISSUE TITLE
node-gyp fails on Windows with exit code 1

### ISSUE THREAD

**Issue by feliperoos** [nodejs/node-gyp#1499]
* **Node Version**: v8.9.4
* **Platform**: Windows_NT 10.0.14393
* **Compiler**: MSVC 14.0.25441.01

<details><summary>Verbose output (from npm or node-gyp):</summary>
```
[11:38:02] Starting 'gyp-rebuild-electron'...
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.9.4 | win32 | x64
gyp info chdir ./
gyp http GET https://atom.io/download/electron/v2.0.2/iojs-v2.0.2.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.2/iojs-v2.0.2.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.2/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v2.0.2/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v2.0.2/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.2/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.2/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.2/win-x64/iojs.lib
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\jenkins\\workspace\\******\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\jenkins\\workspace\\********\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\jenkins\\workspace\\*******\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Windows\\system32\\config\\systemprofile\\.node-gyp\\iojs-2.0.2\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Windows\\system32\\config\\systemprofile\\.node-gyp\\iojs-2.0.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\jenkins\\workspace\\********\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Windows\\system32\\config\\systemprofile\\.node-gyp\\iojs-2.0.2\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\jenkins\\workspace\\*******',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\jenkins\\workspace\\*********\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: C:\Windows\system32\config\systemprofile\.node-gyp\iojs-2.0.2\common.gypi not found (cwd: C:\jenkins\workspace\**********) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\jenkins\workspace\***********\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS894\\node.exe" "C:\\jenkins\\workspace\\********\\node_modules\\node-gyp\\bin\\node-gyp.js" "--msvs_version=2015" "rebuild" "--directory=./" "--target=2.0.2" "--dist-url=https://atom.io/download/electron" "--platform=win32" "--arch=x64"
gyp ERR! cwd C:\jenkins\workspace\********
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
[11:38:10] 'gyp-rebuild-electron' errored after 8.26 s
```
</details>

I've edited a few names with "******". Even though this is a Windows platform, https://atom.io/download/electron points to an atom-mac.zip package.

**Comment by bzoz** [comment]
There is also  
`gyp info spawn args   '-Dnode_root_dir=C:\\Windows\\system32\\config\\systemprofile\\.node-gyp\\iojs-2.0.2'`  
in the log. Can you try reinstalling node?
