### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by gitHub-Tienlele** [nodejs/node-gyp#1500]
* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```

```

</details>

**Comment by gitHub-Tienlele** [comment]
`> scrypt@6.0.3 preinstall /Users/tianlele/Documents/vevid_sc/VEVID01/node_modules/scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /Users/tianlele/Documents/vevid_sc/VEVID01/node_modules/scrypt
> node-gyp rebuild

2018-07-12 16:45:55.771 xcodebuild[47902:569579] [MT] DVTPlugInManager: Required plug-in compatibility UUID 426A087B-D3AA-431A-AFDF-F135EC00DE1C for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
../src/scryptwrapper/keyderivation.c:33:10: warning: non-portable path to file '<String.h>'; specified path differs in case from file name on disk
      [-Wnonportable-include-path]
#include <string.h>
         ^~~~~~~~~~
         <String.h>
In file included from ../src/scryptwrapper/keyderivation.c:33:
/usr/local/include/string.h:25:10: fatal error: 'plist/Node.h' file not found
#include <plist/Node.h>
         ^~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tianlele/Documents/vevid_sc/VEVID01/node_modules/scrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN vevid01@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tianlele/.npm/_logs/2018-07-12T08_45_56_563Z-debug.log`
