### ISSUE TITLE
Setting User Defined Variables through command line.

### ISSUE THREAD

**Issue by scual** [nodejs/node-gyp#1507]
* **Node Version**: 6.2.0
* **Platform**: Microsoft Windows 10 Pro  10.0.17134 N/A Build 17134
* **Compiler**:  Microsoft (R) Build Engine version 14.0.25420.1

<details><summary>Verbose output:</summary>

```
> electron-f-sdk@1.0.0 electron:build D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron
> node-gyp --verbose clean && node-gyp --verbose configure -Dto_deploy=false && node-gyp --verbose build -Dto_deploy=false && electron-rebuild


D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron>if not defined npm_config_node_gyp (node "C:\Users\HDEV\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --verbose clean )  else (node "C:\Users\HDEV\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --verbose clean )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\HDEV\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   '--verbose',
gyp verb cli   'clean' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.11.2 | win32 | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok

D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron>if not defined npm_config_node_gyp (node "C:\Users\HDEV\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --verbose configure -Dto_deploy=false )  else (node "C:\Users\HDEV\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --verbose configure -Dto_deploy=false )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\HDEV\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   '--verbose',
gyp verb cli   'configure',
gyp verb cli   '-Dto_deploy=false' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.11.2 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\HDEV\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\HDEV\.windows-build-tools\python27\python.exe C:\Users\HDEV\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\HDEV\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.2
gyp verb command install [ '8.11.2' ]
gyp verb install input version string "8.11.2"
gyp verb install installing version: 8.11.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.2
gyp verb build dir attempting to create "build" dir: D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron\build
gyp verb build dir "build" dir needed to be created? D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron\config.gypi
gyp verb common.gypi checking for gypi file: D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\HDEV\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\HDEV\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Code\\wo-fullstack\\beauty\\Projects\\FSDK\\build\\electron\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\HDEV\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\HDEV\\.node-gyp\\8.11.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\HDEV\\.node-gyp\\8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\HDEV\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\HDEV\\.node-gyp\\8.11.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Code\\wo-fullstack\\beauty\\Projects\\FSDK\\build\\electron',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Code\\wo-fullstack\\beauty\\Projects\\FSDK\\build\\electron\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable to_deploy in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\HDEV\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HDEV\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--verbose" "configure" "-Dto_deploy=false"
gyp ERR! cwd D:\Code\wo-fullstack\beauty\Projects\FSDK\build\electron
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-f-sdk@1.0.0 electron:build: `node-gyp --verbose clean && node-gyp --verbose configure -Dto_deploy=false && node-gyp --verbose build -Dto_deploy=false && electron-rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-f-sdk@1.0.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HDEV\AppData\Roaming\npm-cache\_logs\2018-07-19T10_38_00_803Z-debug.log
```

</details>

__binding.gyp file:__
```
{
    'variables': {
    	'deploy%': '<@(to_deploy)'
	},
    "targets": [
        {
            "target_name": "fbhElectron",
            "include_dirs": [
                "src",
                "<!(node -e \"require('nan')\")",
            ],
            'configurations': {
		'Release': {
                    'msvs_configuration_platform': 'x64',
                    'msvs_settings': {
                        'VCCLCompilerTool': {
                            'RuntimeTypeInfo': 'true',
                        },
                        'VCLinkerTool': {
                            'AdditionalDependencies': [
                                "../../../../../3rdParty/angle/out/Release/angle_util.dll.lib",
                            ],
			    'AdditionalLibraryDirectories' : [
                                "../../../../../3rdParty/basler/lib/x64/"
			    ]
                        }
                    },
                },  # Release
                'Debug': {
                    'msvs_configuration_platform': 'x64',
                    'msvs_settings': {
                        'VCCLCompilerTool': {
                            'RuntimeTypeInfo': 'true',
                        },
                        'VCLinkerTool': {
                            'AdditionalDependencies': [
                                "../../../../../3rdParty/angle/out/Debug/angle_util.dll.lib",
                            ],
                     		'AdditionalLibraryDirectories': [
                                "../../../../../3rdParty/basler/lib/x64/"
                            ]
                        }
                    }
		}  # Debug
            },
	    'msvs_disabled_warnings': [4305, 4244, 4101],
	    "cflags": ["-std=c++17"],
	    'defines': [
		'GL_GLEXT_PROTOTYPES',
		 '_CONSOLE'
	     ],
             'conditions': [
                ['deploy == "false"', {
                    'defines': ['ELECTRON_BUILD']
                }, {
                    'defines': ['ELECTRON_RELEASE']
                }]
            ],
            "sources": [
                "src/index.cc",
                "src/EWrap.cc",
                "src/FbhResponse.cc",
                "src/FbhData.cc"
            ]
	}
    ]
}

```

what i'm trying to do is to pass `to_deploy` via the command line, something like:
```
node-gyp --verbose configure -Dto_deploy=false
```
however, as reported in the error log, I get a `Undefined variable to_deploy in binding.gyp while trying to load binding.gyp` error. 

In the documentation it's not too clear how or even if is possible to achieve something like this.
Any suggestions?

**Comment by rvagg** [comment]
closing due to staleness, sorry I don't have an answer off the top of my head

**Comment by laverdet** [comment]
For people who found this on Google:

His issue was that he was doing `-Dto_deploy=false` instead of `--to_deploy=false`. Documentation on gyp is sparse but it seems that you can omit the `@` to make the variable not required on the command line, so it would just be `<(to_deploy)` in the binding.gyp file if you wanted an optional variable.
