### ISSUE TITLE
Error: Could not locate the bindings file 

### ISSUE THREAD

**Issue by Logeshwaran21** [nodejs/node-gyp#1511]
Facing the below issue while running the node in VSC:
Node Version:  node -v6.14.2 and npm -v3.10.10
Platform: Windows(64 bit)

Error: Could not locate the bindings file. Tried:
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\build\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\build\Debug\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\build\Release\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\out\Debug\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\Debug\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\out\Release\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\Release\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\build\default\ursaNative.node
 → C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\compiled\6.14.2\win32\x64\ursaNative.node
    at bindings (C:\Users\Admin_Ajay\edi_blockchain\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (C:\Users\Admin_Ajay\edi_blockchain\node_modules\ursa\lib\ursa.js:18:37)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Admin_Ajay\edi_blockchain\route.js:5:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Admin_Ajay\edi_blockchain\app.js:24:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

**Comment by sandu9618** [comment]
Please tell me hoe to install node modules.

**Comment by wjamro** [comment]
@sandu9618 run: `npm install`
Read more here: https://docs.npmjs.com/cli/install

**Comment by yaronuliel** [comment]
It might happen when some libraries failed during installation (e.g. due to incompatible Node version)
Try rebuilding dependencies with `npm rebuild`

**Comment by alessandraamosso** [comment]
I've solved the same issue installing the missing file.
In your case it is `ursaNative.node`, so you should do: `npm install ursaNative`

**Comment by vangaris** [comment]
This happened due to an incompatible Node version, a simple solution should be to use a different node version with nvm.

**Comment by abrahamrkj** [comment]
@vangaris  what is the correct node version?
