### ISSUE TITLE
binding.gyp not found

### ISSUE THREAD

**Issue by gt-c** [nodejs/node-gyp#1523]
I get the following error while attempting to run `node-gyp rebuild` in my powershell:
```gyp: binding.gyp not found (cwd: C:\Users\a\Documents\GitHub\Bro-Time-Server) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\a\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\helen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\helen\Documents\GitHub\Bro-Time-Server
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR!
```

**Comment by maclover7** [comment]
Hi @gt-c! If you are getting an error saying that `node-gyp` can't find your `binding.gyp` file, then it's likely you need to change directories into your project folder. You should be able to use `node-gyp` again after that.
