### ISSUE TITLE
Failure to handle path with space characters

### ISSUE THREAD

**Issue by jamesabc** [nodejs/node-gyp#1533]
* **Node Version**: `node -v : v8.11.4` and `yarn -v 1.9.4` -->
* **Platform**: `Darwin Jamess-MacBook-Pro-2.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
* **Compiler**: 
```
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
* **Module**: `@newrelic/native-metrics`

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
[1/4] ⠄ @newrelic/native-metrics
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
error /Users/james 1/projects/wowbox-cage/src/wowbox-card-service/node_modules/@newrelic/native-metrics: Command failed.
Exit code: 1
Command: node ./lib/pre-build.js install native_metrics
Arguments:
Directory: /Users/james 1/projects/wowbox-cage/src/wowbox-card-service/node_modules/@newrelic/native-metrics
Output:
> /Users/james 1/.nvm/versions/node/v8.11.4/bin/node /Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.4 | darwin | x64
gyp info spawn /Users/james 1/.pyenv/shims/python
gyp info spawn args [ '/Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/james 1/projects/wowbox-cage/src/wowbox-card-service/node_modules/@newrelic/native-metrics/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/james 1/.node-gyp/8.11.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/james 1/.node-gyp/8.11.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/james 1/.node-gyp/8.11.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/james 1/projects/wowbox-cage/src/wowbox-card-service/node_modules/@newrelic/native-metrics',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp info ok
> /Users/james 1/.nvm/versions/node/v8.11.4/bin/node /Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build -j 4 native_metrics
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.4 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'native_metrics',
gyp info spawn args   'BUILDTYPE=Release',
gyp info spawn args   '-C',
gyp info spawn args   'build',
gyp info spawn args   '--jobs',
gyp info spawn args   4 ]
  CXX(target) Release/obj.target/native_metrics/src/native_metrics.o
  CXX(target) Release/obj.target/native_metrics/src/GCBinder.o
  CXX(target) Release/obj.target/native_metrics/src/LoopChecker.o
  CXX(target) Release/obj.target/native_metrics/src/RUsageMeter.o
clang: clang: errorerror: : no such file or directory: '1/.node-gyp/8.11.4/include/node'no such file or directory: '1/.node-gyp/8.11.4/include/node'

clang: errorclang: : error: no such file or directory: '1/.node-gyp/8.11.4/src'no such file or directory: '1/.node-gyp/8.11.4/src'

clang: error: clangno such file or directory: '1/.node-gyp/8.11.4/deps/uv/include':
error: no such file or directory: '1/.node-gyp/8.11.4/deps/uv/include'clang
: error: no such file or directory: '1/.node-gyp/8.11.4/deps/v8/include'
clang: clang: error: errorno such file or directory: '1/.node-gyp/8.11.4/include/node':
no such file or directory: '1/.node-gyp/8.11.4/deps/v8/include'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/src'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/deps/uv/include'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/deps/v8/include'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/include/node'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/src'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/deps/uv/include'
clang: error: no such file or directory: '1/.node-gyp/8.11.4/deps/v8/include'
make: *** [Release/obj.target/native_metrics/src/GCBinder.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Release/obj.target/native_metrics/src/RUsageMeter.o] Error 1
make: *** [Release/obj.target/native_metrics/src/LoopChecker.o] Error 1
make: *** [Release/obj.target/native_metrics/src/native_metrics.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/james 1/.nvm/versions/node/v8.11.4/bin/node" "/Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "-j" "4" "native_metrics"
gyp ERR! cwd /Users/james 1/projects/wowbox-cage/src/wowbox-card-service/node_modules/@newrelic/native-metrics
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Error: Failed to execute install: Error: Failed to install module: Error: Failed to execute /Users/james 1/.nvm/versions/node/v8.11.4/bin/node /Users/james 1/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build -j 4 native_metr
```

</details>

So I recently upgraded macbook and used the migration assistant to copy my files and applications across from the old mac.  I somehow ended up with a space in the name of my home directory, and it's broken a lot of things.  I will probably end up reformatting this and starting over, but am making an issue in case it's something you can easily diagnose and fix.  It may be a problem with the `@newrelic/native-metrics` repo, if so please close this and I can move it over there.

**Comment by richardlau** [comment]
I think this has been fixed by https://github.com/nodejs/node-gyp/pull/1436 (included in node-gyp@3.7.0).
