### ISSUE TITLE
AttributeError: 'module' object has no attribute 'path'

### ISSUE THREAD

**Issue by PythonDevOp** [nodejs/node-gyp#1560]
* **Node Version**: 8.10.0
* **Platform**:  MACOS 10.13.3
* **Compiler**: Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.4.0
* **Module**: SQLite3

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
path.join(os.path.dirname(sys.argv[0]), 'pylib'))
AttributeError: 'module' object has no attribute 'path'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/user/Downloads/AngularElectron2-master/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/user/Downloads/AngularElectron2-master/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/Users/user/Downloads/AngularElectron2-master/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v3.1.13/{toolset}/" "--package_name=electron-v1.7-darwin-x64.tar.gz"
gyp ERR! cwd /Users/user/Downloads/AngularElectron2-master/node_modules/sqlite3
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1
Error: Traceback (most recent call last):
  File "/Users/user/Downloads/AngularElectron2-master/node_modules/node-gyp/gyp/gyp_main.py", line 12, in <module>
    sys.path.insert(0, os.path.join(os.path.dirname(sys.argv[0]), 'pylib'))
AttributeError: 'module' object has no attribute 'path'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/user/Downloads/AngularElectron2-master/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/user/Downloads/AngularElectron2-master/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/Users/user/Downloads/AngularElectron2-master/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v3.1.13/{toolset}/" "--package_name=electron-v1.7-darwin-x64.tar.gz"
gyp ERR! cwd /Users/user/Downloads/AngularElectron2-master/node_modules/sqlite3
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.next (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:189:22)
    at Subscriber._next (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:129:26)
    at Subscriber.next (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:93:18)
    at DefaultIfEmptySubscriber._next (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/operators/defaultIfEmpty.js:67:26)
    at DefaultIfEmptySubscriber.Subscriber.next (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:93:18)
    at TakeLastSubscriber._complete (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/operators/takeLast.js:102:29)
    at TakeLastSubscriber.Subscriber.complete (/Users/user/Downloads/AngularElectron2-master/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:118:18)```
```
</details>

I tried installing SQLite version 3  or 4 with ElectronJS (via Electron Forge) with `electron-rebuild`.  I have node gyp installed, but something is not working and I don't know how to interpret the error message. It appears this is a common issue.

I have tried:

1. removing and re-installing `node_modules` with yarn instead of npm
2. `--runtime=electron --target=1.7.6 --dist-url=https://atom.io/download/electron`
3. `--runtime=electron --target=3.0.3 --dist-url=https://atom.io/download/electron`
4. `npm install --build-from-source`
5. deleting `~./node-gyp`

The project works fine on Windows 7x64

**Comment by rvagg** [comment]
sorry we couldn't provide an answer here, it looks like an Angular issue to me. I'm going to close this due to staleness.
