### ISSUE TITLE
Find python logic doesn't work on travis windows

### ISSUE THREAD

**Issue by jkrems** [nodejs/node-gyp#1568]
* **Node Version**: 10.12.0
* **Platform**: [Windows Server 2016](https://docs.travis-ci.com/user/reference/windows/)
* **Compiler**: visualstudio2017buildtools
* **Module**: https://github.com/jkrems/loader/blob/master/binding.gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\travis\build\jkrems\loader>if not defined npm_config_node_gyp (node "C:\ProgramData\nvs\node\10.12.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\ProgramData\nvs\node\10.12.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\ProgramData\nvs\node\10.12.0\x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\ProgramData\nvs\node\10.12.0\x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\ProgramData\nvs\node\10.12.0\x64\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\ProgramData\\nvs\\node\\10.12.0\\x64\\node.exe" "C:\\ProgramData\\nvs\\node\\10.12.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\travis\build\jkrems\loader
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loader@0.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loader@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\travis\AppData\Roaming\npm-cache\_logs\2018-10-12T16_48_43_061Z-debug.log
```

</details>

**Comment by jkrems** [comment]
This might also be a travis issue but at least officially the docs claim that Python 2 and 3 are installed: https://github.com/travis-ci/packer-templates/blob/master/packer-assets/windows-server-2016-ci-onion-packages.txt

**Comment by jkrems** [comment]
I can try but it would likely mean wrapping the command somehow because this is a multi-os build and the path would change..? Or would it fall back to the normal searching on other systems if I set it to the Windows path?

**Comment by bzoz** [comment]
Can you see what is in the `PATH` env variable on that machine?

**Comment by SimenB** [comment]
Having the same issue. I added `echo $PATH`: https://travis-ci.org/SimenB/weak-travis-windows/jobs/443354201#L83

Feel free to send PRs to test other stuff if you want

**Comment by refack** [comment]
Did anyone try to add `python: 2.7` to their `.travis.yaml`?

Also if anyone can run this file https://github.com/nodejs/node/blob/master/tools/msvs/find_python.cmd
with
```
set DEBUG_HELPER=1
find_python.cmd
echo VCBUILD_PYTHON_LOCATION
```
And paste the output, that will be great help

**Comment by SimenB** [comment]
@refack feel free to PR my repo, it should trigger CI builds. I pushed `find_python` now, but I don't think stuff runs in `cmd`

**Comment by refack** [comment]
> EDIT2: [travis-ci.org/SimenB/weak-travis-windows/jobs/443367344#L84](https://travis-ci.org/SimenB/weak-travis-windows/jobs/443367344#L84) `Could not find Python.`

Thank you very much @SimenB, This result seems to indicate that python is not registered with the [PEP 514](https://www.python.org/dev/peps/pep-0514/) mechanism either.
So this is most likely a Travis issue.

I would close this issue, but I'm keeping it open for tracking.

**Comment by joaocgreis** [comment]
Adding this to `.travis.yml` makes node-gyp work on Travis:
```yml
env:
  - YARN_GPG=no

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cinst -y python2; fi
```

There are two issues:
- Python not being installed: tracked in https://travis-ci.community/t/installed-packages-does-not-match-the-documented-list/843
- Yarn leaving a `gpg-tools` process behind: tracked in https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
