### ISSUE TITLE
node-sass fails to update, error code 7

### ISSUE THREAD

**Issue by magicalraccoon** [nodejs/node-gyp#1609]
* **Node Version**: v8.13.0 and 6.4.1 
* **Platform**: Linux hackoon 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
```
* **Compiler**: Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
```

* **Module**: node-sass

<details><summary>Verbose output (from npm or node-gyp): </summary>

```
$ yarn install --pure-lockfile
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning store@1.3.20: The engine "browser" appears to be invalid.
[3/4] Linking dependencies...
warning " > chai-enzyme@0.6.1" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
warning " > react-decoration@1.4.0" has incorrect peer dependency "react-addons-perf@15.3.2".
warning " > react-redux-loading-bar@2.4.1" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0".
warning " > react-storybook-addon-intl@0.1.0" has incorrect peer dependency "@kadira/storybook@^1.35.1".
[4/4] Building fresh packages...
[1/3] ⠐ bufferutil
[2/3] ⠐ node-sass
error /home/mastodon/live/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/mastodon/live/node_modules/node-sass
Output:
Building: /usr/bin/node /home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot read property 'length' of undefined
gyp ERR! stack     at parse (/home/mastodon/live/node_modules/semver/semver.js:239:15)
gyp ERR! stack     at Function.valid (/home/mastodon/live/node_modules/semver/semver.js:255:11)
gyp ERR! stack     at processRelease (/home/mastodon/live/node_modules/node-gyp/lib/process-release.js:16:25)
gyp ERR! stack     at configure (/home/mastodon/live/node_modules/node-gyp/lib/configure.js:35:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/home/mastodon/live/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:132:7)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:181:9)
gyp ERR! System Linux 4.15.0-39-generic
gyp ERR! command "/usr/bin/node" "/home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/mastodon/live/node_modules/node-sass
gyp ERR! node -v v8.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7

```

</details>

**Comment by magicalraccoon** [comment]
I poked at things a bit more before I fell asleep last night. Reinstalled `node-sass`, ran `npm install`, `rbenv install`, `gem install bundle` and I guess it worked.

Wish I had more details.
