### ISSUE TITLE
Install failing Windows 10 x64 whilst installing sqlite3

### ISSUE THREAD

**Issue by baumy1** [nodejs/node-gyp#1631]
* **Node Version**: v10.13.0
* **Platform**: OS Name:  Microsoft Windows 10 Education 10.0.17134 N/A Build 17134 x64
* **Compiler**: 
* **Module**:  sqlite3

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npm install node-gyp --save

> grpc@1.10.1 install C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\baumwi734\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp gypERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\baumwi734\\Documents\\Code\\_Interesting facts comp\\_final\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\baumwi734\\Documents\\Code\\_Interesting facts comp\\_final\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
 gyp ERR!ERR!  cwdconfigure error C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc

gyp ERR! node -v v10.13.0
gypgyp  ERR! ERR!node-gyp -v  v3.8.0
stackgyp Error: Command failed: C:\Users\baumwi734\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
 gypERR!  ERR!not ok
stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\baumwi734\\Documents\\Code\\_Interesting facts comp\\_final\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\baumwi734\\Documents\\Code\\_Interesting facts comp\\_final\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
gypnode-pre-gyp  ERR!ERR!  build error
cwdnode-pre-gyp C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc
 gypERR!  stackERR! Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
 node-pre-gypnode -v  v10.13.0
ERR!gyp  ERR!stack      at ChildProcess.<anonymous> (C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-gyp -vnode-pre-gyp v3.8.0
 gypERR!  ERR!stack      at ChildProcess.emit (events.js:182:13)
not ok
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\baumwi734\\Documents\\Code\\_Interesting facts comp\\_final\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\baumwi734\Documents\Code\_Interesting facts comp\_final\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
npm WARN final@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\baumwi734\AppData\Roaming\npm-cache\_logs\2018-12-12T10_04_53_660Z-debug.log
```

</details>

 Trying to install node-gyp as a dependency for [sqlite3](https://github.com/mapbox/node-sqlite3/), install errors out as above. Unsure how to proceed

**Comment by bzoz** [comment]
`node-gyp` does not support Python 3. You need to have Python 2.x installed.
