### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by kohahn** [nodejs/node-gyp#1634]
I don't fix this error. help

node version - 8.14.1
npm version : 6.4.1
platfrom : linux mint and windows10
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
node_modules/libpq: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/woong/velog/velog-backend/node_modules/libpq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.14.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.14.1/node-v8.14.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.14.1/node-v8.14.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.14.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.14.1/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/woong/velog/velog-backend/node_modules/libpq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/.gyp/8.14.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/tmp/.gyp/8.14.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/tmp/.gyp/8.14.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/woong/velog/velog-backend/node_modules/libpq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
gyp: Call to '/usr/bin/pg_config --libdir' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/woong/velog/velog-backend/node_modules/libpq
gyp ERR! node -v v8.14.1
gyp ERR! node-gyp -v v3.8.0


```

</details>

**Comment by bzoz** [comment]
As the log says:
```
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
gyp: Call to '/usr/bin/pg_config --libdir' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```
