### ISSUE TITLE
Not able to build in osx 10.14.2 with java 10.0.1

### ISSUE THREAD

**Issue by cksachdev** [nodejs/node-gyp#1641]
When trying to install a module which has dependency on node-gyp, getting the following error. Checked to ensure that jdk and jni dependencies are of same version. 
Any suggestions on what is causing this issue? I have tried using different versions of java using jabba and different versions of node using nvm, but I get one or the other issue.
```
~
➜ java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

~
➜ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home

~
➜ cd ~/Documents/code

pdf2ecml on  development is 📦 v1.0.0 via ⬢ v10.4.0
➜

pdf2ecml on  development is 📦 v1.0.0 via ⬢ v10.4.0
➜ npm i

> java@0.8.0 install /Users/Chetan/Documents/code/pdf2ecml/node_modules/java
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:1447:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Chetan/.node-gyp/10.4.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/java.cpp:125:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value utf8(suffix);
                          ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:133:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value utf8(suffix);
                          ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:141:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value utf8(suffix);
                          ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:193:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arrayItemStr(arrayItem);
                          ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:199:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value nativeBindingLocationStr(v8NativeBindingLocation);
                        ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:222:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arrayItemStr(arrayItem);
                          ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:276:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value nameStr(property);
                        ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:299:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value nameStr(property);
                        ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:346:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:173:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:389:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:181:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:431:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(interfaceName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:189:1: note: expanded from here
_interfaceName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:542:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:200:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:543:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(methodName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:208:1: note: expanded from here
_methodName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:586:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:216:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:587:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(methodName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:224:1: note: expanded from here
_methodName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:633:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(methodName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:232:1: note: expanded from here
_methodName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:673:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(methodName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:240:1: note: expanded from here
_methodName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:710:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:248:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:739:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:256:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:867:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
        v8::String::Utf8Value valStr(item);
                              ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:897:40: error: no matching member function for call to 'ToNumber'
  v8::Local<v8::Number> val = info[0]->ToNumber();
                              ~~~~~~~~~^~~~~~~~
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2390:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2407:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Number> ToNumber(Isolate* isolate) const);
                                  ^
../src/java.cpp:927:40: error: no matching member function for call to 'ToNumber'
  v8::Local<v8::Number> val = info[0]->ToNumber();
                              ~~~~~~~~~^~~~~~~~
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2390:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2407:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Number> ToNumber(Isolate* isolate) const);
                                  ^
../src/java.cpp:956:40: error: no matching member function for call to 'ToNumber'
  v8::Local<v8::Number> val = info[0]->ToNumber();
                              ~~~~~~~~~^~~~~~~~
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2390:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2407:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Number> ToNumber(Isolate* isolate) const);
                                  ^
../src/java.cpp:983:42: error: no matching member function for call to 'ToNumber'
    v8::Local<v8::Number> val = info[0]->ToNumber();
                                ~~~~~~~~~^~~~~~~~
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2390:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2407:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Number> ToNumber(Isolate* isolate) const);
                                  ^
../src/java.cpp:990:39: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    std::string strVal = std::string(*v8::String::Utf8Value(val));
                                      ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1019:40: error: no matching member function for call to 'ToNumber'
  v8::Local<v8::Number> val = info[0]->ToNumber();
                              ~~~~~~~~~^~~~~~~~
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2390:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2407:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Number> ToNumber(Isolate* isolate) const);
                                  ^
../src/java.cpp:1044:40: error: no matching member function for call to 'ToNumber'
  v8::Local<v8::Number> val = info[0]->ToNumber();
                              ~~~~~~~~~^~~~~~~~
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2390:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2407:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Number> ToNumber(Isolate* isolate) const);
                                  ^
../src/java.cpp:1067:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:276:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1068:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(fieldName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:284:1: note: expanded from here
_fieldName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1114:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_CLASSNAME();
  ^
../src/utils.h:124:32: note: expanded from macro 'ARGS_FRONT_CLASSNAME'
#define ARGS_FRONT_CLASSNAME() ARGS_FRONT_STRING(className)
                               ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:292:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1115:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(fieldName);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:300:1: note: expanded from here
_fieldName_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1175:3: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  ARGS_FRONT_STRING(className);
  ^
../src/utils.h:120:25: note: expanded from macro 'ARGS_FRONT_STRING'
  v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \
                        ^
<scratch space>:308:1: note: expanded from here
_className_val
^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:2845:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1263:16: error: no matching constructor for initialization of 'v8::TryCatch'
  v8::TryCatch tryCatch;
               ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:8388:12: note: candidate constructor not viable: requires single argument 'isolate', but no arguments were provided
  explicit TryCatch(Isolate* isolate);
           ^
/Users/Chetan/.node-gyp/10.4.0/include/node/v8.h:8508:3: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  TryCatch(const TryCatch&) = delete;
  ^
30 warnings and 8 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Chetan/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/Chetan/.nvm/versions/node/v10.4.0/bin/node" "/Users/Chetan/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Chetan/Documents/code/pdf2ecml/node_modules/java
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN PDFTOECML@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Chetan/.npm/_logs/2019-01-08T12_28_50_503Z-debug.log

```

Here is another issue, which I was getting when I was using Java 1.8
https://github.com/shyiko/jabba/issues/378
cc: @pedro-lucas

**Comment by ilanl** [comment]
I'm stuck on the same issue, I'm trying to use node-pdfbox (npm)

MacOS 10.13
Node v10.15.3
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by rvagg** [comment]
you need to report this to the packages causing these errors, it means they are not compatible with the version of Node you're using. They probably need to migrate to https://github.com/nodejs/node-addon-api
