### ISSUE TITLE
Incompatibility with node 10.15 and 11.6

### ISSUE THREAD

**Issue by magpielover** [nodejs/node-gyp#1646]
* **Node Version**:  10.15 and 11.6
* **Platform**: macOS Mojave
* **Compiler**: Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* **Module**: mean.js

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 

4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: make: *** [Release/obj.target/fse/fsevents.o] Error 1
*** [Release/obj.target/fse/fsevents.o] Error 1
gypgyp  ERR!ERR! build error  
build error 
gyp gyp ERR!ERR!  stackstack Error: `make` failed with exit code: 2
gyp Error: `make` failed with exit code: 2
 gyp ERR! ERR!stack      at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
stackgyp     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
 ERR!gyp  stackERR!     at ChildProcess.emit (events.js:182:13)
 gypstack      at ChildProcess.emit (events.js:182:13)
gypERR!  stackERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gypgyp  ERR! ERR! SystemSystem Darwin 18.2.0
 Darwin 18.2.0
gyp ERR! gypcommand  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/path/mean/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/path/Server_Docker/mean/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
ERR! gypcommand  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/path/mean/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/path/mean/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
ERR! cwdgyp /path/mean/node_modules/fsevents
 ERR!gyp  cwdERR! /path/mean/node_modules/fsevents
 gypnode -v  v10.15.0
ERR! gypnode -v  v10.15.0
ERR! gypnode-gyp -v  v3.8.0
ERR!gyp  node-gyp -vERR! v3.8.0
 not okgyp 
 ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/path/mean/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/path/mean/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/path/mean/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (in
```

</details>

**Comment by sebelga** [comment]
And `11.8`. My Travis build logs:

https://travis-ci.org/sebelga/gstore-node/jobs/485787779

**Comment by hieuhlc** [comment]
Same here, has anyone found a different solution than downgrading nodejs to v8?

**Comment by rootlinux2** [comment]
Same here!!
`<pre><span style="background-color:#2E3436"><font color="#D3D7CF">gyp</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">cwd</font> /usr/local/lib/node_modules/local-npm/node_modules/leveldown
<span style="background-color:#2E3436"><font color="#D3D7CF">gyp</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">node -v</font> v10.15.3
<span style="background-color:#2E3436"><font color="#D3D7CF">gyp</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">node-gyp -v</font> v3.8.0
<span style="background-color:#2E3436"><font color="#D3D7CF">gyp</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">not ok</font> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
</pre>`

**Comment by hieuhlc** [comment]
I don't know the reason but it worked after I switched from using `npm` to `yarn` instead

**Comment by rvagg** [comment]
I think there's a few very distinct issues in this thread and node-gyp may not be directly responsible. I'm going to close this, but if you're still experiencing problems then feel free to open a new issue with some verbose build output. The short output doesn't help all that much in some of these cases. `node-gyp build --verbose`
