### ISSUE TITLE
make: *** No rule to make target `Release/obj.target

### ISSUE THREAD

**Issue by yarcowang** [nodejs/node-gyp#165]
```
$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.8.0
gyp info using node@0.8.14 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/hello/hello.o', needed by `Release/hello.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/npm/lib/node_modules/node-gyp/lib/build.js:232:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.2.0
gyp ERR! command "node" "/usr/local/share/npm/bin/node-gyp" "build"
gyp ERR! cwd /Users/yarco/Sites/js/tmp
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.8.0
gyp ERR! not ok 
```

following the code from http://nodejs.org/api/addons.html

**Comment by TimZaman** [comment]
omg yeah i had a typo in targets->sources as well, wrong filename, haha shit! Thanks for this post, would have taken me hours otherwise. It's in binding.gyp, William

**Comment by clevertechru** [comment]
Hi. Need help.

```
-> sw_vers | grep Pro
ProductName:    Mac OS X
ProductVersion: 10.9.5

[MasterMac-master] (master) ! /var/www/project
-> node -v
v7.4.0

[MasterMac-master] (master) ! /var/www/project
-> cat binding.gyp 
{
      "targets": [
          {
                    "target_name": "binding",
                          "sources": [ "binding.cc" ]
                              }
                                ]
}

[MasterMac-master] (master) ! /var/www/project
-> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.4.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/private/var/www/project/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/master/.node-gyp/7.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/master/.node-gyp/7.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/private/var/www/project',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 

[MasterMac-master] (master) ! /var/www/project
-> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.4.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/private/var/www/project/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/master/.node-gyp/7.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/master/.node-gyp/7.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/private/var/www/project',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/binding/binding.o', needed by `Release/binding.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/www/project
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```
x-code installed and license approved.

**Comment by dasdeck** [comment]
+1! Sensible error messages are always helpful :D.

**Comment by phoniks** [comment]
Seems like this is an issue that is relatively common.  I'm having it now and I've found several other issues regarding something similar.  I wonder if anyone could point me to a resource for understanding what is going on, so that I can troubleshoot?  I look at the [GYP documentation](https://gyp.gsrc.io/docs/UserDocumentation.md) and it's got a lot of info, but I'm not seeing the answer to my question there , or at least not in a way that I can understand.  Assuming my targets->sources entry is incorrect, how can I figure out what it should be?

**Comment by m-nonna** [comment]
Same here, can't figure out how to define the "target" and "source". @TimZaman @WilliamCuckoo @phoniks Did you find a way?

**Comment by pixelschrubber** [comment]
Anyone reading this in the future and still wondering what to do - just create an empty binding.cc file in your source folder in order to compile node-gyp
