### ISSUE TITLE
Installation on Windows does not work for Node 11 and Visual Studio 17

### ISSUE THREAD

**Issue by sinapsist** [nodejs/node-gyp#1652]
I am trying to run some sample project that includes node-gyp as dependency and it shows an error: 

* **Node Version**:  v11.4.0
* **Platform**: System Windows_NT 10.0.17134
* **Compiler**:  MSBuild 15.9.21+g9802d43bc3
* **Module**: v3.8.0

<details><summary>Verbose output (from npm or node-gyp):</summary>
There are steps to reproduce:
1. Install Node 11
2. Install Visual Studio 2017 Community Edition
3. Use Option 1 to install MS Build Tool and Python.
4. Create a project
5. Add node-gyp as dependency.
6. Try to run the project. 

Some details can be found in the log posted below:

```
> fibers@2.0.2 install C:\Users\tester\test\test-app\portal\node_modules\fibers
> node build.js || nodejs build.js


C:\Users\tester\test\test-app\portal\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Users\tester\test\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Users\tester\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
  win_delay_load_hook.cc
c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(464): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
  c:\users\tester\.node-gyp\11.4.0\include\node\v8.h(2991): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(686): error C2660: 'v8::Script::Compile': function does not take 1 arguments [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
  c:\users\tester\.node-gyp\11.4.0\include\node\v8.h(1359): note: see declaration of 'v8::Script::Compile' (compiling source file ..\src\fibers.cc)
c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(701): error C2660: 'v8::TryCatch::StackTrace': function does not take 0 arguments [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
  c:\users\tester\.node-gyp\11.4.0\include\node\v8.h(8878): note: see declaration of 'v8::TryCatch::StackTrace' (compiling source file ..\src\fibers.cc)
c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(701): error C2672: 'uni::Reset': no matching overloaded function found [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(701): error C2780: 'void uni::Reset(v8::Isolate *,v8::Persistent<T,v8::NonCopyablePersistentTraits<T>> &,v8::Local<T>)': expects 3 arguments - 2 provided [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
  c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(126): note: see declaration of 'uni::Reset'
c:\users\tester\test\test-app\portal\node_modules\fibers\src\coroutine.cc(138): warning C4552: '!': result of expression not used [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]

npm install stderr:
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\tester\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tester\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\tester\test\test-app\portal\node_modules\fibers
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN fork-ts-checker-webpack-plugin@0.2.10 requires a peer of typescript@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN new-relic-agent-react@2.0.1 requires a peer of react@>=0.14.8 < ^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@22.0.1 requires a peer of typescript@2.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tester\AppData\Roaming\npm-cache\_logs\2019-01-21T18_32_10_742Z-debug.log

npm install exited 1 in 'portal'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</details>

After I rolled back to Node 10.15 (LTS) I was able to run it with no issues

**Comment by richardlau** [comment]
> ```
> c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(686): error C2660: 'v8::Script::Compile': function does not take 1 arguments [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
>   c:\users\tester\.node-gyp\11.4.0\include\node\v8.h(1359): note: see declaration of 'v8::Script::Compile' (compiling source file ..\src\fibers.cc)
> c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(701): error C2660: 'v8::TryCatch::StackTrace': function does not take 0 arguments [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
>   c:\users\tester\.node-gyp\11.4.0\include\node\v8.h(8878): note: see declaration of 'v8::TryCatch::StackTrace' (compiling source file ..\src\fibers.cc)
> c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(701): error C2672: 'uni::Reset': no matching overloaded function found [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
> c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(701): error C2780: 'void uni::Reset(v8::Isolate *,v8::Persistent<T,v8::NonCopyablePersistentTraits<T>> &,v8::Local<T>)': expects 3 arguments - 2 provided [C:\Users\tester\test\test-app\portal\node_modules\fibers\build\fibers.vcxproj]
>   c:\users\tester\test\test-app\portal\node_modules\fibers\src\fibers.cc(126): note: see declaration of 'uni::Reset'
> ```
> 
> After I rolled back to Node 10.15 (LTS) I was able to run it with no issues

These errors indicate that the version of fibers you are using (2.0.2) is incompatible with the version of V8 used in Node.js 11. You could try a later version of fibers (e.g. 3.1.1 looks to be the latest), or take this up at https://github.com/laverdet/node-fibers.
