### ISSUE TITLE
Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by ohelixa** [nodejs/node-gyp#1667]
* **Node Version**: Node v5.12 Npm 
* **Platform**: Mac OSX Mojave* **

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/omarassadi/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/omarassadi/.nvm/versions/node/v5.12.0/bin/node" "/Users/omarassadi/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/omarassadi/repos/cubeyou-platform/node_modules/sleep
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.
npm WARN CubeYou-Platform@1.0.0 No license field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/Users/omarassadi/.nvm/versions/node/v5.12.0/bin/node" "/Users/omarassadi/.nvm/versions/node/v5.12.0/bin/npm" "i"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

</details>

**Comment by rvagg** [comment]
closing due to staleness, sorry we didn't have anything for you
if this is still a problem, try a newer version of Node and/or npm
