### ISSUE TITLE
invalid ELF header when deploying to heroku

### ISSUE THREAD

**Issue by KrishieldKyle** [nodejs/node-gyp#1672]
* **Node Version**: v10.15.0
* **Platform**: Windows 7 64 bit.

Hi. I'm currently facing an issue on my node addon, it was working fine when executing on my local machine but on heroku, i got an "Application Error" and ```heroku logs --tail``` gave me this:

```
Error: /app/plagiarismAlgo/build/Release/plagiarism.node: invalid ELF header
at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/app/routes/api/plagiarism.js:9:20)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/app/app.js:12:20)
at Module._compile (internal/modules/cjs/loader.js:689:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! capstone@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the capstone@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-02-17T12_45_25_209Z-debug.log
```

**Comment by bzoz** [comment]
Looks like you are trying to run Win32 addon, while Heroku runs on Linux
