### ISSUE TITLE
Upload node addon to npm

### ISSUE THREAD

**Issue by KrishieldKyle** [nodejs/node-gyp#1674]
* **Node Version**: 10.15.0
* **Platform**: Windows 7 64bit

Hi i uploaded a node addon module to npm and when i try to npm install it to another windows pc i'm getting an error related to 'msbuild.exe' i think its about the windows build tool. 

*EDITED*

this what i got when trying to npm install my published module to npm:

```
$ npm install krishield-plagiarism-module --save

> krishield-plagiarism-module@1.1.1 install C:\Users\carlj\Documents\MERN Stack\mern_shopping_list\node_modules\krishield-plagiarism-module
> node-gyp rebuild


C:\Users\carlj\Documents\MERN Stack\mern_shopping_list\node_modules\krishield-plagiarism-module>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\carlj\Documents\MERN Stack\mern_shopping_list\node_modules\krishield-plagiarism-module\build\plagiarism.vcxproj(20,3): error 
MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is cor
rect, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\carlj\Documents\MERN Stack\mern_shopping_list\node_modules\krishield-plagiarism-module
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN mern_shopping_list@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! krishield-plagiarism-module@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the krishield-plagiarism-module@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\carlj\AppData\Roaming\npm-cache\_logs\2019-02-20T12_05_25_063Z-debug.log
```
* **Module Name**: ```krishield-plagiarism-module```

* **Binding.gyp**:
```
{
    "targets":[
        {
            "target_name": "plagiarism",
            "include_dirs" : [
                "src",
                "<!(node -e \"require('nan')\")"
            ],
            "sources":["src/plagiarismAlgorithm.cc"]
        }
    ],
    
}
```
[Github Repo Here](https://github.com/KrishieldKyle/krishield-plagiarism-module)

I think the problem here is about the build tool that is not present in the other pc. how can i make a node addon module that doesn't require the build tool when doing ```npm install <module name>``` on other normal pc?

**Comment by ORESoftware** [comment]
you should include the error trace and the relevant files here

**Comment by KrishieldKyle** [comment]
> you should include the error trace and the relevant files here

@ORESoftware my apologies for not giving enough info. Already edited the post.

**Comment by bzoz** [comment]
I think https://www.npmjs.com/package/node-pre-gyp is what you need
