### ISSUE TITLE
Configure error in node-gyp

### ISSUE THREAD

**Issue by suvsingh** [nodejs/node-gyp#1683]
* **Node Version**: v10.14.2
* **Platform**: WIndows 10
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):ERR! stack Error: Command failed: C:\Users\suvsingh\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info</summary>

```
D:\UI\_build\node_modules\.bin>node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\UI\\_build\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\UI\_build\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\UI\_build\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\UI\_build\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\UI\_build\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\UI\_build\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\UI\_build\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\UI\_build\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\UI\_build\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\UI\_build\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\UI\_build\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\UI\_build\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\UI\_build\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\suvsingh\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\suvsingh\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\UI\\_build\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
gyp ERR! cwd D:\UI\_build\node_modules\.bin
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

</details>

**Comment by trogper** [comment]
I have the same issue with python 3.6 installed.
The code for version check uses print statement, which does not exist in python 3.
In python 3, there's only print function.

change following line (in `node_modules/node-gyp/lib/configure.js`)
`var args = ['-c', 'import sys; print "%s.%s.%s" % sys.version_info[:3];']`
to this (add parentheses)
`var args = ['-c', 'import sys; print ("%s.%s.%s" % sys.version_info[:3]);']`

**Comment by bzoz** [comment]
Python 3 is not supported, use Python 2.x for node-gyp

**Comment by suvsingh** [comment]
Thanks a lot guys.
I reverted to Python 2.7, and then moved ahead with the work.
