### ISSUE TITLE
its 2019, use Python3 no questions. Can't install node-opus

### ISSUE THREAD

**Issue by MichaelXF** [nodejs/node-gyp#1685]
* **Node Version**: v11.10.1
* **Platform**: Linux ubuntu 4.15.0-1031-raspi2 33-Ubuntu SMP PREEMPT Wed Jan 16 09:52:45 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
* **Compiler**: [1] 13816
* **Module**: node-opus

This is very annoying having to figure what causes node-gyp to not work, why the is this still required for python2 seriously, python2 builds are already removed most repos, python2 is ancient, updated to python3, my Ubuntu comes installed with it and removing it breaks OS features.

```
ubuntu@ubuntu:~/Desktop/InfraredBot$ npm install node-opus

> ref@1.3.5 install /home/ubuntu/Desktop/InfraredBot/node_modules/ref
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.15.0-1031-raspi2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/Desktop/InfraredBot/node_modules/ref
gyp ERR! node -v v11.10.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

node-gyp relies on ancient & vulnerable python2, if you close this a duplicate at least address this issue and confirm if node-gyp will ever upgrade to python3.

**Comment by MichaelXF** [comment]
I'm dumb I just had to 
`sudo apt-get install build-essential`
