### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by chengdonglin** [nodejs/node-gyp#1691]
* **Node Version**: 8.11.2
* **Platform**: win10    x_64
* **Module**: workerpool
```
electron_project\TMAPConvertSDK\x64\node_modules\shmmap>if not defined npm_config_node_gyp (node "E:\nvm\v8.11.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "E:\nvm\v8.11.2\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  memory.cpp
  win_delay_load_hook.cc
..\src\memory.cpp(6): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory [E:\electron_project\TMAPConver
tSDK\x64\node_modules\shmmap\build\shmmap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nvm\v8.11.2\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nvm\\v8.11.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\electron_project\TMAPConvertSDK\x64\node_modules\shmmap
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

</details>

**Comment by Chrissie** [comment]
I have spent 2 full days last week figuring out what was going wrong. I had the same error as you are showing here.
Tried uninstalling node, changing versions of node, reinstalling Visual Studio and reinstalling Visual Studio Build Tools. No success.

The thing that made the rebuild error disappear for me was
`npm config delete msvs_version` and `npm config delete msvs_version -g`

**Comment by chengdonglin** [comment]
Thanks for reply! I have tried,but I still meet the same error.

**Comment by bzoz** [comment]
`sys/mman.h` is a Linux thingy, it is not available under Windows. You should report this to the repo of whatever module you are trying to compile.

**Comment by rvagg** [comment]
agreed, looks to me like you're trying to build an addon in Windows that is designed for Linux or *nix in general. better report it upstream to the addon author.
