### ISSUE TITLE
rebuild error in directory containing '%'

### ISSUE THREAD

**Issue by Chrissie** [nodejs/node-gyp#1701]
* **Node Version**:  Tested on both Node 8 and Node 10 versions
* **Platform**:  Windows 10 - other Operating Systems not tested
* **Compiler**: msbuild, installed from windows-build-tools
* **Module**:  Any module requiring a node-gyp rebuild 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
  win_delay_load_hook.cc
  Generating code
  All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  copied_files.vcxproj -> C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\build\Release\\copied_file
  s.node
  memlimit.c
cl : Command line error D8038: invalid argument 'C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\src
\scryptwrapper\inc' [C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
  keyderivation.c
cl : Command line error D8038: invalid argument 'C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\src
\scryptwrapper\inc' [C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
  pickparams.c
cl : Command line error D8038: invalid argument 'C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\src
\scryptwrapper\inc' [C:\Users\me\Desktop\This%20Fails\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
cl : Command line error D8040: error creating or communicating with child process [C:\Users\me\Desktop\Th
is%20Fails\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\me\Desktop\This%20Fails\node_modules\scrypt
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ag@1.0.0 No description
npm WARN ag@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-03-26T16_49_43_144Z-debug.log
```

</details>

I struggled many times with this issue, not quite understanding what was going wrong. 

In my case the problem was the fact that I tried to install in a folder (cloned from Git) with %20 (in text) in it's name. 

Node-gyp somehow crashes on this, without letting me know that that is the problem. 

Can you please fix this, it would have been a lot easier for me.

**Comment by bzoz** [comment]
GYP also does not support spaces nor non-ascii chars in the path (https://github.com/nodejs/node-gyp/issues/65). Right now the only solution is to change the folder name.

**Comment by rvagg** [comment]
pull requests to https://github.com/refack/GYP if you have ideas for how to make it support special characters might be worthwhile, otherwise there's not much we can do here.
