### ISSUE TITLE
gyp-error when installing gatsby-transformer-sharp

### ISSUE THREAD

**Issue by jradikal** [nodejs/node-gyp#1724]
* **Node Version**: node 12.0.0 and npm 6.9.0
* **Platform**: Windows 10
* **Compiler**: msbuild 2015 and 2017
* **Module**: tried to install gatsby-transform-sharp, followed all the different setup instructions for windows on https://www.gatsbyjs.org/docs/gatsby-on-windows/ but getting constant gyp errors no matter what i try

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\users\jared\Desktop\JST\node_modules\sharp
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jared\AppData\Roaming\npm-cache\_logs\2019-04-24T23_16_56_288Z-debug.log
```

</details>

Can provide further logs if needed.

[2019-04-24T23_16_56_288Z-debug.log](https://github.com/nodejs/node-gyp/files/3114536/2019-04-24T23_16_56_288Z-debug.log)

**Comment by bzoz** [comment]
From the log:
```
2341 verbose stack Error: sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
2341 verbose stack Exit status 1
2341 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
2341 verbose stack     at EventEmitter.emit (events.js:196:13)
2341 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2341 verbose stack     at ChildProcess.emit (events.js:196:13)
2341 verbose stack     at maybeClose (internal/child_process.js:1000:16)
2341 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
2342 verbose pkgid sharp@0.21.3
```
This is a issue with the package itself, not node-gyp. You can try going into sharp folder and running `node-gyp rebuild --verbose` there and see if produced error message is helpful.

**Comment by jradikal** [comment]
Unfortunately sharp has not created a folder as it hasnt got past the install stage however its been added to the package file? ill pop onto sharp's git and see what they say, thanks for having a look at this!

**Comment by jradikal** [comment]
Just a little more info incase anyone needs it, sharp currently doesn't support node 12, after downgrading this I had no more issues.
