### ISSUE TITLE
Rebuild fail with grammar warnings and errors

### ISSUE THREAD

**Issue by Fnxxxxo** [nodejs/node-gyp#1732]
* **Node Version**: v.10.15.3
* **Platform**: Win 10
* **Compiler**: msbuild v14
* **Module**: @dp-cat/client

I get a lot of weird grammar complains when installing and rebuilding node-cat client. I have tried many env, such as vs2013, vs2015, vs2017. I also tried node 8 and 10. 
What can I do to fix it?

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
[5/5] Building fresh packages...
error E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client
Output:
E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" r
ebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp info spawn D:\Python27\python.EXE
gyp info spawn args [ 'D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\projects\\Git\\LC\\xcrm-components\\node_modules\\@dp-cat\\client\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\palki\\.node-gyp\\10.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\palki\\.node-gyp\\10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\palki\\.node-gyp\\10.15.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\projects\\Git\\LC\\xcrm-components\\node_modules\\@dp-cat\\client',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\projects\\Git\\LC\\xcrm-components\\node_modules\\@dp-cat\\client\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  nodecat.cc
  win_delay_load_hook.cc
..\src\nodecat.cc(60): error C2065: 'u_int32_t': undeclared identifier [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(60): error C2146: syntax error: missing ';' before identifier 'i' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(60): error C2143: syntax error: missing ';' before '=' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(60): error C2143: syntax error: missing ')' before '=' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(60): error C2059: syntax error: '=' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(60): error C2065: 'i': undeclared identifier [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(60): error C2059: syntax error: ')' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(61): error C2065: 'i': undeclared identifier [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(61): error C2672: 'v8::Local<v8::Object>::Cast': no matching overloaded function found [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(61): error C2660: 'catapi::InnerSendNode': function does not take 1 arguments [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(61): error C2059: syntax error: ';' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(64): error C2065: 't': undeclared identifier [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(64): error C2227: left of '->complete' must point to class/struct/union/generic type [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  ..\src\nodecat.cc(64): note: type is 'unknown-type'
..\src\nodecat.cc(48): warning C4996: 'v8::Value::NumberValue': was declared deprecated [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2475): note: see declaration of 'v8::Value::NumberValue'
..\src\nodecat.cc(49): warning C4996: 'v8::Value::NumberValue': was declared deprecated [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2475): note: see declaration of 'v8::Value::NumberValue'
..\src\nodecat.cc(65): error C2059: syntax error: 'else' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(65): error C2143: syntax error: missing ';' before '{' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(65): error C2447: '{': missing function header (old-style formal list?) [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(77): error C2059: syntax error: 'else' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(77): error C2143: syntax error: missing ';' before '{' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(77): error C2447: '{': missing function header (old-style formal list?) [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(98): error C3861: 'InnerSendNode': identifier not found [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(102): error C2065: 'Init': undeclared identifier [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(103): error C2065: 'Destroy': undeclared identifier [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(109): error C2059: syntax error: '}' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
..\src\nodecat.cc(109): error C2143: syntax error: missing ';' before '}' [E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\projects\Git\LC\xcrm-components\node_modules\@dp-cat\client
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

```

</details>

**Comment by joaocgreis** [comment]
This looks like an issue with the package you are trying to install, not node-gyp. However, that package doesn't seem to have a public repository to report the issue.

**Comment by bnoordhuis** [comment]
Closing, not a node-gyp issue.
