### ISSUE TITLE
Rebuilding node-sqlite3 with Electron-Builder for Electron Bindings on Windows 10 Fails

### ISSUE THREAD

**Issue by wuno** [nodejs/node-gyp#1748]
* **Node Version**: 
v12.2.0
* **Platform**: 
OS Name Windows 10 Home
Version 10.0.17763 Build 17763
x64-based PC

* **Compiler**: 
Microsoft 2019 Build tools

* **Module**: 
https://github.com/mapbox/node-sqlite3 for Electron

<details><summary>Verbose output (from npm or node-gyp):</summary>
I am using Electron Builder to develop an Electron application. When I use the sqlite3 package on MacOS or Linux Ubuntu, it rebuilds the sqlite3 package using the correct bindings as expected. When I run the build and use the exe on Windows, or try and run the app in development mode on Windows it fails due to the bindings file failing to download. 

It appears in the log that Node-Gyp is failing to download the bindings. 

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.

node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\nodejs\\node.exe',
gyp verb cli   'C:\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@4.0.0
gyp info using node@12.2.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Python2\python2.EXE
gyp verb check python version `C:\Python2\python2.EXE -c "import sys; print("2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3]);"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.2.0
gyp verb command install [ '12.2.0' ]
gyp verb install input version string "12.2.0"
gyp verb install installing version: 12.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.2.0
gyp verb build dir attempting to create "build" dir: C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\build
gyp verb build dir "build" dir needed to be created? C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python2\python2.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\nicho\\nvm\\v12.2.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\nvm\\v12.2.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\.node-gyp\\12.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nicho\\.node-gyp\\12.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nicho\\nvm\\v12.2.0\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\nicho\\.node-gyp\\12.2.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\nicho\Dropbox\Hack\Devops\electron\offline) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nicho\nvm\v12.2.0\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
gyp ERR! cwd C:\Users\nicho\Dropbox\Hack\Devops\electron\offline
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
```

> yarn or npm i

```
• electron-builder version=20.40.2
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=sqlite3
Error: C:\nodejs\node.exe exited with code 1
Output:
yarn run v1.15.2
$ node-pre-gyp install --fallback-to-build
Failed to execute 'C:\nodejs\node.exe C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.2' (7)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.2.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.8 and electron@4.2.0 (electron-v4.2 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.2.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.2.0 | win32 | x64
gyp info spawn C:\Users\nicho\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nicho\\.electron-gyp\\4.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nicho\\.electron-gyp\\4.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\nicho\\.electron-gyp\\4.2.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.2.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:442:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.2"
gyp ERR! cwd C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\nodejs\node.exe C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.2' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1011:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3
node-pre-gyp ERR! node -v v12.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
error Command failed with exit code 1.

    at ChildProcess.<anonymous> (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:284:20)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
From previous event:
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\src\util\yarn.ts:155:24
From previous event:
    at _rebuild (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at _installAppDeps (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
    at C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\src\cli\cli.ts:46:19
error Command failed with exit code 1.
```

</details>

This is the part I am trying to solve, 

> node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz

```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.8 and electron@4.2.0 (electron-v4.2 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
```

When I go to that URL it says I do not have access to it. node-gyp fails to download the binding from that URL. I am trying to understand if this is a node-gyp issue or the package. If this binding is somewhere on the internet I can download manually. 

Also, where in the node-gyp library does the URL to the binding get added in while building?  Is this a reference in sqlite3 or node-gyp?

**Comment by richardlau** [comment]
`node-pre-gyp` is a different module: https://github.com/mapbox/node-pre-gyp

The URL itself comes from [`node-sqlite3`](https://github.com/mapbox/node-sqlite3), so that's probably the best place to start: 
https://github.com/mapbox/node-sqlite3/blob/ac3666ddaab74331a065aafa5095eb338ed59a78/package.json#L10-L15

In any case this isn't a `node-gyp` issue.

**Comment by wuno** [comment]
In the output it does use `node-pre-gyp` but it also uses `node-gyp` and says this is a `node-gyp` error. 

> gyp ERR! This is a bug in `node-gyp`.
> gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

```
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\eastside\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\eastside\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\eastside\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.2"
gyp ERR! cwd C:\Users\nicho\Dropbox\Hack\Devops\electron\eastside\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
```

**Comment by richardlau** [comment]
> 
> 
> In the output it does use `node-pre-gyp` but it also uses `node-gyp` and says this is a `node-gyp` error.
> 
> > gyp ERR! This is a bug in `node-gyp`.
> > gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> > gyp ERR!     https://github.com/nodejs/node-gyp/issues
> 
> ```
> gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\nicho\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.2"
> gyp ERR! cwd C:\Users\nicho\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3
> gyp ERR! node -v v10.13.0
> gyp ERR! node-gyp -v v4.0.0
> gyp ERR! This is a bug in `node-gyp`.
> gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
> node-pre-gyp ERR! build error
> ```

There's not enough information there to diagnose what's gone wrong -- Are there lines earlier in the log to indicate what hasn't worked (e.g. compilation failure, something not found, etc)?

**Comment by wuno** [comment]
This is the full output when I try and build and building the binary fails,

```
Error: C:\nodejs\node.exe exited with code 1
Output:
yarn run v1.15.2
$ node-pre-gyp install --fallback-to-build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\build\deps\action_before_build.vcxproj(21,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Failed to execute 'C:\nodejs\node.exe C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.2' (1)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@10.13.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.8 and electron@4.2.0 (electron-v4.2 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.13.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.13.0 | win32 | x64
gyp info spawn C:\Users\person\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\person\\.electron-gyp\\4.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\person\\.electron-gyp\\4.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\person\\.electron-gyp\\4.2.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.13.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\sqlite3\\lib\\binding\\electron-v4.2-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.2"
gyp ERR! cwd C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\nodejs\node.exe C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3\lib\binding\electron-v4.2-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.2' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\person\\Dropbox\\Hack\\Devops\\electron\\offline\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\src\util\yarn.ts:155:24
From previous event:
    at _rebuild (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installAppDeps (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
    at then (C:\Users\person\Dropbox\Hack\Devops\electron\offline\node_modules\electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
```
