### ISSUE TITLE
Header missing from 12.3.0 development files

### ISSUE THREAD

**Issue by paysonwallach** [nodejs/node-gyp#1759]
* **Node Version**: v12.3.0 (npm 6.9.0)
* **Platform**: GNU/Linux
* **Compiler**: GCC 8.3.0
* **Module**: node-pty

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> node-pty@0.8.1 install /home/paysonwallach/Repositories/node-pty
> node scripts/install.js

make: Entering directory '/home/paysonwallach/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../node_modules/nan/nan.h:54,
                 from ../src/unix/pty.cc:20:
/home/paysonwallach/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: util-inl.h: No such file or directory
 #  include <util-inl.h>
            ^~~~~~~~~~~~
compilation terminated.
make: *** [pty.target.mk:107: Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory '/home/paysonwallach/node-pty/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/paysonwallach/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.1.3-arch2-1-ARCH
gyp ERR! command "/home/paysonwallach/.nvm/versions/node/v12.3.0/bin/node" "/home/paysonwallach/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paysonwallach/node-pty
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</details>

After installing development files for 12.3.0 with `node-gyp install`, node-pty failed to build, with `make` citing that `util-inl.h` was missing. The binary compiled successfully after manually adding the header from https://github.com/nodejs/node/blob/master/src/util-inl.h.

**Comment by ridhoq** [comment]
This looks to be related to https://github.com/nodejs/node/issues/27803

**Comment by richardlau** [comment]
You'll need to pick up the fixed Node.js version 12.3.1: https://nodejs.org/en/blog/release/v12.3.1/
