### ISSUE TITLE
Rendertron - gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by jonasjacek** [nodejs/node-gyp#1761]
* **Node Version**:  
none: v11.15.0, npm: 6.9.0 

* **Platform**: 
Linux host 5.1.3-arch1-1-ARCH #1 SMP PREEMPT Thu May 16 20:59:36 UTC 2019 x86_64 GNU/Linux

* **Compiler**: 
```
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.3.0 (GCC) 
```

* **Module**: 
The error occurred when trying to build GoogleChrome Rendertron - https://github.com/GoogleChrome/rendertron

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 5.1.3-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /home/user/Repositories/rendertron/node_modules/grpc
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/Repositories/rendertron/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
node-pre-gyp ERR! System Linux 5.1.3-arch1-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/user/Repositories/rendertron/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/user/Repositories/rendertron/node_modules/grpc
node-pre-gyp ERR! node -v v11.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc --napi_version=4 --node_abi_napi=napi' (1)
npm verb lifecycle grpc@1.14.2~install: unsafe-perm in lifecycle true
npm verb lifecycle grpc@1.14.2~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Repositories/rendertron/node_modules/grpc/node_modules/.bin:/home/user/Repositories/rendertron/node_modules/.bin:/home/user/Bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/sbin/:/usr/sbin/:/home/user/.gem/ruby/2.6.0/bin
npm verb lifecycle grpc@1.14.2~install: CWD: /home/user/Repositories/rendertron/node_modules/grpc
npm info lifecycle grpc@1.14.2~install: Failed to exec install script
npm timing action:install Completed in 8127ms
npm verb unlock done using /home/user/.npm/_locks/staging-8db71f505227850e.lock for /home/user/Repositories/rendertron/node_modules/.staging
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directoryme/user/Repositories/rendertron/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 434ms
npm timing stage:runTopLevelLifecycles Completed in 29022ms
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sed: can't read ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o.d.raw: No such file or directory
/bin/sh: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o.d: No such file or directory
make: *** [grpc.target.mk:464: Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o] Error 1
make: Leaving directory '/home/user/Repositories/rendertron/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 5.1.3-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/user/Repositories/rendertron/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /home/user/Repositories/rendertron/node_modules/grpc
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: grpc@1.14.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:193:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:193:13)
npm verb stack     at maybeClose (internal/child_process.js:999:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
npm verb pkgid grpc@1.14.2
npm verb cwd /home/user/Repositories/rendertron
npm verb Linux 5.1.3-arch1-1-ARCH
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose"
npm verb node v11.15.0
npm verb npm  v6.9.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.14.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.14.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```

</details>

**Comment by richardlau** [comment]
This is most likely an issue with the grpc module. e.g. see https://github.com/grpc/grpc/issues/15576 for issues with gcc 8. 

I don't know if grpc@1.14.2 is compatible with Node.js 11. The latest version of grpc is v1.21.0: https://github.com/grpc/grpc/releases/tag/v1.21.0
