### ISSUE TITLE
running yarn throws this error

### ISSUE THREAD

**Issue by manavbp** [nodejs/node-gyp#1765]
```
yarn install v1.12.3
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning rustParserTool@0.0.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠐ ref
error C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref
Output:
C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.3.1 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program ' +
gyp info spawn args     'Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Manav-Work\\Desktop\\New ' +
gyp info spawn args     'folder\\rust-typescript-bindgen\\node_modules\\ref\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Manav-Work\\.node-gyp\\12.3.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Manav-Work\\.node-gyp\\12.3.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program ' +
gyp info spawn args     'Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Manav-Work\\.node-gyp\\12.3.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Manav-Work\\Desktop\\New ' +
gyp info spawn args     'folder\\rust-typescript-bindgen\\node_modules\\ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Manav-Work\\Desktop\\New ' +
gyp info spawn args     'folder\\rust-typescript-bindgen\\node_modules\\ref\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(222): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(253): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(2567): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(360): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(360): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(360): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(447): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(447): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(447): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(521): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(2567): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(550): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(2567): note: see declaration of 'v8::Value::Uint32Value' (compiling source file ..\src\binding.cc)
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(582): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(583): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(584): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(585): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(586): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(587): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(588): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(589): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(590): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(591): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(593): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(594): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(595): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(596): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(597): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(598): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(599): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(600): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(601): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(602): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(603): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(604): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(605): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(606): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(608): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(615): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(616): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(617): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(618): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(619): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(620): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(621): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(622): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(623): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(624): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(625): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(626): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(627): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(628): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(629): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(630): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(631): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(632): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(633): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(634): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(635): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(636): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(637): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(638): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(641): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(642): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\ref\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref\build\binding.vcxproj]
  c:\users\manav-work\desktop\new folder\rust-typescript-bindgen\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Manav-Work\Desktop\New folder\rust-typescript-bindgen\node_modules\ref
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
On running yarn I get this error

Could soneone please help me debug this

**Comment by richardlau** [comment]
The `ref` module currently does not support Node.js 12 and would need to release a new compatible version: https://github.com/TooTallNate/ref/issues/107 and https://github.com/TooTallNate/ref/pull/114.
