### ISSUE TITLE
node-gyp rebuild failed

### ISSUE THREAD

**Issue by KittyLe** [nodejs/node-gyp#1825]
* **Node Version**: `node -v: v10.16.0` and `npm -v: 6.9.0`
* **Platform**: 
```
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.17763 N/A Build 17763
System Type:              x64-based PC
```
* **Compiler**: 
```
msbuild : The term 'msbuild' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
* **Module**: `robotjs`

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
PS C:\Projects\Kawosu!> npm i robotjs

> robotjs@0.5.1 install C:\Projects\Kawosu!\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.16.0 runtime=node arch=x64 platform=win32)

C:\Projects\Kawosu!\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\KittyLe\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\Kawosu!\node_modules\robotjs
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN kawosu@1.0.6 No description
npm WARN kawosu@1.0.6 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KittyLe\AppData\Roaming\npm-cache\_logs\2019-07-15T20_51_27_358Z-debug.log
PS C:\Projects\Kawosu!>
```

</details>

**Comment by KittyLe** [comment]
Trying to install `windows-build-tools` gives me this:
```
PS C:\Projects\Kawosu!> npm i windows-build-tools -g

> windows-build-tools@5.2.2 postinstall C:\Users\KittyLe\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

fs.js:114
    throw err;
    ^

Error: EPERM: operation not permitted, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:361:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\KittyLe\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\request\index.js:18:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KittyLe\AppData\Roaming\npm-cache\_logs\2019-07-15T21_00_54_921Z-debug.log
PS C:\Projects\Kawosu!>
```

**Comment by cclauss** [comment]
You are running on Python but node-gyp requires legacy Python.

**Comment by KittyLe** [comment]
> You are running on Python but node-gyp still requires legacy Python.
Now I'm confused. Didn't understand that, what's legacy Python? 
![image](https://user-images.githubusercontent.com/41251521/61249775-c11a4700-a75e-11e9-8765-4ca7ddc07af5.png)

**Comment by KittyLe** [comment]
I have just reinstalled Python, now I have other error:
```
PS C:\Projects\Kawosu!> npm i robotjs

> robotjs@0.5.1 install C:\Projects\Kawosu!\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.16.0 runtime=node arch=x64 platform=win32)

C:\Projects\Kawosu!\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: EPERM: operation not permitted, read
gyp ERR! stack     at Object.readSync (fs.js:498:3)
gyp ERR! stack     at tryReadSync (fs.js:332:20)
gyp ERR! stack     at Object.readFileSync (fs.js:361:19)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:20)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:690:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:18:15)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\Kawosu!\node_modules\robotjs
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN kawosu@1.0.6 No description
npm WARN kawosu@1.0.6 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KittyLe\AppData\Roaming\npm-cache\_logs\2019-07-15T21_21_26_279Z-debug.log
PS C:\Projects\Kawosu!>
```
It seems like it's the same as with `windows-build-tools`.

**Comment by cclauss** [comment]
```
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
```
Legacy print statements are syntax errors in Python 3 but print() function works as expected in both Python 2 and Python 3.  Given that this line raised a SyntaxError, it is being run on Python 3.

**Comment by KittyLe** [comment]
Yes, my mistake. I have installed Python 2.7.6 and now I have permissions error. I don't think that this is node-gyp problem though.

**Comment by angelcruzt** [comment]
muchas gracias, corrigio mi error
