### ISSUE TITLE
node-gyp rebuild error in macOS

### ISSUE THREAD

**Issue by sidntrivedi012** [nodejs/node-gyp#1837]
I am getting the following error while running `npm install` in my macOS. I have not yet installed Xcode since I currently don't have enough bandwidth to download it. Is there any other workaround to make it work since I need it to work urgently as one of my project depends on it?

Any help will be much appreciated.

```
> contextify@0.1.15 install /Users/sidntrivedi012/Code/spectral-workbench.js/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:62:65: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        ContextifyContext* ctx = new ContextifyContext(info[0]->ToObject());
                                                                ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:131:56: error: no matching member function for call to 'NewInstance'
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but
      no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 0 were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:176:43: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:182:80: error: too few arguments to function call, expected 2, have 1
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:3562:3: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:192:43: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:203:43: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:209:67: error: too few arguments to function call, expected 2, have 1
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:3562:3: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:210:71: error: too few arguments to function call, expected 2, have 1
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:3562:3: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:218:43: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:229:43: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:319:53: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        if (!ContextifyContext::InstanceOf(info[0]->ToObject()))
                                                    ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/contextify.cc:322:86: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
        ContextifyContext* ctx = Nan::ObjectWrap::Unwrap<ContextifyContext>(info[0]->ToObject());
                                                                                     ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/sidntrivedi012/Library/Caches/node-gyp/10.16.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
8 warnings and 5 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sidntrivedi012/Code/spectral-workbench.js/node_modules/contextify
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sidntrivedi012/.npm/_logs/2019-07-21T11_50_57_636Z-debug.log
```

**Comment by rvagg** [comment]
Those compile errors are indicative of C++ code that was designed to work against older Node versions compiling against newer ones. You either need to downgrade your version of Node to match what's supported by the package, or find a newer version of the package (or a newer version of a dependent of the package) if one's available or find some other alternative.

It's worth noting that contextify, the package you're compiling here, has been redundant since Node 0.12 since its functionality was integrated into core. See the message here: https://github.com/brianmcd/contextify#you-dont-need-this-module-on-node--012

If you're using a package that's depending on contextify then you might want to see if there's a newer version of it available, it must be pretty old.
