### ISSUE TITLE
cannot open source file "node.h" in hello.cc

### ISSUE THREAD

**Issue by johnzhu12** [nodejs/node-gyp#1841]
* **Node Version**:v12.1.0
* **Platform**:Mac osx
* **node-gyp**:v5.0.3

I don't know if it's a problem or just a personal question 。as a nodejs addons beginner,I write a 
hello.cc file,which as below:

```c++
#include <node.h>
#include <v8.h>
using namespace v8;
// 实现􏵹定义的方法
Handle<Value> SayHello(const Arguments &args)
{
    HandleScope scope;
    return scope.Close(String::New("Hello world!"));
}
// 给传入的目􏵺对象􏱭加sayHello()方法 void Init_Hello(Handle<Object> target) {
target->Set(String::NewSymbol("sayHello"), FunctionTemplate::New(SayHello)->GetFunction());
}
// 调用NODE_MODULE()方法将注􏵻方法定义􏵼内存中 NODE_MODULE(hello, Init_Hello)
```

and my binding.gyp is like this:

```json
{
    'targets': [
        {
            'target_name': 'hello', 'sources': [
                'src/hello.cc'],
            'conditions': [['OS == "mac"',
                            {
                            }
                            ]],
            "include_dirs": [
                "<!(node -e \"require('nan')\")"
            ]
        }]
}
```

but the source code show Squiggles
![issue](https://user-images.githubusercontent.com/11485619/61708488-7c566780-ad7f-11e9-9cc5-4870c04d75c1.png)

and when I run `node-gyp configure build`

error showing:

 CXX(target) Release/obj.target/hello/src/hello.o
../src/hello.cc:5:1: error: no template named 'Handle'
Handle<Value> SayHello(const Arguments &args)
^
../src/hello.cc:5:30: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> SayHello(const Arguments &args)
                             ^~~~~~~~~
                             v8::internal::Arguments
/Users/johnzhu/Library/Caches/node-gyp/12.1.0/include/node/v8.h:117:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/hello.cc:7:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/johnzhu/Library/Caches/node-gyp/12.1.0/include/node/v8.h:1004:13: note: declared protected here
  V8_INLINE HandleScope() = default;
            ^
../src/hello.cc:8:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(String::New("Hello world!"));
           ~~~~~ ^
../src/hello.cc:8:32: error: no member named 'New' in 'v8::String'
    return scope.Close(String::New("Hello world!"));
                       ~~~~~~~~^
../src/hello.cc:11:1: error: unknown type name 'target'
target->Set(String::NewSymbol("sayHello"), FunctionTemplate::New(SayHello)->GetFunction());
^
../src/hello.cc:11:7: error: cannot use arrow operator on a type
target->Set(String::NewSymbol("sayHello"), FunctionTemplate::New(SayHello)->GetFunction());
      ^
../src/hello.cc:12:1: error: extraneous closing brace ('}')
}
^
8 errors generated.
make: *** [Release/obj.target/hello/src/hello.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/johnzhu/.nvm/versions/node/v12.1.0/lib/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/johnzhu/.nvm/versions/node/v12.1.0/bin/node" "/Users/johnzhu/.nvm/versions/node/v12.1.0/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/johnzhu/Desktop/gitlabRepo/node_addons
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

**Comment by johnzhu12** [comment]
use nan.h fixed
version issues.sorry , will close this
