### ISSUE TITLE
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by thisTom** [nodejs/node-gyp#1859]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\www\zuhao\client\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\www\\zuhao\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=6.0.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd F:\www\zuhao\client\node_modules\ffi
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (F:\www\zuhao\client\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (F:\www\zuhao\client\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (F:\www\zuhao\client\node_modules\rxjs\internal\Subscriber.js:143:22)
error Command failed with exit code 4294967295.

win10 system  ，i realy need your help

**Comment by bzoz** [comment]
Please provide output of `npm install --verbose`

**Comment by thisTom** [comment]
@bzoz
I find the problem.
I used to use”cd ./node_modules/.bin && electron-rebuild --force --module-dir=../../”. And it didn’t work, if I use “cd node_modules/ffi && node-gyp rebuild” it works well!
But I still don’t know why.   Thanks

**Comment by cclauss** [comment]
Can this issue be closed?
