### ISSUE TITLE
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by dhruvenvora** [nodejs/node-gyp#1868]
* **Node Version**: v12.9.1 
* **Platform**: Darwin LM-SJN-40001978 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
* **Compiler**: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
* **Module**: npm install 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
19 warnings and 15 errors generated.
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dhvora/Documents/dev/campaigninsightnodeweb/node_modules/memwatch-next
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm verb lifecycle memwatch-next@0.3.0~install: unsafe-perm in lifecycle true
npm verb lifecycle memwatch-next@0.3.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dhvora/Documents/dev/campaigninsightnodeweb/node_modules/memwatch-next/node_modules/.bin:/Users/dhvora/Documents/dev/campaigninsightnodeweb/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/apache-maven-3.3.9/bin
npm verb lifecycle memwatch-next@0.3.0~install: CWD: /Users/dhvora/Documents/dev/campaigninsightnodeweb/node_modules/memwatch-next
npm info lifecycle memwatch-next@0.3.0~install: Failed to exec install script
npm timing action:install Completed in 3781ms
npm verb unlock done using /Users/dhvora/.npm/_locks/staging-24da91a7b673e18e.lock for /Users/dhvora/Documents/dev/campaigninsightnodeweb/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 24ms
npm timing stage:runTopLevelLifecycles Completed in 11915ms
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN campaigninsightnodeweb@1.0.0 license should be a valid SPDX license expression

npm verb stack Error: memwatch-next@0.3.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:209:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:209:13)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm verb pkgid memwatch-next@0.3.0
npm verb cwd /Users/dhvora/Documents/dev/campaigninsightnodeweb
npm verb Darwin 18.7.0
npm verb argv "/usr/local/Cellar/node/12.9.1/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v12.9.1
npm verb npm  v6.11.2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 12802ms
```

</details>
I installed node from brew.

I have tried all the possible solutions from other threads such as https://github.com/nodejs/node-gyp/issues/809

Please let me know if any other information is needed.

**Comment by bnoordhuis** [comment]
Sorry for the delay. The `19 warnings and 15 errors generated` means you were trying to build it for a version of Node.js it doesn't support. That's not a node-gyp issue, you should take that up with memwatch-next (but the last release was 4 years ago so chances are good it's abandoned.)
