### ISSUE TITLE
node-gyp build error with node-java 

### ISSUE THREAD

**Issue by exislow** [nodejs/node-gyp#1874]
I am trying to install my dependencies (using `yarn` or `npm install`). It worked before but now I am getting the following error. It seems that node-java has some problems. Can anybody help me with this.

I also tried to remove `node_modules`, `~/.node-gyp` and `~/.cache/node-gyp` but nothing has helped.

```
node -v                                                                           
v12.10.0

npm -v                 
6.11.3

Arch Linux 5.2.13-arch1-1-ARCH #1 SMP PREEMPT Fri Sep 6 17:52:33 UTC 2019 x86_64 GNU/Linux

cc -v                                                                                  ✔  1391  16:23:07 
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.1.0 (GCC) 

----------------
$ yarn 
[...]
/home/q/.cache/node-gyp/12.10.0/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9893 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/q/.cache/node-gyp/12.10.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:66:61:   required from here
/home/q/.cache/node-gyp/12.10.0/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [nodejavabridge_bindings.target.mk:116: Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
make: Leaving directory '/home/q/backend/node_modules/java/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.13-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/q/backend/node_modules/java
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.2


------
$ npm install

[...] almost the same

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.11.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

package.json
```
"dependencies": {
    "@hapi/joi": "^15.1.1",
    "app-root-path": "^2.2.1",
    "axios": "^0.19.0",
    "bcryptjs": "2.4.3",
    "bluebird": "^3.5.5",
    "body-parser": "^1.19.0",
    "bull": "^3.10.0",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "cross-env": "^5.0.1",
    "dotenv-safe": "^6.1.0",
    "esm": "^3.2.25",
    "express": "^4.17.1",
    "express-validation": "^1.0.2",
    "helmet": "^3.20.0",
    "http-status": "^1.3.2",
    "jdbc": "^0.6.4",
    "joi": "^14.3.1",
    "jwt-simple": "0.5.6",
    "lodash": "^4.17.15",
    "method-override": "^3.0.0",
    "module-alias": "^2.2.1",
    "moment-timezone": "^0.5.26",
    "mongoose": "^5.6.9",
    "morgan": "^1.8.1",
    "passport": "^0.4.0",
    "passport-http-bearer": "^1.0.1",
    "passport-jwt": "4.0.0",
    "pm2": "^3.0.0",
    "snyk": "^1.217.1",
    "uuid": "^3.3.3",
    "webpack-merge": "^4.2.1",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "apidoc": "^0.17.7",
    "chai": "^4.1.0",
    "chai-as-promised": "^7.1.1",
    "coveralls": "^3.0.6",
    "eslint": "^6.2.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-import": "^2.18.2",
    "husky": "^3.0.4",
    "mocha": "^6.2.0",
    "nodemon": "^1.19.1",
    "nyc": "^14.1.1",
    "open-cli": "^5.0.0",
    "sinon": "^7.4.1",
    "sinon-chai": "^3.3.0",
    "supertest": "^4.0.2"
  },
```

**Comment by rvagg** [comment]
@exislow I'm pretty sure these are Node version compatibility problems. Trying to compile a C++ addon that was written to support an older version of Node.js than the one you're compiling against. You may either need to get a newer version of node-java if it exists to support the version of Node.js you're using, get them to upgrade their support (hopefully just bumping the version of NAN they are using for comptibility), or downgrade your version of Node to find one that works with the node-java version you're using.
