### ISSUE TITLE
Unable to install nfc-pcsc due to a failure of this module

### ISSUE THREAD

**Issue by MagicElyas** [nodejs/node-gyp#1878]
* **Node Version**: v10.16.3, npm:   6.9.0  
* **Platform**:  Windows 10 64 bits (command you provide won't provide any response)
* **Compiler**: Promts error 
* **Module**: nfc-pcsc 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'nfc-pcsc' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session acbc768d965288a3
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/nfc-pcsc 198ms (from cache)
8 silly pacote tag manifest for nfc-pcsc@latest fetched in 231ms
9 timing stage:loadCurrentTree Completed in 261ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule nfc-pcsc@0.7.4 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@pokusew%2fpcsclite 1824ms (from cache)
18 silly pacote range manifest for @pokusew/pcsclite@^0.5.2 fetched in 1835ms
19 silly resolveWithNewModule @pokusew/pcsclite@0.5.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/nan 122ms (from cache)
21 silly pacote range manifest for nan@^2.12.1 fetched in 140ms
22 silly resolveWithNewModule nan@2.14.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/bindings 147ms (from cache)
24 silly pacote range manifest for bindings@^1.4.0 fetched in 157ms
25 silly resolveWithNewModule bindings@1.5.0 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 51ms (from cache)
27 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 60ms
28 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
29 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2065ms
30 timing stage:loadIdealTree Completed in 2069ms
31 silly currentTree node
32 silly idealTree node
32 silly idealTree +-- @pokusew/pcsclite@0.5.2
32 silly idealTree +-- bindings@1.5.0
32 silly idealTree +-- file-uri-to-path@1.0.0
32 silly idealTree +-- nan@2.14.0
32 silly idealTree `-- nfc-pcsc@0.7.4
33 silly install generateActionsToTake
34 timing stage:generateActionsToTake Completed in 7ms
35 silly diffTrees action count 5
36 silly diffTrees add file-uri-to-path@1.0.0
37 silly diffTrees add bindings@1.5.0
38 silly diffTrees add nan@2.14.0
39 silly diffTrees add @pokusew/pcsclite@0.5.2
40 silly diffTrees add nfc-pcsc@0.7.4
41 silly decomposeActions action count 40
42 silly decomposeActions fetch file-uri-to-path@1.0.0
43 silly decomposeActions extract file-uri-to-path@1.0.0
44 silly decomposeActions preinstall file-uri-to-path@1.0.0
45 silly decomposeActions build file-uri-to-path@1.0.0
46 silly decomposeActions install file-uri-to-path@1.0.0
47 silly decomposeActions postinstall file-uri-to-path@1.0.0
48 silly decomposeActions finalize file-uri-to-path@1.0.0
49 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
50 silly decomposeActions fetch bindings@1.5.0
51 silly decomposeActions extract bindings@1.5.0
52 silly decomposeActions preinstall bindings@1.5.0
53 silly decomposeActions build bindings@1.5.0
54 silly decomposeActions install bindings@1.5.0
55 silly decomposeActions postinstall bindings@1.5.0
56 silly decomposeActions finalize bindings@1.5.0
57 silly decomposeActions refresh-package-json bindings@1.5.0
58 silly decomposeActions fetch nan@2.14.0
59 silly decomposeActions extract nan@2.14.0
60 silly decomposeActions preinstall nan@2.14.0
61 silly decomposeActions build nan@2.14.0
62 silly decomposeActions install nan@2.14.0
63 silly decomposeActions postinstall nan@2.14.0
64 silly decomposeActions finalize nan@2.14.0
65 silly decomposeActions refresh-package-json nan@2.14.0
66 silly decomposeActions fetch @pokusew/pcsclite@0.5.2
67 silly decomposeActions extract @pokusew/pcsclite@0.5.2
68 silly decomposeActions preinstall @pokusew/pcsclite@0.5.2
69 silly decomposeActions build @pokusew/pcsclite@0.5.2
70 silly decomposeActions install @pokusew/pcsclite@0.5.2
71 silly decomposeActions postinstall @pokusew/pcsclite@0.5.2
72 silly decomposeActions finalize @pokusew/pcsclite@0.5.2
73 silly decomposeActions refresh-package-json @pokusew/pcsclite@0.5.2
74 silly decomposeActions fetch nfc-pcsc@0.7.4
75 silly decomposeActions extract nfc-pcsc@0.7.4
76 silly decomposeActions preinstall nfc-pcsc@0.7.4
77 silly decomposeActions build nfc-pcsc@0.7.4
78 silly decomposeActions install nfc-pcsc@0.7.4
79 silly decomposeActions postinstall nfc-pcsc@0.7.4
80 silly decomposeActions finalize nfc-pcsc@0.7.4
81 silly decomposeActions refresh-package-json nfc-pcsc@0.7.4
82 silly install executeActions
83 silly doSerial global-install 40
84 verbose correctMkdir C:\Users\Usuario\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
85 verbose lock using C:\Users\Usuario\AppData\Roaming\npm-cache\_locks\staging-b84d9d7707df591c.lock for C:\Users\Usuario\test_nfc\node\node_modules\.staging
86 silly doParallel extract 5
87 silly extract file-uri-to-path@1.0.0
88 silly extract bindings@1.5.0
89 silly extract nan@2.14.0
90 silly extract @pokusew/pcsclite@0.5.2
91 silly extract nfc-pcsc@0.7.4
92 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
93 silly tarball trying bindings@^1.4.0 by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
94 silly tarball trying nan@^2.12.1 by hash: sha512-INOFj37C7k3AfaNTtX8RhsTw7qRy7eLET14cROi9+5HAVbbHuIWUHEauBv5qT4Av2tWasiTY1Jw6puUNqRJXQg==
95 silly tarball trying @pokusew/pcsclite@^0.5.2 by hash: sha512-Pmu3aIJBk8vrtxHAxyEA54FhsVDShqzr/tvya0c0TS4vOgWjcz0EhOYIWPzkvI8wjcqab3VHQJm5DGt55Ln5Tw==
96 silly tarball trying nfc-pcsc@latest by hash: sha512-XprBgVQt+qH+Q5HStOikbYlAPHBQOxPj8PXLifKrLCfiLzq0p5aExjM0qqX+KTfz8WiHnJi1uH5CBwc4pityOw==
97 silly extract bindings@^1.4.0 extracted to C:\Users\Usuario\test_nfc\node\node_modules\.staging\bindings-6df76204 (118ms)
98 silly extract file-uri-to-path@1.0.0 extracted to C:\Users\Usuario\test_nfc\node\node_modules\.staging\file-uri-to-path-f443f81c (134ms)
99 silly extract nfc-pcsc@latest extracted to C:\Users\Usuario\test_nfc\node\node_modules\.staging\nfc-pcsc-0cd5f24d (189ms)
100 silly extract nan@^2.12.1 extracted to C:\Users\Usuario\test_nfc\node\node_modules\.staging\nan-93815fbe (220ms)
101 silly extract @pokusew/pcsclite@^0.5.2 extracted to C:\Users\Usuario\test_nfc\node\node_modules\.staging\@pokusew\pcsclite-8f95dd6f (246ms)
102 timing action:extract Completed in 250ms
103 silly doReverseSerial unbuild 40
104 silly doSerial remove 40
105 silly doSerial move 40
106 silly doSerial finalize 40
107 silly finalize C:\Users\Usuario\test_nfc\node\node_modules\file-uri-to-path
108 silly finalize C:\Users\Usuario\test_nfc\node\node_modules\bindings
109 silly finalize C:\Users\Usuario\test_nfc\node\node_modules\nan
110 silly finalize C:\Users\Usuario\test_nfc\node\node_modules\@pokusew\pcsclite
111 silly finalize C:\Users\Usuario\test_nfc\node\node_modules\nfc-pcsc
112 timing action:finalize Completed in 18ms
113 silly doParallel refresh-package-json 5
114 silly refresh-package-json C:\Users\Usuario\test_nfc\node\node_modules\file-uri-to-path
115 silly refresh-package-json C:\Users\Usuario\test_nfc\node\node_modules\bindings
116 silly refresh-package-json C:\Users\Usuario\test_nfc\node\node_modules\nan
117 silly refresh-package-json C:\Users\Usuario\test_nfc\node\node_modules\@pokusew\pcsclite
118 silly refresh-package-json C:\Users\Usuario\test_nfc\node\node_modules\nfc-pcsc
119 timing audit submit Completed in 468ms
120 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 467ms
121 timing audit body Completed in 0ms
122 timing action:refresh-package-json Completed in 222ms
123 silly doParallel preinstall 5
124 silly preinstall file-uri-to-path@1.0.0
125 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
126 silly preinstall bindings@1.5.0
127 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
128 silly preinstall nan@2.14.0
129 info lifecycle nan@2.14.0~preinstall: nan@2.14.0
130 silly preinstall @pokusew/pcsclite@0.5.2
131 info lifecycle @pokusew/pcsclite@0.5.2~preinstall: @pokusew/pcsclite@0.5.2
132 silly preinstall nfc-pcsc@0.7.4
133 info lifecycle nfc-pcsc@0.7.4~preinstall: nfc-pcsc@0.7.4
134 timing action:preinstall Completed in 1ms
135 silly doSerial build 40
136 silly build file-uri-to-path@1.0.0
137 info linkStuff file-uri-to-path@1.0.0
138 silly linkStuff file-uri-to-path@1.0.0 has C:\Users\Usuario\test_nfc\node\node_modules as its parent node_modules
139 silly build bindings@1.5.0
140 info linkStuff bindings@1.5.0
141 silly linkStuff bindings@1.5.0 has C:\Users\Usuario\test_nfc\node\node_modules as its parent node_modules
142 silly build nan@2.14.0
143 info linkStuff nan@2.14.0
144 silly linkStuff nan@2.14.0 has C:\Users\Usuario\test_nfc\node\node_modules as its parent node_modules
145 silly build @pokusew/pcsclite@0.5.2
146 info linkStuff @pokusew/pcsclite@0.5.2
147 silly linkStuff @pokusew/pcsclite@0.5.2 has C:\Users\Usuario\test_nfc\node\node_modules as its parent node_modules
148 silly build nfc-pcsc@0.7.4
149 info linkStuff nfc-pcsc@0.7.4
150 silly linkStuff nfc-pcsc@0.7.4 has C:\Users\Usuario\test_nfc\node\node_modules as its parent node_modules
151 timing action:build Completed in 2ms
152 silly doSerial global-link 40
153 silly doParallel update-linked 0
154 silly doSerial install 40
155 silly install file-uri-to-path@1.0.0
156 info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
157 silly install bindings@1.5.0
158 info lifecycle bindings@1.5.0~install: bindings@1.5.0
159 silly install nan@2.14.0
160 info lifecycle nan@2.14.0~install: nan@2.14.0
161 silly install @pokusew/pcsclite@0.5.2
162 info lifecycle @pokusew/pcsclite@0.5.2~install: @pokusew/pcsclite@0.5.2
163 verbose lifecycle @pokusew/pcsclite@0.5.2~install: unsafe-perm in lifecycle true
164 verbose lifecycle @pokusew/pcsclite@0.5.2~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Usuario\test_nfc\node\node_modules\@pokusew\pcsclite\node_modules\.bin;C:\Users\Usuario\test_nfc\node\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Users\Usuario\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Usuario\AppData\Local\Programs\Python\Python37\;C:\Users\Usuario\AppData\Local\Microsoft\WindowsApps;C:\Users\Usuario\AppData\Roaming\npm
165 verbose lifecycle @pokusew/pcsclite@0.5.2~install: CWD: C:\Users\Usuario\test_nfc\node\node_modules\@pokusew\pcsclite
166 silly lifecycle @pokusew/pcsclite@0.5.2~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
167 silly lifecycle @pokusew/pcsclite@0.5.2~install: Returned: code: 7  signal: null
168 info lifecycle @pokusew/pcsclite@0.5.2~install: Failed to exec install script
169 timing action:install Completed in 5085ms
170 verbose unlock done using C:\Users\Usuario\AppData\Roaming\npm-cache\_locks\staging-b84d9d7707df591c.lock for C:\Users\Usuario\test_nfc\node\node_modules\.staging
171 timing stage:rollbackFailedOptional Completed in 54ms
172 timing stage:runTopLevelLifecycles Completed in 7992ms
173 silly saveTree node
173 silly saveTree `-- nfc-pcsc@0.7.4
173 silly saveTree   `-- @pokusew/pcsclite@0.5.2
173 silly saveTree     +-- bindings@1.5.0
173 silly saveTree     | `-- file-uri-to-path@1.0.0
173 silly saveTree     `-- nan@2.14.0
174 warn enoent ENOENT: no such file or directory, open 'C:\Users\Usuario\test_nfc\node\package.json'
175 verbose enoent This is related to npm not being able to find a file.
176 warn node No description
177 warn node No repository field.
178 warn node No README data
179 warn node No license field.
180 verbose stack Error: @pokusew/pcsclite@0.5.2 install: `node-gyp rebuild`
180 verbose stack Exit status 7
180 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
180 verbose stack     at EventEmitter.emit (events.js:198:13)
180 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
180 verbose stack     at ChildProcess.emit (events.js:198:13)
180 verbose stack     at maybeClose (internal/child_process.js:982:16)
180 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
181 verbose pkgid @pokusew/pcsclite@0.5.2
182 verbose cwd C:\Users\Usuario\test_nfc\node
183 verbose Windows_NT 10.0.18362
184 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nfc-pcsc"
185 verbose node v10.16.3
186 verbose npm  v6.9.0
187 error code ELIFECYCLE
188 error errno 7
189 error @pokusew/pcsclite@0.5.2 install: `node-gyp rebuild`
189 error Exit status 7
190 error Failed at the @pokusew/pcsclite@0.5.2 install script.
190 error This is probably not a problem with npm. There is likely additional logging output above.
191 verbose exit [ 7, true ]
```

</details>

I am trying to make a nfc reader work, I have been trying it on python but won't support it even in version 2.7, so, desperate for not being able to make it work I have started with the node way I have found. I am trying to follow this isntructions 
https://github.com/pokusew/nfc-pcsc
First, I got an error related to the MS Tools, but I have fixed it installing a package from the visual studio installer, the next error was this one. As it suggests I have tried to update the node-gyp version but I got the latest one so, as it also describes the prompted error, I am opening an issue here.

P.S. 1: I am using an ACR122U as NFC reader, I don't really know I this would be an important information but I leave it here.

**Comment by joaocgreis** [comment]
@MagicElyas I see there's a problem with our issue template (thanks for following it!), the npm log file does not contain the console output of node-gyp. Can you run:
```
npm install @pokusew/pcsclite --verbose
```
in a console a paste the output here? Thanks!

If this turns out to be an issue with the module and not node-gyp, the best place to open an issue is https://github.com/pokusew/node-pcsclite.
