### ISSUE TITLE
failed module install on redhat ppc64le

### ISSUE THREAD

**Issue by flynn1973** [nodejs/node-gyp#1922]
* **Node Version**:  v10.17.0-rc.0
* **Platform**: Linux lpgaixmgmtlx01 3.10.0-1062.el7.ppc64le #
* **Compiler**: gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
* **Module**: grpc@1.24.0

```
root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>npm install -g grpc@latest

> grpc@1.24.0 install /usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.0 and node@10.17.0-rc.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/build'
gyp ERR! System Linux 3.10.0-1062.el7.ppc64le
gyp ERR! command "/usr/local/node-v10.17.0-rc.0-linux-ppc64le/bin/node" "/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node/extension_binary/node-v64-linux-ppc64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node/extension_binary/node-v64-linux-ppc64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc
gyp ERR! node -v v10.17.0-rc.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node-v10.17.0-rc.0-linux-ppc64le/bin/node /usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node/extension_binary/node-v64-linux-ppc64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node/extension_binary/node-v64-linux-ppc64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 3.10.0-1062.el7.ppc64le
node-pre-gyp ERR! command "/usr/local/node-v10.17.0-rc.0-linux-ppc64le/bin/node" "/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc
node-pre-gyp ERR! node -v v10.17.0-rc.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/node-v10.17.0-rc.0-linux-ppc64le/bin/node /usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node/extension_binary/node-v64-linux-ppc64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node/extension_binary/node-v64-linux-ppc64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN You are using a pre-release version of node and things may not work as expected

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-14T11_49_15_405Z-debug.log
```

see related issue over at the grpc guys > https://github.com/grpc/grpc-node/issues/1075

**Comment by rvagg** [comment]
```
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/node-v10.17.0-rc.0-linux-ppc64le/lib/node_modules/grpc/src/node'
```

Does this need to be `-g`? Isn't grpc just a library you include in other applications? You should reserve `-g` for genuine commandline applications.

If you must `-g`, can you just do this as a normal user? Doing `-g` as `root` isn't a great idea. On single user machines it's common to set /user/local to be owned by the primary user account so you can `npm -g` and `npm link` without needing to get `sudo` involved.

You can also change the location that `-g` works in by setting your `prefix` with npm: `npm config set prefix /some/other/location`. But I'd still question first whether it needs to be `-g` and whether this must be done as root.

Aside from all that, I don't think there's anything more we can help with here unless @nodejs/platform-ppc has words of wisdom about ppc-specific things in play here.

**Comment by rvagg** [comment]
I'm hesitant to suggest it because root npm is just not advisable, but `--unsafe-perm` is an option for npm that may help here too?

**Comment by sam-github** [comment]
IIRC, when you run npm as root, it drops privs to the user `nobody` before running scripts. It doesn't do that when running .gyp builds with its built-in gyp install script, one of the reasons using a non-gyp build can run into issues that .gyp builds don't. This usually makes install scripts incapable of running when installing into global dirs that are only writable by root. `--unsafe-perm` may be the only way, here, it disables the setting of the uid to nobody, but has the risk of running arbitrary user scripts as root.

**Comment by bnoordhuis** [comment]
No follow-up. I'll go ahead and close this out.
