### ISSUE TITLE
config.gypi still generating NODE_MODULE_VERSION: 57 when it should be 64

### ISSUE THREAD

**Issue by jbdoster** [nodejs/node-gyp#1950]
* **Node Version**: Node- v10.17.0 npm 6.11.3
* **Platform**: Darwin Jonathan 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
* **Compiler**: Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
* **Module**: C++ addon

<details><summary>What am I doing wrong? node-gyp configure and rebuild finish, but I think node-gyp isn't using my current version of node (v10.17.0 which has NODE_MODULE_VERSION 64 ) which I use with nvm. </summary>

**node-gyp rebuild --verbose**

```
node-gyp rebuild --verbose
gyp info it worked if it ends with ok
gyp verb cli [ '/Users/dev/.nvm/versions/node/v10.17.0/bin/node',
gyp verb cli   '/Users/dev/.npm-global/bin/node-gyp',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@5.0.2
gyp info using node@10.17.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.10"
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 10.17.0
gyp verb command install [ '10.17.0' ]
gyp verb install input version string "10.17.0"
gyp verb install installing version: 10.17.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.17.0
gyp verb build dir attempting to create "build" dir: /Users/dev/Documents/node addons/Stats/build
gyp verb build dir "build" dir needed to be created? /Users/dev/Documents/node addons/Stats/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/dev/Documents/node addons/Stats/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/dev/Documents/node addons/Stats/config.gypi
gyp verb common.gypi checking for gypi file: /Users/dev/Documents/node addons/Stats/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/dev/.npm-global/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dev/Documents/node addons/Stats/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dev/.npm-global/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dev/Library/Caches/node-gyp/10.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/dev/Library/Caches/node-gyp/10.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/dev/.npm-global/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/dev/Library/Caches/node-gyp/10.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/dev/Documents/node addons/Stats',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/dev/Library/Caches/node-gyp/10.17.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=linker' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DBUILDING_NODE_EXTENSION' -I/Users/dev/Library/Caches/node-gyp/10.17.0/include/node -I/Users/dev/Library/Caches/node-gyp/10.17.0/src -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/openssl/config -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/openssl/openssl/include -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/uv/include -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/zlib -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -fvisibility=hidden -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/linker/src/internal/core/base.o.d.raw   -c -o Release/obj.target/linker/src/internal/core/base.o ../src/internal/core/base.cc
  c++ '-DNODE_GYP_MODULE_NAME=linker' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DBUILDING_NODE_EXTENSION' -I/Users/dev/Library/Caches/node-gyp/10.17.0/include/node -I/Users/dev/Library/Caches/node-gyp/10.17.0/src -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/openssl/config -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/openssl/openssl/include -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/uv/include -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/zlib -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -fvisibility=hidden -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/linker/src/internal/core/mean.o.d.raw   -c -o Release/obj.target/linker/src/internal/core/mean.o ../src/internal/core/mean.cc
In file included from ../src/internal/core/mean.cc:1:
../src/internal/core/../include/base.h:132:28: warning: unused variable 'arr' [-Wunused-variable]
        Local<ArrayBuffer> arr = Local<ArrayBuffer>::Cast(data);
                           ^
In file included from ../src/internal/core/mean.cc:2:
../src/internal/core/../include/mean.h:133:13: warning: unused variable 'abs_difference' [-Wunused-variable]
      float abs_difference = abs(data_set->Get(i)->NumberValue() - mean);
            ^
2 warnings generated.
  c++ '-DNODE_GYP_MODULE_NAME=linker' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DBUILDING_NODE_EXTENSION' -I/Users/dev/Library/Caches/node-gyp/10.17.0/include/node -I/Users/dev/Library/Caches/node-gyp/10.17.0/src -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/openssl/config -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/openssl/openssl/include -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/uv/include -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/zlib -I/Users/dev/Library/Caches/node-gyp/10.17.0/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -fvisibility=hidden -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/linker/src/internal/link_all.o.d.raw   -c -o Release/obj.target/linker/src/internal/link_all.o ../src/internal/link_all.cc
In file included from ../src/internal/link_all.cc:1:
In file included from ../src/internal/../../src/internal/include/mean.h:4:
../src/internal/../../src/internal/include/base.h:132:28: warning: unused variable 'arr' [-Wunused-variable]
        Local<ArrayBuffer> arr = Local<ArrayBuffer>::Cast(data);
                           ^
In file included from ../src/internal/link_all.cc:1:
../src/internal/../../src/internal/include/mean.h:133:13: warning: unused variable 'abs_difference'
      [-Wunused-variable]
      float abs_difference = abs(data_set->Get(i)->NumberValue() - mean);
            ^
2 warnings generated.
  c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.7 -arch x86_64 -L./Release -stdlib=libc++  -o Release/linker.node Release/obj.target/linker/src/internal/core/base.o Release/obj.target/linker/src/internal/core/mean.o Release/obj.target/linker/src/internal/link_all.o 
gyp info ok 
```

**node-gyp configure -j 16 build --debug**

```
Error caught:  Error: The module '/Users/dev/Documents/node addons/Stats/build/Debug/linker.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/Users/dev/Documents/node addons/node_modules/bindings/bindings.js:76:44)
    at Object.module.exports.mean (/Users/dev/Documents/node addons/Stats/src/public/lib.js:6:47)
    at Object.<anonymous> (/Users/dev/Documents/node addons/Stats/tests/mean.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```
I also tried adding the ``` --target=v10.17.0 ``` flag but that would break the configure command.

Please let me know if you need more details and I will happily provide them, thank you!

</details>

**Comment by jbdoster** [comment]
@richardlau I knew I was doing something dumb, thank you I am still green. 
I will try this when I get home!
