### ISSUE TITLE
node-gyp fails loading binding-gyp with node-addon-api when --experimental-modules enabled

### ISSUE THREAD

**Issue by bmacnaughton** [nodejs/node-gyp#1951]
`appoptics-bindings` compiles and links a node addon when `npm install` is executed. this fails in `node-gyp` when `--experimental-modules` is enabled.

when `--experimental-modules` is not enabled `npm install` succeeds.

to reproduce
1. create any dummy app. it doesn't have to have any code.
2. `export NODE_OPTIONS=--experimental-modules`
3. `npm install appoptics-bindings`

in order to have a successful installation change (2) to `export NODE_OPTIONS=--experimental-modules --no-warnings`

from https://github.com/nodejs/node/issues/30206 it appears that node-gyp is interpreting the output (`ExperimentalWarning: The ESM module loader is experimental.`) from executing `'node -p "require('node-addon-api').include"` in the binding.gyp file as an error even though no error status is returned. the reason for that interpretation is that if i add `--no-warnings` to `NODE_OPTIONS` then the build succeeds.

more details:

node v12.13.0, v13.0.1
npm 6.12.0
node-gyp v5.0.5
ubuntu 18.04

output:
```
bruce@uxpanapa:~/working/esm-modules$ npm install ~/github.com/appoptics/ao-bindings/appoptics-bindings-8.0.0.tgz 
(node:23293) ExperimentalWarning: The ESM module loader is experimental.

> appoptics-bindings@8.0.0 install /home/bruce/working/esm-modules/node_modules/appoptics-bindings
> node setup-liboboe.js && node-gyp rebuild

(node:23309) ExperimentalWarning: The ESM module loader is experimental.
(node:23321) ExperimentalWarning: The ESM module loader is experimental.
(node:23337) ExperimentalWarning: The ESM module loader is experimental.
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/bruce/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/home/bruce/.nvm/versions/node/v12.11.1/bin/node" "/home/bruce/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bruce/working/esm-modules/node_modules/appoptics-bindings
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN esm-modules@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appoptics-bindings@8.0.0 install: `node setup-liboboe.js && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appoptics-bindings@8.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruce/.npm/_logs/2019-11-01T15_24_38_416Z-debug.log
```

test environment package.json:
```
{
  "name": "esm-modules",
  "type": "module", // same error with or without this line
  "version": "1.0.0",
  "description": "testing 1, 2, 3...",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {}
}
```

appoptics-bindings package.json:
```
{
  "name": "appoptics-bindings",
  "version": "8.0.0",
  "description": "Bindings to liboboe for the AppOptics APM agent",
  "author": "Bruce A. MacNaughton <bruce@solarwinds.cloud>",
  "contributors": [
    "Stephen Belanger <admin@stephenbelanger.com>",
    "Silvio Fernandes <silviofernandes.developer@gmail.com"
  ],
  "main": "index.js",
  "gypfile": true,
  "license": {
    "name": "Librato Open License, Version 1.0",
    "url": "http://docs.traceview.solarwinds.com/Instrumentation/librato-open-license.html"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/appoptics/appoptics-bindings-node"
  },
  "bugs": {
    "url": "https://github.com/appoptics/appoptics-bindings-node/issues"
  },
  "scripts": {
    "test": "mocha test/*.test.js",
    "install": "node setup-liboboe.js && node-gyp rebuild",
    "rebuild": "node setup-liboboe.js && node-gyp rebuild"
  },
  "dependencies": {
    "bindings": "~1.2.1",
    "linux-os-info": "^2.0.0",
    "node-addon-api": "^1.6.3",
    "node-gyp": "^4.0.0"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "segfault-handler": "^1.2.0"
  }
}
```

appoptics-bindings binding.gyp:
```
{
'targets': [
    {
    'target_name': 'appoptics-bindings',
      'cflags!': [ '-fno-exceptions' ],
      'cflags_cc!': [ '-fno-exceptions' ],
      'xcode_settings': { 'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
        'CLANG_CXX_LIBRARY': 'libc++',
        'MACOSX_DEPLOYMENT_TARGET': '10.7',
      },
      'msvs_settings': {
        'VCCLCompilerTool': { 'ExceptionHandling': 1 },
      },
    'include_dirs': [
      '<!@(node -p "require(\'node-addon-api\').include")',
    ],
    # preprocessor only (in bindings.o for some reason)
    #'cflags': ['-E'],
    # suppress warnings
    #'cflags': ['-w'],
    'sources': [
        'src/bindings.cc'
    ],
    'conditions': [
        ['OS in "linux"', {
        # includes reference oboe/oboe.h, so
        'include_dirs': [
          '<!@(node -p "require(\'node-addon-api\').include")',
            '<(module_root_dir)/'
        ],
        'libraries': [
            '-loboe',
            '-L<(module_root_dir)/oboe/',
            '-Wl,-rpath-link,<(module_root_dir)/oboe/',
            '-Wl,-rpath,\$$ORIGIN/../../oboe/'
        ],
        }]
    ]
    }
]
}
```

* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
```

</details>

**Comment by bnoordhuis** [comment]
I don't think we consider that a bug. Your binding.gyp has this stanza:
```py
    'include_dirs': [
      '<!@(node -p "require(\'node-addon-api\').include")',
    ],
```
If the command prints to stderr, it's considered to have failed:
https://github.com/nodejs/node-gyp/blob/68319a2c344c822d48bd6d5dd32f82dd41384e19/gyp/pylib/gyp/input.py#L917-L922
You already mention it but `--no-warnings` is the workaround here. I'll go ahead and close this out but thanks for the report.

**Comment by dekelev** [comment]
This issue also happens without `--experimental-modules` option in NodeJS v10.15.0, simply by running NPM/Yarn install programmatically using [NodeJS child_process](https://nodejs.org/api/child_process.html).

Passing `NODE_OPTIONS: '--no-warnings'` to the child process works fine as a workaround.
