### ISSUE TITLE
node-gyp erroring on Windows

### ISSUE THREAD

**Issue by jonhue** [nodejs/node-gyp#2015]
* **Node Version**: v12.13.1
* **Platform**: Windows_NT 10.0.17763
* **Compiler**: VisualStudio/16.4.0+29519.181
* **Module**: tree-sitter-quik

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
yarn install v1.21.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ prebuild-install || node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.13.1 | win32 | x64
gyp http GET https://nodejs.org/download/release/v12.13.1/node-v12.13.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.13.1/node-v12.13.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.13.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v12.13.1/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v12.13.1/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v12.13.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.13.1/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v12.13.1/win-x86/node.lib
gyp info spawn C:\ProgramData\Chocolatey\bin\python2.EXE
gyp info spawn args [
gyp info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\runneradmin\\.node-gyp\\12.13.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\runneradmin\\.node-gyp\\12.13.1',
gyp info spawn args   '-Dnode_gyp_dir=D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\runneradmin\\.node-gyp\\12.13.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\a\\tree-sitter-quik\\tree-sitter-quik',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\a\\tree-sitter-quik\\tree-sitter-quik\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\12.13.1\\x64\\node.exe" "D:\\a\\tree-sitter-quik\\tree-sitter-quik\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\tree-sitter-quik\tree-sitter-quik
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

</details>

The same runs successfully on Linux.

**Comment by joaocgreis** [comment]
```
gyp ERR! node-gyp -v v3.8.0
```

node-gyp 3.8.0 does not support Visual Studio 2019. You need at least node-gyp 5.0.0. It's not clear to me why an old version is being used. Perhaps you have a config variable forcing yarn to use node-gyp 3.8.0.
