### ISSUE TITLE
Missing krb5.h header file on Windows

### ISSUE THREAD

**Issue by royprigat** [nodejs/node-gyp#2030]
* **Node Version**: Node v12.14.1 and npm 6.13.6
* **Platform**: Windows 10 Enterprise
* **Compiler**:  VS 2017
* **Module**:  node-krb5

I am attempting to compile the krb5 native addon without success. I keep getting an error for missing header file krb5.h and could't find any related issue that was resolved.

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\rprigat\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@12.14.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "C:\Users\rprigat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe"
gyp verb find Python - executing "C:\Users\rprigat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe" to get version
gyp verb find Python - version is "3.8.1"
gyp info find Python using Python version 3.8.1 found at "C:\Users\rprigat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 12.14.1
gyp verb command install [ '12.14.1' ]
gyp verb install input version string "12.14.1"
gyp verb install installing version: 12.14.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.14.1
gyp verb build dir attempting to create "build" dir: C:\Users\rprigat\Desktop\node-krb5-master\build
gyp verb build dir "build" dir needed to be created? C:\Users\rprigat\Desktop\node-krb5-master\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2017 (15.9.28307.1000) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp info find VS using VS2017 (15.9.28307.1000) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\rprigat\Desktop\node-krb5-master\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\rprigat\Desktop\node-krb5-master\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\rprigat\Desktop\node-krb5-master\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\rprigat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\rprigat\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rprigat\\Desktop\\node-krb5-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rprigat\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rprigat\\AppData\\Local\\node-gyp\\Cache\\12.14.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rprigat\\AppData\\Local\\node-gyp\\Cache\\12.14.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\rprigat\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\rprigat\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.14.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\rprigat\\Desktop\\node-krb5-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\rprigat\\Desktop\\node-krb5-master\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\rprigat\AppData\Local\node-gyp\Cache\12.14.1
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/20/2020 5:25:02 PM.
Project "C:\Users\rprigat\Desktop\node-krb5-master\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\Users\rprigat\Desktop\node-krb5-master\build\binding.sln" (1) is building "C:\Users\rprigat\Desktop\node-kr
b5-master\build\krb5.vcxproj.metaproj" (2) on node 1 (default targets).
Project "C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj.metaproj" (2) is building "C:\Users\rprigat\Deskt
op\node-krb5-master\node_modules\node-addon-api\src\nothing.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "C:\Users\rprigat\Desktop\node-krb5-master\build\Release\".
InitializeBuildStatus:
  Creating "Release\obj\nothing\nothing.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  All outputs are up-to-date.
  All outputs are up-to-date.
Lib:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\Lib.exe /OUT
  :"C:\Users\rprigat\Desktop\node-krb5-master\build\Release\nothing.lib" /NOLOGO /MACHINE:X64 Release\obj\nothing\nothi
  ng.obj
  Release\obj\nothing\win_delay_load_hook.obj
  nothing.vcxproj -> C:\Users\rprigat\Desktop\node-krb5-master\build\Release\\nothing.lib
FinalizeBuildStatus:
  Deleting file "Release\obj\nothing\nothing.tlog\unsuccessfulbuild".
  Touching "Release\obj\nothing\nothing.tlog\nothing.lastbuildstate".
Done Building Project "C:\Users\rprigat\Desktop\node-krb5-master\node_modules\node-addon-api\src\nothing.vcxproj" (defa
ult targets).

Project "C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj.metaproj" (2) is building "C:\Users\rprigat\Deskt
op\node-krb5-master\build\krb5.vcxproj" (4) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\krb5\".
  Creating directory "Release\obj\krb5\krb5.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\krb5\krb5.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\CL.exe /c /I
  "C:\Users\rprigat\AppData\Local\node-gyp\Cache\12.14.1\include\node" /I"C:\Users\rprigat\AppData\Local\node-gyp\Cache
  \12.14.1\src" /I"C:\Users\rprigat\AppData\Local\node-gyp\Cache\12.14.1\deps\openssl\config" /I"C:\Users\rprigat\AppDa
  ta\Local\node-gyp\Cache\12.14.1\deps\openssl\openssl\include" /I"C:\Users\rprigat\AppData\Local\node-gyp\Cache\12.14.
  1\deps\uv\include" /I"C:\Users\rprigat\AppData\Local\node-gyp\Cache\12.14.1\deps\zlib" /I"C:\Users\rprigat\AppData\Lo
  cal\node-gyp\Cache\12.14.1\deps\v8\include" /I"C:\Users\rprigat\Desktop\node-krb5-master\node_modules\node-addon-api"
   /I"\Program Files\MIT\Kerberos\include" /I"\Program Files\MIT\Kerberos\include\gssapi" /I..\src /Z7 /nologo /W3 /WX-
   /diagnostics:classic /MP /Ox /Ob2 /Oi /Ot /Oy /D NODE_GYP_MODULE_NAME=krb5 /D USING_UV_SHARED=1 /D USING_V8_SHARED=1
   /D V8_DEPRECATION_WARNINGS=1 /D V8_DEPRECATION_WARNINGS /D V8_IMMINENT_DEPRECATION_WARNINGS /D WIN32 /D _CRT_SECURE_
  NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D OPENSSL_NO_PINSHARED /D OPENSSL_THREADS /D BUILDING
  _NODE_EXTENSION /D "HOST_BINARY=\"node.exe\"" /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Z
  c:inline /GR- /Fo"Release\obj\krb5\\" /Fd"Release\obj\krb5\vc141.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275
   /wd4244 /wd4267 /FC /errorReport:queue /MP /EHsc ..\src\module.cc ..\src\krb5_bind.cc ..\src\gss_bind.cc ..\src\base
  64.cc "C:\Users\rprigat\AppData\Roaming\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
  module.cc
  krb5_bind.cc
  gss_bind.cc
  base64.cc
  win_delay_load_hook.cc
c:\users\rprigat\desktop\node-krb5-master\src\krb5_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h': No
 such file or directory (compiling source file ..\src\krb5_bind.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\kr
b5.vcxproj]
c:\users\rprigat\desktop\node-krb5-master\src\krb5_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h': No
 such file or directory (compiling source file ..\src\module.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.
vcxproj]
c:\users\rprigat\desktop\node-krb5-master\src\gss_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h': No
such file or directory (compiling source file ..\src\gss_bind.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\krb5
.vcxproj]
Done Building Project "C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj.metaproj" (default targets) -- FAIL
ED.

Done Building Project "C:\Users\rprigat\Desktop\node-krb5-master\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Users\rprigat\Desktop\node-krb5-master\build\binding.sln" (default target) (1) ->
"C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj.metaproj" (default target) (2) ->
"C:\Users\rprigat\Desktop\node-krb5-master\build\krb5.vcxproj" (default target) (4) ->
(ClCompile target) ->
  c:\users\rprigat\desktop\node-krb5-master\src\krb5_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h':
No such file or directory (compiling source file ..\src\krb5_bind.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\
krb5.vcxproj]
  c:\users\rprigat\desktop\node-krb5-master\src\krb5_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h':
No such file or directory (compiling source file ..\src\module.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\krb
5.vcxproj]
  c:\users\rprigat\desktop\node-krb5-master\src\gss_bind.h(2): fatal error C1083: Cannot open include file: 'krb5.h': N
o such file or directory (compiling source file ..\src\gss_bind.cc) [C:\Users\rprigat\Desktop\node-krb5-master\build\kr
b5.vcxproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:03.29
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\rprigat\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rprigat\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
gyp ERR! cwd C:\Users\rprigat\Desktop\node-krb5-master
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```

</details>

**Comment by rvagg** [comment]
I'm pretty sure that this just means you don't have the Kerberos library installed on your system, at least in a place that the compiler knows how to fetch.

> To build this module, you need MIT Kerberos library. Refer to the section corresponding to your operating system:

See in their binding.gyp: https://github.com/adaltas/node-krb5/blob/4ff6c7a6be6caf3c7e36e497eab3924ac160598d/binding.gyp#L19-L21

You need to have Kerberos installed on your system, in that exact location such that the `include` directory can be pulled in during compile. Perhaps you could contribute docs back to the node-krb5 README when you get this sorted so it's clear for the next person?

**Comment by royprigat** [comment]
@rvagg I have installed Kerberos for Windows and it seems to get through the step of finding the krb5.h header file. But, unfortunately now it fails when it tries to find the unistd.h header file which has to do with Unix based systems.

**Comment by rvagg** [comment]
@royprigat I think you're probably going to have to take this up with the node-krb5 folks. Sorry, we usually can't offer generic help here unless someone happens to be reading this who knows such situations and their solutions off the top of their head.
