### ISSUE TITLE
Nodejs v13.8 vs rdkafka 2.7.4 support

### ISSUE THREAD

**Issue by ntkumar1** [nodejs/node-gyp#2055]
* **Node Version**: 13.8
* **Platform**: macOS Catalina 10.15.1
* **Compiler**: 
* **Module**: 

We are using a base image with Node Version [13.8-slim], NPM Version [6.13.6] and install
node-rdkafka version [2.7.4]. The below error occurs during the make command.

```
node-librdkafka.target.mk:130: recipe for target 'Release/obj.target/node-librdkafka/src/binding.o' failed
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory '/usr/src/app/node_modules/node-rdkafka/build'
make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/node-rdkafka
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN security-advisor-shard-manager@0.0.1 license should be a valid SPDX license expression
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-20T10_10_01_699Z-debug.log
```

</details>

**Comment by richardlau** [comment]
https://github.com/Blizzard/node-rdkafka/issues/733 says that module does not currently support Node.js 13.
