### ISSUE TITLE
`gyp rebuild` fails during npm install (python3.7). 

### ISSUE THREAD

**Issue by sadvazha** [nodejs/node-gyp#2064]
* **Node Version**: 10.19.0
* **Platform**: Linux ubiytsa 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
* **Module**: npm 6.13.4

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> node-rdkafka@2.7.0 install /home/scandal/work/pos-backend/node_modules/node-rdkafka
> node-gyp rebuild

Traceback (most recent call last):
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 794, in Write
    extra_mac_bundle_resources, part_of_all)
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 978, in WriteActions
    part_of_all=part_of_all, command=name)
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1724, in WriteDoCmd
    force = True)
  File "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1779, in WriteMakeRule
    cmddigest = hashlib.sha1(command if command else self.target).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-88-generic
gyp ERR! command "/home/scandal/.nvm/versions/node/v10.19.0/bin/node" "/home/scandal/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/scandal/work/pos-backend/node_modules/node-rdkafka
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN @nestjs/cqrs@6.1.0 requires a peer of reflect-metadata@0.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN pos-backend@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scandal/.npm/_logs/2020-03-09T10_19_19_581Z-debug.log
```
I could not install `node-rdkafka` module without setting PYTHON to v2.7. My current version of python is 3.7.1
</details>

**Comment by rvagg** [comment]
@cclauss one for you I think? I can't see anything in https://github.com/Blizzard/node-rdkafka/blob/master/binding.gyp that suggests unicode is getting involved, other than the `BUILD_LIBRDKAFKA` environment variable _possibly_ but it's only used to check for `==1`. I also don't see any unicode in the paths here. 🤷‍♂

**Comment by cclauss** [comment]
I believe that @dothebart nailed this one in #1925 which landed in [v5.0.6](https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v506-2019-12-16).  v5.0.5 does not have this fix so I believe that npm/cli needs to do anothe gyp round trip.

**Comment by dothebart** [comment]
yes, this stacktrace sounds familliar.

**Comment by sadvazha** [comment]
Yep, works for me after updating `npm`
