### ISSUE TITLE
Windows 10 LINK : fatal error LNK1104

### ISSUE THREAD

**Issue by franklevasseur** [nodejs/node-gyp#2070]
* **Node Version**: 12.16.1 (using [nvm](https://github.com/coreybutler/nvm-windows))
* **Platform**: Windows 10
* **Compiler**: MSbuild 15.0 downloaded [here](https://visualstudio.microsoft.com/fr/downloads/?rr=https%3A%2F%2Fwww.google.com%2F)
* **Module**: my own node binding for libsvm
<details><summary>Verbose output (running with node v12.16.1):</summary>

```
yarn run v1.16.0
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.1 | win32 | x64
gyp info find Python using Python version 2.7.16 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.4.29905.134) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp\\addon.gypi',gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\12.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\franc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "-m".
  nothing.vcxproj -> C:\Users\franc\Documents-franc\botpress-root\node-svm2\build\Release\\nothing.lib
  main.cpp
  hello_world.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1104: impossible d'ouvrir le fichier '.lib' [C:\Users\franc\Documents-franc\botpress-root\node-sv 
m2\build\node-svm.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-gyp\lib\build.js:195:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\franc\Documents-franc\botpress-root\node-svm2
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

<details><summary>Verbose output (running with node v10.11.0):</summary>

```
yarn run v1.16.0
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.11.0 | win32 | x64
gyp info find Python using Python version 2.7.16 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.4.29905.134) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\10.11.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\10.11.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\franc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\10.11.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "-m".
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\franc\Documents-franc\botpress-root\node-svm2\build\Release\\nothing.lib
  main.cpp
  hello_world.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1181: impossible d'ouvrir le fichier en entrÚe '.lib' [C:\Users\franc\Documents-franc\botpress-ro
ot\node-svm2\build\node-svm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-gyp\lib\build.js:195:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\franc\\Documents-franc\\botpress-root\\node-svm2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\franc\Documents-franc\botpress-root\node-svm2
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

Hi,

I have a different error message weither I use node v12.16.1 or v10.11.0.

The binding works fine both on ubuntu 18.04 and macos, but not on Windows.

I first commented [this issue](https://github.com/nodejs/node-gyp/issues/1394) because it really look like the same error I get when using node v10.11.0.

But because the issue is closed, I decided to post a new one here.

If there's any other information I can provide to help, let me know.

Sorry in advance for my bad english,

François

**Comment by bzoz** [comment]
Looks like it is looking for a library with empty name: `.lib`. Can you share your code, or at least your `binding.gyp`?

**Comment by franklevasseur** [comment]
Yes it does! It's actually searching for a library named ```.lib``` but I have not clue why... Here's the ```node-svm.vcxproj``` file content:

<details><summary>node-svm.vcxproj file content:</summary>

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>{528CE9A2-48C4-2866-080D-BD60E8134E6E}</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
    <RootNamespace>node-svm</RootNamespace>
    <IgnoreWarnCompileDuplicatedFilename>true</IgnoreWarnCompileDuplicatedFilename>
    <PreferredToolArchitecture>x64</PreferredToolArchitecture>
    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props"/>
  <PropertyGroup Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
  </PropertyGroup>
  <PropertyGroup Label="Locals">
    <PlatformToolset>v142</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props"/>
  <Import Project="$(VCTargetsPath)\BuildCustomizations\masm.props"/>
  <ImportGroup Label="ExtensionSettings"/>
  <ImportGroup Label="PropertySheets">
    <Import Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props"/>
  </ImportGroup>
  <PropertyGroup Label="UserMacros"/>
  <PropertyGroup>
    <ExecutablePath>$(ExecutablePath);$(MSBuildProjectDirectory)\..\bin\;$(MSBuildProjectDirectory)\..\bin\</ExecutablePath>
    <IgnoreImportLibrary>true</IgnoreImportLibrary>
    <IntDir>$(Configuration)\obj\$(ProjectName)\</IntDir>
    <LinkIncremental Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</LinkIncremental>
    <OutDir>$(SolutionDir)$(Configuration)\</OutDir>
    <TargetExt Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">.node</TargetExt>
    <TargetExt Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">.node</TargetExt>
    <TargetExt Condition="'$(Configuration)|$(Platform)'=='Release|x64'">.node</TargetExt>
    <TargetExt Condition="'$(Configuration)|$(Platform)'=='Release|x64'">.node</TargetExt>
    <TargetName>$(ProjectName)</TargetName>
    <TargetPath>$(OutDir)\$(ProjectName).node</TargetPath>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <AdditionalIncludeDirectories>C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\include\node;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\src;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\config;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\openssl\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\uv\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\zlib;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\v8\include;C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-addon-api;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
      <BufferSecurityCheck>true</BufferSecurityCheck>
      <CompileAsWinRT>false</CompileAsWinRT>
      <DebugInformationFormat>OldStyle</DebugInformationFormat>
      <DisableSpecificWarnings>4351;4355;4800;4251;4275;4244;4267;%(DisableSpecificWarnings)</DisableSpecificWarnings>
      <ExceptionHandling>false</ExceptionHandling>
      <MinimalRebuild>false</MinimalRebuild>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <OmitFramePointers>false</OmitFramePointers>
      <Optimization>Disabled</Optimization>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <PreprocessorDefinitions>NODE_GYP_MODULE_NAME=node-svm;USING_UV_SHARED=1;USING_V8_SHARED=1;V8_DEPRECATION_WARNINGS=1;V8_DEPRECATION_WARNINGS;V8_IMMINENT_DEPRECATION_WARNINGS;WIN32;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_HAS_EXCEPTIONS=0;OPENSSL_NO_PINSHARED;OPENSSL_THREADS;NAPI_DISABLE_CPP_EXCEPTIONS;BUILDING_NODE_EXTENSION;HOST_BINARY=&quot;node.exe&quot;;DEBUG;_DEBUG;V8_ENABLE_CHECKS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
      <StringPooling>true</StringPooling>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <TreatWarningAsError>false</TreatWarningAsError>
      <WarningLevel>Level3</WarningLevel>
    </ClCompile>
    <Link>
      <AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;&quot;C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\x64\\node.lib&quot;;.lib</AdditionalDependencies>
      <AdditionalOptions>/ignore:4199 %(AdditionalOptions)</AdditionalOptions>
      <DelayLoadDLLs>node.exe;%(DelayLoadDLLs)</DelayLoadDLLs>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <OutputFile>$(OutDir)$(ProjectName).node</OutputFile>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <TargetExt>.node</TargetExt>
      <TargetMachine>MachineX64</TargetMachine>
    </Link>
    <ResourceCompile>
      <AdditionalIncludeDirectories>C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\include\node;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\src;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\config;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\openssl\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\uv\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\zlib;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\v8\include;C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-addon-api;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>NODE_GYP_MODULE_NAME=node-svm;USING_UV_SHARED=1;USING_V8_SHARED=1;V8_DEPRECATION_WARNINGS=1;V8_DEPRECATION_WARNINGS;V8_IMMINENT_DEPRECATION_WARNINGS;WIN32;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_HAS_EXCEPTIONS=0;OPENSSL_NO_PINSHARED;OPENSSL_THREADS;NAPI_DISABLE_CPP_EXCEPTIONS;BUILDING_NODE_EXTENSION;HOST_BINARY=&quot;node.exe&quot;;DEBUG;_DEBUG;V8_ENABLE_CHECKS;%(PreprocessorDefinitions);%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <AdditionalIncludeDirectories>C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\include\node;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\src;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\config;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\openssl\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\uv\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\zlib;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\v8\include;C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-addon-api;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <BufferSecurityCheck>true</BufferSecurityCheck>
      <CompileAsWinRT>false</CompileAsWinRT>
      <DebugInformationFormat>OldStyle</DebugInformationFormat>
      <DisableSpecificWarnings>4351;4355;4800;4251;4275;4244;4267;%(DisableSpecificWarnings)</DisableSpecificWarnings>
      <ExceptionHandling>false</ExceptionHandling>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <OmitFramePointers>true</OmitFramePointers>
      <Optimization>Full</Optimization>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <PreprocessorDefinitions>NODE_GYP_MODULE_NAME=node-svm;USING_UV_SHARED=1;USING_V8_SHARED=1;V8_DEPRECATION_WARNINGS=1;V8_DEPRECATION_WARNINGS;V8_IMMINENT_DEPRECATION_WARNINGS;WIN32;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_HAS_EXCEPTIONS=0;OPENSSL_NO_PINSHARED;OPENSSL_THREADS;NAPI_DISABLE_CPP_EXCEPTIONS;BUILDING_NODE_EXTENSION;HOST_BINARY=&quot;node.exe&quot;;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <RuntimeTypeInfo>false</RuntimeTypeInfo>
      <StringPooling>true</StringPooling>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <TreatWarningAsError>false</TreatWarningAsError>
      <WarningLevel>Level3</WarningLevel>
    </ClCompile>
    <Link>
      <AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;&quot;C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\x64\\node.lib&quot;;.lib</AdditionalDependencies>
      <AdditionalOptions>/ignore:4199 %(AdditionalOptions)</AdditionalOptions>
      <DelayLoadDLLs>node.exe;%(DelayLoadDLLs)</DelayLoadDLLs>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <OutputFile>$(OutDir)$(ProjectName).node</OutputFile>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <TargetExt>.node</TargetExt>
      <TargetMachine>MachineX64</TargetMachine>
    </Link>
    <ResourceCompile>
      <AdditionalIncludeDirectories>C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\include\node;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\src;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\config;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\openssl\openssl\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\uv\include;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\zlib;C:\Users\franc\AppData\Local\node-gyp\Cache\12.16.1\deps\v8\include;C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-addon-api;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>NODE_GYP_MODULE_NAME=node-svm;USING_UV_SHARED=1;USING_V8_SHARED=1;V8_DEPRECATION_WARNINGS=1;V8_DEPRECATION_WARNINGS;V8_IMMINENT_DEPRECATION_WARNINGS;WIN32;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_HAS_EXCEPTIONS=0;OPENSSL_NO_PINSHARED;OPENSSL_THREADS;NAPI_DISABLE_CPP_EXCEPTIONS;BUILDING_NODE_EXTENSION;HOST_BINARY=&quot;node.exe&quot;;%(PreprocessorDefinitions);%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <None Include="..\binding.gyp"/>
  </ItemGroup>
  <ItemGroup>
    <ClCompile Include="..\cppsrc\main.cpp"/>
    <ClCompile Include="..\cppsrc\hello_world.cpp"/>
    <ClCompile Include="C:\Users\franc\Documents-franc\botpress-root\node-svm2\node_modules\node-gyp\src\win_delay_load_hook.cc"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\node_modules\node-addon-api\src\nothing.vcxproj">
      <Project>{C486577C-EEB7-7220-09A5-3F6978FB7806}</Project>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets"/>
  <Import Project="$(VCTargetsPath)\BuildCustomizations\masm.targets"/>
  <ImportGroup Label="ExtensionTargets"/>
</Project>

```
</details>

My ```binding.gyp file``` looks like this:

```
{
    "targets": [{
        "target_name": "node-svm",
        "cflags!": [ "-fno-exceptions" ],
        "cflags_cc!": [ "-fno-exceptions" ],
        "sources": [
            "cppsrc/main.cpp",
            "cppsrc/hello_world.cpp"
        ],
        'include_dirs': [
            "<!@(node -p \"require('node-addon-api').include\")"
        ],
        'libraries': [""],
        'dependencies': [
            "<!(node -p \"require('node-addon-api').gyp\")"
        ],
        'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ]
    }]
}
```

I removed all code from [libsvm](https://github.com/cjlin1/libsvm) just to make sure the problem does not come from there.

Again, the problem only occurs on windows and the same repo builds on ubuntu18.04 and MacOS...

Thanks again for any help,

François

**Comment by bzoz** [comment]
`<AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;&quot;C:\\Users\\franc\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\x64\\node.lib&quot;;.lib</AdditionalDependencies>`
At the very end there is the `.lib`.

Maybe try removing `'libraries': [""],`  from your gyp file?

**Comment by franklevasseur** [comment]
Well, 

that was it haha!!

@bzoz, YOU'RE THE REAL MVP

**Comment by bzoz** [comment]
Glad I could help!
