### ISSUE TITLE
`gyp` failed with exit code: 1 when install expo-task-manger

### ISSUE THREAD

**Issue by sarahalmunif** [nodejs/node-gyp#2085]
* **Node Version**:node v13.11.0 , npm 6.13.7 
* **Platform**: Darwin MacBook-Pro-alkhas-b-Sara-2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
* **Compiler**: Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* **Module**: expo install expo-task-manager

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Installing 1 SDK 36.0.0 compatible native module using npm.
> npm install

> fsevents@1.2.11 install /Users/saramuneef/maghnaApplication/maghnaGit/Maghna/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/saramuneef/maghnaApplication/maghnaGit/Maghna/node_modules/fsevents
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

updated 1 package and audited 962609 packages in 9.191s

22 packages are looking for funding
  run `npm fund` for details
```

</details>

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md to install XCode command line interface tools.
