### ISSUE TITLE
node-gyp cannot find the python installed by cygwin.

### ISSUE THREAD

**Issue by LeuisKen** [nodejs/node-gyp#2087]
* **Node Version**: 10.19.0
* **Platform**: CYGWIN_NT-6.3 cp01-win2012-20 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin
* **Compiler**: 
* **Module**: https://github.com/microsoft/node-pty

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
[2020-04-02 19:07:10] gyp info using node-gyp@6.1.0
[2020-04-02 19:07:10] gyp info using node@10.19.0 | win32 | x64
[2020-04-02 19:07:10] gyp verb command rebuild []
[2020-04-02 19:07:10] gyp verb command clean []
[2020-04-02 19:07:10] gyp verb clean removing "build" directory
[2020-04-02 19:07:10] gyp verb command configure []
[2020-04-02 19:07:10] gyp sill find Python runChecks: err = undefined
[2020-04-02 19:07:10] gyp verb find Python checking Python explicitly set from NODE_GYP_FORCE_PYTHON
[2020-04-02 19:07:10] gyp verb find Python - process.env.NODE_GYP_FORCE_PYTHON is "D:\cygwin\bin\python2.7.exe"
[2020-04-02 19:07:10] gyp verb find Python - executing "D:\cygwin\bin\python2.7.exe" to get executable path
[2020-04-02 19:07:10] gyp sill find Python execFile: exec = "\"D:\\cygwin\\bin\\python2.7.exe\""
[2020-04-02 19:07:10] gyp sill find Python execFile: args = ["\"-c\"","\"import sys; print(sys.executable);\""]
[2020-04-02 19:07:11] gyp sill find Python execFile result: err = null
[2020-04-02 19:07:11] gyp sill find Python execFile result: stdout = "/usr/bin/python2.7\n"
[2020-04-02 19:07:11] gyp sill find Python execFile result: stderr = ""
[2020-04-02 19:07:11] gyp verb find Python - executable path is "/usr/bin/python2.7"
[2020-04-02 19:07:11] gyp verb find Python - executing "/usr/bin/python2.7" to get version
[2020-04-02 19:07:11] gyp sill find Python execFile: exec = "/usr/bin/python2.7"
[2020-04-02 19:07:11] gyp sill find Python execFile: args = ["-c","import sys; print(\"%s.%s.%s\" % sys.version_info[:3]);"]
[2020-04-02 19:07:11] gyp sill find Python execFile result: stdout = ""
[2020-04-02 19:07:11] gyp sill find Python execFile result: stderr = ""
[2020-04-02 19:07:11] gyp verb find Python - "/usr/bin/python2.7" could not be run
[2020-04-02 19:07:11] gyp sill find Python runChecks: err = "Error: spawn /usr/bin/python2.7 ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
[2020-04-02 19:07:11] gyp ERR! find Python 
[2020-04-02 19:07:11] gyp ERR! find Python checking Python explicitly set from NODE_GYP_FORCE_PYTHON
[2020-04-02 19:07:11] gyp ERR! find Python - process.env.NODE_GYP_FORCE_PYTHON is "D:\cygwin\bin\python2.7.exe"
[2020-04-02 19:07:11] gyp ERR! find Python - executable path is "/usr/bin/python2.7"
[2020-04-02 19:07:11] gyp ERR! find Python - "/usr/bin/python2.7" could not be run
[2020-04-02 19:07:11] gyp ERR! find Python 
[2020-04-02 19:07:11] gyp ERR! find Python **********************************************************
[2020-04-02 19:07:11] gyp ERR! find Python You need to install the latest version of Python.
[2020-04-02 19:07:11] gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
[2020-04-02 19:07:11] gyp ERR! find Python you can try one of the following options:
[2020-04-02 19:07:11] gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
[2020-04-02 19:07:11] gyp ERR! find Python   (accepted by both node-gyp and npm)
[2020-04-02 19:07:11] gyp ERR! find Python - Set the environment variable PYTHON
[2020-04-02 19:07:11] gyp ERR! find Python - Set the npm configuration variable python:
[2020-04-02 19:07:11] gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
[2020-04-02 19:07:11] gyp ERR! find Python For more information consult the documentation at:
[2020-04-02 19:07:11] gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
[2020-04-02 19:07:11] gyp ERR! find Python **********************************************************
[2020-04-02 19:07:11] gyp ERR! find Python 
[2020-04-02 19:07:11] gyp ERR! configure error 
[2020-04-02 19:07:11] gyp ERR! stack Error: Could not find any Python installation to use
```

</details>

I'm using node-gyp on a Windows machine which installed python using cygwin. And cygwin installed python 2.7.16 at `D:\cygwin\bin\python2.7.exe` which was the NODE_GYP_FORCE_PYTHON I set, but node-gyp can't use this python due to the follow logic.

According to the log, we could find that node-gyp could using the `D:\cygwin\bin\python2.7.exe`. After that it executing a script to get the `sys.executable`variable, but the python installed by cygwin return this value as `"/usr/bin/python2.7"`, not `D:\cygwin\bin\python2.7.exe` that we need.

Then as node-gyp getting the python using `"/usr/bin/python2.7"` by spawn, spawn could not recognize the unix like path that cygwin python provided, so the error ENOENT throwed and node-gyp treat this python as invalid.

I think maybe we could support this case by supporting some way to skip the `sys.executable` check, maybe a new environment variable like NODE_GYP_FORCE_PYTHON.

Thank you.

**Comment by cclauss** [comment]
What command did you type?

What do you see when you: `D:\cygwin\bin\python2.7.exe --version`

**Comment by bzoz** [comment]
The recommended way is to use the [Windows Store, as in the README](https://github.com/nodejs/node-gyp#on-windows). I don't see a way we could support all the Python installations that do not play along nicely.

**Comment by LeuisKen** [comment]
> The recommended way is to use the [Windows Store, as in the README](https://github.com/nodejs/node-gyp#on-windows). I don't see a way we could support all the Python installations that do not play along nicely.

Maybe you're right, I'll close this issue. It took me hours to find this problem, and hope this issue could save others time.
