### ISSUE TITLE
Error: ref@1.3.5 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by DataScientist1** [nodejs/node-gyp#2094]
here is my log of problem
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'autoit'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose npm-session 736f06b3970231c8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/autoit 3397ms
8 http fetch GET 200 https://registry.npmjs.org/autoit/-/autoit-1.1.11.tgz 6079ms
9 silly pacote tag manifest for autoit@latest fetched in 9517ms
10 timing stage:loadCurrentTree Completed in 9554ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule autoit@1.1.11 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/ffi 185ms
19 http fetch GET 200 https://registry.npmjs.org/ref-struct 303ms
20 http fetch GET 200 https://registry.npmjs.org/iconv-lite 469ms
21 http fetch GET 200 https://registry.npmjs.org/ref 511ms
22 http fetch GET 200 https://registry.npmjs.org/ref-struct/-/ref-struct-1.1.0.tgz 941ms
23 silly pacote range manifest for ref-struct@>=1.0.2 fetched in 1259ms
24 silly resolveWithNewModule ref-struct@1.1.0 checking installable status
25 http fetch GET 200 https://registry.npmjs.org/ffi/-/ffi-2.3.0.tgz 11418ms
26 silly pacote range manifest for ffi@>=2.0.0 fetched in 11621ms
27 silly resolveWithNewModule ffi@2.3.0 checking installable status
28 http fetch GET 200 https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.5.1.tgz 12245ms
29 silly pacote range manifest for iconv-lite@>=0.4.11 fetched in 12727ms
30 silly resolveWithNewModule iconv-lite@0.5.1 checking installable status
31 http fetch GET 200 https://registry.npmjs.org/ref/-/ref-1.3.5.tgz 12916ms
32 silly pacote range manifest for ref@>=1.2.0 fetched in 13450ms
33 silly resolveWithNewModule ref@1.3.5 checking installable status
34 http fetch GET 200 https://registry.npmjs.org/nan 433ms
35 http fetch GET 200 https://registry.npmjs.org/bindings 484ms
36 http fetch GET 200 https://registry.npmjs.org/debug 496ms
37 http fetch GET 200 https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz 223ms
38 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-2.6.9.tgz 231ms
39 silly pacote range manifest for bindings@~1.2.0 fetched in 736ms
40 silly resolveWithNewModule bindings@1.2.1 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/nan/-/nan-2.14.0.tgz 297ms
42 silly pacote range manifest for debug@2 fetched in 742ms
43 silly resolveWithNewModule debug@2.6.9 checking installable status
44 silly pacote range manifest for nan@2 fetched in 747ms
45 silly resolveWithNewModule nan@2.14.0 checking installable status
46 http fetch GET 200 https://registry.npmjs.org/ms 115ms
47 http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.0.0.tgz 210ms
48 silly pacote version manifest for ms@2.0.0 fetched in 339ms
49 silly resolveWithNewModule ms@2.0.0 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/safer-buffer 79ms
51 http fetch GET 200 https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz 110ms
52 silly pacote range manifest for safer-buffer@>= 2.1.2 < 3 fetched in 200ms
53 silly resolveWithNewModule safer-buffer@2.1.2 checking installable status
54 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 14791ms
55 timing stage:loadIdealTree Completed in 14806ms
56 silly currentTree autoitSetup@1.0.0
57 silly idealTree autoitSetup@1.0.0
57 silly idealTree +-- autoit@1.1.11
57 silly idealTree +-- bindings@1.2.1
57 silly idealTree +-- debug@2.6.9
57 silly idealTree +-- ffi@2.3.0
57 silly idealTree +-- iconv-lite@0.5.1
57 silly idealTree +-- ms@2.0.0
57 silly idealTree +-- nan@2.14.0
57 silly idealTree +-- ref-struct@1.1.0
57 silly idealTree +-- ref@1.3.5
57 silly idealTree `-- safer-buffer@2.1.2
58 silly install generateActionsToTake
59 timing stage:generateActionsToTake Completed in 12ms
60 silly diffTrees action count 10
61 silly diffTrees add bindings@1.2.1
62 silly diffTrees add ms@2.0.0
63 silly diffTrees add debug@2.6.9
64 silly diffTrees add nan@2.14.0
65 silly diffTrees add ref@1.3.5
66 silly diffTrees add ref-struct@1.1.0
67 silly diffTrees add safer-buffer@2.1.2
68 silly diffTrees add ffi@2.3.0
69 silly diffTrees add iconv-lite@0.5.1
70 silly diffTrees add autoit@1.1.11
71 silly decomposeActions action count 80
72 silly decomposeActions fetch bindings@1.2.1
73 silly decomposeActions extract bindings@1.2.1
74 silly decomposeActions preinstall bindings@1.2.1
75 silly decomposeActions build bindings@1.2.1
76 silly decomposeActions install bindings@1.2.1
77 silly decomposeActions postinstall bindings@1.2.1
78 silly decomposeActions finalize bindings@1.2.1
79 silly decomposeActions refresh-package-json bindings@1.2.1
80 silly decomposeActions fetch ms@2.0.0
81 silly decomposeActions extract ms@2.0.0
82 silly decomposeActions preinstall ms@2.0.0
83 silly decomposeActions build ms@2.0.0
84 silly decomposeActions install ms@2.0.0
85 silly decomposeActions postinstall ms@2.0.0
86 silly decomposeActions finalize ms@2.0.0
87 silly decomposeActions refresh-package-json ms@2.0.0
88 silly decomposeActions fetch debug@2.6.9
89 silly decomposeActions extract debug@2.6.9
90 silly decomposeActions preinstall debug@2.6.9
91 silly decomposeActions build debug@2.6.9
92 silly decomposeActions install debug@2.6.9
93 silly decomposeActions postinstall debug@2.6.9
94 silly decomposeActions finalize debug@2.6.9
95 silly decomposeActions refresh-package-json debug@2.6.9
96 silly decomposeActions fetch nan@2.14.0
97 silly decomposeActions extract nan@2.14.0
98 silly decomposeActions preinstall nan@2.14.0
99 silly decomposeActions build nan@2.14.0
100 silly decomposeActions install nan@2.14.0
101 silly decomposeActions postinstall nan@2.14.0
102 silly decomposeActions finalize nan@2.14.0
103 silly decomposeActions refresh-package-json nan@2.14.0
104 silly decomposeActions fetch ref@1.3.5
105 silly decomposeActions extract ref@1.3.5
106 silly decomposeActions preinstall ref@1.3.5
107 silly decomposeActions build ref@1.3.5
108 silly decomposeActions install ref@1.3.5
109 silly decomposeActions postinstall ref@1.3.5
110 silly decomposeActions finalize ref@1.3.5
111 silly decomposeActions refresh-package-json ref@1.3.5
112 silly decomposeActions fetch ref-struct@1.1.0
113 silly decomposeActions extract ref-struct@1.1.0
114 silly decomposeActions preinstall ref-struct@1.1.0
115 silly decomposeActions build ref-struct@1.1.0
116 silly decomposeActions install ref-struct@1.1.0
117 silly decomposeActions postinstall ref-struct@1.1.0
118 silly decomposeActions finalize ref-struct@1.1.0
119 silly decomposeActions refresh-package-json ref-struct@1.1.0
120 silly decomposeActions fetch safer-buffer@2.1.2
121 silly decomposeActions extract safer-buffer@2.1.2
122 silly decomposeActions preinstall safer-buffer@2.1.2
123 silly decomposeActions build safer-buffer@2.1.2
124 silly decomposeActions install safer-buffer@2.1.2
125 silly decomposeActions postinstall safer-buffer@2.1.2
126 silly decomposeActions finalize safer-buffer@2.1.2
127 silly decomposeActions refresh-package-json safer-buffer@2.1.2
128 silly decomposeActions fetch ffi@2.3.0
129 silly decomposeActions extract ffi@2.3.0
130 silly decomposeActions preinstall ffi@2.3.0
131 silly decomposeActions build ffi@2.3.0
132 silly decomposeActions install ffi@2.3.0
133 silly decomposeActions postinstall ffi@2.3.0
134 silly decomposeActions finalize ffi@2.3.0
135 silly decomposeActions refresh-package-json ffi@2.3.0
136 silly decomposeActions fetch iconv-lite@0.5.1
137 silly decomposeActions extract iconv-lite@0.5.1
138 silly decomposeActions preinstall iconv-lite@0.5.1
139 silly decomposeActions build iconv-lite@0.5.1
140 silly decomposeActions install iconv-lite@0.5.1
141 silly decomposeActions postinstall iconv-lite@0.5.1
142 silly decomposeActions finalize iconv-lite@0.5.1
143 silly decomposeActions refresh-package-json iconv-lite@0.5.1
144 silly decomposeActions fetch autoit@1.1.11
145 silly decomposeActions extract autoit@1.1.11
146 silly decomposeActions preinstall autoit@1.1.11
147 silly decomposeActions build autoit@1.1.11
148 silly decomposeActions install autoit@1.1.11
149 silly decomposeActions postinstall autoit@1.1.11
150 silly decomposeActions finalize autoit@1.1.11
151 silly decomposeActions refresh-package-json autoit@1.1.11
152 silly install executeActions
153 silly doSerial global-install 80
154 verbose correctMkdir C:\Users\muhammad.adnan\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
155 verbose makeCacheDir UID & GID are irrelevant on win32
156 verbose lock using C:\Users\muhammad.adnan\AppData\Roaming\npm-cache\_locks\staging-494e2717ce98eb44.lock for C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging
157 silly doParallel extract 10
158 silly extract bindings@1.2.1
159 silly extract ms@2.0.0
160 silly extract debug@2.6.9
161 silly extract nan@2.14.0
162 silly extract ref@1.3.5
163 silly extract ref-struct@1.1.0
164 silly extract safer-buffer@2.1.2
165 silly extract ffi@2.3.0
166 silly extract iconv-lite@0.5.1
167 silly extract autoit@1.1.11
168 silly tarball trying bindings@~1.2.0 by hash: sha1-FK1hE4EtLTfXLme0ystLtyZQXxE=
169 silly tarball trying ms@2.0.0 by hash: sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g=
170 silly tarball trying debug@2 by hash: sha512-bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==
171 silly tarball trying nan@2 by hash: sha512-INOFj37C7k3AfaNTtX8RhsTw7qRy7eLET14cROi9+5HAVbbHuIWUHEauBv5qT4Av2tWasiTY1Jw6puUNqRJXQg==
172 silly tarball trying ref@>=1.2.0 by hash: sha512-2cBCniTtxcGUjDpvFfVpw323a83/0RLSGJJY5l5lcomZWhYpU2cuLdsvYqMixvsdLJ9+sTdzEkju8J8ZHDM2nA==
173 silly tarball trying ref-struct@>=1.0.2 by hash: sha1-XV7mWtQc78Olxf60BYcmHkee3BM=
174 silly tarball trying safer-buffer@>= 2.1.2 < 3 by hash: sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==
175 silly tarball trying ffi@>=2.0.0 by hash: sha512-vkPA9Hf9CVuQ5HeMZykYvrZF2QNJ/iKGLkyDkisBnoOOFeFXZQhUPxBARPBIZMJVulvBI2R+jgofW03gyPpJcQ==
176 silly tarball trying iconv-lite@>=0.4.11 by hash: sha512-ONHr16SQvKZNSqjQT9gy5z24Jw+uqfO02/ngBSBoqChZ+W8qXX7GPRa1RoUnzGADw8K63R1BXUMzarCVQBpY8Q==
177 silly tarball trying autoit@latest by hash: sha512-Gm/NUx5mTFKqZiSATw+MxA970lfBN99LAYVqF8X5JuUPSvCmSMUDZe96KZfRZHyiHT6ZUkf9pFt+zQLbAHcO9A==
178 silly extract ms@2.0.0 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\ms-cb713212 (135ms)
179 silly extract bindings@~1.2.0 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\bindings-c9ebd571 (140ms)
180 silly extract safer-buffer@>= 2.1.2 < 3 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\safer-buffer-062e2149 (145ms)
181 silly extract ref-struct@>=1.0.2 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\ref-struct-c60c5708 (149ms)
182 silly extract debug@2 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\debug-a398f9a8 (164ms)
183 silly extract autoit@latest extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\autoit-aa06e79f (216ms)
184 silly extract iconv-lite@>=0.4.11 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\iconv-lite-5b8c9c7e (220ms)
185 silly extract nan@2 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\nan-a80eb1f7 (236ms)
186 silly extract ref@>=1.2.0 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\ref-b4277bb3 (237ms)
187 silly extract ffi@>=2.0.0 extracted to C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging\ffi-92127770 (595ms)
188 timing action:extract Completed in 602ms
189 silly doReverseSerial unbuild 80
190 silly doSerial remove 80
191 silly doSerial move 80
192 silly doSerial finalize 80
193 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\bindings
194 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ms
195 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\debug
196 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\nan
197 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ref
198 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ref-struct
199 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\safer-buffer
200 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ffi
201 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\iconv-lite
202 silly finalize C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\autoit
203 timing action:finalize Completed in 38ms
204 silly doParallel refresh-package-json 10
205 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\bindings
206 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ms
207 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\debug
208 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\nan
209 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ref
210 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ref-struct
211 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\safer-buffer
212 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ffi
213 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\iconv-lite
214 silly refresh-package-json C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\autoit
215 timing action:refresh-package-json Completed in 53ms
216 silly doParallel preinstall 10
217 silly preinstall bindings@1.2.1
218 info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
219 silly preinstall ms@2.0.0
220 info lifecycle ms@2.0.0~preinstall: ms@2.0.0
221 silly preinstall debug@2.6.9
222 info lifecycle debug@2.6.9~preinstall: debug@2.6.9
223 silly preinstall nan@2.14.0
224 info lifecycle nan@2.14.0~preinstall: nan@2.14.0
225 silly preinstall ref@1.3.5
226 info lifecycle ref@1.3.5~preinstall: ref@1.3.5
227 silly preinstall ref-struct@1.1.0
228 info lifecycle ref-struct@1.1.0~preinstall: ref-struct@1.1.0
229 silly preinstall safer-buffer@2.1.2
230 info lifecycle safer-buffer@2.1.2~preinstall: safer-buffer@2.1.2
231 silly preinstall ffi@2.3.0
232 info lifecycle ffi@2.3.0~preinstall: ffi@2.3.0
233 silly preinstall iconv-lite@0.5.1
234 info lifecycle iconv-lite@0.5.1~preinstall: iconv-lite@0.5.1
235 silly preinstall autoit@1.1.11
236 info lifecycle autoit@1.1.11~preinstall: autoit@1.1.11
237 timing action:preinstall Completed in 3ms
238 silly doSerial build 80
239 silly build bindings@1.2.1
240 info linkStuff bindings@1.2.1
241 silly linkStuff bindings@1.2.1 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
242 silly build ms@2.0.0
243 info linkStuff ms@2.0.0
244 silly linkStuff ms@2.0.0 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
245 silly build debug@2.6.9
246 info linkStuff debug@2.6.9
247 silly linkStuff debug@2.6.9 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
248 silly build nan@2.14.0
249 info linkStuff nan@2.14.0
250 silly linkStuff nan@2.14.0 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
251 silly build ref@1.3.5
252 info linkStuff ref@1.3.5
253 silly linkStuff ref@1.3.5 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
254 silly build ref-struct@1.1.0
255 info linkStuff ref-struct@1.1.0
256 silly linkStuff ref-struct@1.1.0 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
257 silly build safer-buffer@2.1.2
258 info linkStuff safer-buffer@2.1.2
259 silly linkStuff safer-buffer@2.1.2 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
260 silly build ffi@2.3.0
261 info linkStuff ffi@2.3.0
262 silly linkStuff ffi@2.3.0 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
263 silly build iconv-lite@0.5.1
264 info linkStuff iconv-lite@0.5.1
265 silly linkStuff iconv-lite@0.5.1 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
266 silly build autoit@1.1.11
267 info linkStuff autoit@1.1.11
268 silly linkStuff autoit@1.1.11 has C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules as its parent node_modules
269 timing action:build Completed in 4ms
270 silly doSerial global-link 80
271 silly doParallel update-linked 0
272 silly doSerial install 80
273 silly install bindings@1.2.1
274 info lifecycle bindings@1.2.1~install: bindings@1.2.1
275 silly install ms@2.0.0
276 info lifecycle ms@2.0.0~install: ms@2.0.0
277 silly install debug@2.6.9
278 info lifecycle debug@2.6.9~install: debug@2.6.9
279 silly install nan@2.14.0
280 info lifecycle nan@2.14.0~install: nan@2.14.0
281 silly install ref@1.3.5
282 info lifecycle ref@1.3.5~install: ref@1.3.5
283 verbose lifecycle ref@1.3.5~install: unsafe-perm in lifecycle true
284 verbose lifecycle ref@1.3.5~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ref\node_modules\.bin;C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin;C:\Users\muhammad.adnan\AppData\Local\Programs\Python\Python38-32\Scripts;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\muhammad.adnan\.windows-build-tools\python27\;C:\Users\muhammad.adnan\AppData\Local\Microsoft\WindowsApps;C:\Users\muhammad.adnan\AppData\Local\Programs\Microsoft VS Code\bin;C:\Python27amd64;C:\Users\muhammad.adnan\AppData\Roaming\npm
285 verbose lifecycle ref@1.3.5~install: CWD: C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\ref
286 silly lifecycle ref@1.3.5~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
287 timing audit submit Completed in 1393ms
288 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1392ms
289 timing audit body Completed in 0ms
290 silly lifecycle ref@1.3.5~install: Returned: code: 1  signal: null
291 info lifecycle ref@1.3.5~install: Failed to exec install script
292 timing action:install Completed in 4869ms
293 verbose unlock done using C:\Users\muhammad.adnan\AppData\Roaming\npm-cache\_locks\staging-494e2717ce98eb44.lock for C:\Users\muhammad.adnan\Desktop\autoitSetup\node_modules\.staging
294 timing stage:rollbackFailedOptional Completed in 218ms
295 timing stage:runTopLevelLifecycles Completed in 30200ms
296 silly saveTree autoitSetup@1.0.0
296 silly saveTree `-- autoit@1.1.11
296 silly saveTree   +-- ffi@2.3.0
296 silly saveTree   | +-- bindings@1.2.1
296 silly saveTree   | +-- debug@2.6.9
296 silly saveTree   | | `-- ms@2.0.0
296 silly saveTree   | +-- nan@2.14.0
296 silly saveTree   | +-- ref-struct@1.1.0
296 silly saveTree   | | `-- ref@1.3.5
296 silly saveTree   | `-- ref@1.3.5
296 silly saveTree   +-- iconv-lite@0.5.1
296 silly saveTree   | `-- safer-buffer@2.1.2
296 silly saveTree   +-- ref-struct@1.1.0
296 silly saveTree   `-- ref@1.3.5
297 warn autoitSetup@1.0.0 No description
298 warn autoitSetup@1.0.0 No repository field.
299 verbose stack Error: ref@1.3.5 install: `node-gyp rebuild`
299 verbose stack Exit status 1
299 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
299 verbose stack     at EventEmitter.emit (events.js:311:20)
299 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
299 verbose stack     at ChildProcess.emit (events.js:311:20)
299 verbose stack     at maybeClose (internal/child_process.js:1021:16)
299 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
300 verbose pkgid ref@1.3.5
301 verbose cwd C:\Users\muhammad.adnan\Desktop\autoitSetup
302 verbose Windows_NT 10.0.17763
303 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "autoit"
304 verbose node v12.16.1
305 verbose npm  v6.13.4
306 error code ELIFECYCLE
307 error errno 1
308 error ref@1.3.5 install: `node-gyp rebuild`
308 error Exit status 1
309 error Failed at the ref@1.3.5 install script.
309 error This is probably not a problem with npm. There is likely additional logging output above.
310 verbose exit [ 1, true ]

**Comment by DataScientist1** [comment]
sorry its ref related error which i think is not compatible with node12
