### ISSUE TITLE
Yarn install can not find unistd.h

### ISSUE THREAD

**Issue by PawanBadeNiceInContact** [nodejs/node-gyp#2098]
**yarn install** command fails 

log:-
```
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
  unix_dgram.cc
  win_delay_load_hook.cc
c:\\test\\channel-integration-chat-socket-gateway\\node_modules\\unix-dgram\\src\\unix_dgram.cc(9): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\\Test\\channel-integration-chat-socket-gateway\\node_modules\\unix-dgram\\build\\unix_dgram.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Users\\pbade\\AppData\\Roaming\\nvm\\v13.12.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Test\\channel-integration-chat-socket-gateway\\node_modules\\unix-dgram
Done in 71.60s.
```

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/issues/2030#issuecomment-578641079

**Comment by bzoz** [comment]
The `unistd.h` is not a Windows thingy, no wonder it fails to build. You should report this issue to the author of the module you are trying to build, as this is probably not an issue with node-gyp.

In the future fill up the issue template. We can't really help if we don't know what you are trying to build nor on what platform/config you are trying to do this.

**Comment by bzoz** [comment]
I don't think there is anything actionable for us here, closing. Feel free to reopen or open a new issue if you find any problems with node-gyp.
