### ISSUE TITLE
TypeError: 'cmp' is an invalid keyword argument for sort()

### ISSUE THREAD

**Issue by xxoo** [nodejs/node-gyp#2101]
* **Node Version**: 13.13.0
* **Platform**: macos 10.15
* **Compiler**: XCode 11.4.1

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
% node-gyp configure -- -f xcode 
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.13.0 | darwin | x64
gyp info find Python using Python version 3.7.3 found at "/Volumes/data/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v13.13.0/node-v13.13.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.13.0/node-v13.13.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.13.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.13.0/SHASUMS256.txt
gyp info spawn /Volumes/data/Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Volumes/data/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'xcode',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/data/Projects/mem/mem/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/data/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xx/Library/Caches/node-gyp/13.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/xx/Library/Caches/node-gyp/13.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/data/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/xx/Library/Caches/node-gyp/13.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/data/Projects/mem/mem',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 1294, in GenerateOutput
    xcode_projects[build_file].Finalize1(xcode_targets, serialize_all_tests)
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 323, in Finalize1
    self.project.SortGroups()
  File "/Volumes/data/lib/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 2639, in SortGroups
    cmp=lambda x,y: x.CompareRootGroup(y))
TypeError: 'cmp' is an invalid keyword argument for sort()
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Volumes/data/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Volumes/data/bin/node" "/Volumes/data/bin/node-gyp" "configure" "--" "-f" "xcode"
gyp ERR! cwd /Volumes/data/Projects/mem/mem
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```

</details>

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L2639
The code on master is not in the same locations but [this __cmp__ argument problem](https://portingguide.readthedocs.io/en/latest/comparisons.html#the-cmp-function) can be found on lines:
* https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L1400
* https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L2706
* https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L2797
* https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L2923
* https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L2955
* https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/xcodeproj_file.py#L2982

Note the [this __cmp__ function problem](https://portingguide.readthedocs.io/en/latest/comparisons.html#the-cmp-function) is resolved around line 150 but the this __cmp__ argument problem is a Python 3 showstopper and needs to be fixed.

This code must be executed on very rare occasions or we would have had other reports earlier.

**Comment by imnemo** [comment]
To avoid this problem, you can backup and delete your python 3, then node-gyp will find python 2 to do the rest things.

**Comment by cclauss** [comment]
Python 2 died on 1/1/2020.

**Comment by johnsusek** [comment]
I'm getting this when I run "node-gyp configure -- -f xcode"

**Comment by johnsusek** [comment]
Workaround:

`PYTHON=/usr/local/bin/python2.7 node-gyp configure -- -f xcode`

**Comment by rehatkathuria** [comment]
> Workaround:
> 
> `PYTHON=/usr/local/bin/python2.7 node-gyp configure -- -f xcode`

This doesn't seem to be working for me. It looks like gyp doesn't respect the selection of PYTHON? I get the following:

```
PYTHON=/usr/local/bin/python2.7 node-gyp configure -- -f xcode
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.16.0 | darwin | x64
gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
...
```

**Comment by cclauss** [comment]
Python 2 died 15 months ago so node-gyp dropped all support for it.
