### ISSUE TITLE
can't install mdns

### ISSUE THREAD

**Issue by alexandrus21a** [nodejs/node-gyp#2103]
* **Node Version**: v13.12.0
* **Platform**: Windows 10 pro 1903
* **Compiler**: unknown
* **Module**: node-gyp rebuild

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
mdns@2.5.1 install D:\programs\dev\node_modules\mdns
> node-gyp rebuild


D:\programs\dev\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "-m".
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
  dns_service_process_result.cpp
  dns_service_ref.cpp
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
  dns_service_register.cpp
  dns_service_resolve.cpp
  dns_service_update_record.cpp
  mdns_utils.cpp
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_update_record.cpp) [D:\programs\dev\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\mdns_utils.cpp) [D:\programs\dev\node_modules\mdns\build
\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_browse.cpp) [D:\programs\dev\node_modules\md
ns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref_deallocate.cpp) [D:\programs\dev\node_mo
dules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_resolve.cpp) [D:\programs\dev\node_modules\m
dns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_process_result.cpp) [D:\programs\dev\node_mo
dules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref_sock_fd.cpp) [D:\programs\dev\node_modul
es\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_enumerate_domains.cpp) [D:\programs\dev\node
_modules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_sd.cpp) [D:\programs\dev\node_modules\mdns\build\dns
_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_register.cpp) [D:\programs\dev\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_get_addr_info.cpp) [D:\programs\dev\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref.cpp) [D:\programs\dev\node_modules\mdns\
build\dns_sd_bindings.vcxproj]
  network_interface.cpp
  socket_watcher.cpp
  txt_record_ref.cpp
  txt_record_create.cpp
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
  txt_record_get_length.cpp
  txt_record_buffer_to_object.cpp
  win_delay_load_hook.cc
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_ref.cpp) [D:\programs\dev\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\network_interface.cpp) [D:\programs\dev\node_modules\mdn
s\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_create.cpp) [D:\programs\dev\node_modules\mdn
s\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\socket_watcher.cpp) [D:\programs\dev\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_get_length.cpp) [D:\programs\dev\node_modules
\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_buffer_to_object.cpp) [D:\programs\dev\node_m
odules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_set_value.cpp) [D:\programs\dev\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_deallocate.cpp) [D:\programs\dev\node_modules
\mdns\build\dns_sd_bindings.vcxproj]
[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mbuild error[0m
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.emit (events.js:315:20)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Windows_NT 10.0.18362
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m D:\programs\dev\node_modules\mdns
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v13.12.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode-gyp -v[0m v5.1.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnot ok[0m
[0mnpm WARN enoent ENOENT: no such file or directory, open 'D:\programs\dev\package.json'
npm WARN dev No description
npm WARN dev No repository field.
npm WARN dev No README data
npm WARN dev No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Александр\AppData\Roaming\npm-cache\_logs\2020-04-22T15_21_00_963Z-debug.log

Александр@DESKTOP-UE4UAUJ MINGW64 /d/programs/dev
$ npm install mdns

> mdns@2.5.1 install D:\programs\dev\node_modules\mdns
> node-gyp rebuild


D:\programs\dev\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "-m".
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
  dns_service_process_result.cpp
  dns_service_ref.cpp
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
  dns_service_register.cpp
  dns_service_resolve.cpp
  dns_service_update_record.cpp
  mdns_utils.cpp
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_register.cpp) [D:\programs\dev\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_resolve.cpp) [D:\programs\dev\node_modules\m
dns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_update_record.cpp) [D:\programs\dev\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref_sock_fd.cpp) [D:\programs\dev\node_modul
es\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_sd.cpp) [D:\programs\dev\node_modules\mdns\build\dns
_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_get_addr_info.cpp) [D:\programs\dev\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_browse.cpp) [D:\programs\dev\node_modules\md
ns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref_deallocate.cpp) [D:\programs\dev\node_mo
dules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_enumerate_domains.cpp) [D:\programs\dev\node
_modules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\mdns_utils.cpp) [D:\programs\dev\node_modules\mdns\build
\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_process_result.cpp) [D:\programs\dev\node_mo
dules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref.cpp) [D:\programs\dev\node_modules\mdns\
build\dns_sd_bindings.vcxproj]
  network_interface.cpp
  socket_watcher.cpp
  txt_record_ref.cpp
  txt_record_create.cpp
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
  txt_record_get_length.cpp
  txt_record_buffer_to_object.cpp
  win_delay_load_hook.cc
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_set_value.cpp) [D:\programs\dev\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_deallocate.cpp) [D:\programs\dev\node_modules
\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_ref.cpp) [D:\programs\dev\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_get_length.cpp) [D:\programs\dev\node_modules
\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\network_interface.cpp) [D:\programs\dev\node_modules\mdn
s\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\socket_watcher.cpp) [D:\programs\dev\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_buffer_to_object.cpp) [D:\programs\dev\node_m
odules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_create.cpp) [D:\programs\dev\node_modules\mdn
s\build\dns_sd_bindings.vcxproj]
[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mbuild error[0m
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.emit (events.js:315:20)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Windows_NT 10.0.18362
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m D:\programs\dev\node_modules\mdns
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v13.12.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode-gyp -v[0m v5.1.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnot ok[0m
[0mnpm WARN enoent ENOENT: no such file or directory, open 'D:\programs\dev\package.json'
npm WARN dev No description
npm WARN dev No repository field.
npm WARN dev No README data
npm WARN dev No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Александр\AppData\Roaming\npm-cache\_logs\2020-04-22T15_22_30_375Z-debug.log

This should look like this:

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node.exe',
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.9.0

Usage: npm <command>
mdns@2.5.1 install D:\programs\dev\node_modules\mdns
> node-gyp rebuild


D:\programs\dev\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "-m".
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
  dns_service_process_result.cpp
  dns_service_ref.cpp
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
  dns_service_register.cpp
  dns_service_resolve.cpp
  dns_service_update_record.cpp
  mdns_utils.cpp
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_update_record.cpp) [D:\programs\dev\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\mdns_utils.cpp) [D:\programs\dev\node_modules\mdns\build
\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_browse.cpp) [D:\programs\dev\node_modules\md
ns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref_deallocate.cpp) [D:\programs\dev\node_mo
dules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_resolve.cpp) [D:\programs\dev\node_modules\m
dns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_process_result.cpp) [D:\programs\dev\node_mo
dules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref_sock_fd.cpp) [D:\programs\dev\node_modul
es\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_enumerate_domains.cpp) [D:\programs\dev\node
_modules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_sd.cpp) [D:\programs\dev\node_modules\mdns\build\dns
_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_register.cpp) [D:\programs\dev\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_get_addr_info.cpp) [D:\programs\dev\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\dns_service_ref.cpp) [D:\programs\dev\node_modules\mdns\
build\dns_sd_bindings.vcxproj]
  network_interface.cpp
  socket_watcher.cpp
  txt_record_ref.cpp
  txt_record_create.cpp
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
  txt_record_get_length.cpp
  txt_record_buffer_to_object.cpp
  win_delay_load_hook.cc
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_ref.cpp) [D:\programs\dev\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\network_interface.cpp) [D:\programs\dev\node_modules\mdn
s\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_create.cpp) [D:\programs\dev\node_modules\mdn
s\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\socket_watcher.cpp) [D:\programs\dev\node_modules\mdns\b
uild\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_get_length.cpp) [D:\programs\dev\node_modules
\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_buffer_to_object.cpp) [D:\programs\dev\node_m
odules\mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_set_value.cpp) [D:\programs\dev\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
D:\programs\dev\node_modules\mdns\src\mdns.hpp(32,10): fatal error C1083: Не удается открыть файл включение: dns_sd.h:
No such file or directory, (компилируется исходный файл ..\src\txt_record_deallocate.cpp) [D:\programs\dev\node_modules
\mdns\build\dns_sd_bindings.vcxproj]
[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mbuild error[0m
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at ChildProcess.emit (events.js:315:20)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mstack[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mSystem[0m Windows_NT 10.0.18362
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcommand[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mcwd[0m D:\programs\dev\node_modules\mdns
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode -v[0m v13.12.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnode-gyp -v[0m v5.1.0
[0m[37;40mgyp[0m [0m[31;40mERR![0m [0m[35mnot ok[0m
[0mnpm WARN enoent ENOENT: no such file or directory, open 'D:\programs\dev\package.json'
npm WARN dev No description
npm WARN dev No repository field.
npm WARN dev No README data
npm WARN dev No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Александр\AppData\Roaming\npm-cache\_logs\2020-04-22T15_21_00_963Z-debug.log


```

</details>

**Comment by bzoz** [comment]
This is definatly a issue with the mdns package. You should report it at https://github.com/agnat/node_mdns, nothing node-gyp can do about this.

**Comment by sparya6146** [comment]
Node mdns package require **avahi dns_sd compat** library and its header files.
On debianesque systems the package name is libavahi-compat-libdnssd-dev, on fedoraesque systems the package is avahi-compat-libdns_sd-devel
apt install libavahi-compat-libdnssd-dev
npm i mdns
Worked for me
