### ISSUE TITLE
Error on npm install command on linux

### ISSUE THREAD

**Issue by Skeec54** [nodejs/node-gyp#2108]
* **Node Version**: Node: v13.5.0 NPM: 6.14.4
* **Platform**: Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
* **Compiler**: https://pastebin.com/JtSRAh0g
* **Module**: trying to run npm install (https://pastebin.com/N7Vzt7F9)

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/dc/Kuzumi/node_modules/ref
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules/ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

</details>

**Comment by bnoordhuis** [comment]
You omitted the actual build error but chances are it's an issue with the module you're trying to build, ref, not node-gyp.

**Comment by Skeec54** [comment]
its working on the computer but not on my raspberry pi and i need it on the pi

**Comment by bnoordhuis** [comment]
Still omitting the build error. :-)
