### ISSUE TITLE
node-gyp sets plattform toolset to vs120_xp

### ISSUE THREAD

**Issue by fstx** [nodejs/node-gyp#2132]
* **Node Version**: v12.16.3
* **Platform**: 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
System Type:               x64-based PC
* **Compiler**:   vs2019, installed the standard way, and vs2017, installed vid node.js dependency install
* **Module**: blpapi
<details><summary>Verbose output (from npm or node-gyp):</summary>

```
c:\fstx\20_git\github.com\bloomberg\blpapi-node>node-gyp configure --msvs_version=2017
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.3 | win32 | x64
gyp info find Python using Python version 3.8.3 found at "C:\Python38\python.exe"
gyp info find VS using VS2017 (15.9.28307.1146) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python38\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\fstxb\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\fstx\\20_git\\github.com\\bloomberg\\blpapi-node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\fstxb\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\fstxb\\AppData\\Local\\node-gyp\\Cache\\12.16.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\fstxb\\AppData\\Local\\node-gyp\\Cache\\12.16.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\fstxb\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\fstxb\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\fstx\\20_git\\github.com\\bloomberg\\blpapi-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\fstx\\20_git\\github.com\\bloomberg\\blpapi-node\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
fstx: 2015
gyp info ok

c:\fstx\20_git\github.com\bloomberg\blpapi-node>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.3 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(
67,5): error MSB8020: The build tools for v120_xp (Platform Toolset = 'v120_xp') cannot be found. To build using the v1
20_xp build tools, please install v120_xp build tools.  Alternatively, you may upgrade to the current Visual Studio too
ls by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [c:\fstx\20_git\g
ithub.com\bloomberg\blpapi-node\build\blpapijs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\fstxb\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fstxb\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd c:\fstx\20_git\github.com\bloomberg\blpapi-node
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```

</details>

---
edit by @bzoz: fixed formatting

**Comment by bzoz** [comment]
Can you test running `npm config set msvs_version 2017`?

If this does not help, please add `--verbose` to both `node-gyp` calls.

**Comment by bzoz** [comment]
No followup, closing.
