### ISSUE TITLE
using --arch=ia32 gives Error: g++: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?

### ISSUE THREAD

**Issue by Roaders** [nodejs/node-gyp#2169]
* **Node Version**: 14.5.0 and 12.x
* **Platform**:  Linux garage-pi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
* **Compiler**: 
using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 
* **Module**: epoll

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npx node-gyp rebuild -C node_modules/epoll/ --arch=ia32 --target=v10.21.0 --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/pi/git/rpi-garage-door/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild',
gyp verb cli   '-C',
gyp verb cli   'node_modules/epoll/',
gyp verb cli   '--arch=ia32',
gyp verb cli   '--target=v10.21.0',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@14.5.0 | linux | arm
gyp info chdir node_modules/epoll/
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.7.3"
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp verb get node dir compiling against --target node version: 10.21.0
gyp verb command install [ '10.21.0' ]
gyp verb install input version string "10.21.0"
gyp verb install installing version: 10.21.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.21.0
gyp verb build dir attempting to create "build" dir: /home/pi/git/rpi-garage-door/node_modules/epoll/build
gyp verb build dir "build" dir needed to be created? /home/pi/git/rpi-garage-door/node_modules/epoll/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/pi/git/rpi-garage-door/node_modules/epoll/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/pi/git/rpi-garage-door/node_modules/epoll/config.gypi
gyp verb common.gypi checking for gypi file: /home/pi/git/rpi-garage-door/node_modules/epoll/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/pi/git/rpi-garage-door/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/git/rpi-garage-door/node_modules/epoll/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/git/rpi-garage-door/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/10.21.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/10.21.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/git/rpi-garage-door/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/10.21.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/git/rpi-garage-door/node_modules/epoll',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir /home/pi/.cache/node-gyp/10.21.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/git/rpi-garage-door/node_modules/epoll/build'
  g++ '-DNODE_GYP_MODULE_NAME=epoll' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/10.21.0/include/node -I/home/pi/.cache/node-gyp/10.21.0/src -I/home/pi/.cache/node-gyp/10.21.0/deps/openssl/config -I/home/pi/.cache/node-gyp/10.21.0/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/10.21.0/deps/uv/include -I/home/pi/.cache/node-gyp/10.21.0/deps/zlib -I/home/pi/.cache/node-gyp/10.21.0/deps/v8/include -I../../nan  -pthread -Wall -Wextra -Wno-unused-parameter -m32 -Wno-deprecated-declarations -Wno-cast-function-type -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF ./Release/.deps/Release/obj.target/epoll/src/epoll.o.d.raw   -c -o Release/obj.target/epoll/src/epoll.o ../src/epoll.cc
g++: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?
make: *** [epoll.target.mk:105: Release/obj.target/epoll/src/epoll.o] Error 1
make: Leaving directory '/home/pi/git/rpi-garage-door/node_modules/epoll/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/git/rpi-garage-door/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.118-v7l+
gyp ERR! command "/usr/bin/node" "/home/pi/git/rpi-garage-door/node_modules/.bin/node-gyp" "rebuild" "-C" "node_modules/epoll/" "--arch=ia32" "--target=v10.21.0" "--verbose"
gyp ERR! cwd /home/pi/git/rpi-garage-door/node_modules/epoll
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```

</details>

**Comment by rvagg** [comment]
what are you trying to do here? cross compile to ia32 from a raspberry pi? are you sure that's what you want?

**Comment by Roaders** [comment]
I am trying to cross compile to 32 bit on Travis CI servers (which are all 64 bit) so that I can run on a raspberry pi. I get the same error on Travis and raspberry pi though.

**Comment by rvagg** [comment]
`ia32` is an alias for `i386` or `x86` or simply "32-bit Intel", which is probably not what you want here. `armv6` or `armv7` is probably what you want, they're 32-bit ARM (as opposed to `arm64` / `aarch64`). I'm not sure it's going to work here for you though, you'll need a proper cross-compiler toolchain in place to do all of this properly for you.

**Comment by Roaders** [comment]
using arm7 made the command work, but as you suspected the generated files still don't work on Raspberry pi. Thanks for the help.
