### ISSUE TITLE
Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by juanamm** [nodejs/node-gyp#2173]
* **Node Version**:  v10.19.0 and **npm** 6.14.4
* **Platform**: Linux ip-xxx-xx-xx-xx 5.4.0-1018-aws #18-Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Linux Version**:  Ubuntu 20.04.1 LTS
* **Compiler**:  gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
* **Module**: [nodejs-phplike](https://github.com/puritys/nodejs-phplike)   

<details><summary>Verbose output (from npm and node-gyp):</summary>

`npm --verbose`
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', '--verbose' ]
npm info using npm@6.14.4
npm info using node@v10.19.0
```

`node-gyp rebuild --verbose`
```
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node', '/usr/bin/node-gyp', 'rebuild', '--verbose' ]
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - executable path is "/usr/bin/python2"
gyp verb find Python - executing "/usr/bin/python2" to get version
gyp verb find Python - version is "2.7.18"
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp verb get node dir no --target version specified, falling back to host node version: 10.19.0
gyp verb build dir attempting to create "build" dir: /var/www/mysite.com/html/build
gyp verb build dir "build" dir needed to be created? /var/www/mysite.com/html/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /var/www/mysite.com/html/build/config.gypi
gyp verb config.gypi checking for gypi file: /var/www/mysite.com/html/config.gypi
gyp verb common.gypi checking for gypi file: /var/www/mysite.com/html/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/mysite.com/html/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/mysite.com/html',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /var/www/mysite.com/html) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1018-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild" "--verbose"
gyp ERR! cwd /var/www/mysite.com/html
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

```
/var/www/osirisradio.ml/html# npm install -g phplike
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/requ                               est/request/issues/3142

> phplike@2.5.11 install /usr/local/lib/node_modules/phplike
> node-gyp rebuild
/var/www/osirisradio.ml/html# npm install -g phplike
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/requ                               est/request/issues/3142

> phplike@2.5.11 install /usr/local/lib/node_modules/phplike
> node-gyp rebuild
</details>

**Usage:** `sudo npm install -g phplike`
pwd: /var/www/mysite.com/html#

<details><summary>Result:</summary>

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/requ                               est/request/issues/3142

> phplike@2.5.11 install /usr/local/lib/node_modules/phplike
> node-gyp rebuild
```
</details>

**Then:** `node-gyp rebuild`

<details><summary>Result:</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/mysite.com/html/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/mysite.com/html',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /var/www/mysite.com/html) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1018-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/mysite.com/html
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```
</details>

I am a novice in all of this, so I ask for your patience and understanding.

I need to install module nodejs-phplike.

From what I saw in the [GitHub](https://github.com/puritys/nodejs-phplike) repository this module requires a Pyhton version higher than 2.7.8.
From the log that I shared earlier, you are using version python2 = "2.7.18".
But I also have python3 = "3.8.2" installed.
I assumed that for this reason it gave the error (I honestly don't know), but anyway I tried this command:
`NODE_GYP_FORCE_PYTHON=python3 node-gyp rebuild`
<details><summary>Result:</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [ '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/mysite.com/html/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/mysite.com/html',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize                               _master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_maste                               r
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is require                               d by the application
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355                               :16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1018-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/mysite.com/html
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```
</details>

If someone can help me by providing me with the commands that I must execute I would be very grateful.
Verbose output of node-gyp is very complete and identifies errors, but I do not have the necessary knowledge to interpret it and know what to do.

If you need any other data or additional information, ask me.

Thank you very much.

**Comment by NullVoxPopuli** [comment]
why was this closed? what was the solution?

**Comment by cclauss** [comment]
gyp ERR! node-gyp -v v6.1.0
