### ISSUE TITLE
 I cannot generate Xcode project

### ISSUE THREAD

**Issue by qixin1106** [nodejs/node-gyp#2182]
This is my first test program, I cannot generate Xcode project files
---
* MacOS 10.15.6
* Xcode 11.6 
* Command_Line_Tools_for_Xcode_11.5.dmg

```
<Test>
----binding.gyp
----test.cc
```
### binding.gyp
```
{
  "targets": [
    {
      "target_name": "test",
      "sources": [ "test.cc" ]
    }
  ]
}
```
### test.cc
```
//Only for testing, so nothing was written.
```
>node-gyp configure
>success
```
qixin@QixindeiMac Test % node-gyp configure            
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@14.7.0 | darwin | x64
gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Documents/Test/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Library/Caches/node-gyp/14.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/qixin/Library/Caches/node-gyp/14.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/qixin/Library/Caches/node-gyp/14.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/qixin/Documents/Test',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
qixin@QixindeiMac Test % 
```

>node-gyp configure -- -f Xcode
>failure
```
qixin@QixindeiMac Test % node-gyp configure -- -f xcode
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@14.7.0 | darwin | x64
gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'xcode',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Documents/Test/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Library/Caches/node-gyp/14.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/qixin/Library/Caches/node-gyp/14.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/qixin/Library/Caches/node-gyp/14.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/qixin/Documents/Test',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 687, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 679, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 664, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 1388, in GenerateOutput
    xcode_projects[build_file].Finalize1(xcode_targets, serialize_all_tests)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 355, in Finalize1
    self.project.SortGroups()
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 2894, in SortGroups
    self._properties["mainGroup"]._properties["children"] = sorted(
TypeError: 'cmp' is an invalid keyword argument for sort()
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:350:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "--" "-f" "xcode"
gyp ERR! cwd /Users/qixin/Documents/Test
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok 
qixin@QixindeiMac Test % 
```

**Comment by cclauss** [comment]
Related to #2101
