### ISSUE TITLE
Error: Cannot find module 'node-addon-api'

### ISSUE THREAD

**Issue by qixin1106** [nodejs/node-gyp#2183]
* I download the test [demo](https://github.com/nodejs/node-addon-examples), I used the node-addon-api project in 1_hello_world, I used "node-gyp configure - -f xcode" and it failed。

* If I use the napi project in 1_hello_world, it is successful

* How can I find module 'node-addon-api'

### napi/binding.gyp(C)
```
{
  "targets": [
    {
      "target_name": "hello",
      "sources": [ "hello.cc" ]
    }
  ]
}
```
```
qixin@QixindeiMac napi % node-gyp configure -- -f xcode                                                 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@14.7.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'xcode',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Downloads/node-addon-examples-master/2_function_arguments/napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Library/Caches/node-gyp/14.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/qixin/Library/Caches/node-gyp/14.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/qixin/Library/Caches/node-gyp/14.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/qixin/Downloads/node-addon-examples-master/2_function_arguments/napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
```

### node-addon-api/binding.gyp(C++)
```
{
  "targets": [
    {
      "target_name": "hello",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ "hello.cc" ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
    }
  ]
}
```
```
qixin@QixindeiMac node-addon-api % node-gyp configure -- -f xcode                                     
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@14.7.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'xcode',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Downloads/node-addon-examples-master/1_hello_world/node-addon-api/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qixin/Library/Caches/node-gyp/14.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/qixin/Library/Caches/node-gyp/14.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/qixin/Library/Caches/node-gyp/14.7.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/qixin/Downloads/node-addon-examples-master/1_hello_world/node-addon-api',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'node-addon-api'
Require stack:
- /Users/qixin/Downloads/node-addon-examples-master/1_hello_world/node-addon-api/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:315:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at evalScript (internal/process/execution.js:98:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/qixin/Downloads/node-addon-examples-master/1_hello_world/node-addon-api/[eval]'
  ]
}
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:350:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "--" "-f" "xcode"
gyp ERR! cwd /Users/qixin/Downloads/node-addon-examples-master/1_hello_world/node-addon-api
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok 

```

**Comment by gengjiawen** [comment]
Have you executed `npm install` or `yarn` ?

**Comment by qixin1106** [comment]
> Have you executed `npm install` or `yarn` ?

Thank you, I used `npm install`, the installation was successful, and the Xcode project can be generated
