### ISSUE TITLE
C:\Windows\Microsoft.NET\Framework64\v3.5\msbuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by kevinsimper** [nodejs/node-gyp#219]
I am trying to install nodetime but i am running into a problem.

node-gyp@0.9.1
node.js v.0.10.0

I am on Windows 8. 
I am running powershell with admin rights. 
The user is local admin. 
I have installed node-gyp global "npm install node-gyp". 
I have installed Visual Studio 2011 C++. 
I have added the MSBuild.exe to my PATH. 
I have tried installing the windows 2008 SDK. 
I have Python version 2.7.3 installed.
I have restarted a lot of times.

I have also search the web, stackoverflow and github. 

I dont know what i can do else.

But i am getting this error:

```
PS C:\Users\ksi\Dropbox\Web\BB> npm install nodetime
npm WARN package.json Buildingbag@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/nodetime
npm http 304 https://registry.npmjs.org/nodetime
npm http GET https://registry.npmjs.org/request/2.12.0
npm http GET https://registry.npmjs.org/timekit
npm http GET https://registry.npmjs.org/v8tools
npm http 304 https://registry.npmjs.org/v8tools
npm http 304 https://registry.npmjs.org/timekit
npm http 304 https://registry.npmjs.org/request/2.12.0
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> timekit@0.1.9 install C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\timekit
> node-gyp rebuild


C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\timekit>node "C:\Program Files\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

> v8tools@0.2.2 install C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\v8tools
> node-gyp rebuild


C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\v8tools>node "C:\Program Files\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\v8tools\build\binding.sln : error MSB3411: Visual C++-ko
mponenten "VCBuild.exe" kunne ikke indlæses. Hvis komponenten er installeret, skal dens placering føjes til systemstien
. Hvis den ikke er installeret, skal du enten 1) installere Microsoft Windows SDK til Windows Server 2008 og .NET Frame
work 3.5 eller 2) installere Microsoft Visual Studio 2008.
C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\timekit\build\binding.sln : error MSB3411: Visual C++-ko
mponenten "VCBuild.exe" kunne ikke indlæses. Hvis komponenten er installeret, skal dens placering føjes til systemstien
. Hvis den ikke er installeret, skal du enten 1) installere Microsoft Windows SDK til Windows Server 2008 og .NET Frame
work 3.5 eller 2) installere Microsoft Visual Studio 2008.
gyp gypERR!  build errorERR!
 build error
gyp ERR! gypstack Error: `C:\Windows\Microsoft.NET\Framework64\v3.5\msbuild.exe` failed with exit code: 1
 ERR! gyp stackERR! Error: `C:\Windows\Microsoft.NET\Framework64\v3.5\msbuild.exe` failed with exit code: 1
 stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:256:23)
gypgyp  ERR!ERR! stack      at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR!stack      at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
56:23)
stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gypgyp  ERR!ERR!  Systemstack Windows_NT 6.2.9200
     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! gypcommand  "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re
build"
ERR!gyp  System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\timekit
gypERR! ERR!  node -v v0.10.0
gyp cwdERR! C:\Users\ksi\Dropbox\Web\BB\node_modules\nodetime\node_modules\v8tools
 node-gyp -v v0.8.5
gyp gyp ERR! node -v v0.10.0
ERR! gyp not ok
ERR! node-gyp -v v0.8.5
gyp ERR! not ok
npm WARN optional dep failed, continuing timekit@0.1.9
npm WARN optional dep failed, continuing v8tools@0.2.2
nodetime@0.8.9 node_modules\nodetime
└── request@2.12.0
```

Thank you for your help!

**Comment by nishachopra1012** [comment]
Any updates?
