### ISSUE TITLE
node-gyp build error

### ISSUE THREAD

**Issue by flowely** [nodejs/node-gyp#2190]
* **Node Version**: 12.18.3
* **Platform**: Microsoft Windows 7 Ultimate x64-based PC
* **Module**:  yarn && yarn watch
* **yarn**: v1.22.4
* **node**: 12.18.3
* **node-gyp**:  v7.0.0

I want to run the code (at **https://github.com/tensorflow/tfjs-examples/tree/master/mnist**) with the **yarn && yarn** watch command and I get this error:

```
error C:\Users\nazar\Desktop\tfjs-examples\mnist\node_modules\deasync: Command failed.
Exit code: 7
Command: node ./build.js
Arguments:
Directory: C:\Users\nazar\Desktop\tfjs-examples\mnist\node_modules\deasync
Output:
C:\Users\nazar\Desktop\tfjs-examples\mnist\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js" rebuild
)
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.3 | win32 | x64
gyp info find Python using Python version 3.8.5 found at "C:\Users\nazar\AppData\Local\Programs\Python\Python38-32\python.exe"
gyp info find VS using VS2019 (16.5.30002.166) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\nazar\AppData\Local\Programs\Python\Python38-32\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\nazar\\AppData\\Roaming\\nvm\\v12.18.3\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nazar\\Desktop\\tfjs-examples\\mnist\\node_modules\\deasync\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nazar\\AppData\\Roaming\\nvm\\v12.18.3\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nazar\\AppData\\Local\\node-gyp\\Cache\\12.18.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nazar\\AppData\\Local\\node-gyp\\Cache\\12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nazar\\AppData\\Roaming\\nvm\\v12.18.3\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\nazar\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.18.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\nazar\\Desktop\\tfjs-examples\\mnist\\node_modules\\deasync',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\nazar\\Desktop\\tfjs-examples\\mnist\\node_modules\\deasync\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nazar\Desktop\tfjs-examples\mnist\node_modules\deasync
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v7.0.0
gyp ERR! Node-gyp failed to build your package.
```

**Comment by bzoz** [comment]
What VS version do you have installed with what workloads?

**Comment by SetWeather** [comment]
> What VS version do you have installed with what workloads?

Visual Studio code 2019

**Comment by bzoz** [comment]
Uhm, VSCode is not a compiler, only an editor. From the log you provided it looks like there is something off with the configuration of your machine, besides using a system version that is no longer supported.

Go to "Add or remove programs" and look for Visual Studio (without Code) or Build Tools. Uninstall them all. Install VS Build Tools 2019 from [https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16](here), using "Visual C++ build tools" workload. Then `npm config set msvs_version 2019` and try building the module again.

If it fails, paste here the entire verbose log - similar to what you already have done, but paste the whole log, including the command you used.
