### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by ishanuda** [nodejs/node-gyp#2191]
Hi,
I have an application on the Windows desktop env. configured running node-gyp without errors
My desktop env is:

**windows 10 (os build 18363.959) - 64bit**
**using Node Package Manager (nvm) v1.1.7**
**node v10.16.3**
**node-gyp v5.0.7**
**python v3.8.0**
**also in npmrc file refered to the following:**
**python=D:\Program Files\Python\Python27\python.exe**

**MSVS 2015 - Professional Ed**
**MSVS 2019 - Community Ed**

**windows-build-tools@5.2.2**

But when I try to install the dependency for the same application on my laptop by running **npm i** it fails with the node-gyp rebuild error:

My laptop env is:

**windows 10 (os build 19041.388) - 64bit**
**using Node Package Manager (nvm) v1.1.7**
**node v10.16.3**
**node-gyp v7.0.0**
**python v2.7.3**

**MSVS 2015 - Community Ed**
**MSVS 2019 - Community Ed**

**windows-build-tools@5.2.2**

**NOTE: I tried to configure with the same configurations as my desktop, also followed many references.**
**but the situation is the same. Could not get to fix the problem.**

**I also tried installing only build tools, also only installing MSVS 2015 but the result is the same.**

Error is as follows:

![node-gyp-error](https://user-images.githubusercontent.com/8893919/89739671-4bd38f80-daa0-11ea-8cb8-065c5a393642.jpg)

Any recommendations would be appreciated.

Thank you very much.

**Comment by cclauss** [comment]
Python v2.7.3 -> v2.7.18 or v3.8.5 sounds like a good place to start.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/pull/1762 Landed in Node-gyp v5.

**Comment by username1565** [comment]
Try to `rebuild` the `node-gyp`, on Windows 8.1 x64, with NodeJS `v12.3.1`, but get the same failure:
This wants `Visual Studio 2017`, but this can not be installed: https://github.com/justmoon/node-bignum/issues/121#issuecomment-671322395
Nees some workaround, because everything else works.

**Comment by cclauss** [comment]
Did you upgrade npm?  What does log say after that?

**Comment by username1565** [comment]
@cclauss, there the same log, like here: https://github.com/justmoon/node-bignum/issues/121#issuecomment-671818205
after `npm upgrade` try to run the command `node-gyp rebuild`.

**Comment by ishanuda** [comment]
Hi, also I tried installing the following configurations and gives the same error.

windows 10 (os build 18363.959) - 64bit
using Node Package Manager (nvm) v1.1.7
node v10.16.3
**node-gyp v7.1.0**
**python v3.8.0**
also in npmrc file refered to the following:
python=D:\Program Files\Python\Python27\python.exe

MSVS 2015 - Professional Ed
MSVS 2019 - Community Ed

windows-build-tools@5.2.2

regards.

**Comment by ctolkien** [comment]
I believe I'm hitting the same issue.

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\chad\source\PS.PW\Umbraco.Base.Implementation\node_modules\ttf2woff2
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

Looking at the build error logs:

>error C2661: 'v8::Value::ToObject': no overloaded function takes 0 arguments

Does this indicate the version of node running is not compatible with this version of node-gyp? I could not find a compatibility table.

**Comment by cclauss** [comment]
It is unclear what command you typed and the full error log is missing.  The label on this issue should be a clue that `gyp ERR! node-gyp -v v5.0.5` is a problem.  The current node-gyp is v7.1.

**Comment by SailingSteve** [comment]
@cclauss "Please try npm install -g npm or the equivalent Windows commands." worked for me!

on MacOS 10.15.5

    sudo npm install -g npm

did it
Thanks!

**Comment by water-in-stone** [comment]
try `npm install -g node-gyp`

**Comment by multimontana** [comment]
@SailingSteve hello friend?

**Comment by multimontana** [comment]
> try `npm install -g node-gyp`

?

**Comment by multimontana** [comment]
> It is unclear what command you typed and the full error log is missing. The label on this issue should be a clue that `gyp ERR! node-gyp -v v5.0.5` is a problem. The current node-gyp is v7.1.
> 
> Please try [`npm install -g npm`](https://docs.npmjs.com/try-the-latest-stable-version-of-npm) or the equivalent Windows commands.

?

**Comment by multimontana** [comment]
> It is unclear what command you typed and the full error log is missing. The label on this issue should be a clue that `gyp ERR! node-gyp -v v5.0.5` is a problem. The current node-gyp is v7.1.
> 
> Please try [`npm install -g npm`](https://docs.npmjs.com/try-the-latest-stable-version-of-npm) or the equivalent Windows commands.

Test

**Comment by multimontana** [comment]
> try `npm install -g node-gyp`

qewewewe

**Comment by multimontana** [comment]
@cclauss Test

**Comment by multimontana** [comment]
`Class test {
    public static void() {}
}`

**Comment by ShahriarKh** [comment]
`npm upgrade` worked for me.

**Comment by Dot-roasting** [comment]
This occurs after i installed NodeV16 with Latest Npm Version
```js
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Python39\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1622) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:15588) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Priyansh Das\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Priyansh Das\\Desktop\\E BOT rewrite\\node_modules\\@discordjs\\opus\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Priyansh Das\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Priyansh Das\\AppData\\Local\\node-gyp\\Cache\\16.6.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Priyansh Das\\AppData\\Local\\node-gyp\\Cache\\16.6.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Priyansh Das\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Priyansh Das\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.6.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Priyansh Das\\Desktop\\E BOT rewrite\\node_modules\\@discordjs\\opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Priyansh Das\\Desktop\\E BOT rewrite\\node_modules\\@discordjs\\opus\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | win32 | ia32
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Priyansh Das\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Priyansh Das\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Priyansh Das\\Desktop\\E BOT rewrite\\node_modules\\@discordjs\\opus\\prebuild\\node-v93-napi-v3-win32-ia32-unknown-unknown\\opus.node" "--module_name=opus" "--module_path=C:\\Users\\Priyansh Das\\Desktop\\E BOT rewrite\\node_modules\\@discordjs\\opus\\prebuild\\node-v93-napi-v3-win32-ia32-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd C:\Users\Priyansh Das\Desktop\E BOT rewrite\node_modules\@discordjs\opus
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\Priyansh Das\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Priyansh Das\Desktop\E BOT rewrite\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\Priyansh Das\Desktop\E BOT rewrite\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Priyansh Das\Desktop\E BOT rewrite\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19042
npm ERR! node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Priyansh Das\\Desktop\\E BOT rewrite\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\Priyansh Das\Desktop\E BOT rewrite\node_modules\@discordjs\opus
npm ERR! node-pre-gyp ERR! node -v v16.6.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.0
npm ERR! node-pre-gyp ERR! not ok
```

**Comment by epomatti** [comment]
I was running a an old app on Node 18 and was getting this issue.

Figured I needed Node 14, so the following did it for me:

```sh
nvm install 14
nvm use 14
```
