### ISSUE TITLE
discord bot installing error in discord.js

### ISSUE THREAD

**Issue by lordligma12** [nodejs/node-gyp#2197]
Hey there, i'm daniel. Im trying to code a discord bot that can allow people to play chess. I've finished writing the source code and am pretty sure there are no syntax errors in it (i've checked through online js checkers). Following discord bot tutorials, i went into terminal, cd into the file, and then did the command `npm install node app.js`. I got the following massive message below. As a result when i did `node app.js` to get my bot online and working with the proper actions it failed. any tips? thanks, and have a great day. 
Message:

`npm WARN deprecated express@2.5.9: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> node@14.8.0 preinstall /Users/daniel/Desktop/discord bot/node_modules/node
> node installArchSpecificPackage

+ node-darwin-x64@14.8.0
added 1 package in 4.508s
found 0 vulnerabilities

> contextify@0.1.15 install /Users/daniel/Desktop/discord bot/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:52:53: error: too few arguments to function call, single
      argument 'context' was not specified
        target->Set(className, ljsTmpl->GetFunction());
                               ~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:6475:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:62:74: error: too few arguments to function call, single
      argument 'context' was not specified
        ContextifyContext* ctx = new ContextifyContext(info[0]->ToObject());
                                                       ~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2822:3: note: 
      'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:77:48: error: too few arguments to function call, single
      argument 'context' was not specified
        Local<String> code = info[0]->ToString();
                             ~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2810:3: note: 
      'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:83:51: error: too few arguments to function call, single
      argument 'context' was not specified
            ScriptOrigin origin(info[1]->ToString());
                                ~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2810:3: note: 
      'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:126:45: error: too few arguments to function call, single
      argument 'context' was not specified
        constructor.Reset(tmpl->GetFunction());
                          ~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:6475:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:131:56: error: no matching member function for call to
      'NewInstance'
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:4454:44: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:4451:44: note: 
      candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/contextify.cc:140:16: error: no member named 'SetHiddenPrototype' in
      'v8::FunctionTemplate'
        ftmpl->SetHiddenPrototype(true);
        ~~~~~  ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in
      'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:176:52: error: too few arguments to function call, single
      argument 'context' was not specified
        Local<Object> data = info.Data()->ToObject();
                             ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2822:3: note: 
      'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:182:80: error: too few arguments to function call, expected
      2, have 1
  ...rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3988:3: note: 
      'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:192:52: error: too few arguments to function call, single
      argument 'context' was not specified
        Local<Object> data = info.Data()->ToObject();
                             ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2822:3: note: 
      'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:198:33: error: no matching member function for call to
      'Set'
        Nan::New(ctx->sandbox)->Set(property, value);
        ~~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note: 
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note: 
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/contextify.cc:203:52: error: too few arguments to function call, single
      argument 'context' was not specified
        Local<Object> data = info.Data()->ToObject();
                             ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2822:3: note: 
      'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:209:67: error: too few arguments to function call, expected
      2, have 1
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3988:3: note: 
      'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:210:71: error: too few arguments to function call, expected
      2, have 1
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property)....
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3988:3: note: 
      'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:218:52: error: too few arguments to function call, single
      argument 'context' was not specified
        Local<Object> data = info.Data()->ToObject();
                             ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2822:3: note: 
      'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:224:48: error: no matching member function for call to
      'Delete'
        bool success = Nan::New(ctx->sandbox)->Delete(property);
                       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3755:37: note: 
      candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Delete(Local<Context> context,
                                    ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3760:37: note: 
      candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Delete(Local<Context> context,
                                    ^
../src/contextify.cc:229:52: error: too few arguments to function call, single
      argument 'context' was not specified
        Local<Object> data = info.Data()->ToObject();
                             ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:2822:3: note: 
      'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8config.h:431:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:237:59: error: no matching member function for call to
      'GetPropertyNames'
        info.GetReturnValue().Set(Nan::New(ctx->sandbox)->GetPropertyNames());
                                  ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3825:43: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
/Users/daniel/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3827:43: note: 
      candidate function not viable: requires at least 4 arguments, but 0 were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/daniel/Desktop/discord bot/node_modules/node/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/daniel/Desktop/discord bot/node_modules/contextify
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for express@2.5.9: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"14.8.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: express@2.5.9
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN chessbot@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2020-08-21T20_14_21_590Z-debug.log`

**Comment by lordligma12** [comment]
hey there, thanks for the reply. i tried it, and got the following error message:
`Error: Cannot find module './settings.json'
Require stack:
- /Users/daniel/Desktop/discord bot/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/daniel/Desktop/discord bot/app.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/daniel/Desktop/discord bot/app.js' ]
}
`

**Comment by cclauss** [comment]
In the filepath, can you rename `discord bot` to `discord_bot` and retest?

**Comment by lordligma12** [comment]
thanks for the reply:). it still gives me the same error message, any other suggestions?

**Comment by TheSpoiledSnail** [comment]
hi
