### ISSUE TITLE
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/errno.h:31:15: fatal error: 'errno.h' file not found

### ISSUE THREAD

**Issue by AlwaysLoveme** [nodejs/node-gyp#2214]
```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> fsevents@1.2.13 install /Users/zhuxian/Desktop/learnStudy/shunluzhidi-seller/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:55:
In file included from /Users/zhuxian/Library/Caches/node-gyp/12.18.3/include/node/uv.h:52:
In file included from /Users/zhuxian/Library/Caches/node-gyp/12.18.3/include/node/uv/errno.h:25:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/errno.h:31:15: fatal error: 
      'errno.h' file not found
#include_next <errno.h>
              ^~~~~~~~~
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zhuxian/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/zhuxian/.nvm/versions/node/v12.18.3/bin/node" "/Users/zhuxian/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhuxian/Desktop/learnStudy/shunluzhidi-seller/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> fsevents@1.2.13 install /Users/zhuxian/Desktop/learnStudy/shunluzhidi-seller/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:55:
In file included from /Users/zhuxian/Library/Caches/node-gyp/12.18.3/include/node/uv.h:52:
In file included from /Users/zhuxian/Library/Caches/node-gyp/12.18.3/include/node/uv/errno.h:25:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/errno.h:31:15: fatal error: 
      'errno.h' file not found
#include_next <errno.h>
              ^~~~~~~~~
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zhuxian/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/zhuxian/.nvm/versions/node/v12.18.3/bin/node" "/Users/zhuxian/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhuxian/Desktop/learnStudy/shunluzhidi-seller/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

* **Node Version**: V12.18.3
* **Platform**: MacOS 10.15.6
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
node: V12.18.3
npm: V6.14.6
Platform: MacOS 10.15.6
```

</details>

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/search?q=errno.h&type=Issues

**Comment by AlwaysLoveme** [comment]
> gcc --version

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by AlwaysLoveme** [comment]
> https://github.com/nodejs/node-gyp/search?q=errno.h&type=Issues
> 
> What does `gcc --version` on your command line return?

I reinstalled Xcode, but not working

**Comment by cclauss** [comment]
What does gcc --version on your command line return?

**Comment by AlwaysLoveme** [comment]
> ls /usr/include/

sorry, /usr/include/: No such file or directory

**Comment by cclauss** [comment]
`--with-gxx-include-dir=` is a problem if it is pointing to a nonexistant directory!

`ls /Applications/Xcode.app/Contents/Developer/usr/include/` ?

**Comment by AlwaysLoveme** [comment]
> ls /Applications/Xcode.app/Contents/Developer/usr/include/

bad, command line return "ls: /Applications/Xcode.app/Contents/Developer/usr/include/: No such file or directory"

**Comment by AlwaysLoveme** [comment]
> `--with-gxx-include-dir=` is a problem if it is pointing to a nonexistant directory!
> 
> `ls /Applications/Xcode.app/Contents/Developer/usr/include/` ?
> 
> On my Mac, `errno.h` is in `ls $(xcode-select --print-path)/usr/include/c++/v1` but I have not installed all of Xcode.

and what should i do, please! This error has bothered me for a long time

**Comment by cclauss** [comment]
Have you gone through https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md ?

**Comment by AlwaysLoveme** [comment]
> Have you gone through https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md ?

not yet, i will try

**Comment by AlwaysLoveme** [comment]
> Have you gone through https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md ?

i tried, but the error still exit when i run "npm i"

**Comment by AlwaysLoveme** [comment]
> Have you gone through https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md ?

now , i run "gcc --version" in command line, it return
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
command line run "ls /Library/Developer/CommandLineTools/usr/include/", it return
```
FlexLexer.h c++         swift
```

**Comment by AlwaysLoveme** [comment]
> * npm doctor
yes, i installed homebrew,
npm doctor: 
```
npm notice PING https://registry.npmjs.org/
Check                               Value                                            Recommendation
npm ping                            ok
npm -v                              v6.14.6                                          Use npm v6.14.8
node -v                             v12.18.3
npm config get registry             https://registry.npmjs.org/
which git                           /Library/Developer/CommandLineTools/usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2248 tarballs
```
ls /Library/Developer/CommandLineTools/usr/include/c++:
```
v1
```
ls /Library/Developer/CommandLineTools/usr/include/c++/v1 ：
```
__bit_reference          complex                  module.modulemap
__bsd_locale_defaults.h  complex.h                mutex
__bsd_locale_fallbacks.h condition_variable       new
__config                 csetjmp                  numeric
__cxx_version            csignal                  optional
__debug                  cstdarg                  ostream
__errc                   cstdbool                 queue
__functional_03          cstddef                  random
__functional_base        cstdint                  ratio
__functional_base_03     cstdio                   regex
__hash_table             cstdlib                  scoped_allocator
__libcpp_version         cstring                  set
__locale                 ctgmath                  setjmp.h
__mutex_base             ctime                    shared_mutex
__node_handle            ctype.h                  span
__nullptr                cwchar                   sstream
__split_buffer           cwctype                  stack
__sso_allocator          deque                    stdbool.h
__std_stream             errno.h                  stddef.h
__string                 exception                stdexcept
__threading_support      experimental             stdint.h
__tree                   ext                      stdio.h
__tuple                  fenv.h                   stdlib.h
__undef_macros           filesystem               streambuf
algorithm                float.h                  string
any                      forward_list             string.h
array                    fstream                  string_view
atomic                   functional               strstream
bit                      future                   system_error
bitset                   initializer_list         tgmath.h
cassert                  inttypes.h               thread
ccomplex                 iomanip                  tuple
cctype                   ios                      type_traits
cerrno                   iosfwd                   typeindex
cfenv                    iostream                 typeinfo
cfloat                   istream                  unordered_map
charconv                 iterator                 unordered_set
chrono                   limits                   utility
cinttypes                limits.h                 valarray
ciso646                  list                     variant
climits                  locale                   vector
clocale                  locale.h                 version
cmath                    map                      wchar.h
codecvt                  math.h                   wctype.h
compare                  memory
```

**Comment by cclauss** [comment]
That last directory has `errno.h`

**Comment by cclauss** [comment]
npm install -g npm

**Comment by AlwaysLoveme** [comment]
> That last directory has `errno.h`

i resolved, since run 
```
sudo rm -rf /Library/Developer/CommandLineTools

```

**Comment by AlwaysLoveme** [comment]
> npm install -g npm

I checked a lot of information on NET, found a solution which there is  no need to uninstall CommandLineTools.

command line run "which -a gcc", it is returned:
```
/Library/Developer/CommandLineTools/usr/bin/gcc
/usr/bin/gcc

```
so , i edit the .zshrc file, found that there is a path:
```
export PATH=/Library/Developer/CommandLineTools/usr/bin:$PATH

```
and delete this PATH, reinstall CommandLineTools, then, run " npm i " again, it is normal, no errors

**Comment by iTidy** [comment]
node 11.9.0
