### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by raveendrau** [nodejs/node-gyp#2215]
* **Node Version**: Node v12.16.2 & Npm v.6.14.4 
* **Platform**: Darwin HYDDT0011-iMAC.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
* **Compiler**: pple clang version 12.0.0 (clang-1200.0.31.1)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
WARNING in ./node_modules/lzma-native/index.js 13:13-34
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/node-pre-gyp/lib/pre-binding.js 20:22-48
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/node-pre-gyp/lib/util/versioning.js 17:20-67
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'node-gyp' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib/util'

WARNING in ./node_modules/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'npm' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib/util'

WARNING in ./node_modules/node-pre-gyp/lib/util/nw-pre-gyp/index.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

ERROR in ./node_modules/node-pre-gyp/lib/info.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/publish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in '/Users/raveendra.uppala/git/speed-test/node_modules/detect-libc/lib'
ERROR in ./node_modules/node-pre-gyp/lib/testbinary.js
Module not found: Error: Can't resolve 'child_process' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'child_process' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib/util'
ERROR in ./node_modules/osenv/osenv.js
Module not found: Error: Can't resolve 'child_process' in '/Users/raveendra.uppala/git/speed-test/node_modules/osenv'
ERROR in ./node_modules/speedtest-net/index.js
Module not found: Error: Can't resolve 'child_process' in '/Users/raveendra.uppala/git/speed-test/node_modules/speedtest-net'
ERROR in ./node_modules/tree-kill/index.js
Module not found: Error: Can't resolve 'child_process' in '/Users/raveendra.uppala/git/speed-test/node_modules/tree-kill'
ERROR in ./node_modules/chownr/chownr.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/chownr'
ERROR in ./node_modules/config-chain/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/config-chain'
ERROR in ./node_modules/decompress/node_modules/make-dir/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/decompress/node_modules/make-dir'
ERROR in ./node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/detect-libc/lib'
ERROR in ./node_modules/download/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/download'
ERROR in ./node_modules/download/node_modules/make-dir/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/download/node_modules/make-dir'
ERROR in ./node_modules/fd-slicer/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/fd-slicer'
ERROR in ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/fs.realpath'
ERROR in ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/fs.realpath'
ERROR in ./node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/glob'
ERROR in ./node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/glob'
ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/got'
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/graceful-fs'
ERROR in ./node_modules/ignore-walk/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/ignore-walk'
ERROR in ./node_modules/lzma-native/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/lzma-native'
ERROR in ./node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/mkdirp'
ERROR in ./node_modules/needle/lib/needle.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/needle/lib'
ERROR in ./node_modules/needle/lib/multipart.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/needle/lib'
ERROR in ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/pre-binding.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/clean.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/info.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/install.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/package.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/publish.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/rebuild.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/reinstall.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/reveal.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/testbinary.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/testpackage.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib'
ERROR in ./node_modules/node-pre-gyp/lib/util/napi.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib/util'
ERROR in ./node_modules/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib/util'
ERROR in ./node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/lib/util'
ERROR in ./node_modules/node-pre-gyp/node_modules/fs-minipass/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/fs-minipass'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/create.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/list.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/extract.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/pack.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/unpack.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/mkdir.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/write-entry.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/node-pre-gyp/node_modules/tar/lib/replace.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/node-pre-gyp/node_modules/tar/lib'
ERROR in ./node_modules/npm-bundled/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/npm-bundled'
ERROR in ./node_modules/npm-conf/lib/conf.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/npm-conf/lib'
ERROR in ./node_modules/npm-conf/lib/util.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/npm-conf/lib'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/request/lib'
ERROR in ./node_modules/rimraf/rimraf.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/rimraf'
ERROR in ./node_modules/sha256-file/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/sha256-file'
ERROR in ./node_modules/speedtest-net/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/speedtest-net'
ERROR in ./node_modules/speedtest-net/node_modules/mkdirp/lib/opts-arg.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/speedtest-net/node_modules/mkdirp/lib'
ERROR in ./node_modules/speedtest-net/node_modules/mkdirp/lib/use-native.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/speedtest-net/node_modules/mkdirp/lib'
ERROR in ./node_modules/yauzl/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/raveendra.uppala/git/speed-test/node_modules/yauzl'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/raveendra.uppala/git/speed-test/node_modules/forever-agent'
ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/Users/raveendra.uppala/git/speed-test/node_modules/tough-cookie/lib'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/raveendra.uppala/git/speed-test/node_modules/tunnel-agent'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/raveendra.uppala/git/speed-test/node_modules/forever-agent'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/raveendra.uppala/git/speed-test/node_modules/tunnel-agent'
ℹ ｢wdm｣: Failed to compile.
```

</details>

When I tried to installed the packag which used node-gyp as dependency
that broken log is:
```
HYDDT0011-iMAC:~ raveendra.uppala$ sudo npm install --global speedtest-net
Password:
/usr/local/bin/speedtest-net -> /usr/local/lib/node_modules/speedtest-net/bin/index.js

> lzma-native@4.0.6 install /usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for lzma-native@4.0.6 and node@12.16.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64' 
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/raveendra.uppala/Library/Caches/node-gyp/12.16.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/.node-gyp'
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/speedtest-net/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/speedtest-net/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native
node-pre-gyp ERR! node -v v12.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64/lzma_native.node --module_name=lzma_native --module_path=/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/binding-v4.0.6-node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.6 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raveendra.uppala/.npm/_logs/2020-09-04T07_57_03_894Z-debug.log
HYDDT0011-iMAC:~ raveendra.uppala$ 
```

Any ideas what is wrong?

**Comment by cclauss** [comment]
> EACCES current user ("nobody") does not have permission to access the dev dir

Are you logged in as `raveendra.uppala` when you run this command?  What command was run at the top of your output?

Try to successfully install `lzma-native` before installing `speedtest-net`.

On the commandline try:
`mkdir '/usr/local/lib/node_modules/speedtest-net/node_modules/lzma-native/.node-gyp'

And then try to rerun.

**Comment by rvagg** [comment]
Well, you could try `--unsafe-perm=true`, but as the name suggests it's not ideal.

Since this is probably just your dev machine, you could just `sudo chown raveendra.uppala:staff -R /usr/local/*` so that you don't need to `sudo` any of these things at all and don't have to worry about permissions problems when dealing with `/usr/local`. This may not be ideal depending on what you do with your machine and whether others have accounts on it, but it's what I do and a lot of Node.js developers do and it helps avoid giving `root` to arbitrary code that comes out of npm (who knows what the various install scripts are doing). But it doesn't solve all your security problems, since now it doesn't even take privileged access to put things into /usr/local, including /usr/local/bin, but that's a lesser-of-evils thing IMO.

**Comment by cclauss** [comment]
Does getting rid of `--global` help?

Try changing: `sudo npm install --global speedtest-net`
To `npm install speedtest-net`
Or `sudo npm install speedtest-net`
