### ISSUE TITLE
gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by JonathanWoodward** [nodejs/node-gyp#2224]
* **Node Version**: 10.19.0
* **Platform**:  5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 9.3.0
* **Module**: electron-rebuild -f -w sqlite3

<details><summary>
I am rebuilding a project from a few months ago. I am using sqlite a rebuild into electron is required. The only changes from the working version are the latest packages and audit fixes, and now I get the following errors.</summary>

```
$ yarn rebuild
yarn run v1.22.5
$ electron-rebuild -f -w sqlite3
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [ '/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/projects/myApp/trunk/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.electron-gyp/7.1.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.electron-gyp/7.1.11',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.electron-gyp/7.1.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/projects/myApp/trunk/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-47-generic
gyp ERR! command "/usr/bin/node" "/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.11" "--arch=x64" "--dist-u      rl=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/home/user/projects/myApp/trunk/node_modules/sqlite3/lib/binding/napi      -v{napi_build_version}-linux-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-linux-x64.tar.gz"
gyp ERR! cwd /home/user/projects/myApp/trunk/node_modules/sqlite3
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [ '/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/projects/myApp/trunk/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.electron-gyp/7.1.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.electron-gyp/7.1.11',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.electron-gyp/7.1.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/projects/myApp/trunk/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-47-generic
gyp ERR! command "/usr/bin/node" "/home/user/projects/myApp/trunk/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.11" "--arch=x64" "--dist-u      rl=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/home/user/projects/myApp/trunk/node_modules/sqlite3/lib/binding/napi      -v{napi_build_version}-linux-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-linux-x64.tar.gz"
gyp ERR! cwd /home/user/projects/myApp/trunk/node_modules/sqlite3
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/home/user/projects/myApp/trunk/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/user/projects/myApp/trunk/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/user/projects/myApp/trunk/node_modules/rxjs/internal/Subscriber.js:143:22)
```

</details>

**Comment by richardlau** [comment]
https://github.com/nodejs/node/pull/27835 was never backported to Node.js 10.x.

FYI @nodejs/n-api
