### ISSUE TITLE
build error zeromq.js

### ISSUE THREAD

**Issue by androllen** [nodejs/node-gyp#2228]
Platform: Windows 10 Pro
yarn: v1.22.5
npm: v6.14.4
node: v12.16.2
node-gyp: v7.1.0
I want to run the code [https://github.com/zeromq/zeromq.js](https://github.com/zeromq/zeromq.js) 

windows-build-tools is ok
```sh
PS D:\> npm install --global windows-build-tools
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this

> windows-build-tools@5.2.2 postinstall C:\Users\Androllen\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\Androllen\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\Androllen\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Successfully installed Python 2.7

Now configuring the Visual Studio Build Tools and Python...

All done!

+ windows-build-tools@5.2.2
added 144 packages from 99 contributors in 35.005s
```

```sh
D:\Downloads\zeromq.js-master>node-gyp configure --msvs_version=2017
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@12.16.2 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\Androllen\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1259) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Androllen\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Androllen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Downloads\\zeromq.js-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Androllen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Androllen\\AppData\\Local\\node-gyp\\Cache\\12.16.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Androllen\\AppData\\Local\\node-gyp\\Cache\\12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Androllen\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Androllen\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Downloads\\zeromq.js-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Downloads\\zeromq.js-master\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
```

here, I get this error:

```sh
D:\Downloads\zeromq.js-master>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@12.16.2 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  build_libzmq
  'sh' 不是内部或外部命令，也不是可运行的程序
  或批处理文件。
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209
,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [D:\Downloads\zeromq.js-master\build\libzmq.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Androllen\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Androllen\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\Downloads\zeromq.js-master
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok

```

both python 2.7 and 3.7 not ok

thanks~~

**Comment by androllen** [comment]
[https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules)

### Native Modules

Native modules are supported and should work without any configuration, assuming nodeIntegration is enabled. If you get errors, you may need to set the native dependency as an webpack external (opens new window). It should get found automatically, but it might not. To do this, use the externals option:

```sh
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // List native deps here if they don't work
      externals: ['my-native-dep'],
      // If you are using Yarn Workspaces, you may have multiple node_modules folders
      // List them all here so that VCP Electron Builder can find them
      nodeModulesPath: ['../../node_modules', './node_modules']
    }
  }
}
```
