### ISSUE TITLE
can't run node-gyp rebuild

### ISSUE THREAD

**Issue by philipeachille** [nodejs/node-gyp#2232]
node-gyp rebuild results in many errors - do i have a compatibility issue?

* **Node Version**: 14.13.0
* **Platform**: OSX 10.15.5
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```



fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"

gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v7.1.0

gyp ERR! not ok
```

</details>

> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:222:43: error: too few arguments to function call, single argument 'isolate' was not specified
  bool persistent = info[3]->BooleanValue();
                    ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/pav/Library/Caches/node-gyp/14.13.0/include/node/v8.h:2858:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^

../src/binding.cc:253:38: error: too few arguments to function call, single argument 'context' was not specified
  size_t size = info[2]->Uint32Value();
                ~~~~~~~~~~~~~~~~~~~~ ^
/Users/pav/Library/Caches/node-gyp/14.13.0/include/node/v8.h:2866:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^

etc ...

**Comment by philipeachille** [comment]
boiled it down to an incompatibility with the OCR package ( https://www.npmjs.com/package/ocr )
