### ISSUE TITLE
Rebuilds Problem (Win10 Insider Preview)

### ISSUE THREAD

**Issue by mcdmaster** [nodejs/node-gyp#2234]
* **Node Version**: `14.13.0`
* **Platform**:  `Windows 10 Home Insider Preview 10.0.20226 N/A Build 20226`
* **Compiler**:  `16.8.0-preview-20452-03+5dee11854`
* **Module**:  a `Nuxt.js` application w/ `yarn` 

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

Please see:

error C:\Users\Mac\node_modules\fibers: Command failed.
Exit code: 1
Command: node build.js || nodejs build.js
Arguments:
Directory: C:\Users\Mac\node_modules\fibers
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@14.13.0 | win32 | x64
gyp info find Python using Python version 3.8.5 found at "C:\Python38\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2019
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.8.30524.135) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Mac\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Mac\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Mac\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Mac\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Mac\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Mac\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Mac\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
gyp ERR! System Windows_NT 10.0.20226
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mac\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Mac\node_modules\fibers
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'
````

</details>

Windows SDK upgrade cannot be reflected on `node-gyp` building platform and tries to find older SDK version

**Comment by jabbar86** [comment]
Try this Solution :
```
yarn install global node-gyp

export npm_config_node_gyp=/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js(path will be different if you are using windows)

rm -rf node_modules(if already there)

yarn install
```

**Comment by mcdmaster** [comment]
Thanks @jabbar86 , as FYI, on my environment w/ `Node 14`, it was as unsuccessful as previous.
Will try older `Node` version(s) later

**Comment by jabbar86** [comment]
@mcdmaster I was facing the same issue. I downgradge to the older stable version like 10.13.0 its worked like a charm.

**Comment by mcdmaster** [comment]
@jabbar86 Although I much appreciate your information indeed, I would not want to retain the "downgrade" approach. Yes, I knew that we use a magic keyword "fallback" in the case like that. I think that we would rather be in progressive fashion though.

Anyway, for my day-to-day development activities, I intend to use the "fallen back" instance. Along with that, I will look for a persistent resolution so that it can be PR'd here. Thank you anyway

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/nodejs/node-gyp/assets/54507071/d488b0f4-1d26-4d8c-91ff-a515aac8860b)

The installed windows sdk is the windows 11 latest

**Comment by shenjackyuanjie** [comment]
more info: 

![image](https://github.com/nodejs/node-gyp/assets/54507071/40c249f3-f365-41f0-93f3-a2bf04cc7e54)

I switch My windows sdk to the `windows 10 10.0.20348` and it works

**Comment by cclauss** [comment]
> gyp info using node-gyp@8.4.1

Please upgrade... https://github.com/nodejs/node-gyp/releases

**Comment by StefanStojanovic** [comment]
This issue (especially the original one) seems no longer relevant. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
