### ISSUE TITLE
node-gyp configure fails on Windows

### ISSUE THREAD

**Issue by JwanKhalaf** [nodejs/node-gyp#2271]
When I try to run `node-gyp configure --python C:\Python\Python39\python.exe` I get the following:

```
PS C:\code\bejebeje.identity\Bejebeje.Identity> node-gyp configure --python C:\Python\Python39\python.exe
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.1 | win32 | x64
gyp info find Python using Python version 3.9.0 found at "C:\Python\Python39\python.exe"
gyp http GET https://nodejs.org/download/release/v14.15.1/node-v14.15.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.15.1/node-v14.15.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.15.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.15.1/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v14.15.1/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v14.15.1/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.15.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.15.1/win-x64/node.lib
gyp http 404 https://nodejs.org/download/release/v14.15.1/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.15.1/win-x86/node.lib
gyp info find VS using VS2019 (16.8.30717.126) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\jwan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\code\\bejebeje.identity\\Bejebeje.Identity\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jwan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jwan\\AppData\\Local\\node-gyp\\Cache\\14.15.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jwan\\AppData\\Local\\node-gyp\\Cache\\14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jwan\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jwan\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\code\\bejebeje.identity\\Bejebeje.Identity',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\code\\bejebeje.identity\\Bejebeje.Identity\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\code\bejebeje.identity\Bejebeje.Identity) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\jwan\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jwan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--python" "C:\\Python\\Python39\\python.exe"
gyp ERR! cwd C:\code\bejebeje.identity\Bejebeje.Identity
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

I am on Windows 10 Pro (x64 - OS build: 19042.630). Node version is 14.15.1and npm version is 6.14.9 and node-gyp version is 7.1.2

What am I doing wrong?

**Comment by bzoz** [comment]
`gyp: binding.gyp not found (cwd: C:\code\bejebeje.identity\Bejebeje.Identity) while trying to load binding.gyp`

The thing you are trying to build is not properly configured to be built by node-gyp, or maybe you are running node-gyp in the wrong directory.

**Comment by JwanKhalaf** [comment]
hmm interesting. All I really wanted to do was `npm rebuild node-sass` but that was failing and Google searches led me to install the Windows Build Tools.

**Comment by cclauss** [comment]
On [Bejebeje.Identity](https://github.com/JwanKhalaf/Bejebeje.Identity/actions), its tests are failing.

On [Node Saas](https://github.com/sass/node-sass/blob/master/README.md) it is deprecated in favor of Dart Sass.

**Comment by JwanKhalaf** [comment]
Thanks, I didn't know node-sass was deprecated, I'll move to dart sass.
