### ISSUE TITLE
Rebuild error when use --dist-url=https://www.electronjs.org/headers/

### ISSUE THREAD

**Issue by Jan307** [nodejs/node-gyp#2275]
```
$ electron-rebuild -f -w my-module
⠦ Building module: my-module, Completed: 0gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
⠧ Building module: my-module, Completed: 0gyp http GET https://www.electronjs.org/headers/v10.1.5/node-v10.1.5-headers.tar.gz
⠙ Building module: my-module, Completed: 0gyp WARN install got an error, rolling back install
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/code/node_modules/my-module'.
Error: read ECONNRESET



Error: node-gyp failed to rebuild '/Users/code/node_modules/my-module'.
Error: read ECONNRESET


    at ModuleRebuilder.rebuildNodeGypModule (/Users/code/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at async Rebuilder.rebuildModuleAt (/Users/code/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/Users/code/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /Users/code/node_modules/electron-rebuild/lib/src/cli.js:146:9
```

**Comment by cclauss** [comment]
Do the other [122 issues on Electron](https://github.com/nodejs/node-gyp/search?q=electron&type=issues) contain tips that help to clear up this issue?  The output does not resemble other node-gyp error logs.  Python 2 died 11 months ago so perhaps it is not a good idea to rely on that.
