### ISSUE TITLE
Cannot rebuild better_sqlite3 with Electron on Mac

### ISSUE THREAD

**Issue by jepiqueau** [nodejs/node-gyp#2276]
* **Node Version**: 
Node Version v14.15.1
npm Version 6.14.9

* **Platform**: 
MacOS Big Sur 11.0.1
Xcode 12.2
Build version 12B45b

* **Compiler**: 
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

* **Module**: 
npm install

<details><summary>Verbose output (from npm or node-gyp):</summary>
```
queaujeanpierre@MacBook-Pro-de-Queau-Jean-Pierre my-electron-sqlite-app % npm install

> my-electron-sqlite-app@1.0.0 postinstall /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app
> electron-rebuild -f -w better-sqlite3

⠇ Building module: better-sqlite3, Completed: 0  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
⠙ Building module: better-sqlite3, Completed: 0  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
⠸ Building module: better-sqlite3, Completed: 0  LIBTOOL-STATIC Release/sqlite3.a
⠏ Building module: better-sqlite3, Completed: 0  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
⠴ Building module: better-sqlite3, Completed: 0In file included from ../src/better_sqlite3.cpp:4:
In file included from ./src/better_sqlite3.lzz:10:
In file included from /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3/11.0.3/include/node/node.h:67:
In file included from /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3/11.0.3/include/node/v8.h:30:
/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3/11.0.3/include/node/v8-internal.h:418:38: error: 
      no template named 'remove_cv_t' in namespace 'std'; did you mean
      'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 
      'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
⠏ Building module: better-sqlite3, Completed: 01 error generated.
make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/electron-rebuild/lib/src/cli.js:146:9
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! my-electron-sqlite-app@1.0.0 postinstall: `electron-rebuild -f -w better-sqlite3`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the my-electron-sqlite-app@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/queaujeanpierre/.npm/_logs/2020-12-06T18_04_14_425Z-debug.log


```

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node.exe',
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.9.0

Usage: npm <command>
(...)
```

</details>

package.json file

```
{
  "name": "my-electron-sqlite-app",
  "version": "1.0.0",
  "description": "",
  "main": "build/index.js",
  "scripts": {
    "compile": "tsc && copyfiles -f src/index.html src/style.css build",
    "start": "npm run compile && electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "electron-rebuild -f -w better-sqlite3"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/better-sqlite3": "^5.4.1",
    "electron": "^11.0.3",
    "electron-rebuild": "^2.3.4",
    "rimraf": "^3.0.2",
    "typescript": "^4.1.2"
  },
  "dependencies": {
    "better-sqlite3": "^7.1.1",
    "copyfiles": "^2.4.1"
  }
}

```

**Comment by rvagg** [comment]
sorry @jepiqueau but these are questions for better-sqlite3 rather than node-gyp which is just handling the compile process. It looks like compiler / language mismatch problems. Maybe your compiler isn't supported by that project or maybe there's a native dependency that's needed. Head over to https://github.com/JoshuaWise/better-sqlite3 and see if they have any docs or issues on this.

**Comment by jepiqueau** [comment]
@rvagg Thanks for your quick answer, you are right, i made the request too to better-sqlite3.

**Comment by jepiqueau** [comment]
@rvagg i came back, i deleted the node_modules and install again and the build works fine. now when running the electron app i got
```
 queaujeanpierre@MacBook-Pro-de-Queau-Jean-Pierre my-electron-sqlite-app % npm start

> my-electron-sqlite-app@1.0.0 start /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app
> npm run compile && electron .


> my-electron-sqlite-app@1.0.0 compile /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app
> tsc && copyfiles -f src/index.html src/style.css build

(node:1441) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
 from Echo Hello World
(node:1441) UnhandledPromiseRejectionWarning: Error: The module '/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3/lib/database.js:9:24)
(node:1441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1441) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
telling that the `NODE_MODULE_VERSION`  is not correct.
meaning that i have to recompile `better-sqlite3` 
so it is what i did to recompile

```
cd ./node_modules/better-sqlite3
node-gyp rebuild --target=11.0.3 --arch=x64 --dist-url=https://atom.io/download/electron
```
and i got
```
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.1 | darwin | x64
gyp info find Python using Python version 3.6.5 found at "/usr/local/bin/python3"
gyp http GET https://atom.io/download/electron/v11.0.3/node-v11.0.3-headers.tar.gz
gyp http 200 https://atom.io/download/electron/v11.0.3/node-v11.0.3-headers.tar.gz
gyp http GET https://atom.io/download/electron/v11.0.3/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v11.0.3/SHASUMS256.txt
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/queaujeanpierre/Library/Caches/node-gyp/11.0.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/queaujeanpierre/Library/Caches/node-gyp/11.0.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/queaujeanpierre/Library/Caches/node-gyp/11.0.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
In file included from ../src/better_sqlite3.cpp:4:
In file included from ./src/better_sqlite3.lzz:10:
In file included from /Users/queaujeanpierre/Library/Caches/node-gyp/11.0.3/include/node/node.h:67:
In file included from /Users/queaujeanpierre/Library/Caches/node-gyp/11.0.3/include/node/v8.h:30:
/Users/queaujeanpierre/Library/Caches/node-gyp/11.0.3/include/node/v8-internal.h:418:38: error: 
      no template named 'remove_cv_t' in namespace 'std'; did you mean
      'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 
      'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild" "--target=11.0.3" "--arch=x64" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd /Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite-app/node_modules/better-sqlite3
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```
Any ideas on how to proceed from there ?

**Comment by jepiqueau** [comment]
Sorry to have bother you, it is my mistake i build with the wrong target, it should be the node version not the electron version
