### ISSUE TITLE
mac and node-pty - MODULE_NOT_FOUND 

### ISSUE THREAD

**Issue by ShlomiRex** [nodejs/node-gyp#2290]
* **Node Version**:  node: v14.15.3 npm: 6.14.10
* **Platform**:  macOS Big Sur
* **Compiler**:  Apple clang version 12.0.0 (clang-1200.0.32.28)
* **Module**:  node-pty and node-gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/lib/unixTerminal.js
- /Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/lib/index.js
- /Users/shlomidomnenko/Projects/e-xterm/app/app.js
- /Users/shlomidomnenko/Projects/e-xterm/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/lib/unixTerminal.js',
    '/Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/lib/index.js',
    '/Users/shlomidomnenko/Projects/e-xterm/app/app.js',
    '/Users/shlomidomnenko/Projects/e-xterm/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js',
    undefined
  ]
}
```

</details>

I just want to use node-pty in my electron application. In windows it compiles and runs fine. But in mac it thorws this error. I used the same npm packages for windows and mac. Just `npm install` and `npm run start` and in windows its fine and mac it throws error.

I use the following package:
```
"node-pty": "^0.9.0"
```

I tried running `electron-rebuild -f -w node-pty` but it throws another error:
<details>
<summary>Output of electron rebuild</summary>

⠏ Building module: node-pty, Completed: 0  CXX(target) Release/obj.target/pty/src/unix/pty.o
⠇ Building module: node-pty, Completed: 0In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:56:
In file included from /Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/11.1.1/include/node/node.h:67:
In file included from /Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/11.1.1/include/node/v8.h:30:
/Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty/11.1.1/include/node/v8-internal.h:418:38: error: no template named 'remove_cv_t' in namespace 'std';
      did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
⠸ Building module: node-pty, Completed: 01 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/shlomidomnenko/Projects/e-xterm/node_modules/node-pty'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/Users/shlomidomnenko/Projects/e-xterm/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/Users/shlomidomnenko/Projects/e-xterm/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/Users/shlomidomnenko/Projects/e-xterm/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /Users/shlomidomnenko/Projects/e-xterm/node_modules/electron-rebuild/lib/src/cli.js:146:9
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! shadowengineterminaltest@1.0.0 macRebuild: `electron-rebuild -f -w node-pty`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the shadowengineterminaltest@1.0.0 macRebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shlomidomnenko/.npm/_logs/2020-12-27T20_18_11_521Z-debug.log

</details>

**Comment by rvagg** [comment]
Sorry to not be more helpful but you're going to have to take this one up with the node-pty folks at https://ghub.io/node-pty, it looks like the addon isn't being built, or downloaded, or whatever it needs to do. Probably something to do with the novel environment electron || electron-rebuild is giving you and not something to do with node-gyp.
