### ISSUE TITLE
Cannot support nodejs v15.x

### ISSUE THREAD

**Issue by bluemiaomiao** [nodejs/node-gyp#2292]
* **Node Version**: 15.4.0
* **Platform**: Microsoft Windows 10 专业版 10.0.19041 暂缺 Build 19041
* **Compiler**: 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.2+25e4d540b
* **Module**: node-sass@4.14.1

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\xujunjie\Documents\SourceTree\entrance-demo>yarn add node-sass@4.14.1
yarn add v1.22.10
[1/4] Resolving packages...
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "antd > @ant-design/create-react-context@0.2.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "antd > @ant-design/icons-react@2.0.1" has incorrect peer dependency "react@16.x".
warning "antd > rc-resize-observer@0.1.3" has incorrect peer dependency "react@^16.0.0".
warning "antd > rc-resize-observer@0.1.3" has incorrect peer dependency "react-dom@^16.0.0".
warning "antd > rc-switch@1.9.2" has incorrect peer dependency "react@^16.0.0".
warning "antd > rc-switch@1.9.2" has incorrect peer dependency "react-dom@^16.0.0".
warning "antd > rc-table@6.10.15" has incorrect peer dependency "react@^16.0.0".
warning "antd > rc-table@6.10.15" has incorrect peer dependency "react-dom@^16.0.0".
warning "antd > react-lazy-load@3.1.13" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "antd > react-lazy-load@3.1.13" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "antd > react-slick@0.25.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.1 || ^16.0.0".
warning "antd > react-slick@0.25.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1 || ^16.0.0".
warning "antd > rc-editor-mention > draft-js@0.10.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "antd > rc-editor-mention > draft-js@0.10.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "react-helmet > react-side-effect@1.2.0" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
[4/4] Building fresh packages...
[1/2] ⠐ core-js
error C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 15.4.0
gyp verb command install [ '15.4.0' ]
gyp verb install input version string "15.4.0"
gyp verb install installing version: 15.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.4.0
gyp verb build dir attempting to create "build" dir: C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xujunjie\\.node-gyp\\15.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xujunjie\\.node-gyp\\15.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\xujunjie\\.node-gyp\\15.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\xujunjie\.node-gyp\15.4.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:276:19)
gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xujunjie\\Documents\\SourceTree\\entrance-demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\xujunjie\Documents\SourceTree\entrance-demo\node_modules\node-sass
gyp ERR! node -v v15.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
```

</details>

this node v10.9.0 is ok:
<details><summary>Verbose output (from npm or node-gyp):</summary>

```
C:\Users\xujunjie\Documents\SourceTree\entrance-demo>yarn add node-sass@4.14.1
yarn add v1.22.10
[1/4] Resolving packages...
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "antd > @ant-design/create-react-context@0.2.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "antd > @ant-design/icons-react@2.0.1" has incorrect peer dependency "react@16.x".
warning "antd > rc-resize-observer@0.1.3" has incorrect peer dependency "react@^16.0.0".
warning "antd > rc-resize-observer@0.1.3" has incorrect peer dependency "react-dom@^16.0.0".
warning "antd > rc-switch@1.9.2" has incorrect peer dependency "react@^16.0.0".
warning "antd > rc-switch@1.9.2" has incorrect peer dependency "react-dom@^16.0.0".
warning "antd > rc-table@6.10.15" has incorrect peer dependency "react@^16.0.0".
warning "antd > rc-table@6.10.15" has incorrect peer dependency "react-dom@^16.0.0".
warning "antd > react-lazy-load@3.1.13" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "antd > react-lazy-load@3.1.13" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "antd > react-slick@0.25.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.1 || ^16.0.0".
warning "antd > react-slick@0.25.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1 || ^16.0.0".
warning "antd > rc-editor-mention > draft-js@0.10.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "antd > rc-editor-mention > draft-js@0.10.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0".
warning "react-helmet > react-side-effect@1.2.0" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 26 new dependencies.
info Direct dependencies
└─ node-sass@4.14.1
info All dependencies
├─ amdefine@1.0.1
├─ array-find-index@1.0.2
├─ async-foreach@0.1.3
├─ block-stream@0.0.9
├─ camelcase-keys@2.1.0
├─ currently-unhandled@0.4.1
├─ fstream@1.0.12
├─ gaze@1.1.3
├─ globule@1.3.2
├─ in-publish@2.0.1
├─ indent-string@2.1.0
├─ js-base64@2.6.4
├─ loud-rejection@1.6.0
├─ map-obj@1.0.1
├─ meow@3.7.0
├─ node-gyp@3.8.0
├─ node-sass@4.14.1
├─ nopt@3.0.6
├─ redent@1.0.0
├─ sass-graph@2.2.5
├─ scss-tokenizer@0.2.3
├─ stdout-stream@1.4.1
├─ strip-indent@1.0.1
├─ tar@2.2.2
├─ trim-newlines@1.0.0
└─ true-case-path@1.0.3
Done in 36.55s.
```

</details>

**Comment by cclauss** [comment]
> node-gyp@3.8.0

current is v7
