### ISSUE TITLE
Unable to override a variable defined in binding.gyp

### ISSUE THREAD

**Issue by tveronezi** [nodejs/node-gyp#2320]
* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```tveronezi:node-gyp-help-sample$ export GYP_DEFINES="so_dir=good_directory_here"
tveronezi:node-gyp-help-sample$ npm install

> node-gyp-help-sample@1.0.0 install /home/tveronezi/Documents/sources/trend_vpn/node-gyp-help-sample
> node-gyp rebuild

make: Entering directory '/home/tveronezi/Documents/sources/trend_vpn/node-gyp-help-sample/build'
  CXX(target) Release/obj.target/mycode/src/mycode.o
  SOLINK_MODULE(target) Release/obj.target/mycode.node
g++: error: /home/tveronezi/Documents/sources/trend_vpn/node-gyp-help-sample/wrong_dir/external.so: No such file or directory
mycode.target.mk:138: recipe for target 'Release/obj.target/mycode.node' failed
make: *** [Release/obj.target/mycode.node] Error 1
make: Leaving directory '/home/tveronezi/Documents/sources/trend_vpn/node-gyp-help-sample/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tveronezi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.15.0-132-generic
gyp ERR! command "/home/tveronezi/.nvm/versions/node/v14.4.0/bin/node" "/home/tveronezi/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tveronezi/Documents/sources/trend_vpn/node-gyp-help-sample
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gyp-help-sample@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gyp-help-sample@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tveronezi/.npm/_logs/2021-01-29T14_04_23_614Z-debug.log
tveronezi:node-gyp-help-sample$ 

```

</details>

Hi community, I need help finding out what's going on here.

I'm looking for a way to override a variable defined by my `binding.gyp` file. The trick with
`export GYP_DEFINES="so_dir=good_directory_here"` does not seem to work when the variable is defined in that file.

```
# overriding the value of the "so_dir" variable
export GYP_DEFINES="so_dir=good_directory_here"
npm install
...
g++: error: /home/tveronezi/Documents/sources/trend_vpn/node-gyp-help-sample/wrong_dir/external.so: No such file or directory
...
```

Note that the variable `so_dir` still points to the value defined in the `binding.gyp` file.

If I remove the variable definition out of the `binding.gyp` file and try it again, the `so_dir` will have the value
from the `GYP_DEFINES` environment variable.

`binding.gyp` without `variables`:

```
{
  "targets": [
    {
      "target_name": "mycode",
      "sources": [
        "src/mycode.cc",
      ],
      "libraries": [
        "<(so_dir)/external.so",
      ]
    }
  ]
}
```

```
export GYP_DEFINES="so_dir=good_directory_here"
npm install
...
g++: error: good_directory_here/external.so: No such file or directory
...
```

Can you help?

Companion project to reproduce the issue: https://github.com/tveronezi/node-gyp-help-sample

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v5.1.0

[Current is v7.1.2](https://github.com/nodejs/node-gyp/releases) so please update and try again.

**Comment by richardlau** [comment]
In your [`binding.gyp`](https://github.com/tveronezi/node-gyp-help-sample/blob/main/binding.gyp) you should declare the variable with a `%` suffix.
https://gyp.gsrc.io/docs/InputFormatReference.md#Providing-Default-Values-for-Variables

**Comment by tveronezi** [comment]
Thanks @cclauss and @richardlau . The suffix did the trick. Tx!
