### ISSUE TITLE
linux build fail -Werror (grpc@1.22.2 and node@14.15.4)

### ISSUE THREAD

**Issue by xenogenesi** [nodejs/node-gyp#2321]
* **Node Version**: node v14.15.4 and npm 6.14.11
* **Platform**: `Linux hellspawn 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux`
* **Compiler**: cc -v `gcc version 10.2.1 20210110 (Debian 10.2.1-6)`
* **Module**: 
* 
<details><summary>Verbose output from npm install:</summary>

```
$ npm i

> grpc@1.22.2 install /src/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.22.2 and node@14.15.4 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/src/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/status_util.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_internal.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/format_request.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/httpcli.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/parser.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/buffer_list.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/call_combiner.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/cfstream_handle.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/combiner.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_cfstream.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o
../deps/grpc/src/core/lib/iomgr/error.cc: In function ‘void internal_set_time(grpc_error**, grpc_error_times, gpr_timespec)’:
../deps/grpc/src/core/lib/iomgr/error.cc:267:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  267 |   memcpy((*err)->arena + slot, &value, sizeof(value));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../deps/grpc/src/core/lib/iomgr/error.cc:36:
../deps/grpc/src/core/lib/iomgr/error_internal.h:58:12: note: at offset 0 to object ‘grpc_error::arena’ with size 0 declared here
   58 |   intptr_t arena[0];
      |            ^~~~~
In function ‘void internal_add_error(grpc_error**, grpc_error*)’,
    inlined from ‘grpc_error* grpc_error_create(const char*, int, const grpc_slice&, grpc_error**, size_t)’ at ../deps/grpc/src/core/lib/iomgr/error.cc:357:23:
../deps/grpc/src/core/lib/iomgr/error.cc:290:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  290 |   memcpy((*err)->arena + slot, &new_last, sizeof(grpc_linked_error));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void internal_add_error(grpc_error**, grpc_error*)’,
    inlined from ‘grpc_error* grpc_error_add_child(grpc_error*, grpc_error*)’ at ../deps/grpc/src/core/lib/iomgr/error.cc:507:25:
../deps/grpc/src/core/lib/iomgr/error.cc:290:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  290 |   memcpy((*err)->arena + slot, &new_last, sizeof(grpc_linked_error));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:514: Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o] Error 1
make: Leaving directory '/src/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alex/install/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.0-2-amd64
gyp ERR! command "/home/alex/install/bin/node" "/home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /src/node_modules/grpc
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/alex/install/bin/node /home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/src/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.10.0-2-amd64
node-pre-gyp ERR! command "/home/alex/install/bin/node" "/src/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /src/node_modules/grpc
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/alex/install/bin/node /home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN svelte-app@1.0.0 No repository field.
npm WARN svelte-app@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2021-01-29T14_17_20_001Z-debug.log
```

</details>

I'm trying to run `npm install`, I haven't installed node-pre-gyp, node-gyp or gprc directly, perhaps are dependencies. I've installed the project without issues some week ago, then few days ago I've upgraded node, today I needed to reinstall the project. 

I'm not sure how to proceed

**Comment by rvagg** [comment]
these look like language problems with your newer compiler not supporting the older code with the strict flags causing errors. You need to take this up with grpc. sorry. https://ghub.io/grpc
