### ISSUE TITLE
Issue with installing node-gyp on Windows10 and Visual Studio 2019

### ISSUE THREAD

**Issue by LassiAutioSolita** [nodejs/node-gyp#2323]
* **Node Version**: v14.15.4 and 7.5.2
* **Platform**: Microsoft Windows 10 Enterprise, 10.0.19041 N/A Build 19041
* **Compiler**: Visual Studio 2019
* **Module**: node-gyp

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npm install node-gyp
npm ERR! code 1
npm ERR! path C:\xxx\myapp\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.4 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.1 found at "C:\xxx\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp info find VS using VS2019 (16.8.30907.101) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\xxx\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\xxx\\myapp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\xxx\\myapp\\node_modules\\fibers\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\xxx\\myapp\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\xxx\\AppData\\Local\\node-gyp\\Cache\\14.15.4\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\xxx\\AppData\\Local\\node-gyp\\Cache\\14.15.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\xxx\\myapp\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\xxx\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.4\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\xxx\\myapp\\node_modules\\fibers',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\xxx\\myapp\\node_modules\\fibers\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 3221225477
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\xxx\myapp\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xxx\\myapp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd C:\xxx\myapp\node_modules\fibers
npm ERR! gyp ERR! node -v v14.15.4
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! 'nodejs' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\xxx\AppData\Local\npm-cache\_logs\xxx.log
```

I have tried all things mentioned here: https://spin.atomicobject.com/2019/03/27/node-gyp-windows/
But I still can't install node-gyp. Is Node or Npm version not supported? Is there a wrong Visual Studio or Python version? What should I do?

**Comment by cclauss** [comment]
> I still can't install node-gyp.

The current node-gyp seems to be present: `npm ERR! gyp info using node-gyp@7.1.2`

**Comment by RileyManda** [comment]
Have you tried this solution?
[https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp](url)

**Comment by WickedWizard3588** [comment]
Did you install `node-gyp` globally? The first line says that you did `npm i node-gyp`. Instead of that, try doing `npm i -g node-gyp`

Then, create a `binding.gypi` and a `binding.cc` file, and you should be ready to run configure

**Comment by LassiAutioSolita** [comment]
I will close this as this is not relevant anymore for me. The problem wasn't solved but I didn't try the last suggestion.
