### ISSUE TITLE
Cannot install headers with proxy --> Error: self signed certificate

### ISSUE THREAD

**Issue by TheAsda** [nodejs/node-gyp#2331]
* **Node Version**: v14.15.5
* **NPM Version**: 6.14.11
* **Platform**: Windows 1909
* **Compiler**: 15.9.27

I tried installing with simple command
<details><summary>node-gyp install</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.5 | win32 | x64
gyp http GET https://nodejs.org/download/release/v14.15.5/node-v14.15.5-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install"
gyp ERR! cwd C:\Users\User\Documents\project
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

</details>

Then i added proxy
<details><summary>node-gyp install --proxy http://localhost:8888</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.5 | win32 | x64
gyp http GET https://nodejs.org/download/release/v14.15.5/node-v14.15.5-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--proxy" "http://localhost:8888"
gyp ERR! cwd C:\Users\User\Documents\project
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

</details>

Then i downloaded header and provided them via the flag

<details><summary>node-gyp install --tarball C:\Users\User\Downloads\node-v14.15.5-headers.tar.gz</summary>

```
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.5 | win32 | x64
gyp http GET https://nodejs.org/download/release/v14.15.5/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.15.5/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v14.15.5/win-arm64/node.lib
gyp http GET https://nodejs.org/download/release/v14.15.5/win-x64/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--tarball" "C:\\Users\\User\\Downloads\\node-v14.15.5-headers.tar.gz"
gyp ERR! cwd C:\Users\User\Documents\project
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

</details>

I tried to combine but result is the same. I don't understand why providing proxy does not work. This proxy is used in VS Code and other applications and they work fine with it. But here there is no difference between with and without proxy.
Has anyone faced this issue?

**Comment by StefanStojanovic** [comment]
Together with being stale for too long, this issue also targets old, no longer supported versions. For those reasons, I'm closing this issue now. If you experience similar behavior again, feel free to either reopen this one or open a new one.
