### ISSUE TITLE
UNCAUGHT EXCEPTION TypeError: tar.Extract is not a function

### ISSUE THREAD

**Issue by heyitsaking** [nodejs/node-gyp#2338]
* **Node Version**: Node 15.9.0 and NPM 7.5.4
* **Platform**: 
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19041 N/A Build 19041
System Type:               x64-based PC

I have updated node-gyp to the latest and have uninstalled and reinstalled Node and NPM to the latest

<details><summary>Verbose output (from npm or node-gyp):</summary>

Usage: npm audit fix

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Arturo King\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'audit',
0 verbose cli   'fix'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v15.9.0
...
468 verbose stack Error: command failed
468 verbose stack     at ChildProcess.<anonymous> (C:\Users\Arturo King\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
468 verbose stack     at ChildProcess.emit (node:events:378:20)
468 verbose stack     at maybeClose (node:internal/child_process:1067:16)
468 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
469 verbose pkgid node-sass@4.14.1
470 verbose cwd L:\Arturo King\Documents\git\crwn-clothing
471 verbose Windows_NT 10.0.19041
472 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arturo King\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "audit" "fix"
473 verbose node v15.9.0
474 verbose npm  v7.5.4
475 error code 7
476 error path L:\Arturo King\Documents\git\crwn-clothing\node_modules\node-sass
477 error command failed
478 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
479 error gyp info it worked if it ends with ok
479 error gyp info using node-gyp@3.8.0
479 error gyp info using node@15.9.0 | win32 | x64
479 error gyp ERR! UNCAUGHT EXCEPTION
479 error gyp ERR! stack TypeError: tar.Extract is not a function
479 error gyp ERR! stack     at L:\Arturo King\Documents\git\crwn-clothing\node_modules\node-gyp\lib\install.js:152:27
479 error gyp ERR! stack     at L:\Arturo King\Documents\git\crwn-clothing\node_modules\mkdirp\index.js:49:26
479 error gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:197:5)
479 error gyp ERR! System Windows_NT 10.0.19041
479 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "L:\\Arturo King\\Documents\\git\\crwn-clothing\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
479 error gyp ERR! cwd L:\Arturo King\Documents\git\crwn-clothing\node_modules\node-sass
479 error gyp ERR! node -v v15.9.0
479 error gyp ERR! node-gyp -v v3.8.0
479 error gyp ERR! This is a bug in `node-gyp`.
479 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
479 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
480 verbose exit 7
</details>

**Comment by cclauss** [comment]
> error gyp info using node-gyp@3.8.0

The current [release](https://github.com/nodejs/node-gyp/releases) in v71.2 so please upgrade.

**Comment by cclauss** [comment]
https://github.com/sass/node-sass/issues/2952 is deprecated.

**Comment by cclauss** [comment]
Please follow the Windows instructions at https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp
