### ISSUE TITLE
Npm fails to install

### ISSUE THREAD

**Issue by slim-hmidi** [nodejs/node-gyp#2340]
* **Node Version**: 14.15.5  and 6.14.11
* **Platform**: Windows 10 v 1909
* **Compiler**: 
* **Module**: npm i 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
.\src\binding.cc(345): error C2061: syntax error: identifier 'Handle' [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(83): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(91): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(91): error C2512: 'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\m 
agic.vcxproj]
..\src\binding.cc(94): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(95): error C2660: 'v8::Value::BooleanValue': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]       
..\src\binding.cc(120): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(120): error C2512: 'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\ 
magic.vcxproj]
..\src\binding.cc(274): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
  C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'
..\src\binding.cc(321): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
  C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'
..\src\binding.cc(336): error C2660: 'v8::Value::ToString': function does not take 0 arguments [node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(336): error C2227: left of '->Length' must point to class/struct/union/generic type [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]   
..\src\binding.cc(337): error C2660: 'v8::Value::ToString': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(337): error C2512: 'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\ 
magic.vcxproj]
..\src\binding.cc(354): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcx
proj]
..\src\binding.cc(354): error C2660: 'Nan::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>::Reset': function does not take 1 arguments [C:\Users\x199377\AppData\Local\Programs\Git\Ego\ego\ego-ap 
p\node_modules\mmmagic\build\magic.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\binding.cc(355): error C2065: 'target': undeclared identifier [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(355): error C2227: left of '->Set' must point to class/struct/union/generic type [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]      
  ..\src\binding.cc(355): note: type is 'unknown-type'
..\src\binding.cc(356): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcx 
proj]
..\src\binding.cc(358): error C2065: 'target': undeclared identifier [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(358): error C2227: left of '->Set' must point to class/struct/union/generic type [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]      
  ..\src\binding.cc(358): note: type is 'unknown-type'
..\src\binding.cc(358): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcx 
proj]
..\src\binding.cc(363): error C2065: 'Handle': undeclared identifier [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(363): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
  c:\users\x199377\appdata\local\node-gyp\cache\14.15.5\include\node\v8.h(3664): note: see declaration of 'v8::Object'
..\src\binding.cc(363): error C2065: 'target': undeclared identifier [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(363): error C2182: 'init': illegal use of type 'void' [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxproj]
..\src\binding.cc(363): error C2448: 'init': function-style initializer appears to be a function definition [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\build\magic.vcxp
roj]
..\src\binding.cc(368): warning C4312: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size [C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic\bui 
ld\magic.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xxx\AppData\Local\Programs\Git\myApp\node_modules\mmmagic
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

</details>

**Comment by slim-hmidi** [comment]
The issue fixed after upgraded the mmmagic to latest version
