### ISSUE TITLE
Error with Java on Windows Server 12

### ISSUE THREAD

**Issue by matheusgoc** [nodejs/node-gyp#2343]
* **Node Version**: v14.16.0
* **NPM Version**: 6.14.11
* **Platform**: Microsoft Windows Server 2012 R2 Datacenter | 6.3.9600 N/A Build 9600 | x64-based PC
* **Compiler**: not specified
* **Module**: node-expat

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

> node-gyp rebuild


C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python checking Python explicitly set from command line or npm configuration
gyp verb find Python - "--python=" or "npm config get python" is "python2.7"
gyp verb find Python - executing "python2.7" to get executable path
gyp verb find Python - "python2.7" is not in PATH or produced an error
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "C:\Program Files\Python\Python39\python.exe"
gyp verb find Python - executing "C:\Program Files\Python\Python39\python.exe" to get version
gyp verb find Python - version is "3.9.2"
gyp info find Python using Python version 3.9.2 found at "C:\Program Files\Python\Python39\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 14.16.0
gyp verb command install [ '14.16.0' ]
gyp verb install input version string "14.16.0"
gyp verb install installing version: 14.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.16.0
gyp verb build dir attempting to create "build" dir: C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build
gyp verb build dir "build" dir needed to be created? C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build
gyp verb find VS msvs_version was set from command line or npm config
gyp verb find VS - looking for Visual Studio version 2017
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2019 (16.9.31105.61) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp verb find VS - "Visual Studio C++ core features" missing
gyp verb find VS checking VS2017 (15.9.28307.1440) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp info find VS using VS2017 (15.9.28307.1440) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\config.gypi
gyp verb common.gypi checking for gypi file: C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Program Files\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Jenkins\\jobs\\COINS (DEV)\\workspace\\node_modules\\java\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\casit-jenkins\\AppData\\Local\\node-gyp\\Cache\\14.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\casit-jenkins\\AppData\\Local\\node-gyp\\Cache\\14.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\casit-jenkins\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Program Files (x86)\\Jenkins\\jobs\\COINS (DEV)\\workspace\\node_modules\\java',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Program Files (x86)\\Jenkins\\jobs\\COINS (DEV)\\workspace\\node_modules\\java\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/15/2021 3:37:50 PM.
Project "C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\binding.sln" (1) is building "C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\nodejavabridge_bindings\".
  Creating directory "Release\obj\nodejavabridge_bindings\nodejava.224DB15B.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\nodejavabridge_bindings\nodejava.224DB15B.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\CL.exe /c /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\include\node" /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\src" /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\deps\openssl\config" /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\deps\openssl\openssl\include" /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\deps\uv\include" /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\deps\zlib" /I"C:\Users\casit-jenkins\AppData\Local\node-gyp\Cache\14.16.0\deps\v8\include" /I"C:\Program Files\Common Files\Oracle\Java\include" /I..\..\nan /I"C:\Program Files\Common Files\Oracle\Java\include\win32" /Z7 /nologo /W3 /WX- /diagnostics:classic /MP /Ox /Ob2 /Oi /Ot /Oy /D NODE_GYP_MODULE_NAME=nodejavabridge_bindings /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D V8_DEPRECATION_WARNINGS /D V8_IMMINENT_DEPRECATION_WARNINGS /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D OPENSSL_NO_PINSHARED /D OPENSSL_THREADS /D BUILDING_NODE_EXTENSION /D "HOST_BINARY=\"node.exe\"" /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\nodejavabridge_bindings\\" /Fd"Release\obj\nodejavabridge_bindings\vc141.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /FC /errorReport:queue ..\src\java.cpp ..\src\javaObject.cpp ..\src\javaScope.cpp ..\src\methodCallBaton.cpp ..\src\nodeJavaBridge.cpp ..\src\utils.cpp "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
  java.cpp
  javaObject.cpp
c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\java.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\java.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  javaScope.cpp
c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\javaobject.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\javaObject.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  methodCallBaton.cpp
c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\javascope.h(5): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\javaScope.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  nodeJavaBridge.cpp
c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\utils.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\methodCallBaton.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  utils.cpp
c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\java.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\nodeJavaBridge.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  win_delay_load_hook.cc
c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\utils.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\utils.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
Done Building Project "C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\binding.sln" (default target) (1) ->
"C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\java.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\java.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\javaobject.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\javaObject.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\javascope.h(5): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\javaScope.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\utils.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\methodCallBaton.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\java.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\nodeJavaBridge.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\program files (x86)\jenkins\jobs\coins (dev)\workspace\node_modules\java\src\utils.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file or directory (compiling source file ..\src\utils.cpp) [C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\build\nodejavabridge_bindings.vcxproj]

    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:01.12
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm verb lifecycle java@0.12.1~install: unsafe-perm in lifecycle true
npm verb lifecycle java@0.12.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java\node_modules\.bin;C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\.bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk-15.0.2;C:\Program Files\Python\Python39;
npm verb lifecycle java@0.12.1~install: CWD: C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\java
npm info lifecycle java@0.12.1~install: Failed to exec install script
npm timing action:install Completed in 6954ms
npm verb unlock done using C:\Users\casit-jenkins\AppData\Roaming\npm-cache\_locks\staging-26d52f5872bdc276.lock for C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 110ms
npm timing stage:runTopLevelLifecycles Completed in 17119ms
npm WARN node-coinshandler@1.0.0 No description
npm WARN node-coinshandler@1.0.0 No repository field.

npm verb stack Error: java@0.12.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid java@0.12.1
npm verb cwd C:\Program Files (x86)\Jenkins\jobs\COINS (DEV)\workspace
npm verb Windows_NT 6.3.9600
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--loglevel" "verbose"
npm verb node v14.16.0
npm verb npm  v6.14.11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.12.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.12.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 17666ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\casit-jenkins\AppData\Roaming\npm-cache\_logs\2021-03-15T20_37_51_518Z-debug.log
```
</details>

After solving many other issues, I got stuck here where node-gyp tries to build something with JAVA. The error happens due to a file called *jni.h* that cannot be found:

`fatal error C1083: Cannot open include file: 'jni.h': No such file or directory`

**Comment by matheusgoc** [comment]
I could found the problem myself and there was nothing related to node-gyp package. Actually, the JAVA environment was place wrong on path. It was pointing to a path that had only java and javac commands. After reading the JAVA documentation, I set up the right path and it works perfect. For those that are facing similar problem, take a look on the [JDK installation documentation](https://docs.oracle.com/en/java/javase/11/install/installation-jdk-microsoft-windows-platforms.html) and then check if your JAVA environment had been set ok. In my case, I had to remove this path **C:\Program Files\Common Files\Oracle\Java\javapath** and add this one in turn: **C:\Program Files\Java\jdk-15.0.2\bin**. But it will depend on the JDK you have installed. Pretty much you need to have this **bin** directory of JDK set on PATH.
