### ISSUE TITLE
Issue with non 'username' defined

### ISSUE THREAD

**Issue by beltran-rubo** [nodejs/node-gyp#2373]
Related to this, still an issue when the username is not defined, only the user ID e.g. that is common in 'non-root' containers for OpenShift https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines.

```
I have no name!@52545ce360b8$ node-gyp --help
os.js:272
    throw new ERR_SYSTEM_ERROR(ctx);
    ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:272:11)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/node-gyp/lib/find-python.js:11:76)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/node-gyp/lib/configure.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_get_passwd'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
```

Python is in the path so a good option could be to add a fallback or not return an error for the line

```
const username = process.env.USERNAME || process.env.USER || require('os').userInfo().username
```

_Originally posted by @beltran-rubo in https://github.com/nodejs/node-gyp/pull/2333#discussion_r610383278_

**Comment by DeeDeeG** [comment]
@beltran-rubo I have a fix for this on a local branch. Having gotten this a little bit wrong the first time (as proved by your bug report), I am trying very hard to arrive at a design that is rock solid and with good code patterns.

That said, the simplest fix would be to not attempt `os.userInfo()` or to only attempt it in a `try {}` block.

Once I am happy with the design (I think that can be today) I will post it as a PR. But if posting it right away as a Work-In-Progress PR would be helpful, I can do that as well.

**Comment by DeeDeeG** [comment]
@beltran-rubo here is the Pull Request with my proposed fix: https://github.com/nodejs/node-gyp/pull/2375

**Comment by beltran-rubo** [comment]
Awesome thanks!
