### ISSUE TITLE
node-gyp rebuild command giving error during npm install

### ISSUE THREAD

**Issue by ashishkumar2804** [nodejs/node-gyp#2377]
* **Node Version**: node : 11.15.0, npm : 7.9.0
* **Platform**: Windows
* **Compiler**: Windows
* **Module**:  -
[2021-04-14T11_32_18_515Z-debug.log](https://github.com/nodejs/node-gyp/files/6310602/2021-04-14T11_32_18_515Z-debug.log)

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
NPM logs:
1854 verbose stack Error: command failed
1854 verbose stack     at ChildProcess.proc.on (C:\Users\ak9418\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
1854 verbose stack     at ChildProcess.emit (events.js:193:13)
1854 verbose stack     at maybeClose (internal/child_process.js:999:16)
1854 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
1855 verbose pkgid node-sass@4.14.1
1856 verbose cwd C:\SPM\spm-alignment\client\app
1857 verbose Windows_NT 10.0.18363
1858 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ak9418\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
1859 verbose node v11.15.0
1860 verbose npm  v7.9.0
1861 error code 1
1862 error path C:\SPM\spm-alignment\client\app\node_modules\node-sass
1863 error command failed
1864 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
1865 error gyp info it worked if it ends with ok
1865 error gyp info using node-gyp@3.8.0
1865 error gyp info using node@11.15.0 | win32 | x64
1865 error gyp http GET https://nodejs.org/download/release/v11.15.0/node-v11.15.0-headers.tar.gz
1865 error gyp WARN install got an error, rolling back install
1865 error gyp ERR! configure error
1865 error gyp ERR! stack Error: unable to get local issuer certificate
1865 error gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1245:34)
1865 error gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
1865 error gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:726:8)
1865 error gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:560:12)
1865 error gyp ERR! System Windows_NT 10.0.18363
1865 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\SPM\\spm-alignment\\client\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
1865 error gyp ERR! cwd C:\SPM\spm-alignment\client\app\node_modules\node-sass
1865 error gyp ERR! node -v v11.15.0
1865 error gyp ERR! node-gyp -v v3.8.0
1865 error gyp ERR! not ok
1866 verbose exit 1

Usage: npm <command>
(...)
```

</details>

attached log file too

Any help on fixing this will be much appreciated

**Comment by cclauss** [comment]
> error gyp info using node-gyp@3.8.0

v.s. https://github.com/nodejs/node-gyp/releases please upgrade
