### ISSUE TITLE
cuda module build fail on windows10 with error MSB3721..

### ISSUE THREAD

**Issue by cpple** [nodejs/node-gyp#2380]
cuda package building fail on windows!
* **Node Version**: node@v14.16.1 & npm@6.14.12
* **Platform**:Windows10 pro
* **Compiler**: VS2017 (15.9.28307.1300)
* **Module**: cuda-cpple

<details><summary>Verbose output (from npm or node-gyp):</summary>

npm install -d
npm info it worked if it ends with ok
npm info using npm@6.14.12
npm info using node@v14.16.1
npm info lifecycle test@1.0.0~preinstall: test@1.0.0
npm timing stage:loadCurrentTree Completed in 7ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/cuda-cpple 709ms
npm http fetch GET 200 https://registry.npmjs.org/cuda-cpple/-/cuda-cpple-1.0.0.tgz 250ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 985ms
npm timing stage:loadIdealTree Completed in 988ms
npm timing stage:generateActionsToTake Completed in 2ms
npm timing action:extract Completed in 13ms
npm timing action:finalize Completed in 4ms
npm timing action:refresh-package-json Completed in 8ms
npm info lifecycle cuda-cpple@1.0.0~preinstall: cuda-cpple@1.0.0
npm timing action:preinstall Completed in 1ms
npm info linkStuff cuda-cpple@1.0.0
npm timing action:build Completed in 1ms
npm info lifecycle cuda-cpple@1.0.0~install: cuda-cpple@1.0.0

> cuda-cpple@1.0.0 install E:\cnnAI\conv\error\test\node_modules\cuda-cpple
> node-gyp rebuild

E:\cnnAI\conv\error\test\node_modules\cuda-cpple>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild )  else (node "C:\Users\Cpple\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.16.1 | win32 | x64
gyp info find Python using Python version 3.7.9 found at "C:\Users\Cpple\AppData\Local\Programs\Python\Python37\python.exe"
gyp info find VS using VS2017 (15.9.28307.1300) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Cpple\AppData\Local\Programs\Python\Python37\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Cpple\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\cnnAI\\conv\\error\\test\\node_modules\\cuda-cpple\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cpple\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cpple\\AppData\\Local\\node-gyp\\Cache\\14.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Cpple\\AppData\\Local\\node-gyp\\Cache\\14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Cpple\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Cpple\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\cnnAI\\conv\\error\\test\\node_modules\\cuda-cpple',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\cnnAI\\conv\\error\\test\\node_modules\\cuda-cpple\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
。
  compile cuda file on windows
E:\cnnAI\conv\error\test\node_modules\cuda-cpple\build\cuda.targets(28,5): error MSB3721: 命令“call nvcc -c "..\test.cu" -o  "Release\obj\cuda\test.obj"”exit, code: 1. [E:\cnnAI\conv\error\test\node_modules
\cuda-cpple\b
uild\cuda.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Cpple\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Cpple\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\cnnAI\conv\error\test\node_modules\cuda-cpple
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok
npm timing audit submit Completed in 264ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 264ms
npm timing audit body Completed in 0ms
npm info lifecycle cuda-cpple@1.0.0~install: Failed to exec install script
npm timing action:install Completed in 12664ms
npm timing stage:rollbackFailedOptional Completed in 10ms
npm timing stage:runTopLevelLifecycles Completed in 13738ms
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cuda-cpple@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cuda-cpple@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 14217ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cpple\AppData\Roaming\npm-cache\_logs\2021-04-21T09_00_45_166Z-debug.log

</details>
package.json
`{
  "name": "test-cpple",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "cuda-cpple": "^1.0.0"
  },
  "author": "",
  "license": "ISC"
}`
test.js
`const cuda = require('test');
let result = cuda.cuda();
console.error(result)`

**Comment by cpple** [comment]
use "node-gyp rebuild"  alone in the directory is ok

**Comment by cpple** [comment]
cuda -v11.1 and cudnn -v8.1.1
