### ISSUE TITLE
Could not find any Visual Studio installation to us

### ISSUE THREAD

**Issue by Gavin-YYC** [nodejs/node-gyp#2397]
The error message shows that I did not install the tool and could not match msvs_ Version, but I have installed it and set it with `npm config set msvs_version 2017`.

-------------------------------

PS C:\Users\xxx\Desktop\fuzhu> node -v
`v14.16.0`
PS C:\Users\xxx\Desktop\fuzhu> npm config get msvs_version
`2017`
PS C:\Users\xxx\Desktop\fuzhu> .\node_modules\.bin\electron-rebuild.cmd
```
| Building module: winax, Completed: 0gyp info find Python using Python version 3.7.2 found at "C:\Users\xxx\.pyenv\pyenv-win\versions\3.7.2\python3.exe"
/ Building module: winax, Completed: 0gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2015
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.9.31205.134) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1525) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1500) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS - "2019"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - "2017"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - "2017"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\xxx\Desktop\fuzhu\node_modules\winax'.
Error: Could not find any Visual Studio installation to use



Error: node-gyp failed to rebuild 'C:\Users\xxx\Desktop\fuzhu\node_modules\winax'.
Error: Could not find any Visual Studio installation to use


    at ModuleRebuilder.rebuildNodeGypModule (C:\Users\xxx\Desktop\fuzhu\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (C:\Users\xxx\Desktop\fuzhu\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (C:\Users\xxx\Desktop\fuzhu\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async C:\Users\xxx\Desktop\fuzhu\node_modules\electron-rebuild\lib\src\cli.js:146:9
```

**Comment by Gavin-YYC** [comment]
By reading the source code of the electron-rebuild, I found just one way to change msvs_version's value is to change the system env variable named "GYP_MSVS_VERSION". which default set 2015.

I don't know if this is the right step. Because after that there shows another error.
