### ISSUE TITLE
Installing gpu.js fails with node-gyp not finding python

### ISSUE THREAD

**Issue by devghost** [nodejs/node-gyp#2398]
* **Node Version**: 16.1.0, npm: 7.11.2
* **Platform**: Linux 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 10.2.0 (Ubuntu 10.2.0-13ubuntu1)
* **Module**: gpu.js

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
> npm i gpu.js
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   'gpu.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.11.2
npm info using node@v16.1.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 0ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/home/robert/code/ml/gpu/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/robert/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 6ms
npm timing npm:load:configload Completed in 6ms
npm timing npm:load:setTitle Completed in 1ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 1ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 14ms
npm timing config:load:flatten Completed in 2ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 74ms
npm timing idealTree:userRequests Completed in 1ms
npm verb shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
npm http fetch GET 304 https://registry.npmjs.org/gpu.js 186ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/acorn 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gpu-mock.js 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gl 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gl-wiretap 79ms (from cache)
npm timing idealTree:#root Completed in 275ms
npm http fetch GET 304 https://registry.npmjs.org/bit-twiddle 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glsl-tokenizer 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-gyp 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 91ms (from cache)
npm timing idealTree:node_modules/gpu.js Completed in 99ms
npm timing idealTree:node_modules/acorn Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/semver 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 76ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/request 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 88ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/through2 105ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 109ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 112ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 116ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 120ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 123ms (from cache)
npm timing idealTree:node_modules/gl Completed in 139ms
npm timing idealTree:node_modules/bindings Completed in 1ms
npm timing idealTree:node_modules/bit-twiddle Completed in 0ms
npm timing idealTree:node_modules/file-uri-to-path Completed in 0ms
npm timing idealTree:node_modules/gl-wiretap Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xtend 45ms (from cache)
npm timing idealTree:node_modules/glsl-tokenizer Completed in 47ms
npm timing idealTree:node_modules/gpu-mock.js Completed in 0ms
npm timing idealTree:node_modules/nan Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 1ms
npm http fetch GET 304 https://registry.npmjs.org/ini 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 73ms (from cache)
npm timing idealTree:node_modules/prebuild-install Completed in 88ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/noop-logger Completed in 0ms
npm timing idealTree:node_modules/pump Completed in 1ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/rc Completed in 1ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 48ms (from cache)
npm timing idealTree:node_modules/simple-get Completed in 51ms
npm timing idealTree:node_modules/decompress-response Completed in 3ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/bl 37ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 43ms (from cache)
npm timing idealTree:node_modules/tar-fs Completed in 52ms
npm http fetch GET 304 https://registry.npmjs.org/buffer 35ms (from cache)
npm timing idealTree:node_modules/tar-stream Completed in 41ms
npm http fetch GET 304 https://registry.npmjs.org/base64-js 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ieee754 50ms (from cache)
npm timing idealTree:node_modules/bl Completed in 55ms
npm timing idealTree:node_modules/buffer Completed in 4ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 49ms (from cache)
npm timing idealTree:node_modules/through2 Completed in 57ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/which-pm-runs Completed in 0ms
npm timing idealTree:node_modules/xtend Completed in 0ms
npm timing idealTree:node_modules/bl/node_modules/readable-stream Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/aws-sign2 117ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/extend 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json-stringify-safe 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aws4 120ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-typedarray 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/form-data 119ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/forever-agent 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/performance-now 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/oauth-sign 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isstream 119ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/combined-stream 131ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/har-validator 126ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/http-signature 127ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/caseless 136ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/qs 121ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tough-cookie 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mime-types 130ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/uuid 125ms (from cache)
npm timing idealTree:node_modules/gl/node_modules/node-gyp Completed in 150ms
npm http fetch GET 304 https://registry.npmjs.org/delayed-stream 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/asynckit 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/sshpk 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ajv 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mime-db 74ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/psl 74ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsprim 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/punycode 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/assert-plus 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/har-schema 84ms (from cache)
npm timing idealTree:node_modules/request Completed in 99ms
npm timing idealTree:node_modules/aws-sign2 Completed in 0ms
npm timing idealTree:node_modules/aws4 Completed in 0ms
npm timing idealTree:node_modules/caseless Completed in 0ms
npm timing idealTree:node_modules/combined-stream Completed in 1ms
npm timing idealTree:node_modules/delayed-stream Completed in 0ms
npm timing idealTree:node_modules/extend Completed in 0ms
npm timing idealTree:node_modules/forever-agent Completed in 0ms
npm timing idealTree:node_modules/form-data Completed in 1ms
npm timing idealTree:node_modules/asynckit Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/json-schema-traverse 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-deep-equal 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/uri-js 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-json-stable-stringify 63ms (from cache)
npm timing idealTree:node_modules/har-validator Completed in 65ms
npm timing idealTree:node_modules/ajv Completed in 3ms
npm timing idealTree:node_modules/fast-deep-equal Completed in 0ms
npm timing idealTree:node_modules/fast-json-stable-stringify Completed in 0ms
npm timing idealTree:node_modules/har-schema Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/asn1 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/getpass 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bcrypt-pbkdf 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json-schema 85ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ecc-jsbn 84ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tweetnacl 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/extsprintf 93ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsbn 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/verror 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/dashdash 95ms (from cache)
npm timing idealTree:node_modules/http-signature Completed in 101ms
npm timing idealTree:node_modules/assert-plus Completed in 0ms
npm timing idealTree:node_modules/is-typedarray Completed in 0ms
npm timing idealTree:node_modules/isstream Completed in 0ms
npm timing idealTree:node_modules/json-schema-traverse Completed in 0ms
npm timing idealTree:node_modules/json-stringify-safe Completed in 0ms
npm timing idealTree:node_modules/jsprim Completed in 3ms
npm timing idealTree:node_modules/extsprintf Completed in 0ms
npm timing idealTree:node_modules/json-schema Completed in 0ms
npm timing idealTree:node_modules/mime-types Completed in 1ms
npm timing idealTree:node_modules/mime-db Completed in 0ms
npm timing idealTree:node_modules/oauth-sign Completed in 0ms
npm timing idealTree:node_modules/performance-now Completed in 0ms
npm timing idealTree:node_modules/qs Completed in 0ms
npm timing idealTree:node_modules/sshpk Completed in 7ms
npm timing idealTree:node_modules/asn1 Completed in 0ms
npm timing idealTree:node_modules/bcrypt-pbkdf Completed in 0ms
npm timing idealTree:node_modules/dashdash Completed in 0ms
npm timing idealTree:node_modules/ecc-jsbn Completed in 0ms
npm timing idealTree:node_modules/getpass Completed in 0ms
npm timing idealTree:node_modules/jsbn Completed in 0ms
npm timing idealTree:node_modules/tough-cookie Completed in 2ms
npm timing idealTree:node_modules/psl Completed in 0ms
npm timing idealTree:node_modules/punycode Completed in 0ms
npm timing idealTree:node_modules/tweetnacl Completed in 0ms
npm timing idealTree:node_modules/uri-js Completed in 0ms
npm timing idealTree:node_modules/uuid Completed in 0ms
npm timing idealTree:node_modules/verror Completed in 0ms
npm timing idealTree:node_modules/node-abi/node_modules/semver Completed in 0ms
npm timing idealTree:node_modules/tar-fs/node_modules/chownr Completed in 0ms
npm timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
npm timing idealTree:node_modules/through2/node_modules/readable-stream Completed in 2ms
npm timing idealTree:node_modules/through2/node_modules/isarray Completed in 0ms
npm timing idealTree:node_modules/through2/node_modules/string_decoder Completed in 0ms
npm timing idealTree:buildDeps Completed in 1368ms
npm timing idealTree:fixDepFlags Completed in 2ms
npm timing idealTree Completed in 1447ms
npm timing reify:loadTrees Completed in 1448ms
npm timing reify:diffTrees Completed in 5ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 8ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 358ms
npm timing auditReport:getReport Completed in 359ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 360ms
npm timing reifyNode:node_modules/oauth-sign Completed in 357ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 357ms
npm timing reifyNode:node_modules/ini Completed in 357ms
npm timing reifyNode:node_modules/which-pm-runs Completed in 357ms
npm timing reifyNode:node_modules/end-of-stream Completed in 357ms
npm timing reifyNode:node_modules/tar-fs/node_modules/chownr Completed in 357ms
npm timing reifyNode:node_modules/simple-get Completed in 357ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 358ms
npm timing reifyNode:node_modules/bindings Completed in 360ms
npm timing reifyNode:node_modules/assert-plus Completed in 364ms
npm timing reifyNode:node_modules/is-typedarray Completed in 364ms
npm timing reifyNode:node_modules/forever-agent Completed in 364ms
npm timing reifyNode:node_modules/caseless Completed in 364ms
npm timing reifyNode:node_modules/aws-sign2 Completed in 364ms
npm timing reifyNode:node_modules/ieee754 Completed in 365ms
npm timing reifyNode:node_modules/fs-constants Completed in 365ms
npm timing reifyNode:node_modules/mimic-response Completed in 365ms
npm timing reifyNode:node_modules/decompress-response Completed in 365ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 365ms
npm timing reifyNode:node_modules/through2 Completed in 366ms
npm timing reifyNode:node_modules/through2/node_modules/string_decoder Completed in 366ms
npm timing reifyNode:node_modules/gpu-mock.js Completed in 367ms
npm timing reifyNode:node_modules/combined-stream Completed in 370ms
npm timing reifyNode:node_modules/base64-js Completed in 370ms
npm timing reifyNode:node_modules/expand-template Completed in 370ms
npm timing reifyNode:node_modules/through2/node_modules/isarray Completed in 370ms
npm timing reifyNode:node_modules/getpass Completed in 377ms
npm timing reifyNode:node_modules/delayed-stream Completed in 376ms
npm timing reifyNode:node_modules/mime-types Completed in 375ms
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm timing reifyNode:node_modules/har-validator Completed in 376ms
npm timing reifyNode:node_modules/xtend Completed in 375ms
npm timing reifyNode:node_modules/simple-concat Completed in 375ms
npm timing reifyNode:node_modules/deep-extend Completed in 375ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 375ms
npm timing reifyNode:node_modules/pump Completed in 375ms
npm timing reifyNode:node_modules/gl-wiretap Completed in 376ms
npm timing reifyNode:node_modules/punycode Completed in 382ms
npm timing reifyNode:node_modules/bcrypt-pbkdf Completed in 381ms
npm timing reifyNode:node_modules/jsprim Completed in 381ms
npm timing reifyNode:node_modules/isstream Completed in 386ms
npm timing reifyNode:node_modules/extend Completed in 387ms
npm timing reifyNode:node_modules/aws4 Completed in 386ms
npm timing reifyNode:node_modules/noop-logger Completed in 385ms
npm timing reifyNode:node_modules/detect-libc Completed in 386ms
npm timing reifyNode:node_modules/bit-twiddle Completed in 386ms
npm timing reifyNode:node_modules/jsbn Completed in 392ms
npm timing reifyNode:node_modules/verror Completed in 391ms
npm timing reifyNode:node_modules/tar-stream Completed in 390ms
npm timing reifyNode:node_modules/file-uri-to-path Completed in 389ms
npm timing reifyNode:node_modules/node-abi/node_modules/semver Completed in 390ms
npm timing reifyNode:node_modules/ecc-jsbn Completed in 395ms
npm timing reifyNode:node_modules/extsprintf Completed in 395ms
npm timing reifyNode:node_modules/json-stringify-safe Completed in 394ms
npm timing reifyNode:node_modules/asn1 Completed in 397ms
npm timing reifyNode:node_modules/json-schema-traverse Completed in 397ms
npm timing reifyNode:node_modules/buffer Completed in 396ms
npm timing reifyNode:node_modules/fast-deep-equal Completed in 399ms
npm timing reifyNode:node_modules/dashdash Completed in 402ms
npm timing reifyNode:node_modules/github-from-package Completed in 399ms
npm timing reifyNode:node_modules/glsl-tokenizer Completed in 400ms
npm timing reifyNode:node_modules/rc Completed in 402ms
npm timing reifyNode:node_modules/tough-cookie Completed in 406ms
npm timing reifyNode:node_modules/bl Completed in 404ms
npm timing reifyNode:node_modules/node-abi Completed in 404ms
npm timing reifyNode:node_modules/form-data Completed in 408ms
npm timing reifyNode:node_modules/http-signature Completed in 408ms
npm timing reifyNode:node_modules/mime-db Completed in 411ms
npm timing reifyNode:node_modules/through2/node_modules/readable-stream Completed in 409ms
npm timing reifyNode:node_modules/asynckit Completed in 413ms
npm timing reifyNode:node_modules/performance-now Completed in 412ms
npm timing reifyNode:node_modules/prebuild-install Completed in 411ms
npm timing reifyNode:node_modules/fast-json-stable-stringify Completed in 414ms
npm timing reifyNode:node_modules/uuid Completed in 417ms
npm timing reifyNode:node_modules/tweetnacl Completed in 419ms
npm timing reifyNode:node_modules/har-schema Completed in 418ms
npm timing reifyNode:node_modules/minimist Completed in 415ms
npm timing reifyNode:node_modules/qs Completed in 424ms
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm timing reifyNode:node_modules/request Completed in 425ms
npm timing reifyNode:node_modules/psl Completed in 431ms
npm timing reifyNode:node_modules/bl/node_modules/readable-stream Completed in 428ms
npm timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 428ms
npm timing reifyNode:node_modules/tar-fs Completed in 432ms
npm timing reifyNode:node_modules/json-schema Completed in 438ms
npm timing reifyNode:node_modules/sshpk Completed in 445ms
npm timing reifyNode:node_modules/uri-js Completed in 451ms
npm timing reifyNode:node_modules/acorn Completed in 448ms
npm timing reifyNode:node_modules/nan Completed in 449ms
npm timing reifyNode:node_modules/ajv Completed in 474ms
npm timing reifyNode:node_modules/gl/node_modules/node-gyp Completed in 490ms
npm timing reifyNode:node_modules/gpu.js Completed in 492ms
npm timing reifyNode:node_modules/gl Completed in 640ms
npm timing reify:unpack Completed in 647ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 2ms
npm timing build:link:node_modules/acorn Completed in 2ms
npm timing build:link:node_modules/detect-libc Completed in 2ms
npm timing build:link:node_modules/prebuild-install Completed in 2ms
npm timing build:link:node_modules/rc Completed in 2ms
npm timing build:link:node_modules/sshpk Completed in 2ms
npm timing build:link:node_modules/uuid Completed in 3ms
npm timing build:link:node_modules/gl/node_modules/node-gyp Completed in 2ms
npm timing build:link:node_modules/node-abi/node_modules/semver Completed in 2ms
npm timing build:link Completed in 3ms
npm info run gl@4.9.0 install node_modules/gl prebuild-install || node-gyp rebuild
npm info run gl@4.9.0 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 122ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 2716ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:365:28)
npm verb stack     at maybeClose (node:internal/child_process:1067:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid gl@4.9.0
npm verb cwd /home/robert/code/ml/gpu
npm verb Linux 5.11.0-7614-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "gpu.js" "--verbose"
npm verb node v16.1.0
npm verb npm  v7.11.2
npm ERR! code 1
npm ERR! path /home/robert/code/ml/gpu/node_modules/gl
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install info begin Prebuild-install version 5.3.6
npm ERR! prebuild-install info install installing standalone, skipping download.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/home/robert/code/ml/gpu/node_modules/gl/node_modules/.bin/node-gyp',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.1.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python checking Python explicitly set from command line or npm configuration
npm ERR! gyp verb find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.8.6"
npm ERR! gyp info find Python using Python version 3.8.6 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.1.0
npm ERR! gyp verb command install [ '16.1.0' ]
npm ERR! gyp verb install input version string "16.1.0"
npm ERR! gyp verb install installing version: 16.1.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.1.0
npm ERR! gyp verb build dir attempting to create "build" dir: /home/robert/code/ml/gpu/node_modules/gl/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/robert/code/ml/gpu/node_modules/gl/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/robert/code/ml/gpu/node_modules/gl/build/config.gypi
npm ERR! (node:16482) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /home/robert/code/ml/gpu/node_modules/gl/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/robert/code/ml/gpu/node_modules/gl/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/robert/code/ml/gpu/node_modules/gl/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/robert/code/ml/gpu/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/robert/code/ml/gpu/node_modules/gl/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/robert/.cache/node-gyp/16.1.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/robert/.cache/node-gyp/16.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/robert/code/ml/gpu/node_modules/gl/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/robert/.cache/node-gyp/16.1.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/robert/code/ml/gpu/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: python: not found
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/robert/code/ml/gpu/node_modules/gl/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.11.0-7614-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/robert/code/ml/gpu/node_modules/gl/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/robert/code/ml/gpu/node_modules/gl
npm ERR! gyp ERR! node -v v16.1.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 2875ms
npm verb code 1
```

</details>

Been trying to install Gpu.js but to no avail. Any help is highly appreciated.
python3 --version: 3.8.6
python --version: 3.8.6

Using Fish shell mostly, but bash yields same error.

**Comment by devghost** [comment]
Sigh, spending hours trying to get it to work.. decides to post an issue only to find an article moments later on the interwebs that solved the issue. What finally did the trick was..

```
sudo apt-get remove -y gyp 
sudo apt install -y curl bzip2 build-essential g++ python git make gcc gcc-multilib node-gyp 
```

Not sure which package solved it, but I'm a happy camper :)
