### ISSUE TITLE
LINK : fatal error LNK1158: cannot run 'rc.exe'

### ISSUE THREAD

**Issue by ghost** [nodejs/node-gyp#2400]
Hello,

I've been trying to rebuild `node-gyp` for my sqlite, but it throws this error
`LINK : fatal error LNK1158: cannot run 'rc.exe' [D:\Chintu\Coding\Javascript\Xyborg\build\binding.vcxproj]`

* **Node Version**: 14.17.0 (NodeJS-LTS) & 7.13.0 (NPM)
* **Platform**: Windows
* **Compiler**: MSBuild.exe
* **Module**: Normal `node-gyp` build commands

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
λ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@14.17.0 | win32 | x64
gyp info find Python using Python version 3.9.4 found at "C:\Python39\python.exe"
gyp info find VS using VS2019 (16.9.31229.75) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\chira\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Chintu\\Coding\\Javascript\\Xyborg\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\chira\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\chira\\AppData\\Local\\node-gyp\\Cache\\14.17.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\chira\\AppData\\Local\\node-gyp\\Cache\\14.17.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\chira\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\chira\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Chintu\\Coding\\Javascript\\Xyborg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Chintu\\Coding\\Javascript\\Xyborg\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  binding.cc
  win_delay_load_hook.cc
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
LINK : fatal error LNK1158: cannot run 'rc.exe' [D:\Chintu\Coding\Javascript\Xyborg\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\chira\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chira\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Chintu\Coding\Javascript\Xyborg
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok
```
</details>

I've tried reinstalling `node-gyp`, and `Visual Studio 2019` in vain. Python Version `3.9.4` 

My Binding Files,
binding.cc 
```
// Just an empty file
```

binding.gyp
```
{
    "targets": [
        {
            "target_name": "binding",
            "sources": [ "binding.cc" ]
        }
    ]
}
```

My Visual Studio is installed with the options `Desktop Development With C++` and `Node.js Development`
I also tried the solution mentioned in #1541 but, it too didn't work

Thank you

**Comment by cclauss** [comment]
Dup of #1541 ?

**Comment by WickedWizard3588** [comment]
I tried it, it didn't work. I mentioned that above :^)

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
