### ISSUE TITLE
How to solve gyp ERR! problem?

### ISSUE THREAD

**Issue by cooper1x** [nodejs/node-gyp#2415]
* **Node Version**:  16.0.1
* **Platform**: windows 10 x64

```
C:\sx\cmder_mini>node-gyp configure --msvs_version=2017
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@16.1.0 | win32 | x64
gyp info find Python using Python version 3.9.5 found at "C:\Program Files\Python39\python3.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.10.31321.278) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.9.31313.79) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - found in "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp ERR! find VS - could not find MSBuild in registry for this version
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS - "2019"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - "2019"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\find-visualstudio.js:384:20
gyp ERR! stack     at C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.21354
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2017"
gyp ERR! cwd C:\sx\cmder_mini
gyp ERR! node -v v16.1.0
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok
```
```
PS C:\Users\Cooper> node-gyp configure --msvs_version=2019
gyp info it worked if it ends with ok
gyp info using node-gyp@8.0.0
gyp info using node@16.1.0 | win32 | x64
gyp info find Python using Python version 3.9.5 found at "C:\Program Files\Python39\python3.exe"
gyp info find VS using VS2019 (16.10.31321.278) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
(node:44084) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn C:\Program Files\Python39\python3.exe
gyp info spawn args [
gyp info spawn args   'C:\\ProgramData\\nvs\\node\\16.1.0\\x64\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cooper\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\ProgramData\\nvs\\node\\16.1.0\\x64\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Cooper\\AppData\\Local\\node-gyp\\Cache\\16.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Cooper\\AppData\\Local\\node-gyp\\Cache\\16.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\ProgramData\\nvs\\node\\16.1.0\\x64\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Cooper\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.1.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Cooper',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Cooper\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Users\Cooper) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\ProgramData\nvs\node\16.1.0\x64\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.21354
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2019"
gyp ERR! cwd C:\Users\Cooper
gyp ERR! node -v v16.1.0
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok
```

**Comment by owl-from-hogvarts** [comment]
Hi, @cooper1x! What do you want to do?

According to `node-gyp --help` command `configure`:
> `configure` - Generates a Makefile for the *current module*

For second provided output, you are tryng to "configure" `node-gyp` in the folder (`C:\Users\Cooper` your home directory in fact) which is not contain any module to be build. So to solve the problem, change your current working dirrectory via `cd` command to i guess `C:\sx\cmder_mini` from your first output.

From `node-gyp` README.md:
> Note: The configure step looks for a binding.gyp file in the current directory to process. 

For firts output you a trying to force node-gyp to use VS version 2017 while it seems that you have only VS *2019* installed. So you can try to specify version `2019`

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
