### ISSUE TITLE
How to resolve a configure error in node-gyp

### ISSUE THREAD

**Issue by rouuzz** [nodejs/node-gyp#2422]
Can anyone help with this? I'm trying to install quick.db for almost 3 days now, I tried so many methods but nothing works

```
PS C:\Windows\system32> npm i quick.db

better-sqlite3@7.4.0 install C:\Windows\system32\node_modules\better-sqlite3
prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=ia32 libc= platform=win32)

better-sqlite3@7.4.0 build-release C:\Windows\system32\node_modules\better-sqlite3
node-gyp rebuild --release


C:\Windows\system32\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp: binding.gyp not found (cwd: C:\Windows\system32\node_modules\better-sqlite3) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Windows\system32\node_modules\better-sqlite3
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.4.0 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.4.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chantal\AppData\Roaming\npm-cache\_logs\2021-05-30T21_03_15_155Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.4.0 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chantal\AppData\Roaming\npm-cache\_logs\2021-05-30T21_03_15_462Z-debug.log
```

**Comment by cclauss** [comment]
This line in the error log above is a problem.
> gyp ERR! node-gyp -v v5.1.0

Please upgrade https://github.com/nodejs/node-gyp/releases

**Comment by rouuzz** [comment]
> This line in the error log above is a problem.
> 
> > gyp ERR! node-gyp -v v5.1.0
> 
> Please upgrade https://github.com/nodejs/node-gyp/releases
> https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp#windows

I'm sorry, but i did that and i still get the same error

**Comment by cclauss** [comment]
Does the log still say: `gyp ERR! node-gyp -v v5.1.0`

**Comment by rouuzz** [comment]
> Does the log still say: `gyp ERR! node-gyp -v v5.1.0`

Not the same, now it shows me this

```
gyp ERR! node-gyp -v v8.1.0
```

**Comment by cclauss** [comment]
Please provide the full log.

**Comment by rouuzz** [comment]
> Please provide the full log.

```
PS C:\Windows\system32> npm i quick.db

> better-sqlite3@7.4.0 install C:\Windows\system32\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=ia32 libc= platform=win32)

> better-sqlite3@7.4.0 build-release C:\Windows\system32\node_modules\better-sqlite3
> node-gyp rebuild --release


C:\Windows\system32\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp: binding.gyp not found (cwd: C:\Windows\system32\node_modules\better-sqlite3) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Windows\system32\node_modules\better-sqlite3
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.4.0 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.4.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chantal\AppData\Roaming\npm-cache\_logs\2021-05-31T20_44_05_600Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.4.0 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chantal\AppData\Roaming\npm-cache\_logs\2021-05-31T20_44_06_157Z-debug.log
```

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
