### ISSUE TITLE
better sqlite 

### ISSUE THREAD

**Issue by alphaleadership** [nodejs/node-gyp#2436]
* **Node Version**: v15.14.0
* **Platform**: win32
* **Compiler**: 
* **Module**: 
quick.db
<details><summary>Verbose output (from npm or node-gyp):</summary>

it worked if it ends with ok
cli [
  'C:\\Program Files (x86)\\nodejs\\node.exe',
  'C:\\Users\\Collegien\\node_modules\\node-gyp\\bin\\node-gyp.js',
  'rebuild',
  '--release'
]
using node-gyp@%s 3.8.0
using node@%s | %s | %s 15.14.0 win32 ia32
UNCAUGHT EXCEPTION
stack TypeError: log.verbose is not a function
    at Object.self.commands.<computed> [as rebuild] (C:\Users\Collegien\node_modules\node-gyp\lib\node-gyp.js:54:11)
    at run (C:\Users\Collegien\node_modules\node-gyp\bin\node-gyp.js:87:30)
    at Object.<anonymous> (C:\Users\Collegien\node_modules\node-gyp\bin\node-gyp.js:148:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
System Windows_NT 10.0.17134
command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Collegien\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
cwd C:\Users\Collegien\Documents\GitHub\bot\node_modules\better-sqlite3
node -v v15.14.0
node-gyp -v v3.8.0
 This is a bug in `node-gyp`.
Try to update node-gyp and file an Issue if it does not help:
```
Paste your log here, between the backticks. It can be:
  - npm --verbose output,
  - or contents of npm-debug.log,
  - or output of node-gyp rebuild --verbose.
Include the command you were trying to run.

This should look like this:

>npm --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node.exe',
npm verb cli   'C:\\...\\node\\13.9.0\\x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.9.0

Usage: npm <command>
(...)
```

</details>

**Comment by cclauss** [comment]
The current [release of node-gyp](https://github.com/nodejs/node-gyp/releases) is __v8.1.0__ but the log output above says:
> gyp ERR! node-gyp -v v3.8.0

Please use https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp to upgrade to the current version of node-gyp.
