### ISSUE TITLE
gyp ERR! on npm/yarn install

### ISSUE THREAD

**Issue by bUxEE** [nodejs/node-gyp#2444]
I encounter the following error, log says 
npm ERR! gyp info using node-gyp@3.8.0
but if i use the command node-gyp -v  v8.1.0 is displayed. How can i force npm to use the correct node-gyp version?

node v16.3.0
npm  v7.19.0
python 3.9.5
Windows10 AMD64

```
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\...\AppData\Roaming\nvm\v16.3.0\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27) npm verb stack     at ChildProcess.emit (node:events:394:28)
npm verb stack     at maybeClose (node:internal/child_process:1067:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid node-sass@4.14.1
npm verb cwd C:\...
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--verbose"
npm verb node v16.3.0
npm verb npm  v7.19.0
npm ERR! code 1
npm ERR! path C:\...\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\...\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\...\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.3.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Python39\python.exe" in the PATH
npm ERR! gyp verb `which` succeeded C:\Python39\python.exe C:\Python39\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\...\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.3.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
npm verb exit 1
npm timing npm Completed in 7816ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Local\npm-cache\_logs\2021-06-25T09_25_53_133Z-debug.log

```

**Comment by cclauss** [comment]
Please see https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by bUxEE** [comment]
Thank you for your quick answer, but i am using[ VNM windows ](https://github.com/coreybutler/nvm-windows).
Will that guide still work?

**Comment by BasilaryGroup** [comment]
I'm running Volta. The suggested fix runs for npm < 7, but the same error appears.

**Comment by cclauss** [comment]
> the same error appears

Does it still say `npm ERR! gyp ERR! node-gyp -v v3.8.0`?

**Comment by BasilaryGroup** [comment]
```
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | win32 | x64
```

```
> npm --version
6.14.13
```

**Comment by BasilaryGroup** [comment]
```
> node-sass@4.13.1 postinstall C:\Users\Me\Web\client\node_modules\node-sass
> node scripts/build.js

Building: C:\Users\Me\AppData\Local\Volta\tools\image\node\14.17.0\node.exe C:\Users\Me\Web\client\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Users\\Me\\AppData\\Local\\Volta\\tools\\image\\node\\14.17.0\\node.exe',
gyp verb cli   'C:\\Users\\Me\\Web\\client\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Me\Web\client\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Me\Web\client\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Me\Web\client\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Me\Web\client\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Me\Web\client\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Me\Web\client\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Me\Web\client\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Me\Web\client\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Me\Web\client\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Me\Web\client\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Me\Web\client\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Me\Web\client\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Me\AppData\Local\Programs\Python\Python37\python.EXE
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Users\Me\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\Me\\AppData\\Local\\Volta\\tools\\image\\node\\14.17.0\\node.exe" "C:\\Users\\Me\\Web\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Me\Web\client\node_modules\node-sass
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vtk.js@16.2.1 requires a peer of wslink@0.1.15 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Me\AppData\Roaming\npm-cache\_logs\2021-06-27T20_04_26_707Z-debug.log
```

**Comment by cclauss** [comment]
Current npm is 7.19.0 https://www.npmjs.com/package/npm

Current node-gyp is v8.1.0.  https://github.com/nodejs/node-gyp/releases v3 is out-of-date.

Node-sass is deprecated.  https://github.com/sass/node-sass/issues/2952

**Comment by BasilaryGroup** [comment]
I've upgrade npm to 7.19.0. I'm still seeing the same problem.

Until a few minutes ago, I didn't know node-gyp existed. How does one upgrade node-gyp?

**Comment by BasilaryGroup** [comment]
Ok. Upgraded npm to `7.19.0`, followed the instructions https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md#windows to upgrade for Windows.

There is no sub folder `node_modules\npm\node_modules\@npmcli\run-script`.

**Comment by BasilaryGroup** [comment]
Ran the following,

```
npm install --package-lock-only
npm audit fix --force
```

Now I see a different problem with node-gyp.

```
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:326:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Users\\David\\AppData\\Local\\Volta\\tools\\image\\node\\14.17.0\\node.exe" "C:\\Users\\David\\ShearFrac\\FracBrainWeb\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\David\ShearFrac\FracBrainWeb\client\node_modules\node-sass
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```

Do I need to install Visual Studio????

**Comment by cclauss** [comment]
```
cd c:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle
npm install node-gyp@latest
```

**Comment by BasilaryGroup** [comment]
That's what I did. Now I'm seeing errors about Visual Studio. I don't have Visual Studio on my machine. I do have VS Code.

**Comment by BasilaryGroup** [comment]
Am I getting burned by Volta? I just finished migrating our projects from various versions on node to node 14.x. Would it help to remove Volta?

**Comment by BasilaryGroup** [comment]
I don't remember ever installing `node-gyp`.

**Comment by BasilaryGroup** [comment]
What a mess. For those stuck with this problem of being guilting of using older packages on your Windows development system.

* Uninstalled Volta, *it served its purpose*
* Uninstalled node 14.x
* deleted `c:\Program Files\nodejs`
* rebooted
* installed node 14.7.1, do **not** select Automatically install the necessary tools.... option

Now I'm left with a node-sass problem due to old code that didn't cleanly, my bad, migrate from Vuetify 1.5 to 2.x. *I thought I had migrated correctly*.

* npm uinstall node-sass
* npm install --save-dev sass

Clean install and build and my website is building and running.

Thank you `cclauss` for your patience! I'm still not sure WTH happened.

**Comment by cclauss** [comment]
@bUxEE Can this issue be closed?

**Comment by bUxEE** [comment]
Last night I managed to update node-gyp in the latest node version 16.x.x inside nvm folders. This did not solve the error but by:

installing a lower version of node (14.x.x) which was using node-gyp 5.x
completely removing all lock files and node_modules directory
reinstalling with yarn 

solved the issue

**Comment by TheoOliveira** [comment]
In case someone faced, my context i was using vite with yarn, i just add to the package using the @latest tag 

`yarn add node-gyp@latest`
