### ISSUE TITLE
Python syntax error when using node-gyp@3.8.0

### ISSUE THREAD

**Issue by xtexChooser** [nodejs/node-gyp#2451]
* **Node Version**: 
* **Platform**: 
* **Compiler**: 
* **Module**: 

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npm ERR! code 1
npm ERR! path F:\Blog\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\Program Files\nodejs\node.exe F:\Blog\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'F:\\Blog\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.2.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python E:\Program Files\Python\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: E:\Program Files\Python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "F:\\Blog\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd F:\Blog\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xtex\AppData\Local\npm-cache\_logs\2021-07-03T00_55_52_982Z-debug.log

</details>

I think the problem is at `E:\Program Files\Python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];`

**Comment by xtexChooser** [comment]
Windows 10 64bits
nodejs v16.2.0

**Comment by xtexChooser** [comment]
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@3.8.0
vs. https://github.com/nodejs/node-gyp/releases

https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by xtexChooser** [comment]
How can I install the new version?
```
F:\Blog>npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path F:\Blog\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\Program Files\nodejs\node.exe F:\Blog\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'F:\\Blog\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.2.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python E:\Program Files\Python\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: E:\Program Files\Python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "F:\\Blog\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd F:\Blog\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xtex\AppData\Local\npm-cache\_logs\2021-07-03T07_39_13_246Z-debug.log

F:\Blog>node-gyp

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `msbuild` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates MSVC project files for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@8.1.0  C:\Users\xtex\AppData\Roaming\npm\node_modules\node-gyp
node@16.2.0
```

**Comment by cclauss** [comment]
Please read the last url above.

**Comment by xtexChooser** [comment]
I saw.

It did not work.

```
D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\node_modules>cd node-gyp

D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp>ls
CHANGELOG.md     LICENSE    addon.gypi  gyp  macOS_Catalina.md            package.json  test
CONTRIBUTING.md  README.md  bin         lib  macOS_Catalina_acid_test.sh  src           update-gyp.py

D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp>cat package.json
{
  "name": "node-gyp",
  "description": "Node.js native addon build tool",
  "license": "MIT",
  "keywords": [
    "native",
    "addon",
    "module",
    "c",
    "c++",
    "bindings",
    "gyp"
  ],
  "version": "8.1.0",
  "installVersion": 9,
  "author": "Nathan Rajlich <nathan@tootallnate.net> (http://tootallnate.net)",
  "repository": {
    "type": "git",
    "url": "git://github.com/nodejs/node-gyp.git"
  },
  "preferGlobal": true,
  "bin": "./bin/node-gyp.js",
  "main": "./lib/node-gyp.js",
  "dependencies": {
    "env-paths": "^2.2.0",
    "glob": "^7.1.4",
    "graceful-fs": "^4.2.6",
    "make-fetch-happen": "^8.0.14",
    "nopt": "^5.0.0",
    "npmlog": "^4.1.2",
    "rimraf": "^3.0.2",
    "semver": "^7.3.5",
    "tar": "^6.1.0",
    "which": "^2.0.2"
  },
  "engines": {
    "node": ">= 10.12.0"
  },
  "devDependencies": {
    "bindings": "^1.5.0",
    "nan": "^2.14.2",
    "require-inject": "^1.4.4",
    "standard": "^14.3.4",
    "tap": "^12.7.0"
  },
  "scripts": {
    "lint": "standard */*.js test/**/*.js",
    "test": "npm run lint && tap --timeout=120 test/test-*"
  }
}

D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp>
```

But, I remember that node gyp tells me that it can not found MSVC when I try to install it.

Am I have to install MSVC?

**Comment by owl-from-hogvarts** [comment]
run exact `python --version` please. It seems that python in PATH which is found by node-gyp differ from which one is prefered by you.

**Comment by cclauss** [comment]
`py --version`  # on Windows?

`python3 --version`

**Comment by xtexChooser** [comment]
I uninstalled Ubuntu for WSL just now.
I still installed python for windows and the python in cygwin but they are all python 3.
```
Microsoft Windows [版本 10.0.19043.1081]
(c) Microsoft Corporation。保留所有权利。

C:\Users\xtex>py --version
Python 3.9.5

C:\Users\xtex>python --version
Python 3.9.5

C:\Users\xtex>python3 --version

C:\Users\xtex>which python
/cygdrive/e/Program Files/Python/python

C:\Users\xtex>which which
/usr/bin/which

C:\Users\xtex>which python3
/usr/bin/python3

C:\Users\xtex>bash E:\cygwin64\bin\py --version
bash: E:\cygwin64\bin\py: No such file or directory

C:\Users\xtex>bash

xtex@xtex /cygdrive/c/Users/xtex
$ E:\cygwin64\bin\py --version
bash: E:cygwin64binpy: command not found

xtex@xtex /cygdrive/c/Users/xtex
$ E:/cygwin64/bin/py --version
bash: E:/cygwin64/bin/py: No such file or directory

xtex@xtex /cygdrive/c/Users/xtex
$ py --version
Python 3.9.5

xtex@xtex /cygdrive/c/Users/xtex
$ python --version
Python 3.9.5

xtex@xtex /cygdrive/c/Users/xtex
$ python3 --version
Python 3.8.10

xtex@xtex /cygdrive/c/Users/xtex
$
```

F:\Blog>npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path F:\Blog\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\Program Files\nodejs\node.exe F:\Blog\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'F:\\Blog\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.2.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\Blog\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\Blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python E:\Program Files\Python\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: E:\Program Files\Python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "F:\\Blog\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd F:\Blog\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xtex\AppData\Local\npm-cache\_logs\2021-07-07T04_43_57_813Z-debug.log

F:\Blog>"E:\Program Files\Python\python.EXE" --version
Python 3.9.5

**Comment by cclauss** [comment]
Congratulations!  Python 3 is properly installed.  The problem is that the log still says:
> npm ERR! gyp info using node-gyp@3.8.0

This [version of node-gyp](https://github.com/nodejs/node-gyp/releases) needs to be upgraded as discussed at:
https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by xtexChooser** [comment]
I tryed to upgrade it but it gets failure.

```
C:\Users\xtex>node -v
v16.2.0

C:\Users\xtex>npm -v
7.19.1

C:\Users\xtex>node-gyp -v
v8.1.0

C:\Users\xtex>where node
D:\Program Files\nodejs\node.exe

C:\Users\xtex>which node
/cygdrive/d/Program Files/nodejs/node

C:\Users\xtex>D:

D:\>cd Program Files\nodejs\

D:\Program Files\nodejs>ls
install_tools.bat  node.exe  node_etw_provider.man  node_modules  nodevars.bat  npm  npm.cmd  npx  npx.cmd

D:\Program Files\nodejs>cd node_moddules\npm\node_modules\@npmcli\run-script
系统找不到指定的路径。

D:\Program Files\nodejs>cd node_modules\npm\node_modules\@npmcli\run-script

D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script>npm install node-gyp@latest

up to date, audited 655 packages in 4s

61 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script>cat node-gyp/package.json
cat: node-gyp/package.json: No such file or directory

D:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script>cat node_modules/node-gyp/package.json
{
  "name": "node-gyp",
  "description": "Node.js native addon build tool",
  "license": "MIT",
  "keywords": [
    "native",
    "addon",
    "module",
    "c",
    "c++",
    "bindings",
    "gyp"
  ],
  "version": "8.1.0",
  "installVersion": 9,
  "author": "Nathan Rajlich <nathan@tootallnate.net> (http://tootallnate.net)",
  "repository": {
    "type": "git",
    "url": "git://github.com/nodejs/node-gyp.git"
  },
  "preferGlobal": true,
  "bin": "./bin/node-gyp.js",
  "main": "./lib/node-gyp.js",
  "dependencies": {
    "env-paths": "^2.2.0",
    "glob": "^7.1.4",
    "graceful-fs": "^4.2.6",
    "make-fetch-happen": "^8.0.14",
    "nopt": "^5.0.0",
    "npmlog": "^4.1.2",
    "rimraf": "^3.0.2",
    "semver": "^7.3.5",
    "tar": "^6.1.0",
    "which": "^2.0.2"
  },
  "engines": {
    "node": ">= 10.12.0"
  },
  "devDependencies": {
    "bindings": "^1.5.0",
    "nan": "^2.14.2",
    "require-inject": "^1.4.4",
    "standard": "^14.3.4",
    "tap": "^12.7.0"
  },
  "scripts": {
    "lint": "standard */*.js test/**/*.js",
    "test": "npm run lint && tap --timeout=120 test/test-*"
  }
}

```

**Comment by cclauss** [comment]
Please try
```
C:\Users\xtex>npm -v
7.19.1

C:\Users\xtex>where node
D:\Program Files\nodejs\node.exe

cd "D:\Program Files\nodejs\node.exe\node_modules\npm\node_modules\@npmcli\run-script"
npm install node-gyp@latest
```

**Comment by xtexChooser** [comment]
I know!! 
```
npm ERR! code 1
npm ERR! path F:\Blog\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\Program Files\nodejs\node.exe F:\Blog\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
```
npm using an local installed node-gyp!

I try to run `npm install` and break it force using CTRL+C

node_modules directory was not deleted.

I opened it. The node-gyp is 3.8.0!

I am trying install node-gyp@latest in my local project

**Comment by cclauss** [comment]
Ahhh… [`node-sass is deprecated`](https://github.com/nodejs/node-gyp/labels/Node%20Sass%20--%3E%20Dart%20Sass).

**Comment by xtexChooser** [comment]
I do NOT KNOW where did I included node-sass, but Github Actions can build it correctly;

See https://github.com/xtexChooser/blog/runs/2476485914?check_suite_focus=true

**Comment by xtexChooser** [comment]
Looks like hexo-renderer-scss

**Comment by xtexChooser** [comment]
Thanks, I am opening issues in hexo-renderer-scss

**Comment by makc-dataloop** [comment]
> Please read the last url above.

did not work today as well, after 
> Finish by running:
> $ npm install node-gyp@latest

step I get
```
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/fibers.cc:27:65: error: no member named 'kFinalizer' in 'v8::WeakCallbackType'
npm ERR!                 handle.SetWeak(val, WeakCallbackShim<F, P>, WeakCallbackType::kFinalizer);
npm ERR!                                                             ~~~~~~~~~~~~~~~~~~^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
```
(this is on mac m1 13.6.4)
