### ISSUE TITLE
Failed to install node-gyp while installing ffmpeg-concat

### ISSUE THREAD

**Issue by sbonaime** [nodejs/node-gyp#2460]
node -v v16.5.0
npm -v 7.20.0
Darwin macagyver.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64 macos 11.5
cc -v
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```
npm install --save ffmpeg-concat
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/bonaime/node_modules/ffmpeg-concat/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Using cached /Users/bonaime/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.5.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! (node:9192) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/bonaime/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bonaime/node_modules/ffmpeg-concat/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bonaime/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/bonaime/Library/Caches/node-gyp/16.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/bonaime/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/bonaime/Library/Caches/node-gyp/16.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/bonaime/node_modules/ffmpeg-concat/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/common.cc:22:
npm ERR! In file included from /Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/node.h:63:
npm ERR! In file included from /Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/v8.h:30:
npm ERR! /Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/v8-internal.h:454:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/bonaime/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/16.5.0/bin/node" "/Users/bonaime/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/bonaime/node_modules/ffmpeg-concat/node_modules/sharp
npm ERR! gyp ERR! node -v v16.5.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bonaime/.npm/_logs/2021-07-22T12_13_10_441Z-debug.log
```
and
````
node-gyp rebuild --verbose.
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@16.5.0 | darwin | x64
gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
(node:10530) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bonaime/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bonaime/Library/Caches/node-gyp/16.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/bonaime/Library/Caches/node-gyp/16.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/bonaime',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Users/bonaime) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/Cellar/node/16.5.0/bin/node" "/usr/local/bin/node-gyp" "rebuild" "--verbose."
gyp ERR! cwd /Users/bonaime
gyp ERR! node -v v16.5.0
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok
````
not sur it is  problem of ffmpeg-concat module https://github.com/transitive-bullshit/ffmpeg-concat/issues/122

**Comment by richardlau** [comment]
> ```
> npm ERR! /Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/v8-internal.h:454:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
> npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
> npm ERR!                                 ~~~~~^~~~~~~~~~~
> npm ERR!                                      remove_cv
> npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
> npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
> npm ERR!                                                  ^
> npm ERR! 1 error generated.
> npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
> ```

This looks like an incompatibility with the `sharp` libary (that `ffmpeg-concat` depends on) and the version of V8 inside Node.js 16. `remove_cv_t` is a [C++14 feature](https://en.cppreference.com/w/cpp/types/remove_cv) but `sharp` declares to use the earlier C++11 standard: https://github.com/lovell/sharp/blob/7467fa8b50d280780dfa9fe9a7248deaa499c7a1/binding.gyp#L178

**Comment by sbonaime** [comment]
> > ```
> > npm ERR! /Users/bonaime/Library/Caches/node-gyp/16.5.0/include/node/v8-internal.h:454:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
> > npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
> > npm ERR!                                 ~~~~~^~~~~~~~~~~
> > npm ERR!                                      remove_cv
> > npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
> > npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
> > npm ERR!                                                  ^
> > npm ERR! 1 error generated.
> > npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
> > ```
> 
> This looks like an incompatibility with the `sharp` libary (that `ffmpeg-concat` depends on) and the version of V8 inside Node.js 16. `remove_cv_t` is a [C++14 feature](https://en.cppreference.com/w/cpp/types/remove_cv) but `sharp` declares to use the earlier C++11 standard: https://github.com/lovell/sharp/blob/7467fa8b50d280780dfa9fe9a7248deaa499c7a1/binding.gyp#L178

Anything I can do to  install ffmpeg-concat ? thanks

**Comment by richardlau** [comment]
You could try using Node.js 14. Otherwise you may need to engage with https://github.com/lovell/sharp to see if there's a solution there.

**Comment by hieunc229** [comment]
Switch to Node.js v14 definitely solved the issue

**Comment by swampthang** [comment]
I'm trying to add this to an electron app. I switched to Nodejs 14 using nvm and still having this issue. I first tried 14.7 and then went all the way back to 14.0.0. About ready to give up on this. Spent 2 days trying to get this set up. I'm trying to add this to an electron app. 

**Version info:**
node: 14.0.0
npm: 6.14.4
node-gyp: 3.6.2
Python: 3.6.10

This is the error I'm ending up with when trying to install...

```
An unhandled error has occurred inside Forge:
node-gyp failed to rebuild '/<app-path>/node_modules/ffmpeg-concat/node_modules/sharp'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: 'make' failed with exit code: 2

Error: node-gyp failed to rebuild '/<app-path>/node_modules/ffmpeg-concat/node_modules/sharp'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: 'make' failed with exit code: 2

    at NodeGyp.rebuildModule (/<app-path>/node_modules/electron-rebuild/src/module-type/node-gyp.ts:129:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ModuleRebuilder.rebuildNodeGypModule (/<app-path>/node_modules/electron-rebuild/src/module-rebuilder.ts:93:5)
    at ModuleRebuilder.rebuild (/<app-path>/node_modules/electron-rebuild/src/module-rebuilder.ts:129:8)
    at Rebuilder.rebuildModuleAt (/<app-path>/node_modules/electron-rebuild/src/rebuild.ts:203:9)
    at Rebuilder.rebuild (/<app-path>/node_modules/electron-rebuild/src/rebuild.ts:158:9)
    at /<app-path>/node_modules/@electron-forge/core/src/util/rebuild.ts:32:5
```
Any help would be greatly appreciated.

**Comment by cclauss** [comment]
Node-gyp 3 and Python 3.6 are both end of life.  Please upgrade.

**Comment by cclauss** [comment]
Can this issue be closed?
