### ISSUE TITLE
Visual Studio 2022 Preview - stack Error: Could not find any Visual Studio installation to use 

### ISSUE THREAD

**Issue by innellea** [nodejs/node-gyp#2462]
* **Node Version**: v15.3.0
* **Platform**:  /C:"System Type"` (Windows) 
* **Compiler**: 
* **Module**: node-sass

> 12094 error gyp verb find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Preview"

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
12094 error gyp verb build dir attempting to create "build" dir: D:\Project\FashionOrb\client\node_modules\node-sass\build
12094 error gyp verb build dir "build" dir needed to be created? D:\Project\FashionOrb\client\node_modules\node-sass\build
12094 error gyp verb find VS msvs_version was set from command line or npm config
12094 error gyp verb find VS - looking for Visual Studio version 2017
12094 error gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
12094 error gyp verb find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Preview"
12094 error gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
12094 error gyp verb find VS looking for Visual Studio 2015
12094 error gyp verb find VS - not found
12094 error gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
12094 error gyp ERR! find VS
12094 error gyp ERR! find VS msvs_version was set from command line or npm config
12094 error gyp ERR! find VS - looking for Visual Studio version 2017
12094 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
12094 error gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Preview"
12094 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
12094 error gyp ERR! find VS looking for Visual Studio 2015
12094 error gyp ERR! find VS - not found
12094 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
12094 error gyp ERR! find VS
12094 error gyp ERR! find VS valid versions for msvs_version:
12094 error gyp ERR! find VS
12094 error gyp ERR! find VS **************************************************************
12094 error gyp ERR! find VS You need to install the latest version of Visual Studio
12094 error gyp ERR! find VS including the "Desktop development with C++" workload.
12094 error gyp ERR! find VS For more information consult the documentation at:
12094 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
12094 error gyp ERR! find VS **************************************************************
12094 error gyp ERR! find VS
12094 error gyp ERR! configure error
12094 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
12094 error gyp ERR! stack     at VisualStudioFinder.fail (D:\Project\FashionOrb\client\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
12094 error gyp ERR! stack     at D:\Project\FashionOrb\client\node_modules\node-gyp\lib\find-visualstudio.js:74:16
12094 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\Project\FashionOrb\client\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
12094 error gyp ERR! stack     at D:\Project\FashionOrb\client\node_modules\node-gyp\lib\find-visualstudio.js:70:14
12094 error gyp ERR! stack     at D:\Project\FashionOrb\client\node_modules\node-gyp\lib\find-visualstudio.js:372:16
12094 error gyp ERR! stack     at D:\Project\FashionOrb\client\node_modules\node-gyp\lib\util.js:54:7
12094 error gyp ERR! stack     at D:\Project\FashionOrb\client\node_modules\node-gyp\lib\util.js:33:16
12094 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:316:5)
12094 error gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
12094 error gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
12094 error gyp ERR! System Windows_NT 10.0.22000
12094 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Project\\FashionOrb\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
12094 error gyp ERR! cwd D:\Project\FashionOrb\client\node_modules\node-sass
12094 error gyp ERR! node -v v15.3.0
12094 error gyp ERR! node-gyp -v v7.1.2
12094 error gyp ERR! not ok
12094 error Build failed with error code: 1
12095 verbose exit 1
```

</details>

**Comment by cclauss** [comment]
Node-sass is deprecated so we can not support it with a preview version of MSVS.

**Comment by blattersturm** [comment]
This doesn't only happen with 'node-sass', it happens with any node-gyp module. I don't get why this is closed.

**Comment by cclauss** [comment]
@blattersturm Please provide the command that was typed and the full error log.

**Comment by blattersturm** [comment]
The same portion from the error log above applies, this e.g. also happens when trying to run `npm i ffi-napi` with _only_ VS2022 installed:

```
12094 error gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
12094 error gyp verb find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Preview"
12094 error gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
12094 error gyp verb find VS looking for Visual Studio 2015
12094 error gyp verb find VS - not found
12094 error gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
```

Some code here hardcodes checks for 2019 when checking for MSBuild path:

https://github.com/nodejs/node-gyp/blob/782a6f12d75d0af96e6ae797d38a492d4a9af7e8/lib/find-visualstudio.js#L272

... though the bundled `gyp` also seems unaware of any newer version:

https://github.com/nodejs/node-gyp/blob/0da2e0140dbf4296d5ba7ea498fac05e74bb4bbb/gyp/pylib/gyp/MSVSVersion.py#L273

Should this not fall back to pretending to be the version before if a newer one is installed?

**Comment by cclauss** [comment]
I believe that  was fixed in gyp-next v0.10.0 https://github.com/nodejs/gyp-next/blob/main/CHANGELOG.md

**Comment by aleksey-hoffman** [comment]
@cclauss the issue should probably be re-opened:

**VS Studio**: 2022 (all build tools and C++  workloads are inistalled)

```
>node-gyp
v8.2.0
>node-gyp configure
```
### Error
```
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@15.14.0 | win32 | x64
gyp info find Python using Python version 3.9.6 found at "C:\Python39\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Preview"
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\Preview"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
```

**Comment by liudonghua123** [comment]
I have the same problems. When I add `--loglevel silly` options to `npm install` and I found the key errors belows:

```
npm ERR! gyp verb find VS msvs_version was set from command line or npm config
npm ERR! gyp verb find VS - looking for Visual Studio version 2022
npm ERR! gyp verb find VS running in VS Command Prompt, installation path is:
npm ERR! gyp verb find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp verb find VS - will only use this version
npm ERR! gyp sill find VS Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [
npm ERR! gyp sill find VS   '-ExecutionPolicy',
npm ERR! gyp sill find VS   'Unrestricted',
npm ERR! gyp sill find VS   '-NoProfile',
npm ERR! gyp sill find VS   '-Command',
npm ERR! gyp sill find VS   "&{Add-Type -Path 'C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v16.13.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\Find-VisualStudio.cs';[VisualStudioConfiguration.Main]::PrintJson()}"
npm ERR! gyp sill find VS ]
npm ERR! gyp sill find VS PS stderr = ""
npm ERR! gyp sill find VS processing installation: "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp sill find VS - version match = ["17.0.31903.59","17","0"]
npm ERR! gyp sill find VS - unsupported version: 17
npm ERR! gyp sill find VS - found VC.Tools.x86.x64
npm ERR! gyp sill find VS - invalid versionYear: undefined
npm ERR! gyp sill find VS - found Win10SDK: 19041
npm ERR! gyp sill find VS vsInfo: [
npm ERR! gyp sill find VS   {
npm ERR! gyp sill find VS     path: 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community',
npm ERR! gyp sill find VS     msBuild: null,
npm ERR! gyp sill find VS     toolset: null,
npm ERR! gyp sill find VS     sdk: '10.0.19041.0'
npm ERR! gyp sill find VS   }
npm ERR! gyp sill find VS ]
```

And finally I found the npm was `8.1.0` which the bundled `node-gyp` is `8.2.0` which does not support vs 2022 (https://github.com/nodejs/node-gyp/blob/bc47cd60b986eaa55a23050d8f72d1cc117bdba0/lib/find-visualstudio.js#L252-L259).

Then I tried to update `node-gyp` to latest `8.4.0` currently (https://github.com/nodejs/node-gyp/blob/7073c65f61d2b5b3a4aff3370be430849b9bd0b3/lib/find-visualstudio.js#L253-L264) in npm directory which was `C:\Users\Liu.D.H\AppData\Roaming\nvm\v16.13.0\node_modules\npm` on my environment. And this error disappeared.

````
npm ERR! gyp verb find VS msvs_version was set from command line or npm config
npm ERR! gyp verb find VS - looking for Visual Studio version 2022
npm ERR! gyp verb find VS running in VS Command Prompt, installation path is:
npm ERR! gyp verb find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp verb find VS - will only use this version
npm ERR! gyp sill find VS Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [
npm ERR! gyp sill find VS   '-ExecutionPolicy',
npm ERR! gyp sill find VS   'Unrestricted',
npm ERR! gyp sill find VS   '-NoProfile',
npm ERR! gyp sill find VS   '-Command',
npm ERR! gyp sill find VS   "&{Add-Type -Path 'C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v16.13.0\\node_modules\\npm\\node_modules\\node-gyp\\lib\\Find-VisualStudio.cs';[VisualStudioConfiguration.Main]::PrintJson()}"
npm ERR! gyp sill find VS ]
npm ERR! gyp sill find VS PS stderr = ""
npm ERR! gyp sill find VS processing installation: "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp sill find VS - version match = ["17.0.31903.59","17","0"]
npm ERR! gyp sill find VS - found VC.Tools.x86.x64
npm ERR! gyp sill find VS - found Win10SDK: 19041
npm ERR! gyp sill find VS vsInfo: [
npm ERR! gyp sill find VS   {
npm ERR! gyp sill find VS     version: '17.0.31903.59',
npm ERR! gyp sill find VS     versionMajor: 17,
npm ERR! gyp sill find VS     versionMinor: 0,
npm ERR! gyp sill find VS     versionYear: 2022,
npm ERR! gyp sill find VS     path: 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community',
npm ERR! gyp sill find VS     msBuild: 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe',
npm ERR! gyp sill find VS     toolset: 'v143',
npm ERR! gyp sill find VS     sdk: '10.0.19041.0'
npm ERR! gyp sill find VS   }
npm ERR! gyp sill find VS ]
npm ERR! gyp verb find VS checking VS2022 (17.0.31903.59) found at:
npm ERR! gyp verb find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp verb find VS - found "Visual Studio C++ core features"
npm ERR! gyp verb find VS - found VC++ toolset: v143
npm ERR! gyp verb find VS - found Windows SDK: 10.0.19041.0
npm ERR! gyp info find VS using VS2022 (17.0.31903.59) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
```

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/releases --> __v8.4.0__
* https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by olawalejuwonm** [comment]
I also have issues with this

**Comment by wsdt** [comment]
me as well

**Comment by WeiqianFredZhang** [comment]
I am stuck trying to npm install @tensorflow-tfjs-node for a week because my computer "could not find any visual studio installation to use"

**Comment by WeiqianFredZhang** [comment]
> me as well

I fixed this by downloading the 2017 Visual Studio Community on https://www.techspot.com/downloads/6278-visual-studio.html
