### ISSUE TITLE
I tried creating new Vue project with Sass-loader, and I get this error

### ISSUE THREAD

**Issue by UmrenTV** [nodejs/node-gyp#2468]
```
965 error code 1
966 error path C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass
967 error command failed
968 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
969 error Building: C:\Program Files\nodejs\node.exe C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
970 error gyp info it worked if it ends with ok
970 error gyp verb cli [
970 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
970 error gyp verb cli   'C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-gyp\\bin\\node-gyp.js',
970 error gyp verb cli   'rebuild',
970 error gyp verb cli   '--verbose',
970 error gyp verb cli   '--libsass_ext=',
970 error gyp verb cli   '--libsass_cflags=',
970 error gyp verb cli   '--libsass_ldflags=',
970 error gyp verb cli   '--libsass_library='
970 error gyp verb cli ]
970 error gyp info using node-gyp@3.8.0
970 error gyp info using node@15.5.1 | win32 | x64
970 error gyp verb command rebuild []
970 error gyp verb command clean []
970 error gyp verb clean removing "build" directory
970 error gyp verb command configure []
970 error gyp verb check python checking for Python executable "python2" in the PATH
970 error gyp verb `which` failed Error: not found: python2
970 error gyp verb `which` failed     at getNotFoundError (C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:13:12)
970 error gyp verb `which` failed     at F (C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:68:19)
970 error gyp verb `which` failed     at E (C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:80:29)
970 error gyp verb `which` failed     at C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:89:16
970 error gyp verb `which` failed     at C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\isexe\index.js:42:5
970 error gyp verb `which` failed     at C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\isexe\windows.js:36:5
970 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
970 error gyp verb `which` failed  python2 Error: not found: python2
970 error gyp verb `which` failed     at getNotFoundError (C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:13:12)
970 error gyp verb `which` failed     at F (C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:68:19)
970 error gyp verb `which` failed     at E (C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:80:29)
970 error gyp verb `which` failed     at C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\which\which.js:89:16
970 error gyp verb `which` failed     at C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\isexe\index.js:42:5
970 error gyp verb `which` failed     at C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\isexe\windows.js:36:5
970 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
970 error gyp verb `which` failed   code: 'ENOENT'
970 error gyp verb `which` failed }
970 error gyp verb check python checking for Python executable "python" in the PATH
970 error gyp verb `which` succeeded python C:\Python27\python.EXE
970 error gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.18
970 error gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
970 error gyp verb get node dir no --target version specified, falling back to host node version: 15.5.1
970 error gyp verb command install [ '15.5.1' ]
970 error gyp verb install input version string "15.5.1"
970 error gyp verb install installing version: 15.5.1
970 error gyp verb install --ensure was passed, so won't reinstall if already installed
970 error gyp verb install version is already installed, need to check "installVersion"
970 error gyp verb got "installVersion" 9
970 error gyp verb needs "installVersion" 9
970 error gyp verb install version is good
970 error gyp verb get node dir target node version installed: 15.5.1
970 error gyp verb build dir attempting to create "build" dir: C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass\build
970 error gyp verb build dir "build" dir needed to be created? C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass\build
970 error gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
970 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
970 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
970 error gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
970 error gyp verb find vs2017   - Using this installation with Windows 10 SDK
970 error gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
970 error gyp verb build/config.gypi creating config file
970 error gyp verb build/config.gypi writing out config file: C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass\build\config.gypi
970 error gyp verb config.gypi checking for gypi file: C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass\config.gypi
970 error gyp verb common.gypi checking for gypi file: C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass\common.gypi
970 error gyp verb gyp gyp format was not specified; forcing "msvs"
970 error gyp info spawn C:\Python27\python.EXE
970 error gyp info spawn args [
970 error gyp info spawn args   'C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-gyp\\gyp\\gyp_main.py',
970 error gyp info spawn args   'binding.gyp',
970 error gyp info spawn args   '-f',
970 error gyp info spawn args   'msvs',
970 error gyp info spawn args   '-G',
970 error gyp info spawn args   'msvs_version=2015',
970 error gyp info spawn args   '-I',
970 error gyp info spawn args   'C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-sass\\build\\config.gypi',
970 error gyp info spawn args   '-I',
970 error gyp info spawn args   'C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-gyp\\addon.gypi',
970 error gyp info spawn args   '-I',
970 error gyp info spawn args   'C:\\Users\\umren\\.node-gyp\\15.5.1\\include\\node\\common.gypi',
970 error gyp info spawn args   '-Dlibrary=shared_library',
970 error gyp info spawn args   '-Dvisibility=default',
970 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\umren\\.node-gyp\\15.5.1',
970 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-gyp',
970 error gyp info spawn args   '-Dnode_lib_file=C:\\Users\\umren\\.node-gyp\\15.5.1\\<(target_arch)\\node.lib',
970 error gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-sass',
970 error gyp info spawn args   '-Dnode_engine=v8',
970 error gyp info spawn args   '--depth=.',
970 error gyp info spawn args   '--no-parallel',
970 error gyp info spawn args   '--generator-output',
970 error gyp info spawn args   'C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-sass\\build',
970 error gyp info spawn args   '-Goutput_dir=.'
970 error gyp info spawn args ]
970 error gyp verb command build []
970 error gyp verb build type Release
970 error gyp verb architecture x64
970 error gyp verb node dev dir C:\Users\umren\.node-gyp\15.5.1
970 error gyp verb found first Solution file build/binding.sln
970 error gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
970 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
970 error gyp info spawn args [
970 error gyp info spawn args   'build/binding.sln',
970 error gyp info spawn args   '/nologo',
970 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
970 error gyp info spawn args ]
970 error gyp ERR! UNCAUGHT EXCEPTION
970 error gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
970 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:276:19)
970 error gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
970 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
970 error gyp ERR! System Windows_NT 10.0.19042
970 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\umren\\Documents\\Coding\\VueJS\\umren\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
970 error gyp ERR! cwd C:\Users\umren\Documents\Coding\VueJS\umren\node_modules\node-sass
970 error gyp ERR! node -v v15.5.1
970 error gyp ERR! node-gyp -v v3.8.0
970 error gyp ERR! This is a bug in `node-gyp`.
970 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
970 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
970 error Build failed with error code: 7
971 verbose exit 1
```

Any idea what might be the issue?
I tried reinstalling npm, vue, node-gyp, removed node_modules, reinstalled them, etc. I can't seem to fix the issue.

Thank you for the help.

**Comment by cclauss** [comment]
> error gyp ERR! node-gyp -v v3.8.0

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@3.8.0

vs. https://github.com/nodejs/node-gyp/releases

https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

---
Also, [`node-sass is deprecated`](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22) so we can not provide support.
