### ISSUE TITLE
Fails to build on macOS 12 (Monterey) & node@16

### ISSUE THREAD

**Issue by alexgurr** [nodejs/node-gyp#2476]
* **Node Version**:  16.6.1
* **Platform**: Darwin
* **Compiler**: 
```
Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: x86_64-apple-darwin21.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
* **Module**: 
```
node-pre-gyp install --fallback-to-build --library=static_library
```

This is run within a simple `yarn install` command on a create-react-app.

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
error /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments: 
Directory: /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@16.6.1 | darwin | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown/grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.3 and node@16.6.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
(node:21971) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alexgurr/Library/Caches/node-gyp/16.6.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/alexgurr/Library/Caches/node-gyp/16.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/alexgurr/Library/Caches/node-gyp/16.6.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/status_util.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_internal.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
../deps/grpc/src/core/lib/debug/stats_data.cc:284:5: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
    "requested the incoming call",
    ^
../deps/grpc/src/core/lib/debug/stats_data.cc:283:5: note: place parentheses around the string literal to silence warning
    "How many completion queues were checked looking for a CQ that had "
    ^
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.0.0
gyp ERR! command "/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node" "/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc
gyp ERR! node -v v16.6.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node /Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.0.0
node-pre-gyp ERR! command "/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node" "/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc
node-pre-gyp ERR! node -v v16.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.17.0

```

</details>

**Comment by cclauss** [comment]
> using Python version 2.7.16

Python 2 died on 1/1/2020 so please see https://github.com/nodejs/node-gyp#configuring-python-dependency to use Python 3 instead of 2.

**Comment by alexgurr** [comment]
It still fails, even with Python@3.9.6.

```
error /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@16.6.1 | darwin | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown/grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.3 and node@16.6.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v93-darwin-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | darwin | x64
gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
(node:27913) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/alexgurr/Library/Caches/node-gyp/16.6.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/alexgurr/Library/Caches/node-gyp/16.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/alexgurr/Library/Caches/node-gyp/16.6.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/status_util.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_internal.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
../deps/grpc/src/core/lib/debug/stats_data.cc:284:5: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
    "requested the incoming call",
    ^
../deps/grpc/src/core/lib/debug/stats_data.cc:283:5: note: place parentheses around the string literal to silence warning
    "How many completion queues were checked looking for a CQ that had "
    ^
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.0.0
gyp ERR! command "/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node" "/Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc
gyp ERR! node -v v16.6.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node /Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/src/node/extension_binary/node-v93-darwin-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.0.0
node-pre-gyp ERR! command "/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node" "/Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/alexgurr/Documents/GitHub/notmyturn/node_modules/grpc
node-pre-gyp ERR! node -v v16.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/alexgurr/.nvm/versions/node/v16.6.1/bin/node /Users/alexgurr/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin
```

**Comment by cclauss** [comment]
Thanks for the report!  How is [Xcode installed](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md)?

https://github.com/mapbox/node-pre-gyp is v1.0.5, not v1.0.3

https://github.com/nodejs/node-gyp/releases is v8.1.0, not v7.1.2
To upgrade, see https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by alexgurr** [comment]
I've upgraded using your link, but how do I upgrade the global node-pre-gyp version without setting a local resolved version in my project?

**Comment by cclauss** [comment]
Identical results after upgrading node-gyp?

I have little knowledge of node-pre-gyp...  You could open an issue on that repo.

**Comment by cclauss** [comment]
Did you find a solution?

**Comment by alexgurr** [comment]
Nope. Not for this exact issue. Turns out though, one of my dependencies had another on this version of pre gyp. When I upgraded the library it used a newer version.

**Comment by handhikadj** [comment]
@alexgurr how do you solve this? I'm also getting this now

**Comment by cclauss** [comment]
What is the text of the `gyp info using node-gyp@` line in your log?

**Comment by rilian** [comment]
i'm getting exactly same issue as @alexgurr posted here https://github.com/nodejs/node-gyp/issues/2476#issuecomment-894738949 on a MacOS with M1 chip but with **nodejs v14.x**

@alexgurr did you by chance find a solution already ?.. thank you!

**Comment by rilian** [comment]
upd: i was able to solve this issue by adding these packages

```
    "@grpc/grpc-js": "^1.4.4",
    "@mapbox/node-pre-gyp": "^1.0.7",
```
