### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by Joblyn** [nodejs/node-gyp#2479]
This error is thrown when I run `yarn app` on my linux system
In scripts in my package.json file 
"scripts": { "app": "parcel client/index.html --out-dir client/dist" }

```yarn run v1.22.5
$ parcel client/index.html --out-dir client/dist
(node:19038) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build/Debug/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build/Release/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/out/Debug/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/Debug/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/out/Release/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/Release/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build/default/deasync.node
 → /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/compiled/14.5.0/linux/x64/deasync.node
    at bindings (/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/index.js:30:31)
    at Module._compile (/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/parcel/src/utils/syncPromise.js:1:79)
    at Module._compile (/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

Any help is appreciated

**Comment by cclauss** [comment]
This is a _question_, not a critique: Given that `gyp` does not appear in the error log, is this a `node-gyp` issue?
