### ISSUE TITLE
Error on yarn install

### ISSUE THREAD

**Issue by Joblyn** [nodejs/node-gyp#2480]
Trying to run `yarn install` on my full-stack on Linux machine, but throws the following error log

```
error /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.5.0 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/joblyn/.cache/node-gyp/14.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/joblyn/.cache/node-gyp/14.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/joblyn/.cache/node-gyp/14.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
g++: error: courses: No such file or directory
g++: error: repos/fullstack-graphql/node_modules/node-addon-api: No such file or directory
make: *** [deasync.target.mk:109: Release/obj.target/deasync/src/deasync.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stackmake: Leaving directory '/home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync/build'
     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-80-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/joblyn/Desktop/frontendmasters courses repos/fullstack-graphql/node_modules/deasync
gyp ERR! node -v v14.5.0
```

Any help is appreciated

**Comment by cclauss** [comment]
> gyp info using node-gyp@5.1.0

Current is @8.1.0 -->
https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

Python 2 died on 1/1/2020

**Comment by Joblyn** [comment]
Alright works, thanks.
