### ISSUE TITLE
Package 'xi', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by BrunoQuaresma** [nodejs/node-gyp#2513]
I'm using a Docker image to install a dependency that uses node-gyp, but I'm facing the following issue:

```
> [7/9] RUN npm install:                                                                                                                                                                
#11 1.069 npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!  
#11 11.83                                                                                                                                                                                
#11 11.83 > canvas@2.8.0 install /usr/src/app/node_modules/canvas
#11 11.83 > node-pre-gyp install --fallback-to-build
#11 11.83 
#11 12.48 node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-musl-x64.tar.gz 
#11 12.48 node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.18.0 (node-v83 ABI, musl) (falling back to source compile with node-gyp) 
#11 12.48 node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-musl-x64.tar.gz 
#11 15.94 make: Entering directory '/usr/src/app/node_modules/canvas/build'
#11 15.95   SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
#11 15.96   COPY Release/canvas-postbuild.node
#11 15.97   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
#11 16.89   CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
#11 17.78   CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
#11 18.87   CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
#11 19.91   CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
#11 20.85   CXX(target) Release/obj.target/canvas/src/Backends.o
#11 21.68   CXX(target) Release/obj.target/canvas/src/Canvas.o
#11 24.50   CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
#11 25.57   CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
#11 26.66   CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
#11 30.50   CXX(target) Release/obj.target/canvas/src/closure.o
#11 31.38   CXX(target) Release/obj.target/canvas/src/color.o
#11 32.32   CXX(target) Release/obj.target/canvas/src/Image.o
#11 34.02   CXX(target) Release/obj.target/canvas/src/ImageData.o
#11 35.03   CXX(target) Release/obj.target/canvas/src/init.o
#11 35.88   CXX(target) Release/obj.target/canvas/src/register_font.o
#11 36.11   SOLINK_MODULE(target) Release/obj.target/canvas.node
#11 36.17   COPY Release/canvas.node
#11 36.17 make: Leaving directory '/usr/src/app/node_modules/canvas/build'
#11 36.19 
#11 36.19 > gl@4.9.2 install /usr/src/app/node_modules/gl
#11 36.19 > prebuild-install || node-gyp rebuild
#11 36.19 
#11 36.70 prebuild-install WARN install No prebuilt binaries found (target=14.18.0 runtime=node arch=x64 libc=musl platform=linux)
#11 37.19 Package xi was not found in the pkg-config search path.
#11 37.19 Perhaps you should add the directory containing `xi.pc'
#11 37.19 to the PKG_CONFIG_PATH environment variable
#11 37.19 Package 'xi', required by 'virtual:world', not found
#11 37.19 gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
#11 37.20 gyp ERR! configure error 
#11 37.20 gyp ERR! stack Error: `gyp` failed with exit code: 1
#11 37.20 gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
#11 37.20 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#11 37.20 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
#11 37.20 gyp ERR! System Linux 5.10.25-linuxkit
#11 37.20 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#11 37.20 gyp ERR! cwd /usr/src/app/node_modules/gl
#11 37.20 gyp ERR! node -v v14.18.0
#11 37.20 gyp ERR! node-gyp -v v5.1.0
#11 37.21 gyp ERR! not ok 
#11 37.67 npm WARN tweetpik-video@1.0.0 No description
#11 37.68 npm WARN tweetpik-video@1.0.0 No repository field.
#11 37.68 
#11 37.71 npm ERR! code ELIFECYCLE
#11 37.71 npm ERR! errno 1
#11 37.72 npm ERR! gl@4.9.2 install: `prebuild-install || node-gyp rebuild`
#11 37.72 npm ERR! Exit status 1
#11 37.72 npm ERR! 
#11 37.72 npm ERR! Failed at the gl@4.9.2 install script.
#11 37.72 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#11 37.76 
#11 37.76 npm ERR! A complete log of this run can be found in:
#11 37.76 npm ERR!     /root/.npm/_logs/2021-10-06T15_10_24_223Z-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
```

here is is the Dockerfile
```
FROM  node:14-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY tsconfig.json ./

# Necessary to run editly and node-gyp
RUN apk add  --no-cache ffmpeg
RUN apk add --no-cache --virtual .gyp \
  build-base \
  python \
  make \
  g++ \
  pkgconfig \
  cairo-dev \
  jpeg-dev \
  pango-dev \
  giflib-dev
RUN npm install
RUN apk del .gyp
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]

```

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v5.1.0

The current release is v8.2.0 https://github.com/nodejs/node-gyp/releases

**Comment by richardlau** [comment]
There's nothing we can do in this project to help. 

Something in your app is using gl (https://www.npmjs.com/package/gl) and it appears you don't have the required dependencies installed (https://www.npmjs.com/package/gl#system-dependencies) for compiling from source. If you don't want to compile from source it looks like gl may provide prebuilt binaries so you could take it up with that project as to whether prebuilt binaries could be provided for the Node.js 14 alpine container.

**Comment by BrunoQuaresma** [comment]
@richardlau I see, I'm very sorry for that.
