### ISSUE TITLE
v8.3.0 install error

### ISSUE THREAD

**Issue by coder0107git** [nodejs/node-gyp#2529]
* **Node Version**: 17.0.0
* **Platform**: ChromeOS (Linux penguin 5.4.131-16049-gc688e114d34e &#35; 1 SMP PREEMPT Sun Sep 19 21:16:20 PDT 2021 x86_64 GNU/Linux)
* **Compiler**: 8.3.0
* **Module**: node-red-contrib-xterm

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
19 Oct 17:02:23 - [info] Installing module: node-red-contrib-xterm, version: 1.0.0
19 Oct 17:02:39 - [warn] Installation of module node-red-contrib-xterm failed:
19 Oct 17:02:39 - [warn] ------------------------------------------
19 Oct 17:02:39 - [warn] npm ERR! code 1
npm ERR! path /home/user/.node-red/node_modules/node-pty-prebuilt-multiarch
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node scripts/install.js
npm ERR! make: Entering directory '/home/user/.node-red/node_modules/node-pty-prebuilt-multiarch/build'
npm ERR!   CXX(target) Release/obj.target/pty/src/unix/pty.o
npm ERR! make: Leaving directory '/home/user/.node-red/node_modules/node-pty-prebuilt-multiarch/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@17.0.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/user/.config/nvm/versions/node/v17.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/user/.node-red/node_modules/node-pty-prebuilt-multiarch/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/user/.config/nvm/versions/node/v17.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/user/.cache/node-gyp/17.0.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/17.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/user/.config/nvm/versions/node/v17.0.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/17.0.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/user/.node-red/node_modules/node-pty-prebuilt-multiarch',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /home/user/.cache/node-gyp/17.0.0/include/node/v8-object.h:10,
npm ERR!                  from /home/user/.cache/node-gyp/17.0.0/include/node/v8-array-buffer.h:13,
npm ERR!                  from /home/user/.cache/node-gyp/17.0.0/include/node/v8.h:25,
npm ERR!                  from /home/user/.cache/node-gyp/17.0.0/include/node/node.h:63,
npm ERR!                  from ../../nan/nan.h:58,
npm ERR!                  from ../src/unix/pty.cc:20:
npm ERR! /home/user/.cache/node-gyp/17.0.0/include/node/v8-persistent-handle.h:10:10: fatal error: v8-weak-callback-info.h: No such file or directory
npm ERR!  #include "v8-weak-callback-info.h"  // NOLINT(build/include_directory)
npm ERR!           ^~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [pty.target.mk:113: Release/obj.target/pty/src/unix/pty.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/user/.config/nvm/versions/node/v17.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.4.131-16049-gc688e114d34e
npm ERR! gyp ERR! command "/home/user/.config/nvm/versions/node/v17.0.0/bin/node" "/home/user/.config/nvm/versions/node/v17.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/user/.node-red/node_modules/node-pty-prebuilt-multiarch
npm ERR! gyp ERR! node -v v17.0.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-10-19T23_02_39_514Z-debug.log

19 Oct 17:02:39 - [warn] ------------------------------------------
Error: Install failed
    at /home/user/.config/nvm/versions/node/v17.0.0/lib/node_modules/node-red/node_modules/@node-red/registry/lib/installer.js:245:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
19 Oct 17:02:39 - [error] Error: Install failed
```

</details>

I also encountered this problem with any nodejs package that requires `node-gyp`. Some of the packages I encountered that had this problem was `robotjs`, `node-pty-prebuilt-multiarch`, and `node-pty`.

I was able to fix this issue by going to [https://v8.github.io/api/head/files.html](https://v8.github.io/api/head/files.html) and searching for the included file that couldn't be found (for example `v8-persistent-handle.h`). I then clicked the link to the file then from there I clicked the link to the missing file (for example `v8-weak-callback-info.h`). I then copied and pasted into a new file (in my case it would be at `/home/user/.cache/node-gyp/17.0.0/include/node/v8-weak-callback-info.h`) with the correct name.

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@8.2.0

v8.2.0, not v8.3.0

**Comment by richardlau** [comment]
This is https://github.com/nodejs/Release/issues/704 and an issue with the headers for Node.js 17.0.0. Being addressed 
by https://github.com/nodejs/node/pull/40526.
