### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by coolbossinator** [nodejs/node-gyp#2551]
* **Node Version**: `Node: v10.14.1` and `NPM: 6.4.1`
* **Platform**: `Windows 10`
* **Compiler**: `MS Build tools 2017`
* **Issue**:

I tried to install a package using node-gyp and here is my issue:
```
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jwjoh\\AppData\\Roaming\\nvm\\v10.14.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd S:\Dyno-Discord-Bot\dyno-master\node_modules\bufferutil
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN ws@8.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
```

Verbose Log:
```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v10.14.1

```

</details>

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.8.0

https://github.com/nodejs/node-gyp/releases

https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md
