### ISSUE TITLE
Getting ERR! Error: Command failed: node-gyp rebuild --jobs max. Error: Could not find any Visual Studio installation to use.

### ISSUE THREAD

**Issue by iamlivinsunny** [nodejs/node-gyp#2564]
Complete log
```
C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )  else (node "C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files"
gyp ERR! find VS - will only use this version
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
gyp ERR! find VS installation cannot be used.
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\TestingAccount\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
ERR! Error: Command failed: node-gyp rebuild --jobs max
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files"
gyp ERR! find VS - will only use this version
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
gyp ERR! find VS installation cannot be used.
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\TestingAccount\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\TestingAccount\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by iamlivinsunny** [comment]
OS : Windows 10
Error getting while installing opencv4nodejs

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v5.1.0

Please upgrade to https://github.com/nodejs/node-gyp/releases using https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by iamlivinsunny** [comment]
Thank you for the response. I have changed the npm-gyp refernce and ran the installation command again. But still getting the same error.

C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )  else (node "C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files"
gyp ERR! find VS - will only use this version
gyp ERR! find VS checking VS2022 (17.0.31919.166) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v143
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
gyp ERR! find VS installation cannot be used.
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
ERR! Error: Command failed: node-gyp rebuild --jobs max
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files"
gyp ERR! find VS - will only use this version
gyp ERR! find VS checking VS2022 (17.0.31919.166) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v143
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
gyp ERR! find VS installation cannot be used.
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by iamlivinsunny** [comment]
The version of npm-gyp is now v8.4.1. But the VS is not getting detected.
I have vs 2017 installed under : C:\Program Files (x86)\Microsoft Visual Studio\2017
                                                  C:\Program Files\Microsoft Visual Studio\2017
2019 installed under : C:\Program Files (x86)\Microsoft Visual Studio\2019
2022 installed under : C:\Program Files\Microsoft Visual Studio\2022\Community

**Comment by cclauss** [comment]
The often-repeated line `msvs_version does not match this version` seems to be the problem but I am not a Windows user.

**Comment by iamlivinsunny** [comment]
![image](https://user-images.githubusercontent.com/71168111/144738425-ab9c22b5-355b-4997-9131-de13c574870b.png)


> The often-repeated line `msvs_version does not match this version` seems to be the problem but I am not a Windows user.

**Comment by iamlivinsunny** [comment]
The version gets picked from the .npmrc file. Not sure it cant detect the Visual Studio.

**Comment by iamlivinsunny** [comment]
![image](https://user-images.githubusercontent.com/71168111/144738470-be34fddd-02d8-417b-a942-aa794f053644.png)
![image](https://user-images.githubusercontent.com/71168111/144738481-6f5f7a06-82c4-4e40-b4ef-5f6436d9f4f2.png)
![image](https://user-images.githubusercontent.com/71168111/144738496-eb889ff5-9aab-405d-8c5c-08f6852d1182.png)
![image](https://user-images.githubusercontent.com/71168111/144738506-76ce2506-0ae2-4997-8a6b-026fe8fa6d53.png)
 Have these installations of VS in the system.

**Comment by iamlivinsunny** [comment]
Are you aware of which Visual Studio installation file node-gyp looking for.
![image](https://user-images.githubusercontent.com/71168111/144739307-58248b48-1633-4c8e-921f-762b018461ca.png
If we know the path "this.configPath" node-gyp looking for the we can try to set that manually and run to check whether it will work or not

**Comment by iamlivinsunny** [comment]
findVisualStudio: function findVisualStudio() {
    this.configVersionYear = null
    this.configPath = null
    if (this.configMsvsVersion) {
      this.addLog('msvs_version was set from command line or npm config')
      if (this.configMsvsVersion.match(/^\d{4}$/)) {
        this.configVersionYear = parseInt(this.configMsvsVersion, 10)
        this.addLog(
          `- looking for Visual Studio version ${this.configVersionYear}`)
      } else {
        this.configPath = path.resolve(this.configMsvsVersion)
        this.addLog(
          `- looking for Visual Studio installed in "${this.configPath}"`)
      }
    } else {
      this.addLog('msvs_version not set from command line or npm config')
    }


If we know the path "this.configPath" node-gyp looking for (In the file E:\Software\npm-gyp\node-gyp-8.4.1\lib\find-visualstudio) the we can try to set that manually and run to check whether it will work or not

**Comment by cclauss** [comment]
Look thru your log output above for lines that start with `gyp ERR! find VS checking VS20` to see all the versions that it is finding.  The problem is that after finding them, the code does not like their `msvs_version`.

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/docs/Common-issues.md

**Comment by iamlivinsunny** [comment]
I have installed VS from location mentioned in the above link and set the version as 2017 but for some reason still not picking the vs installation.

**Comment by iamlivinsunny** [comment]
![image](https://user-images.githubusercontent.com/71168111/144746589-b570fafa-bf26-43ac-bc63-7ca32adccafe.png)

The "envVcInstallDir" gets the value "c://Program files" and the "vsPath "  gets the actual installation path. The because of this 
the "return true" never gets execute. That is why the visual studio installation is not getting detected. On hard coding the path 
"MSBuild.exe" is getting detected.

**Comment by iamlivinsunny** [comment]
But still fails with below error.
`C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )  else (node "C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )
C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj(21,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
ERR! Error: Command failed: node-gyp rebuild --jobs max
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok`

**Comment by iamlivinsunny** [comment]
Any one know how to sort this out

**Comment by iamlivinsunny** [comment]
Anyone know whether this package require any additional tools to run in the AMD based system. Why I am asking because I just installed the opencv4nodejs (Which uses node-gyp) on my old intel based system just now. Not sure if it works. But the installation completed without error. So confuse if the issue is with my Ryzen processor. Both the systems have windows 10 installed and intel one(successful) have node v14.16.1 and amd one have 14.15.4. Not much difference.

**Comment by kingdevnl** [comment]
I'm getting the same error when installing @tensorflow/tfjs-node

**Comment by NorVirae** [comment]
> But still fails with below error.
> 
> ```
> C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )  else (node "C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )
> C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj(21,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> gyp ERR! System Windows_NT 10.0.19042
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
> gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
> gyp ERR! node -v v14.15.4
> gyp ERR! node-gyp -v v8.4.1
> gyp ERR! not ok
> ERR! Error: Command failed: node-gyp rebuild --jobs max
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> gyp ERR! System Windows_NT 10.0.19042
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TestingAccount\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max"
> gyp ERR! cwd C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\opencv4nodejs
> gyp ERR! node -v v14.15.4
> gyp ERR! node-gyp -v v8.4.1
> gyp ERR! not ok
> ```

guys am Having the same Issue on an Intel processor, amd64  have installed vs version but still can't wrap my head around why its not detecting visual studio, like i therer no human that has got a clue on how to solve this issue.

I had to re-install my OS just to make sure i do not have any conflicting  programs. need help.

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v8.4.1

https://github.com/nodejs/node-gyp/releases

**Comment by she-WritesCode** [comment]
Had a similar issue when installing `danfojs-node` which is dependent on `@tensorflow/tfjs-node`. This is how I fixed the issue, 

1. Went into `node_modules/@tensorflow/tfjs-node` directory and ran the command that was failing, in the case of this particular error log in this issue, it would be 
```cmd
"C:\Program Files\nodejs\node.exe" "C:\Users\TestingAccount\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--jobs" "max"
```
In my case, it mentioned that a particular SDK was missing `The Windows SDK version 10.0.18362.0 was not found.`


2. I modified the installation of VS build tools 2019 to contain the missing SDK, using Visual studio installer, I think finding the SDK on the [Microsoft archive](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/) will give an equivalent result. I also had to remove any other SDK so that `node-gyp` can find the particular SDK it was looking for. `npm install` now works

This StackOverflow answer was a guide https://stackoverflow.com/a/50606326

**Comment by cclauss** [comment]
Please use the updated Windows setup... https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-windows

**Comment by Eysen-ZZT** [comment]
![image](https://github.com/nodejs/node-gyp/assets/64021941/8e51c7b4-4e17-4148-b45b-6c1859bbf4a8)
试试把visual studio community 的C++桌面开发的这几项勾选上，保险起见全部勾选上也行，感觉应该是windows sdk造成的问题
