### ISSUE TITLE
node-gyp fins build-tools and vs-studio 2017/ 2019 but doesn't use them

### ISSUE THREAD

**Issue by LuvbCa** [nodejs/node-gyp#2569]
* **Node Version**: 17.2.0
* **Platform**:  Microsoft Windows 11 Pro Insider Preview / 10.0.22509 Nicht zutreffend Build 22509 / x64-based PC
* **Compiler**: 16.8.3.61104
* **Module**: isolated-vm

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
71 verbose stack Error: command failed
71 verbose stack     at ChildProcess.<anonymous> (C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
71 verbose stack     at ChildProcess.emit (node:events:390:28)
71 verbose stack     at maybeClose (node:internal/child_process:1062:16)
71 verbose stack     at Socket.<anonymous> (node:internal/child_process:448:11)
71 verbose stack     at Socket.emit (node:events:390:28)
71 verbose stack     at Pipe.<anonymous> (node:net:687:12)
72 verbose pkgid isolated-vm@4.3.6
73 verbose cwd C:\Users\lmima\Desktop\ownEditor\src-electron
74 verbose Windows_NT 10.0.22509
75 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "isolated-vm"
76 verbose node v17.2.0
77 verbose npm  v8.1.4
78 error code 1
79 error path C:\Users\lmima\Desktop\ownEditor\src-electron\node_modules\isolated-vm
80 error command failed
81 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild --release -j 4
82 error gyp info it worked if it ends with ok
82 error gyp info using node-gyp@8.4.0
82 error gyp info using node@17.2.0 | win32 | x64
82 error gyp info find Python using Python version 3.9.1 found at "C:\Python39\python.exe"
82 error gyp ERR! find VS
82 error gyp ERR! find VS msvs_version was set from command line or npm config
82 error gyp ERR! find VS - looking for Visual Studio version 2019
82 error gyp ERR! find VS running in VS Command Prompt, installation path is:
82 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
82 error gyp ERR! find VS - will only use this version
82 error gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
82 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
82 error gyp ERR! find VS - found "Visual Studio C++ core features"
82 error gyp ERR! find VS - found VC++ toolset: v142
82 error gyp ERR! find VS - found Windows SDK: 10.0.18362.0
82 error gyp ERR! find VS - does not match this Visual Studio Command Prompt
82 error gyp ERR! find VS checking VS2019 (16.8.30907.101) found at:
82 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
82 error gyp ERR! find VS - found "Visual Studio C++ core features"
82 error gyp ERR! find VS - found VC++ toolset: v142
82 error gyp ERR! find VS - found Windows SDK: 10.0.18362.0
82 error gyp ERR! find VS - does not match this Visual Studio Command Prompt
82 error gyp ERR! find VS checking VS2017 (15.9.28307.1585) found at:
82 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
82 error gyp ERR! find VS - found "Visual Studio C++ core features"
82 error gyp ERR! find VS - found VC++ toolset: v141
82 error gyp ERR! find VS - found Windows SDK: 10.0.17763.0
82 error gyp ERR! find VS - msvs_version does not match this version
82 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
82 error gyp ERR! find VS looking for Visual Studio 2015
82 error gyp ERR! find VS - not found
82 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
82 error gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
82 error gyp ERR! find VS installation cannot be used.
82 error gyp ERR! find VS
82 error gyp ERR! find VS **************************************************************
82 error gyp ERR! find VS You need to install the latest version of Visual Studio
82 error gyp ERR! find VS including the "Desktop development with C++" workload.
82 error gyp ERR! find VS For more information consult the documentation at:
82 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
82 error gyp ERR! find VS **************************************************************
82 error gyp ERR! find VS
82 error gyp ERR! configure error
82 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
82 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
82 error gyp ERR! stack     at C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
82 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
82 error gyp ERR! stack     at C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
82 error gyp ERR! stack     at C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
82 error gyp ERR! stack     at C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
82 error gyp ERR! stack     at C:\Users\lmima\AppData\Roaming\nvm\v17.2.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
82 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
82 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
82 error gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
82 error gyp ERR! System Windows_NT 10.0.22509
82 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lmima\\AppData\\Roaming\\nvm\\v17.2.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release" "-j" "4"
82 error gyp ERR! cwd C:\Users\lmima\Desktop\ownEditor\src-electron\node_modules\isolated-vm
82 error gyp ERR! node -v v17.2.0
82 error gyp ERR! node-gyp -v v8.4.0
82 error gyp ERR! not ok
83 verbose exit 1

```

</details>

So as the logs suggest node-gyp finds VS-Studio 2017 / 2019 and VS-Studio build-tools 2019 but it doesn't use them for some reason.
I tried to install the windows 11 sdk but it doesn't fix my issue in any way. I don't think this problem is related to the insider version 'm currently using but i could be wrong. (why should it affect the compilation?)

thanks in advance :)

**Comment by LuvbCa** [comment]
tried installing VS-Studio 2022 with C++ Build Tools no effect
