### ISSUE TITLE
Can't run node-gyp configure build

### ISSUE THREAD

**Issue by Mohamed-Elzohary** [nodejs/node-gyp#2570]
* **Node Version**:  node v12.22.7 and npm v6.14.15
* **Platform**: Ubuntu 18.04.6 LTS
* **Compiler**: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
* **Module**: Can't run node-gyp configure build

```
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@12.22.7 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/project/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/12.22.7/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.22.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.22.7/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/project',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /home/ubuntu/project) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-1060-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/ubuntu/project
gyp ERR! node -v v12.22.7
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok


```

**Comment by georzaza** [comment]
Ι'm having a similar issue @cclauss. Try this:
https://stackoverflow.com/questions/42638918/cannot-npm-install-due-to-node-gyp-binding-gyp-not-found

**Comment by Mohamed-Elzohary** [comment]
I added `binding.gyp` file:

```
{
  'targets': [
    {
      'target_name': 'addon',
      'win_delay_load_hook': 'false',
      'include_dirs': ['<!(node -e "require(\'nan\')")'],
      'sources': [
        'src/compat-inl.h',
        'src/compat.h',
        'src/heapdump-posix.h',
        'src/heapdump-win32.h',
        'src/heapdump.cc',
      ],
    }
  ]
}

```

and the Error is:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@12.22.8 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/project/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/12.22.8/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.22.8',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.22.8/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/project',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu/project/build'
make: *** No rule to make target 'Release/obj.target/addon/src/heapdump.o', needed by 'Release/obj.target/addon.node'.  Stop.
make: Leaving directory '/home/ubuntu/project/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-1060-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/ubuntu/project
gyp ERR! node -v v12.22.8
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
```

**Comment by Mohamed-Elzohary** [comment]
Solution: 
`binding.gyp` file:

```
{
  'targets': [
    {
      'target_name': 'addon',
      'win_delay_load_hook': 'false',
      'include_dirs': ['<!(node -e "require(\'nan\')")'],
      'sources': [
        'src/compat-inl.h',
        'src/compat.h',
        'src/heapdump-posix.h',
        'src/heapdump-win32.h',
        'src/heapdump.cc',
      ],
    }
  ]
}
```

I
