### ISSUE TITLE
Invalid or unexpected token: v=process.versions.node.split(.)

### ISSUE THREAD

**Issue by jdc-cunningham** [nodejs/node-gyp#2575]
* **Node Version**:
v14.15.3 and 6.14.9 
* **Platform**:
Windows 10 Pro, 10.0.19044 N/A Build 19044 x64
* **Compiler**: 
2019 current, build engine 16.8.3+...
* **Module**: 
Calipers with poppler-simple
<details><summary>Verbose output (from npm or node-gyp):</summary>

```
>yarn add calipers calipers-pdf
error C:\Users\Green\DirA\DirB\my-api\node_modules\poppler-simple: Command failed.
Exit code: 1
Command: (node-gyp rebuild) || (exit 1)
Arguments:
Directory: C:\Users\Green\DirA\DirB\my-api\node_modules\poppler-simple
Output:
C:\Users\Green\DirA\DirB\my-api\node_modules\poppler-simple>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Green\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@14.15.3 | win32 | x64
gyp info find Python using Python version 3.9.1 found at "C:\Python39\python.exe"
gyp info find VS using VS2019 (16.8.31005.135) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Green\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Green\\DirA\\DirB\\my-api\\node_modules\\poppler-simple\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Green\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Green\\AppData\\Local\\node-gyp\\Cache\\14.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Green\\AppData\\Local\\node-gyp\\Cache\\14.15.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Green\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Green\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Green\\DirA\\DirB\\my-api\\node_modules\\poppler-simple',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Green\\DirA\\DirB\\my-api\\node_modules\\poppler-simple\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
[eval]:1
'v=process.versions.node.split(.);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3
gyp: Call to 'node -pe 'v=process.versions.node.split("."); v[0];'' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Green\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Green\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Green\DirA\DirB\my-api\node_modules\poppler-simple
gyp ERR! node -v v14.15.3
```

</details>

Running this command `node -pe 'v=process.versions.node.split("."); v[0];` in a terminal does output 14.

**Comment by rvagg** [comment]
Is this your code, or in an addon you're trying to compile (poppler-simple?)? This command has been designed for running in bash but you're running it on Windows. The command could probably be simplified to either `node -pe 'process.versions.node.split(".")[0]'` or `node -e 'console.log(process.versions.node.split(".")[0])'`.
Either way, you'll need to take it up with the addon author and get the script fixed in their binding.gyp.
