### ISSUE TITLE
rebuild error

### ISSUE THREAD

**Issue by hakuna-tata** [nodejs/node-gyp#2591]
## stack information

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3009, in Load
    LoadTargetBuildFile(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 424, in LoadTargetBuildFile
    ProcessToolsetsInDict(build_file_data)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 336, in ProcessToolsetsInDict
    toolsets = target.get("toolsets", ["target"])
AttributeError: 'str' object has no attribute 'get' while trying to load binding.gyp

## my  binding.gyp config
```
{
  "targets": {
    "target_name": "first-addon",
    "sources": ["index.cc"],
  }
}
```

**Comment by cclauss** [comment]
Please provide the command typed and the FULL stack trace.

**Comment by hakuna-tata** [comment]
## full stack trace
**gyp-node rebuild**

gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liujianfeng/Work/test-pkg/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liujianfeng/Library/Caches/node-gyp/16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/liujianfeng/Library/Caches/node-gyp/16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/liujianfeng/Library/Caches/node-gyp/16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/liujianfeng/Work/test-pkg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3009, in Load
    LoadTargetBuildFile(
liujianfeng@FFFXUE test-pkg % node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liujianfeng/Work/test-pkg/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liujianfeng/Library/Caches/node-gyp/16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/liujianfeng/Library/Caches/node-gyp/16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/liujianfeng/Library/Caches/node-gyp/16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/liujianfeng/Work/test-pkg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3009, in Load
    LoadTargetBuildFile(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 424, in LoadTargetBuildFile
    ProcessToolsetsInDict(build_file_data)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 336, in ProcessToolsetsInDict
    toolsets = target.get("toolsets", ["target"])
AttributeError: 'str' object has no attribute 'get' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/liujianfeng/Work/test-pkg
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by hakuna-tata** [comment]
## FULL stack trace

**node-gyp rebuild**

gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liujianfeng/Work/test-pkg/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liujianfeng/Library/Caches/node-gyp/16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/liujianfeng/Library/Caches/node-gyp/16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/liujianfeng/Library/Caches/node-gyp/16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/liujianfeng/Work/test-pkg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3009, in Load
    LoadTargetBuildFile(
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 424, in LoadTargetBuildFile
    ProcessToolsetsInDict(build_file_data)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 336, in ProcessToolsetsInDict
    toolsets = target.get("toolsets", ["target"])
AttributeError: 'str' object has no attribute 'get' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/liujianfeng/Work/test-pkg
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by hakuna-tata** [comment]
It's a **configure** error，not **build** error。But my **binding.gyp config** is configured according to the official website

**Comment by hakuna-tata** [comment]
> Please provide the command typed and the FULL stack trace.

It should not be a version problem, I hope it can be solved as soon as possible

**Comment by hakuna-tata** [comment]
> Please provide the command typed and the FULL stack trace.

Not a **build** error, its **configure** error。

**Comment by cclauss** [comment]
Duplicate of #1062 ?

**Comment by hakuna-tata** [comment]
> Duplicate of #1062 ?

Thank you
