### ISSUE TITLE
unable to run npm i - node-gyp still at v3.8.0 even after updating

### ISSUE THREAD

**Issue by NealWilxite** [nodejs/node-gyp#2602]
* **Node Version**: v16.13.2
* **Platform**: Microsoft Windows 11 Pro, Microsoft Windows 11 Pro, x64-based PC
* **Compiler**:  `msbuild /version & cl` doesnt work. Have installed Visual Build Tools 2017, 2019 and Visual Studio Comminity 2022
* **Module**:  just ran `npm i` but also stalls with `npm i --save @fortawesome/fontawesome-svg-core`

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
npm ERR! code 1
npm ERR! path C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\NealW\Development\Peters-Schools\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\NealW\Development\Peters-Schools\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\NealW\Development\Peters-Schools\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2.7 Error: not found: python2.7
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\NealW\Development\Peters-Schools\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\NealW\Development\Peters-Schools\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\NealW\Development\Peters-Schools\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python2.7". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
npm ERR! gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.2
npm ERR! gyp verb command install [ '16.13.2' ]
npm ERR! gyp verb install input version string "16.13.2"
npm ERR! gyp verb install installing version: 16.13.2
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.2
npm ERR! gyp verb build dir attempting to create "build" dir: C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass\build
npm ERR! gyp verb find vs2017 Found installation at: C:\Program Files\Microsoft Visual Studio\2022\Community
npm ERR! gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
npm ERR! gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
npm ERR! gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
npm ERR! gyp verb find vs2017   - Some required components are missing, not using this installation
npm ERR! gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
npm ERR! gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
npm ERR! gyp verb find vs2017   - Using this installation with Windows 10 SDK
npm ERR! gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass\build\config.gypi
npm ERR! (node:30260) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\NealW\\.node-gyp\\16.13.2\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\NealW\\.node-gyp\\16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\NealW\\.node-gyp\\16.13.2\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir C:\Users\NealW\.node-gyp\16.13.2
npm ERR! gyp verb found first Solution file build/binding.sln
npm ERR! gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\NealW\\Development\\Peters-Schools\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\NealW\Development\Peters-Schools\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Build failed with error code: 7
```

</details>

I have followed the instructions in these articles

https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

https://github.com/nodejs/node-gyp/blob/master/docs/Force-npm-to-use-global-node-gyp.md

I have Python 2 installed (`python --version` => v2.7.18)

`node-gyp -v` => v8.4.1

**Comment by cclauss** [comment]
Python 2 died 758 days ago on 1/1/2020 so its use is no longer supported as discussed in README.md.  The log output clearly states that node-gyp v3.0.8 is being used so do not expect it to work.  The docs at the URLs quoted above should get current node-gyp installed.  They also explain why what `node-gyp -v` returns is irrelevant.

**Comment by NealWilxite** [comment]
Hi. Thanks but I managed to sort it. I just deleted all node_modules. Doh!
