### ISSUE TITLE
Error during node-gyp rebuild Windows 10

### ISSUE THREAD

**Issue by steelx** [nodejs/node-gyp#2627]
Trying to rebuild I get follow error on Windows 10. GTK is at `C:\GTK`

**gyp: binding.gyp not found (cwd: C:\Windows\System32) while trying to load binding.gyp**

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.0.5
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.13.2 | win32 | x64
gyp info find Python using Python version 3.10.0 found at "C:\Python310\python.exe"
gyp info find VS using VS2022 (17.0.32112.339) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\ProgramData\\nvm\\v16.13.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Windows\\System32\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\ProgramData\\nvm\\v16.13.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ajink\\AppData\\Local\\node-gyp\\Cache\\16.13.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ajink\\AppData\\Local\\node-gyp\\Cache\\16.13.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\ProgramData\\nvm\\v16.13.2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\ajink\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Windows\\System32',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Windows\\System32\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Windows\System32) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\System32
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok

C:\Windows\System32>
```

* **Node Version**:
* node 16.13.2
* npm 8.1.2
* **Platform**:  Windows 10 Pro
* **Compiler**: MSVC 2022
* **Module**: node-gyp

```
C:\Windows\System32>npm --verbose
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@8.1.2
npm info using node@v16.13.2
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\ProgramData\nvm\v16.13.2\node_modules\npm\npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:C:\Windows\System32\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\ajink\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 10ms
npm timing npm:load:configload Completed in 10ms
npm timing npm:load:setTitle Completed in 1ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:cleanupLog Completed in 1ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 25ms
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term> (in a browser)
npm help npm       more involved overview (in a browser)

All commands:

    access, adduser, audit, bin, bugs, cache, ci, completion,
    config, dedupe, deprecate, diff, dist-tag, docs, doctor,
    edit, exec, explain, explore, find-dupes, fund, get, help,
    hook, init, install, install-ci-test, install-test, link,
    ll, login, logout, ls, org, outdated, owner, pack, ping,
    pkg, prefix, profile, prune, publish, rebuild, repo,
    restart, root, run-script, search, set, set-script,
    shrinkwrap, star, stars, start, stop, team, test, token,
    uninstall, unpublish, unstar, update, version, view, whoami

Specify configs in the ini-formatted file:
    C:\Users\ajink\.npmrc
or on the command line via: npm <command> --key=value

More configuration info: npm help config
Configuration fields: npm help 7 config

npm@8.1.2 C:\ProgramData\nvm\v16.13.2\node_modules\npm
npm verb exit 0
npm timing npm Completed in 221ms
npm verb code 1
```

</details>

**Comment by steelx** [comment]
more info. Running via Teriminal and editing script to show info.

```
   ajink@LAPTOP-018O850F ~ ❯❯❯ node-gyp configure --msvs_version=2022
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.13.2 | win32 | x64
gyp info find Python using Python version 3.10.0 found at "C:\Python310\python.exe"
Ajinkya was here
[
  {
    path: 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community',
    version: '17.1.32210.238',
    packages: [
      'Microsoft.VisualStudio.Component.VC.14.30.17.0.x86.x64',
      'Microsoft.VC.14.30.17.0.Tools.HostX64.TargetX86',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX64.TargetX86',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX64.TargetX86.base',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX64.TargetX86.Resources.base',
      'Microsoft.VC.14.30.17.0.Tools.HostX86.TargetX64',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX86.TargetX86',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX86.TargetX86.base',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX86.TargetX86.Resources.base',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX86.TargetX64',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX86.TargetX64.base',
      'Microsoft.VC.14.30.17.0.Premium.Tools.Hostx86.Targetx64.Resources.base',
      'Microsoft.VC.14.30.17.0.PGO.X86',
      'Microsoft.VC.14.30.17.0.PGO.X86.base',
      'Microsoft.VC.14.30.17.0.PGO.X64',
      'Microsoft.VC.14.30.17.0.PGO.X64.base',
      'Microsoft.VC.14.30.17.0.CRT.x86.Store',
      'Microsoft.VC.14.30.17.0.CRT.x86.Store.base',
      'Microsoft.VC.14.30.17.0.CRT.x86.OneCore.Desktop',
      'Microsoft.VC.14.30.17.0.CRT.x86.OneCore.Desktop.base',
      'Microsoft.VC.14.30.17.0.CRT.x86.Desktop',
      'Microsoft.VC.14.30.17.0.CRT.x86.Desktop.base',
      'Microsoft.VC.14.30.17.0.CRT.x64.Store',
      'Microsoft.VC.14.30.17.0.CRT.x64.Store.base',
      'Microsoft.VC.14.30.17.0.CRT.x64.OneCore.Desktop',
      'Microsoft.VC.14.30.17.0.CRT.x64.OneCore.Desktop.base',
      'Microsoft.VC.14.30.17.0.CRT.x64.Desktop',
      'Microsoft.VC.14.30.17.0.CRT.x64.Desktop.base',
      'Microsoft.VC.14.30.17.0.CRT.Redist.x86.OneCore.Desktop',
      'Microsoft.VC.14.30.17.0.CRT.Redist.x86.OneCore.Desktop.base',
      'Microsoft.VC.14.30.17.0.CRT.Redist.X86',
      'Microsoft.VC.14.30.17.0.CRT.Redist.X86.base',
      'Microsoft.VC.14.30.17.0.CRT.Redist.x64.OneCore.Desktop',
      'Microsoft.VC.14.30.17.0.CRT.Redist.x64.OneCore.Desktop.base',
      'Microsoft.VC.14.30.17.0.CRT.Redist.X64',
      'Microsoft.VC.14.30.17.0.CRT.Redist.X64.base',
      'Microsoft.VC.14.30.17.0.ASAN.X86',
      'Microsoft.VC.14.30.17.0.ASAN.X86.base',
      'Microsoft.VC.14.30.17.0.Tools.HostX64.TargetX86.base',
      'Microsoft.VC.14.30.17.0.Tools.HostX64.TargetX86.Resources.base',
      'Microsoft.VC.14.30.17.0.ASAN.X64.base',
      'Microsoft.VC.14.30.17.0.Tools.HostX86.TargetX64.base',
      'Microsoft.VC.14.30.17.0.Tools.Hostx86.Targetx64.Resources.base',
      'Microsoft.VC.14.30.17.0.ASAN.Headers.base',
      'Microsoft.VC.14.30.17.0.Tools.HostX64.TargetX64',
      'Microsoft.VisualStudio.Component.VC.Tools.ARM',
      'Microsoft.VisualCpp.Tools.HostX86.TargetARM.Resources',
      'Microsoft.VisualCpp.Tools.Hostx86.Targetarm',
      'Microsoft.VC.14.31.17.1.Tools.Hostx86.Targetarm.base',
      'Microsoft.VC.14.31.17.1.Tools.HostX86.TargetARM.Resources.base',
      'Microsoft.VisualCpp.CRT.Redist.arm.OneCore.Desktop',
      'Microsoft.VC.14.31.17.1.CRT.Redist.arm.OneCore.Desktop.base',
      'Microsoft.VisualCpp.CRT.arm.Store',
      'Microsoft.VC.14.31.17.1.CRT.arm.Store.base',
      'Microsoft.VisualCpp.CRT.arm.Desktop',
      'Microsoft.VC.14.31.17.1.CRT.arm.Desktop.base',
      'Microsoft.VisualStudio.PackageGroup.VC.Tools.x64.ARM',
      'Microsoft.VisualCpp.Premium.Tools.Hostx86.Targetarm',
      'Microsoft.VC.14.31.17.1.Premium.Tools.Hostx86.Targetarm.base',
      'Microsoft.VC.14.31.17.1.Premium.Tools.HostX86.TargetARM.Resources.base',
      'Microsoft.VisualCpp.Premium.Tools.HostX64.TargetARM',
      'Microsoft.VC.14.31.17.1.Premium.Tools.HostX64.TargetARM.base',
      'Microsoft.VC.14.31.17.1.Premium.Tools.HostX64.TargetARM.Resources.base',
      'Microsoft.VisualCpp.Premium.Tools.ARM.Base',
      'Microsoft.VC.14.31.17.1.Premium.Tools.ARM.Base.base',
      'Microsoft.VC.14.31.17.1.Premium.Tools.ARM.Base.Resources.base',
      'Microsoft.VisualCpp.PGO.ARM',
      'Microsoft.VC.14.31.17.1.PGO.ARM.base',
      'Microsoft.VisualCpp.Tools.HostX64.TargetARM',
      'Microsoft.VC.14.31.17.1.Tools.HostX64.TargetARM.base',
      'Microsoft.VC.14.31.17.1.Tools.HostX64.TargetARM.Resources.base',
      'Microsoft.VC.14.31.17.1.Props.ARM',
      'Microsoft.VisualCpp.CRT.arm.OneCore.Desktop',
      'Microsoft.VC.14.31.17.1.CRT.arm.OneCore.Desktop.base',
      'Microsoft.VC.14.31.17.1.ATL.Headers.base',
      'Microsoft.VC.14.31.17.1.Servicing.ATL',
      'Microsoft.VisualStudio.Component.VC.CMake.Project',
      'Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake',
      'Microsoft.VisualStudio.VC.Ide.LanguageService',
      'Microsoft.VisualStudio.VC.CMake',
      'Microsoft.VisualStudio.Cache.Service',
      'Microsoft.VisualStudio.VC.CMake.Project',
      'Microsoft.VisualStudio.VC.Ide.ResourceEditor',
      'Microsoft.VisualStudio.VC.Ide.ResourceEditor.Resources',
      'Microsoft.VisualStudio.VC.CMake.Client',
      'Microsoft.VisualStudio.VC.Ide.VCPkgDatabase',
      'Microsoft.VisualStudio.VC.ExternalBuildFramework',
      'Microsoft.VisualStudio.VC.Ide.Progression.Enterprise',
      'Microsoft.VisualStudio.VisualC.Utilities',
      'Microsoft.VC.14.30.17.0.Tools.HostX64.TargetX64.base',
      'Microsoft.VC.14.30.17.0.Props.x64',
      'Microsoft.VisualStudio.VC.Ide.Common',
      'Microsoft.VisualStudio.VC.MSVCDis',
      'Microsoft.VC.14.30.17.0.Tools.HostX64.TargetX64.Resources.base',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX64.TargetX64',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX64.TargetX64.base',
      'Microsoft.VisualStudio.VC.Ide.Base',
      'Microsoft.VC.14.30.17.0.Premium.Tools.HostX64.TargetX64.Resources.base',
      'Microsoft.VisualCpp.Tools.Common.Utils.Resources',
      'Microsoft.VisualStudio.VirtualTree',
      ... 535 more items
    ]
  }
]
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2022
gyp ERR! find VS running in VS Command Prompt, installation path is:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022"
gyp ERR! find VS - will only use this version
gyp ERR! find VS checking VS2022 (17.1.32210.238) found at:
gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v143
gyp ERR! find VS - found Windows SDK: 10.0.19041.0
gyp ERR! find VS - does not match this Visual Studio Command Prompt
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS msvs_version does not match this VS Command Prompt or the
gyp ERR! find VS installation cannot be used.
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\find-visualstudio.js:367:14)
gyp ERR! stack     at C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\find-visualstudio.js:388:16
gyp ERR! stack     at C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\ProgramData\nvm\v16.13.2\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2022"
gyp ERR! cwd C:\Users\ajink
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
```

**Comment by marf** [comment]
I have the same problem

**Comment by lakshya187** [comment]
I have the same issue

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/lib/find-visualstudio.js#L432-L436

**Comment by A-ANing** [comment]
me too

**Comment by AlphaCodeProgrammer** [comment]
and me

**Comment by ItsMeTazz** [comment]
And here as well

**Comment by kkoomen** [comment]
same here

**Comment by cclauss** [comment]
@mhdawson @gengjiawen @nodejs/platform-windows Any thoughts?

**Comment by gengjiawen** [comment]
> gyp ERR! find VS You need to install the latest version of Visual Studio
> gyp ERR! find VS including the "Desktop development with C++" workload.
> gyp ERR! find VS For more information consult the documentation at:
> gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

From the log looks like the cpp tools not installed.

**Comment by Edstar3000** [comment]
any update?

**Comment by xXAvoraXx** [comment]
++

**Comment by kmashint** [comment]
I've had similar problems with more recent node-gyp as used through @parcel/watcher. I had to use "@parcel/watcher": "~2.1.0" in my project devDependencies to avoid problems with 'gyp: binding.gyp not found' on both Windows 10 with npm 18 or 16 and Python 3.11, and MacOS 12.6.5 with npm 18 or 16 and Python 3.10. The problems seem to start in "@parcel/watcher": "~2.2.0" with its "node-addon-api": "^7.0.0" dependency, whereas  "@parcel/watcher": "~2.1.0" with node-addon-api: ^3.2.1 and node-gyp-build: ^4.3.0 dependencies works.

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
