### ISSUE TITLE
Python error syntax on Mac M1

### ISSUE THREAD

**Issue by thibpoullain** [nodejs/node-gyp#2646]
Hi there, 

I have an issue with node-gyp about a python syntax : 

`gyp ERR! stack Error: Command failed: /opt/homebrew/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];`

I'm on Mac OS 12.3.1 on M1 chip, on a legacy project with this version of node etc :

node : 14.19.1
npm : 8.6.0
nvm : 0.39
node-gyp : 9.0 (installed, but it seems to use the 3.8.0 🤔 )
node-sass: 4.14

Could you give me a little help about that please ? Thx a lot ! 🍀 😊  

My logs : 

```
❯ yarn install
yarn install v1.22.17
warning package.json: No license field
warning No license field
[1/5] 🔍  Validating package.json...
warning No license field
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning " > expose-loader@0.7.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > webpack-dev-server@3.9.0" has unmet peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[5/5] 🔨  Building fresh packages...
[1/4] ⠐ fsevents
[-/4] ⠐ waiting...
[3/4] ⠐ node-sass
error /Users/thibaut/Documents/atelier/OURS/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/thibaut/Documents/atelier/OURS/node_modules/node-sass
Output:
Building: /Users/thibaut/.nvm/versions/node/v14.19.1/bin/node /Users/thibaut/Documents/atelier/OURS/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/thibaut/.nvm/versions/node/v14.19.1/bin/node',
gyp verb cli   '/Users/thibaut/Documents/atelier/OURS/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.19.1 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/opt/homebrew/bin/python3" in the PATH
gyp verb `which` succeeded /opt/homebrew/bin/python3 /opt/homebrew/bin/python3
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /opt/homebrew/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/thibaut/.nvm/versions/node/v14.19.1/bin/node" "/Users/thibaut/Documents/atelier/OURS/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/thibaut/Documents/atelier/OURS/node_modules/node-sass
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v3.8.0
```

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/tree/master/docs
