### ISSUE TITLE
Unsupported version 17

### ISSUE THREAD

**Issue by jensborch** [nodejs/node-gyp#2661]
Executing `npm install` on a project using node-gyp on Windows 10 using the most resent version of [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) fails. It seem this version isn't supported.

Running `npm install --loglevel=silly`. I get the following in the log:

```
gyp sill find VS processing installation: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp sill find VS - version match = ["17.1.32421.90","17","1"]
gyp sill find VS - unsupported version: 17
gyp sill find VS - found VC.Tools.x86.x64
gyp sill find VS - invalid versionYear: undefined
gyp sill find VS - found Win10SDK: 19041
```

and at the end of the build:

```
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\test\AppData\Local\nvs\node\14.19.2\x64\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
gyp ERR! System Windows_NT 10.0.19042
```

* **Node Version**: v14.19.2
* **Platform**: Microsoft Windows 10 Enterprise
* **Compiler**:  17.1.0.7609
* **Module**: renovate

Are there any plans to support this version Visual Studio Build Tools or should I try to downgrade?

**Comment by gengjiawen** [comment]
Can you try this https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

**Comment by jensborch** [comment]
Updating the bundled version of node-gyp seems to have fixed the issue. Thanks!
