### ISSUE TITLE
Error when trying to deploy to Netlify

### ISSUE THREAD

**Issue by mluce194** [nodejs/node-gyp#2666]
* **Node Version**: node v17.4.0 and npm 8.3.1
* **Platform**: Darwin iMacdeMarieLuce 18.7.0 Darwin Kernel Version 
* **Compiler**: 
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
* **Module**: Gatsby Website: deployment fails on Netlify although I did not get any error locally

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
9:33:08 AM:   gyp: binding.gyp not found (cwd: /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/node_modules/@netlify/ipx/node_modules/ipx/node_modules/sharp/node_modules/node-addon-api) while trying to load binding.gyp
9:33:08 AM:   gyp ERR! configure error
9:33:08 AM:   gyp ERR! stack Error: `gyp` failed with exit code: 1
9:33:08 AM:   gyp ERR! stack     at ChildProcess.onCpExit (/opt/build/repo/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
9:33:08 AM:   gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
9:33:08 AM:   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
9:33:08 AM:   gyp ERR! System Linux 5.4.181-99.354.amzn2.x86_64
9:33:08 AM:   gyp ERR! command "/opt/buildhome/.nvm/versions/node/v14.19.2/bin/node" "/opt/build/repo/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
9:33:08 AM:   gyp ERR! cwd /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/node_modules/@netlify/ipx/node_modules/ipx/node_modules/sharp/node_modules/node-addon-api
9:33:08 AM:   gyp ERR! node -v v14.19.2
9:33:08 AM:   gyp ERR! node-gyp -v v3.6.0
9:33:08 AM:   gyp ERR! not ok
9:33:08 AM: ​
9:33:08 AM:   > bufferutil@4.0.6 install /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/node_modules/@netlify/ipx/node_modules/unstorage/node_modules/bufferutil
9:33:08 AM:   > node-gyp-build
9:33:08 AM: ​​
9:33:08 AM:   > utf-8-validate@5.0.9 install /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/node_modules/@netlify/ipx/node_modules/unstorage/node_modules/utf-8-validate
9:33:08 AM:   > node-gyp-build
9:33:08 AM: ​
9:33:08 AM:   npm ERR! Linux 5.4.181-99.354.amzn2.x86_64
9:33:08 AM:   npm ERR! argv "/opt/buildhome/.nvm/versions/node/v14.19.2/bin/node" "/opt/build/repo/node_modules/.bin/npm" "install" "--no-progress" "--no-audit" "--no-fund" "--save-exact" "netlify-plugin-gatsby-cache@0.3.0" "@netlify/plugin-gatsby@3.0.0"
9:33:10 AM: Creating deploy upload records
9:33:08 AM:   npm ERR! node v14.19.2
9:33:08 AM:   npm ERR! npm  v2.15.12
9:33:08 AM:   npm ERR! code ELIFECYCLE
9:33:08 AM: ​
9:33:08 AM:   npm ERR! node-addon-api@4.3.0 install: `node-gyp rebuild`
9:33:10 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:33:08 AM:   npm ERR! Exit status 1
9:33:08 AM:   npm ERR!
9:33:08 AM:   npm ERR! Failed at the node-addon-api@4.3.0 install script 'node-gyp rebuild'.
9:33:08 AM:   npm ERR! This is most likely a problem with the node-addon-api package,
9:33:08 AM:   npm ERR! not with npm itself.
9:33:08 AM:   npm ERR! Tell the author that this fails on your system:
9:33:08 AM:   npm ERR!     node-gyp rebuild
9:33:08 AM:   npm ERR! You can get information on how to open an issue for this project with:
9:33:08 AM:   npm ERR!     npm bugs node-addon-api
9:33:08 AM:   npm ERR! Or if that isn't available, you can get their info via:
  npm ERR!
9:33:08 AM:   npm ERR!     npm owner ls node-addon-api
9:33:08 AM:   npm ERR! There is likely additional logging output above.
9:33:08 AM: ​
9:33:08 AM:   npm ERR! Please include the following file with any support request:
9:33:08 AM: ​
9:33:08 AM:   Resolved config
9:33:08 AM:   build:
9:33:08 AM:     command: gatsby build
9:33:08 AM:     commandOrigin: ui
9:33:08 AM:     environment:
9:33:08 AM:       - CONTENTFUL_ACCESS_TOKEN
9:33:08 AM:       - CONTENTFUL_SPACE_ID
9:33:08 AM:     publish: /opt/build/repo/public
9:33:08 AM:     publishOrigin: ui
9:33:08 AM:   plugins:
9:33:08 AM:     - inputs: {}
9:33:08 AM:       origin: ui
9:33:08 AM:       package: netlify-plugin-gatsby-cache
9:33:08 AM:     - inputs: {}
9:33:08 AM:       origin: ui
9:33:08 AM:       package: '@netlify/plugin-gatsby
```

</details>

When I run `node-gyp configure` and `node-gyp build` locally, it works fine. When I deploy the Website to Netlify, I get the error above.

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.6.0

https://github.com/nodejs/node-gyp/blob/master/docs/README.md
