### ISSUE TITLE
MacOS 12.3, Python3.10 Node16 cannot build, I am at loss

### ISSUE THREAD

**Issue by spock123** [nodejs/node-gyp#2670]
Hey guys,
- after struggling with MacOS12.3 update and installing Python 3 (Python2 was removed in MacOS12.3 as you guys know), I cannot install anything using npm. 
I have installed npm 3.10 using pyenv and python3 is installed at /usb/bin/python3

I have tried setting the npm to use it:

```npm config set python /usr/bin/python3```

But I am at a loss after several days of trying to get my dependencies installed in my projects.
Can anyone see in the logs what might the be the issue?
Thanks

* **Node Version**: v16.15.0 npm 8.5.5
* **Platform**:Darwin larss-mbp.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
* 
* **Compiler**: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

* **Module**: node-gyp

```
11686 verbose stack Error: command failed
11686 verbose stack     at ChildProcess.<anonymous> (/Users/lrj/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
11686 verbose stack     at ChildProcess.emit (node:events:527:28)
11686 verbose stack     at maybeClose (node:internal/child_process:1092:16)
11686 verbose stack     at Socket.<anonymous> (node:internal/child_process:451:11)
11686 verbose stack     at Socket.emit (node:events:527:28)
11686 verbose stack     at Pipe.<anonymous> (node:net:709:12)
11687 verbose pkgid node-webcrypto-ossl@1.0.49
11688 verbose cwd /Users/lrj/projects/bropas.oresundsbron.com
11689 verbose Darwin 21.4.0
11690 verbose argv "/Users/lrj/.nvm/versions/node/v16.15.0/bin/node" "/Users/lrj/.nvm/versions/node/v16.15.0/bin/npm" "i" "--legacy-peer-deps"
11691 verbose node v16.15.0
11692 verbose npm  v8.5.5
11693 error code 1
11694 error path /Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-webcrypto-ossl
11695 error command failed
11696 error command sh -c node-gyp rebuild
11697 error CXX(target) Release/obj.target/nodessl/src/main.o
11698 error gyp info it worked if it ends with ok
11698 error gyp info using node-gyp@8.4.1
11698 error gyp info using node@16.15.0 | darwin | arm64
11698 error gyp info find Python using Python version 3.10.4 found at "/Users/lrj/.pyenv/versions/3.10.4/bin/python"
11698 error gyp info spawn /Users/lrj/.pyenv/versions/3.10.4/bin/python
11698 error gyp info spawn args [
11698 error gyp info spawn args   '/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-gyp/gyp/gyp_main.py',
11698 error gyp info spawn args   'binding.gyp',
11698 error gyp info spawn args   '-f',
11698 error gyp info spawn args   'make',
11698 error gyp info spawn args   '-I',
11698 error gyp info spawn args   '/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-webcrypto-ossl/build/config.gypi',
11698 error gyp info spawn args   '-I',
11698 error gyp info spawn args   '/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-gyp/addon.gypi',
11698 error gyp info spawn args   '-I',
11698 error gyp info spawn args   '/Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/common.gypi',
11698 error gyp info spawn args   '-Dlibrary=shared_library',
11698 error gyp info spawn args   '-Dvisibility=default',
11698 error gyp info spawn args   '-Dnode_root_dir=/Users/lrj/Library/Caches/node-gyp/16.15.0',
11698 error gyp info spawn args   '-Dnode_gyp_dir=/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-gyp',
11698 error gyp info spawn args   '-Dnode_lib_file=/Users/lrj/Library/Caches/node-gyp/16.15.0/<(target_arch)/node.lib',
11698 error gyp info spawn args   '-Dmodule_root_dir=/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-webcrypto-ossl',
11698 error gyp info spawn args   '-Dnode_engine=v8',
11698 error gyp info spawn args   '--depth=.',
11698 error gyp info spawn args   '--no-parallel',
11698 error gyp info spawn args   '--generator-output',
11698 error gyp info spawn args   'build',
11698 error gyp info spawn args   '-Goutput_dir=.'
11698 error gyp info spawn args ]
11698 error gyp info spawn make
11698 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
11698 error Apple clang version 13.1.6 (clang-1316.0.21.2.5)
11698 error Target: arm64-apple-darwin21.4.0
11698 error Thread model: posix
11698 error InstalledDir: /Library/Developer/CommandLineTools/usr/bin
11698 error  "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple arm64-apple-macosx10.7.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -mllvm -extra-vectorizer-passes -fno-strict-return -fno-rounding-math -munwind-tables -faligned-alloc-unavailable -target-sdk-version=12.3 -fvisibility-inlines-hidden-static-local-var -target-cpu apple-m1 -target-feature +v8.5a -target-feature +fp-armv8 -target-feature +neon -target-feature +crc -target-feature +crypto -target-feature +dotprod -target-feature +fp16fml -target-feature +ras -target-feature +lse -target-feature +rdm -target-feature +rcpc -target-feature +zcm -target-feature +zcz -target-feature +fullfp16 -target-feature +sm4 -target-feature +sha3 -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -fallow-half-arguments-and-returns -debug-info-kind=standalone -dwarf-version=2 -debugger-tuning=lldb -target-linker-version 763 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6 -dependency-file ./Release/.deps/Release/obj.target/nodessl/src/main.o.d.raw -skip-unused-modulemap-deps -MT Release/obj.target/nodessl/src/main.o -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -D NODE_GYP_MODULE_NAME=nodessl -D USING_UV_SHARED=1 -D USING_V8_SHARED=1 -D V8_DEPRECATION_WARNINGS=1 -D V8_DEPRECATION_WARNINGS -D V8_IMMINENT_DEPRECATION_WARNINGS -D _GLIBCXX_USE_CXX11_ABI=1 -D _DARWIN_USE_64_BIT_INODE=1 -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D OPENSSL_NO_PINSHARED -D OPENSSL_THREADS -D BUILDING_NODE_EXTENSION -I /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node -I /Users/lrj/Library/Caches/node-gyp/16.15.0/src -I /Users/lrj/Library/Caches/node-gyp/16.15.0/deps/openssl/config -I /Users/lrj/Library/Caches/node-gyp/16.15.0/deps/openssl/openssl/include -I /Users/lrj/Library/Caches/node-gyp/16.15.0/deps/uv/include -I /Users/lrj/Library/Caches/node-gyp/16.15.0/deps/zlib -I /Users/lrj/Library/Caches/node-gyp/16.15.0/deps/v8/include -I ../../nan -I/usr/local/include -stdlib=libc++ -stdlib=libc++ -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -O3 -Wall -Wendif-labels -W -Wno-unused-parameter -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -Wno-objc-load-method -std=c++11 -fdeprecated-macro -fdebug-compilation-dir=/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-webcrypto-ossl/build -ferror-limit 19 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fno-rtti -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-cxx-modules -fcxx-exceptions -fexceptions -fmax-type-align=16 -fcommon -vectorize-loops -vectorize-slp -clang-vendor-feature=+messageToSelfInClassMethodIdReturnType -clang-vendor-feature=+disableInferNewAvailabilityFromInit -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o Release/obj.target/nodessl/src/main.o -x c++ ../src/main.cpp
11698 error clang -cc1 version 13.1.6 (clang-1316.0.21.2.5) default target arm64-apple-darwin21.4.0
11698 error ignoring nonexistent directory "/Users/lrj/Library/Caches/node-gyp/16.15.0/src"
11698 error ignoring nonexistent directory "/Users/lrj/Library/Caches/node-gyp/16.15.0/deps/openssl/config"
11698 error ignoring nonexistent directory "/Users/lrj/Library/Caches/node-gyp/16.15.0/deps/openssl/openssl/include"
11698 error ignoring nonexistent directory "/Users/lrj/Library/Caches/node-gyp/16.15.0/deps/uv/include"
11698 error ignoring nonexistent directory "/Users/lrj/Library/Caches/node-gyp/16.15.0/deps/zlib"
11698 error ignoring nonexistent directory "/Users/lrj/Library/Caches/node-gyp/16.15.0/deps/v8/include"
11698 error ignoring nonexistent directory "/usr/local/include"
11698 error ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
11698 error ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
11698 error #include "..." search starts here:
11698 error #include <...> search starts here:
11698 error  /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node
11698 error  ../../nan
11698 error  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1
11698 error  /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include
11698 error  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
11698 error  /Library/Developer/CommandLineTools/usr/include
11698 error  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
11698 error End of search list.
11698 error In file included from ../src/main.cpp:1:
11698 error In file included from ../src/node/common.h:4:
11698 error In file included from ../src/node/../core/common.h:8:
11698 error In file included from ../../nan/nan.h:58:
11698 error In file included from /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/node.h:63:
11698 error In file included from /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/v8.h:30:
11698 error /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
11698 error             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
11698 error                                 ~~~~~^~~~~~~~~~~
11698 error                                      remove_cv
11698 error /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:715:50: note: 'remove_cv' declared here
11698 error template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
11698 error                                                  ^
11698 error 1 error generated.
11698 error make: *** [Release/obj.target/nodessl/src/main.o] Error 1
11698 error gyp ERR! build error 
11698 error gyp ERR! stack Error: `make` failed with exit code: 2
11698 error gyp ERR! stack     at ChildProcess.onExit (/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-gyp/lib/build.js:194:23)
11698 error gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
11698 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
11698 error gyp ERR! System Darwin 21.4.0
11698 error gyp ERR! command "/Users/lrj/.nvm/versions/node/v16.15.0/bin/node" "/Users/lrj/projects/bropas.oresundsbron.com/node_modules/.bin/node-gyp" "rebuild"
11698 error gyp ERR! cwd /Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-webcrypto-ossl
11698 error gyp ERR! node -v v16.15.0
11698 error gyp ERR! node-gyp -v v8.4.1
11698 error gyp ERR! not ok
11699 verbose exit 1

```

</details>

**Comment by cclauss** [comment]
This looks like C++ problem.  Please ensure that your macOS command line tools or Xcode are up to date.  https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md has some hints

**Comment by spock123** [comment]
@cclauss command line tools are up to date, unfortunately. I'll take a look at the link, thank you

**Comment by spock123** [comment]
If I install node-gyp globally and after run node-gyp rebuild I get the same error:

 ```
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.0 | darwin | arm64
gyp info find Python using Python version 3.10.4 found at "/Users/lrj/.pyenv/versions/3.10.4/bin/python"
gyp info spawn /Users/lrj/.pyenv/versions/3.10.4/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/lrj/.nvm/versions/node/v16.15.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lrj/projects/bropas.oresundsbron.com/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lrj/.nvm/versions/node/v16.15.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lrj/Library/Caches/node-gyp/16.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lrj/.nvm/versions/node/v16.15.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lrj/Library/Caches/node-gyp/16.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lrj/projects/bropas.oresundsbron.com',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Users/lrj/projects/bropas.oresundsbron.com) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/lrj/.nvm/versions/node/v16.15.0/lib/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/lrj/.nvm/versions/node/v16.15.0/bin/node" "/Users/lrj/.nvm/versions/node/v16.15.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/lrj/projects/bropas.oresundsbron.com
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
```

**Comment by spock123** [comment]
I removed all references to python on my system, everything. Then installed 3.7. 
It works not, but only on node14. Node 16 is no go. I'll just close this , thanks guys.

**Comment by richardlau** [comment]
FWIW

```
11698 error In file included from /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/v8.h:30:
11698 error /Users/lrj/Library/Caches/node-gyp/16.15.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
11698 error             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
11698 error                                 ~~~~~^~~~~~~~~~~
11698 error                                      remove_cv
11698 error /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:715:50: note: 'remove_cv' declared here
11698 error template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
11698 error                                                  ^
11698 error 1 error generated.
```
is the same as https://github.com/nodejs/node-gyp/issues/2557 -- the module (or particular version of the module) being compiled would need to be updated to work with Node.js 16. It looks like in this case 
```
11698 error gyp info spawn args   '-Dmodule_root_dir=/Users/lrj/projects/bropas.oresundsbron.com/node_modules/node-webcrypto-ossl',
```
the module is `node-webcrypto-ossl` and a newer version of that should have addressed that problem: https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/172

**Comment by spock123** [comment]
@richardlau thanks man, yes that's also what I came to. However I believe it's a dependency of node-gyp so not sure how I could mitigate that.

Thanks again
