### ISSUE TITLE
gyp ERR! stack Error: 403 response downloading

### ISSUE THREAD

**Issue by Ubaii** [nodejs/node-gyp#2671]
i was trying to build electron, with electron-builder, i include pg in this project, and electron-build showing error on pg-native, and i have fix it every error on electron-build except this error, how i can fix it?

electron-builder say

PS C:\Unfinished Project\PBLauncher\PBLauncher Debug> npm run dist
```
> pblauncher@1.0.0 dist
> electron-builder --win=portable -p always

  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=dist\electron-builder.yaml
  • rebuilding native production dependencies platform=win32 arch=x64

Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
npm ERR! code 1
npm ERR! path C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\libpq
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.15.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "C:\Users\AnonyX\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp http GET https://atom.io/download/electron/v18.3.0/node-v18.3.0-headers.tar.gz
npm ERR! gyp http 403 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v18.3.0/node-v18.3.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: 403 response downloading https://atom.io/download/electron/v18.3.0/node-v18.3.0-headers.tar.gz
npm ERR! gyp ERR! stack     at go (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\node-gyp\lib\install.js:153:17)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR! gyp ERR! stack     at async install (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\node-gyp\lib\install.js:62:18)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Unfinished Project\\PBLauncher\\PBLauncher Debug\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\libpq
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AnonyX\AppData\Local\npm-cache\_logs\2022-05-25T08_38_05_586Z-debug-0.log

    at ChildProcess.<anonymous> (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\builder-util\src\util.ts:241:14)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at spawn (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\builder-util\src\util.ts:200:3)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\src\util\yarn.ts:171:5
From previous event:
    at rebuild (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at installOrRebuild (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\src\packager.ts:442:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\out\packager.js:496:11)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\src\packager.ts:356:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\out\packager.js:432:11)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23)
From previous event:
    at Packager._build (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\out\packager.js:376:11)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder-lib\out\packager.js:332:11)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\src\builder.ts:280:10)
    at C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\src\cli\cli.ts:48:33
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.handler (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\node_modules\yargs\yargs.js:1050:24)
    at Object.get [as argv] (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\node_modules\yargs\yargs.js:965:21)
    at Object.<anonymous> (C:\Unfinished Project\PBLauncher\PBLauncher Debug\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by cclauss** [comment]
This just seems to be an Internet download problem.  Have you tried repeating this command?

**Comment by Ubaii** [comment]
i have a normally internet

**Comment by cclauss** [comment]
That does not answer my question.  There are problems on the Internet (esp. Amazon) so retrying may be required.

**Comment by Ubaii** [comment]
and i have tried change the connection, but still given that error.

**Comment by Ubaii** [comment]
do u have any solution, i just wanna build my app with electron-builder. or maybe change the url download? but where the link?
sorry for bad english

**Comment by cclauss** [comment]
The core problem is that the URL returns AccessDenied.  If your code came from a repo, please open an issue there.
* https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v18.3.0/node-v18.3.0-headers.tar.gz

**Comment by Ubaii** [comment]
no, this is my app, not came from any repo

**Comment by Yongle-Fu** [comment]
https://github.blog/2022-06-08-sunsetting-atom/

**Comment by Yongle-Fu** [comment]
download atom failed because above

**Comment by shufps** [comment]
Why was the issue closed?

I don't see any solution to this problem.

I have the same :man_shrugging:

**Comment by cclauss** [comment]
https://github.blog/2022-06-08-sunsetting-atom/
