### ISSUE TITLE
gyp ERR! Building erlpack

### ISSUE THREAD

**Issue by callumok2004** [nodejs/node-gyp#2672]
* **Node Version**: v17.8.0
* **Yarn Version**: v1.22.18
* **NPM Version**: v8.8.0
* **Platform**: 
```
OS Name:                   Microsoft Windows 11 Pro Insider Preview
OS Version:                10.0.25115 N/A Build 25115
System Type:               x64-based PC
```
* **Compiler**: MSBuild Version - 17.1.0.7609
* **Module**: Erlpack

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
  | ~\Desktop\Dev\Youtube Music  ❯  yarn
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
[1/5] ⠈ @discordjs/opus
[-/5] ⠈ waiting...
[3/5] ⠈ utf-8-validate
[4/5] ⠈ erlpack
error C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack
Output:
C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\callu\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@17.8.0 | win32 | x64
gyp info find Python using Python version 3.9.13 found at "C:\Users\callu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2022 (17.1.32421.90) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\callu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\callu\\Desktop\\Dev\\Youtube Music\\node_modules\\erlpack\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\callu\\AppData\\Local\\node-gyp\\Cache\\17.8.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\callu\\AppData\\Local\\node-gyp\\Cache\\17.8.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\callu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.8.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\callu\\Desktop\\Dev\\Youtube Music\\node_modules\\erlpack',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\callu\\Desktop\\Dev\\Youtube Music\\node_modules\\erlpack\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\callu\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.25115
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack
```
</details>

**Comment by cclauss** [comment]
Seems like both `VS2022` and `VS2017` are installed and the build process is trying to use _both_.

> gyp info find VS using VS2022 (17.1.32421.90) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"

> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5):
error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found.
To build using the v143 build tools, please install v143 build tools. 
Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or
right-click the solution, and then selecting "Retarget solution".
[C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj]

**Comment by callumok2004** [comment]
Good spot, is there any method of forcing the build process to use only one of the versions while keeping both versions installed, or do I even need both and should remove VS2017?

**Comment by cclauss** [comment]
Sorry but I am not a Windows user.

**Comment by callumok2004** [comment]
If anyone else can assist, please do.
I updated the yarn and npm config to use msvs_version 2022, uninstalled the 2017 version and tried again. Cleared cache, node_modules etc.
![PEPogugI37 1](https://user-images.githubusercontent.com/35779365/170876988-ad629fac-5865-49dc-bb8a-89f6c503114b.png)

**Comment by cclauss** [comment]
What is in the log?

**Comment by callumok2004** [comment]
```
error C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack
Output:
C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\callu\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@17.8.0 | win32 | x64
gyp info find Python using Python version 3.9.13 found at "C:\Users\callu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2022 (17.2.32519.379) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\callu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\callu\\Desktop\\Dev\\Youtube Music\\node_modules\\erlpack\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\callu\\AppData\\Local\\node-gyp\\Cache\\17.8.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\callu\\AppData\\Local\\node-gyp\\Cache\\17.8.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\callu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.8.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\callu\\Desktop\\Dev\\Youtube Music\\node_modules\\erlpack',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\callu\\Desktop\\Dev\\Youtube Music\\node_modules\\erlpack\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj(21,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\callu\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.25115
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\callu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack
```

I fail to see why it still decides to try use the 2017 version when it is configured to use 2022

**Comment by cclauss** [comment]
Is `2017` in the file `C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj` ?

**Comment by callumok2004** [comment]
> Is `2017` in the file `C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj` ?

No, it is not.

**Comment by callumok2004** [comment]
Anyone have any ideas?

**Comment by poisonintheink** [comment]
Having a look at your error it seems you might be having an issue with either the `VCTargetsPath` being set as an Environment Variable (user/system, not your project) and it's overwriting the inbuilt one.... 

Or worse the inbuilt one is busted, which gets complicated so save this for last - https://stackoverflow.com/questions/63540048/where-exactly-is-macro-vctargetspath-defined

Note: 
- Changing npm settings such as msvs_version and msbuild_path had no effect (save to break it a different way if you make changes to msbuild_path)
- I was able to reproduce both the error in your first and second posts by creating/changing a user environment variable, but it could be stored as a system variable (same spots to check really)
- Also this is just my assumptions based on some poking around, take some time to crosscheck this train of thought and consider any replies/corrections from other responders.

Checking for it in the first place....
- You can search using Powershell `ps>$Env:VCTargetsPath` or list everything via CMD `cmd>set`. There is a GUI option if you prefer and its somewhere in Control Panel
- If this variable exists I'd copy/paste the details and delete it to test whether the defaults are working fine, there is a number of ways to do this so best to have a google.
- Any time you change an environment variable they wont be picked up by apps immediately. Logging out is usually good enough but given your hassle with this one I'd go scorched earth and just reboot.
- After you've logged back in ideally erlpack etc should install without anything additional required

Alternatively if `VCTargetsPath` doesn't already exist you may be able to use this same  environment variable as a workaround by using it to force node-gyp to use the correct path for MSBuild under 2022.
- Caveat on this is that things that need to use MSBuild (not just npm/node) will be bound to this directory. Something to keep in mind if you experience strange issues after making any changes.
- To that point I'd recommend creating it as a 'user' not a system variable to start with
- Similar to removing an environment variable, I'll leave you to google how to add.
- What you'll want to be careful of is the directory you point it to and based on your logs I would expect it to be the following, though important to check
`C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\`
- You may see other folders under that 'VC' path; v170 for Visual Studio 2022, v160 for Visual Studio 2019, or v150 for Visual Studio 2017
- Inside that v170 folder you should find 'Microsoft.Cpp.Platform.targets' amongst other files
- Save the variable and as with before give the computer an off/on before re-attempting to ensure the variables taken hold.

For a little extra context form when I was testing:
- Firstly the error here occurs when you have the `VCTargetsPath` variable pointed to the location containing 2017's Build tools 
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj]
```
- And mine
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [S:\Projects\Scrap\node_modules\erlpack\build\vendor\zlib.vcxproj]
```
- Then when you uninstalled 2017 entirely, you received a slightly different error as the folder or its contents no longer exists
- I've simulated this by pointing that environment variable to an empty drive
```
C:\Users\callu\Desktop\Dev\Youtube Music\node_modules\erlpack\build\vendor\zlib.vcxproj(21,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```
- And again mine...
```
S:\Projects\Scrap\node_modules\zlib-sync\build\deps\zlib.vcxproj(21,3): error MSB4019: The imported project "S:\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "S:\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```
