### ISSUE TITLE
trying to 'npm install', getting node-gyp rebuild and python errors

### ISSUE THREAD

**Issue by petersenrr** [nodejs/node-gyp#2681]
npm ERR! code 1
npm ERR! path /Users/Petersenrr/dev/qa-brightspot/node_modules/node-expat
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
npm ERR!   CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
npm ERR!   CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
npm ERR!   LIBTOOL-STATIC Release/libexpat.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.4.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.3 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! (node:11296) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/Petersenrr/dev/qa-brightspot/node_modules/node-expat/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/Petersenrr/Library/Caches/node-gyp/16.4.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/Petersenrr/Library/Caches/node-gyp/16.4.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/Petersenrr/Library/Caches/node-gyp/16.4.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/Petersenrr/dev/qa-brightspot/node_modules/node-expat',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/libexpat.a] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/Petersenrr/dev/qa-brightspot/node_modules/node-expat
npm ERR! gyp ERR! node -v v16.4.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Petersenrr/.npm/_logs/2022-06-13T20_02_03_320Z-debug.log

**Comment by cclauss** [comment]
Please upgrade to the current version... https://github.com/nodejs/node-gyp/releases

**Comment by petersenrr** [comment]
> Please upgrade to the current version... https://github.com/nodejs/node-gyp/releases

I upgraded and still get the same error

**Comment by cclauss** [comment]
> npm ERR! env: python: No such file or directory

% `alias python=python3`
Then try again.

**Comment by petersenrr** [comment]
> % `alias python=python3`
> Then try again.

I did that and still same error, i closed my terminal, did i need to restart?

**Comment by cclauss** [comment]
% `python --version`
% `python3 --version`

**Comment by petersenrr** [comment]
> python3 --version

**Comment by petersenrr** [comment]
> % `python --version`
> % `python3 --version`

```
Petersenrr@RyanPetinch2019 qa-brightspot % python --version
zsh: command not found: python
Petersenrr@RyanPetinch2019 qa-brightspot % python3 --version
Python 3.10.3
```

**Comment by petersenrr** [comment]
> % `alias python=‘ /Library/Frameworks/Python.framework/Versions/3.10/bin/python3’`
> % `python --version`

```
Petersenrr@RyanPetinch2019 qa-brightspot % alias python=‘ /Library/Frameworks/Python.framework/Versions/3.10/bin/python3’
Petersenrr@RyanPetinch2019 qa-brightspot % python --version                                                             
zsh: command not found: ‘
```

**Comment by cclauss** [comment]
Delete the space before /Library

**Comment by petersenrr** [comment]
> Delete the space before /Library

```
Petersenrr@RyanPetinch2019 qa-brightspot % alias python=‘/Library/Frameworks/Python.framework/Versions/3.10/bin/python3’ 
Petersenrr@RyanPetinch2019 qa-brightspot % python --version                                                             
zsh: no such file or directory: ‘/Library/Frameworks/Python.framework/Versions/3.10/bin/python3’
```

**Comment by cclauss** [comment]
% `which python3`

**Comment by petersenrr** [comment]
> which python3

```
Petersenrr@RyanPetinch2019 ~ % which python3
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
Petersenrr@RyanPetinch2019 ~ % whereis -a python3
python3: /usr/bin/python3 /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 /usr/local/bin/python3 /Library/Frameworks/Python.framework/Versions/3.10/share/man/man1/python3.1
```

**Comment by cclauss** [comment]
alias python=/usr/bin/python3
python --version

**Comment by cclauss** [comment]
Yeah!  Now try your install…

**Comment by petersenrr** [comment]
> Yeah! Now try your install…

Same error :(

**Comment by cclauss** [comment]
I believe that is the one that makes `python --version` work.

**Comment by petersenrr** [comment]
Following these steps fixed it for me

brew install pyenv
pyenv install --list
pyenv install 2.7.18
pyenv versions
pyenv global 2.7.18
Put eval "$(pyenv init --path)" in ~/.zprofile (or ~/.bash_profile or ~/.zshrc)

**Comment by cclauss** [comment]
Python 2 died 897 days ago on 1/1/2020.  Current versions of node-gyp are not longer support it.

**Comment by iamstarkov** [comment]
maybe the OPs problem is outdated node-gyp `npm ERR! gyp info using node-gyp@7.1.2`

```
~ $ npm info node-gyp version
9.0.0
```

**Comment by iamstarkov** [comment]
@petersenrr you should not really use python2

**Comment by TheSegfault** [comment]
@cclauss I admire your patience reading this issue

**Comment by co60ca** [comment]
@cclauss I don't think aliases typically apply in programs only directly in shells. Hence why your alias fix probably didn't work. You could probably make a symbolic link in a directory and add a PATH element to that directory instead if you wanted to avoid breaking other stuff.

**Comment by nguyennhatminh-mgr** [comment]
Just do:
brew install python
It will install python for you, and then you can try again

**Comment by alex-solovev** [comment]
I've had the same issue, this worked for me:
1. If you have `python` installed via `brew` – remove it `brew remove python`
2. Make sure to remove any aliases for `python` as well 
3. Install `pyenv` via brew `brew install pyenv`
4. Install the desired version of `python` for me it was `pyenv install 3.9.6`
5. Select the `python` version using `pyenv global 3.9.6`
6. Add the following snippet to your shell config file, for me it was `.zshrc`
```shell
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
``` 
7. Restart the terminal – try installing packages again, `npm install` or `yarn`

These steps are based on the following article I've found by searching the solution for the problem, so all the credit goes to the author: https://opensource.com/article/19/5/python-3-default-mac

@yesworld In case if you still have the problem you may want to try this approach.

**Comment by johanbento** [comment]
See

> faced the same problem... :(
> 
> ```shell
> $ brew install python
> Warning: python@3.9 3.9.12 is already installed and up-to-date.
> To reinstall 3.9.12, run:
>   brew reinstall python@3.9
> ```
> 
> ```shell
> npm info node-gyp version
> 9.3.0
> ```
> 
> env: python: No such file or directory make: *** [Release/sass.a] Error 127 gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/../node_modules/node-gyp/lib/build.js:194:23) gyp ERR! stack at ChildProcess.emit (node:events:527:28) gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) gyp ERR! System Darwin 21.5.0

If you are using a Ubuntu distro/variant, please install a package called build-essential.
`sudo apt install build-essential`

**Comment by cclauss** [comment]
@johanbento Are you using linuxbrew?

**Comment by GSSCDylan** [comment]
> I've had the same issue, this worked for me:
> 
> 1. If you have `python` installed via `brew` – remove it `brew remove python`
> 2. Make sure to remove any aliases for `python` as well
> 3. Install `pyenv` via brew `brew install pyenv`
> 4. Install the desired version of `python` for me it was `pyenv install 3.9.6`
> 5. Select the `python` version using `pyenv global 3.9.6`
> 6. Add the following snippet to your shell config file, for me it was `.zshrc`
> 
> ```shell
> if command -v pyenv 1>/dev/null 2>&1; then
>   eval "$(pyenv init -)"
> fi
> ```
> 
> 7. Restart the terminal – try installing packages again, `npm install` or `yarn`
> 
> These steps are based on the following article I've found by searching the solution for the problem, so all the credit goes to the author: https://opensource.com/article/19/5/python-3-default-mac
> 
> @yesworld In case if you still have the problem you may want to try this approach.

works for me, thanks a lot!

**Comment by cclauss** [comment]
Perhaps upgrade to Python 3.9.15 or 3.10 or 3.11 for the intervening security fixes.

**Comment by peter-afs** [comment]
Not keen on installing pyenv or removing brew's Python 😅 

`/usr/bin/env python` is looking in your PATH for a `python` executable. If you've installed Python using brew, then it'll have installed `python3` in `/opt/homebrew/bin/`, but not a simple `python` alias, eg:

```
🌵$ which python3
/opt/homebrew/bin/python3
🌵$ which python
🌵$ 
```

*However* it has included installed a bunch of symlinks (including `python`), just not in a directory likely to be in your PATH. On my Mac, that's: `/opt/homebrew/opt/python@3.10/libexec/bin/`. You need to put that directory in your PATH, using something like: 

`export PATH="/opt/homebrew/opt/python@3.10/libexec/bin:$PATH"`

in your `~/.profile` (and then restart your terminal). You'll know you've got this right when you can type: `env python -V` and you get back a version string, and `which python` returns something like:

```
🌵$ which python
/opt/homebrew/opt/python@3.10/libexec/bin/python
```

**Comment by cclauss** [comment]
Just add `$HOMEBREW/bin` to your PATH as other homebrew users do.

**Comment by juxnpxblo** [comment]
in fedora running 

`sudo dnf group install "C Development Tools and Libraries" "Development Tools¨`

solved the problem for me, inspired by the suggestion made by @johanbento of installing build-essentials in ubuntu

**Comment by jvinhit** [comment]
> I've had the same issue, this worked for me:
> 
> 1. If you have `python` installed via `brew` – remove it `brew remove python`
> 2. Make sure to remove any aliases for `python` as well
> 3. Install `pyenv` via brew `brew install pyenv`
> 4. Install the desired version of `python` for me it was `pyenv install 3.9.6`
> 5. Select the `python` version using `pyenv global 3.9.6`
> 6. Add the following snippet to your shell config file, for me it was `.zshrc`
> 
> ```shell
> if command -v pyenv 1>/dev/null 2>&1; then
>   eval "$(pyenv init -)"
> fi
> ```
> 
> 7. Restart the terminal – try installing packages again, `npm install` or `yarn`
> 
> These steps are based on the following article I've found by searching the solution for the problem, so all the credit goes to the author: https://opensource.com/article/19/5/python-3-default-mac
> 
> @yesworld In case if you still have the problem you may want to try this approach.

thanks! it work for me
