### ISSUE TITLE
electron with ref-napi build error

### ISSUE THREAD

**Issue by gintoki94** [nodejs/node-gyp#2709]
my project dependecy:
-----------------------------------
  "devDependencies": {
    "electron": "^19.0.9",
    "ref-array-napi": "^1.2.0",
    "ref-napi": "^1.4.3",
    "ref-struct-napi": "^1.1.0",
    "ffi-napi": "^2.4.7"
  }
-----------------------------------
This is my build log 
-----------------------------------

PS D:\WorkSpace\StudySpace\electron-quick-start> npm install --python=C:\Python27\python.exe

> ref-napi@3.0.3 install D:\WorkSpace\StudySpace\electron-quick-start\node_modules\ref-array-napi\node_modules\ref-napi
> node-gyp-build

D:\WorkSpace\StudySpace\electron-quick-start\node_modules\ref-array-napi\node_modules\ref-napi>if not defined npm_config_node_gyp (node "D:\SoftWare\nvm\v11.10.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\SoftWare\nvm\v11.10.0\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:427:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/next_tick.js:76:17)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "D:\\SoftWare\\nodejs\\node.exe" "D:\\SoftWare\\nvm\\v11.10.0\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\WorkSpace\StudySpace\electron-quick-start\node_modules\ref-array-napi\node_modules\ref-napi
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ref-napi@3.0.3 install: `node-gyp-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ref-napi@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\SoftWare\nodejs\node_modules\npm\node_cache\_logs\2022-07-27T02_04_37_024Z-debug.log

please help me

**Comment by gintoki94** [comment]
Done.
update node-gyp to 8.3.0 and execute this command to fix it:
npm config set msvs_version 2019
