### ISSUE TITLE
Error 7 on yarn install

### ISSUE THREAD

**Issue by ahmedfatehi** [nodejs/node-gyp#2710]
I'm tried to use yarn install for my project it gives me This is a bug in `node-gyp`, `error 7`, I tried all available solutions of installing `node-sass` and `node-gyp` globally, also updates but without success. 

* **Node Version**: 14.16.1
* **NPM Version**: 6.14.12
* **YARN Version**: 1.22.19
* **Platform**: 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
System Type:               x64-based PC

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "laravel-mix > img-loader@3.0.0" has unmet peer dependency "imagemin@^5.0.0".
[4/4] Building fresh packages...
[-/2] ⠈ waiting...
error C:\laragon\www\tujarr\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\laragon\www\tujarr\node_modules\node-sass
Output:
Building: C:\laragon\bin\nodejs\node-v14\node.exe C:\laragon\www\tujarr\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\laragon\\bin\\nodejs\\node-v14\\node.exe',
gyp verb cli   'C:\\laragon\\www\\tujarr\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.16.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\laragon\bin\python\python-2.7.13\python2.EXE
gyp verb check python version `C:\laragon\bin\python\python-2.7.13\python2.EXE -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.16.1
gyp verb command install [ '14.16.1' ]
gyp verb install input version string "14.16.1"
gyp verb install installing version: 14.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.16.1
gyp verb build dir attempting to create "build" dir: C:\laragon\www\tujarr\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\laragon\www\tujarr\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\laragon\www\tujarr\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\laragon\www\tujarr\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\laragon\www\tujarr\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\laragon\bin\python\python-2.7.13\python2.EXE
gyp info spawn args [
gyp info spawn args   'C:\\laragon\\www\\tujarr\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\laragon\\www\\tujarr\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\laragon\\www\\tujarr\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\moham\\.node-gyp\\14.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\moham\\.node-gyp\\14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\laragon\\www\\tujarr\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\moham\\.node-gyp\\14.16.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\laragon\\www\\tujarr\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\laragon\\www\\tujarr\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\moham\.node-gyp\14.16.1
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\laragon\\bin\\nodejs\\node-v14\\node.exe" "C:\\laragon\\www\\tujarr\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\laragon\www\tujarr\node_modules\node-sass
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7

Usage: yarn install
```

</details>

**Comment by cclauss** [comment]
> gyp info using node-gyp@3.8.0

https://github.com/nodejs/node-gyp/releases is v9.1.0

https://github.com/nodejs/node-gyp/tree/main/docs#readme
