### ISSUE TITLE
Compilation error unistd.h on linux mint on node-gyp v5.1.0

### ISSUE THREAD

**Issue by luiscontrerasm** [nodejs/node-gyp#2715]
Im trying to do a yarn install in my project and im gettint this error in 2 different services
```

warning " > ts-jest@26.2.0" has incorrect peer dependency "typescript@>=3.8 <4.0".
[4/4] Building fresh packages...
[1/4] ⠠ @nestjs/core
[-/4] ⠠ waiting...
[3/4] ⠠ @nestjs/core
error /home/luis/postclick/packages/user-service/node_modules/mmmagic: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/luis/postclick/packages/user-service/node_modules/mmmagic
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.20.0 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/luis/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/luis/postclick/packages/user-service/node_modules/mmmagic/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/luis/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/luis/.cache/node-gyp/14.20.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/luis/.cache/node-gyp/14.20.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/luis/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/luis/.cache/node-gyp/14.20.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/luis/postclick/packages/user-service/node_modules/mmmagic',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/luis/postclick/packages/user-service/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
In file included from ../deps/libmagic/src/apprentice.c:32:
../deps/libmagic/src/file.h:75:11: fatal error: unistd.h: No such file or directory
   75 | # include <unistd.h>
      |           ^~~~~~~~~~
compilation terminated.
make: *** [deps/libmagic/libmagic.target.mk:143: Release/obj.target/libmagic/deps/libmagic/src/apprentice.o] Error 1
make: Leaving directory '/home/luis/postclick/packages/user-service/node_modules/mmmagic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/luis/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.15.0-43-generic
gyp ERR! command "/home/luis/.nvm/versions/node/v14.20.0/bin/node" "/home/luis/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/luis/postclick/packages/user-service/node_modules/mmmagic
gyp ERR! node -v v14.20.0
```

Node v14.20.0  & npm v6.14.17
Platform: Linux Mint
Compiler 9.4.0
* **Module**:  node-gyp

**Comment by cclauss** [comment]
`node-gyp@5.1.0` and `Python 2` are both no longer supported.
