### ISSUE TITLE
node-gyp imcompatibility with lin

### ISSUE THREAD

**Issue by luiscontrerasm** [nodejs/node-gyp#2716]
* **Node Version**: v14.20.0 & npm v6.14.7
* **Platform**: Linux Mint 20.3
* **Compiler**: 9.4.0
* **Module**: node-gyp

Trying to compile is impossible. i was told python 2 was unavailable as well as node-gyp below 9.1.0

```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
$ node-gyp rebuild
[###########################################################################################################################################################################################] 187/187gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@14.20.0 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/luis/postclick/packages/user-service/node_modules/mmmagic/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/luis/postclick/packages/user-service/node_modules/mmmagic/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/luis/postclick/packages/user-service/node_modules/mmmagic/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/luis/.cache/node-gyp/14.20.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/luis/.cache/node-gyp/14.20.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/luis/postclick/packages/user-service/node_modules/mmmagic/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/luis/.cache/node-gyp/14.20.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/luis/postclick/packages/user-service/node_modules/mmmagic',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/luis/postclick/packages/user-service/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
In file included from ../deps/libmagic/src/apprentice.c:32:
../deps/libmagic/src/file.h:75:11: fatal error: unistd.h: No such file or directory
   75 | # include <unistd.h>
      |           ^~~~~~~~~~
compilation terminated.
make: *** [deps/libmagic/libmagic.target.mk:143: Release/obj.target/libmagic/deps/libmagic/src/apprentice.o] Error 1
make: Leaving directory '/home/luis/postclick/packages/user-service/node_modules/mmmagic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/luis/postclick/packages/user-service/node_modules/mmmagic/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.15.0-43-generic
gyp ERR! command "/home/luis/.nvm/versions/node/v14.20.0/bin/node" "/home/luis/postclick/packages/user-service/node_modules/mmmagic/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/luis/postclick/packages/user-service/node_modules/mmmagic
gyp ERR! node -v v14.20.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
error Command failed with exit code 1.




```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/luis/.nvm/versions/node/v14.20.0/bin/node',
npm verb cli   '/home/luis/.nvm/versions/node/v14.20.0/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'output'
npm verb cli ]
npm info using npm@6.14.17
npm info using node@v14.20.0
```

**Comment by qeleb** [comment]
+1

**Comment by cclauss** [comment]
@mscdex Do you have any hints on this [mmmagic](https://github.com/mscdex/mmmagic/blob/master/deps/libmagic/src/apprentice.c) issue?
* https://github.com/nodejs/node-gyp/search?q=mmmagic&type=issues
