### ISSUE TITLE
Npm Install

### ISSUE THREAD

**Issue by hamzadahmani** [nodejs/node-gyp#2737]
error on npm install I follow all instructions 
node -v 16.x.x
npm -v 8.13

4802 verbose stack Error: command failed
4802 verbose stack     at ChildProcess.<anonymous> (C:\Users\21625\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
4802 verbose stack     at ChildProcess.emit (node:events:390:28)
4802 verbose stack     at maybeClose (node:internal/child_process:1064:16)
4802 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
4803 verbose pkgid java@0.8.0
4804 verbose cwd C:\Users\21625\Desktop\bulldozer\regard-action-backend
4805 verbose Windows_NT 10.0.22621
4806 verbose node v16.13.2
4807 verbose npm  v8.13.0
4808 error code 1
4809 error path C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java
4810 error command failed
4811 error command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\21625\AppData\Local\Temp\install-1664098562277.cmd
4812 error Les projets sont g n r s individuellement dans cette solution. Pour activer la g n ration en parall le, ajoutez le commutateur "-m".
4812 error   java.cpp
4812 error C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java\src\java.h(7,10): fatal  error C1083: Impossible d'ouvrir le fichier include : 'jni.h' : No such file or directory [C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java\build\nodejavabridge_bindings.vcxproj]
4813 error gyp info it worked if it ends with ok
4813 error gyp info using node-gyp@9.0.0
4813 error gyp info using node@16.13.2 | win32 | x64
4813 error gyp info find Python using Python version 3.10.7 found at "C:\Users\21625\AppData\Local\Programs\Python\Python310\python.exe"
4813 error gyp info find VS using VS2022 (17.3.32901.215) found at:
4813 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
4813 error gyp info find VS run with --verbose for detailed information
4813 error gyp info spawn C:\Users\21625\AppData\Local\Programs\Python\Python310\python.exe
4813 error gyp info spawn args [
4813 error gyp info spawn args   'C:\\Users\\21625\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
4813 error gyp info spawn args   'binding.gyp',
4813 error gyp info spawn args   '-f',
4813 error gyp info spawn args   'msvs',
4813 error gyp info spawn args   '-I',
4813 error gyp info spawn args   'C:\\Users\\21625\\Desktop\\bulldozer\\regard-action-backend\\node_modules\\java\\build\\config.gypi',
4813 error gyp info spawn args   '-I',
4813 error gyp info spawn args   'C:\\Users\\21625\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
4813 error gyp info spawn args   '-I',
4813 error gyp info spawn args   'C:\\Users\\21625\\AppData\\Local\\node-gyp\\Cache\\16.13.2\\include\\node\\common.gypi',
4813 error gyp info spawn args   '-Dlibrary=shared_library',
4813 error gyp info spawn args   '-Dvisibility=default',
4813 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\21625\\AppData\\Local\\node-gyp\\Cache\\16.13.2',
4813 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\21625\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
4813 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\21625\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.2\\\\<(target_arch)\\\\node.lib',
4813 error gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\21625\\Desktop\\bulldozer\\regard-action-backend\\node_modules\\java',
4813 error gyp info spawn args   '-Dnode_engine=v8',
4813 error gyp info spawn args   '--depth=.',
4813 error gyp info spawn args   '--no-parallel',
4813 error gyp info spawn args   '--generator-output',
4813 error gyp info spawn args   'C:\\Users\\21625\\Desktop\\bulldozer\\regard-action-backend\\node_modules\\java\\build',
4813 error gyp info spawn args   '-Goutput_dir=.'
4813 error gyp info spawn args ]
4813 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
4813 error gyp info spawn args [
4813 error gyp info spawn args   'build/binding.sln',
4813 error gyp info spawn args   '/clp:Verbosity=minimal',
4813 error gyp info spawn args   '/nologo',
4813 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
4813 error gyp info spawn args ]
4813 error gyp ERR! build error 
4813 error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
4813 error gyp ERR! stack     at ChildProcess.onExit (C:\Users\21625\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
4813 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
4813 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
4813 error gyp ERR! System Windows_NT 10.0.22621
4813 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\21625\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
4813 error gyp ERR! cwd C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java
4813 error gyp ERR! node -v v16.13.2
4813 error gyp ERR! node-gyp -v v9.0.0
4813 error gyp ERR! not ok
4814 verbose exit 1
4815 timing npm Completed in 61748ms
4816 verbose unfinished npm timer reify 1664098506105
4817 verbose unfinished npm timer reify:build 1664098562150
4818 verbose unfinished npm timer build 1664098562154
4819 verbose unfinished npm timer build:deps 1664098562154
4820 verbose unfinished npm timer build:run:install 1664098562265
4821 verbose unfinished npm timer build:run:install:node_modules/java 1664098562277
4822 verbose code 1
4823 error A complete log of this run can be found in:
4823 error     C:\Users\21625\AppData\Local\npm-cache\_logs\2022-09-25T09_35_05_964Z-debug-0.log

**Comment by cclauss** [comment]
Looks like `Java` trouble to me...
```
4809 error path C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java
4810 error command failed
4811 error command C:\WINDOWS\system32\cmd.exe /d /s /c
     C:\Users\21625\AppData\Local\Temp\install-1664098562277.cmd
4812 error Les projets sont g n r s individuellement dans cette solution. Pour activer la g n ration en
     parall le, ajoutez le commutateur "-m".
4812 error java.cpp
4812 error C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java\src\java.h(7,10):
     fatal error C1083: Impossible d'ouvrir le fichier include : 'jni.h' : No such file or directory
     [C:\Users\21625\Desktop\bulldozer\regard-action-backend\node_modules\java\build\nodejavabridge_bindings.vcxproj]
```

**Comment by hamzadahmani** [comment]
javac 19 installed

**Comment by StefanStojanovic** [comment]
This issue seems no longer relevant as it uses a no longer supported version of Node and has been stale for a long time. If there are no objections, I will close this issue next Mon-Tue. In case something similar happens again please open a new issue.
