### ISSUE TITLE
Doesn't build on NodeJS 19.0.1

### ISSUE THREAD

**Issue by ThatOneCalculator** [nodejs/node-gyp#2757]
Please look thru your error log for the string `gyp info using node-gyp@` and if the version number is less than the [current release of node-gyp](https://github.com/nodejs/node-gyp/releases) then __please upgrade__ using the instructions at https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md and try your command again.

Requests for help with [`node-sass` are very common](https://github.com/nodejs/node-gyp/issues?q=label%3A%22Node+Sass+--%3E+Dart+Sass%22). Please be aware that this package is deprecated, you should seek alternatives and avoid opening new issues about it here.

* **Node Version**: v19.0.1
* **Platform**: Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* **Compiler**: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
* **Module**: re2

<details><summary>Verbose output (from npm or node-gyp):</summary>
 
```
➤ YN0008: │ esbuild@npm:0.14.54 must be rebuilt because its dependency tree changed
➤ YN0009: │ re2@npm:1.17.7 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6a01c75b/build.log)
➤ YN0000: └ Completed in 24s 261ms
➤ YN0000: Failed with errors in 46s 646ms
➜  calckey git:(develop) ✗ cat /tmp/xfs-6a01c75b/build.log
# This file contains the result of Yarn building a package (re2@npm:1.17.7)
# Script name: install

Trying https://github.com/uhop/node-re2/releases/download/1.17.7/linux-x64-111.br ...
Trying https://github.com/uhop/node-re2/releases/download/1.17.7/linux-x64-111.gz ...
Building locally ...

> re2@1.17.7 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@19.0.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp http 500 https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500  status code downloading checksum
gyp ERR! stack     at downloadShasums (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:214:15)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
gyp ERR! stack     at async Promise.all (index 1)
gyp ERR! stack     at async go (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:189:5)
gyp ERR! stack     at async install (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
gyp ERR! System Linux 5.4.0-122-generic
gyp ERR! command "/home/misskey/.nvm/versions/node/v19.0.1/bin/node" "/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/misskey/calckey/node_modules/.store/re2-npm-1.17.7-02f9dd5be3/node_modules/re2
gyp ERR! node -v v19.0.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.0.1

> re2@1.17.7 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@19.0.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp http 500 https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500  status code downloading checksum
gyp ERR! stack     at downloadShasums (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:214:15)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
gyp ERR! stack     at async Promise.all (index 1)
gyp ERR! stack     at async go (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:189:5)
gyp ERR! stack     at async install (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
gyp ERR! System Linux 5.4.0-122-generic
gyp ERR! command "/home/misskey/.nvm/versions/node/v19.0.1/bin/node" "/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/misskey/calckey/node_modules/.store/re2-npm-1.17.7-02f9dd5be3/node_modules/re2
gyp ERR! node -v v19.0.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
➜  calckey git:(develop) ✗  "/home/misskey/.nvm/versions/node/v19.0.1/bin/node" "/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@19.0.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp http 500 https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500  status code downloading checksum
gyp ERR! stack     at downloadShasums (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:214:15)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
gyp ERR! stack     at async Promise.all (index 1)
gyp ERR! stack     at async go (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:189:5)
gyp ERR! stack     at async install (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
gyp ERR! System Linux 5.4.0-122-generic
gyp ERR! command "/home/misskey/.nvm/versions/node/v19.0.1/bin/node" "/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/misskey/calckey
gyp ERR! node -v v19.0.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
```
</details>

> 
```
gyp http GET https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v19.0.1/node-v19.0.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp http 500 https://nodejs.org/download/release/v19.0.1/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500  status code downloading checksum
gyp ERR! stack     at downloadShasums (/home/misskey/.nvm/versions/node/v19.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:214:15)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
gyp ERR! stack     at async Promise.all (index 1)
```

Seems to be a checksum error.

**Comment by JeDaYoshi** [comment]
This seems to happen randomly. It worked for me after ~3-4 tries, unsure of what's wrong and whether it's something specific of `node-gyp` or something with `nodejs.org` itself not liking Node.js v19.
