### ISSUE TITLE
node-gcstats install error

### ISSUE THREAD

**Issue by ezequieldelucaey** [nodejs/node-gyp#2759]
I have an issue installing npm packages related to node-gyp.
I have the following software installed:

Microsoft Windows [Version 10.0.19044.2130]
Python version 3.10.5
NodeJS Version 18.12.0
npm version 8.19.2
node-gyp Version 9.1.0
Visual Studio Community 2022
Visual Studio Build-Tools 2017
```
npm ERR! code 1
npm ERR! path C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe c:\Users\ezequiel.de-luca\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats\build\gcstats\v1.5.7\Release\node-v83-win32-x64-unknown\gcstats.node --module_name=gcstats --module_path=C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats\build\gcstats\v1.5.7\Release\node-v83-win32-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@14.19.3 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats\build\gcstats\v1.5.7\Release\node-v83-win32-x64-unknown\gcstats.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/adnanrahic/node-gcstats/releases/download/1.5.7/gcstats/v1.5.7/Release/node-v83-win32-x64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/adnanrahic/node-gcstats/releases/download/1.5.7/gcstats/v1.5.7/Release/node-v83-win32-x64-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @sematext/gc-stats@1.5.7 and node@14.19.3 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/adnanrahic/node-gcstats/releases/download/1.5.7/gcstats/v1.5.7/Release/node-v83-win32-x64-unknown.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@14.19.3 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@14.19.3 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "C:\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v14.19.3/node-v14.19.3-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v14.19.3/node-v14.19.3-headers.tar.gz failed, reason: unable to get local issuer certificate
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (c:\Users\ezequiel.de-luca\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:475:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (events.js:412:35)
npm ERR! gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:106:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\Users\\ezequiel.de-luca\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\ezequiel.de-luca\\NoBackUp\\Cobani\\Repos\\cobani-hq\\cobani-api-agents\\node_modules\\gc-stats\\build\\gcstats\\v1.5.7\\Release\\node-v83-win32-x64-unknown\\gcstats.node" "--module_name=gcstats" "--module_path=C:\\Users\\ezequiel.de-luca\\NoBackUp\\Cobani\\Repos\\cobani-hq\\cobani-api-agents\\node_modules\\gc-stats\\build\\gcstats\\v1.5.7\\Release\\node-v83-win32-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
npm ERR! gyp ERR! cwd C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats
npm ERR! gyp ERR! node -v v14.19.3
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe c:\Users\ezequiel.de-luca\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats\build\gcstats\v1.5.7\Release\node-v83-win32-x64-unknown\gcstats.node --module_name=gcstats --module_path=C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats\build\gcstats\v1.5.7\Release\node-v83-win32-x64d_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ezequiel.de-luca\\NoBackUp\\Cobani\\Repos\\cobani-hq\\cobani-api-agents\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\ezequiel.de-luca\NoBackUp\Cobani\Repos\cobani-hq\cobani-api-agents\node_modules\gc-stats
npm ERR! node-pre-gyp ERR! node -v v14.19.3
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ezequiel.de-luca\AppData\Local\npm-cache\_logs\2022-11-07T20_37_11_107Z-debug-0.log
```

What most call my attention is the following:
1) **npm ERR! node-pre-gyp http GET https://github.com/adnanrahic/node-gcstats/releases/download/1.5.7/gcstats/v1.5.7/Release/node-v83-win32-x64-unknown.tar.gz** If you try to browse it the address doesn't exist
2) **npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v14.19.3/node-v14.19.3-headers.tar.gz failed, reason: unable to get local issuer certificate**. To mitigate this I performed the following:
  a) npm config set strict-ssl=false
  b) npm config set cafile=<my root certificate>
  c) Set $env:NODE_EXTRA_CA_CERTS = C:\MAINTENANCE\Installers\ZScaler\ZscalerRootCA.pem
  d) Disable ZScaler
  e) Disable Antivirus

Do you have any idea how to fix this?

**Comment by cclauss** [comment]
https://github.com/adnanrahic/node-gcstats/releases

**Comment by ezequieldelucaey** [comment]
> https://github.com/adnanrahic/node-gcstats/releases
That's the version references in the packages.json:
**"gc-stats": "npm:@sematext/gc-stats@^1.5.7",**

**Comment by Hiba97** [comment]
Hi, are there any updates on the fix here please? I am having a similar issue using same node and node-gyp versions. Thanks!

**Comment by cclauss** [comment]
[Their tests](https://github.com/adnanrahic/node-gcstats/pull/14/files) run on old versions of Node.js and legacy Python.

**Comment by cclauss** [comment]
Closing `node-pre-gyp` is unmaintained.
