### ISSUE TITLE
node 18.12.1 and node-gyp 9.3.0 is not ok

### ISSUE THREAD

**Issue by rohail411** [nodejs/node-gyp#2779]
I'm updating my project from node16 to node 18.12.1 but getting this error please assist me.
My current versions:
node: 18.12.1
npm: 9.2.0
python: 3.10

`npm ERR! code 1
npm ERR! path /Users/rohail/Documents/Github/project/node_modules/desjs
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.12.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! gyp WARN read config.gypi ENOENT: no such file or directory, open '/node/src/include/node/config.gypi'
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/rohail/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/rohail/Documents/Github/project/node_modules/desjs/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/rohail/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/node/src/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/node/src/',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/rohail-invozone/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/node/src/$(Configuration)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/rohail-invozone/Documents/Github/ztn-web/node_modules/desjs',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: /node/src/common.gypi not found (cwd: /Users/rohail/Documents/Github/project/node_modules/desjs) while reading includes of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/rohail/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/Users/rohail/.nvm/versions/node/v18.12.1/bin/node" "/Users/rohail-invozone/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/rohail/Documents/Github/project/node_modules/desjs
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok`

**Comment by cclauss** [comment]
> npm ERR! gyp: /node/src/common.gypi not found (cwd: /Users/rohail/Documents/Github/project/node_modules/desjs) while reading includes of binding.gyp while trying to load binding.gyp

It seems to be missing https://github.com/indutny/des.js but that module seems a bit out-of-date.

**Comment by uccmen** [comment]
did the latest release break something?

I'm getting similar error as well

```
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/4] ⢀ ref
[-/4] ⢀ waiting...
[-/4] ⢀ waiting...
error /Users/usivaguru/Documents/remotes/uccmen/makemore-malaysiannames/node_modules/ref: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/usivaguru/Documents/remotes/uccmen/makemore-malaysiannames/node_modules/ref
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.19.0 | darwin | x64
gyp info find Python using Python version 3.10.9 found at "/usr/local/opt/python@3.10/bin/python3.10"
gyp info spawn /usr/local/opt/python@3.10/bin/python3.10
gyp info spawn args [
gyp info spawn args   '/Users/usivaguru/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/usivaguru/Documents/remotes/uccmen/makemore-malaysiannames/node_modules/ref/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/usivaguru/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/usivaguru/Library/Caches/node-gyp/16.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/usivaguru/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/usivaguru/Library/Caches/node-gyp/16.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/usivaguru/Documents/remotes/uccmen/makemore-malaysiannames/node_modules/ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:222:43: error: too few arguments to function call, single argument 'isolate' was not specified
  bool persistent = info[3]->BooleanValue();
                    ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3096:8: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
       ^
../src/binding.cc:253:38: error: too few arguments to function call, single argument 'context' was not specified
  size_t size = info[2]->Uint32Value();
                ~~~~~~~~~~~~~~~~~~~~ ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
../src/binding.cc:253:10: error: no viable conversion from 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'size_t' (aka 'unsigned long')
  size_t size = info[2]->Uint32Value();
         ^      ~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:360:23: error: no matching constructor for initialization of 'String::Utf8Value'
    String::Utf8Value _str(in);
                      ^    ~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3588:5: note: candidate constructor not viable: no known conversion from 'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3581:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/binding.cc:447:23: error: no matching constructor for initialization of 'String::Utf8Value'
    String::Utf8Value _str(in);
                      ^    ~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3588:5: note: candidate constructor not viable: no known conversion from 'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3581:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/binding.cc:521:38: error: too few arguments to function call, single argument 'context' was not specified
  size_t size = info[1]->Uint32Value();
                ~~~~~~~~~~~~~~~~~~~~ ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
../src/binding.cc:521:10: error: no viable conversion from 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'size_t' (aka 'unsigned long')
  size_t size = info[1]->Uint32Value();
         ^      ~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:550:44: error: too few arguments to function call, single argument 'context' was not specified
  uint32_t numZeros = info[1]->Uint32Value();
                      ~~~~~~~~~~~~~~~~~~~~ ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3104:41: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                        ^
../src/binding.cc:550:12: error: no viable conversion from 'Maybe<uint32_t>' (aka 'Maybe<unsigned int>') to 'uint32_t' (aka 'unsigned int')
  uint32_t numZeros = info[1]->Uint32Value();
           ^          ~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:582:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int8, int8_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:583:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint8, uint8_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:584:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int16, int16_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:585:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint16, uint16_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:586:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int32, int32_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:587:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint32, uint32_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:588:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int64, int64_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:589:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint64, uint64_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:590:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(float, float);
  ^~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:591:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(double, double);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint32_t>(sizeof(type))));
  ~~~~~~^~~
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/usivaguru/Library/Caches/node-gyp/16.19.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/usivaguru/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.2.0
gyp ERR! command "/Users/usivaguru/.nvm/versions/node/v16.19.0/bin/node" "/Users/usivaguru/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/usivaguru/Documents/remotes/uccmen/makemore-malaysiannames/node_modules/ref
gyp ERR! node -v v16.19.0
```

**Comment by cclauss** [comment]
@uccmen I have deleted your comment because this issue is about Node.js v18 and you are not running that issue.  Please create a separate new issue.

**Comment by cclauss** [comment]
@rohail411 Did installing desjs fix this issue?
