### ISSUE TITLE
Node 16.15.1 - node-gyp fails to rebuild re2

### ISSUE THREAD

**Issue by fasenderos** [nodejs/node-gyp#2782]
Hi, my app has a dependency on [`@metascraper/helpers`](https://www.npmjs.com/package/@metascraper/helpers) which has a dependency on [`re2`](https://www.npmjs.com/package/re2). When i try to run `npm install` node-gyp fails to rebuild the re2 package with the error `npm ERR! g++: error: unrecognized command line option '-std=c++2a'; did you mean '-std=c++03'?`

* **Node Version**: 16.15.1
* **NPM Version**: 8.11.0
* **Platform**: Linux 4.14.294-220.533.amzn2.aarch64 # 1 SMP Thu Sep 29 01:01:24 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
* **Compiler**: gcc version 7.3.1 20180712 (Red Hat 7.3.1-15) (GCC)

<details><summary>Verbose output:</summary>

```
> npm install -g @scope/my-pkg
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! code 1
npm ERR! path /home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2
npm ERR! command failed
npm ERR! command sh -c install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild
npm ERR! Trying https://github.com/uhop/node-re2/releases/download/1.17.8/linux-arm64-93.br ...
npm ERR! Trying https://github.com/uhop/node-re2/releases/download/1.17.8/linux-arm64-93.gz ...
npm ERR! Building locally ...
npm ERR!
npm ERR! > re2@1.17.8 rebuild
npm ERR! > node-gyp rebuild
npm ERR!
npm ERR! make: Entering directory `/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2/build'
npm ERR!   CXX(target) Release/obj.target/re2/lib/addon.o
npm ERR! make: Leaving directory `/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2/build'
npm ERR!
npm ERR! > re2@1.17.8 rebuild
npm ERR! > node-gyp rebuild
npm ERR!
npm ERR! make: Entering directory `/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2/build'
npm ERR!   CXX(target) Release/obj.target/re2/lib/addon.o
npm ERR! make: Leaving directory `/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@16.15.1 | linux | arm64
npm ERR! gyp info find Python using Python version 3.7.15 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.cache/node-gyp/16.15.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/16.15.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/16.15.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=c++2a’; did you mean ‘-std=c++03’?
npm ERR! make: *** [Release/obj.target/re2/lib/addon.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 4.14.294-220.533.amzn2.aarch64
npm ERR! gyp ERR! command "/home/ec2-user/.nvm/versions/node/v16.15.1/bin/node" "/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2
npm ERR! gyp ERR! node -v v16.15.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node:internal/process/promises:279
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
npm ERR!   code: 'ERR_UNHANDLED_REJECTION'
npm ERR! }
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@16.15.1 | linux | arm64
npm ERR! gyp info find Python using Python version 3.7.15 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.cache/node-gyp/16.15.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/16.15.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/16.15.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=c++2a’; did you mean ‘-std=c++03’?
npm ERR! make: *** [Release/obj.target/re2/lib/addon.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 4.14.294-220.533.amzn2.aarch64
npm ERR! gyp ERR! command "/home/ec2-user/.nvm/versions/node/v16.15.1/bin/node" "/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@scope/my-pkg/node_modules/re2
npm ERR! gyp ERR! node -v v16.15.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
```

</details>

**Comment by richardlau** [comment]
> * **Compiler**: gcc version 7.3.1 20180712 (Red Hat 7.3.1-15) (GCC)

You'll need to be on at least gcc 8 for c++2a support.
