### ISSUE TITLE
node 14.14.0 and node-gyp 9.3.1 is not ok

### ISSUE THREAD

**Issue by rassokhina-e** [nodejs/node-gyp#2784]
Hi there!
We are using GitHub actions to make Windows releases of our electron app. We build the app for both platforms x64 and win32. There is an issue related to node-gyp I guess, please assist me.

Our current versions:
node: 14.14.0
node-gyp 9.3.1
npm: 6.14.8

```
Run npm install

> drivelist@9.1.0 install D:\a\...\node_modules\drivelist
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=[6](https://github.com/.../actions/runs/3845129739/jobs/6548914764#step:7:7).1.2 runtime=electron arch=x64 libc= platform=win32)

D:\a\...\node_modules\drivelist>if not defined npm_config_node_gyp (node "C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: TAR_BAD_ARCHIVE: Unrecognized archive format
gyp ERR! stack     at Unpack.warn (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\warn-mixin.js:21:40)
gyp ERR! stack     at Unpack.warn (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\unpack.js:229:18)
gyp ERR! stack     at Unpack.<anonymous> (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\parse.js:83:14)
...
gyp ERR! stack     at Unpack.[emit] (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\parse.js:303:12)
gyp ERR! stack     at Unpack.[maybeEnd] (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\parse.js:426:17)
gyp ERR! stack     at Unpack.[consumeChunk] 
...
gyp ERR! stack     at Unpack.write (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\parse.js:385:25)
gyp ERR! stack     at Unpack.end (C:\hostedtoolcache\windows\node\14.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node_modules\tar\lib\parse.js:505:14)
gyp ERR! stack     at ShaSum.onend (_stream_readable.js:684:10)
gyp ERR! stack     at Object.onceWrapper (events.js:421:28)
gyp ERR! stack     at ShaSum.emit (events.js:327:22)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1327:12)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\14.14.0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\14.14.0\\x64\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\...\node_modules\drivelist
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v[9](https://github.com/.../actions/runs/3845129739/jobs/6548914764#step:7:10).3.1
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules\@ffmpeg-installer\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules\@ffmpeg-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.4 (node_modules\@ffmpeg-installer\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules\@ffmpeg-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules\@ffmpeg-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules\@ffmpeg-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-arm@4.3.2 (node_modules\@ffprobe-installer\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-arm@4.3.2: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/darwin-x64@4.1.0 (node_modules\@ffprobe-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-ia32@4.1.0 (node_modules\@ffprobe-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-arm64@4.3.2 (node_modules\@ffprobe-installer\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-arm64@4.3.2: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-x64@4.1.0 (node_modules\@ffprobe-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/win32-ia32@4.1.0 (node_modules\@ffprobe-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dmg-license@1.0.[11](https://github.com/...actions/runs/3845129739/jobs/6548914764#step:7:12) (node_modules\dmg-license):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for dmg-license@1.0.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.[13](https://github.com/.../actions/runs/3845129739/jobs/6548914764#step:7:14) (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drivelist@9.1.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the drivelist@9.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
Error: Process completed with exit code 1.
```

**Comment by StefanStojanovic** [comment]
This has been stale for a long time so I'll close it. If still relevant, feel free to reopen.
