### ISSUE TITLE
Any way to find the point issue occured with binding.gyp easily

### ISSUE THREAD

**Issue by seia-soto** [nodejs/node-gyp#2805]
* **Node Version**: v18.10.0 (npm v8.19.2)
* **Platform**: Darwin aa-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
* **Compiler**: Apple clang version 14.0.0 (clang-1400.0.29.202)
* **Module**: Internal

<details><summary>Verbose output (from npm or node-gyp):</summary>

Note that the command is failing at `node-gyp configure` stage.

```
$ pnpm node-pre-gyp rebuild
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@18.10.0 | darwin | arm64
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.10.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.10.0 | darwin | arm64
gyp info find Python using Python version 3.11.0 found at "/Users/aa/.pyenv/versions/3.11.0rc2/bin/python3"
gyp info spawn /Users/aa/.pyenv/versions/3.11.0rc2/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aa/local/repos/embeddable-wg/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aa/Library/Caches/node-gyp/18.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aa/Library/Caches/node-gyp/18.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aa/Library/Caches/node-gyp/18.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/aa/local/repos/embeddable-wg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 686, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 678, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 645, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 155, in Load
    result = gyp.input.Load(
             ^^^^^^^^^^^^^^^
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3024, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1653, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get("variables", {}).get("link_dependency", 0):
       ~~~~~~~^^^
KeyError: 'binding.gyp:embeddable-wg#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/aa/.nvm/versions/node/v18.10.0/bin/node" "/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/bin/node-gyp.js" "configure" "--module=/Users/aa/local/repos/embeddable-wg/lib/binding/napi-v3/embeddable-wg.node" "--module_name=embeddable-wg" "--module_path=/Users/aa/local/repos/embeddable-wg/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Users/aa/local/repos/embeddable-wg
gyp ERR! node -v v18.10.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/aa/.nvm/versions/node/v18.10.0/bin/node /Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/bin/node-gyp.js configure --module=/Users/aa/local/repos/embeddable-wg/lib/binding/napi-v3/embeddable-wg.node --module_name=embeddable-wg --module_path=/Users/aa/local/repos/embeddable-wg/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.10/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 22.3.0
node-pre-gyp ERR! command "/Users/aa/.nvm/versions/node/v18.10.0/bin/node" "/Users/aa/local/repos/embeddable-wg/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "rebuild"
node-pre-gyp ERR! cwd /Users/aa/local/repos/embeddable-wg
node-pre-gyp ERR! node -v v18.10.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
Failed to execute '/Users/aa/.nvm/versions/node/v18.10.0/bin/node /Users/aa/local/repos/embeddable-wg/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/bin/node-gyp.js configure --module=/Users/aa/local/repos/embeddable-wg/lib/binding/napi-v3/embeddable-wg.node --module_name=embeddable-wg --module_path=/Users/aa/local/repos/embeddable-wg/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
```

</details>

<details><summary>binding.gyp, package.json:</summary>

```json
{
    "target_defaults": {
        "configurations": {
            "Release": {
                "defines+": ["_FORTIFY_SOURCE=2"]
            }
        }
    },
    "targets": [
        {
            "target_name": "EmbeddableWireguardExtension",
            "defines": [
                "NAPI_VERSION=<(napi_build_version)",
            ],
            "sources": [
                "./bindings/EmbeddableWireguardExtension.c",
                "./bindings/napi_utils.c",
                "./bindings/libraries/wireguard.c"
            ]
        },
        {
            "target_name": "action_after_build",
            "type": "none",
            "dependencies": ["<(module_name)"],
            "copies": [
                {
                    "files": ["<(PRODUCT_DIR)/<(module_name).node"],
                    "destination": "<(module_path)"
                }
            ]
        }
    ]
}
```

```json
{
  "dependencies": {
    "@mapbox/node-pre-gyp": "^1.0.10",
    "node-api-headers": "^0.0.2",
    "node-gyp": "^9.3.1"
  }
}
```

</details>

Sorry for filing issue with this trivial thing. I checked out many issues but couldn't find what's problem in my binding.gyp yet. The only error line hinted me is `KeyError: 'binding.gyp:embeddable-wg#target'`, and I think it's literally insufficient information to fix. Is there any tip to fix this?

**Comment by seia-soto** [comment]
Resolved after checking out the undeclared target `<(module_name)` in action_after_build step.

**Comment by cclauss** [comment]
Nice work in finding and fixing the problem.

> I think it's literally insufficient information to fix.

Above that error is a 15-line Python stack track that shows exactly how the error occurred.

As I have said numerous times, if node-gyp was re-written in JavaScript then this community would have a much easier time understanding and fixing bugs.

**Comment by seia-soto** [comment]
Thanks for your saying. I fully agree with you. I hope this issue can be help future developers. 👍
