### ISSUE TITLE
Get UNCAUGHT Exception when installing angular cli 14.2.11

### ISSUE THREAD

**Issue by brianreinhold** [nodejs/node-gyp#2821]
<!--
I have an older version of an angular project I am trying to build and then update.

node --version gives v14.18.1
node-gyp is 3.8.0

The node-gyp being used is that of nodejs, it is not installed globally. IT is old, I tried to update it in nodejs to the latest but it did not work, it is still at 3.8.0.

It appears to be failing on trying to build the node-sass modules

log of just the error:
`
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Users\\brian\\AppData\\Local\\nvs\\node\\14.18.1\\x64\\node.exe" "E:\\projects\\exchangex\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "-
-libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
`
Full log below:
`
E:\projects\exchangex>npm install @angular/cli@14.2.11
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

> node-sass@4.9.3 install E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.3 postinstall E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/build.js

Building: C:\Users\brian\AppData\Local\nvs\node\14.18.1\x64\node.exe E:\projects\exchangex\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflag
s= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Users\\brian\\AppData\\Local\\nvs\\node\\14.18.1\\x64\\node.exe',
gyp verb cli   'E:\\projects\\exchangex\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 E:\Python27\python2.EXE
gyp verb check python version `E:\Python27\python2.EXE -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.18.1
gyp verb command install [ '14.18.1' ]
gyp verb install input version string "14.18.1"
gyp verb install installing version: 14.18.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.18.1
gyp verb build dir attempting to create "build" dir: E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn E:\Python27\python2.EXE
gyp info spawn args [
gyp info spawn args   'E:\\projects\\exchangex\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\projects\\exchangex\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\projects\\exchangex\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\brian\\.node-gyp\\14.18.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\brian\\.node-gyp\\14.18.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\projects\\exchangex\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\brian\\.node-gyp\\14.18.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\projects\\exchangex\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\projects\\exchangex\\node_modules\\@angular-devkit\\build-angular\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\brian\.node-gyp\14.18.1
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Users\\brian\\AppData\\Local\\nvs\\node\\14.18.1\\x64\\node.exe" "E:\\projects\\exchangex\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "-
-libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\projects\exchangex\node_modules\@angular-devkit\build-angular\node_modules\node-sass
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
`

**Comment by brianreinhold** [comment]
sUBMISSION FAILED - If I could remove this I would. Lots of work and typing down the tube
