### ISSUE TITLE
Failed to compile node-sass

### ISSUE THREAD

**Issue by denissabramovs** [nodejs/node-gyp#2831]
```
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/beck/.node-gyp/18.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/beck/.node-gyp/18.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/beck/.node-gyp/18.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
    None)
  File "/home/beck/.node-gyp/18.16.0/include/node/common.gypi", line 1
    e_data_file_flag%': 1
                        ^
SyntaxError: EOL while scanning string literal
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.19.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/beck/.cache/yarn/v6/.tmp/b1cd6e61c2079912c1bcd7ad6f4a4c3c.c81d5128a80c6ef02604b0aed4b5bb7009f6905d.prepare/node_modules/node-sass
gyp ERR! node -v v18.16.0
gyp ERR! node-gyp -v v3.8.0
```

**Comment by cclauss** [comment]
> gyp ERR! node-gyp -v v3.8.0

**Comment by denissabramovs** [comment]
Where is that fixed? In which version?

**Comment by cclauss** [comment]
When creating new issues, please read the text before deleting it.  That text explained that node-sass is dead.

**Comment by denissabramovs** [comment]
Thank you, didn't know they are dead.

**Comment by kevlarr** [comment]
Literally just ran into this, too - how is that `SyntaxError` from `/include/node/common.gypi` related to `node-sass` specifically?

**Comment by kevlarr** [comment]
Literally just ran into this, too - how is that `SyntaxError` from `/include/node/common.gypi` related to `node-sass` specifically @cclauss ?

**Comment by cclauss** [comment]
@kevlarr
1. Open a new issue.  --> https://github.com/nodejs/node-gyp/issues
2. Read ALL the text there.  Hint: You have two different problems with your setup but the solutions are described.
3. Please send all questions about `node-sass` to that team.
