### ISSUE TITLE
Invalid version number

### ISSUE THREAD

**Issue by minchopm** [nodejs/node-gyp#2895]
I am using Mac M1, Python 3.10, node 18.12.1 and I am having this error when I try to rebuild the leveldown package.
% `node-gyp rebuild --target arm64 --arch arm64`
```
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.12.1 | darwin | arm64
gyp info find Python using Python version 3.10.6 found at "/opt/local/bin/python3"
gyp ERR! configure error 
gyp ERR! stack Error: Invalid version number: true
gyp ERR! stack     at getNodeDir (/Users/minchomilev/.nvm/versions/node/v18.12.1/lib/node_modules/node-gyp/lib/configure.js:57:25)
gyp ERR! stack     at /Users/minchomilev/.nvm/versions/node/v18.12.1/lib/node_modules/node-gyp/lib/configure.js:31:7
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
gyp ERR! System Darwin 22.5.0
```

**Comment by cclauss** [comment]
https://github.com/Level/classic-level/releases Now has a v2 release.
