### ISSUE TITLE
gyp errors on npm install

### ISSUE THREAD

**Issue by conceptree** [nodejs/node-gyp#2972]
Hello,

I am currently getting an error in most of my installed node versions that goes from 14.16.0 up to 18 and latest 20.

I already tried most of the suggested fixs by the community that pass through the sass reinstallation and others. 

I have reinstalled the node-gyp@latest globally but didnt solved the problem.

* **Node Version**: 20.11.0 & NPM 10.2.4 
* **Platform**: Windows 10 Enterprise
* **Compiler**: ?
* **Module**: local-npm

<details><summary>npm install local-npm gyp errors</summary>

```
npm ERR! code 1
npm ERR! path C:\Users\X\Documents\dev\node-v20.11.0-win-x86\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Users\X\Documents\dev\python-3.12.1-embed-win32\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz
npm ERR! (node:195480) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
npm ERR! (Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
npm ERR! gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
npm ERR! gyp ERR! stack network settings.
npm ERR! gyp ERR! stack at go (C:\Users\X\Documents\dev\node-v20.11.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\lib\install.js:244:21)
npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! gyp ERR! stack at async install (C:\Users\X\Documents\dev\node-v20.11.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\lib\install.js:63:18)
npm ERR! gyp ERR! stack at async getNodeDir (C:\Users\X\Documents\dev\node-v20.11.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\lib\configure.js:53:7)
npm ERR! gyp ERR! stack at async run (C:\Users\X\Documents\dev\node-v20.11.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\bin\node-gyp.js:81:18)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Users\\X\\Documents\\dev\\node-v20.11.0-win-x86\\node.exe" "C:\\Users\\X\\Documents\\dev\\node-v20.11.0-win-x86\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\X\Documents\dev\node-v20.11.0-win-x86\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\X\AppData\Local\npm-cache\_logs\2024-01-26T13_43_18_167Z-debug-0.log
```
</details>

Hope to get some assitance or be pointed into possible solutions.

Thanks in advance.

**Comment by conceptree** [comment]
It seems to be happening on other npm installs now

`npm ERR! code 1
npm ERR! path C:\Users\T0202788\Documents\bitbucket\gdp-ui-toolkit\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@18.19.0 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Users\T0202788\Documents\dev\python-3.12.1-embed-win32\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.19.0/node-v18.19.0-headers.tar.gz
npm ERR! (node:4944) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
npm ERR! (Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
npm ERR! gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
npm ERR! gyp ERR! stack network settings.
npm ERR! gyp ERR! stack at go (C:\Users\T0202788\.nvm\versions\node\v18.19.0\node_modules\npm\node_modules\node-gyp\lib\install.js:244:21)
npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! gyp ERR! stack at async install (C:\Users\T0202788\.nvm\versions\node\v18.19.0\node_modules\npm\node_modules\node-gyp\lib\install.js:63:18)
npm ERR! gyp ERR! stack at async getNodeDir (C:\Users\T0202788\.nvm\versions\node\v18.19.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:53:7)
npm ERR! gyp ERR! stack at async run (C:\Users\T0202788\.nvm\versions\node\v18.19.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Users\\T0202788\\.nvm\\versions\\node\\v18.19.0\\node.exe" "C:\\Users\\T0202788\\.nvm\\versions\\node\\v18.19.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\T0202788\Documents\bitbucket\gdp-ui-toolkit\node_modules\deasync
npm ERR! gyp ERR! node -v v18.19.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok
npm ERR! Build failed

npm ERR! A complete log of this run can be found in: C:\Users\T0202788\AppData\Local\npm-cache\_logs\2024-01-26T14_01_46_997Z-debug-0.log`

**Comment by conceptree** [comment]
Just tried with v16.20.2 and works without problems! May help you out on understanding what might be wrong here...

**Comment by mursalin3sit** [comment]
You can check by running `npm install -g npm@8.10.0`

**Comment by rcerljenko** [comment]
same error... node v18.17

**Comment by rcerljenko** [comment]
10.4.0

**Comment by mursalin3sit** [comment]
> 10.4.0

You can try using NPM versions 10.2.4 into 8.10.0

**Comment by rcerljenko** [comment]
ok that could be a temp fix but i would prefer to use the latest npm if possible

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/issues?q=is%3Aissue+label%3ANODE_TLS_REJECT_UNAUTHORIZED

**Comment by Spendog** [comment]
> https://github.com/nodejs/node-gyp/issues?q=is%3Aissue+label%3ANODE_TLS_REJECT_UNAUTHORIZED

im confused.. what does this link provide. I'm also having the same issues as others described above

**Comment by cclauss** [comment]
That link provides a pointer to all the other issues in this repo about the same problem.

**Comment by conceptree** [comment]
@cclauss so does this confirms that the node tls rejection flag is the cause of the problem?

**Comment by bdkoder** [comment]
Facing same issues

**Comment by Tuscan-blue** [comment]
I met the same error. What should I do ?

**Comment by cclauss** [comment]
Are you all trying to install `leveldown` or some other module?

**Comment by Tuscan-blue** [comment]
@cclauss  I tried to install sqlite3....

**Comment by GourishettySairam** [comment]
https://stackoverflow.com/a/62096421/15046796 this worked for me

**Comment by Lightiiy** [comment]
> https://stackoverflow.com/a/62096421/15046796 this worked for me

this stackoverflow post seems unrelated to the issue, care to explain?

**Comment by Lightiiy** [comment]
> > > https://stackoverflow.com/a/62096421/15046796 this worked for me
> > 
> > 
> > this stackoverflow post seems unrelated to the issue, care to explain?
> 
> I am using Mac m1 chip laptop. I've recently updated to latest homebrew version. When I try to install node modules, there were these node gyp errors. So using the stackoverflow post above I was able to downgrade the homebrew version and the node modules were now installed successfully. So the solution that i posted above is for specifically Mac machines.

Ah, thank you for the clarification. With added context your comment can help out Mac users.

**Comment by cclauss** [comment]
@jeniasaigak The full error log will clarify that you have an out-of-date version of node-gyp.

**Comment by lumleon** [comment]
simply do 2 step:
1. sudo su
2. npm install -g node-gyp

Then re-run npm install,  all GOOD!!!!!

**Comment by cclauss** [comment]
It is highly recommended that you get out of `sudo su` mode asap with `exit` or `Ctrl+D`.  Failure to do so leaves your system open to lots of nasty, destructive commands.

**Comment by wuazhu** [comment]
I tried all the solutions in the comments, but none of them worked.
in the end, it works
step1: npm install node-gyp or add node-gyp to the package.json
step2: npm install
and it works!!! God Please!!!

**Comment by studentrk** [comment]
What solved it for me was downgrading to node version **v16.20.2**, use python version **3.9.0**

And I had to ran the following commands:

```
npm rebuild
rm -rf node_modules
npm cache clean --force
npm i --legacy-peer-deps
```

**Comment by cclauss** [comment]
Downgrading to an unsupported version of Node.is NOT recommended.
* https://nodejs.org/en/about/previous-releases

**Comment by brunoargolo** [comment]
I opened a pr https://github.com/npm/make-fetch-happen/pull/316 so make-fetch-happen respect NODE_TLS_REJECT_UNAUTHORIZED.
It will still does not respect other node variables such as NODE_EXTRA_CA_CERTS (which would be ideal for folks behind a corporate proxy).
