### ISSUE TITLE
tar.Extract is not a function

### ISSUE THREAD

**Issue by EranStockdale** [nodejs/node-gyp#3007]
* **Node Version**: Node v20.12.1 & NPM v10.5.1
* **Platform**: Microsoft Windows 11 Home 10.0.22631 N/A Build 22631 x64-based PC
* **Compiler**: MSBuild version 17.8.5+b5265ef37 for .NET Framework
* **Module**: `curses`

Just FYI I have already reinstalled NodeJS several times (and deleted the `nodejs` folder in `C:\Program Files`).

```
PS C:\Users\eranb\Desktop\AnimalDB> npm i curses --verbose
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\eranb\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@10.5.1
npm info using node@v20.12.1
npm verb title npm i curses
npm verb argv "i" "curses" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\eranb\AppData\Local\npm-cache\_logs\2024-04-03T23_59_45_646Z-
npm verb logfile C:\Users\eranb\AppData\Local\npm-cache\_logs\2024-04-03T23_59_45_646Z-debug-0.log
npm verb shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
npm http fetch GET 200 https://registry.npmjs.org/curses 784ms (cache revalidated)
npm verb reify failed optional dependency C:\Users\eranb\Desktop\AnimalDB\node_modules\fsevents
npm info run curses@0.0.10 install node_modules/curses node ./pre-build.js
npm info run curses@0.0.10 install { code: 1, signal: null }
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 179ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\eranb\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:518:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb pkgid curses@0.0.10
npm verb cwd C:\Users\eranb\Desktop\AnimalDB
npm verb Windows_NT 10.0.22631
npm verb node v20.12.1
npm verb npm  v10.5.1
npm ERR! code 1
npm ERR! path C:\Users\eranb\Desktop\AnimalDB\node_modules\curses
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./pre-build.js
npm ERR! C:\Users\eranb\Desktop\AnimalDB\node_modules\curses\pre-build.js:26
npm ERR! ,      tarExtract = tar.Extract(path.resolve(__dirname, 'deps'))
npm ERR!                         ^
npm ERR!
npm ERR! TypeError: tar.Extract is not a function
npm ERR!     at Object.<anonymous> (C:\Users\eranb\Desktop\AnimalDB\node_modules\curses\pre-build.js:26:20)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1364:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1203:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1019:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
npm ERR!     at node:internal/main/run_main_module:28:49
npm ERR!
npm ERR! Node.js v18.20.0
npm verb exit 1
npm verb unfinished npm timer reify 1712188786049
npm verb unfinished npm timer reify:build 1712188786960
npm verb unfinished npm timer build 1712188786961
npm verb unfinished npm timer build:deps 1712188786961
npm verb unfinished npm timer build:run:install 1712188786962
npm verb unfinished npm timer build:run:install:node_modules/curses 1712188786962
npm verb code 1

npm ERR! A complete log of this run can be found in: C:\Users\eranb\AppData\Local\npm-cache\_logs\2024-04-03T23_59_45_646Z-debug-0.log
```

**Comment by cclauss** [comment]
https://github.com/search?q=repo%3Anodejs%2Fnode-gyp+tar.extract&type=issues

**Comment by EranStockdale** [comment]
@cclauss  Oh, I'm very sorry! I kinda goofed there then lol. I'll give some other things a go, thank you!
