### ISSUE TITLE
Impossible to install on windows 11

### ISSUE THREAD

**Issue by JijaProGamer** [nodejs/node-gyp#3030]
* **Node Version**: v22.1.0 node, 10.7.0 npm
* **Platform**: OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
System Type:               x64-based PC

* **Compiler**: "msbuild /version & cl" fails to run in both cmd and powershell, but I do have Microsoft visual studio build tools 2022
* **Module**: ffi-napi

```
>npm i ffi-napi
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\bloxx\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.7.0
2 info using node@v22.1.0
3 silly config:load:file:C:\Users\bloxx\AppData\Roaming\npm\node_modules\npm\npmrc
4 silly config:load:file:C:\Users\bloxx\Desktop\BrawlStarsAI\.npmrc
5 silly config:load:file:C:\Users\bloxx\.npmrc
6 silly config:load:file:C:\Users\bloxx\AppData\Roaming\npm\etc\npmrc
7 verbose title npm i ffi-napi
8 verbose argv "i" "ffi-napi"
9 verbose logfile logs-max:10 dir:C:\Users\bloxx\AppData\Local\npm-cache\_logs\2024-05-04T05_05_55_521Z-
10 verbose logfile C:\Users\bloxx\AppData\Local\npm-cache\_logs\2024-05-04T05_05_55_521Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly fetch manifest ffi-napi@*
15 http fetch GET 200 https://registry.npmjs.org/ffi-napi 767ms (cache revalidated)
16 silly placeDep ROOT ffi-napi@4.0.3 OK for: brawlstarsai@1.0.0 want: *
17 silly fetch manifest debug@^4.1.1
18 silly fetch manifest get-uv-event-loop-napi-h@^1.0.5
19 silly fetch manifest node-addon-api@^3.0.0
20 silly fetch manifest node-gyp-build@^4.2.1
21 silly fetch manifest ref-napi@^2.0.1 || ^3.0.2
22 silly fetch manifest ref-struct-di@^1.1.0
23 http fetch GET 200 https://registry.npmjs.org/node-gyp-build 631ms (cache revalidated)
24 http fetch GET 200 https://registry.npmjs.org/node-addon-api 698ms (cache revalidated)
25 http fetch GET 200 https://registry.npmjs.org/debug 707ms (cache revalidated)
26 http fetch GET 200 https://registry.npmjs.org/ref-napi 730ms (cache revalidated)
27 http fetch GET 200 https://registry.npmjs.org/ref-struct-di 732ms (cache revalidated)
28 http fetch GET 200 https://registry.npmjs.org/get-uv-event-loop-napi-h 878ms (cache revalidated)
29 silly placeDep ROOT debug@4.3.4 OK for: ffi-napi@4.0.3 want: ^4.1.1
30 silly placeDep ROOT get-uv-event-loop-napi-h@1.0.6 OK for: ffi-napi@4.0.3 want: ^1.0.5
31 silly placeDep ROOT node-addon-api@3.2.1 OK for: ffi-napi@4.0.3 want: ^3.0.0
32 silly placeDep ROOT node-gyp-build@4.8.1 OK for: ffi-napi@4.0.3 want: ^4.2.1
33 silly placeDep ROOT ref-napi@3.0.3 OK for: ffi-napi@4.0.3 want: ^2.0.1 || ^3.0.2
34 silly placeDep ROOT ref-struct-di@1.1.1 OK for: ffi-napi@4.0.3 want: ^1.1.0
35 silly fetch manifest ms@2.1.2
36 silly fetch manifest get-symbol-from-current-process-h@^1.0.1
37 silly fetch manifest get-symbol-from-current-process-h@^1.0.2
38 silly fetch manifest debug@^3.1.0
39 http fetch GET 200 https://registry.npmjs.org/ms 38ms (cache revalidated)
40 http fetch GET 200 https://registry.npmjs.org/get-symbol-from-current-process-h 652ms (cache revalidated)
41 http fetch GET 200 https://registry.npmjs.org/get-symbol-from-current-process-h 695ms (cache revalidated)
42 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
43 silly placeDep ROOT get-symbol-from-current-process-h@1.0.2 OK for: get-uv-event-loop-napi-h@1.0.6 want: ^1.0.1
44 silly placeDep node_modules/ref-struct-di debug@3.2.7 OK for: ref-struct-di@1.1.1 want: ^3.1.0
45 silly reify moves {}
46 silly audit bulk request {
46 silly audit   'ffi-napi': [ '4.0.3' ],
46 silly audit   debug: [ '4.3.4', '3.2.7' ],
46 silly audit   'get-uv-event-loop-napi-h': [ '1.0.6' ],
46 silly audit   'node-addon-api': [ '3.2.1' ],
46 silly audit   'node-gyp-build': [ '4.8.1' ],
46 silly audit   'ref-napi': [ '3.0.3' ],
46 silly audit   'ref-struct-di': [ '1.1.1' ],
46 silly audit   ms: [ '2.1.2' ],
46 silly audit   'get-symbol-from-current-process-h': [ '1.0.2' ]
46 silly audit }
47 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 215ms
48 silly audit report {}
49 info run ffi-napi@4.0.3 install node_modules/ffi-napi node-gyp-build
50 info run ref-napi@3.0.3 install node_modules/ref-napi node-gyp-build
51 info run ref-napi@3.0.3 install { code: 0, signal: null }
52 info run ffi-napi@4.0.3 install { code: 1, signal: null }
53 verbose stack Error: command failed
53 verbose stack     at ChildProcess.<anonymous> (C:\Users\bloxx\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
53 verbose stack     at ChildProcess.emit (node:events:520:28)
53 verbose stack     at maybeClose (node:internal/child_process:1105:16)
53 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
54 verbose pkgid ffi-napi@4.0.3
55 verbose cwd C:\Users\bloxx\Desktop\BrawlStarsAI
56 verbose Windows_NT 10.0.22631
57 verbose node v22.1.0
58 verbose npm  v10.7.0
59 error code 1
60 error path C:\Users\bloxx\Desktop\BrawlStarsAI\node_modules\ffi-napi
61 error command failed
62 error command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
63 error nothing.c
63 error   win_delay_load_hook.cc
63 error   nothing.vcxproj -> C:\Users\bloxx\Desktop\BrawlStarsAI\node_modules\ffi-napi\build\Release\\nothing.lib
63 error   Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
63 error   '"call"' is not recognized as an internal or external command,
63 error   operable program or batch file.
63 error C:\Users\bloxx\Desktop\BrawlStarsAI\node_modules\ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: The command "call "call" "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"" exited with code 1. [C:\Users\bloxx\Desktop\BrawlStarsAI\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
64 error gyp info it worked if it ends with ok
64 error gyp info using node-gyp@10.1.0
64 error gyp info using node@22.1.0 | win32 | x64
64 error gyp info find Python using Python version 3.12.3 found at "C:\Python312\python.exe"
64 error gyp info find VS using VS2022 (17.9.34728.123) found at:
64 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
64 error gyp info find VS run with --verbose for detailed information
64 error gyp info spawn C:\Python312\python.exe
64 error gyp info spawn args [
64 error gyp info spawn args 'C:\\Users\\bloxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
64 error gyp info spawn args 'binding.gyp',
64 error gyp info spawn args '-f',
64 error gyp info spawn args 'msvs',
64 error gyp info spawn args '-I',
64 error gyp info spawn args 'C:\\Users\\bloxx\\Desktop\\BrawlStarsAI\\node_modules\\ffi-napi\\build\\config.gypi',
64 error gyp info spawn args '-I',
64 error gyp info spawn args 'C:\\Users\\bloxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
64 error gyp info spawn args '-I',
64 error gyp info spawn args 'C:\\Users\\bloxx\\AppData\\Local\\node-gyp\\Cache\\22.1.0\\include\\node\\common.gypi',
64 error gyp info spawn args '-Dlibrary=shared_library',
64 error gyp info spawn args '-Dvisibility=default',
64 error gyp info spawn args '-Dnode_root_dir=C:\\Users\\bloxx\\AppData\\Local\\node-gyp\\Cache\\22.1.0',
64 error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\bloxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
64 error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\bloxx\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.1.0\\\\<(target_arch)\\\\node.lib',
64 error gyp info spawn args '-Dmodule_root_dir=C:\\Users\\bloxx\\Desktop\\BrawlStarsAI\\node_modules\\ffi-napi',
64 error gyp info spawn args '-Dnode_engine=v8',
64 error gyp info spawn args '--depth=.',
64 error gyp info spawn args '--no-parallel',
64 error gyp info spawn args '--generator-output',
64 error gyp info spawn args 'C:\\Users\\bloxx\\Desktop\\BrawlStarsAI\\node_modules\\ffi-napi\\build',
64 error gyp info spawn args '-Goutput_dir=.'
64 error gyp info spawn args ]
64 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
64 error gyp info spawn args [
64 error gyp info spawn args 'build\\binding.sln',
64 error gyp info spawn args '/clp:Verbosity=minimal',
64 error gyp info spawn args '/nologo',
64 error gyp info spawn args '/p:Configuration=Release;Platform=x64'
64 error gyp info spawn args ]
64 error gyp ERR! build error 
64 error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
64 error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\bloxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
64 error gyp ERR! stack at ChildProcess.emit (node:events:520:28)
64 error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
64 error gyp ERR! System Windows_NT 10.0.22631
64 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bloxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
64 error gyp ERR! cwd C:\Users\bloxx\Desktop\BrawlStarsAI\node_modules\ffi-napi
64 error gyp ERR! node -v v22.1.0
64 error gyp ERR! node-gyp -v v10.1.0
64 error gyp ERR! not ok
65 verbose exit 1
66 verbose code 1
67 silly unfinished npm timer reify 1714799155759
68 silly unfinished npm timer reify:build 1714799158493
69 silly unfinished npm timer build 1714799158493
70 silly unfinished npm timer build:deps 1714799158493
71 silly unfinished npm timer build:run:install 1714799158498
72 silly unfinished npm timer build:run:install:node_modules/ffi-napi 1714799158498
73 error A complete log of this run can be found in: C:\Users\bloxx\AppData\Local\npm-cache\_logs\2024-05-04T05_05_55_521Z-debug-0.log
```

I also did tick the extra tools checkbox in node when installing, and followed the windows installation

**Comment by cclauss** [comment]
* node-ffi-napi/node-ffi-napi#269

**Comment by maheshsivast** [comment]
@JijaProGamer Were you able to solve this issue?

**Comment by maheshsivast** [comment]
On Windows 10, the below command works
> cmd /C "npm install"

**Comment by hackinghacker1** [comment]
> Duplicate of
> 
> * [PLEASE ARCHIVE THIS REPO -- The code fails on modern Node.js node-ffi-napi/node-ffi-napi#269](https://github.com/node-ffi-napi/node-ffi-napi/issues/269)

maybe answer the question instead of being a nerdy fuck about it " 🤓 ermm actually its a duplicate"
