### ISSUE TITLE
Walrus operator only supported in Python 3.8

### ISSUE THREAD

**Issue by leithouse** [nodejs/node-gyp#3053]
In the most recent release, [gyp/common.py](https://github.com/nodejs/node-gyp/blob/e6f4ede10cca28e9edeaa85d7830914c5d1499c7/gyp/pylib/gyp/common.py#L434) includes the Walrus operator. This operator was introduced in python [3.8](https://docs.python.org/3/whatsnew/3.8.html). Build environments that are still required to run on Debian Buster are stuck with python 3.7.3-1.

* **Node Version**: 20.16.0
* **NodeGyp Version**: 10.2
* **Platform**: Debian Buster/10
* **Compiler**: gcc 8.3.0
* **Module**: unimportant

<details><summary>Relevant output</summary>

```sh
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@20.16.0 | linux | x64
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
...
Traceback (most recent call last):
  File "/usr/local/share/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
  File "/usr/local/share/.config/yarn/global/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/usr/local/share/.config/yarn/global/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module>
    import gyp.common
  File "/usr/local/share/.config/yarn/global/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435
    if CC := os.environ.get("CC_target") or os.environ.get("CC"):
           ^
SyntaxError: invalid syntax
```
</details>

**Comment by cclauss** [comment]
https://devguide.python.org/versions
