### ISSUE TITLE
yarn install 依赖node-pre-gyp ERR!

### ISSUE THREAD

**Issue by yuanjunnbao** [nodejs/node-gyp#3067]
error /Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments: 
Directory: /Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@16.20.2 | darwin | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v93-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.3 and node@16.20.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v93-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.20.2 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.20.2 | darwin | arm64
gyp info find Python using Python version 3.12.5 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/junbaoyuan/Library/Caches/node-gyp/16.20.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/junbaoyuan/Library/Caches/node-gyp/16.20.2',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/junbaoyuan/Library/Caches/node-gyp/16.20.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 23.6.0
gyp ERR! command "/opt/homebrew/Cellar/node@16/16.20.2_1/bin/node" "/opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas
gyp ERR! node -v v16.20.2
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node@16/16.20.2_1/bin/node /opt/homebrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 23.6.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node@16/16.20.2_1/bin/node" "/Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /Users/junbaoyuan/Desktop/zhcx/vue-agent-crowdfund/node_modules/canvas
node-pre-gyp ERR! node -v v16.20.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok

**Comment by cclauss** [comment]
> gyp info using node-gyp@9.1.0
> ...
> gyp info find Python using Python version 3.12.5 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"

Python >= 3.12 requires node-gyp >= v10.
https://github.com/nodejs/node-gyp?tab=readme-ov-file#installation

**Comment by yuanjunnbao** [comment]
node-gyp --version
v10.2.0

**Comment by cclauss** [comment]
That is not what the log above says.  Please edit `package.json` to use the [current version](https://github.com/nodejs/node-gyp/releases) of `node-gyp`.
