### ISSUE TITLE
procLog.pause is not a function

### ISSUE THREAD

**Issue by Leone25** [nodejs/node-gyp#3078]
* **Node Version**: v22.8.0 (also tried v18.20.4) - npm v10.8.3
* **Platform**: Linux 6.6.52-1-MANJARO x86_64 GNU/Linux
* **Compiler**: gcc version 14.2.1 20240910
* **Module**: speaker (but it gives the same error with any module that i try to install)

<details><summary>Verbose output (from npm or node-gyp):</summary>

```
>npm i --verbose speaker
npm verbose cli /usr/bin/node /usr/bin/npm
npm info using npm@10.8.3
npm info using node@v22.8.0
npm verbose title npm i speaker
npm verbose argv "i" "--loglevel" "verbose" "speaker"
npm verbose logfile logs-max:10 dir:/home/enrico/.npm/_logs/2024-10-08T06_25_07_136Z-
npm verbose logfile /home/enrico/.npm/_logs/2024-10-08T06_25_07_136Z-debug-0.log
npm verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
npm http fetch GET 200 https://registry.npmjs.org/speaker 1031ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer-alloc 157ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer-alloc-unsafe 146ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer-fill 406ms (cache revalidated)
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/fsevents
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-win32-x64-msvc
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-win32-ia32-msvc
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-win32-arm64-msvc
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-s390x-gnu
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-riscv64-gnu
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-powerpc64le-gnu
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-arm64-musl
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-arm64-gnu
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-arm-musleabihf
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-linux-arm-gnueabihf
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-darwin-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-darwin-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-android-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@rollup/rollup-android-arm-eabi
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/win32-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/win32-ia32
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/win32-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/sunos-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/openbsd-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/netbsd-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-s390x
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-riscv64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-ppc64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-mips64el
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-loong64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-ia32
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/linux-arm
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/freebsd-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/freebsd-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/darwin-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/darwin-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/android-x64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/android-arm64
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/android-arm
npm verbose reify failed optional dependency /home/enrico/Documents/GitHub/patata-new/node_modules/@esbuild/aix-ppc64
npm info run speaker@0.5.5 install node_modules/speaker node-gyp rebuild
npm info run speaker@0.5.5 install { code: 1, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid speaker@0.5.5
npm error code 1
npm error path /home/enrico/Documents/GitHub/patata-new/node_modules/speaker
npm error command failed
npm error command sh -c node-gyp rebuild
npm error /usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:81
npm error     procLog.pause()
npm error             ^
npm error
npm error TypeError: procLog.pause is not a function
npm error     at new Logger (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:81:13)
npm error     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:165:11)
npm error     at Module._compile (node:internal/modules/cjs/loader:1546:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1317:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1127:12)
npm error     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
npm error     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
npm error     at Module.require (node:internal/modules/cjs/loader:1339:12)
npm error     at require (node:internal/modules/helpers:135:16)
npm error
npm error Node.js v22.8.0
npm verbose cwd /home/enrico/Documents/GitHub/patata-new
npm verbose os Linux 6.6.52-1-MANJARO
npm verbose node v22.8.0
npm verbose npm  v10.8.3
npm verbose exit 1
npm verbose code 1
```

</details>

```
/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:81
error     procLog.pause()
error             ^
error
error TypeError: procLog.pause is not a function
```

It just does that any time I try to install any module that makes use of `node-gyp`, I'm tried reinstalling, changing the node version and doing spiritual rituals, and nothing worked, and have no idea what else to try.

Any help?

Thanks

Rico

**Comment by tniessen** [comment]
I am also seeing this on `Linux 6.1.119-1-MANJARO` using Node.js 23.1.0 and npm 10.9.0. This makes me wonder if it is related to the distribution of Node.js/npm/node-gyp through the Arch Linux official repositories.

**Comment by lukekarrys** [comment]
@tniessen Can you see what version of `proc-log` is available to both `npm` and `node-gyp`? 

There was a breaking change to `proc-log` (https://github.com/npm/proc-log/releases/tag/v4.0.0) where the exports were nested which would result in this error. But only if `node-gyp` was getting the wrong version somehow.

**Comment by tniessen** [comment]
@lukekarrys With the most recent Arch Linux distribution, there is

- `proc-log@4.2.0` at `/usr/lib/node_modules/node-gyp/node_modules/proc-log` and
- `proc-log@5.0.0` at `/usr/lib/node_modules/npm/node_modules/proc-log`.

It seems that `/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js` is loading `proc-log@5.0.0`.

The stack trace is as follows:

```
/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:81
    procLog.pause()
            ^

TypeError: procLog.pause is not a function
    at new Logger (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:81:13)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/log.js:165:11)
    at Module._compile (node:internal/modules/cjs/loader:1572:14)
    at Object..js (node:internal/modules/cjs/loader:1709:10)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
    at Module.require (node:internal/modules/cjs/loader:1337:12)
    at require (node:internal/modules/helpers:139:16)

Node.js v23.1.0
```

**Comment by lukekarrys** [comment]
This reminds me of a different issue which sounds like it could be a similar root cause: https://github.com/npm/cli/issues/6785

There was some discussion about it on the Arch Linux issue tracker as well: https://bugs.archlinux.org/task/79693

**Comment by Leone25** [comment]
I can confirm that the issues is because there seems to be some sort of conflict when installing node and npm from pacman

my solution was uninstalling everything and then installing from pacman nvm and then node and npm with nvm

**Comment by lukekarrys** [comment]
I'm going to close this issue since it seems like an issue with upstream packaging instead.
