### ISSUE TITLE
python is not configured in npm

### ISSUE THREAD

**Issue by unaccepted** [nodejs/node-gyp#3089]
The original issue is posted below which is related to setup of a node repo. While doing the setup I am facing issue with node-gyp and python. 
https://github.com/citrineos/citrineos/issues/45

@cclauss Can you please help here. I followed the thread https://github.com/nodejs/node-gyp/issues/2664
But no luck. let me know if you need any other info to guide me better.

Below is the configuration of my system:

<img width="1319" alt="image" src="https://github.com/user-attachments/assets/26efcf8c-4bb1-449a-97f3-0c76182f2246">

<img width="357" alt="image" src="https://github.com/user-attachments/assets/72d5e0e7-dff8-43cd-84f4-7008235475d3">

<img width="944" alt="image" src="https://github.com/user-attachments/assets/339986ea-2a62-4aab-90d6-c1e6c608f617">

<img width="1696" alt="image" src="https://github.com/user-attachments/assets/4b4cad07-c8dd-42f9-b96f-40c0129bc117">

I am getting this error while hitting the command on readme : "docker-compose -f ./docker-compose.yml up -d"

**Comment by unaccepted** [comment]
@cclauss Can you please help here. I followed the thread https://github.com/nodejs/node-gyp/issues/2664
But no luck. let me know if you need any other info to guide me better.

<img width="357" alt="image" src="https://github.com/user-attachments/assets/72d5e0e7-dff8-43cd-84f4-7008235475d3">

<img width="944" alt="image" src="https://github.com/user-attachments/assets/339986ea-2a62-4aab-90d6-c1e6c608f617">

**Comment by cclauss** [comment]
https://docs.python.org/3/library/venv.html#how-venvs-work

Run these two commands to define `python`:
```
py -m venv .venv
C:\> .venv\Scripts\activate.bat
```

**Comment by unaccepted** [comment]
Thanks @cclauss for the response, please find the reponse of the last command (docker-compose -f ./docker-compose.yml up -d) in text:

`99.49 npm verbose reify failed optional dependency /usr/local/apps/citrineos/node_modules/bufferutil
99.60 npm info run utf-8-validate@6.0.3 install { code: 1, signal: null }
99.60 npm verbose reify failed optional dependency /usr/local/apps/citrineos/node_modules/utf-8-validate
100.9 npm verbose stack Error: command failed
100.9 npm verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
100.9 npm verbose stack     at ChildProcess.emit (node:events:517:28)
100.9 npm verbose stack     at maybeClose (node:internal/child_process:1098:16)
100.9 npm verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
100.9 npm verbose pkgid deasync@0.1.30
100.9 npm verbose cwd /usr/local/apps/citrineos
100.9 npm verbose Linux 5.15.49-linuxkit-pr
100.9 npm verbose node v18.20.4
100.9 npm verbose npm  v10.7.0
100.9 npm error code 1
100.9 npm error path /usr/local/apps/citrineos/node_modules/deasync
100.9 npm error command failed
100.9 npm error command sh -c node ./build.js
100.9 npm error gyp info it worked if it ends with ok
100.9 npm error gyp verb cli [
100.9 npm error gyp verb cli '/usr/local/bin/node',
100.9 npm error gyp verb cli '/usr/local/apps/citrineos/node_modules/.bin/node-gyp',
100.9 npm error gyp verb cli 'rebuild'
100.9 npm error gyp verb cli ]
100.9 npm error gyp info using node-gyp@10.2.0
100.9 npm error gyp info using node@18.20.4 | linux | arm64
100.9 npm error gyp verb clean removing "build" directory
100.9 npm error gyp verb find Python Python is not set from command line or npm configuration
100.9 npm error gyp verb find Python Python is not set from environment variable PYTHON
100.9 npm error gyp verb find Python checking if "python3" can be used
100.9 npm error gyp verb find Python - executing "python3" to get executable path
100.9 npm error gyp verb find Python - executable path is "/usr/bin/python3"
100.9 npm error gyp verb find Python - executing "/usr/bin/python3" to get version
100.9 npm error gyp verb find Python - version is "3.11.2"
100.9 npm error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
100.9 npm error gyp verb get node dir no --target version specified, falling back to host node version: 18.20.4
100.9 npm error gyp verb install input version string "18.20.4"
100.9 npm error gyp verb install installing version: 18.20.4
100.9 npm error gyp verb install --ensure was passed, so won't reinstall if already installed
100.9 npm error gyp verb install version not already installed, continuing with install 18.20.4
100.9 npm error gyp verb ensuring devDir is created /root/.cache/node-gyp/18.20.4
100.9 npm error gyp verb created devDir /root/.cache
100.9 npm error gyp http GET https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz
100.9 npm error gyp http fetch GET https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz attempt 1 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
100.9 npm error gyp WARN install got an error, rolling back install
100.9 npm error gyp verb remove using node-gyp dir: /root/.cache/node-gyp
100.9 npm error gyp verb remove removing target version: 18.20.4
100.9 npm error gyp verb remove removing development files for version: 18.20.4
100.9 npm error gyp ERR! configure error 
100.9 npm error gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz failed, reason: unable to get local issuer certificate
100.9 npm error gyp ERR! stack at ClientRequest.<anonymous> (/usr/local/apps/citrineos/node_modules/minipass-fetch/lib/index.js:130:14)
100.9 npm error gyp ERR! stack at ClientRequest.emit (node:events:517:28)
100.9 npm error gyp ERR! stack at _destroy (node:_http_client:882:13)
100.9 npm error gyp ERR! stack at onSocketNT (node:_http_client:902:5)
100.9 npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
100.9 npm error gyp ERR! System Linux 5.15.49-linuxkit-pr
100.9 npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/apps/citrineos/node_modules/.bin/node-gyp" "rebuild"
100.9 npm error gyp ERR! cwd /usr/local/apps/citrineos/node_modules/deasync
100.9 npm error gyp ERR! node -v v18.20.4
100.9 npm error gyp ERR! node-gyp -v v10.2.0
100.9 npm error gyp ERR! not ok 
100.9 npm error Build failed
100.9 npm verbose exit 1
100.9 npm verbose code 1
100.9 
100.9 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-06T13_20_43_352Z-debug-0.log
101.0 npm notice
101.0 npm notice New minor version of npm available! 10.7.0 -> 10.9.0
101.0 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
101.0 npm notice To update run: npm install -g npm@10.9.0
101.0 npm notice
------
failed to solve: process "/bin/sh -c npm run install-all && npm run build" did not complete successfully: exit code: 1`


I have also created binding.gyp file with below content:

`{
  "targets": [
    {
      "target_name": "binding",
      "sources": [ " /usr/local/bin/node" ]
    }
  ]
}`

**Comment by cclauss** [comment]
```
100.9 npm error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
```
Means that Python is NOT your problem.

Your problem is:
```
100.9 npm error gyp http fetch GET https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz attempt 1 failed with UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```

**Comment by unaccepted** [comment]
Thanks @cclauss  for pointing out. I am using corporate laptop and it has zscalar so I might be running these behind a proxy. Is there a way to setup a my personal cert that node can use. Can you provide some reference.

**Comment by nazarioa** [comment]
I am running into a similar issue. Bellow is the error output. I suspect that this has to do with the operating system version not being compatible with node-gyp. Running 15.1.1

Error
```
npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated q@1.4.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
npm warn deprecated
npm warn deprecated (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
npm warn deprecated @types/googlemaps@3.43.3: Types for the Google Maps browser API have moved to @types/google.maps. Note: these types are not for the googlemaps npm package, which is a Node API.
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code 1
npm error path /Users/na/Developer/acme/web-app/node_modules/weak-napi
npm error command failed
npm error command sh -c node-gyp-build
npm error CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm error   LIBTOOL-STATIC Release/nothing.a
npm error   CXX(target) Release/obj.target/weakref/src/weakref.o
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.3.1
npm error gyp info using node@22.13.0 | darwin | arm64
npm error gyp info find Python using Python version 3.9.6 found at "/Users/na/.pyenv/versions/3.9.6/bin/python3"
npm error gyp info spawn /Users/na/.pyenv/versions/3.9.6/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/Users/na/Developer/acme/web-app/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/na/Developer/acme/web-app/node_modules/weak-napi/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/na/Developer/acme/web-app/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/na/Library/Caches/node-gyp/22.13.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/na/Library/Caches/node-gyp/22.13.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/Users/na/Developer/acme/web-app/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/na/Library/Caches/node-gyp/22.13.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/na/Developer/acme/web-app/node_modules/weak-napi',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm error In file included from ../src/weakref.cc:1:
npm error In file included from /Users/na/Developer/acme/web-app/node_modules/node-addon-api/napi.h:5:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:515:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/search.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/iterator_operations.h:12:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/iter_swap.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/swap.h:16:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_nothrow_move_constructible.h:15:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_nothrow_constructible.h:17:
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
npm error    46 | #   error <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header. \
npm error       |     ^
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
npm error    59 | using ::nullptr_t;
npm error       |       ~~^
npm error In file included from ../src/weakref.cc:1:
npm error In file included from /Users/na/Developer/acme/web-app/node_modules/node-addon-api/napi.h:5:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:515:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/search.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/iterator_operations.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/ranges_iterator_concept.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/concepts.h:16:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__concepts/constructible.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__concepts/destructible.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_nothrow_destructible.h:16:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_scalar.h:17:
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
npm error    26 | struct __is_nullptr_t_impl<nullptr_t> : public true_type {};
npm error       |                            ^
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: template argument for template type parameter must be a type
npm error    26 | struct __is_nullptr_t_impl<nullptr_t> : public true_type {};
npm error       |                            ^~~~~~~~~
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_null_pointer.h:23:17: note: template parameter is declared here
npm error    23 | template <class _Tp>
npm error       |                 ^
npm error In file included from ../src/weakref.cc:1:
npm error In file included from /Users/na/Developer/acme/web-app/node_modules/node-addon-api/napi.h:5:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:515:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/search.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/iterator_operations.h:15:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/advance.h:26:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/limits:819:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:508:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_trivially_copyable.h:14:
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cstdint:149:5: error: <cstdint> tried including <stdint.h> but didn't find libc++'s <stdint.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
npm error   149 | #   error <cstdint> tried including <stdint.h> but didn't find libc++'s <stdint.h> header. \
npm error       |     ^
npm error In file included from ../src/weakref.cc:1:
npm error In file included from /Users/na/Developer/acme/web-app/node_modules/node-addon-api/napi.h:5:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:521:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/bind.h:20:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:272:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/compare:145:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/compare_partial_order_fallback.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/partial_order.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/weak_order.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/strong_order.h:20:
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:322:5: error: <cmath> tried including <math.h> but didn't find libc++'s <math.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
npm error   322 | #   error <cmath> tried including <math.h> but didn't find libc++'s <math.h> header. \
npm error       |     ^
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:583:15: error: expected unqualified-id
npm error   583 |   return std::isnan(__lcpp_x);
npm error       |               ^
npm error /usr/local/include/math.h:166:5: note: expanded from macro 'isnan'
npm error   166 |     ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
npm error       |     ^
npm error In file included from ../src/weakref.cc:1:
npm error In file included from /Users/na/Developer/acme/web-app/node_modules/node-addon-api/napi.h:5:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:521:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/bind.h:20:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:272:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/compare:145:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/compare_partial_order_fallback.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/partial_order.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/weak_order.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/strong_order.h:20:
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:582:46: error: no return statement in constexpr function
npm error   582 | _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR bool __constexpr_isnan(_A1 __lcpp_x) _NOEXCEPT {
npm error       |                                              ^
npm error /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:597:15: error: expected unqualified-id
npm error   597 |   return std::isinf(__lcpp_x);
npm error       |               ^
npm error /usr/local/include/math.h:161:5: note: expanded from macro 'isinf'
npm error   161 |     ( sizeof(x) == sizeof(float)  ? __inline_isinff((float)(x))          \
npm error       |     ^
npm error In file included from ../src/weakref.cc:1:
npm error In file included from /Users/na/Developer/acme/web-app/node_modules/node-addon-api/napi.h:5:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:521:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/bind.h:20:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tuple:272:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/compare:145:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/compare_partial_order_fallback.h:13:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/partial_order.h:14:
npm error In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__compare/weak_order.h:14:

.... 
```

sepc
```
 na@naMBP14 ~/Developer/acme/web-app > node --version
v22.13.0
 na@naMBP14 ~/Developer/acme/web-app > npm --version
10.9.2
 na@naMBP14 ~/Developer/acme/web-app > python --version
Python 3.9.6
 na@naMBP14 ~/Developer/acme/web-app > which python
/Users/na/.pyenv/shims/python
 na@naMBP14 ~/Developer/acme/web-app > nvm --version
0.40.1
 na@naMBP14 ~/Developer/acme/web-app > pyenv --version
pyenv 2.5.0
 na@naMBP14 ~/Developer/acme/web-app > sw_vers
ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91
```

**Comment by cclauss** [comment]
For all of the examples above, Python is not the problem.  A supported version of Python was found and is being used.

Please tell us which module you are trying to install.  `npm i` tells us ___nothing___.
