### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by thany** [nodejs/node-gyp#417]
Trying to install jsdom for hours now, still getting this error no matter what I try. I tried all the common suggestions like puttin python 2.7 on the path, setting the env variabe, installing vc2010, vc2012, win7 sdk, extra compiler, a whole crapload of stuff. I'm now left with just having installed VS2012 express and Python 2.7.

This is the error log:

```
npm WARN package.json to-markdown@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/nwmatcher
npm http GET https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/xmlhttprequest
npm http 304 https://registry.npmjs.org/nwmatcher
npm http 304 https://registry.npmjs.org/htmlparser2
npm http 503 https://registry.npmjs.org/cssstyle
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/cssom
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/oauth-sign

> contextify@0.1.7 install c:\Data\Werk\Keytec\_converter\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild


c:\Data\Werk\Keytec\_converter\node_modules\jsdom\node_modules\contextify>node "C:\Program Files\nodejs\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:988:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd c:\Data\Werk\Keytec\_converter\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/domhandler
npm http 304 https://registry.npmjs.org/domelementtype
npm ERR! contextify@0.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.7 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "jsdom"
npm ERR! cwd c:\Data\Werk\Keytec\_converter
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Data\Werk\Keytec\_converter\npm-debug.log
npm ERR! not ok code 0
```

For extra verbosity:
Windows 7 x64
Node 0.10.26 x64
Python 2.7.6 x64
npm 1.4.3
node-gyp 0.13.0

**Comment by a0viedo** [comment]
As this is resolved this can be closed. cc @Trott
