### ISSUE TITLE
Windows: "CL.exe exited with code -1073741515"

### ISSUE THREAD

**Issue by tomyam1** [nodejs/node-gyp#422]
Sorry to open yet another issue on installing on Windows, but I didn't find any issue like this.

I uninstalled and re-installed Node, Python 2.7 (both use the 64 version), Visual studio (first 2010 express and than tried with 2013 express). I'm running Windows 7 x64.

I keep getting the same error message:

```
F:\Tom\Code\tepez\server>npm install --save bcrypt
npm WARN package.json meanio@0.2.8 No repository field.
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.7 install F:\Tom\Code\tepez\server\node_modules\bcrypt
> node-gyp rebuild


F:\Tom\Code\tepez\server\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetF rameworkVersion or PlatformToolset may be set to an invalid version number. [F:\Tom\Code\tepez\server\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.targets(152,5): error MSB6006: "CL.exe" exited with code -1073741515. [F:\Tom\Code\te pez\server\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Tom\Code\tepez\server\node_modules\bcrypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "bcrypt"
npm ERR! cwd F:\Tom\Code\tepez\server
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     F:\Tom\Code\tepez\server\npm-debug.log
npm ERR! not ok code 0
```

verbose output: https://gist.github.com/tepez/9936448

This is the error I get when VS2010 is installed.
After moving to VS2013, the line 

```
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
```

Changes to

```
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
```

**Comment by CTimmerman** [comment]
Change Visual Studio install to include "Tools and Windows SDK" and use "node install --msvs_version=2015".

**Comment by barocsi** [comment]
using Visual Studio Build Tools 2015 Win7 it throws this error

**Comment by Coderx7** [comment]
I repaired visual studio and the error is gone!
