### ISSUE TITLE
Build on freebsd 10

### ISSUE THREAD

**Issue by josser** [nodejs/node-gyp#423]
Hi, trying to install several modules (mhash, hiredis)  but got strange error: 

```

npm install mhash  
npm http GET https://registry.npmjs.org/mhash
npm http 304 https://registry.npmjs.org/mhash
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> mhash@1.0.0 install /usr/home/josser/test/node_modules/mhash
> node-gyp rebuild

gmake: Entering directory `/usr/home/josser/test/node_modules/mhash/build'
  ACTION binding_gyp_libmhash_target_test .
make[1]: don't know how to make wr. Stop

make[1]: stopped in /usr/home/josser/test/node_modules/mhash/deps/mhash
  TOUCH Release/obj.target/libmhash.stamp
  CXX(target) Release/obj.target/mhash/mhash.o
gmake: g++: Command not found
gmake: *** [Release/obj.target/mhash/mhash.o] Error 127
gmake: Leaving directory `/usr/home/josser/test/node_modules/mhash/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System FreeBSD 10.0-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/josser/test/node_modules/mhash
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

FreeBSD 10 switched to clang from gcc so I think this is a reason.

**Comment by a0viedo** [comment]
hey @josser did you managed to fix this?

**Comment by a0viedo** [comment]
ok then I guess we can close this for now @Trott
