### ISSUE TITLE
gyp_main.py: error: no such option: --no-parallel

### ISSUE THREAD

**Issue by Rudloff** [nodejs/node-gyp#426]
Hello,

When I try to install pg or bcrypt, I get the following error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.0
gyp info using node@0.10.21 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pierre/www/je-suis-ici-cartoviz/scripts/node_modules/pg/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pierre/.node-gyp/0.10.21/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pierre/.node-gyp/0.10.21',
gyp info spawn args   '-Dmodule_root_dir=/home/pierre/www/je-suis-ici-cartoviz/scripts/node_modules/pg',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /home/pierre/www/je-suis-ici-cartoviz/scripts/node_modules/pg
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
```

Regards,

**Comment by khazamov** [comment]
removing gyp helped me, thanks @aviynw

**Comment by iyogeshjoshi** [comment]
@JeremyWei none of them worked for me,
- [x] I tried editing the `/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js` file but couldn't find `--no-parallel` option anywhere on that file.
- [x] Then I upgraded node-gyp to `v1.0.3` which is latest available, still throwing the following error

```shell
apm install git-projects
Installing git-projects to /home/iyogeshjoshi/.atom/packages ✗

> git-utils@3.0.0 install /tmp/apm-install-dir-115227-7025-16poy8t/node_modules/git-projects/node_modules/git-utils
> node-gyp rebuild


Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-33-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115227-7025-16poy8t/node_modules/git-projects/node_modules/git-utils
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/iyogeshjoshi/.atom/.apm/.apmrc" "--userconfig" "/home/iyogeshjoshi/.atom/.apmrc" "install" "/tmp/d-115227-7025-esxv5v/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! git-utils@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115227-7025-16poy8t/npm-debug.log
```

**Comment by JeremyWei** [comment]
@iyogeshjoshi from your logs, i think the right path of your ```configure.js``` is ```/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js```

**Comment by iyogeshjoshi** [comment]
@JeremyWei yes that worked thanks :+1: . 
Which means we have to do both the steps upgrade and then hacking `configure.js` file.

**Comment by davidcstevens** [comment]
@aviynw thanks, that worked for me, too

**Comment by ljconde** [comment]
@aviynw Uninstalling the `gyp` package in Ubuntu worked for me as well. Thanks!

**Comment by pradhanshrijal** [comment]
I tried to remove the gyp module, hack the configure.js file and it is still showing the same error. I also tried to remove the ~/.node-gyp folder. Still nothing.

I am using Debian Wheezy of BeagleBone Black
node v0.9.9
npm 0.2.15
node-gyp v2.0.2

**Comment by ekg** [comment]
I ran into this problem and solved it via `sudo apt-get remove gyp`.

**Comment by catskul** [comment]
@ekg worked for me as well. Thanks!

**Comment by drewboswell** [comment]
@aviynw removing it worked for me too, thanks!

**Comment by asoltys** [comment]
Upgrading the version of gyp used by npm worked for me:  

    sudo npm explore npm -g -- npm install node-gyp@latest

https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp

**Comment by terotil** [comment]
Upgrading bundled node-gyp didn't work for me, but removing OS gyp did. Thanks, @aviynw !

I tried to dig a little deeper into this. It just seems so wrong that you need to poke internals of bundled package or remove system packages. Looks like `runGyp` in `node-gyp/lib/configure.js` is genuinely trying to run the embedded gyp and only depend on python from OS

      // execute `gyp` from the current target nodedir
      argv.unshift(gyp_script)

      // make sure python uses files that came with this particular node package
      var pypath = new PathArray(process.env, 'PYTHONPATH')
      pypath.unshift(path.join(__dirname, '..', 'gyp', 'pylib'))

But apparently that isolation effort fails. Looks like a bug to me.
