### ISSUE TITLE
node-gyp configure error

### ISSUE THREAD

**Issue by donbe** [nodejs/node-gyp#428]
system: mac os x 10.9.2

when type node-gyp configure command terminal, got error follow:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.0
gyp info using node@0.8.26 | darwin | x64
gyp http GET http://nodejs.org/dist/v0.8.26/node-v0.8.26.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.26/node-v0.8.26.tar.gz
gyp http GET http://nodejs.org/dist/v0.8.26/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.8.26/SHASUMS.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.8.26.tar.gz local sha1 1cd5dbf2f26dc4d0ad1dc31f950689b208fcd936 not match remote 2ec960bcc8cd38da271f83c1b2007c12da5153b3
gyp ERR! stack     at deref (/usr/local/lib/node_modules/node-gyp/lib/install.js:296:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-gyp/lib/install.js:336:13)
gyp ERR! stack     at IncomingMessage.EventEmitter.emit (events.js:126:20)
gyp ERR! stack     at IncomingMessage._emitEnd (http.js:367:10)
gyp ERR! stack     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1491:20)
gyp ERR! stack     at TCP.onread (net.js:404:27)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/wuyang/Documents/Node.js/nodegyp
gyp ERR! node -v v0.8.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
```

**Comment by sjfkai** [comment]
I get the same error with node.js v0.8 and v0.12 when i `npm install fibers`,but it works well with node.js v0.10.

**Comment by a0viedo** [comment]
hey @donbe, I know it's been some time but is this still an issue?

**Comment by maclover7** [comment]
Are you able to reproduce this on a more recent version of node-gyp?

**Comment by maclover7** [comment]
Closing due to inactivity, please feel free to reopen if you are able to reproduce on a more recent version of node-gyp :)
