### ISSUE TITLE
binding.gyp files disappearing

### ISSUE THREAD

**Issue by MixMasterMitch** [nodejs/node-gyp#436]
I recently deleted my `node_modules` folder to get a fresh install of all my dependencies. I ran `npm install` and all of the native modules rebuilt properly. When I try to rebuild some of the modules, I get the error `binding.gyp not found`. I confirmed that the binding.gyp files are missing. This is strange because they must have been there for `npm install` to work. I have tried deleting `node_modules` again, but not change.

Any idea on where the `binding.gyp` files are going and how I can rebuild the modules?

I should also note that I am going to be rebuilding the modules for node-webkit.

Here is a sample of installing a single module:

```
d-128-95-116-246:UWCenterStack mitchellloeppky$ npm install leapjs
npm http GET https://registry.npmjs.org/leapjs
npm http 304 https://registry.npmjs.org/leapjs
npm http GET https://registry.npmjs.org/ws/0.4.25
npm http GET https://registry.npmjs.org/gl-matrix/2.0.0
npm http 304 https://registry.npmjs.org/ws/0.4.25
npm http 304 https://registry.npmjs.org/gl-matrix/2.0.0
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor

> ws@0.4.25 install /Users/mitchellloeppky/Documents/GitHub/UWCenterStack/node_modules/leapjs/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
leapjs@0.5.0 node_modules/leapjs
├── gl-matrix@2.0.0
└── ws@0.4.25 (tinycolor@0.0.1, options@0.0.5, commander@0.6.1)
d-128-95-116-246:UWCenterStack mitchellloeppky$  cd node_modules/leapjs
d-128-95-116-246:leapjs mitchellloeppky$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.1
gyp info using node@0.10.24 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/share/npm/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mitchellloeppky/Documents/GitHub/UWCenterStack/node_modules/leapjs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/share/npm/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mitchellloeppky/.node-gyp/0.10.24/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mitchellloeppky/.node-gyp/0.10.24',
gyp info spawn args   '-Dmodule_root_dir=/Users/mitchellloeppky/Documents/GitHub/UWCenterStack/node_modules/leapjs',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/mitchellloeppky/Documents/GitHub/UWCenterStack/node_modules/leapjs)
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/share/npm/lib/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/usr/local/share/npm/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/mitchellloeppky/Documents/GitHub/UWCenterStack/node_modules/leapjs
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
```

**Comment by Trott** [comment]
@nodejs/node-gyp @MixMasterMitch Should this remain open?

**Comment by bnoordhuis** [comment]
Seeing it's about really old versions of node and node-gyp, I'd say no.  Closing.
