### ISSUE TITLE
Build on Solaris fails because sun-make doesn't support -C option

### ISSUE THREAD

**Issue by schedul-xor** [nodejs/node-gyp#453]
Since node-gyp requires a proper C/C++ compiler toolchain (like GCC), and C/C++ compiler tools installed in Solaris are not proper, building node-gyp on Solaris fails. Actually, sun-`make` doesn't support `-C` option.

```
Usage : make [ -f makefile ][ -K statefile ][ -x MODE_NAME=VALUE ]... [ -d ][ -dd ][ -D ][ -DD ]
             [ -e ][ -i ][ -k ][ -n ][ -p ][ -P ][ -q ][ -r ][ -s ][ -S ][ -t ]
             [ -u ][ -w ][ -V ][ target... ][ macro=value... ][ "macro +=value"... ]
make: Fatal error: Unknown option `-C'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

This may simply be solved by installing GNU-`make` in my environment, but it may be better if node-gyp can be compiled even if `make` doesn't support `-C` option.

**Comment by Trott** [comment]
@nodejs/node-gyp Should this remain open?

**Comment by bnoordhuis** [comment]
I'll close this.  Old node and node-gyp version and an unsupported OS.
