### ISSUE TITLE
Does not work inside a Docker container - Permissions error

### ISSUE THREAD

**Issue by d11wtq** [nodejs/node-gyp#487]
Unfortunately this seems to be a blocker, as Docker is pretty widely used in deployments now. It looks like node-gyp is trying to copy files with `-a` or something along those lines.

```
default@41acb05c081c:/projects/nodejs/flunk$ npm install
npm WARN package.json flunk@ No repository field.

> pty.js@0.2.2 install /projects/nodejs/flunk/node_modules/gitty/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/projects/nodejs/flunk/node_modules/gitty/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function 'v8::Handle<v8::Value> PtyFork(const v8::Arguments&)':
../src/unix/pty.cc:186:34: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
  SOLINK_MODULE(target) Release/obj.target/pty.node: Finished
  COPY Release/pty.node
cp: preserving permissions for 'Release/pty.node': Operation not permitted
make: *** [Release/pty.node] Error 1
make: Leaving directory `/projects/nodejs/flunk/node_modules/gitty/node_modules/pty.js/build'
build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.15.5-aufs
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/nodejs/flunk/node_modules/gitty/node_modules/pty.js
gyp ERR! node -v v0.10.29
 v0.13.1 node-gyp -v\
gyp ERR! not ok

> ref@0.3.2 install /projects/nodejs/flunk/node_modules/gitty/node_modules/execSync/node_modules/ffi/node_modules/ref
> node-gyp rebuild

-
gyp: binding.gyp not found (cwd: /projects/nodejs/flunk/node_modules/gitty/node_modules/execSync/node_modules/ffi/node_modules/ref) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.15.5-aufs
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/nodejs/flunk/node_modules/gitty/node_modules/execSync/node_modules/ffi/node_modules/ref
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/projects/nodejs/flunk/node_modules/gitty/node_modules/execSync/node_modules/ffi/node_modules/ref'
npm ERR! error rolling back  gitty@2.1.2 { [Error: ENOTEMPTY, rmdir '/projects/nodejs/flunk/node_modules/gitty/node_modules/execSync/node_modules/ffi/node_modules/ref']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/projects/nodejs/flunk/node_modules/gitty/node_modules/execSync/node_modules/ffi/node_modules/ref' }
npm ERR! pty.js@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.2 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.15.5-aufs
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /projects/nodejs/flunk
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /projects/nodejs/flunk/npm-debug.log
npm ERR! not ok code 0
```

 If I run `npm install` with sudo, I run into an error that I should be running `npm install` as root. Everything is very b0rked :(

```
default@41acb05c081c:/projects/nodejs/flunk$ sudo npm install
npm WARN package.json flunk@ No repository field.
npm ERR! Error: EPERM, chown '/projects/nodejs/flunk/node_modules/gitty/package.json'
npm ERR!  { [Error: EPERM, chown '/projects/nodejs/flunk/node_modules/gitty/package.json']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/projects/nodejs/flunk/node_modules/gitty/package.json',
npm ERR!   fstream_finish_call: 'chown',
npm ERR!   fstream_type: 'File',
npm ERR!   fstream_path: '/projects/nodejs/flunk/node_modules/gitty/package.json',
npm ERR!   fstream_class: 'FileWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.15.5-aufs
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /projects/nodejs/flunk
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /projects/nodejs/flunk/node_modules/gitty/package.json
npm ERR! fstream_path /projects/nodejs/flunk/node_modules/gitty/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, chown '/projects/nodejs/flunk/node_modules/gitty/package.json'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /projects/nodejs/flunk/npm-debug.log
npm ERR! not ok code 0
```

On a side note, I _love_ to not have nodejs depending on a full python install. It seems like building binary packages could be handled entirely in node.

**Comment by tk120404** [comment]
@d11wtq Can you please close this issue if this is not issue any more?

**Comment by tk120404** [comment]
👍
