### ISSUE TITLE
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe".

### ISSUE THREAD

**Issue by ti-dev** [nodejs/node-gyp#488]
I also have this problem with `Could not load the Visual C++ component "VCBuild.exe".`. I already installed Microsoft Visual Studio Premium 2013. I also have the MS .NET Framework 4.5 SDK, MS Visual C++ 2012 Redistributable and Microsoft Windows SDK for Windows 7. So I think I have everything which id needed? But through command line `npm install grunt-svg-sprite --save-dev`I get this error, see below.

Any ideas how to solve this problem?

```
npm install grunt-svg-sprite --save-dev

[...]

`win32-x64-v8-3.14` exists; testing
Binary is fine; exiting
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\data\Projects\Project\node_modules\grunt-svg-sprite\node_modules\svg-sprite\node_modules\libxmljs
\build\binding.sln]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\data\Projects\Project\node_modules\grunt-svg-sprite\node_modules\svg-sprite\node_modules\libxmljs
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
unbuild libxmljs@0.8.1
unbuild svg-sprite@0.3.2
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\data\Projects\Project\node_modules\grunt-svg-sprite\node_modules\svg-sprite\node_modules\phantom-
sync\node_modules\phantom\node_modules\dnode\node_modules\weak\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\data\Projects\Project\node_modules\grunt-svg-sprite\node_modules\svg-sprite\node_modules\phantom-sync\node_modules\phantom\node_modules\dnode\node_modules\weak
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
unbuild weak@0.2.2
unbuild dnode@1.0.5
unbuild grunt-svg-sprite@0.3.2
unbuild phantom@0.5.7
unbuild phantom-sync@1.1.1
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by ostrolucky** [comment]
Here's a solution from #307 for those of you who stumbled on this issue as well:
> npm install --global --production windows-build-tools

**Comment by rvagg** [comment]
closing due to staleness
