### ISSUE TITLE
build on OSX 10.6.8 fails

### ISSUE THREAD

**Issue by nkhine** [nodejs/node-gyp#500]
when i try to build node-gyp on OSX 10.6.8 i get the following:

```
☺  node-gyp configure build                                                                                                                                 2.1.0 master 4dc4305""
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.28 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/khinester/Sandboxes/node-iconv/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/khinester/.node-gyp/0.10.28/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/khinester/.node-gyp/0.10.28',
gyp info spawn args   '-Dmodule_root_dir=/Users/khinester/Sandboxes/node-iconv',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
cc1: error: unrecognized command line option "-Wno-parentheses-equality"
cc1: error: unrecognized command line option "-Wno-static-in-inline"
cc1: error: unrecognized command line option "-Wno-tautological-compare"
make: *** [Release/obj.target/libiconv/deps/libiconv/lib/iconv.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/khinester/Sandboxes/node-iconv
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by gibfahn** [comment]
I think this can be closed. Let me know if it should be reopened.
