### ISSUE TITLE
error while node-gyp rebuild

### ISSUE THREAD

**Issue by yongjinkwon** [nodejs/node-gyp#501]
```
pi@raspberrypi ~ $ sudo node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.31 | linux | arm
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.10.31/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.31',
gyp info spawn args   '-Dmodule_root_dir=/home/pi',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/build'
make: *** No rule to make target 'Release/obj.target/binding/src/binding.o', needed by 'Release/obj.target/binding.node'.  Stop.
make: Leaving directory '/home/pi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.12.22+
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

this is my error code.

binding.gyp

```
{
"targets": [
      {
      "target_name": "binding",
      "sources": ["src/binding.cc"]
      }
   ]
}
```

I install 'npm make' and I do 'sudo apt-get install python-dev' then maybe installed python2.7
And i install 'sudo apt-get install gcc'
i don't understand
make: Entering directory '/home/pi/build'
make: **\* No rule to make target 'Release/obj.target/binding/src/binding.o', needed by 'Release/obj.target/binding.node'.  Stop.
make: Leaving directory '/home/pi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2          this sentence
what does this sentence mean?
why can`t i do?

**Comment by maclover7** [comment]
@yongjinkwon Are you able to reproduce this on a more recent version of `node-gyp`?

**Comment by maclover7** [comment]
Closing due to inactivity, please feel free to reopen if you are able to reproduce on a more recent version of node-gyp :)
