### ISSUE TITLE
gyp ERR! This is a bug in `node-gyp`.

### ISSUE THREAD

**Issue by totty90** [nodejs/node-gyp#539]
Got this error:

win 8 64 bit

```
c:\a\PowerCmd>npm install socket.io
npm WARN package.json app@0.0.0 No description
npm WARN package.json app@0.0.0 No repository field.
npm WARN package.json app@0.0.0 No README data
npm WARN package.json node-inspector@0.0.3 No repository field.
-\/-


> ws@0.5.0 install c:\a\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\\|2.7.3
-gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Invalid Version: 2.7.3
gyp ERR! stack [0x7FFF5648A038] ANOMALY: use of REX.w is meaningless (default operand size is 64)
gyp ERR! stack [0x7FFF56483EF0] ANOMALY: use of REX.w is meaningless (default operand size is 64)
gyp ERR! stack     at new SemVer (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:273:11)
gyp ERR! stack     at compare (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:456:10)
gyp ERR! stack     at gte (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:505:10)
gyp ERR! stack     at cmp (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:522:22)
gyp ERR! stack     at Comparator.test (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:592:10)
gyp ERR! stack     at testSet (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:926:17)
gyp ERR! stack     at Range.test (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:918:9)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:645:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\a\node_modules\socket.io\node_modules\engine.io\node_modules\ws
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
|-//


> ws@0.4.31 install c:\a\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\-2.7.3
|gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Invalid Version: 2.7.3
gyp ERR! stack [0x7FFF5648A038] ANOMALY: use of REX.w is meaningless (default operand size is 64)
gyp ERR! stack [0x7FFF56483EF0] ANOMALY: use of REX.w is meaningless (default operand size is 64)
gyp ERR! stack     at new SemVer (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:273:11)
gyp ERR! stack     at compare (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:456:10)
gyp ERR! stack     at gte (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:505:10)
gyp ERR! stack     at cmp (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:522:22)
gyp ERR! stack     at Comparator.test (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:592:10)
gyp ERR! stack     at testSet (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:926:17)
gyp ERR! stack     at Range.test (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\semver.js:918:9)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:645:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\a\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
--|/\|socket.io@1.2.1 ..\node_modules\socket.io
├── debug@0.7.4
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2)
├── socket.io-parser@2.2.2 (isarray@0.0.1, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── engine.io@1.4.3 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.1.0, ws@0.5.0)
└── socket.io-client@1.2.1 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.5, parseuri@0.0.2, engine.io-client@1.4.3)
```

**Comment by maclover7** [comment]
@totty90 Are you able to reproduce this on a more recent version of node-gyp?

**Comment by maclover7** [comment]
Closing due to inactivity, please feel free to reopen if you are able to reproduce on a more recent version of node-gyp :)
