### ISSUE TITLE
`No module named generator.msvs' how to resolve this error

### ISSUE THREAD

**Issue by liyuankui** [nodejs/node-gyp#550]
when installing ref,
the node calls node-gyp to `rebuild`

however the application throws out 
`ImportError: No module named generator.msvs`

```

  File "C:\Develop\Application\npm-1.4.9\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 19, in <module>
    sys.exit(gyp.script_main())
  File "C:\Develop\Application\npm-1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 537, in script_main
    return main(sys.argv[1:])
  File "C:\Develop\Application\npm-1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 530, in main
    return gyp_main(args)
  File "C:\Develop\Application\npm-1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 506, in gyp_main
    options.circular_check)
  File "C:\Develop\Application\npm-1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 94, in Load
    generator = __import__(generator_name, globals(), locals(), generator_name)
ImportError: No module named generator.msvs
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Develop\Application\npm-1.4.9\node_modules\npm\node_modules\node-gyp\lib\configure.js:340:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Develop\\Application\\npm-1.4.9\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\sc5-styleguide\node_modules\exec-sync\node_modules\ffi\node_modules\ref
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! ref@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

node-gyp@1.0.2  C:\Program Files\nodejs\node_modules\node-gyp
node@0.10.32
Python@2.7.5

**Comment by maclover7** [comment]
Are you able to reproduce this on a more recent version of node-gyp?

**Comment by maclover7** [comment]
Closing due to inactivity, please feel free to reopen if you are able to reproduce on a more recent version of node-gyp :)
