### ISSUE TITLE
NPM install fails, node-gyp rebuild seems to fail on file not found

### ISSUE THREAD

**Issue by Siraris** [nodejs/node-gyp#558]
Getting the following error while trying to install the karma javascript test runner using NPM.  Is this a node-gyp issue?  Any idea how to fix?

```
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:29:
/usr/include/c++/4.2.1/string:46:10: fatal error: 'bits/stringfwd.h' file not found
#include <bits/stringfwd.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Siraris/node_modules/karma/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.1
```

**Comment by maclover7** [comment]
@Siraris Are you able to reproduce this on a more recent version of node-gyp?

**Comment by Siraris** [comment]
@maclover7 I have no idea... I submitted this almost 4 years ago.  I don't even remember what I was working on at the time.

**Comment by maclover7** [comment]
@Siraris Ok, no problem; will close out this issue then
