### ISSUE TITLE
node-pre-gyp error when install ghost

### ISSUE THREAD

**Issue by bytekve** [nodejs/node-gyp#570]
I spend all day to findout and solve this problem, but no reward
Im using Centos 5.5, and follow this tutorial:
http://howtoinstallghost.com/how-to-install-ghost-on-centos-server-6-4/
But I received an error:
```
sqlite3@3.0.4 install /home/domain.com/node_modules/sqlite3
node-pre-gyp install --fallback-to-build
gyp ERR! Completion callback never invoked!
gyp ERR! System Linux 2.6.18-194.el5
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=./lib/sqlite3" "--host=h**ps://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/home/byte/domain.com/node_modules/sqlite3/lib/binding/node-v11-linux-ia32" "--module=/home/byte/domain.com/node_modules/sqlite3/lib/binding/node-v11-linux-ia32/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package_name=node-v11-linux-ia32.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-ia32.tar.gz""--hosted_path=h**ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/" "--hosted_tarball=h**ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-ia32.tar.gz" "--python=python2.7"
gyp ERR! cwd /home/domain.com/node_modules/sqlite3
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! This is a bug in node-gyp.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR! 
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3--patch=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --host=h**ps://mapbox-node-binary.s3.amazonaws.com/ --module_path=/home/domain.com/node_modules/sqlite3/lib/binding/node-v11-linux-ia32 --module=/home/byte/domain.com/node_modules/sqlite3/lib/binding/node-v11-linux-ia32/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-ia32.tar.gz --hosted_path=h**ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=h**ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-ia32.tar.gz --python=python2.7' (6)
node-pre-gyp ERR! stack at ChildProcess. (/home/byte/tajquangkhan
hs.com/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (child_proces
s.js:833:5)
node-pre-gyp ERR! System Linux 2.6.18-194.el5
node-pre-gyp ERR! command "node" "/home/domain.com/node_modules/sql
ite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/domain.com/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.36
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --host=h**ps://mapbox-node-binary.s3.amazonaws.com/ --module_path=/home/domain.com/node_modules/sqlite3/lib/binding/node-v11-linux-ia32 --module=/home/domain.com/node_modules/sqlite3/lib/binding/node-v11-linux-ia32/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-ia32.tar.gz --hosted_path=h**ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=h**ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-ia32.tar.gz --python=python2.7' (6)npm ERR! sqlite3@3.0.4 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR! npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.18-194.el5
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
"--build-from-source"
npm ERR! cwd /home/domain.com
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by Fishrock123** [comment]
```
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR! npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
```

Please report to https://github.com/mapbox/node-sqlite3 if this is still an issue.
