### ISSUE TITLE
node-gyp rebuild fails miserably, crashes my pc

### ISSUE THREAD

**Issue by thmour** [nodejs/node-gyp#584]
I use win8.1 64bit with latest node (v0.12) and npm (v2.6.1) and when I install a module that requires node-gyp rebuild, my pc almost crashes because it spawns thousands of python.exe processes (22k in 10 secs). The command window becomes unresponsive and I can't send a `ctr-c` signal or close the command window. When I use taskill to kill all python.exe there is a chance that the spawning rate is greater than the kill rate and I have to restart my pc. Happens on every module that runs node-gyp rebuild. This is the message of a successful task kill.

```
> hiredis@0.2.0 install C:\Users\theofilos\Desktop\api\node_modules\hiredis
> node-gyp rebuild


C:\Users\theofilos\Desktop\api\node_modules\hiredis>node "C:\Users\theofilos\AppData\Roaming\npm\nod
e_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\theofilos\AppData\Roaming\npm\node_modules\npm
\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\theofilos\\AppData\\Roaming\\npm\\node_modules\\npm\\node_module
s\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\theofilos\Desktop\api\node_modules\hiredis
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\theofilos\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.j
s" "install" "hiredis" "redis"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.
npm ERR! error rolling back Error: EBUSY, unlink 'C:\Users\theofilos\Desktop\api\node_modules\hiredi
s'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, unlink 'C:\Users\theofilos\Desktop\api\node_modules\hi
redis']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Users\\theofilos\\Desktop\\api\\node_modules\\hiredis' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\theofilos\Desktop\api\npm-debug.log
```

The spawning begins when the child_proccess message occurs, and then the rest after i kill all python proccesses.

**Comment by thmour** [comment]
Seems like node-gyp doesn't work with the default python executable found on `C:\Windows\python.exe`, had to rename it back to `py` and add to path the `C:\Python27` so it uses that executable

**Comment by a0viedo** [comment]
hey @thmour, it's been some time now, is this still an issue?

**Comment by gibfahn** [comment]
@thmour  let me know if this is still an issue and I'll reopen.

**Comment by thmour** [comment]
I will try it again and I will let you know

**Comment by deed02392** [comment]
My Debian Stretch VM appears to lock up with 100% CPU util during a remote SSH session:

```
gyp ERR! not ok

> uws@9.14.0 install /home/x/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.9.3 install /home/x/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-57_binding.node
Download complete..] - :
Binary saved to /home/x/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/x/.npm/node-sass/4.9.3/linux-x64-57_binding.node

> sharp@0.19.1 install /home/x/node_modules/sharp
> node-gyp rebuild

Connection reset by x.x.x.x port 22
```
