### ISSUE TITLE
node-gyp barfs on Windows 8.1 with node 0.8.28

### ISSUE THREAD

**Issue by baumatron** [nodejs/node-gyp#590]
I can't seem to get node-gyp to run. Here's the output I see:

C:\Users\Brian\Documents\Projects\alarming\Server\site\wwwroot>node-gyp configure

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\node-gyp\node_modules\npmlog\node_modules\are-we-there-yet\index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\node-gyp\node_modules\npmlog\log.js:2:16)
    at Module._compile (module.js:449:26)

Attempting to run node-gyp with or without any parameters results in the same failure. Any ideas? This is a machine on which I had node 0.10.20 installed previously, but uninstalled node, cleared out npm and npm-cache from roaming\appdata, and ensured the node folder under program files had been removed before installing node 0.8.28, updating to npm 2.7.0, and then running npm install -g node-gyp.

**Comment by baumatron** [comment]
FWIW the failure I'm seeing is with node-gyp 1.0.3. I just installed 1.0.2 and it seems to work fine.

**Comment by a0viedo** [comment]
hey @baumatron, it's been long time, is this still an issue?

**Comment by gibfahn** [comment]
@baumatron let me know if this is still an issue and I'll reopen.
