### ISSUE TITLE
some error to solve:gyp: deps\winpty\winpty.gyp not found

### ISSUE THREAD

**Issue by zuoRambo** [nodejs/node-gyp#601]
```
> pty.js@0.2.6 install C:\Users\Rambo\AppData\Roaming\npm\node_modules\devtools-terminal\node_modules\pty.js
> node-gyp rebuild


C:\Users\Rambo\AppData\Roaming\npm\node_modules\devtools-terminal\node_modules\pty.js>node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\Rambo\AppData\Roaming\npm\node_modules\devtools-terminal\node_modules\pty.js)
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rambo\AppData\Roaming\npm\node_modules\devtools-terminal\node_modules\pty.js
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
```

the follow errors was thrown when i run the command 'npm install -g devtools-termianal', how could i  to get winpty folder ?thanks a lot

**Comment by a0viedo** [comment]
hey @zuoRambo, it's been some time now, is this still an issue?

**Comment by zuoRambo** [comment]
@a0viedo not any more. thanks.
