### ISSUE TITLE
Scratching my head getting nowhere

### ISSUE THREAD

**Issue by SteveyPugs** [nodejs/node-gyp#618]
All,

I've tried installing varying packages that have node-gyp in them and the all fail for the same exact reason. I've done everything here back to front and can't find an answer. I install and uninstalled everything as stated and found that I can run the build perfectly fine if I go into the actual package, its went I try to do the install from outside the folder it crashes.

Here is the error I get I cant figure out why my CWD always go back to C: for no reason

```
C:\>npm install heapdump
npm WARN package.json @1.0.0 No description
npm WARN package.json @1.0.0 No repository field.
npm WARN package.json @1.0.0 No README data
|
> heapdump@0.3.5 install C:\node_modules\heapdump
> node-gyp rebuild


C:\>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
\node-gyp.js" rebuild
gyp: binding.gyp not found (cwd: C:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\n
ode-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild"
gyp ERR! cwd C:\
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! heapdump@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.5 install script.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "heapdump"
npm ERR! cwd C:\
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\>
C:\>npm install heapdump --msvsversion=2012
npm WARN package.json @1.0.0 No description
npm WARN package.json @1.0.0 No repository field.
npm WARN package.json @1.0.0 No README data
|
> heapdump@0.3.5 install C:\node_modules\heapdump
> node-gyp rebuild


C:\>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
\node-gyp.js" rebuild
gyp: binding.gyp not found (cwd: C:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\n
ode-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild"
gyp ERR! cwd C:\
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! heapdump@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.5 install script.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "heapdump" "--msvsversion=2012"
npm ERR! cwd C:\
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\>

```

Any help would be appreciated.

**Comment by SteveyPugs** [comment]
Btw WIndows 7 x64

**Comment by maclover7** [comment]
@SteveyPugs Are you able to reproduce this on a more recent version of node-gyp?

**Comment by SteveyPugs** [comment]
Nope

Having issues with getting https://github.com/felixrieseberg/windows-build-tools installed.

![image](https://user-images.githubusercontent.com/2607556/43083332-3e23e176-8e64-11e8-8399-c507ba5bec46.png)

**Comment by SteveyPugs** [comment]
So I tried this using node v8.11 and got this:

![image](https://user-images.githubusercontent.com/2607556/43163648-c1c3dd30-8f5c-11e8-8306-1c52dbe53021.png)

**Comment by SteveyPugs** [comment]
@maclover7 we have since bumped to 8.11.4. It works now. Closing this.
