### ISSUE TITLE
Build fails on NTFS mounted drive with exit status 126

### ISSUE THREAD

**Issue by Demurgos** [nodejs/node-gyp#654]
Hi,
I have a computer with a Windows/Debian 7 dual boot . I store my node.js projects on a shared partition formatted with NTFS (so Windows is able to read it).
I recently added [scrypt](https://github.com/barrysteyn/node-scrypt) as a dependency to my project. This module uses node-gyp. When I `npm install`'ed on Windows, everything went right and I could use this module.
Then I switched to Linux and got a problem : node-gyp was unable to build my application. I removed the whole `node_modules` directory and did a clean `npm install` but it failed (even with `sudo`).
After a few trials, I decided to copy my project from the shared NTFS drive to the linux ext4 drive and this time a simple `npm install` worked fine.
Note that I already installed modules with node-gyp bindings on this drive (ie. bson) : it's the first time I have this sort of issue.

I tried to install scrypt on its own to narrow down the issue:
````bash
git clone https://github.com/barrysteyn/node-scrypt.git
cd node-scrypt
npm install
node-gyp configure build
````
The error occurs when I type `node-gyp rebuild` :

````bash
csamborski@SAMCHAPC:/media/shared/web/node-scrypt$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@0.10.39 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/media/shared/web/node-scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/csamborski/.node-gyp/0.10.39/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/csamborski/.node-gyp/0.10.39',
gyp info spawn args   '-Dmodule_root_dir=/media/shared/web/node-scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: 1: scrypt/configuration/posixconfig: Permission denied
gyp: Call to 'scrypt/configuration/posixconfig' returned exit status 126. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /media/shared/web/node-scrypt
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
````

I tried to set a `chmod 777` on the whole drive and run the command as root, the error persists.
I cannot exactly understand what command is executed by node-gyp to produce the line `/bin/sh: 1: scrypt/configuration/posixconfig: Permission denied` so I couldn't try in the terminal to verify the permission manually.

One last thing : Since I was able to build on the ext4 drive, I then copied the directory back to the NTFS drive and got the following error (even with sudo):
````bash
csamborski@SAMCHAPC:/media/shared/web/node-scrypt$ node
> require('./index')
Error: /media/shared/web/node-scrypt/build/Release/scrypt.node: failed to map segment from shared object: Operation not permitted
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/media/shared/web/node-scrypt/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````

Thank you for taking time to read this and I hope that it will help this project.

**Comment by Demurgos** [comment]
After some search, I finally found the solution. I had to add the `exec` option for the drive to my `fstab` config.
