### ISSUE TITLE
gyp_main.py: error: no such option: --no-parallel

### ISSUE THREAD

**Issue by anmolshkl** [nodejs/node-gyp#655]
I was trying to install memwatch and ran into this error:
```
gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memwatch"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anmol/Juspay/benchmark/nodejs/npm-debug.log
```
Output from npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'memwatch' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of /home/anmol/Juspay/benchmark/nodejs/package.json
5 warn package.json redirect@0.0.1 No description
6 warn package.json redirect@0.0.1 No repository field.
7 warn package.json redirect@0.0.1 No README data
8 warn package.json redirect@0.0.1 No license field.
9 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/agentkeepalive/package.json
10 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/bluebird/package.json
11 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/connect/package.json
12 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/cool-ascii-faces/package.json
13 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/form-urlencoded/package.json
14 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/htmlparser2/package.json
15 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/node-statsd/package.json
16 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/node-uuid/package.json
17 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/pm2/package.json
18 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/promise/package.json
19 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/redis/package.json
20 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/request/package.json
21 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/restify/package.json
22 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/restify-cookies/package.json
23 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/sticky-session/package.json
24 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/strong-cluster-tls-store/package.json
25 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/strong-store-cluster/package.json
26 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/winston/package.json
27 verbose installManyTop reading scoped package data from /home/anmol/Juspay/benchmark/nodejs/node_modules/winston-cloudwatch/package.json
28 info package.json cool-ascii-faces@1.3.3 license should be a valid SPDX license expression
29 info package.json node-statsd@0.1.1 No license field.
30 info package.json node-uuid@1.4.3 No license field.
31 info package.json redis@0.12.1 No license field.
32 info package.json restify@3.0.3 No license field.
33 info package.json sticky-session@0.1.0 No repository field.
34 info package.json sticky-session@0.1.0 No license field.
35 info package.json winston@1.0.0 No license field.
36 info package.json form-urlencoded@0.0.7 No license field.
37 verbose readDependencies loading dependencies from /home/anmol/Juspay/benchmark/nodejs/package.json
38 silly cache add args [ 'memwatch', null ]
39 verbose cache add spec memwatch
40 silly cache add parsed spec { raw: 'memwatch',
40 silly cache add   scope: null,
40 silly cache add   name: 'memwatch',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: '*',
40 silly cache add   type: 'range' }
41 silly addNamed memwatch@*
42 verbose addNamed "*" is a valid semver range for memwatch
43 silly addNameRange { name: 'memwatch', range: '*', hasData: false }
44 silly mapToRegistry name memwatch
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/memwatch
48 verbose addNameRange registry:https://registry.npmjs.org/memwatch not in flight; fetching
49 verbose get https://registry.npmjs.org/memwatch not expired, no request
50 silly addNameRange number 2 { name: 'memwatch', range: '*', hasData: true }
51 silly addNameRange versions [ 'memwatch',
51 silly addNameRange   [ '0.1.0',
51 silly addNameRange     '0.1.1',
51 silly addNameRange     '0.1.2',
51 silly addNameRange     '0.1.3',
51 silly addNameRange     '0.1.4',
51 silly addNameRange     '0.1.5',
51 silly addNameRange     '0.2.0',
51 silly addNameRange     '0.2.1',
51 silly addNameRange     '0.2.2' ] ]
52 silly addNamed memwatch@0.2.2
53 verbose addNamed "0.2.2" is a plain semver version for memwatch
54 silly cache afterAdd memwatch@0.2.2
55 verbose afterAdd /home/anmol/.npm/memwatch/0.2.2/package/package.json not in flight; writing
56 verbose afterAdd /home/anmol/.npm/memwatch/0.2.2/package/package.json written
57 silly install resolved [ { name: 'memwatch',
57 silly install resolved     description: 'Keep an eye on your memory usage, and discover and isolate leaks.',
57 silly install resolved     version: '0.2.2',
57 silly install resolved     author: { name: 'Lloyd Hilaiel', url: 'http://lloyd.io' },
57 silly install resolved     engines: { node: '>= 0.6.0' },
57 silly install resolved     repository:
57 silly install resolved      { type: 'git',
57 silly install resolved        url: 'git+https://github.com/lloyd/node-memwatch.git' },
57 silly install resolved     main: 'include.js',
57 silly install resolved     licenses: [ [Object] ],
57 silly install resolved     bugs: { url: 'https://github.com/lloyd/node-memwatch/issues' },
57 silly install resolved     scripts: { install: 'node-gyp rebuild', test: 'mocha tests' },
57 silly install resolved     devDependencies: { mocha: '1.2.2', should: '0.6.3', 'node-gyp': '0.5.7' },
57 silly install resolved     contributors: [ [Object], [Object], [Object] ],
57 silly install resolved     readme: '`node-memwatch`: Leak Detection and Heap Diffing for Node.JS\n============================================================\n\n[![Build Status](https://secure.travis-ci.org/lloyd/node-memwatch.png)](http://travis-ci.org/lloyd/node-memwatch)\n\n`node-memwatch` is here to help you detect and find memory leaks in\nNode.JS code.  It provides:\n\n- A `leak` event, emitted when it appears your code is leaking memory.\n\n- A `stats` event, emitted occasionally, giving you\n  data describing your heap usage and trends over time.\n\n- A `HeapDiff` class that lets you compare the state of your heap between\n  two points in time, telling you what has been allocated, and what\n  has been released.\n\n\nInstallation\n------------\n\n- `npm install memwatch`\n\nor\n\n- `git clone git://github.com/lloyd/node-memwatch.git`\n\n\nDescription\n-----------\n\nThere are a growing number of tools for debugging and profiling memory\nusage in Node.JS applications, but there is still a need for a\nplatform-independent native module that requires no special\ninstrumentation.  This module attempts to satisfy that need.\n\nTo get started, import `node-memwatch` like so:\n\n```javascript\nvar memwatch = require(\'memwatch\');\n```\n\n### Leak Detection\n\nYou can then subscribe to `leak` events.  A `leak` event will be\nemitted when your heap usage has increased for five consecutive\ngarbage collections:\n\n```javascript\nmemwatch.on(\'leak\', function(info) { ... });\n```\n\nThe `info` object will look something like:\n\n```javascript\n{ start: Fri, 29 Jun 2012 14:12:13 GMT,\n  end: Fri, 29 Jun 2012 14:12:33 GMT,\n  growth: 67984,\n  reason: \'heap growth over 5 consecutive GCs (20s) - 11.67 mb/hr\' }\n```\n\n\n### Heap Usage\n\nThe best way to evaluate your memory footprint is to look at heap\nusage right aver V8 performs garbage collection.  `memwatch` does\nexactly this - it checks heap usage only after GC to give you a stable\nbaseline of your actual memory usage.\n\nWhen V8 performs a garbage collection (technically, we\'re talking\nabout a full GC with heap compaction), `memwatch` will emit a `stats`\nevent.\n\n```javascript\nmemwatch.on(\'stats\', function(stats) { ... });\n```\n\nThe `stats` data will look something like this:\n\n```javascript\n{\n  "num_full_gc": 17,\n  "num_inc_gc": 8,\n  "heap_compactions": 8,\n  "estimated_base": 2592568,\n  "current_base": 2592568,\n  "min": 2499912,\n  "max": 2592568,\n  "usage_trend": 0\n}\n```\n\n`estimated_base` and `usage_trend` are tracked over time.  If usage\ntrend is consistently positive, it indicates that your base heap size\nis continuously growing and you might have a leak.\n\nV8 has its own idea of when it\'s best to perform a GC, and under a\nheavy load, it may defer this action for some time.  To aid in\nspeedier debugging, `memwatch` provides a `gc()` method to force V8 to\ndo a full GC and heap compaction.\n\n\n### Heap Diffing\n\nSo far we have seen how `memwatch` can aid in leak detection.  For\nleak isolation, it provides a `HeapDiff` class that takes two snapshots\nand computes a diff between them.  For example:\n\n```javascript\n// Take first snapshot\nvar hd = new memwatch.HeapDiff();\n\n// do some things ...\n\n// Take the second snapshot and compute the diff\nvar diff = hd.end();\n```\n\nThe contents of `diff` will look something like:\n\n```javascript\n{\n  "before": { "nodes": 11625, "size_bytes": 1869904, "size": "1.78 mb" },\n  "after":  { "nodes": 21435, "size_bytes": 2119136, "size": "2.02 mb" },\n  "change": { "size_bytes": 249232, "size": "243.39 kb", "freed_nodes": 197,\n    "allocated_nodes": 10007,\n    "details": [\n      { "what": "String",\n        "size_bytes": -2120,  "size": "-2.07 kb",  "+": 3,    "-": 62\n      },\n      { "what": "Array",\n        "size_bytes": 66687,  "size": "65.13 kb",  "+": 4,    "-": 78\n      },\n      { "what": "LeakingClass",\n        "size_bytes": 239952, "size": "234.33 kb", "+": 9998, "-": 0\n      }\n    ]\n  }\n```\n\nThe diff shows that during the sample period, the total number of\nallocated `String` and `Array` classes decreased, but `Leaking Class`\ngrew by 9998 allocations.  Hmmm.\n\nYou can use `HeapDiff` in your `on(\'stats\')` callback; even though it\ntakes a memory snapshot, which triggers a V8 GC, it will not trigger\nthe `stats` event itself.  Because that would be silly.\n\n\nFuture Work\n-----------\n\nPlease see the Issues to share suggestions and contribute!\n\n\nLicense\n-------\n\nhttp://wtfpl.org\n',
57 silly install resolved     readmeFilename: 'README.md',
57 silly install resolved     _id: 'memwatch@0.2.2',
57 silly install resolved     dist:
57 silly install resolved      { shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
57 silly install resolved        tarball: 'http://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz' },
57 silly install resolved     _from: 'memwatch@*',
57 silly install resolved     _npmVersion: '1.2.14',
57 silly install resolved     _npmUser: { name: 'lloyd', email: 'lloyd@hilaiel.com' },
57 silly install resolved     maintainers: [ [Object] ],
57 silly install resolved     directories: {},
57 silly install resolved     _shasum: '779e8cd982532b6221b6ed1c1269098bee16f92c',
57 silly install resolved     _resolved: 'https://registry.npmjs.org/memwatch/-/memwatch-0.2.2.tgz',
57 silly install resolved     gypfile: true,
57 silly install resolved     homepage: 'https://github.com/lloyd/node-memwatch#readme' } ]
58 info install memwatch@0.2.2 into /home/anmol/Juspay/benchmark/nodejs
59 info installOne memwatch@0.2.2
60 verbose installOne of memwatch to /home/anmol/Juspay/benchmark/nodejs not in flight; installing
61 verbose lock using /home/anmol/.npm/_locks/memwatch-276aaba06645ac9d.lock for /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
62 silly install write writing memwatch 0.2.2 to /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
63 verbose unbuild node_modules/memwatch
64 silly gentlyRm /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch is being purged from base /home/anmol/Juspay/benchmark/nodejs
65 verbose gentlyRm don't care about contents; nuking /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
66 verbose tar unpack /home/anmol/.npm/memwatch/0.2.2/package.tgz
67 verbose tar unpacking to /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
68 silly gentlyRm /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch is being purged
69 verbose gentlyRm don't care about contents; nuking /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
70 silly gunzTarPerm modes [ '755', '644' ]
71 silly gunzTarPerm extractEntry package.json
72 silly gunzTarPerm extractEntry .npmignore
73 silly gunzTarPerm extractEntry README.md
74 silly gunzTarPerm extractEntry tests.js
75 silly gunzTarPerm extractEntry foo.js
76 silly gunzTarPerm extractEntry include.js
77 silly gunzTarPerm extractEntry .travis.yml
78 silly gunzTarPerm extractEntry ChangeLog
79 silly gunzTarPerm extractEntry #wscript#
80 silly gunzTarPerm extractEntry binding.gyp
81 silly gunzTarPerm extractEntry src/heapdiff.cc
82 silly gunzTarPerm extractEntry src/heapdiff.hh
83 silly gunzTarPerm extractEntry src/init.cc
84 silly gunzTarPerm extractEntry src/memwatch.cc
85 silly gunzTarPerm extractEntry src/memwatch.hh
86 silly gunzTarPerm extractEntry src/platformcompat.hh
87 silly gunzTarPerm extractEntry src/util.cc
88 silly gunzTarPerm extractEntry src/util.hh
89 silly gunzTarPerm extractEntry examples/basic_heapdiff.js
90 silly gunzTarPerm extractEntry examples/do_nothing_server.js
91 silly gunzTarPerm extractEntry examples/slightly_leaky.js
92 verbose write writing to /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch/package.json
93 info preinstall memwatch@0.2.2
94 verbose readDependencies loading dependencies from /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch/package.json
95 verbose readDependencies loading dependencies from /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch/package.json
96 silly install resolved []
97 verbose about to build /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
98 info build /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
99 info linkStuff memwatch@0.2.2
100 silly linkStuff memwatch@0.2.2 has /home/anmol/Juspay/benchmark/nodejs/node_modules as its parent node_modules
101 verbose linkBins memwatch@0.2.2
102 verbose linkMans memwatch@0.2.2
103 verbose rebuildBundles memwatch@0.2.2
104 info install memwatch@0.2.2
105 verbose unsafe-perm in lifecycle false
106 info memwatch@0.2.2 Failed to exec install script
107 verbose unlock done using /home/anmol/.npm/_locks/memwatch-276aaba06645ac9d.lock for /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
108 verbose stack Error: memwatch@0.2.2 install: `node-gyp rebuild`
108 verbose stack Exit status 1
108 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
108 verbose stack     at EventEmitter.emit (events.js:110:17)
108 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
108 verbose stack     at ChildProcess.emit (events.js:110:17)
108 verbose stack     at maybeClose (child_process.js:1015:16)
108 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
109 verbose pkgid memwatch@0.2.2
110 verbose cwd /home/anmol/Juspay/benchmark/nodejs
111 error Linux 3.13.0-46-generic
112 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memwatch"
113 error node v0.12.5
114 error npm  v2.11.2
115 error code ELIFECYCLE
116 error memwatch@0.2.2 install: `node-gyp rebuild`
116 error Exit status 1
117 error Failed at the memwatch@0.2.2 install script 'node-gyp rebuild'.
117 error This is most likely a problem with the memwatch package,
117 error not with npm itself.
117 error Tell the author that this fails on your system:
117 error     node-gyp rebuild
117 error You can get their info via:
117 error     npm owner ls memwatch
117 error There is likely additional logging output above.
118 verbose exit [ 1, true ]
119 verbose unbuild node_modules/memwatch
120 info preuninstall memwatch@0.2.2
121 info uninstall memwatch@0.2.2
122 verbose unbuild rmStuff memwatch@0.2.2 from /home/anmol/Juspay/benchmark/nodejs/node_modules
123 info postuninstall memwatch@0.2.2
124 silly gentlyRm /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch is being purged from base /home/anmol/Juspay/benchmark/nodejs
125 verbose gentlyRm don't care about contents; nuking /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
126 silly vacuum-fs purging /home/anmol/Juspay/benchmark/nodejs/node_modules/memwatch
127 silly vacuum-fs quitting because other entries in /home/anmol/Juspay/benchmark/nodejs/node_modules
```
This has happened before also while installing few other modules.

**Comment by cesarob** [comment]
Same problem here when building hiredis 0.1.15.
I have npm@2.14.0, node@0.10.26.

My machine is an ubuntu 13.10 with gyp@0.1 installed via apt-get

**Comment by bnoordhuis** [comment]
`--no-parallel` was added in node.js v0.10.27 / npm v1.4.6 / node-gyp v0.13.0.

It looks like node-memwatch depends on node-gyp@0.5.7, which is a bug that you should report to the module's maintainer (although last I checked, it was effectively unmaintained.  YMMV.)  It shouldn't really depend on node-gyp at all and certainly not on a version that old.

**Comment by dpkshrma** [comment]
Hi, I have updated my node-gyp to v3.0.3 using [this](https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp) but still it gave me this same error, so it turns out that ubuntu has its own gyp (mentioned [here](https://github.com/nodejs/node-gyp/issues/426#issuecomment-54112531) by aviynw ) which was seemingly interfering with `node-gyp rebuild`.
So, I removed it, `sudo apt-get remove gyp` and got rid of the error but got a new error due to the absence of gyp [package xi not found](http://pastebin.com/5fWU1CXU) So, gyp is required but at the same time problematic in rebuild, what should i do here?

**Comment by dpkshrma** [comment]
ok, so i got this fixed. I admit it was stupid to think that the latter error was due to absence of gyp. So, all i did was install the missing libxi-dev (`sudo apt-get install libxi-dev`) and everything worked smoothly :)
