### ISSUE TITLE
npm intall node-gyp fails with Error: No compatible version found: mkdirp@'^0.5.0'

### ISSUE THREAD

**Issue by bimalkjha** [nodejs/node-gyp#687]
```
$ npm install node-gyp
.....
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/npmlog
npm ERR! Error: No compatible version found: mkdirp@'^0.5.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1"]
npm ERR!     at installTargetsError (/home/amprasan/ctz_node/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/amprasan/ctz_node/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/home/amprasan/ctz_node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /home/amprasan/ctz_node/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.18-406.el5
npm ERR! command "/home/amprasan/ctz_node/bin/node" "/home/amprasan/ctz_node/bin/npm" "install" "node-gyp"
npm ERR! cwd /home/amprasan/ctz_node/bin/node-ibm_db
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
npm http 304 https://registry.npmjs.org/osenv
npm http 304 https://registry.npmjs.org/path-array
.....
```

**Comment by Fishrock123** [comment]
@bimalkjha This is an npm issue. I suspect your npm may be too old, and you should consider upgrading to npm 2.x.

Please keep future npm reports to http://github.com/npm/npm/issues as it says in the error long. :)
