### ISSUE TITLE
Error: 404 response dowloading https://nodejs.org/dist/v2.5.0/node-v2.5.0.tar.gz

### ISSUE THREAD

**Issue by binarykitchen** [nodejs/node-gyp#689]
... and is breaking my site :(

**Comment by binarykitchen** [comment]
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v2.5.0/node-v2.5.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.12.27-xenU
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/videomail/production/source/node_modules/sharp
gyp ERR! node -v v2.5.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.12.27-xenU
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
```

**Comment by binarykitchen** [comment]
The URL is wrong. node.js.org does not host iojs files.

**Comment by binarykitchen** [comment]
Hello?

**Comment by binarykitchen** [comment]
Heeeeeellooo???

**Comment by rvagg** [comment]
you need to use the version of npm (and therefore node-gyp) that comes shipped with io.js, we've hacked it to make it download from iojs.org instead of nodejs.org

alternatively use pangyp but I'm not actively supporting that, it was meant to be a temporary hack

we'll get it sorted out here in node-gyp very soon!
