### ISSUE TITLE
Installing Protractor

### ISSUE THREAD

**Issue by skullz03** [nodejs/node-gyp#691]
Hi Users, 

I have 64 bit window 7 OS machine and I have been trying to install Protractor from nodejs. The node js installation was successful but when i run the command: npm install -g Protractor I get the below error. Could someone please help ?
```
C:\Users\A418097>npm install -g protractor
\


> utf-8-validate@1.1.0 install C:\Users\A418097\AppData\Roaming\npm\node_modules
\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-v
alidate
> node-gyp rebuild

-
C:\Users\A418097\AppData\Roaming\npm\node_modules\protractor\node_modules\seleni
um-webdriver\node_modules\ws\node_modules\utf-8-validate>if not defined npm_conf
ig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
c:\users\a418097\.node-gyp\0.12.7\deps\uv\include\uv-win.h(32): fatal error C10
83: Cannot open include file: 'winsock2.h': No such file or directory [C:\Users
\A418097\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webd
river\node_modules\ws\node_modules\utf-8-validate\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\A418097\AppData\Roaming\npm\node_modules\protractor\node_m
odules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> bufferutil@1.1.0 install C:\Users\A418097\AppData\Roaming\npm\node_modules\pro
tractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\A418097\AppData\Roaming\npm\node_modules\protractor\node_modules\seleni
um-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_config_n
ode_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
c:\users\a418097\.node-gyp\0.12.7\deps\uv\include\uv-win.h(32): fatal error C10
83: Cannot open include file: 'winsock2.h': No such file or directory [C:\Users
\A418097\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webd
river\node_modules\ws\node_modules\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\A418097\AppData\Roaming\npm\node_modules\protractor\node_m
odules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
C:\Users\A418097\AppData\Roaming\npm\webdriver-manager -> C:\Users\A418097\AppDa
ta\Roaming\npm\node_modules\protractor\bin\webdriver-manager
C:\Users\A418097\AppData\Roaming\npm\protractor -> C:\Users\A418097\AppData\Roam
ing\npm\node_modules\protractor\bin\protractor
protractor@2.1.0 C:\Users\A418097\AppData\Roaming\npm\node_modules\protractor
├── jasminewd@1.1.0
├── jasminewd2@0.0.5
├── html-entities@1.1.3
├── saucelabs@0.1.1
├── q@1.0.0
├── minijasminenode@1.1.1
├── adm-zip@0.4.4
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── jasmine@2.3.1 (exit@0.1.2, jasmine-core@2.3.4)
├── accessibility-developer-tools@2.6.0
├── source-map-support@0.2.10 (source-map@0.1.32)
├── lodash@2.4.2
├── request@2.36.0 (forever-agent@0.5.2, qs@0.6.6, aws-sign2@0.5.0, oauth-sign@0
.3.0, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, mime@1.2.11, node-uuid@1.4.
3, form-data@0.1.4, http-signature@0.10.1, tough-cookie@2.0.0, hawk@1.0.0)
└── selenium-webdriver@2.45.1 (tmp@0.0.24, rimraf@2.4.2, xml2js@0.4.4, ws@0.7.2)
```

**Comment by Sogl** [comment]
See this thread:
https://github.com/nodejs/node-gyp/issues/629
