### ISSUE TITLE
yo webapp with node-gyp failing on Windows x64

### ISSUE THREAD

**Issue by justnull** [nodejs/node-gyp#709]
My attempts to use node-gyp on a Windows 7 + Node.js.when attempting to yo webapp grunt-by-yo-92.I has search the problem for three days,but can not find answer.
.
Configuration:

node-gyp v2.0.2
Windows 7 x64 SP1
Python 2.7.3
Node.js 0.12.7
Visual Studio 2013 
VS SDK 7.1 per [1] ( 64 bit versions)
running yo webapp grunt-by-yo-92 from standard Windows Command Prompt or SDK7.1 cmd prompt
<pre><code>
> bufferutil@1.1.0 install E:\webapp\grunt-in-action-taobaonpm\grunt-by-yo-92\no
de_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

\
E:\webapp\grunt-in-action-taobaonpm\grunt-by-yo-92\node_modules\grunt-browser-sy
nc\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_
modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "E:\
ProgramFiles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。(A project in this solution,To enable parallel generation,Please add the "/m" switch)
E:\webapp\grunt-in-action-taobaonpm\grunt-by-yo-92\node_modules\grunt-browser-s
ync\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\nod
e_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj(20,3): error MSB4
019: 未找到导入的项目(Failed to find the imported project)“E:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中
的路径正确，且磁盘上存在该文件。(Confirmation of the path in the <Import> statement is correct,And there is the file on the disk.)
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\ProgramFiles\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "E:\\ProgramFiles\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\webapp\grunt-in-action-taobaonpm\grunt-by-yo-92\node_modules\gru
nt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\en
gine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.8
</code></pre>

<pre><node>
e:\yo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\so
ket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules
ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "e:\Pro
ramFiles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
in\node-gyp.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。(A project in this solution,To enable parallel generation,Please add the "/m" switch)
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(308,5): error MSB3491: 未能向文件(Failed to file)“Release\obj\validation\validation.tlog\va
idation.lastbuildstate”写入命令行(write in command line)。指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。 
(The specified path or file name is too long,Or both are too long,Fully qualified file name must be less than 260 characters,And directory name must be less than 248 characters.)[e:\yo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_mo
ul
es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m
odules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fai
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (e:\ProgramFiles\nodejs\node_modules\
pm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:107
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "e:\\ProgramFiles\\nodejs\\node_modules\\npm\\node_modu
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd e:\yo\node_modules\grunt-browser-sync\node_modules\browser-sync\no
e_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client
node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
jit-grunt@0.9.1 node_modules\jit-grunt
</node></pre>

**Comment by justnull** [comment]
aflter I ...Upgrade finished. Your new npm version is 3.3.1. Have a nice day!
