### ISSUE TITLE
Trying to create an addon using C# and mono on OSX

### ISSUE THREAD

**Issue by logikaljay** [nodejs/node-gyp#710]
Bindings.gyp:
```
{
  'targets': [{
    'target_name': 'Test',
    'type': 'loadable_module',
    'actions': [{
      'action_name': 'compile',
      'inputs': [ ],
      'outputs': [ 'Test' ],
      'message': 'Building:',
      'action': ['mcs', 'test.cs', '-t:library', '-sdk:4.5']
    }]
  }]
}
```

test.cs:
```csharp
using System;

public class Test
{
  public Test()
  {
    Console.WriteLine("Hello world");
  }
}
```

test.js:
```javascript
var test = require('./build/Release/Test');
```

`node-gyp rebuild`:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.12.7 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jaybaker/Documents/Node/node-gyp-csharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jaybaker/.node-gyp/0.12.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jaybaker/.node-gyp/0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dmodule_root_dir=/Users/jaybaker/Documents/Node/node-gyp-csharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Circular Test <- Release/Test.node dependency dropped.
  ACTION Building: Test
  SOLINK_MODULE(target) Release/Test.node
gyp info ok 
```

`node test`:
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jaybaker/Documents/Node/node-gyp-csharp/test.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

I couldn't find a guide anywhere on google using Mono on OSX to make an addon, closest I could find was this guy: https://github.com/abe545/strider-msbuild-logger who does it with MSBuild - targeting .NET 2.0 which is a bit out of date now.

Am I wasting my time, or am I missing something pretty obvious?

https://twitter.com/logikaljay/status/639650966380265472

**Comment by rvagg** [comment]
the code you've linked to isn't an addon, it's using `spawn` to call a child process that's built by gyp, very different to an addon. unfortunately you need the symbols to line up properly to load an addon into Node and unless you can define some pretty low level c++ structures with your c# code I don't think this is going to be practical

**Comment by logikaljay** [comment]
Ah! I thought this would be too good to be true.

Thanks for your prompt reply.
