### ISSUE TITLE
node-gyp rebuild try to download iojs-v4.0.0.tar.gz that not exist

### ISSUE THREAD

**Issue by chhaj5236** [nodejs/node-gyp#719]
I upgraded nodejs to v4.0 and tried to install bson-ext where ```node-gyp rebuild``` was invoked during installing. It failed with ```Error: 404 status code downloading tarball```.  Then I ran node-gyp command manually and found that it tried to download iojs-v4.0.0 which is not existed. 

```
$/usr/local/bin/node /usr/local/lib/node_modules/tnpm/node_modules/pangyp/bin/node-gyp.js configure --fallback-to-build --module=/xxxxx/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/xxxxx/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release
gyp info it worked if it ends with ok
gyp info using pangyp@2.1.0
gyp info using node@4.0.0 | darwin | x64
gyp http GET https://iojs.org/dist/v4.0.0/iojs-v4.0.0.tar.gz
gyp http 404 https://iojs.org/dist/v4.0.0/iojs-v4.0.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/tnpm/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/tnpm/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/pangyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/xxxxx/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=/xxxxx/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release"
gyp ERR! cwd /xxxxx/node_modules/mongoose/node_modules/bson
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
```

Any solutions? Thanks~

**Comment by bnoordhuis** [comment]
Looks like a pangyp issue.  Try upgrading to the latest version, you're two minor releases behind.
