### ISSUE TITLE
TypeError in gyp when installing module

### ISSUE THREAD

**Issue by kiyanwang** [nodejs/node-gyp#721]
This has been working fine for some time but as of last night 

```
npm install iconv
npm http GET https://registry.npmjs.org/iconv
npm http 200 https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/iconv/-/iconv-2.1.10.tgz
npm http 200 https://registry.npmjs.org/iconv/-/iconv-2.1.10.tgz
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-2.0.9.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-2.0.9.tgz

> iconv@2.1.10 install /vagrant/talis/rl-app/node_modules/iconv
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Object 0.10.13 has no method 'slice'
gyp ERR! stack     at remove (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/remove.js:37:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as remove] (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at Gunzip.cb (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:33:20)
gyp ERR! stack     at Gunzip.EventEmitter.emit (events.js:117:20)
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:298:10)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "node" "/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/talis/rl-app/node_modules/iconv
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
unbuild iconv@2.1.10
npm ERR! weird error 7
npm ERR! not ok code 0
```

**Comment by rvagg** [comment]
this could be related to website issues we've just fixed @kiyanwang, try again and let us know if it's still having trouble

**Comment by kiyanwang** [comment]
@rvagg yup that seems to working again now thanks very much
