### ISSUE TITLE
node-gyp rebuild on Windows7 and VS2013

### ISSUE THREAD

**Issue by gussyboy** [nodejs/node-gyp#733]
I'm running Visual Studio Ultimate 2013 with update 5 and I'm getting the below issue on an npm install. I've noticed a few issues raised over the web for Windows 10 and VS 2015 but nothing related to what I'm experiencing.

Things to note are I'm using Node-v4.0.0 x86 and NPM 3.3.3 (going with that version of npm for the flat dependancies).

Has anyone come across anything similar? Any suggestions on the course or a fix?

```
> bufferutil@1.1.0 install C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\bufferutil
> node-gyp rebuild


C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(511,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected. [C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce. Checkout.Web.JsUnitTests\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.1.0 install C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\utf-8-validate
> node-gyp rebuild


C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(511,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected. [C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce. Checkout.Web.JsUnitTests\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
```

**Comment by bnoordhuis** [comment]
I'm going to guess that you need to pass `--msvs_version=2013` or set `GYP_MSVS_VERSION=2013` in the environment.

**Comment by gussyboy** [comment]
I've actually tried that with no success

**Comment by bnoordhuis** [comment]
Okay, noted.  What node-gyp (or rather, msbuild) is telling you that it can't find VS 2013, that's the 'v120' reference from the error message.

Make sure the environment is set up correctly, that you've run the envvars.bat from VS 2013, etc.  You may want to start the shell from the VS menu, it takes care of that.

**Comment by edmorley** [comment]
Even if this is a "environment wasn't set up correctly", please could we catch some of these errors / fail early, and output appropriate error messages? :-)

**Comment by jwuliger** [comment]
Having the same problem here as well.

**Anytime a packed requires a node-gyp rebuild I get:**
*Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?*

**Environment; Windows with all required prerequisites.**
*npm version:* 3.3.4
*node version:* 4.1.1
*node-gyp version:* 3.0.3

**Trying to install:**

- buffertools@2.1.3
- bcrypt@0.8.5

I really appreciate any help. Thanks.

**Output Stack:**

```
C:\API\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gy
p\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:122:23)
gyp ERR! stack     at C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:104:11
gyp ERR! stack     at F (C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:73:25)
gyp ERR! stack     at E (C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:76:29)
gyp ERR! stack     at C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jwuli\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\API\node_modules\buffertools
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:buffertools buffertools@2.1.3 install: `node-gyp rebuild`
npm WARN install:buffertools Exit status 1
```

**Comment by jwuliger** [comment]
I was able to fix my problem. I needed to run "npm install" from the VS2013 Commpand Prompt.

For anyone that needs to know how to find it, it is called "VS2013 x64 Cross Tools Command Prompt" Be sure to Run it as Admin.

**Comment by bnoordhuis** [comment]
> Even if this is a "environment wasn't set up correctly", please could we catch some of these errors / fail early, and output appropriate error messages?

There is no foolproof way for node-gyp to detect if a proper toolchain is available, except by actually running it.  At that point there isn't much you can do but print the error and abort.

**Comment by Overdrivr** [comment]
Could it be possible to have some sort of node-gyp.test() compiling some dummy file for ensuring tools are well configured ?

I'm facing the same issues than @gussyboy while installing strongloop for a good couple of days, and i'm still not yet sure what's wrong with my setup, if it's MS build tools, or if I need to use npm2, or something else

**Comment by bnoordhuis** [comment]
I don't see how that would help.  You won't get a better or different error message that way.

**Comment by LoveAndHappiness** [comment]
I've got the same error message, when trying to use `"browser-sync": "^2.9.12"`
```
D:\wamp\www\test10\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:122:23)
gyp ERR! stack     at C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:104:11
gyp ERR! stack     at F (C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:73:25)
gyp ERR! stack     at E (C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:76:29)
gyp ERR! stack     at C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Georg\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\wamp\www\test10\node_modules\bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.2.1 install D:\wamp\www\test10\node_modules\utf-8-validate
> node-gyp rebuild


D:\wamp\www\test10\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:122:23)
gyp ERR! stack     at C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:104:11
gyp ERR! stack     at F (C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:73:25)
gyp ERR! stack     at E (C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:76:29)
gyp ERR! stack     at C:\Users\Georg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Georg\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\wamp\www\test10\node_modules\utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
```

I have:
- node v4.2.1
- npm v3.3.6
- Microsoft Visual Studio Community 2013 with Update 5
- Microsoft Build Tools 2013

Any suggestions?

**Comment by hamxiaoz** [comment]
For anyone that's interested, I was trying to build electron and it fails on nslog, then I found this issue. I was able to build it using the  VS2013 Commpand Prompt.

**Comment by seriema** [comment]
I have both VS 2013 and 2015, so for me it failed because it was trying to load v140 and not finding it. I just set it to VS 2013 for now as our project still requires it. This fix doesn't seem to work for everyone, but make sure to set the right VS version (i.e. one you have):

    npm config set msvs_version 2013

**Comment by rvagg** [comment]
closing due to staleness, a lot has changed on the windows front since 2015
