### ISSUE TITLE
fatal error: 'errno.h' file not found

### ISSUE THREAD

**Issue by Macxim** [nodejs/node-gyp#741]
First, sorry if I'm not in the right repository.
Maybe I'm wrong but this looks like a `node-gyp` issue.

```bash
❯❯ npm install -g hexo-cli  
 
> fsevents@0.3.8 install /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:23:
In file included from /Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv.h:48:
/Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv-errno.h:25:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8
/Users/macxim/.nvm/versions/node/v0.12.7/bin/hexo -> /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli/bin/hexo
hexo-cli@0.1.8 /Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/hexo-cli
├── abbrev@1.0.7
├── minimist@1.2.0
├── bluebird@2.10.1
├── tildify@1.1.1 (os-homedir@1.0.1)
├── chalk@1.1.1 (supports-color@2.0.0, escape-string-regexp@1.0.3, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── hexo-fs@0.1.4 (escape-string-regexp@1.0.3, graceful-fs@4.1.2, chokidar@1.0.6)

```
I tried with `node -v v4.0.0` and `node -v v0.12.7`. Same results.
I found here https://github.com/npm/npm/issues/7533#issuecomment-77412460 that this may be related to Xcode, so I uninstalled Xcode 7 and reinstalled. Same results.

Any clue?

**Comment by rvagg** [comment]
what does `xcode-select -p` show? if it's not `/Applications/Xcode.app/Contents/Developer` then try `xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by Macxim** [comment]
It's weird because I remember running `xcode-select -p` and the result was `/Applications/Xcode.app/Contents/Developer` and I was still getting this fatal error.
Anyway, after running `xcode-select -s /Applications/Xcode.app/Contents/Developer` today, that seems to be fixed.  
Thank you @rvagg.

**Comment by Macxim** [comment]
Well, I'm afraid I'll have to reopen.
While `npm install -g hexo-cli` shows no error, `npm install` with the following package.json outputs an error.

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-server": "^0.1.2"
  }
}
```

Error:

```bash
❯ npm install             
\
> fsevents@0.3.8 install /Users/macxim/code/project.github.io/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:23:
In file included from /Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv.h:48:
/Users/macxim/.node-gyp/0.12.7/deps/uv/include/uv-errno.h:25:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/macxim/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macxim/code/project.github.io/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> dtrace-provider@0.6.0 install /Users/macxim/code/project.github.io/node_modules/hexo/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
npm WARN optional dep failed, continuing fsevents@0.3.8

```

**Comment by Macxim** [comment]
It affect my whole computer (Mac OS X 10.10.5).
For example in Atom, I have the following notice : 
`Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.`

The rebuild of the packages doesn't work:

```bash
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:23:
In file included from /Users/macxim/.atom/.node-gyp/.node-gyp/0.30.6/deps/uv/include/uv.h:48:
/Users/macxim/.atom/.node-gyp/.node-gyp/0.30.6/deps/uv/include/uv-errno.h:25:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macxim/.atom/packages/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/macxim/.atom/.apm/.apmrc" "--userconfig" "/Users/macxim/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macxim/.atom/packages/term2/npm-debug.log
```

**Comment by Macxim** [comment]
I have uninstalled Xcode with AppCleaner and then reinstalled from the AppStore.
I'm still stuck with this issue.

**Comment by bnoordhuis** [comment]
FWIW, I've had bug reports for some of my own modules from users where the homebrew node / npm / node-gyp was breaking the build, even when they thought they were using the upstream version.  Maybe try purging it?

**Comment by Macxim** [comment]
Alright. After reinstalling Xcode, I did the following:

Just in case I had installed the command line tools separately, I ran:
```bash
❯❯ rm -rf /Library/Developer/CommandLineTools
```

```bash
❯❯ xcode-select --install
xcode-select: note: install requested for command line developer tools
```
Click “Install” to download and install Xcode Command Line Tools.

Then, verify that you’ve successfully installed Xcode Command Line Tools:
```bash
❯ xcode-select -p                                  
/Applications/Xcode.app/Contents/Developer

❯ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

It seems to be working now.

**Comment by SaidBenaissa** [comment]
Hey.
Some one has a solution ?
I still have this error :
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/errno.h:31:15: fatal error: 'errno.h' file not found`
