### ISSUE TITLE
download error node.lin on windows 7 with VS2015

### ISSUE THREAD

**Issue by Mirodil** [nodejs/node-gyp#751]
```
> mmmagic@0.4.1 install D:\NodeJS\app\node_modules\mmmagic
> node-gyp rebuild


D:\NodeJS\app\node_modules\mmmagic>node "C:\Users\Mirodil\AppData\Roaming\np
m\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Mirodil\AppData\Roaming\npm\
node_modules\npm\node_modules\node-gyp\lib\install.js:369:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onResponse (C:\Users\Mirodil\AppData\Roaming\npm\n
ode_modules\npm\node_modules\request\request.js:1086:10)
gyp ERR! stack     at ClientRequest.g (events.js:260:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mirodil\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd D:\NodeJS\app\node_modules\mmmagic
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mirodil\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "mmmagic"
npm ERR! node v4.1.1
npm ERR! npm  v2.0.2
npm ERR! code ELIFECYCLE
npm ERR! mmmagic@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.4.1 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.
```

**Comment by GritBear** [comment]
seeing the same issue in gyp on Windows 10. Have already tried reinstall node, and node-gyp with no luck. It does not happen on Ubuntu server.

Is this a transient issue?

**Comment by bnoordhuis** [comment]
Update your copy of node-gyp (and probably npm as well.)  v1.0.2 is too old, latest at time of writing is v3.0.3.
