### ISSUE TITLE
Tests try to connect with wrong user

### ISSUE THREAD

**Issue by Suor** [nodejs/node-gyp#758]
I am trying to run tests with
```bash
make test-all connectionString=pg://postgres@localhost:5432/postgres
```
and also just
```bash
npm test
```
And both times I get:
```
130-tests.jsMessage: expected Error: Command failed: psql: FATAL:  role "suor" does not exist
 to be null
AssertionError: expected Error: Command failed: psql: FATAL:  role "suor" does not exist
 to be null
    at Function.assert.isNull (/home/suor/projects/node-postgres/test/test-helper.js:170:10)
    at /home/suor/projects/node-postgres/test/integration/gh-issues/130-tests.js:10:16
    at /home/suor/projects/node-postgres/test/test-helper.js:159:16
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```
Looks like it's trying to connect with current user instead of `postgres`.

**Comment by bnoordhuis** [comment]
Your issue looks completely unrelated to node-gyp.  Did you mean to report it against node-pg?

**Comment by Suor** [comment]
Hm, yes, sorry.
