### ISSUE TITLE
Node 4.1.2 moved SHASUMS.txt to SHASUMS256.txt causing build failures

### ISSUE THREAD

**Issue by nullivex** [nodejs/node-gyp#761]
I just ran into this today while working on trying to solve #679 

```
> bcrypt@0.8.5 install C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt
> node-gyp rebuild


C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt>node "C:\nodist\bin\node_
modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebui
ld
gyp http GET http://nodejs.org/dist/v4.1.2/node-v4.1.2.tar.gz
gyp http 200 http://nodejs.org/dist/v4.1.2/node-v4.1.2.tar.gz
gyp http GET http://nodejs.org/dist/v4.1.2/SHASUMS.txt
gyp http GET http://nodejs.org/dist/v4.1.2/SHASUMS.txt
gyp http GET http://nodejs.org/dist/v4.1.2/node.lib
gyp http GET http://nodejs.org/dist/v4.1.2/x64/node.lib
gyp http GET http://nodejs.org/dist/v4.1.2/node.lib
gyp http GET http://nodejs.org/dist/v4.1.2/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.1.2/SHASUMS.txt
gyp WARN install got an error, rolling back install
gyp http 404 http://nodejs.org/dist/v4.1.2/node.lib
gyp http 404 http://nodejs.org/dist/v4.1.2/SHASUMS.txt
gyp http 404 http://nodejs.org/dist/v4.1.2/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.1.2/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.1.2/node.lib
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading SHASUMS.txt
gyp ERR! stack     at Request.<anonymous> (C:\nodist\bin\node_modules\npm\node_m
odules\node-gyp\lib\install.js:316:18)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onResponse (C:\nodist\bin\node_modules\npm\node_mo
dules\request\request.js:832:10)
gyp ERR! stack     at ClientRequest.g (events.js:260:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\nodist\\v\\nodev4.1.2\\node.exe" "C:\\nodist\\bin\\node_mo
dules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 10.0.10240
npm ERR! command "C:\\nodist\\v\\nodev4.1.2\\node.exe" "C:\\nodist\\bin\\node_mo
dules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2015"
npm ERR! cwd C:\Users\JT4\WebstormProjects\oose
npm ERR! node -v v4.1.2
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\JT4\WebstormProjects\oose\npm-debug.log
npm ERR! not ok code 0
```

The best I can see as that this is the file we want: http://nodejs.org/dist/v4.1.2/SHASUMS256.txt

Okay, I solved this issue using the latest version of NPM.

Here were my install instructions.

Visit this page: https://github.com/npm/npm/releases
I grabbed 3.3.6 as it was the latest in the 3.x branch: https://github.com/npm/npm/archive/v3.3.6.tar.gz

Once I had that I installed it.

In my case, I am using nodist so I did the following

* Went to `C:\nodist\bin\node_modules\npm` and renamed it to `C:\nodist\bin\node_modules\npm_old`
* Created a new folder `C:\nodist\bin\node_modules\npm`
* Extracted the contents of the `npm-3.3.6` folder into `C:\nodist\bin\node_modules\npm`
* Went back to my project
* `npm install --msvs_version=2015` and the install worked successfully.

Here is my console output.

```
C:\nodist\bin\npm -> C:\nodist\bin\node_modules\npm\bin\npm-cli.js
npm@3.3.5 C:\nodist\bin\node_modules\npm

C:\Users\JT4\WebstormProjects\oose>*
'*' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\JT4\WebstormProjects\oose>
C:\Users\JT4\WebstormProjects\oose>npm -g install npm@3
module.js:338
    throw err;
    ^

Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\nodist\bin\node_modules\npm\node_modules\npmlog\lo
g.js:2:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

C:\Users\JT4\WebstormProjects\oose>npm -g install npm@3
module.js:338
    throw err;
    ^

Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\nodist\bin\node_modules\npm\node_modules\npmlog\lo
g.js:2:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

C:\Users\JT4\WebstormProjects\oose>
C:\Users\JT4\WebstormProjects\oose>npm -v
3.3.6

C:\Users\JT4\WebstormProjects\oose>npm install --msvs_version=2015

> bcrypt@0.8.5 install C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt
> node-gyp rebuild


C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt>if not defined npm_config
_node_gyp (node "C:\nodist\bin\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
..\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' to 'unsigne
d char', possible loss of data [C:\Users\JT4\WebstormProjects\oose\node_modules
\bcrypt\build\bcrypt_lib.vcxproj]
  win_delay_load_hook.c
     Creating library C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt\bu
  ild\Release\bcrypt_lib.lib and object C:\Users\JT4\WebstormProjects\oose\node
  _modules\bcrypt\build\Release\bcrypt_lib.exp
  Generating code
  Finished generating code
  bcrypt_lib.vcxproj -> C:\Users\JT4\WebstormProjects\oose\node_modules\bcrypt\
  build\Release\\bcrypt_lib.node
oose@1.4.0 C:\Users\JT4\WebstormProjects\oose
└─┬ bcrypt@0.8.5
  ├── bindings@1.2.1
  └── nan@2.0.5

npm WARN EPACKAGEJSON oose@1.4.0 No license field.

C:\Users\JT4\WebstormProjects\oose>
C:\Users\JT4\WebstormProjects\oose>
```

Devs, please close this I am adding it so it may help someone else resolve this issue.

**Comment by milimetric** [comment]
I have npm 3.10.6 and I'm using node-gyp to try and install node versions, and I still get:

"Error: 404 status code downloading SHASUMS.txt"

**Comment by milimetric** [comment]
I fixed it by upgrading node-gyp: `sudo npm i -g node-gyp`, which is now at version 3.4.0
