### ISSUE TITLE
Build Error - Label Unrecognised

### ISSUE THREAD

**Issue by fletchette** [nodejs/node-gyp#763]
Hello all,
Please be patient with me as I've tried as much as I can to fix this issue.

While compiling an example project (node-cpp-modules/01_bare_minimum) I am getting this error -

    (path)\modulename.vcxproj(3, 14): error MSB4066: The attribute "Label" in element <ItemGroup> is unrecognized.

My system
- Windows 8.1
- VS Express 2013
- Microsoft Visual C++ 2008 Express Edition
- 64 bit
- Windows SDK for Windows 7 and .NET Framework 4
- A bunch of random other patches that I've seen suggested everywhere (I've tried to remove most of them now so I can start fresh)
- I have tried compiling from both my usual CMD and *Visual Studio 2008 Command Prompt*

What's the solution to fix this error?
Thanks.

**Comment by bnoordhuis** [comment]
You need to make sure that VS 2013 is used for the build.  Pass `--msvs_version=2013` to node-gyp or set GYP_MSVS_VERSION=2013 in the environment and make sure you run vcvars.bat from VS 2013 as well.

**Comment by fletchette** [comment]
Ok, that fixed that error, but now:


```javascript
D:\git\node-cpp-modules\01_bare_minimum>node-gyp build --msvs_version=2013
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.1 | win32 | ia32
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  modulename.cpp
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(336): error C2988: unrecognizable template declaration/definition [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(336): error C2059: syntax error : 'using' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(469): error C2988: unrecognizable template declaration/definition [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(469): error C2059: syntax error : 'using' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(576): error C2061: syntax error : identifier 'WeakCallbackType' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(642) : see reference to class template instantiation 'v8::PersistentBase<T>' being compiled
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(637): error C2253: 'PersistentBase<T>' : pure specifier or abstract override specifier only allowed on virtual function [D:\git\node-cpp-modules\01_bare _minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(844): error C2253: 'Global<T>' : pure specifier or abstract override specifier only allowed on virtual function [D:\git\node-cpp-modules\01_bare_minimum \build\modulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(847) : see reference to class template instantiation 'v8::Global<T>' being compiled
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(852): error C2988: unrecognizable template declaration/definition [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(852): error C2059: syntax error : 'using' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(915): error C2989: 'v8::HandleScope' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\m odulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(319) : see declaration of 'v8::HandleScope'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(949): error C2989: 'v8::EscapableHandleScope' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimu m\build\modulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(135) : see declaration of 'v8::EscapableHandleScope'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(979): error C2989: 'v8::Data' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(74) : see declaration of 'v8::Data'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(1118): error C2989: 'v8::Script' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modul ename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(96) : see declaration of 'v8::Script'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(1559): error C2989: 'v8::StackTrace' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\m odulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(101) : see declaration of 'v8::StackTrace'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(1622): error C2989: 'v8::StackFrame' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\m odulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(100) : see declaration of 'v8::StackFrame'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2031): error C2989: 'v8::Value' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\module name.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(108) : see declaration of 'v8::Value'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2037): error C2989: 'v8::Primitive' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\mo dulename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(93) : see declaration of 'v8::Primitive'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2052): error C2989: 'v8::Boolean' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modu lename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(70) : see declaration of 'v8::Boolean'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2072): error C2989: 'v8::Name' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modulen ame.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(86) : see declaration of 'v8::Name'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2439): error C2989: 'v8::String' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modul ename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(102) : see declaration of 'v8::String'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2477): error C2989: 'v8::Symbol' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modul ename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(104) : see declaration of 'v8::Symbol'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2491): error C2989: 'v8::Number' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modul ename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(87) : see declaration of 'v8::Number'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2506): error C2989: 'v8::Integer' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modu lename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(82) : see declaration of 'v8::Integer'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2520): error C2989: 'v8::Int32' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\module name.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(81) : see declaration of 'v8::Int32'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2534): error C2989: 'v8::Uint32' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modul ename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(106) : see declaration of 'v8::Uint32'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2942): error C2989: 'v8::Object' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\modul ename.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(89) : see declaration of 'v8::Object'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(2971): error C2989: 'v8::Array' : class template has already been declared as a non-class template [D:\git\node-cpp-modules\01_bare_minimum\build\module name.vcxproj]
          c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(69) : see declaration of 'v8::Array'
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3181): error C2504: 'v8::Object' : base class undefined [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3188): error C2061: syntax error : identifier 'FunctionCallback' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3194): error C2061: syntax error : identifier 'FunctionCallback' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3205): error C2059: syntax error : 'return' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3205): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3210): error C2146: syntax error : missing ';' before identifier 'Call' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3216): error C2270: 'GetName' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3224): error C2270: 'GetInferredName' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3230): error C2270: 'GetDisplayName' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3236): error C2270: 'GetScriptLineNumber' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxpr oj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3241): error C2270: 'GetScriptColumnNumber' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcx proj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3246): error C2270: 'IsBuiltin' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3251): error C2270: 'ScriptId' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3257): error C2270: 'GetBoundFunction' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj] c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3259): error C2270: 'GetScriptOrigin' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3263): error C2059: syntax error : 'private' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3264): error C2059: syntax error : ')' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3273): error C2504: 'Object' : base class undefined [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3275): error C2504: 'Object' : base class undefined [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3281): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3281): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3281): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3282): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3282): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3283): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3288): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3288): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3288): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3294): error C2061: syntax error : identifier 'Local' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3296): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3296): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3296): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3298): error C2061: syntax error : identifier 'Local' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3300): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3300): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3300): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3302): error C2061: syntax error : identifier 'Value' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3306): error C2061: syntax error : identifier 'Value' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3316): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3316): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3316): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3317): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3317): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3318): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3321): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3321): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3321): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3322): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3322): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3323): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3326): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3326): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3326): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3327): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3327): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3328): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3336): error C2061: syntax error : identifier 'Value' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3340): error C2061: syntax error : identifier 'Value' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3357): error C2504: 'Object' : base class undefined [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3374): error C2628: 'ArrayBuffer::Allocator' followed by 'void' is illegal (did you forget a ';'?) [D:\git\node-cpp-modules\01_bare_minimum\build\module name.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3400): error C3861: 'data_': identifier not found [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3400): error C2461: 'Contents' : constructor syntax missing formal parameters [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3400): error C2059: syntax error : 'constant' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3400): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3400): error C2143: syntax error : missing ';' before '{' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3400): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj ]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3402): error C2059: syntax error : 'return' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3402): error C2238: unexpected token(s) preceding ';' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3403): error C2146: syntax error : missing ';' before identifier 'ByteLength' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3403): error C2270: 'ByteLength' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3403): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\git\node-cpp-modules\01_bare_minimum\build\modulena me.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3403): error C2065: 'byte_length_' : undeclared identifier [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3405): error C2059: syntax error : 'private' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3409): error C2255: 'friend' : not allowed outside of a class definition [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3410): error C2059: syntax error : '}' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3410): error C2143: syntax error : missing ';' before '}' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3416): error C2270: 'ByteLength' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3424): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3432): error C2143: syntax error : missing ';' before '<' [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3440): error C2270: 'IsExternal' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3445): error C2270: 'IsNeuterable' : modifiers not allowed on nonmember functions [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3478): error C2065: 'Value' : undeclared identifier [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3478): error C2065: 'obj' : undeclared identifier [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3478): error C2433: 'Cast' : '__forceinline' not permitted on data declarations [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxproj]
c:\users\notmyrealusername\.node-gyp\4.1.1\include\node\v8.h(3478): fatal error C1903: unable to recover from previous error(s); stopping compilation [D:\git\node-cpp-modules\01_bare_minimum\build\modulename.vcxpr oj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\notmyrealusername\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\notmyrealusername\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--msvs_version=2013"
gyp ERR! cwd D:\git\node-cpp-modules\01_bare_minimum
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
It looks like it's still picking up the wrong compiler.  The errors are basically the compiler not understanding C++11 code.

**Comment by fletchette** [comment]
Ok I fixed that up. I was using node-gyp build instead of node-gyp rebuild (herp derp.

Any ideas about this one? (this is the second example, these are unedited)
[Pastebin](http://pastebin.com/t4K4PUi3)

**Comment by bnoordhuis** [comment]
By the look of it, you're trying to compile an add-on that targets an older version of node, probably v0.10.

**Comment by fletchette** [comment]
Tried to compile the code from (here)[https://nodejs.org/api/addons.html#addons_hello_world] but I get those same sort of errors.

I'm running node v4.1.2
Am I missing something?

**Comment by fletchette** [comment]
Ok, thanks. Sorted it now that I'm using the correct examples.
Thanks for all the help.
