### ISSUE TITLE
Stuck with `node-gyp rebuild` failing on mac os x

### ISSUE THREAD

**Issue by pathakNishant** [nodejs/node-gyp#773]
```
└─(17:27:00 on master ✹)──> npm install                                                                                                                              ──(Fri,Oct16)─┘
npm WARN peerDependencies The peer dependency @lukekarrys/jade-runtime@^1.11.1 included from templatizer will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
\
> node-stringprep@0.7.2 install /Users/nishant.pathak/projects/chatclient-web/node_modules/stanza.io/node_modules/xmpp-jid/node_modules/node-stringprep
> node-gyp rebuild

  SOLINK_MODULE(target) Release/node_stringprep.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node_stringprep.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nishant.pathak/projects/chatclient-web/node_modules/stanza.io/node_modules/xmpp-jid/node_modules/node-stringprep
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
\
> iconv@2.1.11 install /Users/nishant.pathak/projects/chatclient-web/node_modules/jxt/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/iconv.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/iconv.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nishant.pathak/projects/chatclient-web/node_modules/jxt/node_modules/ltx/node_modules/node-expat/node_modules/iconv
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> fsevents@1.0.2 install /Users/nishant.pathak/projects/chatclient-web/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/nishant.pathak/projects/chatclient-web/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nishant.pathak/projects/chatclient-web/npm-debug.log
```

**Comment by pathakNishant** [comment]
tried updateding xcode, still no luck.

**Comment by chevex** [comment]
Same situation for me. Several of our dependencies fail to install in Node 4 because of `node-gyp rebuild` failures. I've tried lots of things. Re-installing node, re-installing NVM, re-installing homebrew entirely and then re-installing every last homebrew formula. I tried installing node manually. I tried updating Xcode. I've tried downgrading to 0.12, installing all the packages that fail to build in node 4, and then upgrading to node 4 for the rest. Seems we simply have to stay on 0.12 for our app to function, which is super frustrating :(

**Comment by chevex** [comment]
Here is the error output for one package I can reliably reproduce the failure for.

1. Create an empty directory to eliminate other dependencies as variables in this issue.

2. cd into that directory and run `npm install contextify`.

3. Note the following error output:

```
> contextify@0.1.14 install /Users/chev/code/sandbox/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chev/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chev/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/chev/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Value *volatile' from incompatible type 'v8::Context *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:267:10: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<v8::Context>' requested here
  return NanNew(val);
         ^
../src/contextify.cc:159:16: note: in instantiation of function template specialization '_NanEnsureLocal<v8::Local<v8::Context> >' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Context *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:159:16: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:7380:3: error: assigning to 'v8::Integer *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:211:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Integer>::Set<v8::Value>' requested here
            NanReturnValue(NanNew<Integer>(None));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:7380:3: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:225:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Boolean>::Set<v8::Value>' requested here
            NanReturnValue(NanNew<Boolean>(false));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/chev/.node-gyp/4.2.1/include/node/node.h:42:
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:7380:3: error: assigning to 'v8::Array *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/chev/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:236:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Array>::Set<v8::Value>' requested here
            NanReturnValue(blank);
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/chev/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/chev/.nvm/versions/node/v4.2.1/bin/node" "/Users/chev/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chev/code/sandbox/node_modules/contextify
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/chev/.nvm/versions/node/v4.2.1/bin/node" "/Users/chev/.nvm/versions/node/v4.2.1/bin/npm" "install" "contextify"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chev/code/sandbox/npm-debug.log
```

**Comment by Fishrock123** [comment]
> ld: library not found for -lgcc_s.10.5

@pathakNishant can you make sure you download the Xcode CLI tools from Apple's website? Something like: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by chevex** [comment]
My issue must be different. That error isn't in my error output and I do have the Xcode command line tools installed.

**Comment by bnoordhuis** [comment]
You may also have to do a full software update and a reboot.

**Comment by jamiedumont** [comment]
I'm suffering the same issues on El Cap with new Xcode 7 (and Command Line Tools) installed.

The rebuild errors are occurring specifically with packages `bufferutil@1.1.0` & `utf-8-validate@1.1.0` in my case with `Exit status 1`

**Comment by pathakNishant** [comment]
xcode-select is already install.
xcode-select version 2339.

**Comment by Kollibri** [comment]
I am getting the same error on El Capitan with Xcode 7 as well.  Any ideas how to fix this?

**Comment by pathakNishant** [comment]
@Kollibri great, it works. Thanks

**Comment by i5ting** [comment]
@Kollibri Thanks

**Comment by nmaxcom** [comment]
[**@Kollibri**](https://github.com/Kollibri) commented on [Oct 21, 2015, 6:06 PM GMT+2](https://github.com/nodejs/node-gyp/issues/773#issuecomment-149945986 "2015-10-21T16:06:34Z - Replied by Github Comment Enhancer"):
> Per [this](https://github.com/nodejs/node/issues/2933) issue, I was able to resolve this by entering this temp command:
> 
>     cd /usr/local/lib sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib

Worked great, thanks.

**Comment by delmartechdude** [comment]
@Kollibri Thank you so much! This saved me so much time.

**Comment by werkzeugh** [comment]
thanks also ! saved my day

**Comment by DrewWeth** [comment]
@Kollibri Thank you!!!

**Comment by treejanitor** [comment]
@Kollibri Thank you!  XCode once again poking a finger in my eye. ;-)

**Comment by joshkpeterson** [comment]
@Kollibri That's magic.

**Comment by abhi-mshetti** [comment]
@Kollibri +1. Thank you!

**Comment by freakynit** [comment]
This might also be helpful: http://stackoverflow.com/questions/21752172/invalid-deployment-target-for-stdlib-libc-on-osx-10-8

**Comment by amfarrell** [comment]
For me, this problem was solved by switching from python3 to legacy python2.7

**Comment by MehmetBal** [comment]
**to run both of them in sequence**
cd /usr/local/lib && sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib

**Comment by JamesMcGuigan** [comment]
This is what worked for me:

```
// package.json
{
  "resolutions": {
    "**/**/fsevents": "^1.2.9"
  }
}
```

**Comment by codelegant** [comment]
@Kollibri Thanks.

**Comment by idemax** [comment]
> 

Not working

**Comment by idemax** [comment]
face the same problem today
