### ISSUE TITLE
404 status code downloading 64-bit node.lib on win32?

### ISSUE THREAD

**Issue by s-a** [nodejs/node-gyp#778]
Currently the installation of all native modules fail on my windows 10 machine...

```bash
c:\git\electron-recompile>npm install ws
npm http GET https://registry.npmjs.org/ws
npm http 200 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/ws/-/ws-0.8.0.tgz
npm http 200 https://registry.npmjs.org/ws/-/ws-0.8.0.tgz
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/utf-8-validate
npm http 200 https://registry.npmjs.org/utf-8-validate
npm http 200 https://registry.npmjs.org/options
npm http 200 https://registry.npmjs.org/ultron
npm http 200 https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/options/-/options-0.0.6.tgz
npm http GET https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz
npm http GET https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-1.2.1.tgz
npm http GET https://registry.npmjs.org/bufferutil/-/bufferutil-1.2.1.tgz
npm http 200 https://registry.npmjs.org/options/-/options-0.0.6.tgz
npm http 200 https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz
npm http 200 https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-1.2.1.tgz
npm http 200 https://registry.npmjs.org/bufferutil/-/bufferutil-1.2.1.tgz
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-2.1.0.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-2.1.0.tgz

> bufferutil@1.2.1 install c:\git\electron-recompile\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\git\electron-recompile\node_modules\ws\node_modules\bufferutil>node "C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
gyp http 200 http://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp WARN install got an error, rolling back install
gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:313:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onResponse (C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:816:10)
gyp ERR! stack     at ClientRequest.g (events.js:260:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\git\electron-recompile\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok

> utf-8-validate@1.2.1 install c:\git\electron-recompile\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\git\electron-recompile\node_modules\ws\node_modules\utf-8-validate>node "C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
gyp http 200 http://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
gyp WARN install got an error, rolling back install
gyp http 404 http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:292:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onResponse (C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:816:10)
gyp ERR! stack     at ClientRequest.g (events.js:260:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\git\electron-recompile\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
ws@0.8.0 node_modules\ws
├── options@0.0.6
└── ultron@1.0.2
```

**Comment by s-a** [comment]
Weird that the log above shows ```gyp ERR! node-gyp -v v0.12.1```

When  i do ```node-gyp -v``` again it shows ```v3.0.3``` maybe some chrashed configuration on my machine?

**Comment by bnoordhuis** [comment]
I can't see it in the logs you pasted but am I right you're using an old version of npm?  It's probably using the node-gyp that's bundled with it, which is separate from the one you have installed globally.

**Comment by s-a** [comment]
I recently installed Node 4.2.1. I know that npm is bundled but not about node-gyp...

**Comment by bnoordhuis** [comment]
What does `npm -v` print?

**Comment by s-a** [comment]
1.3.17

**Comment by Fishrock123** [comment]
@s-a That's far too old of an npm. Only newer npm@2.6+ or so come tith the node-gyp fixes to make addons build properly with node v4.

**Comment by s-a** [comment]
So this is a problem in the current node setup bundle?

**Comment by bnoordhuis** [comment]
No, you have an old copy of npm on your path somewhere.  If you use the npm that came with v4.x, things should work fine.

**Comment by Fishrock123** [comment]
@s-a I don't think so, you should have gotten a new npm when you installed node 4.

Can you try uninstalling npm (`npm uninstall -g npm`) and then if that doesn't work (i.e. not two versions of npm) re-installing node?

**Comment by s-a** [comment]
crazy
```bash 
npm uninstall -g npm
unbuild npm@2.14.7
```
I uninstalled and reinstalled nodejs ... Still npm v1.3.17 :/

**Comment by Fishrock123** [comment]
@s-a you need to check you path for where npm@1.3.17 is.

**Comment by s-a** [comment]
:+1: ty for help. There was a second version at ```C:\Users\Stephan\AppData\Roaming\npm\npm``` I simply deleted this folder and ```npm -v``` is ```2.14.7``` now :smile: 

Now I have a flood of compiler errors during installation of native modules for example 
```bash
C:\Users\Stephan\.node-gyp\4.2.1\include\node\v8.h(3400): error C3861: "data_": not found. [...
```

I am using msvs 2010 c++ compiler. Do I need to upgrade?

**Comment by bnoordhuis** [comment]
> I d like to upgrade to c++ msvs2015. Is this already supported? 

Yes.

**Comment by s-a** [comment]
Ty to all, nice support here :+1: 
After 
 - deleting old npm files
- upgrading msvs c++ to 2015 community edition
- ```npm config set msvs_version=2015 --global```

Everything works fine :grinning:

**Comment by JoanClaret** [comment]
Same problem here: Error: 404 status code downloading 64-bit node.lib

**SO:** Windows 7
**Node version:** v4.3.1 (recently installed)
**NPM version:** 2.14.12

Solved with running same command: `npm config set msvs_version=2015 --global`
Thanks  @s-a  !!
