### ISSUE TITLE
MSBuild.exe failed with exit code: 1

### ISSUE THREAD

**Issue by incacola** [nodejs/node-gyp#786]
## Issue running npm install --save socket.io
======

Whilerunning npm install --save socket.io i had this error message after passing the node-gyp rebuild. 

      gyp ERR! build error
      gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
      gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
      gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
      gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
      gyp ERR! System Windows_NT 6.3.9600
      gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
      gyp ERR! cwd       c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
      gyp ERR! node -v v0.12.2
      gyp ERR! node-gyp -v v1.0.3
      gyp ERR! not ok
      npm WARN optional dep failed, continuing utf-8-validate@1.2.1

I did install everything that is needed for socket.io and for g-node-gyp.
* Python 2.7.10
* Microsoft Visual Studio C++ 2013 Express
* Windows 7 64-bit SDK

==============
And i set my Python config to Python 2.7.^ 
And still have this error Code why could that be?

**Comment by bnoordhuis** [comment]
You seem to have snipped the actual build error.  Can you post the full output?

**Comment by incacola** [comment]
```
$ npm install --save socket.io
/


> utf-8-validate@1.2.1 install c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

\
c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  validation.cc
     Bibliothek "c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\n
  ode_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf
  -8-validate\build\Release\validation.lib" und Objekt "c:\Users\felipe.gutierr
  ez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\eng
  ine.io\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.e
  xp" werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  validation.vcxproj -> c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeCha
  troom\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modu
  les\utf-8-validate\build\Release\\validation.node

> bufferutil@1.2.1 install c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  bufferutil.cc
     Bibliothek "c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\n
  ode_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\buf
  ferutil\build\Release\bufferutil.lib" und Objekt "c:\Users\felipe.gutierrez\D
  ocuments\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\engine.
  io\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp" werd
  en erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  bufferutil.vcxproj -> c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeCha
  troom\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modu
  les\bufferutil\build\Release\\bufferutil.node

> bufferutil@1.2.1 install c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  bufferutil.cc
     Bibliothek "c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\n
  ode_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cl
  ient\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.lib" un
  d Objekt "c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_m
  odules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\
  node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp" werden
  erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  bufferutil.vcxproj -> c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeCha
  troom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engin
  e.io-client\node_modules\ws\node_modules\bufferutil\build\Release\\bufferutil
  .node

> utf-8-validate@1.2.1 install c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  validation.cc
     Bibliothek "c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\n
  ode_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cl
  ient\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.lib
  " und Objekt "c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\no
  de_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cli
  ent\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.exp"
   werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targ
ets(607,5): error MSB6003: Die angegebene ausführbare Datei der Aufgabe "link.e
xe" konnte nicht ausgeführt werden. c:\Users\felipe.gutierrez\Documents\NodeDem
o\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_mod
ules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\Release
\obj\validation\validation.tlog\link-cvtres.write.[ID].tlog [c:\Users\felipe.gu
tierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\
socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf
-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\felipe.gutierrez\Documents\NodeDemo\04_NodeChatroom\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
socket.io@1.3.7 node_modules\socket.io
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── debug@2.1.0 (ms@0.6.2)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8.0)
└── socket.io-client@1.3.7 (to-array@0.1.3, indexof@0.0.1, debug@0.7.4, component-bind@1.0.0, object-component@0.0.3, backo2@1.0.2, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.4)
```

**Comment by bnoordhuis** [comment]
> error MSB6003: Die angegebene ausführbare Datei der Aufgabe "link.exe" konnte nicht ausgeführt werden.

msbuild is telling you it can't find the linker.  That probably means your Visual Studio is borked or not configured properly.  Make sure you run vcvarsall.bat that comes with VS.

> npm WARN optional dep failed, continuing utf-8-validate@1.2.1

It's an optional dependency however, so it probably doesn't matter.

**Comment by incacola** [comment]
Thanks i will trie that.

**Comment by bnoordhuis** [comment]
No problem.  Can you close the issue if you think it's resolved?

**Comment by incacola** [comment]
Hey tried it still not working and same error.

**Comment by bnoordhuis** [comment]
Maybe try googling that MSB6003 error code?  It's probably not an issue with node-gyp as such, more likely it's something local to your machine.
