### ISSUE TITLE
Problem using `node-gyp`

### ISSUE THREAD

**Issue by tunnckoCore** [nodejs/node-gyp#790]
Hi,
Cent OS 6.5 here and

```
[charlike@localhost ann]$ node-gyp --version
v3.0.3
[charlike@localhost ann]$ node --version
v4.0.0
[charlike@localhost ann]$ npm --version
3.3.2
```

trying to install some package that need `node-gyp` it fails. 

Currently failing install is `scissors`

```
[charlike@localhost ann]$ npm i scissors

> buffertools@2.1.3 install /home/charlike/ann/node_modules/buffertools
> node-gyp rebuild

make: Entering directory `/home/charlike/ann/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
In file included from /home/charlike/.node-gyp/4.0.0/src/node.h:42,
                 from ../buffertools.cc:17:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:336: error: expected unqualified-id before ‘using’
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:353: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:360: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:364: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:430: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: At global scope:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:469: error: expected unqualified-id before ‘using’
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:790: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:815: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:827: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: At global scope:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:852: error: expected unqualified-id before ‘using’
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:1089: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:1095: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:3205: error: ‘nullptr’ was not declared in this scope
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/charlike/.node-gyp/4.0.0/deps/v8/include/v8.h:7151: error: ‘nullptr’ was not declared in this scope
../buffertools.cc: At global scope:
../buffertools.cc:32: error: ‘v8::Handle’ has not been declared
../buffertools.cc:492: error: variable or field ‘RegisterModule’ declared void
../buffertools.cc:492: error: ‘Handle’ was not declared in this scope
../buffertools.cc:492: error: expected primary-expression before ‘>’ token
../buffertools.cc:492: error: ‘target’ was not declared in this scope
../buffertools.cc:506: error: ‘RegisterModule’ was not declared in this scope
../buffertools.cc:506: error: too many initializers for ‘node::node_module’
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
make: Leaving directory `/home/charlike/ann/node_modules/buffertools/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/charlike/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.23.4.el6.i686
gyp ERR! command "/home/charlike/.nvm/versions/node/v4.0.0/bin/node" "/home/charlike/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/charlike/ann/node_modules/buffertools
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN install:buffertools buffertools@2.1.3 install: `node-gyp rebuild`
npm WARN install:buffertools Exit status 1
npm WARN ENOENT ENOENT: no such file or directory, open '/home/charlike/ann/package.json'
npm WARN EPACKAGEJSON /home/charlike/ann No description
npm WARN EPACKAGEJSON /home/charlike/ann No repository field.
npm WARN EPACKAGEJSON /home/charlike/ann No README data
npm WARN EPACKAGEJSON /home/charlike/ann No license field.

```

thoughts? more things to show?

**Comment by bnoordhuis** [comment]
Make sure you use a C++11-capable compiler: g++ 4.8 or clang++ 3.4 o newer.

**Comment by tunnckoCore** [comment]
Huh, yes! Thanks!

**Comment by celesteking** [comment]
That means you need to use https://www.softwarecollections.org/en/docs/
