### ISSUE TITLE
node-gyp fails to build sqlite3 package with message that doesn't say what is wrong

### ISSUE THREAD

**Issue by yurivict** [nodejs/node-gyp#818]
There is no specific reason of failure in the log.
```
5861 info install tar-pack@2.0.0
5862 info postinstall tar-pack@2.0.0
5863 info install node-pre-gyp@0.6.14
5864 info postinstall node-pre-gyp@0.6.14
5865 info install sqlite3@3.1.1
5866 verbose unsafe-perm in lifecycle false
5867 info sqlite3@3.1.1 Failed to exec install script
5868 verbose stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
5868 verbose stack Exit status 1
5868 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
5868 verbose stack     at emitTwo (events.js:87:13)
5868 verbose stack     at EventEmitter.emit (events.js:172:7)
5868 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
5868 verbose stack     at emitTwo (events.js:87:13)
5868 verbose stack     at ChildProcess.emit (events.js:172:7)
5868 verbose stack     at maybeClose (internal/child_process.js:818:16)
5868 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
5869 verbose pkgid sqlite3@3.1.1
5870 verbose cwd /usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite
5871 error FreeBSD 10.2-STABLE
5872 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--loglevel" "warn"
5873 error node v4.2.1
5874 error npm  v2.14.7
5875 error code ELIFECYCLE
5876 error sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
5876 error Exit status 1
5877 error Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
5877 error This is most likely a problem with the sqlite3 package,
5877 error not with npm itself.
5877 error Tell the author that this fails on your system:
5877 error     node-pre-gyp install --fallback-to-build
5877 error You can get their info via:
5877 error     npm owner ls sqlite3
5877 error There is likely additional logging output above.
5878 verbose exit [ 1, true ]
```

Top-level command was 'npm rebuild' for etherpad-lite

**Comment by bnoordhuis** [comment]
The command that is executed is `node-pre-gyp install --fallback-to-build` but node-pre-gyp != node-gyp.

You should report this to the node-sqlite3 or the node-pre-gyp project.  The former is perhaps a better place to start because it's possible it configures node-pre-gyp in a way that obscures the error.
