### ISSUE TITLE
VS build error exit code 1 again

### ISSUE THREAD

**Issue by tenchugecko** [nodejs/node-gyp#820]
man why still this windows build error

I followed all the stuff posted here

might vs2008 redist be a problem?

installed: win7pro , VS2008, 2012,2013,2015 , win7.1sdk win81 sdk + update, python2.7.10+path to exe set
deinstalled 2010 redist's , but i did not get rid of the runtimes
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
70:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=G:\\_soundsets\\_projects\\SoundSetsWebAdmin\\sswa_sql\\
node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v47-win32-x64\\debug.node" "--module_name=debug" "--module_path=G:\\_
soundsets\\_projects\\SoundSetsWebAdmin\\sswa_sql\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v47-win32-x64"
gyp ERR! cwd G:\_soundsets\_projects\SoundSetsWebAdmin\sswa_sql\node_modules\v8-debug
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=G:\_soundsets\_project
s\SoundSetsWebAdmin\sswa_sql\node_modules\v8-debug\build\debug\v0.4.6\node-v47-win32-x64\debug.node --module_name=debug
--module_path=G:\_soundsets\_projects\SoundSetsWebAdmin\sswa_sql\node_modules\v8-debug\build\debug\v0.4.6\node-v47-win32
-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\_soundsets\_projects\SoundSetsWebAdmin\sswa_sql\node_modules
\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\_soundsets\\_projects\\SoundSetsWebAdmin\\sswa_sql\
\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd G:\_soundsets\_projects\SoundSetsWebAdmin\sswa_sql\node_modules\v8-debug
node-pre-gyp ERR! node -v v5.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.15
node-pre-gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
The module you're trying to install (v8-debug?) seems to be using node-pre-gyp, which is a different project than node-gyp.

If you have or had several versions of VS installed, make sure to read up on the `--msvs_version` switch described in the [README](https://github.com/nodejs/node-gyp/blob/master/README.md).

**Comment by bnoordhuis** [comment]
Closing, no activity and it's almost certainly not a node-gyp issue.  If I had to guess, I'd say that version of v8-debug is too old to work with node.js v5.x.
