### ISSUE TITLE
node-gyp rebuild error in Windows 7, msbuild.exe failed

### ISSUE THREAD

**Issue by luisamor** [nodejs/node-gyp#821]
- Windows 7
- node v5.1.0
- npm  v3.4.1
- node-gyp v3.0.3
- VS 2013 Express
- Microsoft Build Tools 2013

Previously i've done:
- npm config set python C:\Python27\python.exe --global
- npm install --msvs_version=2013

I tried npm install from "VS2013 x64 Cross Tools Command Prompt" but got same error

Here is the error output after "npm install":
```
ffi@1.2.5 install D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi
node-gyp rebuild

D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "C:\Users\username\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  dlfcn.c
  win_delay_load_hook.c
  dlfcn.vcxproj -> D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\Release\\dlfcn.lib
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.c
  ffi.vcxproj -> D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\Release\\libffi.lib
  pthread.c
  win_delay_load_hook.c
  pthread.vcxproj -> D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\Release\\pthread.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
d:\wf\mooverangapp\node_modules\exec-sync\node_modules\ffi\src\ffi.h(57): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (.. \src\threaded_callback_invokation.cc) [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
d:\wf\mooverangapp\node_modules\exec-sync\node_modules\ffi\src\ffi.h(57): error C2143: syntax error : missing ',' before '&' (..\src\threaded_callback_invokation.cc) [ D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
...
...
...
...
          c:\users\username\.node-gyp\5.1.0\include\node\v8.h(2078) : see declaration of 'v8::String'
..\src\ffi.cc(138): error C3861: 'NewSymbol': identifier not found [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
..\src\ffi.cc(139): error C2039: 'NewSymbol' : is not a member of 'v8::String' [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
          c:\users\username\.node-gyp\5.1.0\include\node\v8.h(2078) : see declaration of 'v8::String'
..\src\ffi.cc(139): error C3861: 'NewSymbol': identifier not found [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
..\src\ffi.cc(140): error C2039: 'NewSymbol' : is not a member of 'v8::String' [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
          c:\users\username\.node-gyp\5.1.0\include\node\v8.h(2078) : see declaration of 'v8::String'
..\src\ffi.cc(140): error C3861: 'NewSymbol': identifier not found [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
..\src\ffi.cc(141): error C2039: 'NewSymbol' : is not a member of 'v8::String' [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcxproj]
          c:\users\username\.node-gyp\5.1.0\include\node\v8.h(2078) : see declaration of 'v8::String'
..\src\ffi.cc(141): fatal error C1003: error count exceeds 100; stopping compilation [D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi\build\ffi_bindings.vcx proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\WF\myAppName\node_modules\exec-sync\node_modules\ffi
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\WF\myAppName\npm-debug.log
```

I really appreciate any help. Thanks.

**Comment by bnoordhuis** [comment]
Not a node-gyp issue.  You're trying to install a native module that is incompatible with newer versions of node.js.  Try installing ffi@2.0.0.  Good luck.
