### ISSUE TITLE
Node-Gyp Rebuild error during npm install

### ISSUE THREAD

**Issue by Chugot** [nodejs/node-gyp#832]
Hello,

I am a bit unsure where my problem lies as I am using a variety of technologies so please bear with me and feel free to direct me elsewhere if I am off-base.  I am working with the a package to connect to an oracle database (https://github.com/bchr02/node-oracledb).  Because of environmental issues, I will not have Visual Studio available for compilation, however this branch of node-oracledb has been setup to include pre-built binaries, so that only the redistributable is required.  I am able to successfully run npm install https://github.com/bchr02/node-oracledb into a folder and to execute a sample app, however my goal is to use the package in conjunction with Meteor.  

My understanding is that Meteor will not allow you to directly use an NPM package outside of a meteor package but I have succesfully used MeteorHacks/npm-container to use other node packages directly in my code.  However, I receive the following error when attempting to run my application with npm-container pointed to the oracledb package:

=> Errors prevented startup:

   While building package npm-container:
```
   error: couldn't install npm package oracledb@1.4.0: Command failed: npm http GET http://registry.npmjs.org/oracledb
   npm http 304 http://registry.npmjs.org/oracledb
   npm http GET http://registry.npmjs.org/oracledb/-/oracledb-1.4.0.tgz
   npm http 200 http://registry.npmjs.org/oracledb/-/oracledb-1.4.0.tgz
   npm http GET http://registry.npmjs.org/node-pre-gyp
   npm http 304 http://registry.npmjs.org/node-pre-gyp
   npm http GET http://registry.npmjs.org/nan
   npm http 304 http://registry.npmjs.org/nan
   gypnpm ERR! oracledb@1.4.0 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the oracledb@1.4.0 install script.
   npm ERR! This is most likely a problem with the oracledb package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get their info via:
   npm ERR!     npm owner ls oracledb
   npm ERR! There is likely additional logging output above.

   npm ERR! System Windows_NT 6.1.7601
   npm ERR! command "C:\\Users\\myuser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.9\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\myuser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.9\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb@1.4.0"
   npm ERR! cwd C:\Users\myuser\WebstormProjects\TemplateSandbox\app\packages\npm-container\.npm\package-new-1b74umj
   npm ERR! node -v v0.10.40
   npm ERR! npm -v 1.4.9
   npm ERR! code ELIFECYCLE
   npmnpm http GET http://registry.npmjs.org/oracledb
   npm http 304 http://registry.npmjs.org/oracledb
   npm http GET http://registry.npmjs.org/oracledb/-/oracledb-1.4.0.tgz
   npm http 200 http://registry.npmjs.org/oracledb/-/oracledb-1.4.0.tgz
   npm http GET http://registry.npmjs.org/node-pre-gyp
   npm http 304 http://registry.npmjs.org/node-pre-gyp
   npm http GET http://registry.npmjs.org/nan
   npm http 304 http://registry.npmjs.org/nan
   gypnpm ERR! oracledb@1.4.0 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the oracledb@1.4.0 install script.
   npm ERR! This is most likely a problem with the oracledb package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get their info via:
   npm ERR!     npm owner ls oracledb
   npm ERR! There is likely additional logging output above.

   npm ERR! System Windows_NT 6.1.7601
   npm ERR! command "C:\\Users\\myuser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.9\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\myuser\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.9\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb@1.4.0"
   npm ERR! cwd C:\Users\myuser\WebstormProjects\TemplateSandbox\app\packages\npm-container\.npm\package-new-1b74umj
   npm ERR! node -v v0.10.40
   npm ERR! npm -v 1.4.9
   npm ERR! code ELIFECYCLE
   npm
```
Again, I am a bit unsure where exactly my problem lies so this is my first query, if it appears I should be asking elsewhere please let me know!

Thanks in advance.

**Comment by bnoordhuis** [comment]
I speculate that you're missing the header files from the Oracle SDK but I can't say for sure.  What does npm-debug.log contain?

**Comment by Chugot** [comment]
I do not see a recent npm-debug.log being written to, however I have a similar result that I had received in the past when I was having trouble installing without the pre-built binaries: 
218 verbose linkBins oracledb@0.6.0
219 verbose linkMans oracledb@0.6.0
220 verbose rebuildBundles oracledb@0.6.0
221 verbose rebuildBundles [ 'nan' ]
222 info install oracledb@0.6.0
223 verbose unsafe-perm in lifecycle true
224 info oracledb@0.6.0 Failed to exec install script
225 verbose unlock done using C:\Users\myuser\AppData\Roaming\npm-cache\_locks\oracledb-938e9a1ec615a47b.lock for C:\Users\myuser\test-app\node_modules\oracledb
226 verbose stack Error: oracledb@0.6.0 install: `node-gyp rebuild`
226 verbose stack Exit status 1
226 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
226 verbose stack     at EventEmitter.emit (events.js:110:17)
226 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
226 verbose stack     at ChildProcess.emit (events.js:110:17)
226 verbose stack     at maybeClose (child_process.js:1015:16)
226 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
227 verbose pkgid oracledb@0.6.0
228 verbose cwd C:\Users\myuser\test-app
229 error Windows_NT 6.1.7601
230 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
231 error node v0.12.4
232 error npm  v2.10.1
233 error code ELIFECYCLE
234 error oracledb@0.6.0 install: `node-gyp rebuild`
234 error Exit status 1
235 error Failed at the oracledb@0.6.0 install script 'node-gyp rebuild'. 

Not sure if that is providing anything relevant, the messages prior to these seem to indicate success.

**Comment by bnoordhuis** [comment]
Unfortunately npm hides the real error.  The fact that it runs node-gyp means it thinks the module needs to be built but I understand that you're trying to use the precompiled module.  Not sure where to go from here, too many moving parts to say for sure where things go wrong.

**Comment by Chugot** [comment]
Thanks a lot for looking into it anyways, I had a feeling that was the case.  I opened an issue with the fork creator and will see if he has any thoughts, if I get back any pertinent info I will update this thread.

**Comment by sohilvshah** [comment]
Hi,

Have  you got resolution to your problem?
I am facing similar issue while installing node oracledb module.

Here is the log -
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\shahsv\Desktop\node app\node_modules\oracledb
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

**Comment by bnoordhuis** [comment]
Closing due to inactivity.
