### ISSUE TITLE
Node-Gyp Compilation error Node 4.23

### ISSUE THREAD

**Issue by donaldhook** [nodejs/node-gyp#836]
I am trying to install JT400 and am getting the following nan.h errors.  I am running on WIndows 10 x64 and have VS 2015 installed.  Any insight is greatly appreciated.
```
 declaration of 'node' (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2061: syntax error: identifier 'FreeCallback' (compiling source file
..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\j
400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2065: 'callback': undeclared identifier (compiling source file ..\sr
\methodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\n
de_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2065: 'hint': undeclared identifier (compiling source file ..\src\me
hodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_
odules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(78
): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all
the argument types (compiling source file ..\src\methodCallBaton.cpp) [C:\User
\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\java\build\nodejava
ridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_buffer.h(43): note: could be
  'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
 (compiling source file ..\src\methodCallBaton.cpp)
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_buffer.h(31): note: or
  'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::St
 ring>,node::encoding)' (compiling source file ..\src\methodCallBaton.cpp)
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 784): note: while trying to match the argument list '(v8::Isolate *, const ch
 ar *, uint32_t)' (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(78
): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to
v8::Local<v8::Object>' (compiling source file ..\src\methodCallBaton.cpp) [C:\
sers\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\java\build\node
avabridge_bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 788): note: No constructor could take the source type, or constructor overloa
 d resolution was ambiguous (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(79
): error C2039: 'Use': is not a member of 'node::Buffer' (compiling source fil
 ..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\
t400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_buffer.h(8): note: see decla
 ration of 'node::Buffer' (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(79
): error C3861: 'Use': identifier not found (compiling source file ..\src\meth
dCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_mo
ules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
4): error C2039: 'IsExternalAscii': is not a member of 'v8::String' (compiling
source file ..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\no
e_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C2039: 'ExternalAsciiStringResource': is not a member of 'v8::String
 (compiling source file ..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\Ro
ming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vc
proj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C4430: missing type specifier - int assumed. Note: C++ does not supp
rt default-int (compiling source file ..\src\methodCallBaton.cpp) [C:\Users\dh
ok\AppData\Roaming\npm\node_modules\jt400\node_modules\java\build\nodejavabrid
e_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C2143: syntax error: missing ';' before '*' (compiling source file .
\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt4
0\node_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C2065: 'ext': undeclared identifier (compiling source file ..\src\me
hodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_
odules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
6): error C2065: 'ext': undeclared identifier (compiling source file ..\src\me
hodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_
odules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
6): error C2039: 'GetExternalAsciiStringResource': is not a member of 'v8::Str
ng' (compiling source file ..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData
Roaming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings
vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\methodCallBaton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
7): error C2065: 'ext': undeclared identifier (compiling source file ..\src\me
hodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_
odules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
7): error C2227: left of '->data' must point to class/struct/union/generic typ
 (compiling source file ..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\Ro
ming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vc
proj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 2187): note: type is 'unknown-type' (compiling source file ..\src\methodCallB
 aton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
8): error C2065: 'ext': undeclared identifier (compiling source file ..\src\me
hodCallBaton.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_
odules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
8): error C2227: left of '->length' must point to class/struct/union/generic t
pe (compiling source file ..\src\methodCallBaton.cpp) [C:\Users\dhook\AppData\
oaming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.
cxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 2188): note: type is 'unknown-type' (compiling source file ..\src\methodCallB
 aton.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(12
): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function templat
 has already been defined (compiling source file ..\src\utils.cpp) [C:\Users\d
ook\AppData\Roaming\npm\node_modules\jt400\node_modules\java\build\nodejavabri
ge_bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 115): note: see declaration of '_NanEnsureLocal' (compiling source file ..\sr
 c\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(29
): error C2766: explicit specialization; 'v8::Local<v8::StringObject> NanNew<v
::StringObject,v8::Local<v8::String>>(v8::Local<v8::String>)' has already been
defined (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roami
g\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxpr
j]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 282): note: see previous definition of 'NanNew' (compiling source file ..\src
 \utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(31
): error C2995: 'v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>,v8::RegExp
:Flags)': function template has already been defined (compiling source file ..
src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_mod
les\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 301): note: see declaration of 'NanNew' (compiling source file ..\src\utils.c
 pp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(32
): error C2995: 'v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>,v8::RegExp
:Flags)': function template has already been defined (compiling source file ..
src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_mod
les\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 313): note: see declaration of 'NanNew' (compiling source file ..\src\utils.c
 pp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(50
): error C2039: 'ExternalAsciiStringResource': is not a member of 'v8::String'
(compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\n
de_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(50
): error C2065: 'ExternalAsciiStringResource': undeclared identifier (compilin
 source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_module
\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(50
): error C2065: 'resource': undeclared identifier (compiling source file ..\sr
\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_module
\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(50
): error C2433: 'NanNew': '__forceinline' not permitted on data declarations (
ompiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\nod
_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(50
): error C2365: 'NanNew': redefinition; previous definition was 'function' (co
piling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_
odules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(50
): error C2448: 'NanNew': function-style initializer appears to be a function
efinition (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roa
ing\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcx
roj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C3083: 'smalloc': the symbol to the left of a '::' must be a type (co
piling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_
odules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2039: 'FreeCallback': is not a member of 'node' (compiling source fi
e ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\nod
_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_object_wrap.h(8): note: see
 declaration of 'node' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2061: syntax error: identifier 'FreeCallback' (compiling source file
..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_
odules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2065: 'callback': undeclared identifier (compiling source file ..\sr
\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_module
\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(77
): error C2065: 'hint': undeclared identifier (compiling source file ..\src\ut
ls.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\ja
a\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(78
): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all
the argument types (compiling source file ..\src\utils.cpp) [C:\Users\dhook\Ap
Data\Roaming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_bin
ings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_buffer.h(43): note: could be
  'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
 (compiling source file ..\src\utils.cpp)
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_buffer.h(31): note: or
  'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::St
 ring>,node::encoding)' (compiling source file ..\src\utils.cpp)
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 784): note: while trying to match the argument list '(v8::Isolate *, const ch
 ar *, uint32_t)' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(78
): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to
v8::Local<v8::Object>' (compiling source file ..\src\utils.cpp) [C:\Users\dhoo
\AppData\Roaming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge
bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 788): note: No constructor could take the source type, or constructor overloa
 d resolution was ambiguous (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(79
): error C2039: 'Use': is not a member of 'node::Buffer' (compiling source fil
 ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node
modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\node_buffer.h(8): note: see decla
 ration of 'node::Buffer' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(79
): error C3861: 'Use': identifier not found (compiling source file ..\src\util
.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\java
build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
4): error C2039: 'IsExternalAscii': is not a member of 'v8::String' (compiling
source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules
jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C2039: 'ExternalAsciiStringResource': is not a member of 'v8::String
 (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\
ode_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C4430: missing type specifier - int assumed. Note: C++ does not supp
rt default-int (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppDat
\Roaming\npm\node_modules\jt400\node_modules\java\build\nodejavabridge_binding
.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C2143: syntax error: missing ';' before '*' (compiling source file .
\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_mo
ules\java\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
5): error C2065: 'ext': undeclared identifier (compiling source file ..\src\ut
ls.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\ja
a\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
6): error C2065: 'ext': undeclared identifier (compiling source file ..\src\ut
ls.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\ja
a\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
6): error C2039: 'GetExternalAsciiStringResource': is not a member of 'v8::Str
ng' (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\n
m\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\.node-gyp\5.1.1\include\node\v8.h(2078): note: see declaration
  of 'v8::String' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
7): error C2065: 'ext': undeclared identifier (compiling source file ..\src\ut
ls.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\ja
a\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
7): error C2227: left of '->data' must point to class/struct/union/generic typ
 (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\npm\
ode_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 2187): note: type is 'unknown-type' (compiling source file ..\src\utils.cpp)
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
8): error C2065: 'ext': undeclared identifier (compiling source file ..\src\ut
ls.cpp) [C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\ja
a\build\nodejavabridge_bindings.vcxproj]
:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(21
8): error C2227: left of '->length' must point to class/struct/union/generic t
pe (compiling source file ..\src\utils.cpp) [C:\Users\dhook\AppData\Roaming\np
\node_modules\jt400\node_modules\java\build\nodejavabridge_bindings.vcxproj]
 C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\nan\nan.h(
 2188): note: type is 'unknown-type' (compiling source file ..\src\utils.cpp)
yp ERR! build error
yp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
d with exit code: 1
yp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
pm\node_modules\node-gyp\lib\build.js:270:23)
yp ERR! stack     at emitTwo (events.js:87:13)
yp ERR! stack     at ChildProcess.emit (events.js:172:7)
yp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
.js:200:12)
yp ERR! System Windows_NT 6.3.9600
yp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
yp ERR! cwd C:\Users\dhook\AppData\Roaming\npm\node_modules\jt400\node_modules\
ava
yp ERR! node -v v5.1.1
yp ERR! node-gyp -v v3.0.3
yp ERR! not ok
pm WARN install:java@0.4.7 java@0.4.7 install: `node-gyp rebuild`
pm WARN install:java@0.4.7 Exit status 1
:\Users\dhook\AppData\Roaming\npm
── (empty)

pm ERR! code 1
```

**Comment by bnoordhuis** [comment]
Looks like jt400 needs to be updated or needs to update its dependencies. You should file an issue with that project.

**Comment by donaldhook** [comment]
Thanks
