### ISSUE TITLE
Unable to rum yo doctor on my Windows 8.1 Pro

### ISSUE THREAD

**Issue by amirlarco** [nodejs/node-gyp#859]
This is the result when I run npm install

$ npm install

> v8-debug@0.4.6 preinstall C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
>

> v8-profiler@5.2.12 preinstall C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler
>

> utf-8-validate@1.1.0 install C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
          C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(256) : see declaration of '_NanEnsureLocal'
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(661): error C2039: 'FreeCallback' : is not a member of 'node' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(661): error C2061: syntax error : identifier 'FreeCallback' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(665): error C2065: 'callback' : undeclared identifier [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(665): error C2065: 'hint' : undeclared identifier [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
          C:\Users\HP\.node-gyp\4.2.4\include\node\node_buffer.h(43): could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\HP\.node-gyp\4.2.4\include\node\node_buffer.h(31): or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(676): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(683): error C2039: 'Use' : is not a member of 'node::Buffer' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.1.0 install C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
          C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(256) : see declaration of '_NanEnsureLocal'
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(661): error C2039: 'FreeCallback' : is not a member of 'node' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(661): error C2061: syntax error : identifier 'FreeCallback' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(665): error C2065: 'callback' : undeclared identifier [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(665): error C2065: 'hint' : undeclared identifier [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
          C:\Users\HP\.node-gyp\4.2.4\include\node\node_buffer.h(43): could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\HP\.node-gyp\4.2.4\include\node\node_buffer.h(31): or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(676): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(683): error C2039: 'Use' : is not a member of 'node::Buffer' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0

> v8-profiler@5.2.12 install C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32\profiler.node --module_name=profiler --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32 )  else (node  configure --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32\profiler.node --module_name=profiler --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32 )

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32\profiler.node --module_name=profiler --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32 )  else (node  build --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32\profiler.node --module_name=profiler --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-ia32 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  profiler.cc
  cpu_profiler.cc
  cpu_profile.cc
  cpu_profile_node.cc
c:\users\hp\desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\node_modules\nan\nan_new.h(208): warning C4244: 'argument' : conversion from 'int64_t' to 'double', possible loss of data (..\src\cpu_profile.cc) [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler.vcxproj]
          ..\src\cpu_profile.cc(87) : see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,int64_t>(A0)' being compiled
          with
          [
              A0=int64_t
          ]
  heap_profiler.cc
  heap_snapshot.cc
  heap_output_stream.cc
  heap_graph_node.cc
  heap_graph_edge.cc
  win_delay_load_hook.c
     Creating library C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\Release\profiler.lib and object C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\Release\profiler.exp
  Generating code
  Finished generating code
  profiler.vcxproj -> C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\Release\\profiler.node
  Copying C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\Release\/profiler.node to C:/Users/HP/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-win32-ia32\profiler.node
          1 file(s) copied.

> v8-debug@0.4.6 install C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --module_name=debug --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32 )  else (node  configure --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --module_name=debug --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32 )

C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --module_name=debug --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32 )  else (node  build --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --module_name=debug --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  debug.cc
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
          C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(256) : see declaration of '_NanEnsureLocal'
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(661): error C2039: 'FreeCallback' : is not a member of 'node' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(661): error C2061: syntax error : identifier 'FreeCallback' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(665): error C2065: 'callback' : undeclared identifier [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(665): error C2065: 'hint' : undeclared identifier [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
          C:\Users\HP\.node-gyp\4.2.4\include\node\node_buffer.h(43): could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\HP\.node-gyp\4.2.4\include\node\node_buffer.h(31): or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(676): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(683): error C2039: 'Use' : is not a member of 'node::Buffer' [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\HP\\Desktop\\meanjs\\node_modules\\grunt-node-inspector\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v46-win32-ia32\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\HP\\Desktop\\meanjs\\node_modules\\grunt-node-inspector\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v46-win32-ia32"
gyp ERR! cwd C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --module_name=debug --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\HP\\Desktop\\meanjs\\node_modules\\grunt-node-inspector\\node_modules\\node-inspector\\node_modules\\v8-debug\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v4.2.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --module_name=debug --module_path=C:\Users\HP\Desktop\meanjs\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32' (1)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\HP\Desktop\meanjs\npm-debug.log

I am unable to run grunt this populates this error message

module.js:340
    throw err;
    ^

Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\HP\Desktop\meanjs\node_modules\grunt\lib\grunt.js:16:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
Why mean stack is too difficult to install on windows

**Comment by bnoordhuis** [comment]
Closing due to inactivity.  FWIW, the error messages suggest the module was written for an older version of node.js.
