### ISSUE TITLE
node-gyp doesn't handle '0.8.0-pre' version

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-gyp#86]
Hope it's not a dup, a quick skim of the open issues didn't turn up anything.

```
$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.5.2
gyp info using node@0.8.0-pre
gyp http GET http://nodejs.org/dist/v0.8.-1/node-v0.8.-1.tar.gz
gyp http 404 http://nodejs.org/dist/v0.8.-1/node-v0.8.-1.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error Error: 404 status code downloading tarball
gyp ERR! configure error     at Request.downloadError [as _callback] (/home/bnoordhuis/opt/node/lib/node_modules/node-gyp/lib/install.js:185:19)
gyp ERR! configure error     at Request.init.self.callback (/home/bnoordhuis/opt/node/lib/node_modules/node-gyp/node_modules/request/main.js:119:22)
gyp ERR! configure error     at Request.EventEmitter.emit (events.js:91:17)
gyp ERR! configure error     at Request.<anonymous> (/home/bnoordhuis/opt/node/lib/node_modules/node-gyp/node_modules/request/main.js:521:16)
gyp ERR! configure error     at Request.EventEmitter.emit (events.js:115:20)
gyp ERR! configure error     at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/home/bnoordhuis/opt/node/lib/node_modules/node-gyp/node_modules/request/main.js:483:14)
gyp ERR! configure error     at IncomingMessage.EventEmitter.emit (events.js:115:20)
gyp ERR! configure error     at IncomingMessage._emitEnd (http.js:366:10)
gyp ERR! configure error     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
gyp ERR! configure error     at Socket.socketOnData [as ondata] (http.js:1356:20)
gyp ERR! not ok 
```

That's with joyent/node@a1b2741.

**Comment by himanshuoodles** [comment]
I was also able to solve this by upgrading my version of node to a stable version (e.g. not a "pre" version - your version is 0.8.13-pre) with the following:

sudo npm install -g n # install node version manager "n"
sudo n stable # install the latest stable version of node
