### ISSUE TITLE
npm 'msnodesql' build is failing with C:\Protractor_Scripts\node_modules\msnodesql\build\sqlserver.vcxproj(20,3): err or MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found . Confirm that the path in the <Import> declaration is correct, and that the fi le exists on disk.

### ISSUE THREAD

**Issue by Dilip9922** [nodejs/node-gyp#862]
C:\Protractor_Scripts\node_modules\msnodesql>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.4 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\dredg\\AppData\\Roaming\\npm\\node_modules\\no
de-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Protractor_Scripts\\node_modules\\msnodesql\\build\\c
onfig.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dredg\\AppData\\Roaming\\npm\\node_modules\\no
de-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dredg\\.node-gyp\\4.2.4\\include\\node\\common
.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dredg\\.node-gyp\\4.2.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\dredg\\AppData\\Roaming\\npm\\n
ode_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Protractor_Scripts\\node_modules\\m
snodesql',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Protractor_Scripts\\node_modules\\msnodesql\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

C:\Protractor_Scripts\node_modules\msnodesql>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.4 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Protractor_Scripts\node_modules\msnodesql\build\sqlserver.vcxproj(20,3): err
or MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found
. Confirm that the path in the <Import> declaration is correct, and that the fi
le exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dredg\AppData\Roaming\npm\no
de_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dredg\\AppDat
a\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Protractor_Scripts\node_modules\msnodesql
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
Closing due to inactivity.  FWIW, that MSB4019 error usually means that you have conflicting SDKs installed.

**Comment by rbaprado** [comment]
I have this problem here as well, any tips on how to diagnose that?
