### ISSUE TITLE
Common.gypi not found on Windows 8.1

### ISSUE THREAD

**Issue by JonathanRowley** [nodejs/node-gyp#866]
Need help to get npm install working. I'm currently getting the following error:

```code
[15:11:33][npm install] gyp: C:\WINDOWS\system32\config\systemprofile\.node-gyp\5.4.1\include\node\common.gypi not found (cwd: C:\TeamCity\BuildAgent2\work\4ec0602c8cb635ea\client\ember-app\node_modules\bufferutil) while reading includes of binding.gyp while trying to load binding.gyp

[15:11:33][npm install] gyp ERR! configure error 

[15:11:33][npm install] gyp ERR! stack Error: `gyp` failed with exit code: 1

[15:11:33][npm install] gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)

[15:11:33][npm install] gyp ERR! stack     at emitTwo (events.js:87:13)

[15:11:33][npm install] gyp ERR! stack     at ChildProcess.emit (events.js:172:7)

[15:11:33][npm install] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

[15:11:33][npm install] gyp ERR! System Windows_NT 6.3.9600

[15:11:33][npm install] gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

[15:11:33][npm install] gyp ERR! cwd C:\TeamCity\BuildAgent2\work\4ec0602c8cb635ea\client\ember-app\node_modules\bufferutil

[15:11:33][npm install] gyp ERR! node -v v5.4.1

[15:11:33][npm install] gyp ERR! node-gyp -v v3.0.3

[15:11:33][npm install] gyp ERR! not ok 

[15:11:33][npm install] npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`

[15:11:33][npm install] npm WARN install:bufferutil@1.1.0 Exit status 1

```

I have installed Python and VS express 2013. No idea what I need to do now?

**Comment by Silvenga** [comment]
Same issue, and the file does exist. I wondering if it's a issue with Teamcity's isolation.

**Comment by Silvenga** [comment]
@JonRowley I fixed the above issue by changing the user that the TC agent is running as. I would imagine if there was a way to change the directory of `.node-gyp` from the default `~/` that would also fix it.

**Comment by bnoordhuis** [comment]
I'm going to assume that it's working now and that it wasn't an issue with node-gyp.  Can reopen if necessary.

**Comment by Silvenga** [comment]
@bnoordhuis I don't quite remember the original issue - however, I believe it could be resolved by allowing us to change the location of the `.node-gyp` directory. Right now `node-gyp` does not work under a Windows System user because of some strict permissions.

**Comment by bnoordhuis** [comment]
You can informally by setting HOME to an alternative directory (e.g. `env HOME=/path/to/devdir node-gyp rebuild`).  There's a pull request to add a `--devdir` flag (#540) but it seems to have stalled.

**Comment by bnoordhuis** [comment]
It's not hard to add so there: https://github.com/nodejs/node-gyp/pull/916

**Comment by mika-fischer** [comment]
@bnoordhuis Is there a way to pass down --devdir when all I'm doing is calling `npm install`?

I'm having the same issue that the CI is running as the system profile and it cannot access the files in `C:\WINDOWS\system32\config\systemprofile\.node-gyp`

**Comment by bnoordhuis** [comment]
@mika-fischer Yes, `npm install --devdir /path/to/dir`.
