### ISSUE TITLE
node-gyp failing on Win10 Fast Build 14251 x64

### ISSUE THREAD

**Issue by paulcbetts** [nodejs/node-gyp#875]
Seems to be a new regression - this will most likely be fixed by Windows, but I wanted to post it here in case someone else found it:

```
C:\Users\paulb\code\temp>npm install nslog

> nslog@3.0.0 install C:\Users\paulb\code\temp\node_modules\nslog
> node-gyp rebuild

C:\Users\paulb\code\temp\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\paulb\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0002: Failed to execute command: ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\CL.exe" @C:\Users\pa
ulb\AppData\Local\Temp\tmpae2d79d69fb940ad89f6168e72c59499.rsp". The handle is invalid. [C:\Users\paulb\code\temp\node_modules\nslog\build\
nslog.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\paulb\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14251
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\paulb\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\paulb\code\temp\node_modules\nslog
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON temp@1.0.0 No description
npm WARN EPACKAGEJSON temp@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14251
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\paulb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "nslog"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\paulb\code\temp\npm-debug.log
```

**Comment by winesociety** [comment]
I am receiving a very similar error. What can be done to resolve this?  It is preventing my workflow from building/installing dependencies from package.json

**Comment by fvpDev** [comment]
Same errors

**Comment by bnoordhuis** [comment]
Looking at the other issues, this appears to be fixed now.  Closing; can reopen if necessary, although it doesn't look like a node-gyp issue.

**Comment by dalper01** [comment]
please elaborate on the fix. I've been dealing with this for the past week
