### ISSUE TITLE
gyp ERR! - RaspberryPi

### ISSUE THREAD

**Issue by mrkd** [nodejs/node-gyp#887]
```
../node-dht-sensor.cpp:258:37: error: 'Nan::imp::FactoryBase<v8::Boolean>::return_t' has no member named 'ToLocalChecked'
../node-dht-sensor.cpp: At global scope:
../node-dht-sensor.cpp:288:11: error: variable or field 'Init' declared void
../node-dht-sensor.cpp:288:11: error: 'Handle' was not declared in this scope
../node-dht-sensor.cpp:288:24: error: expected primary-expression before '>' token
../node-dht-sensor.cpp:288:26: error: 'exports' was not declared in this scope
../node-dht-sensor.cpp:296:1: error: 'Init' was not declared in this scope
../node-dht-sensor.cpp:296:1: note: suggested alternative:
/home/pi/.node-gyp/5.7.0/include/node/node.h:184:18: note:   'node::Init'
node_dht_sensor.target.mk:88: recipe for target 'Release/obj.target/node_dht_sensor/node-dht-sensor.o' failed
make: *** [Release/obj.target/node_dht_sensor/node-dht-sensor.o] Error 1
make: Leaving directory '/home/pi/node-temperature-logger/node_modules/.staging/node-dht-sensor-07ec9ac4/build'

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v5.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13+
gyp ERR! command "/home/pi/.nvm/versions/node/v5.7.0/bin/node" "/home/pi/.nvm/versions/node/v5.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node-temperature-logger/node_modules/.staging/node-dht-sensor-07ec9ac4
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment]
Closing, not a node-gyp issue.  The package you're trying to install probably needs an update.
