### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by sdejanovic** [nodejs/node-gyp#899]
Hi,

I have an error:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Work\Float\DCA2\git\dca-2-0\html\node_modules\gulp-iconfont\node_modules\gulp-ttf2woff2\node_modules\ttf2woff2
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

Thank you in advance for your help.
Srdjan

**Comment by bnoordhuis** [comment]
Can you post the full output?  What are you trying to install / build?

**Comment by sdejanovic** [comment]
I fixed this issue with 
npm install --msvs_version=2013
instead of 
npm install
