### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by githubFree** [nodejs/node-gyp#904]
error logs like this
```
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
\
> lwip@0.0.7 install /data/tgideas/data/editor/site/node_modules/lwip
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/opt/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/opt/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 3.10.0-1-tlinux2_kvm_guest-0013.tl1
gyp ERR! command "node" "/opt/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/tgideas/data/editor/site/node_modules/lwip
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.0-1-tlinux2_kvm_guest-0013.tl1
npm ERR! argv "/opt/node-v0.12.2-linux-x64/bin/node" "/opt/node-v0.12.2-linux-x64/bin/npm" "install" "lwip@0.0.7"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/tgideas/data/editor/site/npm-debug.log
```

I don't know what happend to my program or system
Is there any way to reslove my trouble
thanks a lot

python version is 2.6

I have tried to upgrade python to 2.7, but nothing changed

**Comment by bnoordhuis** [comment]
Can you try upgrading to node.js v0.12.9?  It comes with node-gyp v3.0.3.  If that doesn't fix it, please post the contents of npm-debug.log.

**Comment by githubFree** [comment]
```
gyp ERR! configure error 
gyp ERR! stack Error: tunneling socket could not be established, cause=Parse Error
gyp ERR! stack     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
gyp ERR! stack     at ClientRequest.g (events.js:199:16)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:322:9)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! stack     at TCP.onread (net.js:540:20)
gyp ERR! System Linux 3.10.0-1-tlinux2_kvm_guest-0013.tl1
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/tgideas/data/editor/site/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```
still wrong

**Comment by githubFree** [comment]
I've found the reason。 my colleague set a wrong proxy for npm
thanks for @bnoordhuis
