### ISSUE TITLE
npm install error node-gyp rebuild

### ISSUE THREAD

**Issue by lisx** [nodejs/node-gyp#905]
```
node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:890:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:302:11)
gyp ERR! stack     at exports.spawn (child_process.js:367:9)
gyp ERR! stack     at exports.execFile (child_process.js:139:15)
gyp ERR! stack     at checkPythonVersion (/Users/lisx/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /Users/lisx/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:338:9
gyp ERR! stack     at /Users/lisx/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/which/which.js:79:20
gyp ERR! stack     at /Users/lisx/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /Users/lisx/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/lisx/.nvm/versions/node/v5.10.1/bin/node" "/Users/lisx/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lisx/Ducetech/ydxj/ydxj/node_modules/bufferutil
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 7
```

**Comment by bnoordhuis** [comment]
The EACCES error means node-gyp cannot execute `python` for some reason, probably because it's in an inaccessible directory or because it doesn't have the execute bit set.

I'll close, it's an issue local to your system, but feel free to ask more questions.
