### ISSUE TITLE
Wrong download link for RC 6

### ISSUE THREAD

**Issue by corbinu** [nodejs/node-gyp#907]
The install link for v6 RC2 is incorrect
```
node-gyp configure                                                                                                                     [15:12:49]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.0.0-rc.2 | darwin | x64
gyp http GET https://nodejs.org/download/release/v6.0.0-rc.2/node-v6.0.0-rc.2-headers.tar.gz
gyp http 404 https://nodejs.org/download/release/v6.0.0-rc.2/node-v6.0.0-rc.2-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download/release/v6.0.0-rc.2/node-v6.0.0-rc.2-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:95:20)
gyp ERR! stack     at Request.emit (events.js:182:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/node-gyp/node_modules/request/request.js:962:10)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at ClientRequest.emit (events.js:182:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:359:20)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/corbinu/Developer/git/couchnode
gyp ERR! node -v v6.0.0-rc.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

Should be https://nodejs.org/download/rc/v6.0.0-rc.2/node-v6.0.0-rc.2-headers.tar.gz
not https://nodejs.org/download/release/v6.0.0-rc.2/node-v6.0.0-rc.2-headers.tar.gz

Also is there some way to specify the URL manually? Don't see anything about it in the documentation.

**Comment by TheAlphaNerd** [comment]
Likely a wrong setting in ci

/cc @jasnell

**Comment by TBotV63** [comment]
This is also present in the latest nightly builds.

**Comment by xtaltas** [comment]
You can try the following option node-gyp configure **--dist-url**=https://nodejs.org/download/rc

**Comment by jbergstroem** [comment]
Yes, likely ci issue while passing vars to build -- `release_urlbase` needs to be changed if a job is manually.

**Comment by bnoordhuis** [comment]
Closing, not a node-gyp issue, see https://github.com/nodejs/node/issues/6237 and https://github.com/nodejs/node/issues/6312.
