### ISSUE TITLE
OSX 10.11.4 Can't complete the sudo npm install -g homebridge command

### ISSUE THREAD

**Issue by BuckarooToo** [nodejs/node-gyp#912]
(Continued from #872) - error when trying to install homebridge
[npm-debug.txt](https://github.com/nodejs/node-gyp/files/232473/npm-debug.txt)

Here is the terminal output:
```
$ sudo npm install -g homebridge
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.2.11 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 888
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/_username_/npm-debug.log
npm ERR! code 1


I had some difficulty initially installing node-gyp, but it ultimately worked, albeit with a number of warnings:

$ sudo npm install node-gyp
Password:
/Users/_username_ 
└─┬ node-gyp@3.3.1 
  └─┬ request@2.72.0
    └─┬ http-signature@1.1.1
      └─┬ sshpk@1.8.1 
        ├── assert-plus@1.0.0 
        ├─┬ ecc-jsbn@0.0.1 
        │ └── jsbn@0.0.0  (git+https://github.com/rynomad/jsbn.git#bb522b0124f75424f89d49446c40a87111942c7b)
        ├─┬ getpass@0.1.5 
        │ └── assert-plus@1.0.0 
        └── tweetnacl@0.13.3 

npm WARN enoent ENOENT: no such file or directory, open '/Users/_username_ /package.json'
npm WARN _username_ No description
npm WARN _username_  No repository field.
npm WARN _username_  No README data
npm WARN _username_  No license field.
$
```

**Comment by bnoordhuis** [comment]
The error suggests that your python binary is python3; node-gyp needs python2.  You can point it to a python2 binary with the `--python` switch or the `PYTHON` environment variable.

**Comment by BuckarooToo** [comment]
Not familiar with how to do that (I'll start looking), but can I point to python2 for npm, and still use python3 otherwise?

**Comment by BuckarooToo** [comment]
As it turns out, I'm on Python 2.5 (returned from python -V)

**Comment by bnoordhuis** [comment]
Ah, that's very ancient.  2.6 might work but I'd opt for 2.7.  To answer your other question, you can set it in your .npmrc (`npm config set python /path/to/python`).

**Comment by BuckarooToo** [comment]
Thank you! Updated to Python 2.7.11, and that did the trick!

**Comment by bnoordhuis** [comment]
Glad to hear it's working.  I'll close out the issue.
