### ISSUE TITLE
build fails on Raspberry Pi 2

### ISSUE THREAD

**Issue by dbahn25** [nodejs/node-gyp#917]
`node-gyp build` fails on raspberry pi 2. The code compiles without errors on Ubuntu 16.04 x86, but fails on the Raspi (both node-gyp version 3.0.3 and 3.3.1).

I also tried a different project than mine (https://github.com/lupomontero/node-cpphello) to rule out any errors in the code, same situation as before: builds on the PC but not on the raspi.

Error message: 

> gyp info it worked if it ends with ok
```

> gyp info using node-gyp@3.0.3
> gyp info using node@0.10.41 | linux | arm
> gyp info spawn make
> make: Entering directory '/tmp/node-cpphello/build'
> gyp info   CXX(target) Release/obj.target/cpphello/cpphello.o
> spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> ../cpphello.cpp:5:13: error: ‘v8::FunctionCallbackInfo’ has not been declared
> ../cpphello.cpp:12:18: error: ‘FunctionCallbackInfo’ does not name a type
> ../cpphello.cpp:12:18: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
> ../cpphello.cpp:12:38: error: expected ‘,’ or ‘...’ before ‘<’ token
> ../cpphello.cpp: In function ‘void cpphello::Foo(int)’:
> ../cpphello.cpp:13:24: error: ‘args’ was not declared in this scope
> ../cpphello.cpp:14:31: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
> ../cpphello.cpp: In function ‘void cpphello::Init(v8::Local<v8::Object>)’:
> ../cpphello.cpp:18:40: error: no matching function for call to ‘SetMethod(v8::Local<v8::Object>&, const char [4], void (&)(int))’
> ../cpphello.cpp:18:40: note: candidate is:
> /home/pi/.node-gyp/0.10.41/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
> cpphello.target.mk:84: recipe for target 'Release/obj.target/cpphello/cpphello.o' failed
> make: *** [Release/obj.target/cpphello/cpphello.o] Error 1
> make: Leaving directory '/tmp/node-cpphello/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:270:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
> gyp ERR! System Linux 4.1.13-v7+
> gyp ERR! command "node" "/usr/bin/node-gyp" "build"
> gyp ERR! cwd /tmp/node-cpphello
> gyp ERR! node -v v0.10.41
> gyp ERR! node-gyp -v v3.0.3
> gyp ERR! not ok 

```

**Comment by bnoordhuis** [comment]
That has nothing to do with node-gyp itself.  You're trying to build an add-on that isn't compatible with node.js v0.10.

**Comment by joshspivey** [comment]
@dbahn25 You need to install the v8 engine it cant access the libs for it....

@bnoordhuis has nothing to do with compatibility he's trying to run something that requires to be compiled using the V8 Engine. Node-gyp is a c++ compiler tool and ‘v8::FunctionCallbackInfo’ has not been declared  which means V8 is not imported...

**Comment by bnoordhuis** [comment]
@joshspivey Let me show you why that is wrong:
```
$ git show v0.10.0:deps/v8/include/v8.h | grep FunctionCallbackInfo | wc -l
0

$ git show v0.12.0:deps/v8/include/v8.h | grep FunctionCallbackInfo | wc -l
18
```
