### ISSUE TITLE
Error when deploy on openshift

### ISSUE THREAD

**Issue by SAudelOG** [nodejs/node-gyp#959]
I'm getting this error when I'm trying to deploy my application into openshift, it work locally but not in production, any thoughts about the possible issue?
```
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:
  git config --global push.default matching
To squelch this message and adopt the new behavior now, use:
  git config --global push.default simple
See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)
Warning: Permanently added 'service-rdygo.rhcloud.com' (RSA) to the list of known hosts.
Counting objects: 9, done.
Delta compression using up to 32 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (5/5), 405 bytes | 0 bytes/s, done.
Total 5 (delta 1), reused 4 (delta 0)
remote: CLIENT_RESULT: Application is already stopped.
remote: Building git ref 'master', commit d16178c
remote: npm WARN package.json rdygo-service@1.0.0 No repository field.
remote: 
remote: > bcrypt@0.8.7 install /var/lib/openshift/574e41b47628e1e93d000024/app-root/runtime/repo/node_modules/bcrypt
remote: > node-gyp rebuild
remote: 
remote: gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/var/lib/openshift/574e41b47628e1e93d000024/.node-gyp/5.11.1"
remote: gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
remote: gyp: /tmp/.node-gyp/5.11.1/common.gypi not found (cwd: /var/lib/openshift/574e41b47628e1e93d000024/app-root/runtime/repo/node_modules/bcrypt) while reading includes of binding.gyp while trying to load binding.gyp
remote: gyp ERR! configure error 
remote: gyp ERR! stack Error: `gyp` failed with exit code: 1
remote: gyp ERR! stack     at ChildProcess.onCpExit (/var/lib/openshift/574e41b47628e1e93d000024/app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
remote: gyp ERR! stack     at emitTwo (events.js:100:13)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
remote: gyp ERR! System Linux 2.6.32-573.22.1.el6.x86_64
remote: gyp ERR! command "/var/lib/openshift/574e41b47628e1e93d000024/app-root/data/.nodejs/bin/node" "/var/lib/openshift/574e41b47628e1e93d000024/app-root/data/.nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote: gyp ERR! cwd /var/lib/openshift/574e41b47628e1e93d000024/app-root/runtime/repo/node_modules/bcrypt
remote: gyp ERR! node -v v5.11.1
remote: gyp ERR! node-gyp -v v3.3.1
remote: gyp ERR! not ok 
remote: npm WARN rdygo-service@1.0.0 No repository field.
remote: npm ERR! Linux 2.6.32-573.22.1.el6.x86_64
remote: npm ERR! argv "/var/lib/openshift/574e41b47628e1e93d000024/app-root/data/.nodejs/bin/node" "/var/lib/openshift/574e41b47628e1e93d000024/app-root/data/.nodejs/bin/npm" "i" "--production"
remote: npm ERR! node v5.11.1
remote: npm ERR! npm  v3.9.5
remote: npm ERR! code ELIFECYCLE
remote: 
remote: npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
remote: npm ERR! Make sure you have the latest version of node.js and npm installed.
remote: npm ERR! If you do, this is most likely a problem with the bcrypt package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     node-gyp rebuild
remote: npm ERR! You can get information on how to open an issue for this project with:
remote: npm ERR!     npm bugs bcrypt
remote: npm ERR! Or if that isn't available, you can get their info via:
remote: npm ERR!     npm owner ls bcrypt
remote: npm ERR! There is likely additional logging output above.
remote: 
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     /var/lib/openshift/574e41b47628e1e93d000024/app-root/runtime/repo/npm-debug.log
remote: CLIENT_RESULT: Node.js modules installed.
remote: Preparing build for deployment
remote: Deployment id is 8d345043
remote: Activating deployment
remote: CLIENT_MESSAGE: Starting Node.js application...
remote: CLIENT_RESULT: Node.js application started.
remote: -------------------------
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success
To ssh://574e41b47628e1e93d000024@service-rdygo.rhcloud.com/~/git/service.git/
   f1c0e2d..d16178c  master -> master
Already up-to-date!
 HEAD detached at d16178c
 Untracked files:
   (use "git add <file>..." to include in what will be committed)

	.dpl/

nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (7f1252c885d8fce26f9ddf389d6729ff9274dbc8)
Done. Your build exited with 0.
```
here is the entire log in travis, https://travis-ci.org/Minisis/RdyGo-service

[bnoordhuis - fixed formatting]

**Comment by bnoordhuis** [comment]
It's clearly a permissions error.  I don't see anything that indicates it's a node-gyp issue.

**Comment by SAudelOG** [comment]
thanks, I will check with Openshift team
