### ISSUE TITLE
node-gyp rebuild error 2

### ISSUE THREAD

**Issue by rokyed** [nodejs/node-gyp#968]
```
gyp infomake: *** No rule to make target 'Release/obj.target/binding/src/binding.o', needed by 'Release/obj.target/binding.node'.  Stop.
make: Leaving directory '/var/www/myProject/backend/build'
 spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-24-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/myProject/backend
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

please help, I don't know what to do anymore... the config binding.gyp is the one from the Readme ( very basic )

**Comment by rokyed** [comment]
problem fixed canvas package it has mistakes ...
