### ISSUE TITLE
If node_modules is a symbol link, node-gyp fail to resolve path in include_dirs

### ISSUE THREAD

**Issue by hax** [nodejs/node-gyp#977]
If `node_modules` is a symbol link, node-gyp rebuild fails.

Sample error (`npm-symlink-0/node_modules` is a symbol link to `../npm-symbol-link-0-modules`):

```
> rm -rf node_modules/* && npm install


> canvas@1.4.0 install /Users/hax/r/sandbox/npm-symlink-test/npm-symlink-0/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
module.js:442
    throw err;
    ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at node.js:333:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/nvm/versions/node/v6.2.0/bin/node" "/usr/local/nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hax/r/sandbox/npm-symlink-test/npm-symlink-0-modules/canvas
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by hax** [comment]
Current workaround:

Make sure symbol link target path have a parent with the same name of package name.

For example,
```sh
ln -s  ../any_path/npm-symlink-0/any_path node_modules
```

**Comment by bnoordhuis** [comment]
That's not a node-gyp bug.  The binding.gyp of the module that you're trying to build executes `node -e 'require("nan")` and that is the command that fails, i.e., it's node's built-in require() function that chokes on the symlink.  Check the main nodejs/node bug tracker, there are a few open bugs about that.
