### ISSUE TITLE
cannot rebuild with node-gyp

### ISSUE THREAD

**Issue by MathijsvVelde** [nodejs/node-gyp#982]
OS: Windows 7 32-bit
Node: v6.2.2
Npm: v3.10.3
Node-gyp: v3.4.0

addition stuff installed:

- Visual C++ Build Tools
- .NET Frameworks 4.5.1
- Python 2.7

I got an error while installing a project:
```
C:\Users\Le-Me\Documents\Projects\Player-app\app>npm rebuild
npm WARN prefer global marked@0.3.5 should be installed with -g

> speaker@0.3.0 install C:\Users\Le-Me\Documents\Projects\Player-app\app\node_modules\speaker
> node-gyp rebuild


C:\Users\Le-Me\Documents\Projects\Player-app\app\node_modules\speaker>if not defined npm_config_node_gyp (node "
C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
rebuild )  else (node "" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn UNKNOWN
gyp ERR! stack     at exports._errnoException (util.js:1007:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:302:11)
gyp ERR! stack     at exports.spawn (child_process.js:383:9)
gyp ERR! stack     at exports.execFile (child_process.js:139:15)
gyp ERR! stack     at checkPythonVersion (C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp
\lib\configure.js:371:5)
gyp ERR! stack     at C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:33
8:9
gyp ERR! stack     at C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:88:20
gyp ERR! stack     at C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\ind
ex.js:44:5
gyp ERR! stack     at C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\win
dows.js:29:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\Le-Me\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Le-Me\Documents\Projects\Player-app\app\node_modules\speaker
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\Le-Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! speaker@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the speaker@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speaker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Le-Me\Documents\Projects\Player-app\app\npm-debug.log
```

I updated and reinstalled `node-gyp`, but I'm still getting that error.
Can you help me trying to fix this?

Thanks!!

**Comment by bnoordhuis** [comment]
The error indicates something went really wrong while trying to locate python.exe.  What happens when you pass `--python=\path\to\python.exe` on the command line?

**Comment by MathijsvVelde** [comment]
I think that worked, a little bit...
next error:
```
C:\Users\Le-Me\Documents\Projects\Player-App\app>npm rebuild --python=C:\Python27\python.exe
npm WARN prefer global marked@0.3.5 should be installed with -g

> speaker@0.3.0 install C:\Users\Le-Me\Documents\Projects\Player-App\app\node_modules\speaker
> node-gyp rebuild


C:\Users\Le-Me\Documents\Projects\Player-App\app\node_modules\speaker>if not defined npm_config_node_gyp (node "C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\Le-Me\Documents\Projects\Player-App\app\node_modules\speaker\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Le-Me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\Le-Me\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Le-Me\Documents\Projects\Player-App\app\node_modules\speaker
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\Le-Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--python=C:\\Python27\\python.exe"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! speaker@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the speaker@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speaker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Le-Me\Documents\Projects\Player-App\app\npm-debug.log
```

Thanks for the fast response!!

**Comment by MathijsvVelde** [comment]
https://github.com/nodejs/node-gyp/issues/972
That worked!!!
got npm version 3.10.5 now, not officially stable, but it works MAN!!!
:+1:
