### ISSUE TITLE
 fatal error C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by fanchou** [nodejs/node-gyp#985]
fatal error C1060: compiler is out of heap space

**Comment by bnoordhuis** [comment]
Guess it needs more memory, eh?  Closing, not a node-gyp issue.

**Comment by DininduWanniarachchi** [comment]
**Same for me..**

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@5.12.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\NVIDIA IN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\NODE_MODULE\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\NVIDIA IN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\NVIDIA IN\\.node-gyp\\5.12.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\NVIDIA IN\\.node-gyp\\5.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\NVIDIA IN\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\NODE_MODULE',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\NODE_MODULE\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  mit_custom.cc
  win_delay_load_hook.cc
D:\NODE_MODULE\node_modules\nan\nan.h(72): fatal error C1060: compiler is out of heap space (..\mit_custom.cc) [D:\NODE_MODULE\build\mit_custom.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\NVIDIA IN\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\NVIDIA IN\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\NODE_MODULE
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```
